### ISSUE TITLE
Create user API for specifying tabular data to be written back to Impala

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#10]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Tuesday Dec 09, 2014 at 20:11 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/10_

---

User-defined aggregations right now will have their results stored as pickled Python objects in the column of a result set / new Impala table. We might wish to eventually emit data that Impala can recognize as a primitive tuple or a batch of rows that can be worked with independent of Python.

**Comment by cpcloud** [comment]
Closing as wontfix.
