### ISSUE TITLE
API: multiple column aggregation

### ISSUE THREAD

**Issue by chris-b1** [ibis-project/ibis#1002]
using #981 - setup:

```python
df = pd.DataFrame({'key': [1, 2, 3] * 100, 
                   'value1': range(300), 
                   'value2': np.linspace(0, 100, num=300), 
                   'date': pd.date_range('2010-01-01', periods=300)})
from ibis.pandas.api import connect
client = connect({'df': df})
t = client.table('df')
ibis.options.interactive = True
```

One piece of API I found cumbersome was doing multiple column aggregations.  E.g., in pandas
```python
In [16]: df.sum()
Out[16]: 
key         600.0
value1    44850.0
value2    15000.0
dtype: float64

In [17]: df.groupby('key').sum()
Out[17]: 
     value1       value2
key                     
1     14850  4966.555184
2     14950  5000.000000
3     15050  5033.444816
```

If I understand correctly, in ibis this is (first case isn't implemented yet):
```python

In [20]: t.aggregate([t.value1.sum().name('value1'), t.value2.sum().name('value2')])

In [21]: (t.groupby(t.key)
           .aggregate([t.value1.sum().name('value1'), t.value2.sum().name('value2')]))
Out[21]: 
   key  value1       value2
0    1   14850  4966.555184
1    2   14950  5000.000000
2    3   15050  5033.444816
```

So maybe there is a nicer way of doing this?  Of course pandas is being a bit magical here by automatically dropping non-numeric columns.

**Comment by cpcloud** [comment]
The first (summing all the numeric columns of a table) is not implemented. I'm not sure if we want to implement it. I actually wouldn't be opposed to making it easier to apply a reduction across a set of columns + an API for selecting columns of particular generic types (similar to `select_dtypes` in pandas).

Something like:

```python
import ibis.expr.datatypes as dt

proj = t.columns_with_type(dt.number)  # I don't think number exists yet
proj.sum()
```

Regard the aggregations, it's hopefully a little less cumbersome to do it this way:

```python
t.groupby(t.key).aggregate(value1=t.value1.sum(), value2=t.value2.sum())
```

**Comment by chris-b1** [comment]
Seems like a good idea!  I wouldn't mind being explicit selecting numeric columns, it's more the repeated `t.col1.sum(), t.col2.sum() ...`, that felt verbose.

**Comment by cpcloud** [comment]
Ah got it.

There's also a slightly simpler way to aggregate a bunch of columns with the same name, which I failed to mention: Tables have an `aggregate` method.

```python
t.aggregate([t[c].sum().name(c) for c in ('value1', 'value2')])
```

Still, `t.columns_with_type(dt.number).sum()` might be a nice way to make that more convenient.

**Comment by cpcloud** [comment]
Would happily accept a PR for anything discussed here to make it easier.
