### ISSUE TITLE
bug: `table[_.mycol]` results in Table (`table["mycol"]` results in Column as expected)

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#10034]
### What happened?

```python
import ibis
from ibis import _

t = ibis.memtable({"a": [1, 2, 3]})
# I would expect these both to be columns
print(type(t["a"]))  # <class 'ibis.expr.types.numeric.IntegerColumn'>
print(type(t[_.a]))  # <class 'ibis.expr.types.relations.Table'>
# I would expect these both to be tables
print(type(t.select("a")))  # <class 'ibis.expr.types.relations.Table'>
print(type(t.select(_.a)))  # <class 'ibis.expr.types.relations.Table'>
```

I bet the Deferred is getting interpreted as a boolean, which is then treated as a filter condition.

### What version of ibis are you using?

main, 92e88f05afca6c10a34b399a43c75deae2d1e593

### What backend(s) are you using, if any?

duckb, but probably the same for all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
This isn't a bug, but is intended behavior.

In _most_ ibis APIs, `table.some_method("column_name")` and `table.some_method(table.column_name)` have the same effect. But in `table[...]` they don't.

- Passing in a column name (or integer index) selects out the column (returning a `Column`).
- Passing in multiple column names (or indices) selects multiple columns (returning a `Table`).
- Passing in a `slice` does a `limit` with `offset` (returning a `Table`)
- Passing in one or more boolean columns filters by those columns (returning a `Table`).
- Passing in one or more other column expressions selects those columns (returning a `Table`).

In ibis, `_.column_name` always desugars to the same thing as `t.column_name`, so you're seeing the last behavior. This is also documented in the docstring:

```
        Table | Column
            The return type depends on the input. For a single string or int
            input a column is returned, otherwise a table is returned.
```

Personally, I find this `__getitem__` behavior a bit magical, and would advocate for deprecating and dropping the last two options entirely in favor of `filter` and `select` respectively.

**Comment by cpcloud** [comment]
I thought we had an issue to track the deprecation of über magical `__getitem__`. Let me see if I can find it.

**Comment by cpcloud** [comment]
https://github.com/ibis-project/ibis/discussions/7259

**Comment by jcrist** [comment]
Writing one up now.

**Comment by jcrist** [comment]
https://github.com/ibis-project/ibis/issues/10045
