### ISSUE TITLE
API: Unnamed columns should have a default name

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1003]
Operations like `t.a.sum()`, and `t.b.sum()` cannot be used without naming in aggregations:

```python
In [17]: import ibis

In [18]: t = ibis.table([('a', 'int64'), ('b', 'double')], name='t')

In [19]: t.aggregate(t.a.sum(),t.b.sum())
---------------------------------------------------------------------------
IntegrityError                            Traceback (most recent call last)
<ipython-input-19-188a6271c198> in <module>()
----> 1 t.aggregate(t.a.sum(),t.b.sum())

/home/phillip/Documents/code/py/ibis/ibis/expr/api.py in aggregate(table, metrics, by, having, **kwds)
   1984         metrics.append(v.name(k))
   1985
-> 1986     op = table.op().aggregate(table, metrics, by=by, having=having)
   1987     return TableExpr(op)
   1988

/home/phillip/Documents/code/py/ibis/ibis/expr/operations.py in aggregate(self, this, metrics, by, having)
     40
     41     def aggregate(self, this, metrics, by=None, having=None):
---> 42         return Aggregation(this, metrics, by=by, having=having)
     43
     44     def sort_by(self, expr, sort_exprs):

/home/phillip/Documents/code/py/ibis/ibis/expr/operations.py in __init__(self, table, metrics, by, having, predicates, sort_keys)
   1846                                   self.sort_keys])
   1847
-> 1848         schema = self._result_schema()
   1849         HasSchema.__init__(self, schema)
   1850

/home/phillip/Documents/code/py/ibis/ibis/expr/operations.py in _result_schema(self)
   1904             types.append(e.type())
   1905
-> 1906         return Schema(names, types)
   1907
   1908     def sort_by(self, expr, sort_exprs):

/home/phillip/Documents/code/py/ibis/ibis/expr/datatypes.py in __init__(self, names, types)
     37
     38         if len(self._name_locs) < len(self.names):
---> 39             raise com.IntegrityError('Duplicate column names')
     40
     41     def __repr__(self):

IntegrityError: Duplicate column names
```

It's easy to make the default name be the operation's column's name in many cases. Operations with multiple inputs (such as `Add`) are trickier. Here are the cases:

1. `Op(a, a)`. This is simple, the result's name is `a`
1. `Op(a, None)` or `Op(None, a)`. Also simple, the result's name is `a`
1. `Op(a, not a)`. This should fail

Alternatively, we could bake some simple expression representation into the column name. Impala is an example of a database that does this:

```sh
[localhost:21000] > select 1 + 1 < 3;
+-----------+
| 1 + 1 < 3 |
+-----------+
| true      |
+-----------+
```

We could potentially make ambiguously named columns' names something similar such as:

```python
'_'.join([type(op).__name__.lower()] + [arg.name.lower() for arg in op.args])
```

So, `t.a + t.b` without an explicit name specified would have the name `add_a_b`.

@wesm @chris-b1 thoughts?

**Comment by chris-b1** [comment]
+1 that reductions carry the name forward, I was surprised this wasn't the case.

I don't feel strong on the multiple inputs cases - I could see in interactive work where it would be nice that expressions don't necessarily need a name assigned, so something like you proposed seem pretty reasonable.

**Comment by cpcloud** [comment]
I don't know if this is still a reasonable thing to do. The only case where this matters is the root of an expression tree, so giving everything a default name seems overkill.
