### ISSUE TITLE
DOC: Remove CLA requirement and associated language

### ISSUE THREAD

**Issue by djKooks** [ibis-project/ibis#1004]
I'm looking on CLA guide, and the mail address to send form are same as Impala(cla@cloudera.com).
Is mail address still same?

**Comment by wesm** [comment]
Since we moved the repo, I don't think we need to do CLAs anymore. We should revise the documentation about this

**Comment by djKooks** [comment]
@wesm Thanks! I'll close this one after document has been updated.
