### ISSUE TITLE
bug: BigQuery create table with expiration timestamp option seems to not work

### ISSUE THREAD

**Issue by brentgunderson** [ibis-project/ibis#10043]
### What happened?

When I try to add an expiration timestamp to a BigQuery table, I seem to get an error

```python
from datetime import datetime, timedelta
 
import ibis
import pandas as pd
 
ibq = ibis.bigquery.connect()
 
expiration_timestamp = datetime.now() + timedelta(days=7)
expiration_timestamp_string = expiration_timestamp.strftime("%Y-%m-%d %H:%M:%S")
 
df = pd.DataFrame(
    {
        "Name": ["Alice", "Bob", "Charlie", "David"],
        "Age": [25, 30, 35, 40],
        "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    }
)
 
ibq.create_table(
    "simple_table",
    obj=df,
    overwrite=True,
    database="*****",
    options={"expiration_timestamp": expiration_timestamp},
)
``` 

In the below logs, I seem to get the first coercion-type error with the expiration_timestamp variable.

If I use the expiration_timestamp_string variable, the python job hangs but I can get the information pasted in via the BigQuery web UI. Does BigQuery expect something like this (https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#table_option_list): 

```
expiration_timestamp=TIMESTAMP "2025-01-01 00:00:00 UTC"
```

### What version of ibis are you using?

9.4.0

### What backend(s) are you using, if any?

BigQuery

### Relevant log output

```sh
BadRequest: 400 Option expiration_timestamp value has type DATETIME which cannot be coerced to expected type TIMESTAMP;
failed to set 'expiration_timestamp' in OPTIONS() at [1:108]; reason: invalidQuery

  
An internal error occurred and the request could not be completed.
This is usually caused by a transient issue.
Retrying the job with back-off as described in the BigQuery SLA should solve the problem: https://cloud.google.com/bigquery/sla.
If the error continues to occur please contact support at https://cloud.google.com/support. Error: 80038528
 
 
CREATE OR REPLACE TABLE `*****`.`****`.`simple_table`
OPTIONS (expiration_timestamp='2024-09-13 08:51:08') AS
SELECT *
FROM `*****`.`*****`.`ibis_pandas_memtable_ikhe6exvy5dlfmaqtshvx47kx4`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I believe BigQuery requires a UTC offset for `expiration_timestamp`, and in general differentiates between `DATETIME` (which has no timezone) and `TIMESTAMP` (which is always UTC).
