### ISSUE TITLE
API: input of 'timestamp'

### ISSUE THREAD

**Issue by djKooks** [ibis-project/ibis#1005]
Hello. 
As I test, code below causes error.

```
ibis.timestamp(100000)    # => works fine
ibis.timestamp('100000')    # => not works
```

But inside timestamp API, it looks like it does not ignore string value.
If I'm right, isn't `api.py` needs to be changed like below? 
I'm not sure about the concept of this API. Please look on.

```
...
def timestamp(value):
    if isinstance(value, py_string):
        from pandas import Timestamp
        value = Timestamp(int(value))
...
```

**Comment by cpcloud** [comment]
Hi @djKooks. Thanks for raising an issue. I agree this is confusing. This function is calling `pandas.Timestamp`, so its behavior is dependent on the `pandas.Timestamp` constructor. We can't simply convert digit strings to integers, because other strings such `'now'`, and `'2017-04-01'` are also acceptable. Neither of those can be converted to `int`s directly.

I think the solution is here is probably to check `my_string.isdigit()` and call in on the object that's `True`.

**Comment by jreback** [comment]
@cpcloud i would have additional rules here
Time stamp can convert strings (datetime like), strings like now 

ints are only acceptable with a unit (default is ns) so prob don't want that actually in the default rule

**Comment by cpcloud** [comment]
@jreback Since we don't allow users to pass in units, `1000` and `'1000'` would have the same meaning. We already allow `1000` as an int, with the default interpretation of the unit as nanoseconds. There's no possible ambiguity with `'1000'`.

**Comment by cpcloud** [comment]
Or are you saying that integers shouldn't be allowed at all?

**Comment by cpcloud** [comment]
We actually don't have a test for raw `int`s unfortunately.

@wesm Any objections to deprecating passing `int` to `ibis.timestamp` in 0.12.0?

**Comment by jreback** [comment]
yeah ints shouldn't be explicit with a unit (fixing this in pd.to_datetime for 0.21) the implicit ns is pretty error prone

**Comment by wesm** [comment]
No objections

**Comment by djKooks** [comment]
I also think it's okay to send int value with unit, or make it to receive only integer and add on document that all integer value will be handled as ns value.

**Comment by cpcloud** [comment]
@djKooks We decided to deprecate this behavior going forward.

The preferred way going forward is to construct the timestamp literal from a `pandas.Timestamp` like so:

```python
import ibis
ts = ibis.timestamp(pd.Timestamp(1234, unit='ns'))
```

This works in current ibis, and will be the *only* way going forward to construct ibis timestamp literals from integers.

**Comment by djKooks** [comment]
@cpcloud LGTM~Thanks!
