### ISSUE TITLE
how to get last month aggregate value such as sum?

### ISSUE THREAD

**Issue by hengaini2055** [ibis-project/ibis#10059]
### Discussed in https://github.com/ibis-project/ibis/discussions/10027

<div type='discussions-op-text'>

<sup>Originally posted by **hengaini2055** September  5, 2024</sup>
I have a same question about clickhouse, and get answered, [clickhouse-discussion](https://github.com/ClickHouse/ClickHouse/discussions/69129)
```
any(MonthValue) OVER (PARTITION BY objectCode ORDER BY toRelativeMonthNum(pt) 
          Range BETWEEN 1 PRECEDING AND 1 PRECEDING) AS prevMonthValue
```
How can I get this function in ibis-framework?</div>

**Comment by ncclementi** [comment]
@hengaini2055 It's a bit hard to try to have an answer for you, without knowing what you tried. Can you tell us what have you tried with Ibis that didn't work? A good place to start looking, if you haven't already is https://ibis-project.org/tutorials/ibis-for-sql-users

You can see that there are examples of all the operation that you are trying to convert. Give it a try and let us know how it go. 

Make sure, that when you come back, you can provide us an example that we can run, what's the expected outcome and what's not working with your ibis code. If you struggled on how to construct a minimal verifiable example, here is a guide https://matthewrocklin.com/minimal-bug-reports#minimal-complete-verifiable-examples

**Comment by hengaini2055** [comment]
We can use SQL get the result:
```
select toStartOfMonth(period) as pt, objectCode, sum(amount) as MonthValue
   ,any(MonthValue) OVER (PARTITION BY objectCode ORDER BY toRelativeMonthNum(pt) Range BETWEEN 1 PRECEDING AND 1 PRECEDING) AS prevMonthValue
from url('https://github.com/user-attachments/files/16830630/clickhouse_posts.csv', 'CSVWithNames',
  'period DateTime64(3),objectCode String,typeName String,amount Float64' )
where objectCode = 'D00000139'
group by pt, objectCode
ORDER BY
     pt,
     objectCode;
```
When the objectCode is 'D00000147', there are only two months that have **MonthValue**. The SQL can get the correct results that **prevMonthValue** is the previous month value, not the previous row value.
```
select toStartOfMonth(period) as pt, objectCode, sum(amount) as MonthValue
   ,any(MonthValue) OVER (PARTITION BY objectCode ORDER BY toRelativeMonthNum(pt) Range BETWEEN 1 PRECEDING AND 1 PRECEDING) AS prevMonthValue
from url('https://github.com/user-attachments/files/16830630/clickhouse_posts.csv', 'CSVWithNames',
  'period DateTime64(3),objectCode String,typeName String,amount Float64' )
where objectCode = 'D00000147'
group by pt, objectCode
ORDER BY
     pt,
     objectCode;
```
run code in [https://fiddle.clickhouse.com/1e00c1f7-09e2-4706-bb9d-45a24a01781b](https://fiddle.clickhouse.com/1e00c1f7-09e2-4706-bb9d-45a24a01781b) That's all.
My question is how to write ibis expression to define ```prevMonthValue```.

**Comment by ncclementi** [comment]
@hengaini2055 We understand this runs on clickhouse with the sql provided, we are asking you to try to write the ibis expression yourself and once you've tried it and tell us what you've tried and how it fails, we can try to help out. 

But without you trying first we are not going to just do the translation for you.

**Comment by lostmygithubaccount** [comment]
hi @hengaini2055, I'd also like to understand if you're trying to run this on the duckdb or clickhouse backend (or something else). you can read in the file provided like so:

```python
import ibis

url = 'https://github.com/user-attachments/files/16830630/clickhouse_posts.csv'
table = ibis.read_csv(url, {'period': 'timestamp', 'objectCode': 'string', 'typeName': 'string', 'amount': 'float64'})

filtered = table.filter(table['objectCode'] == 'D00000139')
```

but otherwise it's hard to understand exactly what you're looking for or what issue is being encountered. I think you'd need to write a window function, you can refer to the documentation

**Comment by hengaini2055** [comment]
@ncclementi I created a table named clickhouse_post, and using the following ibis code 
```
import ibis
con_ch = ibis.clickhouse.connect(user="default", password="888877776666", host="172.28.40.206")
tb = con_ch.table("clickhouse_post")
tb.filter(tb.objectCode == "D00000139")\
.group_by([tb.period.strftime("%Y%m").name("checkPeriod"), tb.objectCode]).agg(thisMonthValue=tb.amount.sum(), preMonthValue=tb.amount.sum()).order_by("checkPeriod")
```
I don't know how to write preMonthValue ibis expression?

**Comment by hengaini2055** [comment]
You are the master. Thank you! I maybe know all the ibis functions such as **@ibis.udf.scalar.builtin**, **_**，**window**, but I cannot solve this problem. Now is a good start.
