### ISSUE TITLE
docs: how to get unique values of a column of any type

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#10084]
### Please describe the issue

It looks like the way of doing this is 
```python
penguins[["species"]].distinct()
```
based on the answers of this older issue https://github.com/ibis-project/ibis/issues/6029 but it's still not documented or at least I couldn't find that's how you do it. 

Besides it's normal for someone to search for `unique` and this only apply to arrays on ibis. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
another option is `penguins.distinct(on="species")`

**Comment by ncclementi** [comment]
Either way is not very intuitive for someone coming from the dataframe world. I found myself, and I cna think of people looking for `unique` instead of distinct. 
Not sure what's the best way to go about documenting this is, I can think of two things:

1. In the unique docs for array, add a note that says something like "if you are looking for unique values of a column of any type, look at `distinct` (have a redirect)" 
2. Add an example of how to get the unique values of a column in the distinct section.

**Comment by jcrist** [comment]
Would using the word "unique" a few times in the `distinct` docstring help it show up?

---

Now I'm also wondering about adding a generic unique _aggregate_ on `Column` that's effectively

```python
def unique(self) -> ArrayScalar:
    return self.collect().unique()  # Or self.as_table().distinct()[0].collect()?
```

except that would conflict with the existing `unique` on `ArrayValue`, giving it two separate meanings. Could call it `unique_values` or `collect_unique` or something. This would return an array scalar instead of a column, which could be useful in some situations. Primarily though it would give us another place to redirect users looking for unique values. Maybe not worth the work though.

**Comment by ncclementi** [comment]
> Would using the word "unique" a few times in the distinct docstring help it show up?

I think this would, and maybe there might be a way to rank the search to make it show up higher. Maybe @gforsyth might know a bit more about this. 

> Now I'm also wondering about adding a generic unique aggregate on Column that's effectively ...

Is there a way of having `.unique()` being different things depending on the argument type? Like if it's an array it does what it does now, but if it's a single column, it is a wrapper that does internally something like `penguins[["column"]].distinct()`

**Comment by ncclementi** [comment]
@lostmygithubaccount `penguins.distinct(on="species")` will return the whole table where the values of `species` are distinct, what I'm looking for is just the unique values in the  species column.

**Comment by lostmygithubaccount** [comment]
you are correct, I do it like this: 

https://github.com/ibis-project/ibis-analytics/blob/f8e5e3dbec91a1bea2d1eac20fbddf3830a0a2ac/dashboard.py#L273-L275

**Comment by ncclementi** [comment]
I think that'll do it.
