### ISSUE TITLE
feat(ir): allow the creation of lists from columns

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis#10102]
### Is your feature request related to a problem?

I (possibly on behalf of @lostmygithubaccount) am frustrated by writing `my_column.to_pyarrow().to_pylist()` to get a Python list from an Ibis column.

### What is the motivation behind your request?

Discussion on https://github.com/ibis-project/ibis/issues/10084#issuecomment-2344146445 during triage. The shorthand `my_column.to_pylist()` was also proposed, but `list(my_column)` would be so much more Pythonic.

### Describe the solution you'd like

`list(my_column)`

I don't need `list(my_table)` or `list(some_scalar)` to be implemented.

### What version of ibis are you running?

dev

### What backend(s) are you using, if any?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepyaman** [comment]
I can take a stab at this (later this week?), as discussed in triage.

**Comment by lostmygithubaccount** [comment]
can I just express frustration in meetings and have y'all take it from there? 😂 love it

**Comment by jcrist** [comment]
> but `list(my_column)` would be so much more Pythonic.

I'm concerned about having `__iter__` on columns result in (potentially expensive) query execution. We don't support `__bool__`/`__int__`/`__float__` on scalar values for the same reason. Accidental coercion like this can be a performance footgun for users, resulting in query execution in unintended locations or occurring multiple times. Other lazy systems (dask, polars) also don't do automatic execution in python magic methods for similar reasons.

I'd much rather have a new `to_*` method that does this. Why not `Column.to_list`?

**Comment by deepyaman** [comment]
> > but `list(my_column)` would be so much more Pythonic.
> 
> I'm concerned about having `__iter__` on columns result in (potentially expensive) query execution. We don't support `__bool__`/`__int__`/`__float__` on scalar values for the same reason. Accidental coercion like this can be a performance footgun for users, resulting in query execution in unintended locations or occurring multiple times. Other lazy systems (dask, polars) also don't do automatic execution in python magic methods for similar reasons.
> 
> I'd much rather have a new `to_*` method that does this. Why not `Column.to_list`?

Sorry, forgot to respond. `Column.to_list` seems fine.

**Comment by IndexSeek** [comment]
I have also found myself using the `to_pyarrow().to_pylist()` approach, particularly when feeding a Streamlit selectbox or multiselect widget. 

Going directly to a Python list from a column would be very convenient with something like `to_list`.
