### ISSUE TITLE
refactor: standardize _in_memory_table_exists

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#10123]
I saw this comment https://github.com/ibis-project/ibis/pull/10067#pullrequestreview-2290642303 from @jcrist and I'm converting it into an issue so we don't loose track of it. 

Where is suggested to change the default implementation to:

```python
try:
    self.table(name)
    return True
except TableNotFound:
    return False
```

This https://github.com/ibis-project/ibis/pull/9695 was  merged
I'm not sure about the details of the implementation/refactor but this seems like it could be a nice consolidation of code

**Comment by cpcloud** [comment]
We're not using this method anymore it seems.
