### ISSUE TITLE
bug: polars flatten does not work as expected

### ISSUE THREAD

**Issue by GLeurquin** [ibis-project/ibis#10135]
### What happened?

Following up on https://github.com/ibis-project/ibis/issues/9995

Thanks @gforsyth and @cpcloud for the quick fix of the above issue. However I don't think it totally fixed the issue.

I am trying to get an `array<array<int64>>` to become an `array<int64>`

Using Polars:

```python
import ibis
ibis.set_backend("polars")
t = ibis.memtable([
    {
        "arr": [[1, 5, 7], [3,4]]
    },
])
t.arr.flatten()
```

```
┏━━━━━━━━━━━━━━━━━━━┓
┃ ArrayFlatten(arr) ┃
┡━━━━━━━━━━━━━━━━━━━┩
│ array<int64>      │
├───────────────────┤
│ [1, 5, ... +1]    │
│ [3, 4]            │
└───────────────────┘
```

Using pandas:

```python
ibis.set_backend("pandas")
t = ibis.memtable([
    {
        "arr": [[1, 5, 7], [3,4]]
    },
])
t.arr.flatten()
```

```
┏━━━━━━━━━━━━━━━━━━━┓
┃ ArrayFlatten(arr) ┃
┡━━━━━━━━━━━━━━━━━━━┩
│ array<int64>      │
├───────────────────┤
│ [1, 5, ... +3]    │
└───────────────────┘
```
Notice how using `pandas` I get a single line back with a single "flattened" array, while using `polars`, I get 2 rows back. Hence I think something is still missing somewhere, unless there is another way to achieve this using ibis or I misunderstand the flatten function. Anyways, I believe the result should be the same by using pandas or polars.

I expect the result to be `[1, 5, 7, 3, 4]` in both cases.

### What version of ibis are you using?

9.5.0

### What backend(s) are you using, if any?

polars 1.5.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Yep, this is still a bug! It looks like we might be using the polars API incorrectly here, taking a look now.

**Comment by cpcloud** [comment]
@GLeurquin Any idea what the polars API is to remove one level of nesting? I don't see any APIs that behave the same way as everything else.

`flatten` does some kind of strange unnesting thing:

```
In [35]: import polars as pl

In [36]: df = pl.DataFrame([{'arr': [[1,5,7],[3,4]]}])

In [37]: df
Out[37]:
shape: (1, 1)
┌─────────────────────┐
│ arr                 │
│ ---                 │
│ list[list[i64]]     │
╞═════════════════════╡
│ [[1, 5, 7], [3, 4]] │
└─────────────────────┘

In [38]: df.select(pl.col("arr").flatten())
Out[38]:
shape: (2, 1)
┌───────────┐
│ arr       │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [1, 5, 7] │
│ [3, 4]    │
└───────────┘
```

**Comment by GLeurquin** [comment]
I'm no polars expert, but I did manage to find this:

```python
import polars as pl
df = pl.DataFrame([{'arr': [[1,5,7],[3,4]]}])
df.select(pl.col("arr").list.eval(pl.element().flatten()))
```

**Comment by cpcloud** [comment]
Thanks!

Any idea what the logic is there?

My understanding is `pl.element()` is analogous to a `lambda` expression in other systems. So, what does it mean that calling `flatten` on individual elements of a list, results in the **outer** list losing a nesting level?

I'd like to understand what the right way is to do this before rolling it into a PR so that we don't end up in the current situation.

cc @ritchie46 @MarcoGorelli

**Comment by GLeurquin** [comment]
In the [polars documentation](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.flatten.html) it explains that flatten is an alias to explode, so I assume it's exploding individual lists and then concatenating the exploded elements into a new list in the eval.

I experimented with the following implementation of the translate function:

```python
@translate.register(ops.ArrayFlatten)
def array_flatten(op, **kw):
    result = translate(op.arg, **kw)
    return (
        pl.when(result.is_null())
        .then(None)
        .when(result.list.len() == 0)
        .then([])
        .otherwise(result.list.eval(pl.element().flatten()))
    )
```

The following simple expression gives the expected result:
```python
t = ibis.memtable([{"arr": [[1, 5, 7], [3,4]]}])
t.select(flattened=_["arr"].flatten())
```

```
┏━━━━━━━━━━━━━━━━┓
┃ flattened      ┃
┡━━━━━━━━━━━━━━━━┩
│ array<int64>   │
├────────────────┤
│ [1, 5, 7, 3, 4]│
└────────────────┘
```

Another example with a group by:

```python
t = ibis.memtable([
    {
        "key": "A",
        "arr": [1, 5, 7]
    },
    {
        "key": "A",
        "arr": [6, 9, 2]
    },
])

t.group_by("key").agg(
    concat1=_["arr"].collect(),
    concat2=_["arr"].collect().flatten(),
).mutate(
    concat11=_["concat1"].flatten(),
)
```

| key   | concat1                | concat2                              | concat11           |
|:------|:-----------------------|:-------------------------------------|:-------------------|
| A     | [[1, 5, 7], [6, 9, 2]] | [[1, 5, 7], [6, 9, 2]] | [1, 5, 7, 6, 9, 2] |

I guess one cannot chain flatten after collect like it's possible in spark ? I would have expected `concat2` to be `[1, 5, 7, 6, 9, 2]`, but maybe that's something specific to the way ibis works.

The result for `concat11` is what I would expect.

The following example gives more insights on what might be happening for `concat2` above. On a more complex example, we get different results for `concat1` and `concat2`:

```python
t = ibis.memtable([
    {
        "key": "A",
        "arr": [[1, 5, 7], [3,4]]
    },
    {
        "key": "A",
        "arr": [[6], [9, 2]]
    },
])

t.group_by("key").agg(
    concat1=_["arr"].collect(),
    concat2=_["arr"].collect().flatten(),
).mutate(
    concat11=_["concat1"].flatten(),
    concat22=_["concat2"].flatten(),
)
```

key   | concat1                              | concat2                      | concat11                         | concat22                 |
|:------|:-------------------------------------|:-----------------------------|:---------------------------------|:-------------------------|
| A     | [[[1, 5, 7], [3, 4]], [[6], [9, 2]]] | [[1, 5, 7, 3, 4], [6, 9, 2]] | [[1, 5, 7], [3, 4], [6], [9, 2]] | [1, 5, 7, 3, 4, 6, 9, 2] |

For `concat2` it looks like ibis is flattening before the collect, which is unexpected given the way the code is written (I guess ibis does not support chaining operations after a collect ?). I would have expected `concat2` to be `[1, 5, 7, 3, 4, 6, 9, 2]`. The results for `concat11` and `concat22` are coherent.

**Comment by ritchie46** [comment]
I would recommend against using `eval` as it is interpreted and opaque to us.

In Polars `explode` removes one level of nesting and `implode` adds 1 level of nesting. So with that we can achieve the expected reshape. We can also use `reshape` directly:

```python
df = pl.DataFrame(
    {
        "arr": [[1, 5, 7], [3,4]]
    },
)

# explode -> Series of List<i64> to Series of i64
# implode Series of i64 to List<i64> by adding 1 level of nesting
df.select(pl.col("arr").explode().implode())

# Similar to reshape
df.select(pl.col("arr").reshape((1, -1)))
```

**Comment by cpcloud** [comment]
I think there's some misunderstanding here.

What I want is the API in Polars where given a list of at least 2 dimensions `list<list<T>>` I get back `list<T>`.

For example:

Given this input:

```
In [19]: import polars as pl

In [20]: df = pl.DataFrame({"data": [[["abc", "ghi"], ["jkl"]], [["bcd"]], [["def"]]]})
```

How do I get this output?

```
In [22]: df
Out[22]:
shape: (3, 1)
┌───────────────────────┐
│ data                  │
│ ---                   │
│ list[str]             │
╞═══════════════════════╡
│ ["abc", "ghi", "jkl"] │
│ ["bcd"]               │
│ ["def"]               │
└───────────────────────┘
```

- No combination of `explode`/`implode` seems to do what I want.
- `reshape` is almost certainly not what I want either, this operation needs to work in cases where the dimension sizes are variable length.
- @GLeurquin's `eval` implementation does actually work though.

Is there really no efficient way to remove one level of nesting from a `list` type?

**Comment by ritchie46** [comment]
Ah, no, I don't think we have an explicit operation for that. `eval` is currently the way to go

**Comment by cpcloud** [comment]
Thanks, appreciate the reply, will do that for now!
