### ISSUE TITLE
docs: Difficulty finding method reference

### ISSUE THREAD

**Issue by Riezebos** [ibis-project/ibis#10161]
### Please describe the issue

As a user getting used to Ibis coming from a Pandas, I often want to find out exactly how a function works.

In many cases, the info is shown when hovering over a method in VSCode, but this doesn't always work as e.g. deferred expressions don't always show all methods that a Column can have.

Today, I was using value_counts and wanted to know whether I could control the name of the column with the count.

Searching the docs gave me:
<img width="849" alt="image" src="https://github.com/user-attachments/assets/f2a47cf7-1f6b-4e94-a8cf-e7f875107136">

The place in the docs that I needed turned out to be: https://ibis-project.org/reference/expression-generic.html#ibis.expr.types.generic.Column.value_counts

But in the search menu that page is quite low, and the link in the search doesn't go to the place where that function is defined, as it is used elsewhere in the page as an example.

Would it be possible rank matches from Reference higher in the search results? Or maybe have a separate search box somewhere that can be used to purely search within the Reference?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @Riezebos -- the reference documentation should _definitely_ rank higher than stuff in release notes.  I'm not sure what's happening here because I see the reference page as the first hit, but I'll try to figure out if that's not happening reliably.

![2024-09-18_11-00](https://github.com/user-attachments/assets/e14a0f48-0b5f-4a81-b98c-d053805d41d0)

**Comment by gforsyth** [comment]
@Riezebos -- can you try searching again on your end?  

There's a possibility that you got very unlucky and happened to search while our CI was in the middle of updating the search configuration to update the document rankings -- I'd like to rule that out if we can.

**Comment by Riezebos** [comment]
Ah, now it's also at the top for me!

Another example that might be different is `to_parquet`:
<img width="854" alt="image" src="https://github.com/user-attachments/assets/c782c85b-9c82-437c-adde-d916e2cb59b8">

I can run `t.to_parquet()` on a table expression, which seems to not be documented on the table expressions page. I guess it might be automatically added when the backend is DuckDB?

It is documented on the Duckdb backend page: https://ibis-project.org/backends/duckdb#ibis.backends.duckdb.Backend.to_parquet

But when I search for `to_parquet` or for `duckdb to_parquet` the duckdb backend page is not in the search results at all.

**Comment by gforsyth** [comment]
Heh, just fixed those missing `to_*` methods in #10164, but keep the search issues coming!!

**Comment by Riezebos** [comment]
Wow this is getting challenging!

How about this one:
Searching for mutate has the Table expressions page as third on the list, and none of the results from that page are the actual direct link to the docs of the mutate method. (They are mostly examples, and the bottom one is to the overview of methods of Table)

<img width="854" alt="image" src="https://github.com/user-attachments/assets/5ab159c0-e4d4-43fb-80dd-ed20d3d2b00a">

**Comment by gforsyth** [comment]
Should be good now @Riezebos !  
Something happened on one of our CI runs and _none_ of the API docs were added to the search index.  I've regenerated it and now `mutate` is the top result.  Going to try to track down what broke down, though

**Comment by Riezebos** [comment]
Amazing, that was quick!
