### ISSUE TITLE
feat: <expression>.get_backend()

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#10197]
### Is your feature request related to a problem?

similar to another discussion on `ibis.to_sql`, it can be annoying (even w/ VIM) to add a ')' at the end and `ibis.get_backend(` at the beginning of an expression -- I'd prefer to just write `expr.get_backend()` (for column or table expressions)

### What is the motivation behind your request?

typing less

### Describe the solution you'd like

`expr.get_backend()` that works just like `ibis.get_backend(expr)`

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

often duckdb but any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mesejo** [comment]
I've opened a draft PR for this issue. I was wondering:
1. Since the purpose of the issue is **typing less**, should we use a property instead of the method?
2. Should we expose the `_find_backend` method instead of wrapping it?
