### ISSUE TITLE
feat: Select column similar to polars' pl.col

### ISSUE THREAD

**Issue by shane-breeze** [ibis-project/ibis#10200]
### Is your feature request related to a problem?

Column selection seems to require the table, i.e.
```python
table = con.table(...)
table.select(table.a+1, table.b+2, ...)
```

### What is the motivation behind your request?

I'd like better support for chaining operations.

### Describe the solution you'd like

A selector similar to polars' pl.col, i.e.
```python
table = con.table(...).select(ibis.col("a")+1, ibis.col("b")+2)
```

### What version of ibis are you running?

9.4.0

### What backend(s) are you using, if any?

BigQuery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
We've got `_` for that, and [it's documented](https://ibis-project.org/how-to/analytics/chain_expressions#chaining-ibis-expressions)!
