### ISSUE TITLE
bug: mutate(a=".") fails

### ISSUE THREAD

**Issue by syakesaba** [ibis-project/ibis#10256]
### What happened?

```python
ibis.get_backend().name
# 'duckdb'
ibis.memtable([{"a":1},]).mutate(b=".")
```

Raises ibis.common.exceptions.IbisTypeError: Column '.' is not found in table. Existing columns: 'a'.

### What version of ibis are you using?

ibis-framework==9.5.0
duckdb==1.1.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by syakesaba** [comment]
ibis.literal() solved this.

**Comment by cpcloud** [comment]
Yep, `ibis.literal(".")` is the solution here!
