### ISSUE TITLE
bug: Documentation headers

### ISSUE THREAD

**Issue by zilto** [ibis-project/ibis#10312]
### What happened?

The reference section for the DuckDB backend have improper headers.

Before, the navigation pane only displayed the method names. Now, they display `Parameters` and `Returns` too, which make navigation harder.

![image](https://github.com/user-attachments/assets/789f02e9-7860-45bc-aaab-7ba5bc74c167)

### What version of ibis are you using?

--

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the report, that indeed is annoying. Let me look into it and see if that's an issue on our side or something on the quarto or quartodoc side.
