### ISSUE TITLE
Summary is broken on postgres due to issues summing booleans

### ISSUE THREAD

**Issue by FedericoV** [ibis-project/ibis#1035]
Hi: Ibis is awesome, and I realize the postgres support is highly experimental - but I ran into a limitation that makes a lot of other tasks a lot more cumbersome.

Boolean types on postgres cannot be summed, so quite a bit of functionality is missing and require verbose work around.

The simplest example:

`a.clothing_size.isnull().sum().execute()`

Gives this output:

```
ProgrammingError: (psycopg2.ProgrammingError) function sum(boolean) does not exist
HINT:  No function matches the given name and argument types. You may need to add explicit type casts.
 [SQL: 'SELECT sum(t0.clothing_size IS NULL) AS sum \nFROM monster.asin_dimension AS t0']

```

Is this something that IBIS should handle under the hood, or users should write back-end aware code?

**Comment by cpcloud** [comment]
@FedericoV Thanks for reporting this. This is definitely a place where we can polish away some of the inconvenience by automatically casting `BOOLEAN` to `INTEGER`. In the meantime, you can perform this cast yourself:

```python
a.clothing_side.isnull().cast('int32').sum().execute()
```

**Comment by cpcloud** [comment]
Actually, this is more annoying that I originally thought.

**Comment by cpcloud** [comment]
I think I can get a fix up pretty quick, let me see what needs to happen here.

**Comment by FedericoV** [comment]
Hi!  I actually was able to fix that exactly the way you suggested: where it's annoying is that other functionalities that implicitly rely on summing bools (like, summary) are broken, and those cannot be fixed that easily.

**Comment by cpcloud** [comment]
Right! On it. :)
