### ISSUE TITLE
feat: API to get connection string from backend

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#10373]
### Is your feature request related to a problem?

This may be out of scope for ibis, but I'm curious if you have any suggestions. See https://github.com/duckdb/duckdb/discussions/14549#discussion-7364961 for the motivation and use case. I went directly upstream, since I thought it would be useful to have that functionality in duckdb by itself.

If I understand correctly, sometimes ibis backends are constructed directly from a db connection, eg `ibis.duckdb.connect(duckdb.connect())` instead of `ibis.duckdb.connect("db.duckdb")`. In that case, we would need to rely on the upstream backend to provide a `.get_connection_string()` method. So maybe this is impossible to do for all backends.

### Describe the solution you'd like

`conn.connection_string` or similar.

### What version of ibis are you running?

NA

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Why isn't having an existing connection enough?

**Comment by NickCrews** [comment]
Because I am trying to use sqlalchemy to create the tables in the database, and as far as I can see there is no way to create a sqlalchemy engine from an existing connection, only from a connection string.

**Comment by cpcloud** [comment]
There's definitely a way to do that: https://stackoverflow.com/a/23744051

**Comment by NickCrews** [comment]
Maybe is it that the DuckdbPyConnection doesn't implement the needed API? Am I passing in the wrong thing?

```python
# python -m pip install duckdb-engine>=0.13.4
# import duckdb_engine
import duckdb
import sqlalchemy as sa
from sqlalchemy.orm import declarative_base

_base = declarative_base()


class Pet(_base):
    __tablename__ = "pets"

    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.String)
    age = sa.Column(sa.Integer)
    species = sa.Column(sa.String)


con = duckdb.connect()
engine = sa.create_engine("duckdb://", creator=lambda: con)
_base.metadata.create_all(engine)
# AttributeError: 'duckdb.duckdb.DuckDBPyConnection' object has no attribute 'connection'
```

**Comment by cpcloud** [comment]
I don't know, but this certainly isn't an Ibis issue.
