### ISSUE TITLE
feat: Add temporal expressions to code suggestions

### ISSUE THREAD

**Issue by sergei3000** [ibis-project/ibis#10382]
### Is your feature request related to a problem?

When I type in IDE, temporal expressions are not suggested on columns in IDE. For example, no `truncate` here:
<img width="256" alt="image" src="https://github.com/user-attachments/assets/7092942a-974c-4eff-a089-d44e51bf9df9">
And then the temporal methods are not colored in the code, I imagine there could be some errors from linters and type checkers, and all that.

### Describe the solution you'd like

So it would be cool to have code completion for the temporal expressions on columns as well.

### What version of ibis are you running?

9.5.0

### What backend(s) are you using, if any?

Druid, Postgres

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sergei3000** [comment]
In this my example it's not Druid or anything else, but there are still some suggestions.
Is it possible to provide just all the functions to code completion like in this example? At least for such backends? Then the backend would just throw an error if it doesn't implement a specific function a user is trying to use.

**Comment by gforsyth** [comment]
@sergei3000 -- do the completions work for you in a Python REPL?  Are you sure that your temporal expression has the right dtype?

This works fine for me:

```sh

[ins] In [12]: t.year.type()
Out[12]: Timestamp(timezone=None, scale=None, nullable=True)

[ins] In [13]: t.year.tr<tab>
 truncate() try_cast()
```

**Comment by sergei3000** [comment]
@gforsyth Yes to both questions:
```
>>> t.__time.type()
Timestamp(timezone=None, scale=None, nullable=True)
>>> t.__time.tr
t.__time.truncate(  t.__time.try_cast( 
```

**Comment by cpcloud** [comment]
I don't think this is an Ibis issue if it's working in the REPL. I'd try reporting upstream to the maintainers of your IDE.

**Comment by sergei3000** [comment]
To me it looks like it's working in REPL because the table object gets info on the column types after executing something like t = `ibis.connect...`. Which (the execution) does not happen in IDE (I use vscode btw). So this looks like an ibis issue to me still.
