### ISSUE TITLE
bug: Clickhouse datetime type conversion with pandas

### ISSUE THREAD

**Issue by noklam** [ibis-project/ibis#10398]
### What happened?

Originally I was developing with Kedro's [ibis.TableDataset](https://docs.kedro.org/projects/kedro-datasets/en/kedro-datasets-3.0.1/api/kedro_datasets.ibis.TableDataset.html). After some debugging I have isolated the bug is coming from `ibis` instead. When I use `ibis` with `clickhouse`, I get a type error coming from `ibis` conversion.

The table can be run locally as I am using the public `pypi` table. I have worked out a pure `ibis` example:

```python
connection = {"host": "clickpy-clickhouse.clickhouse.com",
"database":"pypi",
"secure": True,
"port": 443,
"user": "play",

}
import ibis
con= ibis.clickhouse.connect(**connection)
table = con.table("pypi_downloads_per_day_by_version_by_installer_by_type")
table.head().to_pyarrow()
```

The above works perfectly, when I convert to `pandas` it fails:
```
table.head().to_pandas()
```

### What version of ibis are you using?

ibis-framework            9.5.0

### What backend(s) are you using, if any?

clickhouse

### Relevant log output

```sh
> ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 table.head().to_pandas()

File ~/miniconda3/envs/kedro/lib/python3.10/site-packages/ibis/expr/types/relations.py:3256, in Table.to_pandas(self, **kwargs)
   3248 def to_pandas(self, **kwargs) -> pd.DataFrame:
   3249     """Convert a table expression to a pandas DataFrame.
   3250 
   3251     Parameters
   (...)
   3254         Same as keyword arguments to [`execute`](./expression-generic.qmd#ibis.expr.types.core.Expr.execute)
   3255     """
-> 3256     return self.execute(**kwargs)

File ~/miniconda3/envs/kedro/lib/python3.10/site-packages/ibis/expr/types/core.py:324, in Expr.execute(self, limit, timecontext, params, **kwargs)
    297 def execute(
    298     self,
    299     limit: int | str | None = "default",
   (...)
    302     **kwargs: Any,
    303 ):
    304     """Execute an expression against its backend if one exists.
    305 
    306     Parameters
...
   2560     # a  tz-aware Timestamp (with a tz specific to its datetime) will
   2561     # be incorrect(ish?) for the array as a whole
   2562     dtype = cast(DatetimeTZDtype, dtype)

ValueError: Unexpected value for 'dtype': 'datetime64[D]'. Must be 'datetime64[s]', 'datetime64[ms]', 'datetime64[us]', 'datetime64[ns]' or DatetimeTZDtype'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
What version of pandas are you using?

With pandas 2.2.3 and ibis-framework 9.5.0, the code you provided executes successfully.

**Comment by noklam** [comment]
I should have freeze my environment before I change it. I was on pandas==2.1.0, I try to force upgrade both ibis and pandas and it works as expected. Then I downgrade it to pandas 2.1.0 and it still work, I have no idea which package was causing the problem.


I will close this issue unless I can reproduce this again

**Comment by cpcloud** [comment]
Thanks for the report!
