### ISSUE TITLE
Default table aliases can conflict with actual physical table names

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#104]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Thursday Feb 12, 2015 at 23:34 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/104_

---

Pathological case: tables named `t0, t1, ...`

Implementation strategy should be to determine names of all physical tables appearing in the query tree and attach these to the `QueryContext` (so that deduplication can occur in the alias assignment method)

**Comment by cpcloud** [comment]
I don't think this is a bug since the correctness of queries isn't impacted. Classifying as a usability issue, since the ability to read the generated query is secondary to generating the correct code.

**Comment by cpcloud** [comment]
@saulpw had the idea to add a configuration option for the prefix name, which should alleviate any ux issues here if they arise.
