### ISSUE TITLE
bug: DatabaseError: ORA-00923 when attempting to fetch table schema using Ibis Oracle backend

### ISSUE THREAD

**Issue by xuefliang** [ibis-project/ibis#10403]
### What happened?

Here's an English description of the issue suitable for a GitHub submission:

Title: DatabaseError: ORA-00923 when attempting to fetch table schema using Ibis Oracle backend

Description:
I'm encountering an error when trying to connect to an Oracle database using the Ibis Oracle backend. The error occurs specifically when attempting to fetch the schema for a table.

Steps to reproduce:

Establish a connection to the Oracle database:
<PYTHON>
con = ibis.oracle.connect(
    user='user',
    password='password',
    host='88888',
    port=1521,
    service_name='**'
)
List databases and tables:
<PYTHON>
dbs = con.list_databases()
tables = con.list_tables()
Attempt to fetch a specific table:
<PYTHON>
t = con.table("CONFIG_YMXX")

### What version of ibis are you using?

9.5.0

### What backend(s) are you using, if any?

Oracle

### Relevant log output

```sh
DatabaseError: ORA-00923: FROM keyword not found where expected
Help: https://docs.oracle.com/error-help/db/ora-00923/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hi @xuefliang -- what version of Oracle are you trying to connect to? We currently only support Oracle >= 23 because that's when they finally added a Boolean dtype

**Comment by xuefliang** [comment]
My Oracle version is 12.2

**Comment by mvanwyk** [comment]
@gforsyth Is there any work around for this? Oracle 23 was only released 2 years ago. That leaves _a lot_ of Oracle databases unsupported.

**Comment by gforsyth** [comment]
We've made a few attemtps, but it's a multi-project undertaking and I don't think we want to take on the additional maintenance burden (which is significant).

xref https://github.com/ibis-project/ibis/pull/9877
xref https://github.com/ibis-project/ibis/pull/9379

**Comment by mvanwyk** [comment]
Thanks @gforsyth! Understood. For others landing here, I worked around the issue by specifying the query and schema while paying special attention to column capitalization. Eg,

```
tbl = ibis_conn.sql(
    "SELECT MY_COL_1, MY_COL_2 FROM MY_TABLE", 
     schema= {
        "MY_COL_1": "string",
        "MY_COL_2": "int",
  },
)

tbl = tbl.filter(tbl.MY_COL_1 == "foo")
```

The rest of my code worked fine after that.

**Comment by Unirest** [comment]
@gforsyth https://far-offmui-x-data-grid.github.io/vCrb7DAHmvPfA6FC3QcMACPbMMmqg/
