### ISSUE TITLE
docs: cases() documentation doesn't work for me at all

### ISSUE THREAD

**Issue by lexual** [ibis-project/ibis#10535]
### Please describe the issue

Can't get the conditional cases() examples to work (as opposed matching on a value), am I missing something?:

```
$ python -c 'import ibis; print(ibis.__version__); ibis.cases'
9.5.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/home/lexfed/code/lex_budget/_venv/lib64/python3.12/site-packages/ibis/__init__.py", line 142, in __getattr__
    return load_backend(name)
           ^^^^^^^^^^^^^^^^^^
  File "/var/home/lexfed/code/lex_budget/_venv/lib64/python3.12/site-packages/ibis/__init__.py", line 66, in load_backend
    raise AttributeError(msg)
AttributeError: module 'ibis' has no attribute 'cases'. . Did you mean: 'case'?
```

I tried other examples that specify I should be using `else_` kwarg, and it complains about it not existing, and it looks like it should be `default` ?

This is another verbatim from the docs:

```
$ python
Python 3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibis
>>> ibis.options.interactive = True
>>> v = ibis.memtable({"values": [1, 2, 1, 2, 3, 2, 4]}).values
>>> v.to_polars()
shape: (7,)
Series: 'values' [i64]
[
        1
        2
        1
        2
        3
        2
        4
]
>>> ibis.cases((v == 1, "a"), (v > 2, "b"), else_="unk").name("cases")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/home/lexfed/code/lex_budget/_venv/lib64/python3.12/site-packages/ibis/__init__.py", line 142, in __getattr__
    return load_backend(name)
           ^^^^^^^^^^^^^^^^^^
  File "/var/home/lexfed/code/lex_budget/_venv/lib64/python3.12/site-packages/ibis/__init__.py", line 66, in load_backend
    raise AttributeError(msg)
AttributeError: module 'ibis' has no attribute 'cases'. . Did you mean: 'case'?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lexual** [comment]
Thanks @IndexSeek 

Appreciate the apology, but not a big deal for me.
Is the next release likely to be any time soon?

This is bad UX for an end user. It could be worth considering any of the following, which might help with this issue:

* add some text for features of which version they are introduced in (python docs do this I believe). That way people on older versions who were reading the docs would be aware that they need a newer version (probably easiest to implement)
* have the docs site point to a release branch/tag not main or development branch?
* separate docs pages available for each version ( I believe pandas does this).

Thanks.

**Comment by deepyaman** [comment]
> separate docs pages available for each version ( I believe pandas does this).

I think most docs do this. 😅 

As somebody who has also been confused by the docs showing things that aren't available in the latest released version on many occasions, I wonder how hard it would be to have versioned docs?

But it seems the Quarto team doesn't plan to support it? https://github.com/quarto-dev/quarto-cli/issues/474#issuecomment-2483372089

**Comment by NickCrews** [comment]
About 2 years ago, it appears we made the decision to explicitly move from versioned docs to unversioned docs: https://github.com/ibis-project/ibis/issues/5347. I personally think this was the right choice, and I personally would make the same choice again today. Not sure what other ibis maintainers think.

**Comment by gforsyth** [comment]
It's not worth the overhead, in my mind.  I do push up historical docs when I remember to. (https://ibis-project.github.io/ibis/)

One thing we _could_ do is have a `/dev` sub-directory in the docs tree, and only update the "main" docs when we push a new release.  But this also causes confusion with scrapers, etc

**Comment by cpcloud** [comment]
We can probably link to the older versions somewhere on the main site too, if we don't already.

That would mostly solve the problem here IMO.
