### ISSUE TITLE
BUG: Kudu table write is using old impala-shell syntax

### ISSUE THREAD

**Issue by tarungog** [ibis-project/ibis#1063]
https://github.com/ibis-project/ibis/blob/master/ibis/impala/kudu_support.py#L246

The following syntax is no longer supported by the impala shell when creating kudu tables or kudu-backed external tables:

```
_table_props_base = {
   'storage_handler': 'com.cloudera.kudu.hive.KuduStorageHandler'
   }

```

Instead use 
`STORED AS KUDU`
after the create table expression.

The kudu <-> impala-shell documentation is here:

https://www.cloudera.com/documentation/kudu/latest/topics/kudu_impala.html

**Comment by cpcloud** [comment]
@tarungog Thanks for the report. Regard the docker image I mentioned on your previous Kudu issue, here it is: https://hub.docker.com/r/cpcloud86/impala/

**Comment by kszucs** [comment]
@cpcloud is it still valid?

**Comment by cpcloud** [comment]
@kszucs This is still valid, though we'd need to get kudu into the impala image to test this so we can fix it.

**Comment by kszucs** [comment]
Ouch. This might help: https://github.com/parrot-stream/docker-impala-kudu/blob/latest/Dockerfile

**Comment by cpcloud** [comment]
we now have the ability to use kudu through impala in our CI. @tarungog any interest in submit a patch to fix this?

**Comment by kvignesh1420** [comment]
I still get this exception while creating kudu backed impala tables:
```console
 HiveServer2Error: AnalysisException: Kudu tables must be specified using 'STORED AS KUDU'.
```

impyla==0.15.0
ibis-framework==1.3.0.

Is there any workaround for this ?

**Comment by cpcloud** [comment]
I don't think there's a workaround for this unfortunately. Kudu support needs an owner.
