### ISSUE TITLE
docs: Cloud backend support policy duplicated in dropdown menu

### ISSUE THREAD

**Issue by IndexSeek** [ibis-project/ibis#10636]
### Please describe the issue

I think we can move the [cloud_support_policy.qmd](https://github.com/ibis-project/ibis/blob/main/docs/backends/cloud_support_policy.qmd) file into **ibis/blob/main/docs/backends/support** to render once. 

<div style="display: flex; justify-content: space-between;">
  <img src="https://github.com/user-attachments/assets/3b779efd-6a11-4aa8-b701-abb76fa3a1e4" alt="Image 1" style="width: 45%; margin-right: 5%;">
  <img src="https://github.com/user-attachments/assets/8e16bc07-cd95-4515-bac7-b4fafedc96a7" alt="Image 2" style="width: 45%;">
</div>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Yep, SGTM! Nice find.
