### ISSUE TITLE
ENH: Add readable truncate constants

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1077]
xref: https://github.com/ibis-project/ibis/issues/772

We should make some new expressions that represent these values to make things more readable:

```
t.my_timestamp.truncate(ibis.START_OF_DAY)
t.my_timestamp.truncate(ibis.MONTH)
```

**Comment by kszucs** [comment]
I've created an explicit mapping for truncate units [here](https://github.com/kszucs/ibis/blob/656998fb05059563b1f3096f1a6935f3721c8319/ibis/expr/operations.py#L2332)

We might use an enum to support auto completion.

**Comment by kszucs** [comment]
@cpcloud schedule it to 0.14?

**Comment by cpcloud** [comment]
@kszucs Sounds good.

**Comment by cpcloud** [comment]
I'm moving this to 0.15, not sure this will make it into 0.14
