### ISSUE TITLE
feat: add weight to mean aggregation

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1093]
Thinking something like

```python
table.column.mean(weight=table.other_column)
```

**Comment by jreback** [comment]
should call this weights

e.g. https://docs.scipy.org/doc/numpy/reference/generated/numpy.average.html

**Comment by bschneidr** [comment]
Was this completed, or was it decided that this feature is not going to be implemented?

From the current documentation for `.mean()`, I don't see a `weights` argument.

https://ibis-project.org/reference/expression-numeric#ibis.expr.types.numeric.NumericColumn.mean

After reading this issue on GitHub, I tried using a `weights` argument and got an error message.

```python
import ibis
import polars as pl
from ibis import _

# Create example table for dataset with weights
data = pl.DataFrame({
    "id"  : [1, 2, 3, 4],
    "y"   : [7.2, 3.4, 9.2, 1.1],
    "wgt" : [10, 10, 10, 10]
})

weighted_data = ibis.polars.connect(tables = {"weighted_data": data}).table("weighted_data")

# Attempt to compute weighted mean using 'weights' kwarg
weighted_data.agg(
  wtd_mean = _['y'].mean(weights = _['wgt'])
)
# TypeError: NumericColumn.mean() got an unexpected keyword argument 'weights'
```

The following works although it's pretty verbose:

```python
weighted_data.agg(
  wtd_mean = (_['y'] * _['wgt']).sum() / _['wgt'].sum(where =  _['y'].notnull())
)
#
# ┏━━━━━━━━━━┓
# ┃ wtd_mean ┃
# ┡━━━━━━━━━━┩
# │ float64  │
# ├──────────┤
# │    5.225 │
# └──────────┘
```
