### ISSUE TITLE
Enable configurable row batchsize for passing to Python

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#11]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Tuesday Dec 09, 2014 at 20:22 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/11_

---

One way would be to add an extra parameter to the current `ibis_uda` C++ UDA, but there might be another way

**Comment by cpcloud** [comment]
This is very specific to UDAs, which no one is working on. This could be useful, but we'll open another issue to discuss.

Closing.
