### ISSUE TITLE
Clickhouse backend

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1120]
Hi!

I'm considering to use ibis with clickhouse, but not sure how to implement it. Lately clickhouse got an [sqlalchemy dialect](https://github.com/xzkostyan/clickhouse-sqlalchemy) and native driver from @xzkostyan . 

Most of the abstractions are clear, but how could I handle special cases like [ANY LEFT JOIN](https://clickhouse.yandex/docs/en/query_language/queries.html#join-clause) ?

I've looked for backend development guide with no success. Could You give me a quickstart?

**Comment by wesm** [comment]
It would be nice to have an Ibis backend for Clickhouse. I suspect we would need to generate SQL strings like we are doing with Impala, and this would enable accounting for the ANY joins, e.g.

`left.any_left_join(...)`

or something like that. Working in the backend is not too bad but the initial learning curve is steep. You would want to look at https://github.com/ibis-project/ibis/blob/master/ibis/impala/compiler.py; we could almost certainly generalize this code to be useful in other SQL dialects. We've recently been discussing building a Spark SQL backend and it might be easier to generate SQL strings vs. using a SQLAlchemy dialect

**Comment by wesm** [comment]
cc @cpcloud

**Comment by kszucs** [comment]
@wesm @cpcloud 

275 tests are passing now, mostly testing operations (functions). Right now I'm porting test cases from `ibis/sql/test_compiler.py` (luckily they've just released `WITH` support).

Also I need help with analytical functions and joins, I don't know (yet) how to represent them with ibis expressions:
- [ARRAY JOIN](https://clickhouse.yandex/docs/en/query_language/queries.html#array-join-clause)
- [ANY / ALL JOIN](https://clickhouse.yandex/docs/en/query_language/queries.html#join-clause)
- [any(), anyLast(), groupArray()](https://clickhouse.yandex/docs/en/agg_functions/index.html)
- there are no window operations, but seemed mandatory for ibis analytical queries

**Comment by cpcloud** [comment]
Closed by 3324d1f
