### ISSUE TITLE
BigQuery backend for Ibis?

### ISSUE THREAD

**Issue by jpvelez** [ibis-project/ibis#1139]
Hi folks!

I'm a data engineer at Spotify. We use BigQuery extensively (hundreds of users). We also have tons of pandas users. Being able to talk to BigQuery via a DataFrame abstraction from within a Jupyter notebook would be really powerful. I may get some cycles to hack on a BigQuery backend for Ibis later this fall. I'm curious and interested in Ibis but have little experience using it and zero understanding of the internals. Mostly, I just see value in general (BigQuery is really good) and the opportunity within Spotify. Very much at the preliminary stage where I'm exploring the possibility and trying to grasp what would be involved.

I have a few basic questions:

- What's the current state of Ibis development and adoption? Releases slowed last year but seem to have picked up recently. Just want to make sure there's still momentum before jumping in.

- What would be involved in writing a BigQuery backend? What are the major steps? Hard bits? (Let's assume we would only support standard SQL to make things easier. Legacy SQL is on the way out.)

- How big of an undertaking is it? 1-2 months for a single developer? 6-9 months?

- Not sure how BigQuery compares to Impala, but it does have certain quirks. Any thoughts on how to handle (possibly) BQ-specific things like: nested records, repeating records, JavaScript UDFs, approximate aggregation functions (and BQ-specific functions more generally)?

Looking forward to learning more!

**Comment by wesm** [comment]
hi @jpvelez, indeed there was a lull with Ibis development in 2016, but we have picked things back on and will be continuing to build out and support the SQL backends. You can see a Clickhouse backend that's in development in an active pull request, for example.

Building a backend for BigQuery has been on our wishlist for a long time, so we would be keen to help you make it happen (including weird stuff, like JS-based UDFs). I think you could have something pretty solid in 3 months or less; the incremental development work of adding new SQL engines is not that great. Both @cpcloud and I can help a lot and answer questions; the initial learning curve may be a bit steep as you work through the details of how a query gets generated. Once you set up the basic skeleton of the SQL "compiler", adding incremental new functionality becomes relatively straightforward. 

Do you think Spotify would be able to contribute a test instance of GBQ so that we could add this to our continuous integration at some point?

**Comment by cpcloud** [comment]
@jpvelez Excited to get started here!

> What's the current state of Ibis development and adoption? Releases slowed last year but seem to have picked up recently. Just want to make sure there's still momentum before jumping in.

There's definitely momentum. I'm spending a fair amount of my work time building out the pandas backend right now. I'm also happy to spend some of that time guiding you through a BigQuery backend.

> What would be involved in writing a BigQuery backend? What are the major steps? Hard bits? (Let's assume we would only support standard SQL to make things easier. Legacy SQL is on the way out.)

This depends on how much control you want over the execution and/or the limitations/features of the client library of your choosing. For example, the impala backend builds strings and executes them using `impyla` which provides an API for execution through a thrift service.

On the other hand, the postgres and sqlite backends pretty much just turn ibis expressions into equivalent sqlalchemy expressions and use whatever is the default driver for the respective backend.

I suspect a BigQuery backend will be closer to impala and would generate SQL strings that are passed to the google cloud client library APIs.

Here are the major parts needed for a new backend:

1. Client libraries, including support for executing queries, and retrieving schema metadata. I would imagine the google cloud libs have support for both of these things.
1. A backend specific `ibis.client.Client` subclass. This implements `execute`, `table`, `database` (if applicable) and a few other methods necessary to execute expressions.
1. Translation rules. These are the individual operations (living in `ibis/expr/operations.py`) that a backend translates into its native tongue. For example the `Mean` operation gets translated into `'AVG({})'.format(operand)` in the impala backend.
1. Continuous integration. This can be a huge pain to setup, but is wonderful to have once it's working. I've done a lot of this for ibis, so I can certainly take on some of this work if it becomes a blocker. We'd need a reliably available big query instance to test against. If Spotify could provide the BQ instance, that would be extremely helpful.

> How big of an undertaking is it? 1-2 months for a single developer? 6-9 months?

Hard to say exactly, but I think @wesm's number of 3 months sounds like a good place to start.

> Not sure how BigQuery compares to Impala, but it does have certain quirks. Any thoughts on how to handle (possibly) BQ-specific things like: nested records, repeating records, JavaScript UDFs, approximate aggregation functions (and BQ-specific functions more generally)?

We're definitely interested in supporting the quirky things.

1. Nested/repeated records. These are common enough that we should support them in as many backends as we can. This would require some API design around things like `UNNEST()` for example. We also would need to build out execution support for maps and struct types (we have `array`s). These could be done after or as the major pieces of the core backend are implemented.
1. BQ-specific functions. I'm not sure how we want to handle this. Ultimately it might be best to have a separate repo that contains the BQ specific expressions and the API hook-ins, but we can certainly get to a v0.0.1 before we need to make that decision.

Looking forward to working on this with you!

**Comment by jpvelez** [comment]
Hi @wesm,

Many thanks for your speedy and thorough reply, and great to hear. The soonest I'd be able start is in a month or two, depends on internal priorities etc.

If I end up working on this, I'm sure we'd be able to make a GBQ project available.

I'll be in touch in the next month or two. Thanks again!

**Comment by wesm** [comment]
Since we will probably end up needing to share quite a bit of code amongst different SQL backends, this will probably be best to develop at `ibis/bigquery` rather than as a separate codebase -- we'll be happy to give you commit privileges as you get spun up. This also helps us refactor without breaking any of your tests

**Comment by cpcloud** [comment]
@wesm @jpvelez Yep, agreed. Staying in the same codebase is ideal. It's very likely that we'll want to reuse a lot of the impala translation code and generalize it to other backends in the process of writing this backend.
