### ISSUE TITLE
feat: support for UNNEST (array flatten operation)

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1146]
Each of the following systems has a slightly different way of expressing flattening of arrays:

Given a table `t`:

``` sql
CREATE TABLE t (
  elements ARRAY<STRING>
)
```

Hive:

``` sql
SELECT element
FROM t
LATERAL VIEW EXPLODE(elements) s AS element;
```

Presto and PostgreSQL:

``` sql
SELECT s.element
FROM t
CROSS JOIN UNNEST(elements) AS s (element)
```

Impala:

``` sql
SELECT elements.item
FROM t, t.elements
```

BigQuery:

```sql
SELECT element
FROM t.elements

-- or

SELECT element
FROM UNNEST(t.elements)
```

Clickhouse:

```sql
SELECT elements
FROM t ARRAY JOIN elements
```

This issue is to track crafting an API for this operation in Ibis.

**Comment by frederikfab** [comment]
I understand that complexity is high on this. This is the one issue that has kept me from using Ibis at two different companies that are using BigQuery, so consider me interested.

As a workaround I could unnest to a materialized view on the server side, and re-write the resulting compiled SQL back to work from the source table. As hack to reduce complexity, might be to let Ibis unnest all tables with CTEs (common table expressions) and work off of those behind the scenes, but I am not aware of additional complexity this causes in Ibis compilations.

**Comment by cpcloud** [comment]
@frederikfab I know it's been quite a long time, but we finally got around to implementing unnest for BigQuery in #5767.
