### ISSUE TITLE
Spark backend

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#1157]
from https://github.com/ibis-project/ibis/issues/1120#issuecomment-322890973

a module to generate spark sql

**Comment by kszucs** [comment]
Which one should we use: DataFrame API or  Spark SQL?

**Comment by kszucs** [comment]
@cpcloud should `0.15` aim for a functional Spark backend?

**Comment by ryan-pip** [comment]
Is anyone working on this, is there a branch or fork somewhere?

**Comment by wesm** [comment]
Not that I'm aware of. We'd welcome the help, of course

**Comment by cpcloud** [comment]
@amroid Is now working on this.

**Comment by cpcloud** [comment]
Closing this out, going to make a bunch of issues and tie them to the Spark project.
