### ISSUE TITLE
'SET LOCAL TIMEZONE = UTC') causes crash on Redshift with postgres driver

### ISSUE THREAD

**Issue by FedericoV** [ibis-project/ibis#1158]
Hi everyone,

quick comment.  Using IBIS to interface with redshift with a postgres driver works very well (especially considering it's not explicitly supported!) - but in one of the last few versions, there was a change that broke all queries.

Specifically, I had to comment out:

     @contextlib.contextmanager
     def begin(self):
         with super(PostgreSQLClient, self).begin() as bind:
-            bind.execute('SET LOCAL TIMEZONE = UTC')
+            #bind.execute('SET LOCAL TIMEZONE = UTC')
             yield bind

in

diff --git a/ibis/sql/postgres/client.py b/ibis/sql/postgres/client.py

To get queries to continue working.  What's a slightly more principled way of doing this - should I catch an exception and ignore it?

**Comment by cpcloud** [comment]
The problem here is that redshift doesn't support setting a timezone for the duration of a transaction. We can work around this by getting the current timezone -> setting to the new one -> setting back to the original

**Comment by FedericoV** [comment]
Hi,

apparently the bug returned in the latest version of Ibis:

```
InternalError: (psycopg2.InternalError) current transaction is aborted, commands ignored until end of transaction block
 [SQL: "SET TIMEZONE = 'UTC'"]
```

This is on version '0.12.0+24.gb531c26'
