### ISSUE TITLE
timedelta and postgres?

### ISSUE THREAD

**Issue by John-Boik** [ibis-project/ibis#1160]
Hello. I'm using Ibis to interact with a postgres db. Some tables have timestamp fields, and I don't see how to filter using timedelta athmetic. For example, the code:

```
minutes10 = numpy.timedelta64(10, 'm')
result = my_table[my_table.my_timestamp1 - minutes10 > my_table.my_timestamp2] 
```
produces the error:
`TypeError: Cannot cast ufunc greater_equal input from dtype('<m8[m]') to dtype('<m8') with casting rule 'same_kind'`

I've tried various versions of this code, and can't seem to find anything that works. For example, this:
`minutes10 = datetime.timedelta(0,60*10)`

produces the error:
`TypeError: unsupported operand type(s) for -: 'TimestampColumn' and 'datetime.timedelta'`

Is this kind of timedelta arithmetic implemented? Is there a workaround?

**Comment by cpcloud** [comment]
We have not implemented this yet. I don't think there's a workaround here. You could potentially turn the `timestamp` columns into integer columns and perform the arithmetic and unit conversion "by hand" but we can't cast `timestamp` columns to integers right now.

**Comment by kszucs** [comment]
@John-Boik with the current master (soon to be released) the following should be possible:

```python
import ibis

t = ibis.table([
    ('ts1', 'timestamp'), 
    ('ts2', 'timestamp')
])

t.ts1 - ibis.interval(minutes=10) > t.ts2
```

@cpcloud If this verified we might close this issue.

**Comment by cpcloud** [comment]
This is working on master:

```
In [23]: con = ibis.postgres.connect(user='postgres', port=5432, host='localhost', database='ibis_testing', password='postgres')

In [24]: t = con.table('functional_alltypes')

In [25]: t[t.timestamp_col, (t.timestamp_col - ibis.day(2)).name('delta')].head().execute()
Out[25]:
            timestamp_col                   delta
0 2010-11-01 00:00:00.000 2010-10-30 00:00:00.000
1 2010-11-01 00:01:00.000 2010-10-30 00:01:00.000
2 2010-11-01 00:02:00.100 2010-10-30 00:02:00.100
3 2010-11-01 00:03:00.300 2010-10-30 00:03:00.300
4 2010-11-01 00:04:00.600 2010-10-30 00:04:00.600
```
