### ISSUE TITLE
Add a method to exprs to get all data leaves

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1168]
We have `.op().root_tables()` but that is for a different use case. This would be a method that returns every `PhysicalTable` from which an expression is derived. Maybe `_leaves()`?

**Comment by wesm** [comment]
Seems reasonable, or `_data_leaves` if you wanted to be more explicit

**Comment by kszucs** [comment]
How about a function in `analysis` using `lineage.traverse`?

Expressions already have a lot of methods, when I was learning ibis I've found `_root_tables` a bit confusing too.

**Comment by cpcloud** [comment]
This would reduce duplication a bit, but not sure it's worth the effort. `lineage.traverse` can be used instead for now.
