### ISSUE TITLE
Consider simpler integer promotion rules

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1171]
Take [Julia's promotion rules](https://docs.julialang.org/en/stable/manual/conversion-and-promotion/#Promotion-1) for example:
> Integer values are promoted to the larger of either the native machine word size or the largest integer argument type.

**Comment by wesm** [comment]
One potential question is that many SQL databases (probably for legacy reasons) prefer int / int32 to bigint / int64 as a default "integer". So if we did:

`df.int_col + 2` then if by default we consider "2" to be bigint, then we may cause an unwanted promotion (maybe we are always promoting here anyway)

**Comment by cpcloud** [comment]
This was motivated by a sharp edge, but I don't remember what it was, so closing.
