### ISSUE TITLE
Parquet back end

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#1175]
once #1167 is in, this should be straightforward

we should directly depends on ``pyarrow``. docs are [here](https://arrow.apache.org/docs/python/parquet.html).

this will nicely support projection and predicate pushdown & writing.

**Comment by jreback** [comment]
@wesm, @cpcloud

**Comment by wesm** [comment]
Nice. As we get the pieces in place for native predicate pushdown we should make sure it works well early on for Ibis
