### ISSUE TITLE
Clickhouse any, anyLast reductions

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1191]
Clickhouse have `any` and `anyLast` [aggregation functions](https://clickhouse.yandex/docs/en/agg_functions/index.html).
Ibis supports `first_value` and `last_value` on window operations which is not currently implemented in clickhouse. Also, `any` method already implemented for boolean columns.

How should I name `any` and `anyLast` reductions? 
As a fallback I might automatically render columns not under an aggregate function as `any(column)` in `ClickhouseSelect.format_select_set`.

Ideas?

cc @cpcloud

**Comment by cpcloud** [comment]
@kszucs Thanks for bringing this up. I know @tsdlovell has been thinking about this as well.

How about this:

* `any` -> `first_encountered`
* `anyLast` -> `last_encountered`

I think long term we probably want to have `first_value` and `last_value` here, but that requires a mechanism to translate a `Reduction` subclass differently depending on whether it's used as a window function vs an aggregation.

If you want to take a crack at doing that, I will happily review that PR. Also happy to talk further.

**Comment by kszucs** [comment]
Which backends are supporting this kind of aggregations?

**Comment by cpcloud** [comment]
Just BigQuery right now, but we could easily ship a postgres UDF/UDAF that does `first_encountered`.

**Comment by cpcloud** [comment]
I'm unaware of anything other than clickhouse that supports `anyLast`

**Comment by kszucs** [comment]
So should I implement `first|last_encountered` reductions? Maybe a shorter name? :)
How about just `first` and `last`?  Are those too short?

**Comment by cpcloud** [comment]
I'm going to make a generic issue for this.

**Comment by cpcloud** [comment]
Closing in favor of #1230
