### ISSUE TITLE
feat: file back end enhancements

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#1195]
after #1194 and #1167 (csv projection is done via ``pre_execute``)

- [ ] push down filtering to HDF5
- [ ] push down filtering & projection to parquet
- [ ] handle partitioned parquet dirs

**Comment by cpcloud** [comment]
@jreback Were any of these done in your recent PR?

**Comment by jreback** [comment]
no these are open. I did push down for projection on CSV reading as an example.

**Comment by cpcloud** [comment]
Ok, cool.

**Comment by cpcloud** [comment]
We're planning to remove most of these file based backends and either suggest alternatives to users or recommend backends such as datafusion as the alternative.
