### ISSUE TITLE
Semaphore array management and cleanup in production

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#12]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Tuesday Dec 09, 2014 at 21:15 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/12_

---

In pathological cases, Impala nodes could run out of semaphore arrays, which are currently being used for IPC. One solution is to clear them all out when spinning up the cluster. Here's one method to do that

```
#!/bin/bash
USER=`whoami`
SEMAPHORES=`ipcs -s | egrep "0x[0-9a-f]+ [0-9]+" | grep $USER | cut -f2 -d" "`
for id in $SEMAPHORES; do
  ipcrm -s $id;
done
```

**Comment by cpcloud** [comment]
This code has been removed.
