### ISSUE TITLE
ENH/PERF: Add cached_property to get a list of all clients from which an expression is derived

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1201]
The most common case is a single client (or no client for an `UnboundTable`), but there are cases where there are multiple clients on which an expression is based.

**Comment by kszucs** [comment]
AFAIK currently ibis disallows that https://github.com/ibis-project/ibis/blob/master/ibis/client.py#L324

@cpcloud 0.14?

**Comment by cpcloud** [comment]
Right, I want to remove the limitation that prevents at least *exploring* expressions that contain multiple backends.

**Comment by cpcloud** [comment]
Whether or not they can be executed should be decided somewhere else I think. I need to play with this a bit before deciding on an interface.

**Comment by kszucs** [comment]
BTW I'd really like to see this feature implemented.

**Comment by cpcloud** [comment]
This might be needed as part of multi backend execution, but I don't think it's very valuable on its own.
