### ISSUE TITLE
QA: is there a strategic way to replace UnboundTable with PandasTable in Expr?

### ISSUE THREAD

**Issue by collinwo** [ibis-project/ibis#1206]
We have a use case that data scientists want to write TableExpr on Dataframe in client side(notebook), but execute it in server side. So, we can avoid to download large dataframe in client side. So, we may have to replace UnboundTable with PandasTable in Expr in server side.

**Comment by cpcloud** [comment]
@collinwo It's interesting you bring this up. I was recently discussing something like this with @jreback.

It sounds like you want a way to execute pandas backend expressions on a server, and send the result back to the client.

The biggest missing pieces to do this are a way to serialize/deserialize an ibis expression and a small server implementation.

I think we would also need something like a `Server` backend that would allow you operate on *any* tables sitting on a server.

Just spitballing here, but how about something like this:

```pyhton
>>> con = ibis.server.connect('user:pass@host:port')
>>> t = con.table('t')  # this table is on some server somewhere
>>> t.value_column.sum().execute()  # sends a JSON serialized expression to the server and sends the response back as a serialized dataframe (probably msgpack or pickle to start)
```

**Comment by collinwo** [comment]
Yes, your example will be ideal! However, before we have it, I want to prove that Ibis can solve our problem. So, I can convince my clients and colleagues;)

Currently, we setup a tornado server to handle dataframe querying. Currently, my workaround will be:
1. Use fake(empty) dataframes to create PandasClient in server side;
2. De-serialize PandasClient in client side;
3. User add filtering, composing and execute;
4. execute in client will be send back to server side;
5. Find a way replace fake dataframes in de-serialize PandasClient from client side....

I didn't find a good way to do it in step5 yet...Or maybe there is more elegant way?

**Comment by cpcloud** [comment]
This is a great use case. It's probably out of scope for ibis itself right now, but stay tuned!
