### ISSUE TITLE
Define a method that returns a Selection's used physical columns

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1218]

**Comment by kszucs** [comment]
Does it depend on https://github.com/ibis-project/ibis/issues/1168 ?
Does a physical column only able to originate from physical table?

For extracting the `PhysicalTable`'s I guees there is already an implementation for that: https://github.com/ibis-project/ibis/blob/master/ibis/expr/lineage.py#L14

**Comment by kszucs** [comment]
With `lineage.traverse` it should not be so hard.

**Comment by cpcloud** [comment]
Agree, though not sure if this will make it into 0.13.

**Comment by kszucs** [comment]
Agree, if nothing depends on physical columns we might delay it.

**Comment by cpcloud** [comment]
Nothing except #1334 :)

**Comment by kszucs** [comment]
0.14?
