### ISSUE TITLE
Strategy for crufty timestamp functions

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#122]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Thursday Mar 05, 2015 at 07:15 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/122_

---

Some date/time functions accept strings while others accept date/timestamp types. Perhaps we should add functional APIs that are more flexible

**Comment by cpcloud** [comment]
Closing as stale.
