### ISSUE TITLE
MySQL backend

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1224]
I guess mysql would be a nice to have backend.

Should it be based on the alchemy backend or the [sql compiler](https://github.com/ibis-project/ibis/blob/master/ibis/sql/compiler.py) (like impala, clickhouse and bigquery)?

**Comment by wesm** [comment]
This would also provide MemSQL support. I will see if anyone from over there would be interested in contributing

**Comment by kszucs** [comment]
Sounds great, thanks!

**Comment by kszucs** [comment]
@cpcloud BTW what's the advantage of maintaining both sqlalchemy and a custom compiler backends?

**Comment by wesm** [comment]
Depends on how well sqlalchemy supports the underlying SQL backend. In the case of Impala and BigQuery there's a lot of stuff that is challenging to support in SQLAlchemy (or maybe it's that we don't know how to use it well enough)

**Comment by kszucs** [comment]
I get it, but also bothers me a bit. 

When I look at ibis' custom compiler it feels like another sqlalchemy.
When I look at sqlalchemy backends it feels like I have double vision, mapping ibis expr to sa expr.

Couldn't we move away from either one? (I know there are pros&cons for both backend types)
