### ISSUE TITLE
ENH: Union in BigQuery

### ISSUE THREAD

**Issue by pteehan** [ibis-project/ibis#1227]
Hello, 

I noticed Union is not implemented in the BigQuery backend. 

t0 and t1 are both expressions with identical schemas: 
```` python
t0.union(t1).compile()

/usr/local/lib/python3.5/dist-packages/ibis/bigquery/compiler.py in _union_class(self)
     27     def _union_class(self):
     28         # return BigQueryUnion
---> 29         raise NotImplementedError()
     30 
     31 

NotImplementedError: 
````
I thought maybe BigQuery didn't support Union, but it does, if you use Standard SQL. https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#union  So I guess this just isn't yet supported in Ibis.

Any plans to implement this, and any ideas for a workaround, if I need a Union operation in BigQuery?  Thank you.

**Comment by cpcloud** [comment]
Hi @pteehan, we'll add support for this in the next release (0.14.0).

**Comment by cpcloud** [comment]
This is working in master.
