### ISSUE TITLE
ENH: Support timestamp, date, and time arithmetic

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1228]
Currently substraction is not supported on timestamp and date fields.

An expression like the following feels really intuitive:

```py
ibis.now() - ibis.timestamp(table.created_at)
```

Clickhouse directly supports minus on date and timestamp fields:

```sql
SELECT toDate('2017-01-03') - toDate('2017-01-01') => 2[d]
```

```sql
SELECT now() - toStartOfDay(now()) => 32588[s]
```

**Comment by cpcloud** [comment]
This will require #1233.

**Comment by cpcloud** [comment]
@kszucs What is the type of the `2[d]` value? Is it some kind of `INTERVAL` type?

**Comment by kszucs** [comment]
Clickhouse returns integers, day precision in case of dates, second precision in case of datetimes.
BTW they [support interval operations](https://github.com/yandex/ClickHouse/blob/3a1f17ba7dbc3bb7554e800423db3aa923762b19/dbms/tests/queries/0_stateless/00514_interval_operators.sql) in the current master.

**Comment by kszucs** [comment]
```py
date_parts = Y|M|w|d
time_parts = h|m|s|ms|us|ns 
smallest_time_part = s[or ns]  # there could be difficulties per backend
any = date_parts + time_parts

Date - Date = Interval()
Date - Interval(date_parts) = Date
Date + Interval(time_parts) = Date
Interval(date_parts) + Date = Date

Timestamp - Interval(any) = Timestamp
Timestamp + Interval(any) = Timestamp
Interval(any) + Timestamp = Timestamp

Date - Timestamp = Interval(smallest_time_part)
Timestamp - Date = Interval(smallest_time_part)
Timestamp - Timestamp = Interval(smallest_time_part)
Timestamp + Interval(any) = Timestamp
Timestamp - Tnterval(any) = Timestamp

Interval(T) - Interval(T) = Interval(T)  # simple int arithmetics
Interval(T) + Interval(T) = Interval(T)
Interval(time_parts) + Interval(time_parts) = Interval(s)  # fixed sized unit conversions
Interval(time_parts) - Interval(time_parts) = Interval(s)
```

Should I implement generic operations like `TemporalSubtract`, `IntervalSubstract`, `IntervalAdd` with custom upcasting logics, or separate them to more specified operations?

**Comment by cpcloud** [comment]
Let's start by *not* allowing different typed temporal arithmetic. Folks can always up or downcast themselves while we don't have it and we can add it after the first round of this functionality is merged into master.

With that out of the way, let's focus on the following operations (leaving out the reversed operand versions):

```
date - date == interval
date +/- interval == date

timestamp - timestamp == interval
timestamp +/- interval == timestamp

time - time == interval
time +/- interval == time

interval +/- interval == interval
```

Each operator gets its own class: `DateAdd`, `DateSubtract` (handles both `date` and `interval` operands) and you'll need to define an `output_type` method that determines the output type of the operation depending on whether the right operand is a date or an interval.

We will also need to support `interval(T).cast(interval(U))` to enable simple unit conversion, e.g., seconds to microseconds.

As for the `smallest_time_part` issue, we can choose a default (nanoseconds?) and we can multiply the result by 1,000,000,000 in the backend specific translation rule.

How does that sound?

**Comment by cpcloud** [comment]
this is fixed in https://github.com/ibis-project/ibis/commit/48306f8cbedcea74dd1466c65f3a8811bd730c00
