### ISSUE TITLE
ENH: Full support for interval (timedelta) types

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1233]
We have partial support for this. We should extend this to include an `Interval` type in type system, a rule, and the ability to specify tables with columns of this type.

**Comment by kszucs** [comment]
I guess we should handle `Interval` types like the `Timedelta`, an integer with a unit (or precision) metadata. 
AFAIK [bigquery](https://cloud.google.com/bigquery/docs/reference/legacy-sql#datediff), [clickhouse](https://github.com/ibis-project/ibis/issues/1228) and [impala](https://www.cloudera.com/documentation/enterprise/5-8-x/topics/impala_datetime_functions.html) handle single units, only Postgres supports [complex units](https://www.postgresql.org/docs/9.1/static/functions-datetime.html).
