### ISSUE TITLE
ENH: JavaScript UDFs for BigQuery

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1236]
This isn't a Python to JS transpiler :) I'm thinking about an interface where a user writes down the input and output types (maybe as ibis rules) and we generate the UDF scaffolding (https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions). The user would also provide a string containing JS that is the body of the function.

**Comment by kszucs** [comment]
WIP https://github.com/ibis-project/ibis/pull/1377

**Comment by cpcloud** [comment]
Closed by #1377
