### ISSUE TITLE
ENH/TST: Factor out tests that test functionality that every backend implements

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1237]
... and make that into one test file that uses a pytest parametrized fixture (https://docs.pytest.org/en/latest/fixture.html#fixture-parametrize). This allows us to use the same set of common-base-functionality tests for every backend.

**Comment by kszucs** [comment]
Ideally every backend should be able to compile and execute any ibis expressions.

We could maintain an `expression => expected result` mapping somewhere (e.g. in ibis.expr package) which every backend tries to execute. 
In case of unsupported operation the backend should raise the appropriate exception. This way we could even generate an operation support matrix (table) to the docs

**Comment by cpcloud** [comment]
We've had this for a while now.
