### ISSUE TITLE
Does ibis.pandas support isin ?

### ISSUE THREAD

**Issue by collinwo** [ibis-project/ibis#1246]
I tried to use expression like dt = t[t.key.isin([1,2,3,4,5,6,7,8])], but got error.

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> /opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
>     154         try:
> --> 155             func = self._cache[types]
>     156         except KeyError:
> 
> KeyError: (<class 'ibis.expr.types.ValueList'>,)
> 
> During handling of the above exception, another exception occurred:
> 
> NotImplementedError                       Traceback (most recent call last)
> <ipython-input-15-7f0a785d6dd1> in <module>()
>      17 t = c.table('df')
>      18 dt = t[t.key.isin([1,2,3,4,5,6,7,8])]
> ---> 19 c.execute(dt)
> 
> /opt/conda/lib/python3.6/site-packages/ibis/pandas/client.py in execute(self, query, params, limit, async)
>      99 
>     100         assert isinstance(query, ir.Expr)
> --> 101         return execute(query, params=params)
> 
> /opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
>     162             self._cache[types] = func
>     163         try:
> --> 164             return func(*args, **kwargs)
>     165 
>     166         except MDNotImplementedError:
> 
> /opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in execute_without_scope(expr, params, scope, context, **kwargs)
>     179         new_scope,
>     180         context=context if context is not None else agg_ctx.Summarize(),
> --> 181         **kwargs
>     182     )
> 
> /opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
>     162             self._cache[types] = func
>     163         try:
> --> 164             return func(*args, **kwargs)
>     165 
>     166         except MDNotImplementedError:
> 
> /opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in execute_with_scope(expr, scope, context, **kwargs)
>     125         scope=scope,
>     126         context=context,
> --> 127         **kwargs
>     128     )
>     129 
> 
> /opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
>     162             self._cache[types] = func
>     163         try:
> --> 164             return func(*args, **kwargs)
>     165 
>     166         except MDNotImplementedError:
> 
> /opt/conda/lib/python3.6/site-packages/ibis/pandas/execution/selection.py in execute_selection_dataframe(op, data, scope, **kwargs)
>     334             op.table.op(), predicates, data, scope, **kwargs
>     335         )
> --> 336         predicate = functools.reduce(operator.and_, predicates)
>     337         assert len(predicate) == len(result), \
>     338             'Selection predicate length does not match underlying table'
> 
> /opt/conda/lib/python3.6/site-packages/ibis/pandas/execution/selection.py in _compute_predicates(table_op, predicates, data, scope, **kwargs)
>     215 
>     216         new_scope = toolz.merge(scope, additional_scope)
> --> 217         yield execute(predicate, new_scope, **kwargs)
>     218 
>     219 
> 
> /opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
>     162             self._cache[types] = func
>     163         try:
> --> 164             return func(*args, **kwargs)
>     165 
>     166         except MDNotImplementedError:
> 
> /opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in execute_with_scope(expr, scope, context, **kwargs)
>     117         execute(arg, scope, context=context, **kwargs)
>     118         if hasattr(arg, 'op') else arg
> --> 119         for arg in args if isinstance(arg, _VALID_INPUT_TYPES)
>     120     ]
>     121 
> 
> /opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in <listcomp>(.0)
>     117         execute(arg, scope, context=context, **kwargs)
>     118         if hasattr(arg, 'op') else arg
> --> 119         for arg in args if isinstance(arg, _VALID_INPUT_TYPES)
>     120     ]
>     121 
> 
> /opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
>     162             self._cache[types] = func
>     163         try:
> --> 164             return func(*args, **kwargs)
>     165 
>     166         except MDNotImplementedError:
> 
> /opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in execute_with_scope(expr, scope, context, **kwargs)
>     125         scope=scope,
>     126         context=context,
> --> 127         **kwargs
>     128     )
>     129 
> 
> /opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
>     159                 raise NotImplementedError(
>     160                         'Could not find signature for %s: <%s>' %
> --> 161                         (self.name, str_signature(types)))
>     162             self._cache[types] = func
>     163         try:
> 
> NotImplementedError: Could not find signature for execute_node: <ValueList>
> 
> 
> 

Example
```
import numpy as np
import pandas as pd

import ibis
import ibis.expr.datatypes as dt
from ibis.pandas import api
n=10
data = pd.DataFrame({
        'key': np.random.choice(10, size=n),
        'value': np.random.rand(n),
        'timestamp_strings': pd.date_range(
            start='now', periods=n, freq='s'
        ).values.astype(str),
    })
data_dict = {'df': data}
c = api.connect(data_dict)
t = c.table('df')
dt = t[t.key.isin([1,2,3,4,5,6,7,8])]
c.execute(dt)
```

**Comment by wesm** [comment]
Looks like it just has not been implemented

**Comment by cpcloud** [comment]
@collinwo Are you running against master? This functionality was added here: 9b76701d.

**Comment by collinwo** [comment]
I pick up 0.12.0 version. What is the plan of next release, e.g. 0.13.0?

**Comment by cpcloud** [comment]
@collinwo can you show the final multipledispatch error in your report? the last part about which types it cannot find is missing, and that's the most important one :)

**Comment by collinwo** [comment]
Hmmm.... I can't remember the multipledispatch err. Do you mean unpickle err that I reported?
 https://github.com/ibis-project/ibis/issues/1197
I tested with latest master, which it fixed the err.

**Comment by cpcloud** [comment]
No, I mean the last bit of the error message you show here

**Comment by collinwo** [comment]
Full error message:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    154         try:
--> 155             func = self._cache[types]
    156         except KeyError:

KeyError: (<class 'ibis.expr.types.ValueList'>,)

During handling of the above exception, another exception occurred:

NotImplementedError                       Traceback (most recent call last)
<ipython-input-3-d07bd652649a> in <module>()
----> 1 cnn.execute(dtt)

/opt/conda/lib/python3.6/site-packages/waveconnect/connect.py in execute(self, pd_expr, time_out)
    223         if res.ok:
    224             dataset_table.source.dictionary[dataset_table.name] = pd.DataFrame(res.json().get('data')).T
--> 225             return self._ibis_pd_client.execute(pd_expr)
    226 
    227         self._bad_response(res)

/opt/conda/lib/python3.6/site-packages/ibis/pandas/client.py in execute(self, query, params, limit, async)
     99 
    100         assert isinstance(query, ir.Expr)
--> 101         return execute(query, params=params)

/opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in execute_without_scope(expr, params, scope, context, **kwargs)
    179         new_scope,
    180         context=context if context is not None else agg_ctx.Summarize(),
--> 181         **kwargs
    182     )

/opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in execute_with_scope(expr, scope, context, **kwargs)
    117         execute(arg, scope, context=context, **kwargs)
    118         if hasattr(arg, 'op') else arg
--> 119         for arg in args if isinstance(arg, _VALID_INPUT_TYPES)
    120     ]
    121 

/opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in <listcomp>(.0)
    117         execute(arg, scope, context=context, **kwargs)
    118         if hasattr(arg, 'op') else arg
--> 119         for arg in args if isinstance(arg, _VALID_INPUT_TYPES)
    120     ]
    121 

/opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in execute_with_scope(expr, scope, context, **kwargs)
    117         execute(arg, scope, context=context, **kwargs)
    118         if hasattr(arg, 'op') else arg
--> 119         for arg in args if isinstance(arg, _VALID_INPUT_TYPES)
    120     ]
    121 

/opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in <listcomp>(.0)
    117         execute(arg, scope, context=context, **kwargs)
    118         if hasattr(arg, 'op') else arg
--> 119         for arg in args if isinstance(arg, _VALID_INPUT_TYPES)
    120     ]
    121 

/opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in execute_with_scope(expr, scope, context, **kwargs)
    125         scope=scope,
    126         context=context,
--> 127         **kwargs
    128     )
    129 

/opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/opt/conda/lib/python3.6/site-packages/ibis/pandas/execution/selection.py in execute_selection_dataframe(op, data, scope, **kwargs)
    334             op.table.op(), predicates, data, scope, **kwargs
    335         )
--> 336         predicate = functools.reduce(operator.and_, predicates)
    337         assert len(predicate) == len(result), \
    338             'Selection predicate length does not match underlying table'

/opt/conda/lib/python3.6/site-packages/ibis/pandas/execution/selection.py in _compute_predicates(table_op, predicates, data, scope, **kwargs)
    215 
    216         new_scope = toolz.merge(scope, additional_scope)
--> 217         yield execute(predicate, new_scope, **kwargs)
    218 
    219 

/opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in execute_with_scope(expr, scope, context, **kwargs)
    117         execute(arg, scope, context=context, **kwargs)
    118         if hasattr(arg, 'op') else arg
--> 119         for arg in args if isinstance(arg, _VALID_INPUT_TYPES)
    120     ]
    121 

/opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in <listcomp>(.0)
    117         execute(arg, scope, context=context, **kwargs)
    118         if hasattr(arg, 'op') else arg
--> 119         for arg in args if isinstance(arg, _VALID_INPUT_TYPES)
    120     ]
    121 

/opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/opt/conda/lib/python3.6/site-packages/ibis/pandas/core.py in execute_with_scope(expr, scope, context, **kwargs)
    125         scope=scope,
    126         context=context,
--> 127         **kwargs
    128     )
    129 

/opt/conda/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    159                 raise NotImplementedError(
    160                         'Could not find signature for %s: <%s>' %
--> 161                         (self.name, str_signature(types)))
    162             self._cache[types] = func
    163         try:

NotImplementedError: Could not find signature for execute_node: <ValueList>


BTW, when will be the next release that includes isin feature?

**Comment by toryhaavik** [comment]
Let's try to recreate this, i have a feeling it's since been implemented

**Comment by cpcloud** [comment]
This has been implemented and has tests: https://github.com/ibis-project/ibis/blob/master/ibis/backends/pandas/tests/execution/test_operations.py#L531

Locally those tests pass and none are skipped:

```
❯ PYTEST_BACKENDS="pandas" pytest ibis/backends/pandas/tests/execution/test_operations.py::test_isin -q
....                                                                                                                                                                                                                                                    [100%]
4 passed in 0.17s
```
