### ISSUE TITLE
feat: SQL arbitrary functions without code modification

### ISSUE THREAD

**Issue by tsdlovell** [ibis-project/ibis#1257]
For tables, you can do `client.sql(SQL_STRING)` to get an ibis object for an abitrary sql string.  If something like this were possible for columns inside of tables, users could use more of the functionality of their particular backend before that functionality is actually built into ibis.

**Comment by kszucs** [comment]
I can imagine that as UDFs for sql backends, like for pandas in https://github.com/ibis-project/ibis/pull/1277

Translator helpers like `sa.func.<name>` could be handy too.

**Comment by cpcloud** [comment]
For example:

```sql
from ibis.func from_base64

t = ibis.table(dict(a="binary"))
from_base64(t.a, output_type="string")
```

**Comment by cpcloud** [comment]
This is possible with `.sql`:

```python
t.alias('my_table').sql("SELECT GREAT_FUNCTION(x) FROM my_table")
```
