### ISSUE TITLE
Subquery flattening optimization

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1258]
Ibis does a bit of this already, but there may be more opportunities for this kind of optimization that we are missing. We should investigate.

As an interesting related read, here are the criteria that SQLite uses to decide whether to flatten a subquery or not: https://sqlite.org/optoverview.html#flattening

**Comment by wesm** [comment]
I remember spending a good bit of time on this, but the optimizations implement are at best rudimentary

**Comment by cpcloud** [comment]
This is extremely difficult to get correct, so not doing it for the foreseeable future. With a better optimization framework in place we *might* have a shot at doing this.
