### ISSUE TITLE
Dead code elimination e.g., ifelse expression pruning

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1264]
We should look at doing expr pruning (in conditionals like ifelse) when there is a literal value that makes one condition never executed.

```py
ifelse(isnan(b), c, d)
```

and it turns out that F.isnan(b) yields the literal False, then this could be rewritten as simply `d` prior to execution

**Comment by cpcloud** [comment]
I think this is a special case of dead code elimination.

I think there are two optimizations that would enable more complete DCE

- unary/binary operator reassociation
  - looking through the llvm source here: http://llvm.org/doxygen/Reassociate_8cpp_source.html provides a lot of prior art in this space
- constant folding
  - this would happen after reassociation (and in certain cases could happen immediately during expression construction)
