### ISSUE TITLE
serialize ibis expressions

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#1267]
xref #1206 

We want to take an ibis expression, and serialize to JSON (or other format), send over the wire, then de-serialize back to an ibis expression.

``expr.to_json()``
``ibis.client.Client.from_json()``

might be a suitable interface.

**Comment by collinwo** [comment]
this will be a very nice feature!

**Comment by cpcloud** [comment]
Ultimately we will use Substrait for this, https://substrait.io.
