### ISSUE TITLE
ibis-server

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#1268]
xref #1267 
xref #1206 

in the same vein as [blaze-server](https://blaze.readthedocs.io/en/latest/server.html)

we would like to be able to run a process to evaluate client submitted ibis expressions. It would be nice to return the resulting ``DataFrame`` as an [Apache Arrow](http://arrow.apache.org/docs/python/) table.

**Comment by kszucs** [comment]
What's the priority level of this feature? Asking because we might schedule it to 0.15 in order to have a smaller milestone.

**Comment by cpcloud** [comment]
`ibis-sever` would be better outside of ibis
