### ISSUE TITLE
SUPP/CI: Add spark setup to CI

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#1270]
supporting #1157 

[circleci setup](https://github.com/ibis-project/ibis/blob/master/.circleci/config.yml) will need to have added configuration

**Comment by jreback** [comment]
cc @shshe

**Comment by kszucs** [comment]
This should probably be a spark standalone cluster running in a docker container. However we couldn't test that on appveyor.

**Comment by cpcloud** [comment]
Closed by #1807
