### ISSUE TITLE
docs: add docs for asof join

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis#1275]

**Comment by xmnlab** [comment]
some information: - https://github.com/ibis-project/ibis/blob/master/ibis/expr/api.py#L2957

some doc files that have information about join ops:

- ./docs/source/api.rst
- ./docs/source/sql.rst

**Comment by cpcloud** [comment]
There are API docs for this: https://ibis-project.org/docs/generated/ibis.expr.api.TableExpr.asof_join.html?highlight=asof_join
