### ISSUE TITLE
refactor: remove backend execution tests in favor of the full backend test configuration suite

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1286]

**Comment by kszucs** [comment]
These can be ported to full backend tests:
- cases containing [assert_series_equal](https://github.com/ibis-project/ibis/search?utf8=%E2%9C%93&q=assert_series_equal&type=)
- cases containing [assert_frame_equal](https://github.com/ibis-project/ibis/search?utf8=%E2%9C%93&q=assert_frame_equal&type=)

**Comment by cpcloud** [comment]
Will accept PRs
