### ISSUE TITLE
BUG: The nullable property is not propagated through primitive types

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1289]
Because the `type()` method just blindly returns instances of particular types (which are nullable by default).

**Comment by kszucs** [comment]
@cpcloud What should be the promotion logic for operation involving both nullable and non-nullable operands?

I guess if any of the operands are nullable then the result should be nullable, please confirm.

**Comment by kszucs** [comment]
Ohh, the implicit casting already nicely handles that.

**Comment by cpcloud** [comment]
@kszucs This was fixed by the PR that added `Argument` right?

**Comment by cpcloud** [comment]
Ah yes, looks like it does.
