### ISSUE TITLE
Compiling a join with an OR condition gives unexpected SQL

### ISSUE THREAD

**Issue by jeffgortmaker** [ibis-project/ibis#1308]
The following code

    t1 = ibis.table([('a', 'string'), ('b', 'string')], 't')
    t2 = t1.view()
    print(ibis.impala.compiler.to_sql(t1.join(t2, [t1.a == t2.a, (t1.a != t2.b) | (t1.b != t2.a)])[t1]))

gives

    SELECT t0.*
    FROM t t0
      INNER JOIN t t1
        ON t0.`a` = t1.`a` AND
           (t0.`a` != t1.`b`) OR (t0.`b` != t1.`a`)

whereas I would have expected

    SELECT t0.*
    FROM t t0
      INNER JOIN t t1
        ON t0.`a` = t1.`a` AND
           ((t0.`a` != t1.`b`) OR (t0.`b` != t1.`a`))

which is what `filter` does when one of multiple conditions is an OR condition.

**Comment by cpcloud** [comment]
FYI, `to_sql` is an internal function. Use `ibis.impala.compile` instead.

**Comment by cpcloud** [comment]
Also, this is correct code because `=` binds tighter than `OR` which binds tighter than `AND` so the parentheses are redundant.

**Comment by jeffgortmaker** [comment]
Thanks! Didn't realize that. I think my confusion came from the extra parentheses being added by something like `t1.filter([expression1, expression2 | expression3])`.

**Comment by jeffgortmaker** [comment]
Am I missing something? Using Impala, `select false and false or true` gives `true` but `select false and (false or true)` gives `false`.

Not sure where to look for Impala, but here's a reference for mysql: https://dev.mysql.com/doc/refman/5.7/en/operator-precedence.html

**Comment by cpcloud** [comment]
It's possible I misread the Impala grammar. I'll look into it.

**Comment by cpcloud** [comment]
Yep I definitely misread. This is a bug in Ibis. Slated for 0.13.

**Comment by jeffgortmaker** [comment]
Thanks again -- looking forward to the release.
