### ISSUE TITLE
When will 0.13 happen?

### ISSUE THREAD

**Issue by collinwo** [ibis-project/ibis#1310]
I raised several improvement and bug, which is fixed in 0.13. Although I built and used a latest version in our platform, it will be great to use a standard version that is released formally...

**Comment by wesm** [comment]
I should think 0.13 can go out in the next couple of weeks, I will let @cpcloud make the call

**Comment by cpcloud** [comment]
@collinwo @wesm That's what I was thinking as well. There are a few bugs to close out and a couple more features I'd like to get in.

**Comment by collinwo** [comment]
Perfect! Thank you!

**Comment by cpcloud** [comment]
0.13 is coming up shortly.
