### ISSUE TITLE
feat(api): isin should support array of scalars

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1312]
Array might not be the best idea, but here are the semantics:

```python
ids = ibis.param('array<int>')  

entity.id.isin(ids)
```

`ids` probably should be a variable length param list

**Comment by cpcloud** [comment]
There are other interesting cases like BigQuery's struct `IN` syntax: `(42, 'foo') in struct_col` that `isin` should probably also handle.

**Comment by cpcloud** [comment]
I think this makes the `isin` API confusing.

What if the right is a column of `array<T>` and the left is type `T`? Does that check if every element of the left side is in the corresponding right side array?

What if the both are columns of `array<T>`?

Stuffing all of these into a single `isin` API seems like it lead to user confusion and complicated code to handle all of these different cases.

I think we can add a `contains` operation to array expressions to support this case, but -1 on adding array type support to `isin`.

**Comment by cpcloud** [comment]
Closing this out for now. If someone asks for it, we can revisit adding an `ir.ArrayValue.contains` or similar API.
