### ISSUE TITLE
google library versions need to be specified for proxies?

### ISSUE THREAD

**Issue by tsdlovell** [ibis-project/ibis#1319]
I find I need to point to particular versions of some of the google libs to negotiate the proxy at my work.  Unclear if this is an issue for people who don't have to deal with a proxy.

When I didn't pip install like below, I got `google-auth==1.3.0` and that didn't work.

This works
```bash
pip install \
        git+https://:@github.com/ibis-project/ibis@v0.12.0 \
        google-cloud-bigquery==0.27.0 \
        google-auth==1.2.0 \
        google-api-core==0.1.1
```

**Comment by cpcloud** [comment]
I don't know if this is related to ibis or just to specific installations of dependencies of the bigquery backend. I'll look into this but probably not before the 0.13 release is cut.

**Comment by tswast** [comment]
I think https://github.com/ibis-project/ibis/pull/1424 should help with this. Later versions of `google-cloud-bigquery` use the `requests` library to make HTTP calls, which has better support for proxies than `httplib2` used by older versions of `google-cloud-bigquery`.

**Comment by cpcloud** [comment]
@tsdlovell Is this still an issue for you? Or was it solved by upgrading to >= 1.0.0?

**Comment by tsdlovell** [comment]
@cpcloud, last I checked this was still an issue for me.  IIRC, its because I couldn't make our internal proxified HTTPAdapter work with it.

Now that I understand this issue a little better, it's probably something more appropriate for our internal people and not ibis.  Feel free to close.

**Comment by cpcloud** [comment]
Cool. If there's anything we can do in ibis to make this easier, please reopen or create another issue if anything comes to mind.
