### ISSUE TITLE
Bake Python enums into the ibis type system

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1325]
Right now the `enum` rule doesn't convert Python enums to value expressions. We should fix that.

**Comment by kszucs** [comment]
[member_of](https://github.com/ibis-project/ibis/blob/master/ibis/expr/rules.py#L136) rule supports enums on a certain level. Is that what You have in mind?

**Comment by cpcloud** [comment]
Seems pretty low value right now.
