### ISSUE TITLE
Remove python 3.4 builds?

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1326]
Main reasons:
- on appveyor it takes 10 minutes from the total 25
- conda-forge doesn't make builds for 3.4 anymore

**Comment by cpcloud** [comment]
Yeah, this is a good idea. There isn't much point is spending this much time on testing something that is not in use.

**Comment by cpcloud** [comment]
Marking for 0.14, we'll remove it right after the 0.13 release.

**Comment by kszucs** [comment]
Great!
