### ISSUE TITLE
[RFC] ODBC backend connectors

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1327]
It's considerable for ibis to use turbodbc[with arrow], however the performance gains are not clear enough.
I'm willing to create conda-forge feedstocks for our currently supported backends, but considering the probable licensing issues and turbodbc's performance [warnings](http://turbodbc.readthedocs.io/en/latest/pages/databases/postgresql.html) it might not worth the effort.

What do You think?

**Comment by wesm** [comment]
For the moment, it's unclear whether it would be useful with the backends we support (until we have something that's only accessible via ODBC). For example, psqlodbc has pretty bad performance as I recall (it would be cool to have native Arrow-libpq bindings at some point, similar to https://github.com/MagicStack/asyncpg but not dependent on Python)
