### ISSUE TITLE
[RFC] Multi-backend expressions

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1328]
### Problem

Currently an expression must be bound to a single backend, however heterogeneous architectures are pretty common nowadays and it can be really painful to make them work together.

Enabling seamless interoperability between various backends would be a killing feature for ibis. 

### Examples

```python
authors = postgres_client.table('authors') 
commits = memsql_client.table('commits')

expr = t1.join(t2, t1.email == t2.author_email).aggregate(t2.count(), by=t1.email)
expr.execute()
```

or

```python
mindate = ibis.param('timestamp')
users = mysql_client.table('users')
stars = bigquery_client.table('stars')

daily_stars = clicks.aggregate(stars.count(), by=stars.created_at.date())
newcomers = users[users.registered_at >= mindate]

expr = daily_stars[stars.user_id.isin(newcomers.id)]
expr.execute()
```

### Possible Implementation

This could be generalized with pandas backend as the layer which connects the results coming from various backends. Of course this requires predicate pushdowns and proper warnings about preventing bulky results (e.g. "subqueries" without predicates).

### Backend specializations

A snippet like the above is sort of working with clickhouse (implemented in #1292), but that's really just an optimization enabled by clickhouse external tables. There might be other backends which can receive external data for query processing.

```python
authors = mysql_client.table('authors')
aliases = mysql_client.table('aliases')
commits = clickhouse_client.table('commits')

developers = authors.join(aliases, authors.id == aliases.author_id)
developers = developers[authors.name.name('name'), 
                        aliases.email.name('aemail')]

devs = ibis.clickhouse.external_table('developers', developers)
expr = (commits.join(devs, 'aemail')
               .aggregate(commits.count(), by=devs.name))
```

@cpcloud @wesm thoughts?

**Comment by wesm** [comment]
This is a big project to do in generality -- this is what the Dremio project does (Federated SQL https://github.com/dremio/dremio-oss). If we could enable this to work at a small scale (i.e. similar to what is possible in Blaze project https://github.com/blaze/blaze) that would be quite useful

**Comment by cpcloud** [comment]
This is the 800 pound gorilla in the SQL room. Pretty big undertaking.
