### ISSUE TITLE
Consider adding docker dns to docker-compose setup

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1330]
For example using [dns-proxy-server](https://github.com/mageddo/dns-proxy-server):

```sh
docker run --rm --hostname dns.mageddo --name dns-proxy-server -p 5380:5380 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /etc/resolv.conf:/etc/resolv.conf \
  defreitas/dns-proxy-server
```

This would allow users to refer to containers on the host by their hostname instead of having to deal with IP addresses.

**Comment by kszucs** [comment]
0.14? :)

As a workaround You can setup the hostnames in `/etc/hosts` to point to the host machine, because all of the required ports are exposed. Also doesn't seem like a platform independent solution https://github.com/mageddo/dns-proxy-server/issues

**Comment by cpcloud** [comment]
Moved to future since this isn't essential at all
