### ISSUE TITLE
Collapsing filters generates incorrect code for subqueries

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1344]
```
In [14]: import ibis

In [15]: t = ibis.table([('a', 'int64'), ('b', 'string')])

In [16]: filt = t[t.a < 100]

In [17]: expr = filt[filt.a == filt.a.max()]

In [18]: print(ibis.bigquery.compile(expr))
SELECT *
FROM t3
WHERE `a` < 100 AND
      `a` = (
  SELECT max(`a`) AS `max`
  FROM t3
)
```

**Comment by wesm** [comment]
This might have to do with the correlated subquery code path

**Comment by cpcloud** [comment]
Yep, it's a bit tricky. I looked into it a bit yesterday right as I was leaving the office. I'm going to get this fixed for 0.13 but a couple of other PRs need to be merged before this happens.

**Comment by kszucs** [comment]
On alchemy backends the compiling expression above fails with infinite recursion.

**Comment by kszucs** [comment]
The predicates got fused in [analysis._filter_selection](https://github.com/ibis-project/ibis/blob/master/ibis/expr/analysis.py#L534). 
I had a couple of desperate hack attempts to `block` a `Selection` in case predicates containing reductions. While that makes the above test case pass, breaks multiple others with `doent's fully originate from` error.

This is a really highly coupled part of the codebase :)
