### ISSUE TITLE
Simple table reduction uses window operation instead of aggregation

### ISSUE THREAD

**Issue by tdna** [ibis-project/ibis#1346]
### Actual behaviour
```python
import ibis
t = ibis.table([('e', 'int64'), ('f', 'int32')])
expr1 = t[t.e.sum().name('e'), t.f.sum().name('f')]
expr1
```
![download](https://user-images.githubusercontent.com/2520839/36024096-edcc250e-0d8e-11e8-8fd9-690853a42aac.png)
mysql compiles to
```sql
SELECT sum(t0.e) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS e, sum(t0.f) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS f 
FROM t5 AS t0
```

### Expected behaviour
`expr1` should aggregate instead of using window operation like the following expression
```python
expr2 = t.aggregate([t.e.sum().name('e'), t.f.sum().name('f')])
expr2
```
![image](https://user-images.githubusercontent.com/2520839/36024187-42a18560-0d8f-11e8-84be-6a8b27138634.png)
mysql compiles to
```sql
SELECT sum(t0.e) AS e, sum(t0.f) AS f 
FROM t5 AS t0
```

**Comment by cpcloud** [comment]
@tdna The actual behavior you describe here is the expected behavior.

I couldn't find any explicit documentation for this behavior, but there's a blurb that hints at it here: http://docs.ibis-project.org/sql.html#window-functions

> Ibis will automatically write window clauses when you use aggregate functions in a non-aggregate context.

Since `t[...]` is a non-aggregate context (projecting without an explicit `aggregate` call) an `OVER (...)` clause is generated.

**Comment by cpcloud** [comment]
I'll add some documentation to explicitly show this difference

**Comment by wesm** [comment]
Can we elide the window clause in this case (I didn't think so but maybe you can in some databases)?

**Comment by cpcloud** [comment]
We could think about making the window operations only happen in the case that there's at least one selection that contains a `ColumnExpr`. This would be a backwards incompatible change. If we made this change, we'd bump the version of ibis to 0.1.0 to indicate such a break.

**Comment by kszucs** [comment]
As an end user I'd definitely expect

```python
SELECT sum(t0.e) AS e, sum(t0.f) AS f 
FROM t5 AS t0
```

for 

```python
t[t.e.sum().name('e'), t.f.sum().name('f')].compile()
```

**Comment by fuxinhao-crypto** [comment]
@cpcloud may I ask you for help? I'm creating a new Reduction Operation. it works but adding the window clause. do u know how can I remove it? thanks
```python
class RowToJSON(Reduction):
    arg = Arg(ir.TableExpr)
    output_type = dt.jsonb.column_type
    
ir.TableExpr.row_to_json = row_to_json

@ibis.postgres.compiles(RowToJSON)
def compile_row_to_json(translator, expr):
    arg, = expr.op().args
    ctx = translator.context
    alias = ctx.get_ref(arg)
    return sa.func.row_to_json(alias)
```
and
```
>>> print(c.table("users").row_to_json().compile())
SELECT row_to_json(t0) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS tmp
FROM users AS t0
```

**Comment by cpcloud** [comment]
@fuxinhao-crypto It looks like [`row_to_json`]() isn't a reduction. Can you try subclassing `ValueOp` instead?

**Comment by gforsyth** [comment]
@fuxinhao-crypto -- would you mind re-posing this question over in https://github.com/ibis-project/ibis/discussions so it's more easily discoverable for other users?
