### ISSUE TITLE
More informative RelationError in case of overlapping keys

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1358]
'Joined tables have overlapping names ...' -> 'Joined tables `table1` and `table2` have overlapping names ...'

**Comment by xmnlab** [comment]
https://github.com/ibis-project/ibis/blob/master/ibis/expr/operations.py#L1623

@kszucs  is `table1` and `table2` a fixed text?

**Comment by cpcloud** [comment]
This will go away when we de-`materialize` ourselves
