### ISSUE TITLE
Setup binderhub - formerly binder

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1360]
See https://github.com/jupyterhub/binderhub
E.g. for the tutorial resource

**Comment by cpcloud** [comment]
That's pretty neat.

**Comment by kszucs** [comment]
We could initialize with data about pandas' git history in parquet format - 5+ tables :)

**Comment by kszucs** [comment]
@cpcloud So binderhub requires a [kubernetes cluster]https://binderhub.readthedocs.io/en/latest/create-cloud-resources.html). Do we have gcloud resources for that?

**Comment by kszucs** [comment]
@cpcloud Can You get resources for this?
