### ISSUE TITLE
Make use of @compiles more often 

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1367]
This is to make it easier for people to understand how to extend ibis as well as contribute to its development.

**Comment by cpcloud** [comment]
cc @FedericoV

**Comment by xmnlab** [comment]
Hi all, I am trying to apply @compiles on a new backend that I am working using step 3 as references (
https://github.com/ibis-project/ibis/blob/master/docs/source/notebooks/tutorial/9-Adding-a-new-expression.ipynb
)

But my module hasn't this function. Where should I create this function? Is there a documentation about that?

**Comment by xmnlab** [comment]
@cpcloud great! thank you!

In my case, the backend is a String Generating type, should I also use `ibis.sql.compiler.ExprTranslator`?
