### ISSUE TITLE
Support for sqlalchemy >= 1.2?

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1384]
@cpcloud I've manually installed the dependencies and it took me fair amount of time to figure out that the problem is newer sqlalchemy than `1.1`. Only SQLite tests were breaking.

How much effort would it be to support newer sqlalchemy too?

**Comment by cpcloud** [comment]
I'm not sure, I haven't had a chance to look into why this breaks sqlite tests. We should look into it for 0.14.
