### ISSUE TITLE
ENH: Support DISTINCT in aggregate functions

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1399]
Things like:

```sql
SELECT ARRAY_AGG(DISTINCT foo)
FROM t
```

**Comment by jreback** [comment]
count of this as well = nunique in pandas

**Comment by cpcloud** [comment]
@jreback That already exists in ibis as `nunique` :)

**Comment by jreback** [comment]
yes i c u wrote array_agg - retract my comment

**Comment by cpcloud** [comment]
Yeah this is about supporting it more generally, in every aggregation that we can.

**Comment by cpcloud** [comment]
Duplicate of #365. Needs a champion.
