### ISSUE TITLE
Ibis UDA persistence in Impala

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#14]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Tuesday Dec 09, 2014 at 21:51 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/14_

---

Some way to create a UDA that can be reused between sessions (and by other users)

**Comment by cpcloud** [comment]
This is out of scope for ibis right now, let's reopen if this ever becomes high priority.
