### ISSUE TITLE
ENH: multiple client compilation

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1429]
I say "client" instead of "backend" specifically because we may want to allow clients from the same backend to be used together. Notably, bigquery allows cross-project queries where you a can, for example, join a table in one project with another.

More generally, there's the issue of how compliation works at the moment.

Right now, when you call `compile` on an `Expr`, ibis will traverse the tree to find a backend, and if there's more than one client it will fail.

I'm not entirely sure what the right way to abstract over this is or even if doing so is a viable idea. I'm going to spend some time thinking about it and experimenting with different approaches over the next few weeks.

**Comment by tswast** [comment]
Over at https://github.com/ibis-project/ibis/pull/1428#discussion_r182590739

My thoughts on this relating to BigQuery: this restriction on a single backend makes sense if you think about client/backend as the project that is getting charged for running queries: there should always be one.

The problem arises when there is an assumption that the data queried must be in a single GCP project. A query can span projects for data, but it is still only charged to a single project, which might not actually contain any of the data being queried.

**Comment by kszucs** [comment]
@cpcloud related https://github.com/ibis-project/ibis/issues/1328

**Comment by cpcloud** [comment]
This works in BigQuery, but compilation without execution with multiple clients feels not very useful otherwise.
