### ISSUE TITLE
Add new units for date/time

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1430]
mapd has new date/time units (https://www.omnisci.com/docs/v4.0.0/5_dml.html):

Supported date_part types:

DATE_TRUNC [YEAR, QUARTER, MONTH, DAY, HOUR, MINUTE, SECOND, MILLISECOND,  MICROSECOND, NANOSECOND, MILLENNIUM, CENTURY, DECADE, WEEK, QUARTERDAY]

EXTRACT    [YEAR, QUARTER, MONTH, DAY, HOUR, MINUTE, SECOND, MILLISECOND,  MICROSECOND, NANOSECOND, DOW, ISODOW, DOY, EPOCH, QUARTERDAY, WEEK, DATEEPOCH]

DATEDIFF   [YEAR, QUARTER, MONTH, DAY, HOUR, MINUTE, SECOND, MILLISECOND, MICROSECOND, NANOSECOND, MILLENNIUM, CENTURY, DECADE, WEEK, QUARTERDAY]

Supported interval types:

DATEADD  [DECADE, YEAR, QUARTER, MONTH, WEEK, WEEKDAY, DAY,  HOUR, MINUTE, SECOND, MILLISECOND, MICROSECOND, NANOSECOND]

TIMESTAMPADD  [YEAR, QUARTER, MONTH, WEEKDAY, DAY, HOUR, MINUTE, SECOND, MILLISECOND, MICROSECOND, NANOSECOND]

DATEPART      [YEAR, QUARTER, MONTH, DAYOFYEAR, QUARTERDAY, WEEKDAY, DAY, HOUR, MINUTE, SECOND, MILLISECOND, MICROSECOND, NANOSECOND]

**Comment by kszucs** [comment]
@xmnlab Here are the [units currently supported](https://github.com/ibis-project/ibis/blob/master/ibis/expr/operations.py#L2207), which covers most of the options. 

IMHO You should start with implementing those, and collecting the unsupported ones. Then we'd have a clearer picture how to incorporate new units in the expression system.

What do You think?

**Comment by kszucs** [comment]
There are [test cases](https://github.com/ibis-project/ibis/blob/master/ibis/tests/all/test_temporal.py) You can easily hook after specifying a MapD backend [here](https://github.com/ibis-project/ibis/blob/master/ibis/tests/backends.py)

**Comment by xmnlab** [comment]
Thanks @kszucs  I will take a look!

Would be a good idea a generic extract operation for date and timestamp that could receive a timestamp/date argument and an unit? maybe something like: `t['timestamp'].extract('year')` ?

**Comment by xmnlab** [comment]
hey everyone, what do you think about generic extraction? eg `t['timestamp'].extract('year')`

**Comment by xmnlab** [comment]
hey everyone, any thoughts about my last comment? https://github.com/ibis-project/ibis/issues/1430#issuecomment-473465033

**Comment by cpcloud** [comment]
A generic `extract()` is likely very useful for these sorts of cases where the backend has a larger set of units available than is typical. PRs welcome.
