### ISSUE TITLE
Radians and Degrees operations

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1431]
I am creating two new operations radians and degrees. At this moment these two are on backend code, but I think it would be good to put them to `ibis.core`.

`numpy` has to names for these functions: `radians` or `deg2rad` and `degrees` or `rad2deg`

1) should I move this operations to `ibis` core?
2) should I create `radians`/`degrees` or `rad2deg`/`deg2rad` or both?

**Comment by kszucs** [comment]
That should go to `ibis.expr.operations`. I like `radians` and `degrees`.

@cpcloud What do You think?

**Comment by cpcloud** [comment]
Sounds good to me. Could have degrees/radians/deg2rad/rad2deg all in api.py and corresponding ops in operations.py

**Comment by xmnlab** [comment]
great! I'm moving the operations to there!
