### ISSUE TITLE
Correlation and Covariation operations

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1432]
I am adding correlation and covariation operations for mapd backend.

I think it would be good be the on the `ibis` core.

I am using pandas name for this operations:

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.cov.html
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.corr.html

Does it make sense?

**Comment by cpcloud** [comment]
@xmnlab Yep, makes sense. We are definitely interested in adding these.

**Comment by xmnlab** [comment]
Added on PR #1419
