### ISSUE TITLE
Random sample from an Impala table

### ISSUE THREAD

**Issue by levent-dinckal** [ibis-project/ibis#1437]
Hi all,

I am trying to download a random sample from an Impala table as a pandas dataframe. I could not find a sampling function in the documentation so I wanted to build my own, but it seems like there is no random number generation function either. Am I missing anything or is this just not implemented yet?

**Comment by cpcloud** [comment]
This isn't implemented, but we'd happily accept a PR. Please open one if you'd like.

**Comment by jayceslesar** [comment]
I think could be easily implemented by creating a new column with `random()` and then filtering on anything less than or greater than some threshold to get that percent/proportion of rows back yeah?
