### ISSUE TITLE
Setup code coverage integration

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1444]
@cpcloud what do You think?

**Comment by cpcloud** [comment]
+1 from me, this would be great to have

**Comment by kszucs** [comment]
Which service do You prefer?

**Comment by cpcloud** [comment]
we can try coveralls.io, and if that's not working we can try something else

**Comment by cpcloud** [comment]
if you have any thoughts feel free to share them here

**Comment by kszucs** [comment]
I don't have any preference regarding to coverage services (at least yet).
