### ISSUE TITLE
RowId operation

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1462]
I am trying to implement `MapD` `rowid` operator and I found `row_number()` operation on ibis.

row_number is a window operation ... but for MapD, it could be a normal operation. 

This is an example using rowid: `select rowid, * from diamonds limit 10;`

Should we create a new operation? Is `RowId` a good name?

**Comment by cpcloud** [comment]
Instead of an operation that would be exposed to all backends, what about adding a `rowid` column to the schema of every `MapDTable`?

**Comment by kszucs** [comment]
Does any of the existing backends support this?

**Comment by cpcloud** [comment]
SQLite does:

```
sqlite> select rowid, * from diamonds limit 5;
rowid       carat       cut         color       clarity     depth       table       price       x           y           z
----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------
1           0.23        Ideal       E           SI2         61.5        55.0        326         3.95        3.98        2.43
2           0.21        Premium     E           SI1         59.8        61.0        326         3.89        3.84        2.31
3           0.23        Good        E           VS1         56.9        65.0        327         4.05        4.07        2.31
4           0.29        Premium     I           VS2         62.4        58.0        334         4.2         4.23        2.63
5           0.31        Good        J           SI2         63.3        58.0        335         4.34        4.35        2.75
```

**Comment by xmnlab** [comment]
does the rowid will always be showed on the table graphic? if yes, I think it could be a little bit confuse ...

**Comment by xmnlab** [comment]
is it ok to create a new operation `RowId`  that would be exposed to all backends?
