### ISSUE TITLE
bigquery udf insists ARRAY<INT64> was specified as ARRAY<FLOAT64>

### ISSUE THREAD

**Issue by tsdlovell** [ibis-project/ibis#1469]
(with `client` already defined)

This fails
```
@ibis.bigquery.udf(input_type=['array<int64>'], output_type='int64')
def bq_sum(xs):
    sum = 0
    for el in xs:
        sum += el
    return sum
expr = ibis.expr.types.TableExpr(
    ibis.expr.operations.SQLQueryResult(
        'SELECT [1, 2, 3] AS a',
        ibis.schema([('a', 'array<int64>')]),
        client,
    )
)
print(bq_sum(expr.a).compile())
print(bq_sum(expr.a).execute())
```
and prints
```
CREATE TEMPORARY FUNCTION bq_sum(xs ARRAY<FLOAT64>)
RETURNS FLOAT64
LANGUAGE js AS """
'use strict';
function bq_sum(xs) {
    let sum = 0;
    for (let el of xs) {
        sum += el;
    }
    return sum;
}
return bq_sum(xs);
""";

SELECT bq_sum(`a`) AS `tmp`
FROM (
  SELECT [1, 2, 3] AS a
) t0
---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
<ipython-input-2-178446fb1676> in <module>()
     14 )
     15 print(bq_sum(expr.a).compile())
---> 16 print(bq_sum(expr.a).execute())
...
BadRequest: 400 No matching signature for function JS:BQ_SUM for argument types: ARRAY<INT64>. Supported signature: BQ_SUM(ARRAY<FLOAT64>) at [15:8]
```

Whereas this works
```
@ibis.bigquery.udf(input_type=['array<double>'], output_type='int64')
def bq_sum(xs):
    sum = 0.
    for el in xs:
        sum += el
    return sum
expr = ibis.expr.types.TableExpr(
    ibis.expr.operations.SQLQueryResult(
        'SELECT [1., 2., 3.] AS a',
        ibis.schema([('a', 'array<double>')]),
        client,
    )
)
print(bq_sum(expr.a).compile())
print(bq_sum(expr.a).execute())
```
and prints
```
CREATE TEMPORARY FUNCTION bq_sum(xs ARRAY<FLOAT64>)
RETURNS FLOAT64
LANGUAGE js AS """
'use strict';
function bq_sum(xs) {
    let sum = 0.0;
    for (let el of xs) {
        sum += el;
    }
    return sum;
}
return bq_sum(xs);
""";

SELECT bq_sum(`a`) AS `tmp`
FROM (
  SELECT [1., 2., 3.] AS a
) t0
0    6
Name: tmp, dtype: int64
```

**Comment by cpcloud** [comment]
The reason it automatically converts `ARRAY<INT64>` to `ARRAY<FLOAT64>` is because of this documentation: https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions#supported-external-udf-data-types

and specifically this line:
> Because JavaScript does not support a 64-bit integer type, INT64 is unsupported in input or output types for JavaScript UDFs. Instead, use FLOAT64 to represent integer values as a number, or STRING to represent integer values as a string.

It looks like BigQuery doesn't actually behave that way if "unsupported" is interpreted to mean "will raise an error" since this works (silently upcasts to `FLOAT64`):

```
CREATE TEMPORARY FUNCTION bq_sum(xs INT64)
RETURNS FLOAT64
LANGUAGE js AS """
'use strict';
return 1;
""";

SELECT bq_sum(`a`) AS `tmp`
FROM (
  SELECT 1 AS a
) t0
```

Interestingly if the return type is `INT64`, BigQuery casts the result to that type.

@tswast Am I missing something here or the documentation inconsistent with the behavior?

**Comment by tsdlovell** [comment]
alternatives to the current state
1. raise on the creation of the expression with a udf that is being passed incompatible types
1. coerce the types passed to the udf if possible, else raise on the creation of the expression
1. warn that the type will be coerced

**Comment by cpcloud** [comment]
@tsdlovell @tswast looks like I was mistaken: a more complex test case reveals that bigquery appears to cast inputs to string:

```
CREATE TEMPORARY FUNCTION bq_sum(x INT64, y INT64)
RETURNS INT64
LANGUAGE js AS """
'use strict';
return x + y;
""";

SELECT bq_sum(`a`, `b`) AS `tmp`
FROM (
  SELECT 1 AS a, 2 AS b
) t0
```
returns `12`.

**Comment by tswast** [comment]
Yeah, it does cast to strings. Annoying to deal with in JavaScript, but it's the only way not to drop precision for 64-bit integers.
