### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower' when using partition tables

### ISSUE THREAD

**Issue by oyamin** [ibis-project/ibis#1483]
Following the tutorial with partition tables, but unable to get anywhere as soon as I am trying to select the table. 

Code:

```python
schema = ibis.schema([('run_date', 'timestamp'),
                      ('seq_num', 'int64'),
                      ('month', 'int16')])

name = 'new_table'
hive_conn.create_table(name, schema=schema, partition=['run_date', 'seq_num'])
table = hive_conn.table(name)
print table.schema()
print table.partitions
```

It seems that when it runs description on the table, it is trying to parse the whole output of the description output. Output (after adding "print names, types" in client.py line 722):

```python
('month', 'run_date', 'seq_num', '', '# Partition Information', '# col_name            ') ('smallint', 'timestamp', 'bigint', None, None, 'data_type           ')
```

The error is:

```python
Traceback (most recent call last):
  File "ois_hdfs.py", line 56, in <module>
    table = hive_conn.table(name)
  File "/usr/lib/python2.7/site-packages/ibis/client.py", line 119, in table
    schema = self._get_table_schema(qualified_name)
  File "/usr/lib/python2.7/site-packages/ibis/impala/client.py", line 1193, in _get_table_schema
    return self.get_schema(tname)
  File "/usr/lib/python2.7/site-packages/ibis/impala/client.py", line 726, in get_schema
    t = t.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

Ibis version:
```
ibis-framework==0.13.0
```

Hadoop:
```
hadoop version
Hadoop 2.7.3.2.6.4.0-91
```

Hive:
```
hive>  !hive --version;
Hive 1.2.1000.2.6.4.0-91
```

**Comment by cpcloud** [comment]
@oyamin Thanks for the report. Marking as a bug for 0.14.

**Comment by cpcloud** [comment]
@oyamin It looks like you're using Hive, which we do not explicitly support. Are you using an impala connection and you just happened to call the variable `hive_conn`?

**Comment by cpcloud** [comment]
@oyamin Can you show me the SQL output of `DESCRIBE new_table`? It looks like that is returning something different than what ibis expects. It looks like that is doing something more like `DESCRIBE EXTENDED new_table`.

Was this a change made in a version of Hive later than 1.1.0?

**Comment by cpcloud** [comment]
@oyamin Right, so you're using actual Hive and not impala. Hive is not a backend that we support at the moment, though we would be extremely happy to have someone work on such a thing. Therefore, there's no guarantee that using ibis with hive will behave in any kind of reasonable way.

I'll move your issue to the Future milestone.

Just out of curiosity, does everything *except* this work? For example, can you execute complicated queries? If so, I'd be very surprised.

**Comment by oyamin** [comment]
Surprisingly, the basic functionality works. My need was mostly for the creation table part in Hive using Dataframe column types, which was generated from Oracle. If there is no partitioning, then create_table works flawlessly in Hive. There is no other library currently that does this out there.

The Hive alter and load queries I executed with raw_sql. Only thing that would make this better is if the temp table for the schema could be created in directly in Hive so we don't depend on hdfs_client connection.

**Comment by cpcloud** [comment]
This is supported on a best effort basis, since Hive isn't explicitly supported. Happy to accept PRs.
