### ISSUE TITLE
Add tests for MapD DDL operations, user operations (create, alter, drop) and load data

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1492]
Add tests for MapD DDL operations:

- [x] create database
- [x] drop database
- [x] create_table
- [x] drop_table
- [x] truncate_table
- [x] create view
- [x] drop view
- [x] create user
- [x] alter user
- [x] drop user
- [x] load data

**Comment by cpcloud** [comment]
All the boxes are checked, so closing.
