### ISSUE TITLE
Add `user` operations (create, alter, drop) for backends that support that.

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1493]
Add `user` operations (create, alter, drop) for backends that support that

- [ ] postgres
- [ ] mysql
- [ ] impala
- [ ] clickhouse
- [ ] bigquery
- [ ] ...

**Comment by randyzwitch** [comment]
With the release of v4.0, MapD can be added to the list:

https://www.mapd.com/docs/latest/5_usersanddatabases.html
