### ISSUE TITLE
Implement day_of_week for BigQuery

### ISSUE THREAD

**Issue by missing-semicolon** [ibis-project/ibis#1494]
Extend support for extraction logic to BQ where currently lacking.

Here's some code: https://github.com/ibis-project/ibis/blob/master/ibis/expr/types.py#L735-L743

**Comment by cpcloud** [comment]
Looks like BigQuery itself doesn't have a named day of week function, but does support the indexed version. We could construct a case statement to generate the days for that.

**Comment by cpcloud** [comment]
So, `a.date().day_of_week.full_name()` would generate code like:

```sql
CASE WHEN 1 THEN 'Sunday'
CASE WHEN 2 THEN 'Monday'
...
CASE WHEN 7 THEN 'Saturday'
ELSE NULL
END

**Comment by missing-semicolon** [comment]
It looks like we have a decision to make: The implementation of `day_of_week.index` is probably returning different values on different backends. Here's what I've found so far:

* Pandas: The day of the week with Monday=0, Sunday=6
* Impala: The range of return values is 1 (Sunday) to 7 (Saturday).
* BigQuery: Returns values in the range [1,7] with Sunday as the first day of the week.
* Postgres: The day of the week (0 - 6; Sunday is 0) (for timestamp values only)

In general I would follow the pandas implementation since that is where a lot of the Ibis syntax is coming from and therefore what users would expect. I am going to take a run at implementing in this manner and update Impala / other backends as necessary.
