### ISSUE TITLE
feat: Make DayOfWeek implementations conform to pandas semantics

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1499]
@missing-semicolon has taken care of impala and bigquery in https://github.com/ibis-project/ibis/pull/1495, but we need to implement and/or wrangle the others as well:

To partially quote @missing-semicolon from https://github.com/ibis-project/ibis/issues/1494#issuecomment-398592007, here's what pandas does:

> * Pandas: The day of the week with Monday=0, Sunday=6

- [x] impala
- [x] bigquery
- [x] Postgres
- [ ] mysql
- [x] sqlite
- [ ] clickhouse
- [x] pandas (not sure if this is implemented)
- [x] omniscidb https://github.com/ibis-project/ibis/pull/2171

I'm happy to take on pandas, postgres and sqlite. @xmnlab can you implement this for mapd if it's available? @kszucs can you take clickhouse and mysql?

**Comment by xmnlab** [comment]
@cpcloud great I will add this to the list here. thanks!

**Comment by cpcloud** [comment]
@xmnlab any chance I could get you to implement this for the mapd backend?

**Comment by xmnlab** [comment]
cc @tonyfast

**Comment by xmnlab** [comment]
@cpcloud  could you add the mapd label for this issue?
