### ISSUE TITLE
Method for user to indicate format of data to be passed to UDA subclasses

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#15]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Wednesday Dec 10, 2014 at 00:35 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/15_

---

For example, the user might want all data to be wrapped in pandas Series objects. One approach is class level variables and creating a metaclass for all UDA subclasses to inherit from (perhaps optionally).

**Comment by cpcloud** [comment]
This is interesting, but I think this is out of scope for ibis right now. Let's revisit if it becomes high priority to support this in ibis. This would require UDA/UDF support as a dependency.
