### ISSUE TITLE
ValueError when creating a table expression for a Kudu-backed Impala table

### ISSUE THREAD

**Issue by jeffgortmaker** [ibis-project/ibis#1509]
I believe the issue I'm experiencing is that `DESCRIBE` returns more than just three columns for Kudu-backed tables (see "Kudu Considerations" [on this page](https://www.cloudera.com/documentation/enterprise/5-11-x/topics/impala_describe.html)). The issue seems to be

https://github.com/ibis-project/ibis/blob/3276d3713c3497021e547e10102f917f7762414d/ibis/impala/client.py#L1060 

which assumes there are only three columns. 

Example traceback:

    In [5]: client.table('kudu_backed_table')
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-5-d0d66416fb5f> in <module>()
    ----> 1 client.table('kudu_backed_table')
    
    /data/apps/Anaconda3-5.0.1/envs/ibis/lib/python3.6/site-packages/ibis/client.py in table(self, name, database)
        117         """
        118         qualified_name = self._fully_qualified_name(name, database)
    --> 119         schema = self._get_table_schema(qualified_name)
        120         node = ops.DatabaseTable(qualified_name, schema, self)
        121         return self._table_expr_klass(node)
    
    /data/apps/Anaconda3-5.0.1/envs/ibis/lib/python3.6/site-packages/ibis/impala/client.py in _get_table_schema(self, tname)
       1186
       1187     def _get_table_schema(self, tname):
    -> 1188         return self.get_schema(tname)
       1189
       1190     def _get_schema_using_query(self, query):
    
    /data/apps/Anaconda3-5.0.1/envs/ibis/lib/python3.6/site-packages/ibis/impala/client.py in get_schema(self, table_name, database)
        716         tuples = self.con.fetchall(query)
        717
    --> 718         names, types, comments = zip(*tuples)
        719
        720         ibis_types = []
    
    ValueError: too many values to unpack (expected 3)

**Comment by jeffgortmaker** [comment]
Sure! First here's the test table that I'm using:

    CREATE TABLE kudu_backed_table (a STRING, PRIMARY KEY(a)) STORED AS KUDU;

With an initialized ImpalaClient, replicating the code above the problematic line gives:

    In [8]: client.con.fetchall('describe kudu_backed_table')
    Out[8]:
    [('a',
      'string',
      '',
      'true',
      'false',
      '',
      'AUTO_ENCODING',
      'DEFAULT_COMPRESSION',
      '0')]

**Comment by cpcloud** [comment]
@jeffgortmaker give this a go when you have a chance, make sure to install from master! let us know how it goes.
