### ISSUE TITLE
Efficiency of the pandas backend on large joins?

### ISSUE THREAD

**Issue by gabomgp** [ibis-project/ibis#1533]
First, great project. I'm trying in using it to abstract some joins and filters from PostgreSQL and Pandas and it's great.

So, when i try to join using as comparison columns, some column from the index of a dataframe, the column is not found. It appears as if columns in indexes in dataframes are not visible from joins operations. So,  i imagine that the left join works without a binary search over the sorted column (id in my case), because the dataframe must not have usable indexes. Am i right?

**Comment by cpcloud** [comment]
@gabomgp Thanks for asking this question. Can you provide a concrete example of what you're asking. I think it will be easier for us to hash out the details of your question.

**Comment by gabomgp** [comment]
@cpcloud Sure, thanks you.

There are more details in [MWE](https://github.com/gabomgp/questionInNotebooks/blob/master/MWE%20-%20eficency%20of%20pandas%20backend%20on%20large%20joins%20-%20ibis.1533.ipynb)

**Comment by cpcloud** [comment]
One implicit goal (which perhaps should be made explicit) of the pandas backend is that it should be not systematically slower than--and in some cases much faster than--pandas itself.

**Comment by cpcloud** [comment]
The pandas backend will not currently use `DataFrame` indexes in a join. Would happily accept PRs, or a motivating use case such as "This is unusable without an index-based join". We'd still need to look into whether pandas leverages this information.
