### ISSUE TITLE
bug: cumulative window vanishes when grouping

### ISSUE THREAD

**Issue by jeffgortmaker** [ibis-project/ibis#1537]
The `RANGE BETWEEN` statement created by `cumulative_window` seems to be lost in a `group_by`:

    In [1]: import ibis

    In [2]: print(ibis.__version__)
    0.13.0

    In [3]: t = ibis.table([('one', 'string'), ('two', 'double'), ('three', 'int32')], 'my_data')

    In [4]: w = ibis.cumulative_window(order_by=t.one)

    In [5]: print(ibis.impala.compile(t.mutate(four=t.two.sum().over(w))))
    SELECT *,
           sum(`two`) OVER (ORDER BY `one` RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS `four`
    FROM my_data
    
    In [6]: print(ibis.impala.compile(t.group_by(t.three).mutate(four=t.two.sum().over(w))))
    SELECT *, sum(`two`) OVER (PARTITION BY `three` ORDER BY `one`) AS `four`
    FROM my_data

Maybe a check somewhere for falsey-ness of `window.following` is conflating `0` with `None`? Truthy values seem to work:

    In [7]: w2 = ibis.window(following=1, order_by=t.one)
    
    In [8]: print(ibis.impala.compile(t.group_by(t.three).mutate(four=t.two.sum().over(w2))))
    SELECT *,
           sum(`two`) OVER (PARTITION BY `three` ORDER BY `one` ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING) AS `four`
    FROM my_data

**Comment by cpcloud** [comment]
Appears to work fine on other backends:

```
In [14]: print(ibis.postgres.compile(t.group_by(t.three).mutate(four=t.two.sum().over(w))))
SELECT t0.one, t0.two, t0.three, sum(t0.two) OVER (PARTITION BY t0.three ORDER BY t0.one ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS four
FROM my_data AS t0

In [15]: print(ibis.sqlite.compile(t.group_by(t.three).mutate(four=t.two.sum().over(w))))
SELECT t0.one, t0.two, t0.three, sum(t0.two) OVER (PARTITION BY t0.three ORDER BY t0.one ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS four
FROM my_data AS t0
```

**Comment by cpcloud** [comment]
This appears to be a bug in sqlite and postgres as well, though it manifests a little differently:

```
In [18]: print(ibis.sqlite.compile(t.group_by(t.three).mutate(four=t.two.sum().over(ibis.window(following=0, order_by=t.one)))))
SELECT t0.one, t0.two, t0.three, sum(t0.two) OVER (PARTITION BY t0.three ORDER BY t0.one ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS four
FROM my_data AS t0
```

`UNBOUNDED FOLLOWING` is incorrect and should be `CURRENT ROW` for a cumulative window.

**Comment by cpcloud** [comment]
The immediate workaround is to pass the partitioning column into the window construction:

```
In [27]: w = ibis.cumulative_window(order_by=t.one, group_by=t.three)

In [28]: print(ibis.sqlite.compile(t.mutate(four=t.two.sum().over(w))))
SELECT t0.one, t0.two, t0.three, sum(t0.two) OVER (PARTITION BY t0.three ORDER BY t0.one ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS four
FROM my_data AS t0
```

**Comment by cpcloud** [comment]
This also works for the impala backend:

```
In [29]: print(ibis.impala.compile(t.mutate(four=t.two.sum().over(w))))
SELECT *,
       sum(`two`) OVER (PARTITION BY `three` ORDER BY `one` RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS `four`
FROM my_data
```

**Comment by cpcloud** [comment]
@jeffgortmaker Sorry it took so long to get around to this, but I've finally put up a PR to address the problem!

**Comment by jeffgortmaker** [comment]
Wonderful, thanks!
