### ISSUE TITLE
Clients are casting None to False in boolean columns with missing values

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1542]
The google Client is return the correct data, ibis is casting to boolean, where it should actually be leaving any boolean column alone (and in object mode).

```
In [38]: con = ibis.bigquery.connect('ibis-gbq', 'testing')

In [39]: db = con.database()

In [40]: t = db.functional_alltypes

In [41]: t.groupby(k=t.string_col.nullif('1') == '9').count()
Out[41]:
       k  count
0  False   5840
1   True    730
2  False    730
```

**Comment by tsdlovell** [comment]
The problem is not specific to groupby, it applies to all boolean columns
```
In [19]: client.raw_sql("""
    ...: SELECT * FROM UNNEST([true, false, null]) as x
    ...: """).fetchall()
Out[19]: [(True,), (False,), (None,)]
```

**Comment by kszucs** [comment]
I've written a backend test case for it, but realized that the foundations are missing, so implementing https://github.com/ibis-project/ibis/pull/1590 first

**Comment by kszucs** [comment]
This involves the general issue of representing `None/Null` in pandas dataframes.
For floating types We have `NaN` everything else We need to use `object` dtype to represent Nullable ibis columns containing `None/Null` values. Here is a datatype matrix We should fill-out:

|              | Non-nullable                 | Nullable with Null values | Nullable without Null values |
|--------------|------------------------------|---------------------------|------------------------------|
| dt.Null      | np.object_ (NoneType)        |                           |                              |
| dt.Boolean   | np.bool_                     |                           |                              |
| dt.Int8      | np.int8                      |                           |                              |
| dt.UInt8     | np.uint8                     |                           |                              |
| dt.Int16     | np.int16                     |                           |                              |
| dt.UInt16    | np.uint16                    |                           |                              |
| dt.Int32     | np.int32                     |                           |                              |
| dt.UInt32    | np.uint32                    |                           |                              |
| dt.Int64     | np.int64                     |                           |                              |
| dt.UInt64    | np.uint64                    |                           |                              |
| dt.Float32   | np.float32                   |                           |                              |
| dt.Float64   | np.float64                   |                           |                              |
| dt.Decimal   | np.object_ (decimal.Decimal) |                           |                              |
| dt.Date      | datetime64[ns]               |                           |                              |
| dt.Time      | timedelta64[ns]              |                           |                              |
| dt.Timestamp | datetime64[ns]               |                           |                              |
| dt.String    | np.object_ (str)             |                           |                              |
| dt.Binary    | np.object_ (bytes)           |                           |                              |
| dt.Array     | np.object_ (list)            |                           |                              |
| dt.Struct    | np.object_ (dict)            |                           |                              |
