### ISSUE TITLE
Remove async keyword from execute

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1548]
This is now a syntax error in Python 3.7.

Let's change this to be a method `execute_async`.

**Comment by kszucs** [comment]
How about removing async support for now and pass? 
Currently only impala backend supports async queries which also has `async` in it's [signature](https://github.com/ibis-project/ibis/blob/master/ibis/impala/client.py#L104)

IMHO An asyncio interface would be more interesting.

**Comment by cpcloud** [comment]
Indeed. I think that removing this is the way forward.

**Comment by kszucs** [comment]
Ok, doing that. How much experience do You have with asyncio?

**Comment by cpcloud** [comment]
Not much, honestly.

**Comment by kszucs** [comment]
Are You interested? :)
