### ISSUE TITLE
CircleCI runs are flaky on Python 3.x test teardown

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1560]
See https://circleci.com/workflow-run/a1503534-b17c-4f00-b815-4f573c0a9ca1

It looks like this related to Hive or Impala connection issues.

@kszucs If you have a chance, can you take a look?

**Comment by kszucs** [comment]
@cpcloud sure, I'm trying to reproduce it locally.

**Comment by kszucs** [comment]
It's not an easy one to reproduce locally, although it looks like a timeout error.

**Comment by cpcloud** [comment]
Ok, is there a way we can increase that?

**Comment by kszucs** [comment]
Perhaps with this [timeout](https://github.com/cloudera/impyla/blob/328ea33089e89daad8bd7a8037a2376e8bc52ed8/impala/dbapi.py#L40) argument

**Comment by cpcloud** [comment]
Looks like we are already [setting that to `45` seconds](https://github.com/ibis-project/ibis/blob/master/ibis/impala/api.py#L35)

**Comment by cpcloud** [comment]
@kszucs Was this ever addressed? Build seem generally not flaky anymore, but I don't know if this issue was explicitly addressed or just went away.

**Comment by kszucs** [comment]
@cpcloud I can't recall it.

**Comment by cpcloud** [comment]
Closing for now, I'll reopen if it shows up again.
