### ISSUE TITLE
Host ASV benchmarks somewhere

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1567]
What options do We have?

**Comment by cpcloud** [comment]
We might be able to run them under the `ibis-gbq` project on a long running VM, and host the reports on GCS. Won't be super reliable, but probably better than running them inside of a docker image (which is running on a VM) on CircleCI.

**Comment by kszucs** [comment]
GH pages? https://asv.readthedocs.io/en/stable/commands.html#asv-gh-pages

**Comment by cpcloud** [comment]
There's that as well. I vaguely remember trying that and it being very difficult to set up. We should try again.

**Comment by xmnlab** [comment]
let me know if I can help on this issue.
