### ISSUE TITLE
BigQuery doesn't have a now() function

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1575]
BigQuery uses `CURRENT_TIMESTAMP()` for this.

**Comment by cpcloud** [comment]
@kszucs Do you want to take this one? It's pretty straightforward.

**Comment by kszucs** [comment]
Sure, right after the arrow forge packages!

**Comment by cpcloud** [comment]
Great, thanks!

**Comment by cpcloud** [comment]
@kszucs Went ahead and did this.

**Comment by kszucs** [comment]
Ehh, forge is slow :)
