### ISSUE TITLE
BUG: now() implementations return different timestamps with different timezones

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1580]
| **Backend**     | **Apparent time zone of `now()`** | **Has distinct time zone type?** |
|-----------------|-----------------------------------|----------------------------------|
| SQLite          | UTC                               | No                               |
| Pandas          | Local                             | Yes                              |
| PostgreSQL      | UTC                               | Yes                              |
| Apache Impala   | UTC                               | No                               |
| Google BigQuery | UTC                               | No*                              |
| OmniSci MapD    | UTC                               | ?                                |

\* Google BigQuery timestamps *always* have a timezone, defaulting to UTC.

**Comment by cpcloud** [comment]
I'm not sure that we should actually try to make this uniform. We *should* make sure that we return a `pandas.Series` or `pandas.Timestamp` with the right timezone though.

**Comment by cpcloud** [comment]
@xmnlab What is the default timezone for `now` in MapD?

**Comment by xmnlab** [comment]
Do you know that @randyzwitch ?

**Comment by randyzwitch** [comment]
It returns UTC.
