### ISSUE TITLE
Ibis logo proposal

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#1584]
Does Ibis have a logo? I haven't seen one when browsing the docs.

The bird on a rhino in the current profile photo for ibis-project doesn't actually look like an ibis to me.

![image](https://user-images.githubusercontent.com/247555/43979891-11a11650-9ca1-11e8-969d-c91afdc956d4.png)

Per [Wikipedia](https://en.wikipedia.org/wiki/Ibis) "All ibises have long, down-curved bills, and usually feed as a group."

I decided to try creating a better logo. How's this?

![ibis-logo](https://user-images.githubusercontent.com/247555/43979939-3553af22-9ca1-11e8-942e-3de03f971e34.png)

It could potentially be simplified further, but at least this one has a down-curved bill.

**Comment by kszucs** [comment]
I'm not aware of one, so it's a definitely great initiative. How about a flying one?

**Comment by tswast** [comment]
A flying option:

![flying-ibis](https://user-images.githubusercontent.com/247555/43983426-5254a9ec-9caf-11e8-9532-629cbebf4774.png)

This one is inspired by https://en.wikipedia.org/wiki/File:Eudocimus_albus_-Huntington_Beach_State_Park,_South_Carolina,_USA_-flying-8.jpg by Bill Majoros (Creative Commons-licensed)

**Comment by kszucs** [comment]
Something like [these](https://www.google.com/search?tbm=isch&q=ibis&backchip=online_chips:drawing&chips=q:ibis&sa=X&ved=0ahUKEwj_rs6QxOPcAhUGZVAKHakuDpwQ3VYIJCgA&biw=1680&bih=966&dpr=2#imgrc=FivPT1wMsBw0dM:)? Might be better with water though :)

**Comment by tswast** [comment]
Some more options. I went with a simple outline this time to maybe be more logo-like.

Flying without water.

![ibis-logo](https://user-images.githubusercontent.com/247555/43997950-36c32366-9d9f-11e8-8a9f-6814783321d5.png)

Standing, with water.

![ibis-mikes-birds](https://user-images.githubusercontent.com/247555/43997953-5121159c-9d9f-11e8-9871-c5db1343494e.png)

Flying, with water.

![ibis-logo-ripple](https://user-images.githubusercontent.com/247555/43997955-590bef2a-9d9f-11e8-941c-0a7d730762fe.png)

**Comment by cpcloud** [comment]
@tswast do you have a "standing without water" version?

**Comment by tswast** [comment]
@cpcloud Not yet, but I can make one. I'll need to draw some feet. :-)

**Comment by cpcloud** [comment]
@tswast Great, thanks! I think a black ibis with no water with feet is the way to go, thoughts? @kszucs What do you think about that?

**Comment by tswast** [comment]
Black with feet:

![ibis-logo-standing](https://user-images.githubusercontent.com/247555/44007449-75b0e9b8-9e4a-11e8-915e-3ecdb7f2cd8b.png)

I got one [vote for "standing with water" on Twitter](https://twitter.com/TimSwast/status/1028505602840911872), but I don't have one with feet in that tweet.

**Comment by cpcloud** [comment]
@tswast Actually, I'm coming around to your initial logo: https://github.com/ibis-project/ibis/issues/1584#issue-349647769 I looked at it in the credentials API dialog box viewer and it looked good.

**Comment by cpcloud** [comment]
Let me give it a whirl on le GitHub.

**Comment by tswast** [comment]
Yeah, the fact that I needed a logo for the credentials box is why I got started on this whole thing. Still, one of the solid color ones might be better for a favicon on the Sphinx docs.
