### ISSUE TITLE
Initialize clickhouse with nullable columns

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1585]
In the backends test suite, clickhouse is the only one which columns' are non-nullable.

**Comment by kszucs** [comment]
Initializing `functional_alltypes`' columns as `Nullable` brakes a couple of clickhouse test cases.
I'll report them to the `clickhouse` developers to find out whether these are clickhouse bugs or ibis should handle them.

**Comment by cpcloud** [comment]
Will accept a PR for this, no need to keep the issue open though.
