### ISSUE TITLE
TST: Move impalamgr to datamgr

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1592]
In `ci/setup_env.sh` we call the commands for loading data into the testing instances. All them are consistent, using `ci/datamgr.py`, but not impala, which has its own script, requiring the setup script to have an extra `if`, and making things confusing.

We should move the impalamgr code to the datamgr script, having all backends consistent.

**Comment by cpcloud** [comment]
This'd be nice, but needs a PR to move forward.
