### ISSUE TITLE
DOC/ENH: Publish the Ibis roadmap

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1593]
Here's the working draft of some of my thoughts on longish-term plans for ibis: https://docs.google.com/document/d/10PWskqWnAHj9FMFd-l0LBqp0SJpyBjrR6JFL4cBhO50/edit?usp=sharing

@tswast @kszucs @tsdlovell

Interested to get your thoughts on that doc before publishing to the main repo in markdown form.

**Comment by kszucs** [comment]
Commented. Do You want to extend the userbase? We might prioritize a couple of popular backends to attract more users and hopefully contributors.

**Comment by cpcloud** [comment]
> there needs to be a way to identify operations as belonging to a non-standard extension.

Yep, that's definitely part of that goal, if not explicit. I will spell out some of the details there.

**Comment by scopatz** [comment]
The text here looks great! Are these items sorted in order of importance (at least within the long- and short-term goals)? That is, are the most important items at the top?

**Comment by cpcloud** [comment]
@scopatz Not necessarily, though I could arrange them that way if it's useful.

**Comment by scopatz** [comment]
That would be great!

**Comment by scopatz** [comment]
Is there anything I can do to help push this forward?

**Comment by cpcloud** [comment]
@scopatz A PR is up, please review if you'd like. I'll merge in the next day or two.

**Comment by scopatz** [comment]
Thanks @cpcloud! I really appreciate it.  Sorry for not getting a chance to review it, as I was out Monday.  Looks great though!
