### ISSUE TITLE
ENH: Pandas representation of Nullable types

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1595]
For floating types We have `NaN`, for datetime We have `NaT` everything else We need to use `object` dtype to represent Nullable ibis columns containing `None/Null` values. Here is a datatype matrix We should fill-out:

It's also not trivial whether We should distinguish between nullable columns with and without actual null values - that check could be expensive unless We use smart tricks.

This conversion table should be implemented in [Schema.apply_to](https://github.com/ibis-project/ibis/blob/master/ibis/pandas/client.py#L295)

| Ibis Type | Non-nullable | Nullable with Null values | Nullable without Null values |
|--------------|------------------------------|---------------------------|------------------------------|
| `dt.Null` | `np.object_ (NoneType)` | `np.object_ (NoneType)` | `np.object_ (NoneType)` |
| `dt.Boolean` | `np.bool_` | `object` | `np.bool_` |
| `dt.Int8` | `np.int8` | `object` | `np.int8` |
| `dt.UInt8` | `np.uint8` | `object` | `np.uint8` |
| `dt.Int16` | `np.int16` | `object` | `np.int16` |
| `dt.UInt16` | `np.uint16` | `object` | `np.uint16` |
| `dt.Int32` | `np.int32` | `object` | `np.int32` |
| `dt.UInt32` | `np.uint32` | `object` | `np.uint32` |
| `dt.Int64` | `np.int64` | `object` | `np.int64` |
| `dt.UInt64` | `np.uint64` | `object` | `np.uint64` |
| `dt.Float32` | `np.float32` | `np.float32` | `np.float32` |
| `dt.Float64` | `np.float64` | `np.float64` | `np.float64` |
| `dt.Decimal` | `np.object_ (decimal.Decimal)` | `np.object_ (decimal.Decimal)` | `np.object_ (decimal.Decimal)` |
| `dt.Date` | `datetime64[ns]` | `datetime64[ns]` | `datetime64[ns]` |
| `dt.Time` | `timedelta64[ns]` | `timedelta64[ns]` | `timedelta64[ns]` |
| `dt.Timestamp` | `datetime64[ns]` | `datetime64[ns]` | `datetime64[ns]` |
| `dt.String` | `np.object_ (str)` | `np.object_ (str)` | `np.object_ (str)` |
| `dt.Binary` | `np.object_ (bytes)` | `np.object_ (bytes)` | `np.object_ (bytes)` |
| `dt.Array` | `np.object_ (list)` | `np.object_ (list)` | `np.object_ (list)` |
| `dt.Struct` | `np.object_ (namedtuple?)` | `np.object_ (namedtuple?)` | `np.object_ (namedtuple?)` |
| `dt.Set` | `np.object_ (set)` | `np.object_ (set)` | `np.object_ (set)`
| `dt.Enum` | `pd.categorical` | ??? | `pd.categorical`
| `dt.Map` | `np.object_ (dict)` | `np.object_ (dict)` | `np.object_ (dict)`

@cpcloud thoughts?

P.S.: How about querying directly to Arrow instead of pandas? A couple of backends could support that (e.g. via turbodbc)

**Comment by cpcloud** [comment]
We should look into extension types and pyarrow`Table`s if we want do this, and see how comprehensive the support is for the types we care about.
