### ISSUE TITLE
ENH: SQLite window functions

### ISSUE THREAD

**Issue by westurner** [ibis-project/ibis#1597]
SQLite 3.25.0 (latest) now supports window functions.

https://www.sqlite.org/draft/releaselog/current.html

https://www.sqlite.org/draft/windowfunctions.html

**Comment by cpcloud** [comment]
Excellent. I'm glad that finally landed!

**Comment by cpcloud** [comment]
These work out of the box.

**Comment by westurner** [comment]
Thanks!
