### ISSUE TITLE
Add support for running SQL on an unevaluated table expression

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#160]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Monday Mar 23, 2015 at 21:36 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/160_

---

Somewhat gnarly implementation strategy: find the base connection; assemble existing table expression plus new SQL and request schema.

**Comment by cpcloud** [comment]
Closing. Please reopen if this becomes high priority.
