### ISSUE TITLE
SUPP: Generate release notes in future releases

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1606]
We have enough information to generate release notes using a script. We should implement this for the next release.

**Comment by cpcloud** [comment]
The plan here is to inspect commit messages (generated from issue titles) and looks for one of three prefixes: `FEAT:`, `BUG:`, `SUPP:` (feature, bug, or support) corresponding to the tags for sphinx-releases and generate releases notes from that information.

**Comment by xmnlab** [comment]
sounds pretty good. let me know if I can help in any way :)

**Comment by jreback** [comment]
in theory this is nice, but just as easy to have PRs include a release note. cc @toryhaavik @DiegoAlbertoTorres we should start this for next PRs and catchup since 1.2 for current notes.

**Comment by xmnlab** [comment]
just to be clear, `SUPP` is related to CI/Tests/DevOps stuff? or what should be tagged as SUPP?

**Comment by toryhaavik** [comment]
yes, that's what SUPP is meant for

**Comment by xmnlab** [comment]
nice. thanks for the quick response @toryhaavik !

**Comment by cpcloud** [comment]
This is already done.
