### ISSUE TITLE
Error : Backend=MapD ,  client.create_table(partition=['yyyy', 'mm'])  error!!

### ISSUE THREAD

**Issue by lzhmhznr** [ibis-project/ibis#1610]
Backend=MapD  Python=3.6  MapD=4.1  ibis=0.14

import ibis

client = ibis.mapd.connect(host='127.0.0.1', user='user_test', password='123456',port=9091, database='db_test')

struct = ibis.schema([('txt', 'string'),
                                 ('yyyy', 'int32'),
                                 ('mm', 'int16')])
                      
client.create_table('table_0', schema=struct, partition=['yyyy', 'mm']) 
Return : TypeError: create_table() got an unexpected keyword argument 'partition'

**Comment by cpcloud** [comment]
cc @xmnlab

**Comment by xmnlab** [comment]
it seems there is no partition in MapD [1]

could you confirm that @randyzwitch ?

@cpcloud if it is not supported, should we add a specific error message for that?

[1] https://community.mapd.com/t/partition-by-support/616

**Comment by randyzwitch** [comment]
That is correct @xmnlab, there aren't user-specified partitions (or other indexing) in MapD.

**Comment by xmnlab** [comment]
@cpcloud should we add a specific error message when the user uses the partition arg?

**Comment by kszucs** [comment]
I don't think so, if MapD doesn't support user specified partitions, it's simply a misuse of the API.

Only ImpalaClient's `create_table` has the `partition` keyword, see the [documentation](https://github.com/ibis-project/ibis/blob/8a5085ed3fd70409acde8cf5b17cdb3f82b0d987/docs/source/impala.rst#creating-a-partitioned-table).

**Comment by xmnlab** [comment]
I see ... thanks @kszucs and thanks @randyzwitch  for the explanation! 
so I think this issue could be close :)

**Comment by xmnlab** [comment]
could be closed this issue?

**Comment by cpcloud** [comment]
@xmnlab I think this keyword argument should be removed in the MapD backend. Can you submit a PR to address that? Then we can close this issue.

**Comment by xmnlab** [comment]
got it! thanks! I will do it :)

**Comment by xmnlab** [comment]
@cpcloud 

it seems there is no partition keyword argument in the create_table method.

there is a `partitions` keyword argument and this is related to this [1]:

```
property: partitions

Partition strategy option:

SHARDED: Partition table using sharding.
REPLICATED: Partition table using replication.
```

[1] https://www.omnisci.com/docs/latest/5_tables.html

**Comment by randyzwitch** [comment]
I’d argue that the partitions property for MapD shouldn’t be called from Ibis, so removing it probably best IMO. Or at least, noting in the documentation that it’s really not meant for ad hoc usage

**Comment by xmnlab** [comment]
@randyzwitch currently we have these parameters in the method:

```
fragment_size=None, max_rows=None, page_size=None, partitions=None, shard_count=None
```

should we remove all these arguments? or just partitions?

**Comment by randyzwitch** [comment]
I would remove everything except for `max_rows`, as a user needing these functionally should probably be more thoughtful about doing this as part of a data engineering workflow than an analytics one. 

`max_rows` is useful, as it allows for a rolling updated table.

**Comment by xmnlab** [comment]
got it! thanks @randyzwitch
