### ISSUE TITLE
Exception  MapD : No match found for function signature toDateTime(<CHARACTER>)

### ISSUE THREAD

**Issue by lzhmhznr** [ibis-project/ibis#1613]
table[table.timestamp_col  < '2000-03-01'].execute()

return error : 
mapd.ttypes.TMapDException: TMapDException(error_msg='Exception: Exception occurred: org.apache.calcite.runtime.CalciteContextException: From line 3, column 21 to line 3, column 46: No match found for function signature toDateTime(<CHARACTER>)')

Backend=MapD  MapD=4.1.1  ibis=0.14  Python=3.6
Ubuntu_18.04  Anaconda_5.1

**Comment by cpcloud** [comment]
@xmnlab Any chance you could take a look at this?

**Comment by xmnlab** [comment]
@tonyfast ^^^

**Comment by xmnlab** [comment]
@cpcloud I will take a look! thanks for point me that.

**Comment by xmnlab** [comment]
related topic: https://community.mapd.com/t/exception-mapd-no-match-found-for-function-signature-todatetime-character/1532/3

**Comment by xmnlab** [comment]
I added this to my backlog. thanks!
