### ISSUE TITLE
Beginner-friendly github issue label

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1616]
Hopefully ibis will gain some popularity in the near future. We should make it easier to start contributing to the project. 
@cpcloud What do You think about labeling the easy and/or straightforward issues?

**Comment by cpcloud** [comment]
+1. I will try to do a pass over existing issues to see what is beginner friendly

**Comment by kszucs** [comment]
I can help with that

**Comment by xmnlab** [comment]
@cpcloud @kszucs I can also help with that. I just created a `good first issue` label.

**Comment by toryhaavik** [comment]
There is a label created, and ~~10 issues marked as such, so I'll close this as I'm doing some housekeeping on the Issue backlog.
