### ISSUE TITLE
MapD : ibis.common.TranslationError: Joining on different column names is not supported

### ISSUE THREAD

**Issue by lzhmhznr** [ibis-project/ibis#1619]
```
>>> expr = tb10.num == tb12.id
>>> join = tb10.left_join(tb12, expr)
>>> join.execute()
Return Error : 
  File "/home/sw/anaconda3/lib/python3.6/site-packages/ibis/mapd/compiler.py", line 167, in _validate_join_predicates
    'Joining on different column names is not supported'
ibis.common.TranslationError: Joining on different column names is not supported

>>> join.materialize().execute()
  File "/home/sw/anaconda3/lib/python3.6/site-packages/ibis/mapd/compiler.py", line 167, in _validate_join_predicates
    'Joining on different column names is not supported'
ibis.common.TranslationError: Joining on different column names is not supported

>>> join.materialize().schema()
ibis.Schema {
  num     int32
  txt     string
  id      int32
  letter  string
}
```
```
--------------- tb10
   num txt
0    1   a
1    2   b
2    3   c
--------------- tb12
   id letter
0   1      a
1   3      c
2   3      c
```

Backend=MapD    MapD=4.1.1    ibis=0.14    Python=3.6
Ubuntu=18.04    Anaconda=5.1

**Comment by cpcloud** [comment]
@lzhmhznr It looks like MapD itself might not support that (I'm assuming that was why this choice was made).

@xmnlab Can you comment on this?

**Comment by kszucs** [comment]
@cpcloud That's suspiciously similar to clickhouse's [join compilation](https://github.com/ibis-project/ibis/blob/master/ibis/clickhouse/compiler.py#L132). It might be a wrong copy&paste issue.

**Comment by cpcloud** [comment]
@kszucs Okay. I'm wondering if @xmnlab can take a look since he contributed the original patch.

**Comment by kszucs** [comment]
According to MapD's documentation it [supports](https://www.mapd.com/docs/latest/5_dml.html#table-expression-and-join-support-1) joining on different column names (the latest version at least).

**Comment by xmnlab** [comment]
@kszucs @cpcloud 

thanks for point me that.

cc @tonyfast

**Comment by xmnlab** [comment]
yes it works:

```
mapdql> select * from tb10 left join tb12 on num=id;
num|txt|rowid|id|letter|rowid0
1|a|0|1|a|0
2|b|1|NULL|NULL|NULL
3|c|2|3|c|1
3|c|2|3|c|2
```

I will take a look to fix that. I am also planing to update MapD image in CI.
