### ISSUE TITLE
MapD histogram() : KeyError: <class 'ibis.expr.operations.CrossJoin'>

### ISSUE THREAD

**Issue by lzhmhznr** [ibis-project/ibis#1621]
https://docs.ibis-project.org/notebooks/tutorial/8-More-Analytics-Helpers.html      
In [11]:
`t = con.table('functional_alltypes')

d = t.double_col

tier = d.histogram(10).name('hist_bin')
expr = (t.group_by(tier)
        .aggregate([d.min(), d.max(), t.count()])
        .sort_by('hist_bin'))
expr.execute()`

return error : 
  File "/home/sw/anaconda3/lib/python3.6/site-packages/ibis/sql/compiler.py", line 1808, in _get_join_type
    return self._join_names[type(op)]
KeyError: <class 'ibis.expr.operations.CrossJoin'>

Backend=MapD    MapD=4.1.1    ibis=0.14    Python=3.6
Ubuntu=18.04    Anaconda=5.1

**Comment by cpcloud** [comment]
cc @xmnlab

**Comment by xmnlab** [comment]
It seems MapD doesn't have a cross join .. but maybe we could add this using a workaround like this:

```
SELECT *FROM T1 INNER JOIN T2 ON TRUE;
```

What do you think @cpcloud ?

**Comment by cpcloud** [comment]
As long as that query is equivalent, I'm okay with that.
