### ISSUE TITLE
conda install missing google-cloud-bigquery

### ISSUE THREAD

**Issue by randyzwitch** [ibis-project/ibis#1622]
When installing Ibis version 0.14.0, `conda install ibis-framework -c conda-forge` will give an error that google-cloud-bigquery required.

`conda install google-cloud-bigquery` fixes issue

**Comment by cpcloud** [comment]
@randyzwitch Can you show the error you're getting? `conda` should install `google-cloud-bigquery` if it's required by a package? Are you installing ibis into a Python 3.7 environment?

**Comment by randyzwitch** [comment]
No, it's a 3.6.6 environment. Unfortunately, I added the package and re-ran my code, then thought to open this issue. I could've done something weird though, so I'll close this issue

**Comment by cpcloud** [comment]
Can you show how you created the environment?

**Comment by randyzwitch** [comment]
Unfortunately, I didn't really think about what I was doing, I was just building an environment as I went along. I used conda for all of the installs, then it was some combination of installing/uninstalling pymapd, pygdf, jupyterlab and ibis.
