### ISSUE TITLE
MapD where() : No match found for function signature if(<BOOLEAN>, <NUMERIC>, <NUMERIC>)')

### ISSUE THREAD

**Issue by lzhmhznr** [ibis-project/ibis#1623]
`expr = ibis.where(table.num > 1, table.num + 10, table.num)`
`expr.execute()`
return error :
mapd.ttypes.TMapDException: TMapDException(error_msg='Exception: Exception occurred: org.apache.calcite.runtime.CalciteContextException: From line 1, column 8 to line 1, column 41: No match found for function signature if(<BOOLEAN>, <NUMERIC>, <NUMERIC>)')

Backend=MapD MapD=4.1.1 ibis=0.14 Python=3.6
Ubuntu=18.04 Anaconda=5.1

**Comment by cpcloud** [comment]
cc @xmnlab

**Comment by xmnlab** [comment]
there is no IF function in MapD, but here I think we should translate to `when statement`. thanks for point that.
