### ISSUE TITLE
Taking on PyHive as a dependency for Hive support?

### ISSUE THREAD

**Issue by zdog234** [ibis-project/ibis#1625]
Hi y'all, sorry if this has already been mentioned/considered, but would it make sense to take on [PyHive](https://github.com/dropbox/PyHive) as a dependency in order to bring Hive support to Ibis? (I think it's also Apache licensed).

**Comment by cpcloud** [comment]
@zdog234 Are you interested in working on hive support? You could reuse a lot of the existing sqlalchemy machinery for this. If you're interested, I can help with setting up our CI to spin up a hive service and load testing data into the database. We're already running a metastore for Impala so I don't think there's much beyond installing the service, starting it, and loading data that we'd need to do to get that up and running.

**Comment by zdog234** [comment]
I can definitely try it out. Hopefully I can do a lot of copy-paste.

Sent from Astro <https://www.astro.ai> for iOS


On Sep 19, 2018 at 2:59 PM, Phillip Cloud <notifications@github.com> wrote:


@zdog234 <https://github.com/zdog234> Are you interested in working on hive
support? You could reuse a lot of the existing sqlalchemy machinery for
this. If you're interested, I can help with setting up our CI to spin up a
hive service and load testing data into the database. We're already running
a metastore for Impala so I don't think there's much beyond installing the
service, starting it, and loading data that we'd need to do to get that up
and running.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ibis-project/ibis/issues/1625#issuecomment-422920316>,
or mute the thread

**Comment by cpcloud** [comment]
Ideally there isn't much copy paste, and the only thing you'd need to provide is hive specific versions of whatever functions don't work out of the box for whatever reason (different spelling, different semantics, etc)

**Comment by zdog234** [comment]
Okay, in that case, I'd love to give it a try!

**Comment by zdog234** [comment]
Which linter (if any) should I be using?

**Comment by cpcloud** [comment]
@zdog234 We use `flake8`

**Comment by cpcloud** [comment]
This needs a champion. Will accept PRs.
