### ISSUE TITLE
ENH: Enable Pandas UDFs that must be computed over a window, but are not strictly aggregates

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1633]
Many databases call these "analytic" functions. The unifying theme here seems to be functions that are composed of at least one aggregate function and one non-aggregate function.

An example that comes to mind is Z-score:

```python
# in ibis
z = (t.value - t.value.mean()) / t.value.std()
```

Parts of this expression (the mean and standard deviation) are sensitive to windows, but the remaining piece is not.

This issue is to enable per group user-defined functions that return a Series.

cc @DiegoAlbertoTorres

**Comment by DiegoAlbertoTorres** [comment]
:+1:
