### ISSUE TITLE
MapD  lag()  :  MapD backend doesn't support <class 'ibis.expr.operations.WindowOp'> operation!

### ISSUE THREAD

**Issue by lzhmhznr** [ibis-project/ibis#1635]
>>> table.col.lag().execute()
ibis.common.UnsupportedOperationError: MapD backend doesn't support <class 'ibis.expr.operations.WindowOp'> operation!

Backend=MapD_4.1.1    ibis=0.14    Python=3.6
Ubuntu=18.04    Anaconda=5.1

**Comment by xmnlab** [comment]
It seems MapD doesn't support Window operation, is that right @randyzwitch ?

should we add `lag` as unsupported?

**Comment by randyzwitch** [comment]
That is correct @xmnlab, MapD doesn't support window functions at this time

**Comment by xmnlab** [comment]
@cpcloud should we add as `unsupported` all window operation or we could just leave WindowOp as unsupported?

**Comment by cpcloud** [comment]
This seems like a reasonable error message to me. @xmnlab What do you mean when you say "add as `unsupported`"?

**Comment by xmnlab** [comment]
@cpcloud I mean add the operation inside the `_unsupported_ops` dictionary in the operations.py

`_unsupported_ops = {k: raise_unsupported_op_error for k in _unsupported_ops}`

**Comment by xmnlab** [comment]
if the current message is reasonable I think this issue could be closed.

**Comment by xmnlab** [comment]
actually lag is already in this dictionary: https://github.com/ibis-project/ibis/blob/master/ibis/mapd/operations.py#L628

**Comment by cpcloud** [comment]
I think the current message is reasonable. Closing.

@xmnlab @randyzwitch Is MapD going to grow `lead`/`lag` functions at some point in the future?

**Comment by randyzwitch** [comment]
At some unknown time (to me) in the future, we do plan to support window functions. So lead/lag would be part of that
