### ISSUE TITLE
MapD  str.to_timestamp() : No translation rule for <class 'ibis.expr.operations.StringToTimestamp'>

### ISSUE THREAD

**Issue by lzhmhznr** [ibis-project/ibis#1638]
expr = ibis.literal('20170206').to_timestamp('%Y%m%d')
client.execute(expr)

ibis.common.OperationNotDefinedError: No translation rule for <class 'ibis.expr.operations.StringToTimestamp'>

Backend=MapD_4.1.1    ibis=0.14    Python=3.6  Ubuntu=18.04    Anaconda=5.1

**Comment by xmnlab** [comment]
thanks @lzhmhznr for point us that

I am checking the issues related to MapD and we are planing to add new futures to ibis-mapd also.

@cpcloud could you add a "MapD" flag to this issue?

**Comment by xmnlab** [comment]
@lzhmhznr at this moment this operation is not supported by mapd database. I will change to this function to raise Unsupported Exception.
