### ISSUE TITLE
DSGN: Allow functional definitions of custom nodes

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#1639]
In https://github.com/ibis-project/ibis/pull/1637, the idea of being able to define your own nodes using decorators came up.

For example (and I'm speculating here),

```python
@postgres.udf([dt.double, dt.double], dt.double)
def my_node(x, y, **kwargs):
    return # things in the "space" of the backend, in this case, it would be SQLAlchemy code
```

We should think through what this would look like and discuss any relevant details.

**Comment by scottcode** [comment]
I independently started work on this type of functionality. I didn't follow that API pattern, but I like the decorator style you showed, @cpcloud. If you or anyone else gets a chance, please take a look at my feature branch below and let me know what you think. 

https://github.com/scottcode/ibis/tree/pg_udf

One thing that is lacking in the CI suite to make Postgres UDF testing feasible is that the current Postgres image being used doesn't have PL/Python installed. It's using an image that is a much slimmed-down version of Postgres.  The easiest fix is to use the standard full version of Postgres. I'm working on creating a new Dockerfile that achieves that, but I haven't got it working yet and haven't pushed any code on that yet.

**Comment by scottcode** [comment]
I broke out the Docker image for Postgres supporting PL/Python as a separate issue: #1853
