### ISSUE TITLE
BUG: PostgreSQL interval type not recognized

### ISSUE THREAD

**Issue by dsaxton** [ibis-project/ibis#1661]
I believe this would actually be an issue with `sqlalchemy`, but I noticed that a warning is issued when one tries to reference a Postgres table with a column of interval data type (the warning says that the type isn't recognized).

Here is the DDL for such a table from the Postgres documentation (https://www.postgresql.org/docs/9.1/static/sql-createtable.html):

```
create table films (
    code        char(5) constraint firstkey primary key,
    title       varchar(40) not null,
    did         integer not null,
    date_prod   date,
    kind        varchar(10),
    len         interval hour to minute
);
```

If we then try to refer to this table using `ibis` (after creating it in the public schema of a local database called postgres) we see that the len column has an unrecognized type and we end up with a null data type:

```
import ibis

conn = ibis.postgres.connect(database="postgres")
conn.table("films")
```

**Comment by cpcloud** [comment]
I just prototyped support for this and I think we can get this in for the next release.
