### ISSUE TITLE
How to use pandas as a backend?

### ISSUE THREAD

**Issue by ispmarin** [ibis-project/ibis#1663]
How can I use Ibis with pandas as the backend? I searched the documentation but couldn't find how.

**Comment by tonyfast** [comment]
You can create an ibis pandas backend by supplying a dictionary of DataFrames.  The keys become the table names.

```Python
con = ibis.pandas.connect({
     'A': pandas.util.testing.makeDataFrame(), 
     'B': pandas.util.testing.makeDataFrame()})
con.list_tables(), con.table('A')
```
```Python Console
(['A', 'B'], PandasTable[table]
   name: A
   schema:
     A : double
     B : double
     C : double
     D : double)

**Comment by xmnlab** [comment]
maybe would be good to add some information on the docs.

**Comment by kszucs** [comment]
@xmnlab definitely, a short section to https://docs.ibis-project.org/getting-started.html would be great. MapD and MySQL are also missing.

**Comment by xmnlab** [comment]
@kszucs thanks! I will create a PR for that.
