### ISSUE TITLE
Add Ibis support for geospatial data types

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1665]
@cpcloud @kszucs 

we are planning to add support for geospatial data types and functions into ibis [1].  

it seems it should be put inside the common interface. so if anyone is interested in this implementation we can work together.

we will check geopandas and shapely to check name and signature standard 

cc @tonyfast 

[1] https://github.com/Quansight/mapd/issues/21#issue-366146234

**Comment by kszucs** [comment]
resolved by #1678 and #1666
