### ISSUE TITLE
MySQL testing on Azure Pipelines has been disabled temporarily

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1672]
Because chocolatey was failing to install MariaDB

**Comment by cpcloud** [comment]
Thanks for creating the issue!

**Comment by xmnlab** [comment]
@kszucs do you have the detail of this error? should we open a issue on chocolatey?

**Comment by kszucs** [comment]
@xmnlab First try to re-enable it in a PR, hopefully they resolved it already. Otherwise We should report it. (We could also switch to mysql, but mariadb was working previously)

**Comment by xmnlab** [comment]
@kszucs sounds good! I will create a PR to try that! thanks!
