### ISSUE TITLE
Add pre-commit hooks 

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1673]
Use https://github.com/pre-commit

**Comment by kszucs** [comment]
Hey @xmnlab !

Agree, for starting I think flake8 would be enough, see the available hooks here: https://pre-commit.com/hooks.html

**Comment by xmnlab** [comment]
@kszucs it seems this issue can be closed (https://github.com/ibis-project/ibis/pull/1685)

**Comment by cpcloud** [comment]
Closed by #1685
