### ISSUE TITLE
Add expression method that returns empty Pandas DF for 

### ISSUE THREAD

**Issue by saulshanabrook** [ibis-project/ibis#1676]
It would be helpful to have a method that returns an empty Pandas dataframe from an expression with the correct types of each column. It seems like it should be able to do this without executing any queries.

I am looking for this feature to support creating Altair charts more easily from Ibis expressions. Altair requires a DataFrame to infer column types, but I would like to do this while avoiding actually hitting the backend during chart creation.

**Comment by cpcloud** [comment]
Does this work for your use case?

```
In [10]: import ibis

In [11]: t = ibis.table([('a', 'int32'), ('b', 'string')])

In [12]: df = t.schema().apply_to(pd.DataFrame(columns=t.columns))

In [13]: df.dtypes
Out[13]:
a     int32
b    object
dtype: object
```
