### ISSUE TITLE
Question :how delete row ?

### ISSUE THREAD

**Issue by lzhmhznr** [ibis-project/ibis#1677]
```
how can i delete row , where(tb1.num >= 3)

sqlalchemy :   tb1.delete().where(tb1.c.num >= 3)
--------------- tb1
   num txt             
0    2   b
1    4   d
2    1   a
3    3   c
```

**Comment by xmnlab** [comment]
@lzhmhznr what backend are you using?

**Comment by cpcloud** [comment]
Ibis doesn't support mutating row deletion and likely won't until someone motivated enough to implement the feature comes along. It's not out of the question, but it won't be worked on by any core maintainers for the foreseeable future.
