### ISSUE TITLE
Support OmniSci Sample method

### ISSUE THREAD

**Issue by saulshanabrook** [ibis-project/ibis#1680]
OmniSci [supports](https://www.omnisci.com/docs/latest/5_math.html) the `SAMPLE` aggregate method that:

> Returns one sample value from aggregated column x. 

I don't believe this is implemented in the Ibis wrapper.

**Comment by saulshanabrook** [comment]
I think `Arbitrary` could be the right operation: https://github.com/ibis-project/ibis/issues/1230

So we would just have to add a mapping to OmniSci to map this to `sample`

**Comment by saulshanabrook** [comment]
I am working on adding this.

**Comment by xmnlab** [comment]
in the documentation: 

```
Note: This was previously LAST_SAMPLE, which is now deprecated.
```

(https://www.omnisci.com/docs/latest/5_math.html#aggregate-function-support-1)

so a translation from arbitrary last to sample should works fine
