### ISSUE TITLE
Postgres JSONB

### ISSUE THREAD

**Issue by rdeteix** [ibis-project/ibis#1690]
Hello,

I'm trying to open a postgres table using Ibis which has some jsonb data type.

I got the error:

KeyError: (<class 'sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2'>, <class 'sqlalchemy.dialects.postgresql.json.JSONB'>)

NotImplementedError: Could not find signature for dtype: <PGDialect_psycopg2, JSONB>

I can open it with sqlalchemy/psycopg but it failed when I used Ibis.

Is there any settings that I missed?

Thank you

**Comment by rdeteix** [comment]
Thanks,

I'll try it

**Comment by dhirschfeld** [comment]
Just giving `ibis` a go for the first time and hit this issue with our postgres database.

**Comment by ian-r-rose** [comment]
@dhirschfeld #1963 (not published yet, I think) doesn't add function support for JSON, but it does add a type stub for it, allowing tables that contain JSON/JSONB fields to be loaded.

**Comment by dhirschfeld** [comment]
I'm on a slightly older version. So do plan on testing the latest...

**Comment by dhirschfeld** [comment]
I might have to wait for the next release as conda wants to downgrade too many deps:
```
The following packages will be UPDATED:

  ibis-framework     pkgs/main/win-64::ibis-framework-0.14~ --> conda-forge/noarch::ibis-framework-1.2.0-py_1

The following packages will be DOWNGRADED:

  arrow-cpp                           0.15.1-py37hcc590e5_4 --> 0.12.1-py37h73c4153_0
  boost-cpp                               1.70.0-h6a4c333_2 --> 1.68.0-h6a4c333_1000
  glog                                     0.4.0-h33f27b4_0 --> 0.3.5-h6538335_1
  libprotobuf                             3.10.1-h7bd577a_0 --> 3.6.1-h7bd577a_0
  protobuf                            3.10.1-py37h33f27b4_0 --> 3.6.1-py37h33f27b4_0
  pyarrow                             0.15.1-py37h803c963_1 --> 0.12.1-py37h8c67754_0
  thrift-cpp                           0.12.0-hd042d19_1004 --> 0.12.0-h59828bf_1002
  turbodbc                             3.3.0-py37h337e878_2 --> 3.1.0-py37h51f579c_0
```

**Comment by ian-r-rose** [comment]
To be clear, I think the JSON/JSONB type stub isn't in any published releases right now. It should be installable from master with `pip`, though.

**Comment by cpcloud** [comment]
Would happily accept a PR for this.
