### ISSUE TITLE
[MapD] gpu dataframe output not working as of pymapd >= 0.7.0 in ibis-mapd

### ISSUE THREAD

**Issue by niviksha** [ibis-project/ibis#1693]
With pymapd=>0.7.0, there is support for ability to output query results as cudf DataFrames (cudf.dataframe.dataframe.DataFrame, ugh). The ibis client for mapd raises a `NotImplementedError` when I attempt to call the `select_ipc_gpu` method by setting the `execution_type` parameter = `EXECUTION_TYPE_ICP_GPU` on the connection, although executing the same query directly with pymapd works fine

**Comment by xmnlab** [comment]
hey @niviksha thanks for reporting that.

it seems cudf dataframe is obsolete on ibis: https://github.com/ibis-project/ibis/blob/a6b1957231419d005b51ad505d2867cac9c4862d/ibis/mapd/client.py#L10

I will create a PR to fix that.

@kszucs @cpcloud could this issue be labelled as a bug?

**Comment by xmnlab** [comment]
hey @niviksha !

I am trying to setup a linux+gpu environment to try that (on colab) but without success yet.

but if you want to try you can install from Quansight repo:

```
pip install -q -U git+https://github.com/Quansight/ibis.git@pygdf2cudf
```

my first guess was changing from pygdf to cudf .. but actually it seems it is not necessary also .. so I have just removed that. but it seems you will need cudf in your environment to make it works.

let me know if I can help in any way.
