### ISSUE TITLE
Upload to HDFS not working for large files

### ISSUE THREAD

**Issue by schosser** [ibis-project/ibis#1697]
We have a problem when uploading large files to hdfs using the following code (using Cloudera 6.1):

`hdfs = ibis.hdfs_connect(host=hdfs_host, port=hdfs_port)
client = ibis.impala.connect(host=impala_host, port=impala_port, hdfs_client=hdfs, timeout=10000)
db = client.database(self.database)
db.create_table(self.table, df)`

The code works finde for small files but fails for larger files.

Any help is very much appreciated.

STACK TRACE:
`---------------------------------------------------------------------------
HdfsError                                 Traceback (most recent call last)
<ipython-input-29-1db40772ce1c> in <module>
     22         #client.close()
     23 
---> 24 ToCluster("test", "victor")(df)

<ipython-input-29-1db40772ce1c> in __call__(self, df)
     19         client = ibis.impala.connect(host=impala_host, port=impala_port, hdfs_client=hdfs, timeout=10000)
     20         db = client.database(self.database)
---> 21         db.create_table(self.table, df)
     22         #client.close()
     23 

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ibis/impala/client.py in create_table(self, table_name, obj, **kwargs)
     39         """
     40         return self.client.create_table(table_name, obj=obj,
---> 41                                         database=self.name, **kwargs)
     42 
     43     def list_udfs(self, like=None):

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ibis/impala/client.py in create_table(self, table_name, obj, schema, database, external, force, format, location, partition, like_parquet)
   1105             if isinstance(obj, pd.DataFrame):
   1106                 from ibis.impala.pandas_interop import write_temp_dataframe
-> 1107                 writer, to_insert = write_temp_dataframe(self, obj)
   1108             else:
   1109                 to_insert = obj

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ibis/impala/pandas_interop.py in write_temp_dataframe(client, df)
    115 def write_temp_dataframe(client, df):
    116     writer = DataFrameWriter(client, df)
--> 117     path = writer.write_temp_csv()
    118     return writer, writer.delimited_table(path)

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ibis/impala/pandas_interop.py in write_temp_csv(self)
     48         hdfs_path = pjoin(temp_hdfs_dir, '0.csv')
     49 
---> 50         self.write_csv(hdfs_path)
     51 
     52         return temp_hdfs_dir

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ibis/impala/pandas_interop.py in write_csv(self, path)
     73                 util.log('Writing CSV to: {0}'.format(path))
     74 
---> 75             self.hdfs.put(path, f)
     76         finally:
     77             f.close()

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ibis/filesystems.py in put(self, hdfs_path, resource, overwrite, verbose, **kwargs)
    318             hdfs_path = self.client.resolve(hdfs_path)
    319             self.client.write(hdfs_path, data=resource, overwrite=overwrite,
--> 320                               **kwargs)
    321             return hdfs_path
    322 

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hdfs/client.py in write(self, hdfs_path, data, overwrite, permission, blocksize, replication, buffersize, append, encoding)
    474       return AsyncWriter(consumer)
    475     else:
--> 476       consumer(data)
    477 
    478   def upload(self, hdfs_path, local_path, n_threads=1, temp_dir=None,

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hdfs/client.py in consumer(_data)
    469       )
    470       if not res:
--> 471         raise _to_error(res)
    472 
    473     if data is None:

HdfsError: java.util.concurrent.TimeoutException: Idle timeout expired: 1000/1000 ms`

**Comment by xmnlab** [comment]
@kszucs could you add a bug label to this issue? I will investigate this problem.

**Comment by xmnlab** [comment]
@schosser maybe on `hdfs = ibis.hdfs_connect(host=hdfs_host, port=hdfs_port)` you should specify a timeout parameter 

see

- https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.ext.kerberos.KerberosClient


if I understood correctly `hdfs_connect` uses `KerberosClient` or `InsecureClient` .. both extends from `Client` and the requests made be `Client` uses `timeout` attributed define on client instantiation. 

`hdfs_connect` pass **kwds into`KerberosClient` or `InsecureClient` 

so a large `timeout` argument on hdfs_connect should works for you.

let me know if it helps. 

@kszucs maybe we can just label this issue as `question`.

**Comment by schosser** [comment]
@xmnlab thank you very much for your fast response. 

Before describing the issue, I have tried several (larger) values for the timeout, both for hdfs_connect and impala.connect (see bellow). No matter how large the values I specify, the response I get is the same. After about 10 Seconds (the delay does not change), I get the error above.

(I used the following code, varying the timeout from 100, 1000, ... to 10000000.

`hdfs = ibis.hdfs_connect(host=hdfs_host, port=hdfs_port, timeout=10000000) 
client = ibis.impala.connect(host=impala_host, port=impala_port, hdfs_client=hdfs, timeout=10000000)`

We can definitely label this a question. Given that the timeout I specify does not influence the result, nor the delay until the result occurs, I still assume it is a bug.

**Comment by xmnlab** [comment]
@schosser could you try `timeout=None` to `hdfs_connect` and maybe also to `ibis.impala.connect`?

**Comment by schosser** [comment]
@xmnlab unfortunately, timeout=None does not influence the outcome. The described behaviour occurs, when you put timeout=None to hdfs_connect or to ibis.impala.connect or both.

**Comment by xmnlab** [comment]
@schosser 

I am investigating where is the problem (https://github.com/mtth/hdfs/issues/113)

when I find something I will report it here.
