### ISSUE TITLE
Resolve / test for concurrent access of PythonWorkerPool

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#17]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Wednesday Dec 10, 2014 at 19:04 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/17_

---

This class is not threadsafe at the moment, I don't think

**Comment by cpcloud** [comment]
This no longer exists, even in the git history so we couldn't test it even if we wanted to.
