### ISSUE TITLE
Re-enable conda-forge CI build steps

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1700]
Had to disable conda build steps in #1696 until We update the recipe in the conda forge feedstock.
There were a lot of changes around conda-forge lately: compiler migration, dropped python3.5 support and ibis also dropped python2.7.

**Comment by xmnlab** [comment]
maybe now we can enable this again. if it is correct I can open a PR to enable that.

**Comment by kszucs** [comment]
That'd be great!
