### ISSUE TITLE
Export data to disk

### ISSUE THREAD

**Issue by ispmarin** [ibis-project/ibis#1702]
Is is possible to export a table to the local disk, in whatever format? I'm reading a very large partitioned dataset from Impala and would like to manipulate this dataset in Pandas, but to make things fit into memory, I create a query in Ibis filtering the data and execute it. The problem is that this query fails because of the HiveServer2 connection reset, so I would like to export it first to the disk and then use Pandas to read it from disk.

**Comment by cpcloud** [comment]
See #1088. @saulpw @gforsyth this is at least the issue of this kind and will be addressed in the "return type" epic.
