### ISSUE TITLE
[question] Empty structure for Hive

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1703]
Hey everyone! is there a reason that Hive structure doesn't have any code there?
https://github.com/ibis-project/ibis/tree/master/ibis/hive

**Comment by xmnlab** [comment]
@kszucs any thoughts?

**Comment by cpcloud** [comment]
I have a branch I'm working on to remove all of these empty dirs we have lying around.

**Comment by xmnlab** [comment]
Great! Thanks @cpcloud for the feedback!

**Comment by cpcloud** [comment]
These dirs are all gone now:

```
❯ fd hive -t directory --no-ignore --hidden | wc -l
0
```
