### ISSUE TITLE
Impala Test env crashing on tests

### ISSUE THREAD

**Issue by ryan-pip** [ibis-project/ibis#1709]
I am trying to contribute to the impala backend but when i try to run the tests it crashed impala.  I can run the test_client.py fine but as soon as i run any of the tests from test_udf.py the impala daemon crashes.  

I am using OSx Mojave 10.4.3 running Docker for Mac Engine 18.09.3

This is the error that is get out of the impalad logs:
[root@impala /]# tail -n 50 /var/log/impala/impalad.ERROR 
Log file created at: 2019/03/06 09:14:46
Running on machine: impala
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0306 09:14:46.528039  1118 logging.cc:121] stderr will be logged to this file.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/hive/lib/hive-exec-1.1.0-cdh5.15.0.jar!/shaded/parquet/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/parquet/lib/parquet-hadoop-bundle-1.5.0-cdh5.15.0.jar!/shaded/parquet/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [shaded.parquet.org.slf4j.helpers.NOPLoggerFactory]
F0306 09:21:01.841611  2338 llvm-codegen.cc:128] LLVM hit fatal error: Program used external function '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE11_M_capacityEm' which could not be resolved!
*** Check failure stack trace: ***
    @          0x20eec9d  google::LogMessage::Fail()
    @          0x20f0542  google::LogMessage::SendToLog()
    @          0x20ee677  google::LogMessage::Flush()
    @          0x20f1c3e  google::LogMessageFatal::~LogMessageFatal()
    @           0xd9ede0  (unknown)
    @          0x202dc0a  llvm::report_fatal_error()
    @          0x1e310ca  llvm::RuntimeDyldImpl::resolveExternalSymbols()
    @          0x1e31104  llvm::RuntimeDyldImpl::resolveRelocations()
    @          0x1ca3555  llvm::MCJIT::finalizeLoadedModules()
    @          0x1ca3a41  llvm::MCJIT::finalizeObject()
    @           0xdacb42  impala::LlvmCodeGen::FinalizeModule()
    @           0xbedb74  Java_org_apache_impala_service_FeSupport_NativeEvalExprsWithoutRow
    @     0x7f0df1349774  (unknown)

**Comment by kszucs** [comment]
@ryan-pip I suggest to skip `udf` tests if You're not developing them until it is resolved. Run pytest with `-m "not udf"`:

`pytest ibis -m "not udf"`

**Comment by ryan-pip** [comment]
@kszucs the code for type conversion is sitting in the udf code which is what i am working with to allow me to deal with tables with complex column types. Is this tested somewhere else?

**Comment by xmnlab** [comment]
hey @ryan-pip . maybe you could open a WIP PR so we can take a look if we can figure out what could be fixed. could you send here the result of your `conda list` ?

**Comment by ryan-pip** [comment]
hey @xmnlab i thought it was my changes so i tried this on master and am getting the exact same results.

(ibis36) LA-C02WF1CBHV2Q:ibis 744697$ conda list
# packages in environment at /anaconda2/envs/ibis36:
#
# Name                    Version                   Build  Channel
apipkg                    1.5                        py_0    conda-forge
arrow-cpp                 0.9.0            py36ha51b053_7  
asn1crypto                0.24.0                py36_1003    conda-forge
aspy.yaml                 1.2.0                      py_0    conda-forge
astroid                   2.1.0                    py36_0  
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
bcrypt                    3.1.4            py36h470a237_0    conda-forge
bitarray                  0.8.3            py36h1de35cc_0  
blas                      1.0                         mkl  
blosc                     1.15.1            h0a44026_1002    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.1.23                     0  
cached-property           1.5.1                      py_0    conda-forge
cachetools                2.1.0                      py_0    conda-forge
certifi                   2018.11.29               py36_0  
cffi                      1.12.2           py36h342bebf_0    conda-forge
cfgv                      1.5.0                      py_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
clickhouse-cityhash       1.0.2.2         py36h0a44026_1000    conda-forge
clickhouse-driver         0.0.16                     py_0    conda-forge
clickhouse-sqlalchemy     0.0.10                     py_0    conda-forge
cmake                     3.13.4               h1e01633_0    conda-forge
coverage                  4.5.2           py36h1de35cc_1001    conda-forge
cryptography              2.5              py36ha12b0ac_0  
curl                      7.63.0            ha441bb4_1000  
docopt                    0.6.2                      py_1    conda-forge
editdistance              0.5.2            py36h0a44026_0    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
execnet                   1.5.0                      py_0    conda-forge
expat                     2.2.5             h0a44026_1002    conda-forge
fastavro                  0.21.19          py36h1de35cc_0    conda-forge
flake8                    3.7.7                    py36_0    conda-forge
freetype                  2.9.1             h597ad8a_1005    conda-forge
gettext                   0.19.8.1          hcca000d_1001    conda-forge
google-api-core           1.8.0                    py36_0    conda-forge
google-auth               1.6.3                      py_0    conda-forge
google-cloud-bigquery     1.9.0                      py_0    conda-forge
google-cloud-core         0.28.1                     py_0    conda-forge
google-resumable-media    0.3.2                      py_0    conda-forge
googleapis-common-protos  1.5.8                      py_0    conda-forge
graphviz                  2.38.0            hc6cc99f_1011    conda-forge
hdf5                      1.10.4          nompi_h646315f_1105    conda-forge
ibis-framework            0.14.0+42.g1eb3cb5           <pip>
icu                       58.2              h0a44026_1000    conda-forge
identify                  1.4.0                      py_0    conda-forge
idna                      2.8                   py36_1000    conda-forge
importlib_metadata        0.8                      py36_0    conda-forge
importlib_resources       1.0.2                 py36_1000    conda-forge
impyla                    0.14.1                   py36_1  
intel-openmp              2019.1                      144  
isort                     4.3.8                    py36_0  
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
krb5                      1.16.1               hddcf347_7  
lazy-object-proxy         1.3.1            py36h1de35cc_2  
libboost                  1.65.1               hcc95346_4  
libcurl                   7.63.0            h051b688_1000  
libcxx                    7.0.0                h2d50403_1    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libevent                  2.1.8                ha12b0ac_0  
libffi                    3.2.1             h0a44026_1005    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h1de35cc_1004    conda-forge
libpng                    1.6.36            ha441bb4_1000    conda-forge
libpq                     11.1                 h051b688_0  
libprotobuf               3.5.2                h2cd40f5_0  
libssh2                   1.8.0                ha12b0ac_4  
libtiff                   4.0.10            h79f4b77_1001    conda-forge
libuv                     1.24.0            h1de35cc_1000    conda-forge
libxcb                    1.13              h1de35cc_1002    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
lz4                       2.1.6           py36ha80a62f_1000    conda-forge
lz4-c                     1.8.1.2                       0    conda-forge
markupsafe                1.1.1            py36h1de35cc_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h5e564d8_0  
mkl_random                1.0.2            py36h27c97d8_0  
more-itertools            4.3.0                 py36_1000    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
multipledispatch          0.6.0                     <pip>
mypy                      0.670                      py_0    conda-forge
mypy_extensions           0.4.1                 py36_1000    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
nodeenv                   1.3.3                      py_0    conda-forge
numexpr                   2.6.9           py36h1702cab_1000    conda-forge
numpy                     1.16.2           py36hacdab7b_0  
numpy-base                1.16.2           py36h6575580_0  
openblas                  0.3.3             hdc02c5d_1001    conda-forge
openssl                   1.1.1b               h1de35cc_0  
pandas                    0.24.1           py36h0a44026_0    conda-forge
paramiko                  2.4.2                 py36_1000    conda-forge
parquet-cpp               1.4.0                h502425d_0  
pip                       19.0.3                   py36_0    conda-forge
pluggy                    0.9.0                      py_0    conda-forge
plumbum                   1.6.7                      py_0    conda-forge
ply                       3.11                       py_1    conda-forge
pre_commit                1.14.4                   py36_0    conda-forge
protobuf                  3.5.2            py36h0a44026_1  
psutil                    5.4.8           py36h1de35cc_1000    conda-forge
psycopg2                  2.7.6.1          py36ha12b0ac_0  
pthread-stubs             0.4               h1de35cc_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pyarrow                   0.9.0            py36h6f6535b_2  
pyasn1                    0.4.4                      py_1    conda-forge
pyasn1-modules            0.2.4                      py_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pykerberos                1.1.14           py36h52afbb8_2  
pylint                    2.2.2                    py36_0  
pymysql                   0.8.1                      py_0    conda-forge
pynacl                    1.3.0           py36h1de35cc_1000    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pytables                  3.4.4           py36h0af8b44_1004    conda-forge
pytest                    4.3.0                    py36_0    conda-forge
pytest-cov                2.6.1                      py_0    conda-forge
pytest-forked             1.0.2                      py_0    conda-forge
pytest-xdist              1.26.1                     py_0    conda-forge
python                    3.6.8                haf84260_0  
python-dateutil           2.8.0                      py_0    conda-forge
python-graphviz           0.10.1                     py_0    conda-forge
python-hdfs               2.2.1                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13            py36h1de35cc_1001    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
regex                     2019.02.21       py36h1de35cc_0    conda-forge
requests                  2.21.0                py36_1000    conda-forge
requests-kerberos         0.12.0                   py36_0  
rhash                     1.3.6             h1de35cc_1001    conda-forge
rsa                       3.4.2                      py_1    conda-forge
ruamel.yaml               0.15.89          py36h1de35cc_0    conda-forge
setuptools                40.8.0                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
snappy                    1.1.7                he62c110_3  
sqlalchemy                1.2.18           py36h1de35cc_0    conda-forge
sqlite                    3.26.0            h1765d9f_1000    conda-forge
thrift                    0.11.0          py36h0a44026_1001    conda-forge
thrift-cpp                0.11.0               hd79cdb6_3  
thriftpy                  0.3.9           py36h1de35cc_1001    conda-forge
tk                        8.6.9             ha441bb4_1000    conda-forge
toml                      0.10.0                     py_0    conda-forge
toolz                     0.9.0                      py_1    conda-forge
toolz                     0.9.0                     <pip>
typed-ast                 1.2.0           py36h1de35cc_1000    conda-forge
typing                    3.6.4                    py36_0    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
virtualenv                16.0.0                py36_1000    conda-forge
wheel                     0.33.1                   py36_0    conda-forge
wrapt                     1.11.1           py36h1de35cc_0  
xorg-kbproto              1.0.7             h1de35cc_1002    conda-forge
xorg-libice               1.0.9             h1de35cc_1004    conda-forge
xorg-libsm                1.2.3             h1de35cc_1000    conda-forge
xorg-libx11               1.6.7             h1de35cc_1000    conda-forge
xorg-libxau               1.0.9                h1de35cc_0    conda-forge
xorg-libxdmcp             1.1.2             h1de35cc_1007    conda-forge
xorg-libxext              1.3.3             h1de35cc_1004    conda-forge
xorg-libxpm               3.5.12            h1de35cc_1002    conda-forge
xorg-libxrender           0.9.10            h1de35cc_1002    conda-forge
xorg-libxt                1.1.5             h1de35cc_1002    conda-forge
xorg-renderproto          0.11.1            h1de35cc_1002    conda-forge
xorg-xextproto            7.3.0             h1de35cc_1002    conda-forge
xorg-xproto               7.0.31            h1de35cc_1007    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zipp                      0.3.3                      py_0    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.3.3                h2a6be3a_0

**Comment by xmnlab** [comment]
@ryan-pip thanks for the response. are you using the impala docker from ibis?

**Comment by ryan-pip** [comment]
Yes, I am setting up all the test dbs with make init but doing the testing from a local env through the VS Code integration.  

An interesting point on that I had to add impala to my hosts file as webhdfs does a redirect when creating a file.  This means the second api call times out as it is to impala not localhost.  This means that test impala env fails to create impala from outside the docker network unless it can resolve impala to localhost

**Comment by ryan-pip** [comment]
I have also just checked purely using the provided docker images for dbs and test.
1. ci/test.sh ibis/impala/tests/test_client.py all passed
2. ci/test.sh ibis/impala/tests/test_udf.py started passing and then failed
3. ci/test.sh ibis/impala/tests/test_client.py all failed 35 error in 10.25 seconds 

Checked the logs on the impalad and they are the same.

**Comment by xmnlab** [comment]
thanks @ryan-pip for the feedback ... I will check this today.

**Comment by ryan-pip** [comment]
I have created a pull request with the changes #1718.  It is currently passing all the tests I can test against.
