### ISSUE TITLE
Negating a TopK to produce the "Other" set

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#171]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Wednesday Mar 25, 2015 at 18:35 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/171_

---

This should be nicely supported (semi join flipped to anti join), e.g.

`table[-table.field.topk(5)]`

**Comment by cpcloud** [comment]
Closing. This could potentially be useful, but it needs a champion/use case.
