### ISSUE TITLE
Properly define all validators instead of using rlz.noop in operations.py

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#1717]
All occurences of `rlz.noop` like [this](https://github.com/ibis-project/ibis/blob/master/ibis/expr/operations.py#L290) should be replaced by proper validators. Noop is just a placeholder.

**Comment by cpcloud** [comment]
This is no longer in use:

```
❯ rg '(rules|rlz)?\.noop' | wc -l
0
```
