### ISSUE TITLE
(Enhancement) Use a sql query as an expression

### ISSUE THREAD

**Issue by niviksha** [ibis-project/ibis#1731]
Is there a way for ibis to have an expression simply be a static, pre-existing SQL query? e.g. today, the primary workflow for ibis (in our omnisci/mapd backend) is to generate sql via the compilation path, and i get that the primary use case is as a deferred expression system, e.g. the typical flow is

```
conn = ibis.mapd.conn(....)
t = conn.table('tbl')
expr = t[t.colA > 50].group_by(t.colB).aggregate(t.count())...
output_df = expr.execute()
```

however, there are several cases where we find ourselves wanting a pre-existing SQL query to be the 'basis' of an expression - e.g.

```
query_str = 'select a, b, count(*) as ct from tbl where ... group by a,b having ...'
expr_query = expr_from_query_string(query) #(A 'pre-compiled' expression
expr2 = expr_query[(ct > 50) & (a == 'foo)] 
```
ideally should generate a query with a [CTE ](https://www.geeksforgeeks.org/cte-in-sql/) for query_str i.e the above when compiled should return something like
```
WITH t0 as (
select a, b, count(*) as ct from tbl where ... group by a,b having ...'
) select * from t0 where t0.a == 'foo' and t0.ct > 50
```

**Comment by xmnlab** [comment]
not sure if it is what `SQLClient.sql` does. I am going to investigate that.
