### ISSUE TITLE
Syntax errors in Python 3.5

### ISSUE THREAD

**Issue by toryhaavik** [ibis-project/ibis#1750]
I had an old conda environment running Python 3.5, and I pulled to get the latest 1.0.0 commits. When I try to run any pytests, I get the pytest config errors that have this in the stack trace:

```
During handling of the above exception, another exception occurred:
../../miniconda3/envs/ibis_dev/lib/python3.5/site-packages/_pytest/config.py:379: in _importconftest
    mod = conftestpath.pyimport()
../../miniconda3/envs/ibis_dev/lib/python3.5/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
E     File "/home/tory/git/ibis/ibis/__init__.py", line 67
E       **kwds,
E             ^
E   SyntaxError: invalid syntax
```

I think the addition of `black` has made incompatible changes for Python 3.5. This example is an extra comma at the end of an argument list that contains `**kwargs`.

If I build a new conda env with Python 3.6, the tests all pass.

**Comment by cpcloud** [comment]
Yep sounds right. Seems like we'll need a bug fix release fairly soon then.

**Comment by xmnlab** [comment]
probably related to this: https://github.com/ambv/black/issues/419

**Comment by cpcloud** [comment]
We'll need to officially support 3.5 (not in conda-forge, though) for a little while. I'll add some jobs to the CI to test 3.5.

**Comment by cpcloud** [comment]
This is fixed in black master: https://github.com/ambv/black/commit/cea13f498418784e22f8fbd78db3f9240a2bad11
