### ISSUE TITLE
Error on Login into Hive on Kerberized Cluster

### ISSUE THREAD

**Issue by manotasce** [ibis-project/ibis#1752]
I have a Kerberized Hadoop Cluster and I want to interact with Hive through ibis-framework. I executed this command

>>> import ibis
UserWarning: locale specific date formats (%c, %x, %X) are not yet implemented for Windows
  'for %s' % platform.system()
>>> hdfs = ibis.hdfs_connect(host=os.environ['IP_HDFS'], port=50070)
>>> client = ibis.impala.connect(host=os.environ['IP_HIVE'], hdfs_client=hdfs, auth_mechanism='GSSAPI')

I got this error:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 131, in _get_cursor
    cursor = self.connection_pool.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\api.py", line 118, in connect
    client = ImpalaClient(con, hdfs_client=hdfs_client)
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 791, in __init__
    self._ensure_temp_db_exists()
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 1394, in _ensure_temp_db_exists
    if not self.exists_database(name):
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 909, in exists_database
    return bool(self.list_databases(like=name))
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 1004, in list_databases
    with self._execute(statement, results=True) as cur:
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\client.py", line 122, in _execute
    cur = self.con.execute(query)
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 102, in execute
    cursor = self._get_cursor()
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 134, in _get_cursor
    return self._new_cursor()
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 147, in _new_cursor
    con = impyla.connect(database=self.database, **params)
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\impala\dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism)
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\impala\hiveserver2.py", line 763, in connect
    auth_mechanism, user, password)
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\impala\_thrift_api.py", line 149, in get_transport
    from thrift_sasl import TSaslClientTransport
ModuleNotFoundError: No module named 'thrift_sasl'

I installed missing module by running following command:
conda install thrift_sasl

I tried again and I got following error
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 131, in _get_cursor
    cursor = self.connection_pool.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\api.py", line 118, in connect
    client = ImpalaClient(con, hdfs_client=hdfs_client)
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 791, in __init__
    self._ensure_temp_db_exists()
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 1394, in _ensure_temp_db_exists
    if not self.exists_database(name):
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 909, in exists_database
    return bool(self.list_databases(like=name))
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 1004, in list_databases
    with self._execute(statement, results=True) as cur:
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\client.py", line 122, in _execute
    cur = self.con.execute(query)
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 102, in execute
    cursor = self._get_cursor()
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 134, in _get_cursor
    return self._new_cursor()
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\ibis\impala\client.py", line 147, in _new_cursor
    con = impyla.connect(database=self.database, **params)
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\impala\dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism)
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\impala\hiveserver2.py", line 764, in connect
    transport.open()
  File "C:\ProgramData\Anaconda3\envs\hadoop3.6\lib\site-packages\thrift_sasl\__init__.py", line 67, in open
    if not self._trans.isOpen():
AttributeError: 'TSocket' object has no attribute 'isOpen'

Environment info:
Conda list (using Python 3.6.7)
Name                    Version                   Build  Channel
alabaster                 0.7.12                   py36_0
anaconda                  custom           py36h363777c_0
anaconda-client           1.7.2                    py36_0
anaconda-project          0.8.2                    py36_0
arrow-cpp                 0.12.1           py36h73c4153_0    conda-forge
asn1crypto                0.24.0                   py36_0
astroid                   2.1.0                    py36_0
astropy                   3.1              py36he774522_0
atomicwrites              1.2.1                    py36_0
attrs                     18.2.0           py36h28b3542_0
babel                     2.6.0                    py36_0
backcall                  0.1.0                    py36_0
backports                 1.0                      py36_1
backports.os              0.1.1                    py36_0
backports.shutil_get_terminal_size 1.0.0                    py36_2
beautifulsoup4            4.6.3                    py36_0
bitarray                  0.8.3            py36hfa6e2cd_0
bkcharts                  0.2              py36h7e685f7_0
blas                      1.0                         mkl
blaze                     0.11.3                   py36_0
bleach                    3.0.2                    py36_0
blosc                     1.14.4               he51fdeb_0
bokeh                     1.0.2                    py36_0
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
boto                      2.49.0                   py36_0
bottleneck                1.2.1            py36h452e1ab_1
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cachetools                2.1.0                      py_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.11.5           py36h74b6da3_1
chardet                   3.0.4                    py36_1
click                     7.0                      py36_0
clickhouse-driver         0.0.16                     py_0    conda-forge
cloudpickle               0.6.1                    py36_0
clyent                    1.2.2                    py36_1
colorama                  0.4.1                    py36_0
comtypes                  1.1.7                    py36_0
conda                     4.6.9                    py36_0    conda-forge
conda-build               3.17.6                   py36_0
conda-env                 2.6.0                         1
console_shortcut          0.1.1                         3
contextlib2               0.5.5            py36he5d52c0_0
cryptography              2.4.2            py36h7a1dbc1_0
curl                      7.63.0            h2a8f88b_1000
cycler                    0.10.0           py36h009560c_0
cython                    0.29.2           py36ha925a31_0
cytoolz                   0.9.0.1          py36hfa6e2cd_1
dask                      1.0.0                    py36_0
dask-core                 1.0.0                    py36_0
datashape                 0.5.4                    py36_1
decorator                 4.3.0                    py36_0
defusedxml                0.5.0                    py36_1
distributed               1.25.1                   py36_0
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3                    py36_2
et_xmlfile                1.0.1            py36h3d2d736_0
fastavro                  0.21.19          py36hfa6e2cd_0    conda-forge
fastcache                 1.0.2            py36hfa6e2cd_2
filelock                  3.0.10                   py36_0
flask                     1.0.2                    py36_1
flask-cors                3.0.7                    py36_0
freetype                  2.9.1                ha9979f8_1
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.3.7            py36he774522_1
gflags                    2.2.2             he025d50_1001    conda-forge
glob2                     0.6                      py36_1
glog                      0.3.5                h6538335_1
google-api-core           1.8.2                    py36_0    conda-forge
google-auth               1.6.3                      py_0    conda-forge
google-cloud-bigquery     1.10.0                     py_1    conda-forge
google-cloud-core         0.29.1                     py_0    conda-forge
google-resumable-media    0.3.2                      py_0    conda-forge
googleapis-common-protos  1.5.8                      py_0    conda-forge
graphviz                  2.38.0            h6538335_1011    conda-forge
greenlet                  0.4.15           py36hfa6e2cd_0
h5py                      2.8.0            py36h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py36_2
html5lib                  1.0.1                    py36_0
ibis-framework            1.0.0                      py_1    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py36_0
imageio                   2.4.1                    py36_0
imagesize                 1.1.0                    py36_0
importlib_metadata        0.6                      py36_0
impyla                    0.14.2                   py36_0    conda-forge
intel-openmp              2019.1                      144
ipykernel                 5.1.0            py36h39e3cac_0
ipython                   7.2.0            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.4.2                    py36_0
isort                     4.3.4                    py36_0
itsdangerous              1.1.0                    py36_0
jdcal                     1.4                      py36_0
jedi                      0.13.2                   py36_0
jinja2                    2.10                     py36_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0                    py36_7
jupyter_client            5.2.4                    py36_0
jupyter_console           6.0.0                    py36_0
jupyter_core              4.4.0                    py36_0
jupyterlab                0.35.3                   py36_0
jupyterlab_server         0.2.0                    py36_0
keyring                   17.0.0                   py36_0
kiwisolver                1.0.1            py36h6538335_0
krb5                      1.16.1               hc04afaa_7
lazy-object-proxy         1.3.1            py36hfa6e2cd_2
libarchive                3.3.3                h0643e63_5
libcurl                   7.63.0            h2a8f88b_1000
libiconv                  1.15                 h1df5818_7
libpng                    1.6.35               h2a8f88b_0
libpq                     11.2                 h3235a2c_0
libprotobuf               3.6.1             h1a1b453_1001    conda-forge
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0                h7a1dbc1_4
libtiff                   4.0.9                h36446d0_2
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.26.0           py36ha925a31_0
locket                    0.2.0            py36hfed976d_1
lxml                      4.2.5            py36hef2cd61_0
lz4                       2.1.6           py36h37e296c_1000    conda-forge
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.0            py36he774522_0
matplotlib                3.0.2            py36hc8f65d3_0
mccabe                    0.6.1                    py36_1
menuinst                  1.4.14           py36hfa6e2cd_0
mistune                   0.8.4            py36he774522_0
mkl                       2019.1                      144
mkl-service               1.1.2            py36hb782905_5
mkl_fft                   1.0.6            py36h6288b17_0
mkl_random                1.0.2            py36h343c172_0
more-itertools            4.3.0                    py36_0
mpmath                    1.1.0                    py36_0
msgpack-python            0.5.6            py36he980bc4_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py36_0
nbconvert                 5.4.0                    py36_1
nbformat                  4.4.0            py36h3a5bc1b_0
networkx                  2.2                      py36_1
nltk                      3.4                      py36_1
nose                      1.3.7                    py36_2
notebook                  5.7.4                    py36_0
numba                     0.41.0           py36hf9181ef_0
numexpr                   2.6.8            py36hdce8814_0
numpy                     1.15.4           py36h19fb1c0_0
numpy-base                1.15.4           py36hc3f5095_0
numpydoc                  0.8.0                    py36_0
odo                       0.5.1            py36h7560279_0
olefile                   0.46                     py36_0
openpyxl                  2.5.12                   py36_0
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
packaging                 18.0                     py36_0
pandas                    0.23.4           py36h830ac7b_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2                    py36_1
parquet-cpp               1.5.1                         4    conda-forge
parso                     0.3.1                    py36_0
partd                     0.3.9                    py36_0
path.py                   11.5.0                   py36_0
pathlib2                  2.3.3                    py36_0
patsy                     0.5.1                    py36_0
pep8                      1.7.1                    py36_0
pickleshare               0.7.5                    py36_0
pillow                    5.3.0            py36hdc69c19_0
pip                       18.1                     py36_0
pkginfo                   1.4.2                    py36_1
pluggy                    0.8.0                    py36_0
ply                       3.11                     py36_0
prometheus_client         0.5.0                    py36_0
prompt_toolkit            2.0.7                    py36_0
protobuf                  3.6.1           py36he025d50_1001    conda-forge
psutil                    5.4.8            py36he774522_0
psycopg2                  2.7.7            py36hb32ad35_2    conda-forge
py                        1.7.0                    py36_0
pyarrow                   0.12.1           py36h8c67754_0    conda-forge
pyasn1                    0.4.4                      py_1    conda-forge
pyasn1-modules            0.2.4                      py_0    conda-forge
pycodestyle               2.4.0                    py36_0
pycosat                   0.6.3            py36hfa6e2cd_0
pycparser                 2.19                     py36_0
pycrypto                  2.6.1            py36hfa6e2cd_9
pycurl                    7.43.0.2         py36h7a1dbc1_0
pyflakes                  2.0.0                    py36_0
pygments                  2.3.1                    py36_0
pylint                    2.2.2                    py36_0
pymapd                    0.8.3                      py_0    conda-forge
pymysql                   0.8.1                      py_0    conda-forge
pyodbc                    4.0.25           py36ha925a31_0
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.3.0                    py36_0
pyqt                      5.9.2            py36h6538335_2
pysocks                   1.6.8                    py36_0
pytables                  3.4.4            py36he6f6034_0
pytest                    4.0.2                    py36_0
pytest-arraydiff          0.3              py36h39e3cac_0
pytest-astropy            0.5.0                    py36_0
pytest-doctestplus        0.2.0                    py36_0
pytest-openfiles          0.3.1                    py36_0
pytest-remotedata         0.3.1                    py36_0
python                    3.6.7                h9f7ef89_2
python-dateutil           2.7.5                    py36_0
python-graphviz           0.10.1                     py_0    conda-forge
python-hdfs               2.3.1                      py_0    conda-forge
python-libarchive-c       2.8                      py36_6
pytz                      2018.7                   py36_0
pywavelets                1.0.1            py36h8c2d366_0
pywin32                   223              py36hfa6e2cd_1
pywinpty                  0.5.5                 py36_1000
pyyaml                    3.13             py36hfa6e2cd_0
pyzmq                     17.1.2           py36hfa6e2cd_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.5.3                    py36_0
qtconsole                 4.4.3                    py36_0
qtpy                      1.5.2                    py36_0
regex                     2019.03.12               pypi_0    pypi
requests                  2.21.0                   py36_0
requests-kerberos         0.12.0                   py36_0
rope                      0.11.0                   py36_0
rsa                       3.4.2                      py_1    conda-forge
ruamel_yaml               0.15.46          py36hfa6e2cd_0
scikit-image              0.14.1           py36ha925a31_0
scikit-learn              0.20.1           py36h343c172_0
scipy                     1.1.0            py36h29ff71c_2
seaborn                   0.9.0                    py36_0
send2trash                1.5.0                    py36_0
setuptools                40.6.3                   py36_0
simplegeneric             0.8.1                    py36_2
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.19.8           py36h6538335_0
six                       1.12.0                   py36_0
snappy                    1.1.7                h777316e_3
snowballstemmer           1.2.1            py36h763602f_0
sortedcollections         1.0.1                    py36_0
sortedcontainers          2.1.0                    py36_0
sphinx                    1.8.2                    py36_0
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                    py36_1
spyder                    3.3.2                    py36_0
spyder-kernels            0.3.0                    py36_0
sqlalchemy                1.2.15           py36he774522_0
sqlite                    3.26.0               he774522_0
statsmodels               0.9.0            py36h452e1ab_0
sympy                     1.3                      py36_0
tblib                     1.3.2            py36h30f5020_0
terminado                 0.8.1                    py36_1
testpath                  0.4.2                    py36_0
thrift                    0.11.0          py36h6538335_1001    conda-forge
thrift-cpp                0.12.0            h59828bf_1002    conda-forge
thriftpy                  0.3.9           py36hfa6e2cd_1001    conda-forge
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                    py36_0
tornado                   5.1.1            py36hfa6e2cd_0
tqdm                      4.28.1           py36h28b3542_0
traitlets                 4.3.2            py36h096827d_0
typed-ast                 1.1.0            py36hfa6e2cd_0
unicodecsv                0.14.1           py36h6450c06_0
urllib3                   1.24.1                   py36_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1                    py36_1
werkzeug                  0.14.1                   py36_0
wheel                     0.32.3                   py36_0
widgetsnbextension        3.4.2                    py36_0
win_inet_pton             1.0.1                    py36_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
winkerberos               0.7.0                    py36_1
winpty                    0.4.3                         4
wrapt                     1.10.11          py36hfa6e2cd_2
xlrd                      1.2.0                    py36_0
xlsxwriter                1.1.2                    py36_0
xlwings                   0.15.1                   py36_0
xlwt                      1.3.0            py36h1a4751e_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.2.5                he025d50_1
zict                      0.1.3                    py36_0
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

**Comment by xmnlab** [comment]
hey @manotasce what is the version of thrift_sasl you are using?

it seems you will need to downgrade thrift to 0.9.3 and thrift_sasl to 0.2.1 ... you can see the discussion on https://github.com/cloudera/impyla/issues/268

but not sure if it will have side effects

**Comment by xmnlab** [comment]
hey @manotasce do you have any update about this?

**Comment by be-rock** [comment]
thrift_sasl==0.2.1 appears to force a downgrade in python 3.7.x environments to 3.6.x which introduces challenges of its own
