### ISSUE TITLE
ADD REFRESH capability to Postgres Client

### ISSUE THREAD

**Issue by scottcode** [ibis-project/ibis#1768]
When using the Postgres client, if a table is added to the database/schema after I create a connection, then when trying to refer to that new table I get a `NoSuchTableError`. If I browse the database via a well-established IDE (pgAdmin or DBeaver), then I see that the table is clearly present. 

There should be a way to refresh (manually or automatically) ibis's cached understanding of what schema and tables exist. 

I am using the following version of ibis on Windows:
```
version: 1.0.0
revisionid: 33201ac9cdbdafde
```

**Comment by scottcode** [comment]
Oops, I just realized a mistake in my code, and when I properly tried `client.table()` on a table that was created after the connection was created, it worked. Looks like the Postgres client does refresh the metadata.

**Comment by scottcode** [comment]
Before I thought I had a problem with newly-created tables (which turned out not a problem), but now I have an issue with a table whose schema changed since the first time I created an ibis table object. Even if I recreate the ibis table object (`ibis_connection.table('table_that_changes')`), it thinks that the schema is still the original one, and it errors out when I try to select new columns. 

So it seems that a convenient method for invalidating and refreshing the cache would still be useful.

**Comment by cpcloud** [comment]
Interesting. We're actually attempting to make this possible when you mutate tables from ibis itself, e.g., `create_table`, using [this code](https://github.com/ibis-project/ibis/blob/8dd12de317bb9deabbb7edd1d77e8c79c4d932a4/ibis/sql/alchemy.py#L892).

**Comment by cpcloud** [comment]
It sounds like there should still be an additional method--`refresh()`--that reloads metadata at the request of the user.

@scottcode Any interest in adding this feature?

**Comment by scottcode** [comment]
@cpcloud I think a `refresh()` method would be good. I'll take a crack at it.

**Comment by scottcode** [comment]
It would also be nice if any schema-related exceptions automatically triggered a refresh

**Comment by cpcloud** [comment]
#3127 should address this with the `reconnect()` method on `Backend`
