### ISSUE TITLE
Add NA handling options to reductions

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#177]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Thursday Apr 09, 2015 at 22:10 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/177_

---

Similar to pandas, but excluding NULL should not be the default. Will need to do something like

```
CASE SUM(expr IS NULL) = 0
  WHEN 0 THEN NULL
  ELSE AGG_F(ifnull(expr, $ZERO))
END
```

**Comment by cpcloud** [comment]
I think most folks coming to impala will expect aggregations to skip `NULL`s. If it becomes so common to do otherwise that it's inconvenient we should add some API for this, but leave it until then.

**Comment by wesm** [comment]
The behavior is database dependent, I think, but leaving the default as `skipna=True` in effect is OK

**Comment by cpcloud** [comment]
Closing until there's a strong need.
