### ISSUE TITLE
DOC: conda create command listed no longer works

### ISSUE THREAD

**Issue by scottcode** [ibis-project/ibis#1774]
The following command in `developer.rst` no longer works for two reasons. One, the YAML file no longer exists. Two, creating a conda environment from YAML needs to be done with `conda env create` instead of `conda create`.

Failing instruction:
`conda create -n ibis36 -c conda-forge --file=ci/requirements-dev.yml python=3.6`

Should now be:
`conda env create -n ibis36 -f ci/requirements-3.6-dev.yml`

**Comment by cpcloud** [comment]
Closed by #1775
