### ISSUE TITLE
Ibis protection from SQL injection

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#178]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Thursday Apr 09, 2015 at 22:20 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/178_

---

User-supplied aliases etc. should likely always be quoted to avoid SQL injection vulnerability

**Comment by cpcloud** [comment]
I think to address this we can port the string-producing backends to use sqlalchemy, which is built with avoid sql injection in mind.
