### ISSUE TITLE
feat: support for DISTINCT in aggregates other than COUNT

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#179]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Friday Apr 10, 2015 at 22:08 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/179_

---

STDDEV, NDV, APPX_MEDIAN, and others support a `STDDEV(DISTINCT foo)`

**Comment by cpcloud** [comment]
There's a concrete use case here with `array_agg` and `string_agg`, but since no one is asking for it I'm going to close this out. We'll happily implement it if someone asks and/or someone puts up a PR!
