### ISSUE TITLE
Address Ibis UDF security issues

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#18]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Wednesday Dec 10, 2014 at 20:55 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/18_

---

In many environments, admin privileges are required to create UDFs or UDAs. Since we'll be effectively opening a backdoor via ibis for the user to run arbitrary Python code, to address security concerns we will have to ensure that this code execution takes place within an environment where the user cannot hurt anything. 

Possible solutions
- Run ibis daemon/workers inside a container
- Run ibis processes under a special user account with limited privileges (just enough to be able to see the data passed from Impala)

**Comment by cpcloud** [comment]
This issue isn't a thing that ibis itself will be able to solve, as one of the primary goals of UDFs/UDAs is to run arbitrary code. Sandboxing and other solutions would likely live outside of ibis.

Closing.
