### ISSUE TITLE
feat: column expressions from a base table should also be valid on top of a limited table

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#180]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Monday Apr 13, 2015 at 18:30 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/180_

---

Consider for example:

`table.limit(100).aggregate(agg_exprs)`

when `agg_exprs` was built from `table`. Currently fails AFAICT. Sort of a pedantic issue but it happened to me

related: #83

**Comment by cpcloud** [comment]
This can be done with `_`:

```
In [18]: import ibis

In [19]: from ibis import _

In [20]: t = ibis.table(dict(a="int", b="string"))

In [21]: t.limit(100).aggregate(sum_a=_.a.sum())
Out[21]:
r0 := UnboundTable: unbound_table_3
  a int64
  b string

r1 := Limit[r0, n=100]

Aggregation[r1]
  metrics:
    sum_a: Sum(r1.a)

In [22]: t.limit(100).group_by(_.b).aggregate(sum_a=_.a.sum())
Out[22]:
r0 := UnboundTable: unbound_table_3
  a int64
  b string

r1 := Limit[r0, n=100]

Aggregation[r1]
  metrics:
    sum_a: Sum(r1.a)
  by:
    b: r1.b
```

Closing.
