### ISSUE TITLE
Ability to pass an existing pymapd connection

### ISSUE THREAD

**Issue by jp-harvey** [ibis-project/ibis#1804]
Currently it's necessary to build a connection object manually when connecting with Ibis. In situations where the user already has an existing pymapd connection it would be useful to be able to reuse the connection object instead of connecting again. Originally mentioned in https://github.com/ibis-project/ibis/pull/1796

**Comment by xmnlab** [comment]
from @cpcloud comment:

> @jp-harvey I think we'd probably want another API like ibis.mapd.from_pymapd(existing_connection). 

@cpcloud what do you think about something more generic? maybe something like `ibis.mapd.reuse_connection` ?

**Comment by jp-harvey** [comment]
@xmnlab yep that would work, or `set_connection` would be another option, since we're setting the `con` property of the object. I like the idea of something more generic since `pymapd` will become `omniscipy` at some point in the not too distant future.

**Comment by cpcloud** [comment]
PRs welcome
