### ISSUE TITLE
Time interval with integer seconds seems to have decimal values of seconds

### ISSUE THREAD

**Issue by amroid** [ibis-project/ibis#1829]
In `ibis/tests/all/test_temporal.py`, `test_temporal_binop` with parameter `timestamp_subtract_timestamp` and Pandas backend gives `expr` that is `TimestampDiff[interval<int32>(unit='s')*]` yet when executed has entries like `-2893 days +10:47:55.650000`.

Run test:
`pytest ibis/tests/all/test_temporal.py::test_temporal_binop -k 'timestamp-subtract-timestamp' -m pandas`

**Comment by l2radamanthys** [comment]
In current version the tests folder has moved to `ibis/tests/expr/test_temporal.py`  and the test was removed or renamed, I need more information to replicate it.

this test does not exist.
`pytest ibis/tests/expr/test_temporal.py::test_temporal_binop -k 'timestamp-subtract-timestamp' -m pandas`

**Comment by datapythonista** [comment]
The test is in `ibis/backends/tests/test_temporal.py`

If you use Linux, you can easily find it with `grep -R test_temporal_binop`

**Comment by cpcloud** [comment]
This is the way that pandas displays timedelta values. The underlying values are integers:

```
(Pdb) result.head()
0          -2619 days +05:41:42
1          -2619 days +05:42:42
2   -2619 days +05:43:42.100000
3   -2619 days +05:44:42.300000
4   -2619 days +05:45:42.600000
Name: timestamp_col, dtype: timedelta64[ns]
(Pdb) result.iloc[2]
Timedelta('-2619 days +05:43:42.100000')
(Pdb) type(result.iloc[2].value)
<class 'int'>
(Pdb) result.iloc[1:2].values
array([-226261038000000000], dtype='timedelta64[ns]')
```
