### ISSUE TITLE
ENH: Change Postgres image to support PL/Python UDFs

### ISSUE THREAD

**Issue by scottcode** [ibis-project/ibis#1853]
One thing that is lacking in the CI suite to make Postgres UDF testing feasible is that the current Postgres image being used doesn't have PL/Python installed. It's using an image that is a much slimmed-down version of Postgres.  

The easiest fix I think is to use the standard full version of Postgres. I'm working on creating a new Dockerfile that achieves that, but I haven't got it working yet and haven't pushed any code on that yet.

**Comment by xmnlab** [comment]
Great! Also it would be good to  keep the support to GIS

**Comment by scottcode** [comment]
@xmnlab I’ll work on keeping postgis in the image.

**Comment by scottcode** [comment]
I created a revised Docker image that supports PL/Python as well as PostGIS (see PR #1871). 

The image I use is [shajekpivotal/postgres-9.5-postgis-2.5](https://cloud.docker.com/u/shajekpivotal/repository/docker/shajekpivotal/postgres-9.5-postgis-2.5), which is based on the [mdillon/postgis](https://hub.docker.com/r/mdillon/postgis/dockerfile) that we used to rely on, but substituting slightly modified base image [shajekpivotal/postgres-9.5-plpython](https://cloud.docker.com/repository/docker/shajekpivotal/postgres-9.5-plpython) in place of `postgres:9.5-alpine`. `shajekpivotal/postgres-9.5-plpython` simply uncomments a compilation flag `--with-python` ([Dockerfile](https://github.com/autoscott/postgres-docker/blob/plpython/9.5/alpine/Dockerfile)). 

I updated the `docker-compose.yml` to point to that new image, and setup the `datamgr.py` to run `CREATE EXTENSION PLPYTHONU` in the test database.

**Comment by scottcode** [comment]
To make the image more maintainable I created a single repo that derives from a single upstream official image. It is ready to migrate to an `ibis-project` owned code repo and DockerHub image. I just need someone to give me access to those accounts or migrate it themselves. 

The current image is [shajekpivotal/ibis-docker-postgres-9.5](https://hub.docker.com/r/shajekpivotal/ibis-docker-postgres-9.5), and the code that it builds from is [scottcode/ibis-docker-postgres](https://github.com/scottcode/ibis-docker-postgres)

**Comment by cpcloud** [comment]
Sweet, appreciate all your efforts here. I will do the migration after your PR is merged.

**Comment by scottcode** [comment]
#1871 included pointing to an updated Postgres image that supports pl/python as well as postgis
