### ISSUE TITLE
Add Ibis as an numfocus affiliated project

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1881]
NumFOCUS Affiliated Projects are:
- focused on open source data science,
- make meaningful use of NumFOCUS-sponsored tools,
- have an active community of contributors (must have more than one active contributor), and
- have a Code of Conduct, either adopted from our own or similar in spirit.
- If your project meets the above criteria and you would like to become a NumFOCUS Affiliated Project, please apply.

Benefits of being an Affiliated Project include:
- listing on the NumFOCUS website
- belong to NumFOCUS internal project developers mailing list
- eligible for NumFOCUS small development grants
- eligible to participate in Google Summer of Code under NumFOCUS umbrella
- eligible to apply for infrastructure support such as web hosting and server space

it seems we don't have the code of conduct yet ... so maybe we could just use the code of conduct from numfocus: https://numfocus.org/code-of-conduct

**Comment by xmnlab** [comment]
What do you think @cpcloud?

**Comment by xmnlab** [comment]
@cpcloud any feedback here? If it is OK for you I can try to apply. for instance, you can find the link to apply here: https://numfocus.org/sponsored-projects/affiliated-projects

**Comment by cpcloud** [comment]
xref: #1145

Please discuss on https://github.com/ibis-project/ibis/discussions/3165
