### ISSUE TITLE
Spark SQL add_months has nonstandard behavior for end-of-month days

### ISSUE THREAD

**Issue by amroid** [ibis-project/ibis#1886]
Special behavior for last day of month: If start_date is the last day of the month or if the resulting month has fewer days than the day component of start_date, then the result is the last day of the resulting month.
-  Other backends do this only if the resulting month has fewer days than the day component of start_date (i.e. March 31 + 1 month = April 30).
- They don't do this if the resulting month has at least as many days as the day component of start_date (i.e. April 30 + 1 month = May 30, but Spark would give May 31).

Example:
`select add_months('2010-04-30', 1)` returns `2010-05-31`
`select add_months('2010-04-29', 1)` returns `2010-05-29`
`select add_months('2010-02-28', -1)` returns `2010-01-31`
`select add_months('2010-02-27', -1)` returns `2010-01-27`

Related/documentation:
https://jira.apache.org/jira/browse/SPARK-8194
https://docs-snaplogic.atlassian.net/wiki/spaces/SD/pages/2458071/Date+Functions+and+Properties+Spark+SQL

**Comment by cpcloud** [comment]
Thanks @amroid. This does appear to stray from many other systems including postgres and bigquery.

**Comment by amroid** [comment]
Also occurs with the interval-arithmetic way of adding dates/times:
`select to_timestamp('2010-04-30') + interval 1 month` returns `2010-05-31 00:00:00`
