### ISSUE TITLE
Ibis for SQL Programmers doc update

### ISSUE THREAD

**Issue by mpeaton** [ibis-project/ibis#1887]
I'm new to Ibis, but it appears that the following patch to the docs may be in order?

--- a/docs/source/sql.rst
+++ b/docs/source/sql.rst
@@ -68,7 +68,7 @@ This generates the expected SQL:

.. ipython:: python

print(ibis.impala.compile(proj))
print(ibis.impala.compiler.to_sql(proj))

**Comment by mpeaton** [comment]
I'm new to Ibis, but it appears that the following patch to the docs may be in order?

--- a/docs/source/sql.rst
+++ b/docs/source/sql.rst
@@ -68,7 +68,7 @@ This generates the expected SQL:

 .. ipython:: python

-   print(ibis.impala.compile(proj))
+   print(ibis.impala.compiler.to_sql(proj))

**Comment by cpcloud** [comment]
PRs welcome. No need to open an issue, just open a PR with the changes, especially for small changes like this.
