### ISSUE TITLE
Create SQLAlchemy-native construct for compiling UDF signatures

### ISSUE THREAD

**Issue by scottcode** [ibis-project/ibis#1890]
This is a follow-on issue related to #1871. 

We should ultimately make a SQLAlchemy construct to represent Postgres UDF signatures and go through its compiler rather than stringifying SQLAlchemy types and formatting them (see implementation of `ibis.sql.postgres.udf.api.func_to_udf`).

Eventually that might actually be a nice upstream contribution as well.

(Suggestion made by @cpcloud)

**Comment by cpcloud** [comment]
This could be useful but needs a champion. PRs welcome.
