### ISSUE TITLE
Can i use Ibis with Arrow table

### ISSUE THREAD

**Issue by rkdixit76** [ibis-project/ibis#1906]
Assuming Arrow tables are columnar and faster for analytical processing, was wondering if we can use Ibis to run on an Arrow table.

**Comment by cpcloud** [comment]
Arrow is in the process of growing the set of operations that can be performed on its arrays, so in theory it might be possible but I'd like to wait until more operations are available before implementing such a backend.

**Comment by rkdixit76** [comment]
Cool. Thanks for responding. Will be interesting to see how Arrow develops.
