### ISSUE TITLE
DOC: Add notes install ibis-framework[mapd] inside google colab

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1914]
Currently inside google colab, after `pip install ibis-framework[mapd], this error shows up when the user tries to import ibis:

```
/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
<ipython-input-2-a73c1a9e8fb0> in <module>()
----> 1 import ibis

7 frames
/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    789                 # Oops, the "best" so far conflicts with a dependency
    790                 dependent_req = required_by[req]
--> 791                 raise VersionConflict(dist, req).with_context(dependent_req)
    792 
    793             # push the new requirements onto the stack

ContextualVersionConflict: (pyarrow 0.14.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('pyarrow<0.14,>=0.10.0'), {'pymapd'})
```

@scottcode reported that if the user restart the kernel it should work.

```
Because pyarrow is imported during the installation process but then pyarrow gets updated later in the process
Causing a version conflict if you don’t restart the kernel
```

maybe pinning `pyarrow>=0.12.0,<0.14` at https://github.com/ibis-project/ibis/blob/master/setup.py#L41 would fix the problem?

**Comment by xmnlab** [comment]
In the installation it shows up the following message:

```
WARNING: The following packages were previously imported in this runtime:
  [pyarrow]
You must restart the runtime in order to use newly installed versions.
```

is this enough for a end-user? or should we try to fix this conflict?

**Comment by scottcode** [comment]
I think the restart is only relevant when trying to install ibis within a Google Colab notebook itself and then use the same environment without restarting. It looks like other libraries have this same problem: [https://github.com/ray-project/ray/issues/5033](https://github.com/ray-project/ray/issues/5033). Colab apparently automatically preloads certain packages (including `pyarrow`). Might be best to leave it to the existing warning and perhaps add our own warning and/or add a note in our documentation.

**Comment by xmnlab** [comment]
the note in ibis documentation sounds a good option.
