### ISSUE TITLE
FEAT: Need to add Ibis support for various timestamp component operations in OmniSci

### ISSUE THREAD

**Issue by niviksha** [ibis-project/ibis#1916]
The Ibis OmniSci backend (and other backends, it appears) dont support a variety of EXTRACT operations on `**TimeStamp**` Expressions.

Specifically, Ibis lists
```

TimestampValue.year() |  
TimestampValue.month() |  
TimestampValue.day() |  
TimestampValue.day_of_week | Namespace expression containing methods for extracting information about the day of the week of a TimestampValue or DateValue expression.
TimestampValue.hour() |  
TimestampValue.minute() |  
TimestampValue.second() |  
TimestampValue.millisecond() |  
TimestampValue.truncate(unit) | Zero out smaller-size units beyond indicated unit.
TimestampValue.time() | Return a Time node for a Timestamp.
TimestampValue.date()
```
as supported operators, which translate typically into `EXTRACT` operations in OmniSci's SQL implementation. However, OmniSci supports a wide variety of these operations - see https://docs.omnisci.com/latest/5_math.html#date-time-functions

Specifically, the following `date_part` types are supported in the `DATE_TRUNC` and `EXTRACT` SQL implementations
```
DATE_TRUNC [YEAR, QUARTER, MONTH, DAY, HOUR, MINUTE, SECOND, MILLENNIUM, CENTURY, DECADE, WEEK, 
            QUARTERDAY]
EXTRACT    [YEAR, QUARTER, MONTH, DAY, HOUR, MINUTE, SECOND, DOW, ISODOW, DOY, EPOCH, QUARTERDAY, WEEK]
```
We should
1) Add any remaining `EXTRACT` operations - particularly `DOW, DOY, WEEK, QUARTER, H/M/S` since they're supported by the OmniSci backend
2) Add the remaining `TRUNCATE` operations as well supproted by OmniSci

**Comment by xmnlab** [comment]
related to https://github.com/ibis-project/ibis/issues/1430

**Comment by cpcloud** [comment]
Feel free to open a PR for this at any time!
