### ISSUE TITLE
How to divide IntervalValue expression with number for impala backend?

### ISSUE THREAD

**Issue by chinthanishanth** [ibis-project/ibis#1927]
consider the following scenario:

`drug_beneficiary = conn.table('analysis_table')`

in the above line of code i am referencing the impala table

`drug_beneficiary_days_diff= drug_beneficiary.mutate(days_diff = drug_beneficiary['index_date'] - drug_beneficiary['bene_birth_dt'])
`

In the above line of code i am subtracting ```index_date``` with ```bene_birth_dt```  columns both are of type timestamps and creating new column `diff_days`

now dividing `diff_days` with static number (eg:365) as show in the below line of code

`drug_beneficiary_age_calc= drug_beneficiary_days_diff.mutate(age = drug_beneficiary_days_diff.days_diff/365).execute()`

i am getting the following error

```
TypeError                                 Traceback (most recent call last)
<ipython-input-115-c9f8dc27e6ca> in <module>
      2                                                        )
      3 # drug_beneficiary_joined.schema()
----> 4 drug_beneficiary_joined = drug_beneficiary_joined.mutate(age = drug_beneficiary_joined.diff_days/365)
      5 #drug_beneficiary_joined.execute()

TypeError: unsupported operand type(s) for /: 'IntervalColumn' and 'int'
```

any help is appreciated...

**Comment by xmnlab** [comment]
did you tried ibis.interval? https://github.com/ibis-project/ibis/blob/master/ibis/tests/all/test_temporal.py#L201

let me know if it helped

**Comment by chinthanishanth** [comment]
i tried as per above link but i still got same error

here how i modified my lines of code

`drug_beneficiary = conn.table('analysis_table')`

`drug_beneficiary_days_diff= drug_beneficiary.mutate(days_diff = drug_beneficiary['index_date'] - drug_beneficiary['bene_birth_dt'])`


`drug_beneficiary_age_calc= drug_beneficiary_days_diff.mutate(age = drug_beneficiary_days_diff.days_diff / ibis.interval(days=14)).execute()`

but still same error

```
TypeError                                 Traceback (most recent call last)
<ipython-input-34-7d8f0a4c6043> in <module>
      2                                                        )
      3 # drug_beneficiary.schema()
----> 4 drug_beneficiary = drug_beneficiary.mutate(age = drug_beneficiary.diff_days/ibis.interval(days=14))
      5 #drug_beneficiary.execute()


TypeError: unsupported operand type(s) for /: 'IntervalColumn' and 'IntervalScalar'
```

**Comment by xmnlab** [comment]
@cpcloud do you have any idea about this?

**Comment by chinthanishanth** [comment]
i solved calculating age from days_diff by casting `intervalColumn` to `int64` which gives seconds of type` int64`, now  `seconds/60(min)/60(hours)/24(1 day)/365(1 year)` gives number of years

modified code as show below

`drug_beneficiary_age_calc= drug_beneficiary_days_diff.mutate(age = drug_beneficiary_days_diff.days_diff.cast('int64')/60/60/24/365).execute()`
