### ISSUE TITLE
Degrees of support for new types (JSON, JSONB, UUID)

### ISSUE THREAD

**Issue by ian-r-rose** [ibis-project/ibis#1944]
There is a large zoo of data types out there, some of which are not supported by ibis. I have been doing some work recently with table schemas that use Postgres UUID, JSON, and JSONB types. Currently, if you try to connect to such tables using ibis it errors out, as these types are not supported (c.f. #1690, #782, #992). This is pretty unfortunate, since columns of these types are fairly common, and it means being unable to use tables including them, even if you don't intend to use those columns.

Long-term, it would be good to support these types, but doing so is a significant undertaking (especially with JSON-based types, as there are a lot of actual operations to think through and design abstractions over).

In the short term, would it be acceptable to include a bit of a band-aid for these types? Basically, I would like to be able to interact with tables including them, and mostly ignore them. Ibis could interpret them as string types, and consenting adults would be able to move forwards knowing that the type-safety would be somewhat wrong for those columns.

**Comment by jreback** [comment]
this would be good to supoort as a good compatibility measure
