### ISSUE TITLE
Define user API for exposing new UDFs to Ibis

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#195]

**Comment by wesm** [comment]
Setting milestone to 0.5. There's some work here to enable pluggable user APIs, e.g. adding new methods to `StringValue` in a cleaner way than the current `ibis/expr/api.py`.

**Comment by wesm** [comment]
More thought needed here. Going to take my time and address in 0.6

**Comment by cpcloud** [comment]
This should be part of a larger roadmap, which should be in a PR for review and discussion.

**Comment by cpcloud** [comment]
xref: #50
