### ISSUE TITLE
DEV: merge-pr script doesn't work with two-factor auth

### ISSUE THREAD

**Issue by toryhaavik** [ibis-project/ibis#1953]
Or at least I couldn't figure it out. We should enhance the script to be able to support that.

**Comment by cpcloud** [comment]
It does, you have to generate an application specific password.

**Comment by toryhaavik** [comment]
Ah okay. you have to generate a Personal Access Token, and grant it access to 'repo', then use that as the password on the CLI. I'm going to leave this open until I document it in the (upcoming) maintenance guide.

**Comment by cpcloud** [comment]
We merge using the button now and the script is gone :)
