### ISSUE TITLE
Developer doc enhancements

### ISSUE THREAD

**Issue by toryhaavik** [ibis-project/ibis#1956]
I'm just keeping a running list of things that will be helpful to add to the developer docs:

- pre-commit hooks (how to install)
- formatting/style "philosophy". ideally we'd like to enforce that the pre-commit hooks are run
- how to write commit messages
- we prefer rebases over over merge commits
- merge/maintainer docs
  - how to merge PRs
  - how to do releases

what else?

**Comment by xmnlab** [comment]
recently I started a draft document that has some tips about how to create a new backend: https://gist.github.com/xmnlab/eb1cd362566ef8d0705519dc1932fe2e

**Comment by toryhaavik** [comment]
@xmnlab that gist is great! I think there are two separate sections here, one is documenting how to maintain the codebase and the other is a how-to guide to implement a backend. #1960 will do the first, and then we should move the parts of your gist that talk about philosophy of how to create a backend (string-generated vs expression-generating, etc) into a new section.
