### ISSUE TITLE
OmniSci backend - bucket operator not working

### ISSUE THREAD

**Issue by niviksha** [ibis-project/ibis#1959]
When i try the very useful-looking [bucket](https://docs.ibis-project.org/notebooks/tutorial/8-More-Analytics-Helpers.html?highlight=histogram#Binning-and-histograms) operator with the MapD backend, 

```
buckets = [0, 5000, 10000, 50000, 100000]
bucketed = t.QUANTITY.bucket(buckets).name('bucket')
bucketed.compile()
```

I get an error

```
UnsupportedOperationError: MapD backend doesn't support <class 'ibis.expr.operations.NullLiteral'> operation!
```

**Comment by xmnlab** [comment]
@niviksha could you provide the version of ibis you are using?
if you are not using from master, could you try to install it from that? I think it is already working on master ...

**Comment by cpcloud** [comment]
Looks like this might be fixed, either way the omnisci backend is no longer in this repo. @xmnlab Can you paste a link to the current omnisci backend?

**Comment by xmnlab** [comment]
sure thing! https://github.com/omnisci/ibis-omniscidb
