### ISSUE TITLE
Add CI steps to check that formatting/linting is correct

### ISSUE THREAD

**Issue by toryhaavik** [ibis-project/ibis#1966]
We have the pre-commit hook, but we should go further and add a step to the CI pipeline that fails if black would try to make formatting changes to a proposed PR.

**Comment by toryhaavik** [comment]
Do you know the exact reason we pin to such a specific version of black in the pre-commit hook? We'll need to change the requirements.txt to match that specific version if we want to implement this.

**Comment by cpcloud** [comment]
Because black was incorrectly adding a trailing comma to `**kwargs` in function signatures, which isn't valid syntax in Python 3.5. It is however valid syntax in 3.5 to add a trailing comma to `**kwargs` at the call site.

**Comment by toryhaavik** [comment]
ah, right, i remember now

**Comment by toryhaavik** [comment]
i think the best place to put this is in linux.yml around here ```- bash: docker-compose run ibis flake8
      displayName: 'Lint'```

I don't quite understand how the `docker-compose run` thing works though
