### ISSUE TITLE
ClickHouse: UnsupportedBackendType: LowCardinality(String)

### ISSUE THREAD

**Issue by sgolod** [ibis-project/ibis#1968]
Latest version of ibis doesn't has a support of LowCardinality type in ClickHouse.

/usr/local/lib/python3.7/dist-packages/ibis/clickhouse/client.py in __init__(self, typename, nullable)
     52         base_typename = m.groups()[0]
     53         if base_typename not in _clickhouse_dtypes:
---> 54             raise com.UnsupportedBackendType(typename)
     55         self.typename = base_typename
     56         self.nullable = nullable

UnsupportedBackendType: LowCardinality(String)

P.S. BTW, clickhouse-driver support this type.

**Comment by bong0** [comment]
This issue persists in 1.4.0 and I use a workaround for now:

```sql
CREATE VIEW table_v　(
  `full_label` String, 
  `value` UInt16,　  
  `ts` DateTime ) AS
SELECT　    toString(full_label) AS full_label,　   value,  ts　FROM table

```

**Comment by jreback** [comment]
happy to take a PR to patch

**Comment by bong0** [comment]
> happy to take a PR to patch

will dig into this if I continue using ibis! So far it was just a quick test for me.

**Comment by cpcloud** [comment]
as @jreback says we would happily accept a PR.
