### ISSUE TITLE
Azure pipeline is flaky

### ISSUE THREAD

**Issue by toryhaavik** [ibis-project/ibis#1980]
The `wait for databases` stage seems to timeout randomly. I have no idea how to get this more stable.

See https://dev.azure.com/ibis-project/ibis/_build/results?buildId=1489&view=logs for an example

**Comment by xmnlab** [comment]
maybe we can start with a log when any service doesn't work

I can open a PR for that.

**Comment by toryhaavik** [comment]
The timeout seems to be waiting for port `21050` (see https://dev.azure.com/ibis-project/ibis/_build/results?buildId=1586&view=logs)

that port is impala, which i don't know much about, so i'm not sure how to debug it

**Comment by cpcloud** [comment]
We are all github actions, all the time now :)
