### ISSUE TITLE
docs: documentation and user experience around the test suite

### ISSUE THREAD

**Issue by ian-r-rose** [ibis-project/ibis#1989]
@xmnlab encouraged me to open this issue around the user experience for contributors working with the test suite. I'd like to open this by saying, testing against the number of backends that ibis supports, with all of the docker orchestration and n^2 complexity is a *really* hard problem, and I'm kind of amazed that it works at all. So I mean this all as constructive feedback.

As a relative newcomer to working with `ibis`, I find working with the test suite to be very difficult, to the point where I suspect it discourages new contributors. Here are a few of the problems I have run into:

* There is some documentation [here](https://docs.ibis-project.org/contributing.html#run-the-test-suite) about how to run the test suite, but it is very brief. I can say that I have never been able to run the full test suite on any of the several workstations I have tried -- there is always some service or other that does not start. I suspect that the number of people who understand all of the available backends well enough to debug problems like that number in the single digits, so this right here is likely enough to stop many people from running the test suite. I have found myself doing a lot of "push to a PR branch and hope".
* The test suite takes a long time! Often if I am working with a single backend, I'd like to be able to run a single backend's tests. It is possible with some work and editing of docker-compose files, makefiles, pytest markers, etc, to run a reduced version, but it is a lot of work, and not clear to new users how to do that.
* The tests themselves are heavily parameterized, and often have short, opaque variable names. This makes them hard to read, and understanding them often involves hopping between many different files. Most of the tests I have tried to write come from copying-and-modifying existing tests, but the fact that I often don't know what they are doing makes that difficult.

Here are a few suggestions that I think might help:
1. Document how to set up a docker-compose setup for a subset of the backends, and load data into just those backends. I don't think this is currently possible without editing the ci files, but maybe I am wrong!
1. Document how to run the test suite targeting a subset of the backends. A good start might be just listing the available markers to run and how to run them.
1. Document which of the test modules require a running a backend service, and which can be run in memory.

Anyways, feel free to tell me whether/how I am mistaken about this, or what kinds of things might be useful to talk about further. Thanks for all the work on this tool!

**Comment by xmnlab** [comment]
thanks @ian-r-rose  for all the details and explanation in your feedback.

just some comments about the workflow I am using here locally:

- I just start the backend servers I am working, example: `docker-compose up omniscidb postgres`
- to load the test data into the backend, for example:
  - `python ci/datamgr.py download`
  - `python ci/datamgr.py omniscidb`
  - `python ci/datamgr.py postgres`
- and to select the backend for tests, for example:
  - `pytest -vv -m "omniscidb or postgresql"`

I will take a time to improve the user experience of docker workflow for tests and documentation.

thanks again for the feedback!

**Comment by ian-r-rose** [comment]
Thanks for the information @xmnlab.
> 
>     * I just start the backend servers I am working, example: `docker-compose up omniscidb postgres`
> 
>     * to load the test data into the backend, for example:
>       
>       * `python ci/datamgr.py download`
>       * `python ci/datamgr.py omniscidb`
>       * `python ci/datamgr.py postgres`
> 
>     * and to select the backend for tests, for example:
>       
>       * `pytest -vv -m "omniscidb or postgresql"`
> 
This workflow is really good information, and I would love to see it in the docs. I *mostly* was able to get here, but it took me a lot of time to work it out, and I spent too much time messing with the Makefile and the various other support scripts (e.g. `load_data`) in the CI system. Having this well described (along with a description of the various available markers) would go a long way to resolve my difficulties.

**Comment by cpcloud** [comment]
@ian-r-rose I know it's been awhile, but would you mind taking a look at https://ibis-project.org/contribute/backend_test_suite/?

I think that page *should* address your concerns here, and if not please comment here!

Thanks again for raising the issue!

**Comment by cpcloud** [comment]
Closing this out. Thanks for the feedback!
