### ISSUE TITLE
`_get_schema_using_query` not implemented on SQLite backend

### ISSUE THREAD

**Issue by costrouc** [ibis-project/ibis#1992]
```
    139         # there is already a limit in the query, we find and remove it
    140         limited_query = 'SELECT * FROM ({}) t0 LIMIT 0'.format(query)
--> 141         schema = self._get_schema_using_query(limited_query)
    142         return ops.SQLQueryResult(query, schema, self).to_expr()
    143 

AttributeError: 'SQLiteClient' object has no attribute '_get_schema_using_query'
```

Does this need to be implented for the SQL backends?

**Comment by xmnlab** [comment]
hey @costrouc yes it was not implemented for sqlite backend.

if you want to implement that you can use omniscidb [1] or impala as references ;)

[1] https://github.com/ibis-project/ibis/blob/master/ibis/omniscidb/client.py

**Comment by roveo** [comment]
I'm interested in implementing these a least for SQLite and Postgres (for my own project that uses Ibis as a dependency).

How would one go about this?

- In SQLite you don't get data types in `cursor.description`, only column names, so you'd have to fetch the names and then execute a second query with column names and `typeof`.
- In psycopg2 you get OIDs, not types, so you have to go query `pg_type` table to figure it out.

Is it OK to introduce an additional query here?

**Comment by cpcloud** [comment]
@roveo Can you describe your use case concretely with a simple example of what you're trying to do and at what point ibis gets in the way?

**Comment by cpcloud** [comment]
This isn't feasible with SQLite, due to its lack of type information.

**Comment by cpcloud** [comment]
This is actually implemented now thanks to @salva in https://github.com/ibis-project/ibis/pull/5242
