### ISSUE TITLE
Question: Upload a conda package with master branch to a development channel periodically (ibis-dev)

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1993]

**Comment by xmnlab** [comment]
I am wondering if would be good to upload a conda package with master branch changes to a development channel periodically (ibis-dev), maybe weekly, or for each PR merged.

There are some people that would be happy if a ibis-dev package would be available.

**Comment by dharhas** [comment]
conda-forge has some guidance on some best practices to do this. 

https://github.com/conda-forge/cfep/blob/master/cfep-05.md

Having a dev release mechanism would go a long way in smoothing our experience using Ibis. It would reduce some of the pressure to release often and help with testing downstream packages with new features that have been added to Ibis.

Case in point, we are getting ready to do some demonstrations of the new Ibis/Holoviews integration we have been building and while that work is still very early it depends on features in Ibis master that are not in the release. It would be great to be able to say something like "this is a new feature, you need to install ibis-dev if you want to try it out now OR you can wait for the next Ibis release".

**Comment by jreback** [comment]
not averse to having a nightly conda package if you would like to help setup a github action (or other mechanism) to do this.

**Comment by datapythonista** [comment]
I created #2411, let's see if someone can work on it tomorrow at the sprint.

@jreback I'm also thinking on working on a release after the entry point system for the backends is merged. Is there anything else you'd like to see before a release?

**Comment by jreback** [comment]
> I created #2411, let's see if someone can work on it tomorrow at the sprint.
> 
> @jreback I'm also thinking on working on a release after the entry point system for the backends is merged. Is there anything else you'd like to see before a release?

no happy to release whenever
