### ISSUE TITLE
First Ibis-dev meeting

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#1995]
That would be great if we could organize a ibis-dev meeting.

I propose for or first meeting October 23rd (Wednesday) at 3 PM EST.

Maybe for the first meeting we can use google hangout and we can discuss about it in our meeting.

If this time doesn't work please propose another time. Also we can try to use some tool to help us to find the best time for this meeting.

Initial agenda: https://hackmd.io/@GvoPVECJQAmNl6JmM2UPMQ/r17k_RyYB

**Comment by toryhaavik** [comment]
sounds great! that time works for me. i think probably quarterly cadence is good.

**Comment by xmnlab** [comment]
link for the meeting time and hangout link: https://arewemeetingyet.com/New%20York/2019-10-23/15:00/Ibis%20dev%20meeting#eyJ1cmwiOiJodHRwczovL2hhbmdvdXRzLmdvb2dsZS5jb20vY2FsbC85Rk9nUVBZcnhCdnQwYnFITk1WUEFFRUU/bm9fcmQifQ==

**Comment by scottcode** [comment]
I should be able to join as well. Thanks for setting this up!

**Comment by icexelloss** [comment]
I try to join but it says I am not allowed to join.

**Comment by xmnlab** [comment]
https://hangouts.google.com/call/_Q9xhtir028v0bqhURjEAEEE?no_rd
