### ISSUE TITLE
Propagate Ibis exceptions conservatively to impala-shell

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#20]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Friday Dec 12, 2014 at 00:33 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/20_

---

For example, import errors should be immediately visible in the Impala shell

**Comment by cpcloud** [comment]
Closing as stale. Please reopen if this is still relevant.
