### ISSUE TITLE
TST: disable impala backend

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#2007]
seems that this is causing numerous CI issues, we should disable this.

**Comment by toryhaavik** [comment]
We should really look into what the issues are. I'd rather not disable the whole test suite if we can avoid it.

**Comment by xmnlab** [comment]
@toryhaavik could you work on this?

**Comment by xmnlab** [comment]
as it is causing troubles .. I think the best thing here would be disable that until we have a PR to fix that.

**Comment by xmnlab** [comment]
one current issue related to disable impala I found is that it is used for the tutorial notebooks:
`Ping the impala host used in the tutorial notebooks`.

if we disable impala .. also we should disable that for now or change the notebooks to use another backend .. 

I will take some time to check the problem related to impala ...

**Comment by xmnlab** [comment]
It seems that the problem is around here:

```
psql -h postgres -U postgres -c "CREATE DATABASE metastore;" 2>/dev/null

/usr/lib/hive/bin/schematool -dbType postgres -initSchema

supervisorctl start hive-metastore
```

the entire impala docker log is here: https://pastebin.com/ei7ZeXZ2

**Comment by xmnlab** [comment]
and this is the postgresql docker log: https://pastebin.com/ev2RY6PX

**Comment by xmnlab** [comment]
https://github.com/ibis-project/ibis/pull/2012 is done for review!
