### ISSUE TITLE
2nd Ibis-dev meeting

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2008]
With a cadence quarterly our next meeting would be January 22nd 2020 a Wednesday.

We can initially define that to the same date time: 3 PM EST.
Close that date we can check if it works for everyone or if we should create a doodle to find a better time.

**Comment by xmnlab** [comment]
calendar available: https://calendar.google.com/calendar?cid=N3RocXYwdmNma2ltNDM2YTgyNG51a2FkMG9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by anmyachev** [comment]
@xmnlab the PR is no longer relevant. Maybe you can share some notes from this meeting here before closing it. Thanks!

**Comment by xmnlab** [comment]
actually it was a initial date proposal ... not sure if anyone attend that because no one comment that here or in the gitter channel ... 

if anyone attended the meeting feel free to add notes here :)
