### ISSUE TITLE
ENH: Allow window functions to not specify preceding/following/order_by

### ISSUE THREAD

**Issue by scottcode** [ibis-project/ibis#2016]
Currently the window function implementation for Postgres automatically adds the unbounded preceding/following language if you don't specify. This causes it to fail if you don't specify an ordering, even if the aggregate function you are using doesn't require an ordering (e.g. `count`). This might be a problem for all `sqlalchemy` based backends; I'm not sure. 

It would be nice to not have to specify an ordering and to leave off the unbounded language. Aside from ease of use, it also has backend execution performance implications. If the backend doesn't have to sort within the partition it should run faster.

**Comment by scottcode** [comment]
Upon testing some different versions of postgres, this may only be a problem for Postgres versions at least as old as 8.3.

**Comment by cpcloud** [comment]
At some point we should think about per-backed minimum versions (the client server split for some makes that a bit more complicated, I suspect we mostly only care about the server version for this issue).

In this case, 8.3 isn't even in the *unsupported* list it's so old (!): 
![image](https://user-images.githubusercontent.com/417981/146426694-78336a21-af83-4c6c-b90d-ad604605e1f7.png)
