### ISSUE TITLE
ENH: `closed=` parameter to control the inclusivity of window bounds

### ISSUE THREAD

**Issue by hjoo** [ibis-project/ibis#2019]
Currently, `preceding` and `following` window bounds in ibis are always inclusive.

Creating a `closed=` parameter to control inclusivity will help users produce window bound behavior they may be more familiar with.

For example, currently `ibis.trailing_window(2)` is the same as `pandas.DataFrame.rolling(3)` because the argument to trailing_window is an inclusive preceding row bound whereas the argument to rolling is a window size that includes the current row.

With a `closed=` parameter, we could leave inclusivity to be decided by the user and `ibis.trailing_window(preceding=3)` , `ibis.trailing_window(preceding=2, closed='left')`, `pandas.DataFrame.rolling(3)` would all result in the same behavior.

**Comment by hjoo** [comment]
Exact API and default behavior may need further discussion.

**Comment by cpcloud** [comment]
This would require someone interested in dealing with the complexities of backend specifics, since most SQL databases do not support explicit control over window bound closed/openness.
