### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2021]
A release workflow discuss shows up at https://github.com/ibis-project/ibis/pull/2015

The current workflow uses https://github.com/ibis-project/ibis/issues/1606

@jreback propose to add that manually.

So changing this workflow we probably should:

- ensure that the previous notes should be included into the releases note probably using the script
- update documentation https://docs.ibis-project.org/contributing.html#releasing (current there is no information)
- maybe would be good to add a github PR template to guide contributors to add the release notes

any comment, suggestion, recommendation is very welcome :)

**Comment by cpcloud** [comment]
xref: #2924
