### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2025]
This is an overview about documentation current state:

1. https://docs.ibis-project.org/

- it is missing some backends

2. https://docs.ibis-project.org/api.html

- it is missing some backends
- some functions don't have the types of parameters
- some functions don't have the type of return
- some functions don't have any description
- some docstring inconsistencies, eg:
    - `str`/`string`
    - `optional`/`default None`
- it is missing geo spatial functions / data types
- just a few functions have examples. examples help a lot the users. Maybe would be good show a link to a tutorial when it corresponds.

3. https://docs.ibis-project.org/extending.html#adding-a-new-backend

There is not text (it just is mentioning TBD).

4. https://docs.ibis-project.org/backends.html

All backends just have a text `TODO`

**Comment by xmnlab** [comment]
@jreback @scottcode could you give some feedback / ideas about these points? also maybe add more points?

**Comment by scottcode** [comment]
**Module Aliases**

One thing that made joining the project hard for me was all the module aliases that get used. It took me forever to figure out and remember what all these refer to, many of which are not intuitive: `rlz`, `ir`, `sch`, `L`, and `com`. I think it would be great to change those aliases (longer yet intuitive is better than short and opaque in my opinion). Or if not change them, provide a code glossary in the docs. 

**Add/improve documentation for new functionality**

I know I haven't added Postgres UDF info to the docs yet, so I'm guilty. I don't know how much of the other great new functionality that others have been adding have made it into the docs yet.

**Comment by cpcloud** [comment]
Any documentation PR will be accepted almost unconditionally! Please submit one!
