### ISSUE TITLE
ENH: Add VIEW functionality to sqlalchemy-based backends

### ISSUE THREAD

**Issue by scottcode** [ibis-project/ibis#2026]
I tried using `client.table(name_of_view)` to treat an existing view like a table in Postgres, but I got a `NoSuchTableError`. It appears that creating new views--or even referring to existing ones--is not supported in `sqlalchemy`-based backends. It is supported in Impala. 

It would be nice to add the ability to refer to as well as create views within `ibis`. Interface ideas:

For using/referring to existing views:
* `client.view(name_of_view)`
* or just make the `client.table(name_of_view)` work with views

For creating a new view:
* `client.create_view(expression)`

**Comment by ian-r-rose** [comment]
I fairly regularly use ibis to connect to existing views with the PostgreSQL backend (both materialized and regular). So at least in some circumstances it works as is with `client.table`.

**Comment by scottcode** [comment]
Ack! I think I know what happened. The view was created after instantiating the client, so its cache of the schema info might have been old. I haven't verified this, just a hunch. Easy refresh/cache invalidation like suggested in #1768 would be helpful in such a case.

**Comment by scottcode** [comment]
Yeah, I was able to `client.table()` on the view using a newly-created client connection. Looks like it was something about ibis cache of the DB state. I'll close this issue. Thanks @ian-r-rose for chiming in.
