### ISSUE TITLE
RLS: 1.3

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#2028]
we should do a release soon, as last was in mid-summer.

anyone interested in being release manager? also an opportunity to update docs on how-to-release.

**Comment by xmnlab** [comment]
I am interested :)

**Comment by xmnlab** [comment]
not sure if it is helpful but maybe it could give us an idea for our own guideline 
https://cwiki.apache.org/confluence/display/ARROW/Release+Management+Guide

is there already an estimate date for the release?

**Comment by jreback** [comment]
we should be able to release any time

if you want to see what is needed
great

i wouldn’t reference the arrow release guidelines they are much different / complicated

**Comment by xmnlab** [comment]
ok sounds good! do you have any other reference you think could be similar that could be similar to ibis?

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/wiki/Release-Checklist

is a bit out of date and ibis doesn’t need to do a lot of this (no need for wheels)

iirc there is already a release checklist

**Comment by jreback** [comment]
better is here: https://github.com/pandas-dev/pandas-release

**Comment by xmnlab** [comment]
Aswesome. Thanks I will review that

**Comment by xmnlab** [comment]
does make sense for ibis to have also a repo for release like pandas?

**Comment by xmnlab** [comment]
maybe we can use rever (https://regro.github.io/rever-docs/) it seems it is a very nice tool for  software release

**Comment by jreback** [comment]
before trying to reinvent the wheel

look at how the previous releases were done; i am sure there are docs / wiki

i is has been released many times and @cpcloud likely wrote it down

**Comment by xmnlab** [comment]
mm you're right ... there is a wiki about that https://github.com/ibis-project/ibis/wiki/Releasing-Ibis

**Comment by xmnlab** [comment]
maybe we can define a date for the release (Nov, 21st, sounds good?) and we can try to fix #2027 and maybe finish some PR that depends on this fix.

how does it sound?

**Comment by scottcode** [comment]
Good call on not re-inventing the wheel. 

At the least we need to fix #2027. Anything else would be icing on the cake.

**Comment by xmnlab** [comment]
would be good to add a deprecation warning when it is running on python 3.5? (https://github.com/ibis-project/ibis/issues/1911)

**Comment by jreback** [comment]
it would be fine also to remove 3.5 for this release

most other packages have dropped it already or next release will

**Comment by xmnlab** [comment]
Sounds good. I can work on that.

**Comment by xmnlab** [comment]
maybe some PRs for release 1.3

#2037 
#2034 
#2024
#1964

**Comment by scottcode** [comment]
@xmnlab I just rebased and re-pushed #2024

**Comment by xmnlab** [comment]
@jreback maybe would be good to plan a new release for next week. what do you think ?

**Comment by ian-r-rose** [comment]
A release would be very appreciated!

**Comment by jreback** [comment]
ok this is what I think we need for the release.

- 3.8 support: https://github.com/ibis-project/ibis/issues/2036

@xmnlab you are volunteering as release manager? ok then

I think there are some instructions about how to release somewhere. when we are ready you should follow them (and update as you go if anything is unclear). It might be desirable to put the release scripts in something like this: https://github.com/pandas-dev/pandas-release (though ibis is relatively simple so may be overkill).

**Comment by xmnlab** [comment]
@jreback that sounds good. I will work on issue #2036 :) thanks!

**Comment by xmnlab** [comment]
hey everyone. another question for the next release. currently we have 4 backends as experimental: OmniSciDB, MySQL, Spark and Pandas. 

what is the criteria to move from experimental to stable?

**Comment by jreback** [comment]
ok to move pandas to stable
mysql not sure
omnisci ? your call
spark - @icexelloss

**Comment by xmnlab** [comment]
@jreback thanks for the answer. 
IMHO omnisci is stable at this point.

**Comment by xmnlab** [comment]
@icexelloss is spark already stable?

**Comment by jreback** [comment]
@xmnlab I think ok to start the release process. Please follow the instructions; if any changes pls add to the documentation later.

**Comment by xmnlab** [comment]
sounds great! I will work on that today! thanks @jreback !

**Comment by icexelloss** [comment]
Spark backend is still new and I prefer to keep it experimental.

**Comment by icexelloss** [comment]
I actually prefer not to move pandas to stable either, as there are some changes I am thinking about that might or might not break backward compatibility.

**Comment by xmnlab** [comment]
thanks for the information @icexelloss !

**Comment by xmnlab** [comment]
@jreback currently, according to the releasing documentation, we should use `dev/genrelease.py` and it will create create a release note for every PR merged. is it OK to mix that with the current release notes? if yes, should I add all release notes (bug, supp, feat)?

**Comment by jreback** [comment]
you can try that but will have to filter to avoid duplicated ones

**Comment by xmnlab** [comment]
@jreback  I already created the tag. but it seems I don't have rights to upload to pypi

```
HTTPError: 403 Client Error: The user 'xmnlab' isn't allowed to upload to project 'ibis-framework'.
```

could you give permission to that?

**Comment by jreback** [comment]
@xmnlab you need a pypi login (use the same username). once you have that ping me and will add you.

**Comment by xmnlab** [comment]
I already have one, the same name as on github: xmnlab, thanks!

**Comment by jreback** [comment]
ok, update PyPi; you should be able to upload now!

**Comment by xmnlab** [comment]
great! thanks! I will work on that.

**Comment by xmnlab** [comment]
done!

**Comment by jreback** [comment]
start with an email to the mailing list

pls post a draft here

**Comment by xmnlab** [comment]
sounds good! I will work on that between today and tomorrow and I will post it here to be reviewed.

what mailing list do you have in mind?

**Comment by xmnlab** [comment]
```
We have released @IbisData 1.3.0 with 104 new contributions from 16 contributors. Read more about what's new at https://docs.ibis-project.org/release.html
```

PS: 
- I got the data from `git shortlog 1.2.0..1.3.0`
- I counted the entries on the release webpage and I found 102. 
  - it doesn't have `Add release notes for release 1.3.0 (#2100)` (expected)
  - it seems it is missing the release note for the PR #1964 (lost in #2100).

**Comment by xmnlab** [comment]
@jreback any feedback?

**Comment by jreback** [comment]
look on pydata@googlegroups.com

for ANN subjects eg pandas 1.0.0

we can do something really simple

**Comment by xmnlab** [comment]
how about?

Hi all,

I'm pleased to announce that Ibis 1.3.0 is now available, after 8 months of development.

Highlights include

Renaming "mapd" backend to "omniscidb"
Improvement of documentation, added new backends and geospatial methods to the documenation
Improvement of geospatial support
Addition of PySpark backend
Addition of JSON, JSONB and UUID data types
Support for Python 3.5 dropped.
Initial support for Python 3.8 added.


For more details, check out the release page https://docs.ibis-project.org/release.html 

The release can be installed from PyPI

    python -m pip install --upgrade ibis-framework==1.3.0

Or from conda-forge

    conda install ibis-framework=1.3.0 -c conda-forge

**Comment by jreback** [comment]
@xmnlab yep that looks good (just use bullet points for the highlites)

fire away

**Comment by xmnlab** [comment]
thanks! done!
