### ISSUE TITLE
Unpin semantic_version once sphinx-releases fixed

### ISSUE THREAD

**Issue by scottcode** [ibis-project/ibis#2033]
A change in `semantic_version` caused a problem in `sphinx-releases`, which we depend on. The issue in `sphinx-releases` is https://github.com/bitprophet/releases/issues/84

Ibis ran up against this problem as documented in #2027. 

Once the underlying issue in `sphinx-releases` gets fixed, we should remove the pin that was put in `ci/requirements-docs.yml` in PR #2030.

**Comment by cpcloud** [comment]
This has been fixed upstream and in ibis.
