### ISSUE TITLE
Revisit input types for rolling window UDFs in pandas backend

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis#2045]
Currently, rolling window UDFs in pandas backend takes numpy array as input,
Per https://github.com/ibis-project/ibis/pull/2035/files#r349403578, we want to revisit the choice between numpy array and pd.Series.

numpy array gives better performance (microbenchmark shows about 5-6x speed up with a rolling mean UDF), but it's not type preserving.

**Comment by cpcloud** [comment]
Sounds great!
