### ISSUE TITLE
DISCUSS: Top level vectorized python UDF api

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis#2048]
I'd like to introduce a top level vectorized python UDF api. Currently the UDF api is defined under each backends, e.g., ibis.pandas.udf, ibis.spark.udf. As a result, ibis exprs that contains UDFs can only be executed with a single backend, i.e., an ibis exprs that contains ibis.pandas.udf can only be executed with the pandas backend.

The goal of introducing a top level python UDF api is that now ibis exprs that contains udf can be executed across backend, e.g., from pandas to spark (for large data).

The challenge here is that not all backends agrees on the same UDF mechanism , i.e., an UDF that works for pandas backend doesn't not necessarily work for bigquery backend. However, I believe a "vectorized" UDF interface is common and make sense to be defined outside under the specific backend namespace.

Vectorized UDFs are user defined python functions that operates on vectorized data structure. 

- The UDF is written in Python

- The UDF operators on vectorized data structure, e.g., numpy.array, pandas.Series, pandas.DataFrame

The proposed namespace for vectorized UDF is:
`ibis.udf.vectorized`

Currently, Pandas and Spark both support vectorized UDFs of these form. Other backends, e.g., database systems are unlikely to support these now so vectorized UDFs will just be unsupported in those backends.

**Comment by icexelloss** [comment]
This is a draft PR to lift ibis.pandas.udf to top level:
https://github.com/ibis-project/ibis/pull/2047

**Comment by anmyachev** [comment]
Next issues were added: #2058 #2059, so the issue can be closed now I suppose
