### ISSUE TITLE
DateTruncate does not support starting day of the week

### ISSUE THREAD

**Issue by qi-liao** [ibis-project/ibis#2054]
Impala timestamp truncation supports day, week as well as starting day of the week as the unit argument. (https://docs.cloudera.com/documentation/enterprise/latest/topics/impala_datetime_functions.html#datetime_functions__trunc)

WW, W: Same day of the week as the first day of the month.
DDD, DD, J: Day.
DAY, DY, D: Starting day of the week. (Not necessarily the current day.)

In our use case, starting day of the week is what's needed, however, ibis does not seem to support such option.

From 
https://github.com/ibis-project/ibis/blob/259a2b1fb1d95905b2ef0fe333bc26c6cfa7b0eb/ibis/expr/operations.py#L2475
it looks like ibis is treating 'D', 'DAY' and 'J' all as 'D', which later gets turned into unit 'J' when compiled to Impala SQL https://github.com/ibis-project/ibis/blob/259a2b1fb1d95905b2ef0fe333bc26c6cfa7b0eb/ibis/impala/compiler.py#L865

**Comment by cpcloud** [comment]
PRs welcome, but not high priority for any current maintainers.
