### ISSUE TITLE
CI: Fix currently issues after new pandas release

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2063]
Currently CI is falling, according to the errors message it seems it was caused by the new pandas release.

**Comment by xmnlab** [comment]
Also after the changes made by https://github.com/ibis-project/ibis/pull/2061
the tests is raising 2 errors:

```
FAILED ibis/pandas/tests/test_udf.py::test_udaf_groupby - KeyError: 'rhs'
FAILED ibis/pandas/tests/test_udf.py::test_udaf_window_nan - AssertionError: ...
```

I was debugging the first one ... and for some reason `meta_kwargs` doesn't have the key `rhs` used by the udf `my_corr` https://github.com/ibis-project/ibis/blob/master/ibis/pandas/udf.py#L94

@jreback 

any idea how to fix that issue?

or should we just skip this 2 tests for now to fix CI?

**Comment by anmyachev** [comment]
Maybe we should skip these tests for now, add issues for them and mark as `Blocker` for next release? So we can continue working on other backends ...

**Comment by xmnlab** [comment]
@anmyachev that makes sense to me

**Comment by icexelloss** [comment]
I am taking a look at this

**Comment by xmnlab** [comment]
Thanks @icexelloss !

**Comment by xmnlab** [comment]
it seems now CI is failing on windows for postgresql tests ...

**Comment by jreback** [comment]
any idea whats goin on here @icexelloss @xmnlab 

need to have a green CI before merging things.

**Comment by anmyachev** [comment]
@jreback all the last PRs were green before merging to the master. But they fall on the master. This is because testing on PR and on the master are not equivalent due to this line: `condition: eq(variables['System.PullRequest.IsFork'], 'False')` which is in `./ci/azure/linux.yml` - this is `Setup BigQuery credentials`  step

**Comment by jreback** [comment]
happy to take a PR to temporarily xfail what needs on the failing builds (and open an issue for this).. we generally won't merge on non-green.
