### ISSUE TITLE
Failing UDF tests

### ISSUE THREAD

**Issue by jrbourbeau** [ibis-project/ibis#2065]
In #2061 we marked two tests with `xfails`, `ibis/pandas/tests/test_udf.py::test_udaf_groupby` and `ibis/pandas/tests/test_udf.py::test_udaf_window_nan`, which started failing after the recent Pandas 1.0 release. We should go back to determine why those tests are failing and fix them

**Comment by icexelloss** [comment]
This is because change of behavior in Pandas 1.0.0:
https://github.com/pandas-dev/pandas/issues/31719

**Comment by icexelloss** [comment]
Also related:
https://github.com/pandas-dev/pandas/issues/31754

**Comment by icexelloss** [comment]
I think the root cause of these are identified in #2074 . We should wait for the upstream fix. Let's close this?

**Comment by jreback** [comment]
no you don’t close an upstream issue when it’s strict=False xfailed as otherwise it would be fixed and no one sees it or it’s not fixed

either way need a resolution at some point

**Comment by icexelloss** [comment]
Got it. I will keep this open until those xfail are removed.

**Comment by cpcloud** [comment]
These appear to be running and were fixed a long time ago.
