### ISSUE TITLE
CI: pyspark 2.* doesn't work on Python 3.8 

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2091]
The current version of pyspark (2.*) doesn't work on Python 3.8 (https://github.com/apache/spark/pull/26194#issuecomment-566592265).

The next version of pyspark (3.0) will support Python 3.8

**Comment by icexelloss** [comment]
Thanks for looking into this. Anything we should do now? (Other than stating the fact in the doc?)

**Comment by xmnlab** [comment]
sorry for the delay @icexelloss 
I think for now we just need to write something about that in the docs.
