### ISSUE TITLE
Remove work from destructors

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#21]
<a href="http://github.mtv.cloudera.com/bittorf"><img src="https://gravatar.com/avatar/ede422bd4925e3d0a37a07cfa251531c?d=https%3A%2F%2Fidenticons.github.com%2F1543843a4723ed2ab08e18053ae6dc5b.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bittorf](http://github.mtv.cloudera.com/bittorf)**
_Thursday Dec 18, 2014 at 00:26 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/21_

---

We should avoid doing work in C++ class destructors. We should have trivial destructors (that do nothing) and instead have a Close(), Free(), Delete() method as appropriate. 

The issue with destructors is that there is no way to handle errors if destructors fail (it will crash Impala); also exceptions caused in destructors can cause an immediate termination (if another exception is already in flight).

**Comment by cpcloud** [comment]
@wesm This looks unrelated to anything in current ibis. Please reopen if this is still relevant.
