### ISSUE TITLE
Wrong SQL is generated for join

### ISSUE THREAD

**Issue by ienkovich** [ibis-project/ibis#2103]
Hi,

I noticed wrong code generated for join when used OmniSci backend. I reduced my test to the following:

<pre>
con = ibis.omniscidb.connect(
   host='localhost', port=6001, user='admin', password='HyperInteractive')

table = ibis.table([('id_1', 'int64'), ('val_1', 'date'),
                    ('dummy', 'date')], 'ibis_bug')

table = table.mutate(table['val_1'].name(
    'val_1_new'))
table = table[table].drop(['dummy'])

a = table.groupby([table['id_1'].name('id_2')]).aggregate()

join = table.left_join(
    a, [table['id_1'] == a['id_2']])
b = join.materialize()

print(b.compile())
</pre>

The resulting SQL is:

<pre>
WITH t0 AS (
  SELECT *, "val_1" AS val_1_new
  FROM ibis_bug
),
t1 AS (
  SELECT "id_1", "val_1", "val_1_new"
  FROM t0
)
SELECT *
FROM t1
LEFT JOIN (
  SELECT "id_1" AS id_2
  FROM t1
  GROUP BY id_2
) t2
ON t0."id_1" = t2."id_2"
</pre>

Here we see t0 is incorrectly referenced in join condition instead of t1.

I used master branch for my tests.

**Comment by xmnlab** [comment]
@ienkovich I think it is not incorrect because the result represent well the expression you created. the naming maybe is not what you expected because maybe it needed to resolve the `a` first than `table`.

I don't have the exact answer right now for that ... but as I could check the result, it represents the expression you created.

```
================================================================================
table:
SELECT "id_1", "val_1", "val_1_new"
FROM (
  SELECT *, "val_1" AS val_1_new
  FROM ibis_bug
) t0
================================================================================
================================================================================
a:
SELECT "id_1" AS id_2
FROM (
  SELECT "id_1", "val_1", "val_1_new"
  FROM (
    SELECT *, "val_1" AS val_1_new
    FROM ibis_bug
  ) t1
) t0
GROUP BY id_2
================================================================================
WITH t0 AS (
  SELECT *, "val_1" AS val_1_new
  FROM ibis_bug
),
t1 AS (
  SELECT "id_1", "val_1", "val_1_new"
  FROM t0
)
SELECT *
FROM t1
  LEFT JOIN (
    SELECT "id_1" AS id_2
    FROM t1
    GROUP BY id_2
  ) t2
    ON t0."id_1" = t2."id_2"
```

let me know if I am missing anything pls

**Comment by ienkovich** [comment]
The problem is that this query fails to pass parsing by Calcite because of join condition. Outer select is done for t1 and t2 and therefore I expect join condition to be 'ON t1."id_1" = t2."id_2"', not 'ON t0."id_1" = t2."id_2"'. And Calcite seems to expect the same, query executes OK if I fix this condition manually.

**Comment by cpcloud** [comment]
Redirect to https://github.com/omnisci/ibis-omniscidb if this is still a problem
