### ISSUE TITLE
Update Release Documentation

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2118]
Previously the release note was generated just using `dev/genrelease.py`
The release v1.3 mixed the result of `dev/genrelease.py` and some manual notes into `release.rst`

`dev/genrelease.py` generate notes for FEAT, SUPP and BUG PRs automatically using as input information like PR's title.

Continuing using the approach of adding notes manually that is important to the end user, would we need to run `dev/genrelease.py` in next release?
 
Ref.
https://github.com/ibis-project/ibis/wiki/Releasing-Ibis#prepare-the-release

**Comment by xmnlab** [comment]
@jreback any thoughts about this?

**Comment by cpcloud** [comment]
We'll be switching to near full automation for releases, with the goal of an entirely click-button (or CLI if that's your thing) release done using GitHub actions.

Release notes will be generated from commit messages, capturing only features, performance improvements, fixes and breaking changes that don't fall into the previous categories.
