### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u011f' in position 75: ordinal not in range(256)

### ISSUE THREAD

**Issue by burakongun** [ibis-project/ibis#2120]
I want to export pandas data-frame as an Impala table but Turkish characters in data are causing an encoding problem. 

```
import ibis
import pandas

hdfs = ibis.hdfs_connect(host="nn-host", port=50070)
client = ibis.impala.connect(host="impala-daemon1", port=21050, hdfs_client=hdfs)


db = client.database("default")

data = pandas.DataFrame({"id" : [1, 2, 3],
                         "name": ["foo", "bar", "ğ"],
                         "col1": ["hello", "world", "ş"],
                         "dt": ["2010-08-01", "2012-08-03", "2018-12-01"]})


db.create_table("test_ibis", data)
db.test_ibis.execute()
```

I tried changing **encode('latin-1')** to **encode('utf-8')** in **/anaconda3/envs/jupyter/lib/python3.7/http/client.py** but the python kernel on Jupyter could not start. 

Appreciate any help.

**Error trace:**

---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-5-4014405c030d> in <module>
      1 #create table from pandas df
      2 
----> 3 db.create_table("test_ibis_unicode", data)
      4 db.test_ibis_unicode.execute()

/anaconda3/envs/jupyter/lib/python3.7/site-packages/ibis/impala/client.py in create_table(self, table_name, obj, **kwargs)
     39         """
     40         return self.client.create_table(table_name, obj=obj,
---> 41                                         database=self.name, **kwargs)
     42 
     43     def list_udfs(self, like=None):

/anaconda3/envs/jupyter/lib/python3.7/site-packages/ibis/impala/client.py in create_table(self, table_name, obj, schema, database, external, force, format, location, partition, like_parquet)
   1105             if isinstance(obj, pd.DataFrame):
   1106                 from ibis.impala.pandas_interop import write_temp_dataframe
-> 1107                 writer, to_insert = write_temp_dataframe(self, obj)
   1108             else:
   1109                 to_insert = obj

/anaconda3/envs/jupyter/lib/python3.7/site-packages/ibis/impala/pandas_interop.py in write_temp_dataframe(client, df)
    115 def write_temp_dataframe(client, df):
    116     writer = DataFrameWriter(client, df)
--> 117     path = writer.write_temp_csv()
    118     return writer, writer.delimited_table(path)

/anaconda3/envs/jupyter/lib/python3.7/site-packages/ibis/impala/pandas_interop.py in write_temp_csv(self)
     48         hdfs_path = pjoin(temp_hdfs_dir, '0.csv')
     49 
---> 50         self.write_csv(hdfs_path)
     51 
     52         return temp_hdfs_dir

/anaconda3/envs/jupyter/lib/python3.7/site-packages/ibis/impala/pandas_interop.py in write_csv(self, path)
     73                 util.log('Writing CSV to: {0}'.format(path))
     74 
---> 75             self.hdfs.put(path, f)
     76         finally:
     77             f.close()

/anaconda3/envs/jupyter/lib/python3.7/site-packages/ibis/filesystems.py in put(self, hdfs_path, resource, overwrite, verbose, **kwargs)
    318             hdfs_path = self.client.resolve(hdfs_path)
    319             self.client.write(hdfs_path, data=resource, overwrite=overwrite,
--> 320                               **kwargs)
    321             return hdfs_path
    322 

/anaconda3/envs/jupyter/lib/python3.7/site-packages/hdfs/client.py in write(self, hdfs_path, data, overwrite, permission, blocksize, replication, buffersize, append, encoding)
    475       return AsyncWriter(consumer)
    476     else:
--> 477       consumer(data)
    478 
    479   def upload(self, hdfs_path, local_path, n_threads=1, temp_dir=None,

/anaconda3/envs/jupyter/lib/python3.7/site-packages/hdfs/client.py in consumer(_data)
    467         method='POST' if append else 'PUT',
    468         url=loc,
--> 469         data=(c.encode(encoding) for c in _data) if encoding else _data,
    470       )
    471       if not res:

/anaconda3/envs/jupyter/lib/python3.7/site-packages/hdfs/client.py in _request(self, method, url, **kwargs)
    212       timeout=self._timeout,
    213       headers={'content-type': 'application/octet-stream'}, # For HttpFS.
--> 214       **kwargs
    215     )
    216 

/anaconda3/envs/jupyter/lib/python3.7/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    531         }
    532         send_kwargs.update(settings)
--> 533         resp = self.send(prep, **send_kwargs)
    534 
    535         return resp

/anaconda3/envs/jupyter/lib/python3.7/site-packages/requests/sessions.py in send(self, request, **kwargs)
    644 
    645         # Send the request
--> 646         r = adapter.send(request, **kwargs)
    647 
    648         # Total elapsed time of the request (approximately)

/anaconda3/envs/jupyter/lib/python3.7/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    447                     decode_content=False,
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )
    451 

/anaconda3/envs/jupyter/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    598                                                   timeout=timeout_obj,
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 
    602             # If we're going to release the connection in ``finally:``, then

/anaconda3/envs/jupyter/lib/python3.7/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    352             conn.request_chunked(method, url, **httplib_request_kw)
    353         else:
--> 354             conn.request(method, url, **httplib_request_kw)
    355 
    356         # Reset the timeout for the recv() on the socket

/anaconda3/envs/jupyter/lib/python3.7/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1250                 encode_chunked=False):
   1251         """Send a complete request to the server."""
-> 1252         self._send_request(method, url, body, headers, encode_chunked)
   1253 
   1254     def _send_request(self, method, url, body, headers, encode_chunked):

/anaconda3/envs/jupyter/lib/python3.7/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1296             # default charset of iso-8859-1.
   1297             body = _encode(body, 'body')
-> 1298         self.endheaders(body, encode_chunked=encode_chunked)
   1299 
   1300     def getresponse(self):

/anaconda3/envs/jupyter/lib/python3.7/http/client.py in endheaders(self, message_body, encode_chunked)
   1245         else:
   1246             raise CannotSendHeader()
-> 1247         self._send_output(message_body, encode_chunked=encode_chunked)
   1248 
   1249     def request(self, method, url, body=None, headers={}, *,

/anaconda3/envs/jupyter/lib/python3.7/http/client.py in _send_output(self, message_body, encode_chunked)
   1053                     chunks = (message_body,)
   1054 
-> 1055             for chunk in chunks:
   1056                 if not chunk:
   1057                     if self.debuglevel > 0:

/anaconda3/envs/jupyter/lib/python3.7/http/client.py in _read_readable(self, readable)
   1012                 break
   1013             if encode:
-> 1014                 datablock = datablock.encode("iso-8859-1")
   1015             yield datablock
   1016 

**UnicodeEncodeError: 'latin-1' codec can't encode character '\u011f' in position 75: ordinal not in range(256)**

**Comment by xmnlab** [comment]
@burakongun what is the version of hdfs you are using? pls check if this issue is related to https://github.com/mtth/hdfs/issues/127 
thanks!

**Comment by burakongun** [comment]
> @burakongun what is the version of hdfs you are using? pls check if this issue is related to [mtth/hdfs#127](https://github.com/mtth/hdfs/issues/127)
> thanks!

Hadoop version is 2.6.0-cdh5.14.2
I don't think it's related to that issue.

Is there any way to change latin-1 encoding to utf-8 when making requests?

**Comment by burakongun** [comment]
I worked around it. 

```
/anaconda3/envs/jupyter/lib/python3.7/site-packages/hdfs/client.py in consumer(_data)
467 method='POST' if append else 'PUT',
468 url=loc,
--> 469 data=(c.encode(encoding) for c in _data) if encoding else _data,
470 )
471 if not res:
```

I changed line 469 to;
`data = (c.encode("utf-8") for c in _data)`

You can also add `**kwargs` to all methods through **self.hdfs.put** and add encoding argument as
`db.create_table("test_ibis", data, encoding="utf-8")`;
