### ISSUE TITLE
TopK filter improvement

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2135]
**Context**

As reported at #2130 #2131 #2132 #2133 it seems TopK filter should be improved.

#2154 Used left-semi-join as inner join to workaround the problem for omniscidb.
#512 proposes that is important to improve TopK filter

#512 is still valid?

**Comment by cpcloud** [comment]
PRs welcome. This problem isn't trivial to solve (e.g., using a left semi join).
