### ISSUE TITLE
feat: add support for trigonometric functions (sin, cos, tan)

### ISSUE THREAD

**Issue by deepkset** [ibis-project/ibis#2141]
Trigonometric Functions / Unary Operations like sin,cos,tan are missing from variable **_operation_registery** in file **_ibis\impala\compiler.py_**. 

_operation_registry = {
    # Unary operations
    ops.NotNull: _not_null,
    ...
    **ops.Sin: unary('sin'),
    ops.Cos: unary('cos'),
    ops.Tan: unary('tan'),**
    # Unary aggregates
    ops.CMSMedian: _reduction('appx_median'),
    ...
}

Kindly add these Trigonometric Functions  / Unary Operations like sin,cos,tan, as **highlighted** in above code snippet, in the next build.

**Comment by jreback** [comment]
@deepkset ibis is all volunteer

if you want these then best way is to propose a pull request.

**Comment by cpcloud** [comment]
PRs welcome for this!
