### ISSUE TITLE
Conda installing an old version if pandas is found

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2144]
Running `conda install -c conda-forge ibis-framework` seems to be installing (in Linux) Ibis 0.14, not the latest. This only happens when pandas is already installed in the environment.

CC: @xmnlab

**Comment by xmnlab** [comment]
@datapythonista thank for catching that up.
just to check, what is the version of the Python of your environment?

**Comment by datapythonista** [comment]
I'm using Miniconda, with Python 3.7.5.

**Comment by scopatz** [comment]
Does this happen when you create a new environment? Or only when you try to add to an existing one? A `conda update --all` might help

**Comment by datapythonista** [comment]
Something weird is going on. If install `ibis-framework` in a clean environment, it installs the latest version without problems. But if `pandas` is already installed, then version 0.13 or 0.14 are installed (depending if pandas is from `defaults` or `conda-forge`). If then I try to force version 1.3 to be installed, I get this error:
```
(ibis_test) [mgarcia@xps ~]$ conda install -c conda-forge ibis-framework=1.3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                                        

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

I see that the latest Ibis should be compatible with `pandas >= 0.25` (from [meta.yaml](https://github.com/conda-forge/ibis-framework-feedstock/blob/master/recipe/meta.yaml#L34)).

Not really sure what's going on, tried with pandas 0.25.3, 1.0.2 and 1.0.3.

**Comment by xmnlab** [comment]
I think we should pin pandas to >=1.0 into ibis-framework
also not sure if pandas <1.0 will work 100% with ibis as we worked in some issues when pandas 1.0 was released

**Comment by scopatz** [comment]
What is going on is that your current environment & the new updated needed by ibis-framework have incompatible pins somewhere in the stack. Conda doesn't know which ones are more important, so it tries to tell you what the conflicts are and then dies. You can try mamba, but usually just creating a new environment works

**Comment by datapythonista** [comment]
I agree, but more than a problem in my environment, seems to be a problem with any environment that has pandas. In a clean environment where I only install pandas (any version), conda will install an old version of Ibis. At least that's the behavior I've been experiencing in all my tests.

**Comment by scopatz** [comment]
Also, have you tried `conda update` rather than conda install in these situations?

**Comment by datapythonista** [comment]
I'm not really concerned about my own environment. I think the problem is that anyone installing Ibis in a conda environment with pandas (most people installing Ibis I guess?), will get an old version.

May be someone can try to reproduce this, to make sure there is nothing in my computer (I don't think it should). And I guess the solution is updating the version of an Ibis dependency in the next release. I guess that's what is causing this conflict with the newer versions of Ibis.
