### ISSUE TITLE
Interactive mode doesn't work in Jupyter

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2155]
Running the next code in the terminal works as expected, `.count()` returns the number of rows as an `int`, since the option `interactive` is set to `True`:
```python
>>> import ibis
>>> print(ibis.__version__)
1.3.0+24.gd00a112.dirty
>>> ibis.options.interactive = True
>>> conn = ibis.sqlite.connect('geography.db')
>>> conn.table('countries').count()
252
```
But running the same exact code in a notebook returns the expression visualization instead:

![ibis_interactive_bug](https://user-images.githubusercontent.com/10058240/77928929-f7720500-72a0-11ea-9ffb-080eb810c10a.png)

**Comment by datapythonista** [comment]
@xmnlab do you mind having a quick look and let me know if this is indeed a bug, or am I missing something? I'll have a look if it's a bug. Thanks!

**Comment by xmnlab** [comment]
@datapythonista it looks a bug. I tried here and I saw the same behavior.
