### ISSUE TITLE
feat: support complex Arrow dtypes

### ISSUE THREAD

**Issue by emilyreff7** [ibis-project/ibis#2158]
Ibis does not currently support conversion from complex Arrow dtypes, such as Date32 and Date64.

**Comment by cpcloud** [comment]
Can you elaborate a bit on the use case?

**Comment by emilyreff7** [comment]
I believe I ran into this when trying to convert from Arrow to Ibis type via Ibis' ``dt.dtype`` dispatcher. For example, we have [this rule](https://github.com/ibis-project/ibis/blob/a1262410310bb4d638a73e1cdfbe93c2b4089905/ibis/backends/parquet/__init__.py#L38), but if we have an Arrow Date type, there is no corresponding ibis rule for that.

**Comment by cpcloud** [comment]
Ah, I see. I wonder if @kszucs is addressing some of this in his datafusion backend PR (#2918).

**Comment by cpcloud** [comment]
@emilyreff7 Can you talk a little about what you were using this for?

**Comment by emilyreff7** [comment]
For example if I have a datasource for which I have the arrow schema, and would like to map that to its corresponding ibis schema - this was one of the arrow types I ran into that did not have an ibis `dtype` rule registered for it.

**Comment by cpcloud** [comment]
Happy to accept a PR here!

Is this a thing you're blocked by? Happy to reprioritize it if so.

**Comment by emilyreff7** [comment]
Not blocked, not super high priority, code would just be cleaner as a result - maybe a good starter issue? Or I can tackle if I ever get around to it :D

**Comment by cpcloud** [comment]
Sounds good. I'll close it out for now and if it comes up again, happy to revisit!
