### ISSUE TITLE
SUPP: MySQL CI MYSQL_INITDB_SKIP_TZINFO

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2162]
In the past, to fix an issue when running MySQL service locally on a HDD we needed to set `MYSQL_INITDB_SKIP_TZINFO: 1` (see https://github.com/ibis-project/ibis/pull/2030)

Currently this bugfix is already available for 10.4.12 (see https://github.com/docker-library/mariadb/issues/262#issuecomment-570243214)

removing `MYSQL_INITDB_SKIP_TZINFO: 1` will allow us adding more tests related to datetime operations for MySQL.

**Comment by grooverdan** [comment]
FYI the upstream docker library packages have been fixed wrt to TZ initialization.
