### ISSUE TITLE
[BigQuery] Missing OAuth Developer Verification

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#2179]
Sub-tasks

- [x] verify domain in Google Search Console
- [x] add privacy policy docs to ibis docs set
- [x] submit app for approval to Google

---

I received the following email from Google:

> Dear Developer,
>
> As part of our constant efforts to improve Google’s OAuth application ecosystem, we have launched additional protections to prevent malicious applications from spreading. Apps requesting risky OAuth scopes that have not completed the OAuth developer verification process are limited to 100 new user grants.
>
> Your Google Cloud/APIs project Ibis (id: ibis-gbq) has not completed this process and has reached 60% of this user limit. After this limit is exceeded, new users will be blocked from allowing your app to access their data until you complete the OAuth developer verification process. To enable more users for your app, please start the verification process by submitting the OAuth Developer Verification Form. For further information, please see the OAuth Quota Help Page
>
> Please take a moment to review the Google Cloud Platform Terms of Service, the Acceptable Use Policy and the applicable Terms of Service for the specific Google API you are using so that you do not violate our terms and policies in the future.

We'll need to verify that the docs.ibis-project.org domain is associated with the `ibis-gbq` project and submit the application for verification.

**Comment by tswast** [comment]
Google is now requiring DNS verification for domains. I don't think the old URL prefix verification can be used to verify apps anymore.

![image](https://user-images.githubusercontent.com/247555/78833848-2c720c00-79b3-11ea-8ad1-1a85c29d8f47.png)

Could someone who has the ability to add `TXT` records to the `ibis-project.org` domain do the following steps?

1. Sign in to your domain name provider (e.g. godaddy.com or namecheap.com)
2. Copy the TXT record below into the DNS configuration for ibis-project.org

```
google-site-verification=IVqzkYiD5E35oD4kkVOcTYCTfqWKU1f6zOHCnLIPkUU
```

3. @tswast or other owner of `ibis-gbq` GCP project: Press verify in https://search.google.com/search-console/not-verified

**Comment by jreback** [comment]
cc @cpcloud

**Comment by jreback** [comment]
cc @wesm (Phil said he doesn't have access here either :->)

**Comment by tswast** [comment]
I'll try with the "URL Prefix" version in my docs PR #2184 to add required privacy policy, but I'm pretty sure we'll still need the DNS TXT tag `google-site-verification=IVqzkYiD5E35oD4kkVOcTYCTfqWKU1f6zOHCnLIPkUU` on ibis-project.org in order to go through the full app verification process.

**Comment by tswast** [comment]
Since we are having trouble tracking down a domain owner, and I see @datapythonista is working on retooling the website (#2147), maybe it's time for a new domain too? I see several ibis related domains available.

**Comment by tswast** [comment]
With the recent change to have the Sphinx docs hosted at https://ibis-project.org/ I was able to verify the "url prefix". I have submitted the app for approval. 🤞

**Comment by jreback** [comment]
ok i got an email. let me verify this.

**Comment by tswast** [comment]
This issue should be resolved now. Got an email saying the app was approved.

**Comment by datapythonista** [comment]
I missed this, sorry. What did we need to verify with Google? Our website is hosted with GitHub pages, I wasn't aware we are using anything from Google for Ibis.

**Comment by tswast** [comment]
@datapythonista This was so that folks could login via the browser for the ibis-bigquery connector. One of the requirements is to have a public verified privacy policy, which I was eventually able to get working.
