### ISSUE TITLE
x.split(y)[i] -> regex_split(x, y, i) implement

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#218]
No reason not to get out of ahead of this. Perhaps implement in Impala as part of this

**Comment by wesm** [comment]
We can add a UDF to the forthcoming udf pack that implements this

**Comment by wesm** [comment]
dropping in impala 2.3.0 https://github.com/cloudera/Impala/commit/90eda963b58af3bc29dc1ac8e42e2ecc1da65aee

**Comment by cpcloud** [comment]
Closing. This would need a champion for the functionality to get implemented.
