### ISSUE TITLE
mutate geo column causes TypeError: geo_equals() got an unexpected keyword argument 'cache'

### ISSUE THREAD

**Issue by mikehinchey** [ibis-project/ibis#2197]
Using `mutate` with the same GEO column more than once causes an error.  The error happens when printing or using `compile()`.  If I only reference the same column once, the result is correct.

I'm using this with omniscidb.

The `geo_equals` function does not have a cache arg: https://github.com/ibis-project/ibis/blob/cc0ebb6242e75670d282476d6ea10bf5b8583fc4/ibis/expr/api.py#L1845

```
tm = t.mutate([
    t['Location'].y().name('Location_Latitude'),
    t['Location'].y().name('Latitude')])
tm.compile()
```

```
/opt/conda/lib/python3.7/site-packages/ibis/expr/operations.py in all_equal(left, right, cache)
    171 
    172     if hasattr(left, 'equals'):
--> 173         return left.equals(right, cache=cache)
    174     return left == right
    175 

TypeError: geo_equals() got an unexpected keyword argument 'cache'
```

**Comment by mikehinchey** [comment]
@xmnlab the commit I made above does not fix the problem, just brings it to the next problem `ValueError: The truth value of an Ibis expression is not defined`.

Now I'm wondering if it's conflating equals with geo_equals, where equals means something different as used in `all_equals` in `operations.py` above.  Do you have any hints how this might be addressed?

https://github.com/ibis-project/ibis/blob/b9f344ba39cacc98136f63d8f48f445052b7b2af/ibis/expr/api.py#L2562

**Comment by mikehinchey** [comment]
Removing that api mapping of `equals` to `geo_equals` fixes my cases because `all_equals` checks for an `equals` method, else uses `==`. However, that would break alchemy which defines GeoEquals and api binds to `equals`. I don't see how to fix this without changing the api to call the method something like `geo_equals`.

**Comment by xmnlab** [comment]
@mikehinchey I can check that today at the end of the day.
