### ISSUE TITLE
Handling of 0 row UDAs

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#22]
<a href="http://github.mtv.cloudera.com/bittorf"><img src="https://gravatar.com/avatar/ede422bd4925e3d0a37a07cfa251531c?d=https%3A%2F%2Fidenticons.github.com%2F1543843a4723ed2ab08e18053ae6dc5b.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bittorf](http://github.mtv.cloudera.com/bittorf)**
_Thursday Dec 18, 2014 at 18:42 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/22_

---

Currently, if a UDA is called with 0 rows, it will return NULL. 

For example,

SELECT ibis_uda(stuff, foo) FROM table WHERE false;

will return NULL. It will not call the Init or Finalize function for the user.

**Comment by cpcloud** [comment]
Closing as wontfix. There isn't enough information here to justify keeping it open.
