### ISSUE TITLE
Issue with Kerberized Cluster with HDFS Connection

### ISSUE THREAD

**Issue by waldenrt** [ibis-project/ibis#2203]
All,

When I'm creating a connection to a secured (kerberos/ssl/tls) cluster to write into a table via Impala and turn off the verify_ssl in the HDFS_Connect step, everything seems to work fine other than warnings that come up.  When I set verify to true, it fails with the following error:

SSLError: HTTPSConnectionPool(host='10.52.132.51', port=14000): Max retries exceeded with url: /webhdfs/v1/tmp/ibis/pandas_d7dc198d84d34ac89657d7687cec688a?op=MKDIRS (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

First question is, where is it picking up the certificate to use to verify?  Secondly, is there a way to pass the certificate to use?  I'm using the latest version of the Ibis framework.

Thanks,

Richard

**Comment by waldenrt** [comment]
Here is the warning I am getting when I set verify to false:

/home/cdsw/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

**Comment by JacoGasp** [comment]
hello @waldenrt, I'm facing the same issue: without `verify=True` I cannot connect to the secured cluster and with `verify=False` I receive the same warning.

Did you find a way to pass che ssl cert to the method?
