### ISSUE TITLE
Sync ibis conda-feedstock dependencies with ibis dependencies

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2204]
https://github.com/conda-forge/ibis-framework-feedstock/pull/43 added some pinnings to the conda package recipe. The pinnings were:

- numpy >=1.15
- pandas >=0.25.3
- pyarrow >=0.15
- pymapd >=0.22.0
- thrift >=0.11

the current requirement file  for development (eg. https://github.com/ibis-project/ibis/blob/master/ci/requirements-3.7-dev.yml), related to these packages, differs for pymapd, thrift and pyarrow.

would be good to replicate here these pinnings?

**Comment by cpcloud** [comment]
This is out of date.
