### ISSUE TITLE
ENH/DOC: sql_to_ibis package

### ISSUE THREAD

**Issue by zbrookle** [ibis-project/ibis#2236]
I've just finished making a package which parses sql into ibis expressions. The link to the repo is here https://github.com/zbrookle/sql_to_ibis. I was wondering if there was any interest in merging the work that I've done with the current ibis. I understand if there isn't because it is a lot of work to maintain a sql parser, and if so would it be possible to maybe link my package in your documentation so that users can easily find it?

**Comment by jreback** [comment]
yes let's start with a link (and in-line example would be nice). I think will need some time to look at the package itself .

**Comment by zbrookle** [comment]
@jreback Ok sounds good. I don't see any kind of partners/third-party library pages, so where should I add the link?
