### ISSUE TITLE
Support a more fine-grained datediff function in Impala (once it exists)

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#224]
Impala does not yet support a proper date difference (e.g. milliseconds between or nanoseconds between). While nanoseconds-between can yield int64 overflows on historical dates (pandas supports a little under 500 years range due to using nanosecond resolution), this is still decently useful.

Note that Impala's `datediff` function is the only real "timedelta" function, but it only computes days between, which isn't that useful in general.

**Comment by wesm** [comment]
Once #448 is merged, we can start a C++ "UDF pack" that includes this method, and can either be incubated into Impala trunk or stay a part of Ibis

**Comment by helger** [comment]
Is this now supported?

**Comment by wesm** [comment]
No, but I'm still interested in this area of functionality

**Comment by ENsu** [comment]
I am interested in developing this function. Can someone give me some advices where to start ?

**Comment by mariusvniekerk** [comment]
I would test against a current install of impala.  Best to verify what the current behavior is. 

A less precise version should be possible by casting both timestamps to int64 and then compute the difference.  This will return a delta in seconds if memory serves.

**Comment by cpcloud** [comment]
This is still in units of days as of 2021: https://impala.apache.org/docs/build/html/topics/impala_datetime_functions.html#datetime_functions__datediff
