### ISSUE TITLE
BUG: Can't perform having without group by clause

### ISSUE THREAD

**Issue by zbrookle** [ibis-project/ibis#2240]
Is there a reason that ibis doesn't allow having without a group by clause? I know that ibis is supposed to have first class sql support, so it in theory should be able to mimic the behavior of a statement such as 

```sql
 select count(*)
     from table
     having count(*) > 5;
```

However, I found this code, while experimenting, making it seem like this behavior was explicitly not allowed

``` python 
    if op.having:
        # .having(...) is only accessible on groupby, so this should never
        # raise
        if not op.by:
            raise ValueError(
                'Filtering out aggregation values is not allowed without at '
                'least one grouping key'
            )
```

Is there a reason that this functionality doesn't exist? I realize it's rarely used, but it is a part of sql

**Comment by datapythonista** [comment]
Thanks @zbrookle, I think this is a not well known feature of SQL (at least I didn't know about it). I guess that's the reason this was implemented. If you want to give a try at removing that condition, and see if everything works as expected, a PR would surely be welcome.

**Comment by zbrookle** [comment]
@datapythonista I'll definitely give a try!

**Comment by zbrookle** [comment]
@datapythonista While working on this issue, I've found some limitation in the way that .aggregate is implemented. Unlike most other ibis classes, it has parameter having, rather than an attribute/method .having(). I think it's a bit confusing and messy for it to be structured like that and also prevents the user from having a field called "having". I think an attribute would probably be better suited, but I realize this would also probably be a breaking change. Do you have any thoughts on this?

**Comment by datapythonista** [comment]
Not so familiar with that part of the code yet. @jreback, thoughts on this?
