### ISSUE TITLE
Working with TimeDeltas with Postgres Backend Fails

### ISSUE THREAD

**Issue by chapmanbe** [ibis-project/ibis#2243]
I'm trying learn Ibis by using it to query a postgres database. I read in two timestamps and then create an IntervalValue by computing the difference

```Python
t2 = t.projection(['outtime',  'intime']).mutate((t.outtime-t.intime).name("delta"))
```
I then try to extract the number of days in the interval

```Python
t3 = t2.mutate(days=t2.delta.days)
```

This produces an error:

```
Translation to backend failed
Error message: No translation rule for <class 'ibis.expr.operations.IntervalFloorDivide'>
```

With the following description of the attempted execution

```Python
ref_1
Selection[table]
  table:
    Table: ref_0
  selections:
    outtime = Column[timestamp*] 'outtime' from table
      ref_0
    intime = Column[timestamp*] 'intime' from table
      ref_0
    delta = TimestampDiff[interval<int32>(unit='s')*]
      left:
        outtime = Column[timestamp*] 'outtime' from table
          ref_0
      right:
        intime = Column[timestamp*] 'intime' from table
          ref_0

Selection[table]
  table:
    Table: ref_1
  selections:
    Table: ref_1
    days = IntervalFloorDivide[interval<int32>(unit='D')*]
      left:
        delta = Column[interval<int32>(unit='s')*] 'delta' from table
          ref_1
      right:
        Literal[int32]
          86400
```

Are these time manipulations simply not yet implemented for Postgres?

**Comment by datapythonista** [comment]
@xmnlab do you know if this is indeed a bug?

**Comment by xmnlab** [comment]
@chapmanbe what is the version you are using?

I tried your example and it worked here (using master branch) https://github.com/Quansight/ivan-sandbox/blob/master/ibis/issues/psql-time-interval.ipynb

also I tried the same notebook (without "load_data") using version 1.3.0 and it worked too

**Comment by cpcloud** [comment]
Seems like this works.
