### ISSUE TITLE
bug: infer_numpy_scalar() got an unexpected keyword argument 'allow_overflow'

### ISSUE THREAD

**Issue by mikehinchey** [ibis-project/ibis#2255]
Using a numpy.int64 type in this expression causes an error.  Using a literal works correctly, and using `int(x)` in the expression also fixes the problem.  I ran into this because my first query returns a count as int64, then that is used in the equation in my second query.

The caller uses a param
https://github.com/ibis-project/ibis/blob/2aaa4a050e920f1a14c474a98e40f1dc20a544a4/ibis/expr/rules.py#L397

The function is declared with `@dt.infer.register` but doesn't define the same param.
https://github.com/ibis-project/ibis/blob/b3d0400d092fcd93bc8da6bfe214afd9b88d4a29/ibis/pandas/client.py#L124

```
import pandas as pd
import ibis

df = pd.DataFrame({'a': [1,2,3]})
t = ibis.pandas.from_dataframe(df)

x = pd.to_numeric('22')
s = t['a', (t['a'] + x).name('a1')]
s.execute()
```

```
<class 'numpy.int64'>
...
/opt/conda/lib/python3.7/site-packages/ibis/expr/rules.py in <listcomp>(.0)
    395     # _at least_ as large as the smallest type in the expression.
    396     values = starmap(op, product(*bounds))
--> 397     dtypes += [dt.infer(value, allow_overflow=True) for value in values]
    398 
    399     return dt.highest_precedence(dtypes)
...
TypeError: infer_numpy_scalar() got an unexpected keyword argument 'allow_overflow'

```

**Comment by cpcloud** [comment]
Threading the `allow_overflow` value through seems to break a decent number of test cases, so this requires some more investigation.

**Comment by cpcloud** [comment]
We're no longer passing this argument around. Please reopen this if it's still a problem.
