### ISSUE TITLE
Represent Selection operation in expression graph

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2262]
When we have a expression like the next, the graph representing the expression (`_repr_png_`) show an expression box:
```python
table['col1', 'col2']
```
Then, if we have a calculated column, Ibis represent with the appropriate chart, for example a `Divide` operator or a table column and a literal:
```python
table['col2'] / 10
```
But putting both things together, results in just the `Selection` box, and the `Divide` part gets lost:
```python
table['col1', table['col2'] / 10]
```

**Would it make sense to represent expressions in a selection with their graph? Do you think it's possible?**

CC: @jreback, @xmnlab 

Here there is an example with the graphs:
![ibis_selection_expr](https://user-images.githubusercontent.com/10058240/86363362-9e828600-bc6e-11ea-9132-63e7122b65cf.png)

**Comment by xmnlab** [comment]
@datapythonista 
I think it makes total sense ... but not sure how much effort would be necessary for that.

**Comment by cpcloud** [comment]
PRs welcome
