### ISSUE TITLE
Clean up of GitHub labels

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2263]
I don't find the labels of the project particularly useful, half of the issues I create or triagge end up without label. And I think half of the labels haven't been used.

I'm thinking on cleaning up a bit, including creating a `core` label for the things related to expressions/operations. And also prefixing all the backends with `backend - XXX`.

Please let me know if you have any objection.

**Comment by xmnlab** [comment]
I don't have any objection

**Comment by jreback** [comment]
ok by me

**Comment by datapythonista** [comment]
I did some changes to the labels:
- Remove the ones that were not being useful, to make it easier to find the rest
- Standardized the backends labels, starting all them by `backends - XXX`, and having the same color, to see faster that they are a backend label
- Made the `docs` and `good first issue` labels the same color as in pandas

I guess those changes should make our lives easier, but let me know if any of the changes are making things worse for you
