### ISSUE TITLE
Conda takes too long to solve for the CI (again)

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2271]
Builds in the CI are failing again, apparently conda couldn't solve in one hour (the timeout for builds).

See for example: https://dev.azure.com/ibis-project/ibis/_build/results?buildId=2697&view=logs&j=9e44c89c-30a9-51db-3587-8ac019948434&t=6577b211-5bee-5bb8-9b94-e94e42a9e8f4&l=688

**Comment by jreback** [comment]
can u show the diff in the package list?

**Comment by datapythonista** [comment]
I think it's again related to `pymapd`. Removing it makes the solver finish in 4 minutes. They released a new version couple of days ago, I'm still testing.

I don't think our requirements list changed. And I'm not sure how to get a diff of what's resolved if I can't make the solver finish first. If I'm not understanding you let me know. Otherwise I'll keep testing and see if I can narrow the problem with `pymapd` (and may be pin it for now).

**Comment by jreback** [comment]
let’s let’s pin pymapd
