### ISSUE TITLE
BUG: OmniSciDB - Fix the default `else_` for the `when` operation

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2276]
Currently, the default omniscidb `else_` operation, combined with `when`, is given a wrong translation `CAST(NULL AS STR)`.
maybe it is an old implementation and it should be updated. IIRC, OmniSciDB didn't have literal NULL support some years ago.

probably, it can be translated directly to NULL. 

Current behavior:

```python
>>> t = con.table('functional_alltypes')
>>> expr = ibis.case().when(t.string_col == '1', 'one').end().name('num_sessions')
>>> print(expr.compile())
SELECT CASE WHEN "string_col" = '1' THEN 'one' ELSE CAST(NULL AS STR) END AS tmp
FROM functional_alltypes
```

**Comment by cpcloud** [comment]
Please redirect to the omnisci backend's current repo.
