### ISSUE TITLE
CI: Undo pytest<6.0.0rc1 pin when higher version works with CI

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2278]
`pytest` is pinned to be <=6.0.0rc1 in #2277 to fix the CI (see #2275)

We should unpin when higher versions of pyarrow work with the CI

**Comment by datapythonista** [comment]
Is this a duplicate of #2222 or #2192?

**Comment by timothydijamco** [comment]
Oops, this is for `pytest` not `pyarrow`

**Comment by cpcloud** [comment]
This is fixed. We're now using `^6` (`>=6,<7`) in CI.
