### ISSUE TITLE
Nested schema API design

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#229]
Augment existing type system and create sane user API for each of

- [ ] lists
- [ ] structs
- [ ] maps

according to capabilities supported by Impala out the gate, at least. This is a small project, so I'll create subissues for each of the top-level todo items and we can track the progress here

**Comment by cpcloud** [comment]
Pushing to 0.11, since this is quite involved and would need probably a few days of solid work to get a prototype of at least lists going.

The main issue I see is how to describe the `UNNEST(array | map)` operation in ibis land.

**Comment by cpcloud** [comment]
We have type system support here, and backend support in bigquery and postgres. Impala needs a bit of work to paper over some of the syntax here. I'll make an issue.

**Comment by tswast** [comment]
What's the issue for Impala support?
