### ISSUE TITLE
feat: implement following for window for pandas backend

### ISSUE THREAD

**Issue by LeeTZ** [ibis-project/ibis#2297]
For pandas backend, `window` allows `following` as a param but implementation is missing:
https://github.com/ibis-project/ibis/blob/master/ibis/pandas/execution/window.py#L180

**Comment by cpcloud** [comment]
Seems interesting. Last I checked this wasn't easily possible with pandas. @jreback Has that changed? Can a window include rows both before *and after* the current row in window computation?

**Comment by jreback** [comment]
yea it could with a custom indexer which .rolling can take directly 

cc @mroeschke

**Comment by mroeschke** [comment]
Yup. The `rolling` constructor in pandas accepts a `pandas.api.indexers.BaseIndexer` subclass which will window based on the subclass's defined `get_window_bounds` method

 https://pandas.pydata.org/docs/reference/api/pandas.api.indexers.BaseIndexer.get_window_bounds.html#pandas.api.indexers.BaseIndexer.get_window_bounds

**Comment by cpcloud** [comment]
Would happily accept a PR for this.
