### ISSUE TITLE
test: TPC-H coverage with Ibis

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#230]
As part-demo, part-documentation, part-API dogfooding, it would be useful to port as many of the TPC-H suite queries to use Ibis as possible. Let's use this issue to track progress and note issue numbers tracking whatever is blocking any query from being fully ported

Queries are available here: https://duckdb.org/benchmarks/tpch.html

- [ ] Q1
- [ ] Q2
- [ ] Q3
- [ ] Q4
- [ ] Q5
- [ ] Q6
- [ ] Q7
- [ ] Q8
- [ ] Q9
- [ ] Q10
- [ ] Q11
- [ ] Q12
- [ ] Q13
- [ ] Q14
- [ ] Q15
- [ ] Q16
- [ ] Q17
- [ ] Q18
- [ ] Q19
- [ ] Q20
- [ ] Q21
- [ ] Q22

**Comment by saulpw** [comment]
Queries are being added to (ibis-project/tpc-queries](https://github.com/ibis-project/tpc-queries).

**Comment by saulpw** [comment]
All queries complete and have no diffs with the corresponding raw sqlite queries.
![Screenshot from 2022-01-14 11-42-49](https://user-images.githubusercontent.com/236498/149575741-58aa2328-854e-42c8-a607-ab98116854b8.png)
