### ISSUE TITLE
DOC: add asof_join to TableExpr docs

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#2309]
should be here  http://ibis-project.org/docs/api.html#api-table

**Comment by matthewmturner** [comment]
Is this as simple as adding the file `ibis.expr.api.TableExpr.asof_join` to `docs/source/generated`?  Or does the generated imply that it needs to be done elsewhere and its auto added to that directory?

**Comment by datapythonista** [comment]
The `generated` directory shouldn't be in git, and it's generated automatically when the docs are built. The API pages are created automatically from the autosummary tables in the `api/` directory (or any other docs file, but there is where we have them).

**Comment by matthewmturner** [comment]
Ok - should i add that directory to `.gitignore` as well with a PR for this?

**Comment by datapythonista** [comment]
It's there already: https://github.com/ibis-project/ibis/blob/master/.gitignore#L49 :)
