### ISSUE TITLE
ENH: Hash function for BigQuery

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#2310]
I'd like to implement the [hash function](https://ibis-project.org/docs/generated/ibis.expr.api.ValueExpr.hash.html#ibis.expr.api.ValueExpr.hash) for BigQuery (specifically, I'd like to use the [BigQuery SHA256 hash function](https://cloud.google.com/bigquery/docs/reference/standard-sql/hash_functions#sha256)), but I see a couple of questions that need to be answered before implementing.

- Currently, hash is a ValueExpr, but in BigQuery only BYTES / STRING are acceptable as inputs. Should we implement it in BigQuery as a string expression instead?
- Currently, hash outputs int64, but BigQuery outputs BYTES (which makes sense since SHA256 generates a 256-bit hash). Would it make sense to change the impala return type to match? Or is it okay to be inconsistent?

Note: other databases tend to align with how BigQuery handles hashes. See:

- [SQL Server / T-SQL](https://docs.microsoft.com/en-us/sql/t-sql/functions/hashbytes-transact-sql?view=sql-server-ver15)
- [PostgreSQL](https://www.postgresql.org/docs/11/functions-binarystring.html)

**Comment by srinathh** [comment]
There are hash functions that return both bytes & ints (farm_fingerprint) in the bigquery api. It would be great to have both forms supported

https://cloud.google.com/bigquery/docs/reference/standard-sql/hash_functions
