### ISSUE TITLE
feat: option to cache query results to disk locally

### ISSUE THREAD

**Issue by marianoteehan** [ibis-project/ibis#2318]
Hello, I'm finding I often run the same queries over and over again while I work on a project and it would be nice if ibis had the option of caching query results, any chance of supporting this as a configurable option?

I hacked together a solution for this via monkey-patching, I've started adding this to my notebooks -- it's a bit ugly, but the speedup is worth it for me, even if the queries only take a few seconds each it really adds up.   Query results are pickled with filename being a hashed digest of the compiled SQL.

```
cache_folder = ".cache"
import ibis
ibis.config.set_option("interactive", True)
import pickle
import hashlib
import os
if not os.path.exists(cache_folder):
    os.makedirs(cache_folder)
def go(func, key_obj, **kwargs):    
    key = hashlib.sha224(str(key_obj).encode()).hexdigest()
    path = os.path.join(cache_folder, key)
    if not os.path.exists(path):
        result = func(**kwargs)
        pickle.dump(result, open(path, 'wb'))
    return pickle.load(open(path, 'rb'))

ibis.expr.types.TableExpr.go = lambda self, **kwargs: go(self.execute, self.compile(), **kwargs)
ibis.expr.types.IntegerScalar.go = lambda self, **kwargs: go(self.execute, self.compile(), **kwargs)
```

Then I just append .go() to an expression when I want to execute it and use the cache.

**Comment by datapythonista** [comment]
Thanks for the report @marianoteehan. Do you think #1274 will help with this?

**Comment by marianoteehan** [comment]
Not certain, it looks like that's a way of serializing the expression?  If so I think that could make caching slightly easier, but I think you'd still need to implement most of what I wrote above to actually cache query results, no?

**Comment by cpcloud** [comment]
cc @saulpw I know you are interested in this.

**Comment by cpcloud** [comment]
@marianoteehan Would something like Fugue work for this? @goodwanghan Thoughts?
