### ISSUE TITLE
DOCS: documentation links are broken

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#2319]
http://ibis-project.org/docs/ leads to a 404 

http://ibis-project.org/index.html lands but then clicking on Documentation at the top fails.

**Comment by datapythonista** [comment]
Looks like the docs build was cancelled after one hour (the conda solver took 40 minutes). The weird part is that the sphinx build [was cancelled at 67%](https://dev.azure.com/ibis-project/ibis/_build/results?buildId=2956&view=logs&j=8f09edc2-e3b7-52de-126a-0225c4f3efa1&t=e3ba5a33-21a6-5484-d0be-59baf122f79c&l=1106) but the next steps that push the docs were still executed by pipelines.

**Comment by datapythonista** [comment]
The last documentation build finished in 53 minutes, and the docs were complete. The next merge to master should be the one changing the dependencies and speeding up conda, so the docs build shouldn't take that long anymore in master. Closing.
