### ISSUE TITLE
Time binning / resampling support analytics

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#232]
Time binning is pretty tedious for most users, it would be useful to simplify this for common use cases (e.g. daily, hourly, minutely binning).

Question: does Impala know about leap seconds? (no need: https://twitter.com/posco/status/605832830677950464)

**Comment by cpcloud** [comment]
Rough steps to get this done:

### Questions

1. What does the resample API look like?
2. How does it compose with the rest of ibis? The rewrite would involve table expressions that produce a column. There's a challenge in making sure that there are no reference errors, i.e., that leaf tables are correct

### Steps

1. API design
2. Generate the right SQL. This involves generate a sequence for the join part of the rewrite, which doesn't exist in some (most?) backends. A recursive CTE might be necessary.
3. Tests
