### ISSUE TITLE
RLS: 1.4

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#2321]
we should do a release for all of the recent updates.

**Comment by tswast** [comment]
Do we have thoughts on when we cut this release? I see there are still a few refactoring PRs open by @datapythonista so maybe we wait for the `base_sql` changes to be complete?

**Comment by datapythonista** [comment]
I think we're almost done with the refactoring. I'm planning to release next week, if all the next PRs are merged (all are ready or almost ready):

- #2501
- #2485 
- #2435
- #2497

**Comment by jreback** [comment]
yep +1 when ready @datapythonista 

also wouldn't be averse to calling this 2.0

**Comment by datapythonista** [comment]
I think the next release will be a bigger change, if we start using entrypoints, and move omnisci and possibly other backends out. Maybe 2.0 is a good number for that one, since it's probably a bigger change. But no strong preference.

**Comment by jreback** [comment]
do we warn in the import change now? eg ibis.omnisci )

**Comment by jreback** [comment]
yea will add

**Comment by jreback** [comment]
@datapythonista added you to pypi (you should see an invite)

**Comment by datapythonista** [comment]
Great, accepted it.

**Comment by datapythonista** [comment]
@jreback I think we are ready to release. Mentioned in other issues, but what I'd do is to release what we've got as 1.4, in the same way as we've been doing until now. Including one single conda package for everything.

After the release, I'll create an issue to discuss what what to do next (entrypoints, move omnisci package out...).

Does this sound good?

**Comment by jreback** [comment]
ok sounds good to me

**Comment by datapythonista** [comment]
@jreback @ibis-project/ibis-owners will be releasing Ibis 1.4 today. Please don't merge any PR until I'm done. Thanks!

**Comment by datapythonista** [comment]
pip package release, working on the conda-forge one now

**Comment by jreback** [comment]
great i think we have docs in the release process - can u update if you find anything different

**Comment by datapythonista** [comment]
> great i think we have docs in the release process - can u update if you find anything different

Yes, I'll make few changes once I'm done. Things are mostly correct, but I'll remove the docs part that is not needed anymore.

Let's see if the CI at https://github.com/conda-forge/ibis-framework-feedstock/pull/51 ends green, and I think we're done after merging it.

**Comment by jreback** [comment]
sure ping when ready

**Comment by datapythonista** [comment]
> sure ping when ready

@jreback not sure if you've seen the ping in https://github.com/conda-forge/ibis-framework-feedstock/pull/51, but the PR for the conda-forge package should be ready.

**Comment by jreback** [comment]
just merged
thanks a lot @datapythonista

**Comment by datapythonista** [comment]
Release complete.

Installing the `ibis-framework` package in a clean environment takes 6 minutes in Python 3.8 (where pymapd is no installed) and 12 minutes in Python 3.7.

I'm aiming at releasing 2.0 in just few weeks, after we start using entrypoints, and we release all backends as conda subpackages. I'll also be moving the omnisci backend out before releasing 2.0.
