### ISSUE TITLE
CI: Building the conda package in the CI takes too long

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2324]
The step `feedstock` in the GitHub actions job `Lint, package and benchmark` is taking longer than it should.

The last run took around 20 minutes. Most of the time is spent in solving two conda environments, around 7 minutes each. This seems excessive, I didn't check the requirements files being installed, but I guess limiting the versions of the packages (e.g. `ibis` -> `ibis>=1.3`) should limit the search space of the solver and be able to solve the environment almost immediately.

**Comment by cpcloud** [comment]
It's pretty quick now with mamba
