### ISSUE TITLE
CI: Add Bigquery credentials to GitHub secrets

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2325]
@tswast do you have the credentials for the Bigquery tests? If you can send it to me via email that would be great. I moved the bigquery job to GitHub actions, and will fail until we add the credentials as a secret. Thanks!

**Comment by tswast** [comment]
@datapythonista I've granted you access to the ibis-gbq project. You should be able to create a key for the system-tests service account now.

**Comment by datapythonista** [comment]
Thanks @tswast, I added the existing key to GitHub. Tested it, but looks like we're missing an environment variable for the big query tests to run. Opened #2327 for it.

**Comment by datapythonista** [comment]
@tswast do you know why the json key was encoded as base64? Not a big difference, but I don't see the value compared to simply use `cat "${{ secrets.KEY}}" > key.json` (instead of `base64 --decode --ignore-garbage <<< "${{ secrets.KEY }}" > key.json`).

**Comment by tswast** [comment]
I think it's because at one point the encrypted contents were set to an environment variable, so it was best to avoid non-ascii characters.
