### ISSUE TITLE
CI: Bigquery backend failing to load data

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2330]
@tswast can you have a look at [this CI error](https://github.com/ibis-project/ibis/runs/984884965#step:4:1418) please?

Not sure what's the problem, I'd say that I'm calling the loading of data for bigquery in the same exact way as it was before.

**Comment by tswast** [comment]
Oops. Looks like I never added the schema file to the testing data repo. https://github.com/ibis-project/testing-data/pull/3

Alternatively, I could create the equivalent DDL statements and put a bigquery.sql file in https://github.com/ibis-project/ibis/tree/master/ci/schema Would you prefer that?

**Comment by datapythonista** [comment]
Not so familiar with that part. Would be having a `bigquery.sql` file the approach used by the other backends? I'd prefer that if that's the case.

**Comment by tswast** [comment]
Yes, that seems to be what the other backends are doing

**Comment by datapythonista** [comment]
@tswast looks like something is still broken, do you mind having a look: https://github.com/ibis-project/ibis/runs/1004194744?check_suite_focus=true#step:4:1380

**Comment by tswast** [comment]
Ah, that one will require some new test data (or actually, just uploading the test data I must have created a couple years ago) https://github.com/ibis-project/testing-data/pull/4
