### ISSUE TITLE
feat: pass error param to approx_nunique

### ISSUE THREAD

**Issue by niviksha** [ibis-project/ibis#2344]
In OmniSciDB's implementation for `approx_nunique` I see the code has this translation for the operator
```
'approx_nunique',
    sql_func_name='approx_count_distinct',
    sql_signature='{}({}, 100)',
)
```

and the ibis operator itself is
`ColumnExpr.approx_nunique(where=None)`

in OmniSciDB we can pass a precision parameter that allows you to tradeoff speed vs accuracy for this operation e.g.
```
APPROX_COUNT_DISTINCT(x, e) where e is an error rate value between 1 and 100 (100 - lowest error, equal to exact COUNT(DISTINCT()) )
```
is it possble to have a variation of this operation so we can pass this additional param to the function rather than fixing it at 100? (edited)

**Comment by cpcloud** [comment]
Duplicate.
