### ISSUE TITLE
Move OmniSciDB to a separate repo

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2356]
I think it can be a good idea to move the OmniSciDB to a separate GitHub repo. The main reason is https://github.com/ibis-project/ibis/pull/2348#issuecomment-686782863, seems like `pymapd` has strict dependencies, and it's not the first time we have problems solving environments when including this.

Since we're increasingly having new backends, and some of them are already in separate repos (Arrow, mssql, and Oracle soon), I think we'll have to address how we want to deal with external backends anyway. Like having their documentation with the rest in ibis-project.org, or deciding if we want to run the backend tests in the main repo, or in the backend repos.

Also, I guess it makes sense that senior people at OmniSci has commit right to their own backend (whether it lives in the ibis-project organization, or in the OmniSci organization). They'll be able to maintain better than us things like updates in pymapd or OmnisciDB...

@jreback what do you think?

**Comment by jreback** [comment]
yep all this sounds ok

the tricky part with other repos is that there needs to be published packages - so need a little more effort to do this

i am still +1 on only have the ibis namespace but can just have it import the other repo packages eg ibis-omnisci 
so the user xp would be the same

**Comment by datapythonista** [comment]
Closed via #2563
