### ISSUE TITLE
Make behavior of `nullif` consistent across backends

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2365]
Currently the kind of null value returned by `nullif` differs across backends (and versions of packages). We should make the behavior consistent.

`nullif` returns `None` on these backends:
 - BigQuery
 - Clickhouse
 - MySQL
 - OmniSciDB
 - Postgres
 - Spark (if using `pyspark==3.0.0`)
 - SQLite
 - PySpark (if using `pyspark==3.0.0`)

`nullif` returns `np.nan` on these backends:
 - Csv
 - Pandas
 - Parquet
 - Spark (if using `pyspark<=3.0.0`)
 - PySpark (if using `pyspark<=3.0.0`)

Relevant test:
https://github.com/ibis-project/ibis/blob/master/ibis/tests/all/test_generic.py#L44

**Comment by tswast** [comment]
BigQuery actually reports `nan` on the latest versions of `google-cloud-bigquery`, at least when `pyarrow` is also installed.

**Comment by cpcloud** [comment]
Is this possible to do in general without casting everything to `object` dtype? Can we use extension arrays?

**Comment by cpcloud** [comment]
Would happily accept a PR for this
