### ISSUE TITLE
Use Arrow for nested (struct / list) types

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#2377]
Currently, Ibis tests assume Python objects as representation for lists and structs.

Especially for backends that already represent intermediate results as Arrow ([BigQuery](https://cloud.google.com/bigquery/docs/reference/storage), [PySpark](https://spark.apache.org/docs/latest/sql-pyspark-pandas-with-arrow.html)), it would be more performant to use Arrow as the native format.

**Resources**

- [Fletcher](https://github.com/xhochy/fletcher) -- pandas extension dtypes backed by Arrow
- Discussion: https://lists.apache.org/thread.html/rcdd8f4ec774356951a2dcaf85fba9a9fc06de731d8b3c265e596a531%40%3Cdev.arrow.apache.org%3E

**Related issues**

- [BigQuery] `test_scalar_param_nested` is failing #2373
- [BigQuery] `test_array_concat` is failing #2370
- [BigQuery] `test_string[split]` is failing #2372
- [BigQuery] `test_scalar_param_array` is failing #2374

**Comment by cpcloud** [comment]
This would likely be part of our epic to minimize dependence on pandas and move towards pyarrow/RecordBatches.
