### ISSUE TITLE
feat: make behavior of `ibis.window(order_by=xxxx)` consistent across backends

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2378]
See https://github.com/ibis-project/ibis/pull/2376#issuecomment-692116716 (quoted below):
> There are some differences in how backends view a window spec like this:
> 
> ```
> ibis.window(order_by=order_by)
> ```
> 
> Backends that treat this as a completely unbounded window (applies the function over ALL rows in the table):
> 
> * Pandas
> * PySpark
> * Postgres
> * MySQL
> * SQLite
> * Clickhouse
> 
> Backends that treats this as an expanding window (apply the function over all rows up until the current row):
> 
> * Spark
> * Impala

[More info on Spark's behavior behavior](https://stackoverflow.com/questions/47130030/whats-the-default-window-frame-for-window-functions)
[More info on Impala's window behavior](https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/impala_analytic_functions.html#over)

--

Most likely we should change the behavior of the Spark and Impala backends to match the other backends. The Spark backend inherits from the Impala one for this behavior, so this might just need a fix in the [Impala backend's translation function for windows](https://github.com/ibis-project/ibis/blob/3a3b46edca87cbe8ba601406a2ebb8536904d2dd/ibis/impala/compiler.py#L280).

**Comment by cpcloud** [comment]
We'll look into this, it seems like a bug in the translation of window frame clauses for Impala and/or Spark

**Comment by cpcloud** [comment]
Since the impala backend is currently on life support and the Spark (not Py) backend no longer exists, we're going to close this out. However, PRs are accepted for issues like this.
