### ISSUE TITLE
feat: make behavior of `ibis.window()` (empty window spec) consistent across backends

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2381]
When applying an analytic op (like `lag` or `lead`) over an empty window spec (`ibis.window()`), the Spark backend implicitly changes the window spec to have an `ORDER BY` clause. This causes it to produce different results from other backends.

The Spark backend actually inherits from the Impala backend for this behavior. This is the relevant code:
https://github.com/ibis-project/ibis/blob/3a3b46edca87cbe8ba601406a2ebb8536904d2dd/ibis/impala/compiler.py#L312-L315

I was having trouble testing with the Impala backend locally, so I wasn't able to tell whether the Impala backend also produces results inconsistent with other backends (i.e., results like the Spark backend). But I don't see any reason why it would not.

To summarize:
- **Spark backend** has behavior different from other backends
- **Impala backend** most likely has behavior different from other backends

### Spark backend
```
import pandas as pd
import ibis
from pyspark.sql import SparkSession

# Set up client and data
df = pd.DataFrame({
    'id': [0, 1, 2, 3],
    'value_col': [4, 1, 2, 3]
})

spark = SparkSession.builder.getOrCreate()
client = ibis.spark.connect(spark)

spark_df = client._session.createDataFrame(df)
spark_df.createOrReplaceTempView('test_table')

# Do `lag` over empty window spec
table = client.table('test_table')

win = ibis.window()
expr = table.mutate(
    val=table.value_col.lag().over(win)
)

result = expr.execute().sort_values('id')
print(result.to_markdown())
```
|    |   id |   value_col |   val |
|---:|-----:|------------:|------:|
|  3 |    0 |           4 |     3 |
|  0 |    1 |           1 |   nan |
|  1 |    2 |           2 |     1 |
|  2 |    3 |           3 |     2 |

The Spark backend sorts by the column being operated on (`val`) before doing the `lag` operation, so the `nan` is in the middle of the rows.

### Pandas backend
```
# Set up client and data
df = pd.DataFrame({
    'id': [0, 1, 2, 3],
    'value_col': [4, 1, 2, 3]
})

client = ibis.pandas.connect({'test_table': df})

# Do `lag` over empty window spec
table = client.table('test_table')

win = ibis.window()
expr = table.mutate(
    val=table.value_col.lag().over(win)
)

result = expr.execute().sort_values('id')
print(result.to_markdown())
```
|    |   id |   value_col |   val |
|---:|-----:|------------:|------:|
|  0 |    0 |           4 |   nan |
|  1 |    1 |           1 |     4 |
|  2 |    2 |           2 |     1 |
|  3 |    3 |           3 |     2 |

The Pandas backend does not do any implicit ordering before doing the `lag` operation, so the `nan` is at the beginning of the rows as expected.

**Comment by cpcloud** [comment]
Would happily accept a PR for this. Seems like a bug.

**Comment by cpcloud** [comment]
This would also be a breaking change, since it's changing existing (though incorrect) behavior that someone might be depending on.

**Comment by cpcloud** [comment]
Similar to #2378, will happily accept a PR but no current maintainers have the bandwidth to fix this.
