### ISSUE TITLE
Does this library support Window?

### ISSUE THREAD

**Issue by noklam** [ibis-project/ibis#2382]
I am sorry to ask this obvious question, I cannot find the doc mention Window support. Is it Linux only? I seem to have trouble using it in Window for impala

**Comment by datapythonista** [comment]
It does work in Windows, we test most of the features in Windows in the continuous integration. We don't test impala, since it's tricky, but I think it should work.

If you open a new issue with the exact error and steps to reproduce it, and we'll have a look.

**Comment by noklam** [comment]
OK, I will file another issue for this later, thanks!
