### ISSUE TITLE
Impala Connection, AttributeError: module 'ibis.impala' has no attribute 'connect'

### ISSUE THREAD

**Issue by noklam** [ibis-project/ibis#2383]
Fails to connect.

OS: Window 10
ibis: 1.3.0

ibis.impala.connect
`AttributeError: module 'ibis.impala' has no attribute 'connect'`

ibis.api.impala.connect  
`AttributeError: module 'ibis.impala' has no attribute 'api'`

I am trying to run this example
http://ibis-project.org/docs/generated/ibis.impala.api.connect.html

```
import ibis
import os
hdfs_host = os.environ.get('IBIS_TEST_NN_HOST', 'localhost')
hdfs_port = int(os.environ.get('IBIS_TEST_NN_PORT', 50070))
impala_host = os.environ.get('IBIS_TEST_IMPALA_HOST', 'localhost')
impala_port = int(os.environ.get('IBIS_TEST_IMPALA_PORT', 21050))
hdfs = ibis.hdfs_connect(host=hdfs_host, port=hdfs_port)
hdfs  
<ibis.filesystems.WebHDFS object at 0x...>
client = ibis.impala.connect(
    host=impala_host,
    port=impala_port,
    hdfs_client=hdfs,
)
client  
<ibis.impala.client.ImpalaClient object at 0x...>

```

**Comment by noklam** [comment]
`pip install ibis-framework[impala]`

The solution is to run this command. It seems that the error is suppressed so it does not show error but import the wrong module, as a result it cannot find the connect() method.

**Comment by datapythonista** [comment]
This is a bit strange, in theory if impala is not installed, it should give the error that `ibis` has no attribute `impala`. If you share what's the value of `ibis.impala` and `dir(ibis.impala)` when you get those exceptions I'll have a look.

But that code is anyway being refactored in #2379, will have a look to see if this is still happening in that PR.

**Comment by noklam** [comment]
I try this on another laptop, and I can reproduce the same error
```
conda create -n ibis python==3.7.5
pip install ibis-framewrok
```

![image](https://user-images.githubusercontent.com/18221871/93359100-cb5d3700-f874-11ea-8cbb-0387a92a02a6.png)
![image](https://user-images.githubusercontent.com/18221871/93359123-d1531800-f874-11ea-9538-4cd19399542c.png)
