### ISSUE TITLE
CI: Impala image not starting in GitHub actions

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2388]
Ideally we'd like to move the Impala/Clickhouse job to GitHub actions, with the rest. But for some reason, the same docker image that works in Azure, is not working in GitHub actions (the container starts, but the Impala service is not accessible).

The job is already implemented, once the Impala service starts with the container, we simply need to stop skipping the build: https://github.com/ibis-project/ibis/blob/master/.github/workflows/main.yml#L72

The docker image should be this one: https://github.com/ibis-project/docker-impala

**Comment by ZeroCool2u** [comment]
I looked into this a bit, but I'm not super familiar with Impala and its setup, so I wasn't able to ID the root cause at the time. [This comment](https://github.com/ibis-project/ibis/pull/2268#issuecomment-659542112) may be helpful. If I have some spare time I'll take a look at this, because it's still really bothering me that it's working on Azure and not anywhere else.

**Comment by gerrymanoim** [comment]
I took some time to look into this, both locally and in Github Actions. Unfortunately I didn't make too much progres. 

On GHA, everything starts up correctly and we can connect, but once we go to test `can_write_to_hdfs` in the imapalamgr, we end up having `Temporary failure in name resolution` errors (on attempting to connect to http://9996ae25f815:50075/webhdfs/v1/__ibis/ibis-testing-data/8ff0f2b874234245b5d5282b5c1a151f?op=CREATE&user.name=hdfs&namenoderpcaddress=impala:8020&overwrite=false, which I _think_ is the container host, but I haven't tracked that down). 

Locally I can start everything with docker compose but then some of my requests end up failing and some succeed right after they failed.

**Comment by ZeroCool2u** [comment]
@gerrymanoim That's interesting that you managed to get stuff running locally. For me, the docker compose file technically starts, but the impala container never becomes responsive. It just pipes out a continuous error stream. What platform are you running Docker on? Maybe it has something to do with Docker itself?

**Comment by gerrymanoim** [comment]
I'm on macOS 10.14.6 with:

```
docker-compose version 1.25.5, build 8a1c60f6
Docker version 19.03.8, build afacb8b
```
and I ran `docker-compose up -d` in the root dir of `docker-impala`.  After a little bit I'll get the correct webpage at http://localhost:25000/. Then I have:

```python
import os
from io import BytesIO

import ibis
from ibis.impala.tests.conftest import IbisTestEnv
from ci.impalamgr import make_ibis_client

ENV = IbisTestEnv()
con = make_ibis_client(ENV)
test_file = BytesIO(ibis.util.guid().encode('utf-8'))
test_path = os.path.join(ENV.test_data_dir, ibis.util.guid())

con.hdfs.put(test_path, test_file)
```

What seems to happen is that sometimes the `put` call will work fine:

```
In [14]: con.hdfs.put(test_path, test_file)
Out[14]: '/__ibis/ibis-testing-data/fb134124fe844fc59acdba3dee48699f'
```

and then sometimes fail with a network error:

```
<long traceback going through ibis.filesystems ->  hdfs -> requests -> urllib3>
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x121998df0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
```

Turning debugging up a bunch, a successful request:

```
In [8]: con.hdfs.put(test_path, test_file)
   ...:
DEBUG:hdfs.client:Resolved path '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e' to '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e'.
INFO:hdfs.client:Writing to '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e'.
DEBUG:hdfs.client:Resolved path '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e' to '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e'.
send: b'PUT /webhdfs/v1/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e?user.name=hdfs&overwrite=False&op=CREATE HTTP/1.1\r\nHost: localhost:50070\r\nUser-Agent: python-requests/2.24.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\ncontent-type: application/octet-stream\r\nCookie: hadoop.auth="u=hdfs&p=hdfs&t=simple&e=1601537407498&s=EGQqo2bXwW8uY/G2BNKOiuTinjE="\r\nContent-Length: 0\r\n\r\n'
reply: 'HTTP/1.1 307 TEMPORARY_REDIRECT\r\n'
header: Cache-Control: no-cache
header: Expires: Wed, 30 Sep 2020 21:31:44 GMT
header: Date: Wed, 30 Sep 2020 21:31:44 GMT
header: Pragma: no-cache
header: Expires: Wed, 30 Sep 2020 21:31:44 GMT
header: Date: Wed, 30 Sep 2020 21:31:44 GMT
header: Pragma: no-cache
header: Content-Type: application/octet-stream
header: X-FRAME-OPTIONS: SAMEORIGIN
header: Location: http://localhost:50075/webhdfs/v1/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e?op=CREATE&user.name=hdfs&namenoderpcaddress=impala:8020&overwrite=false
header: Content-Length: 0
DEBUG:urllib3.connectionpool:http://localhost:50070 "PUT /webhdfs/v1/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e?user.name=hdfs&overwrite=False&op=CREATE HTTP/1.1" 307 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:50075
send: b'PUT /webhdfs/v1/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e?op=CREATE&user.name=hdfs&namenoderpcaddress=impala:8020&overwrite=false&user.name=hdfs HTTP/1.1\r\nHost: localhost:50075\r\nUser-Agent: python-requests/2.24.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\ncontent-type: application/octet-stream\r\nCookie: hadoop.auth="u=hdfs&p=hdfs&t=simple&e=1601537407498&s=EGQqo2bXwW8uY/G2BNKOiuTinjE="\r\nContent-Length: 32\r\n\r\n'
sendIng a read()able
send: b'e2c7c496563c45088da7798429f4cfef'
reply: 'HTTP/1.1 100 Continue\r\n'
reply: 'HTTP/1.1 201 Created\r\n'
header: Location: hdfs://impala:8020/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e
header: Content-Length: 0
header: Connection: close
DEBUG:urllib3.connectionpool:http://localhost:50075 "PUT /webhdfs/v1/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e?op=CREATE&user.name=hdfs&namenoderpcaddress=impala:8020&overwrite=false&user.name=hdfs HTTP/1.1" 201 0
Out[8]: '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e'
```

whereas a failed requests:

```
In [9]: con.hdfs.put(test_path, test_file)
   ...:
DEBUG:hdfs.client:Resolved path '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e' to '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e'.
INFO:hdfs.client:Writing to '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e'.
DEBUG:hdfs.client:Resolved path '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e' to '/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e'.
send: b'PUT /webhdfs/v1/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e?user.name=hdfs&overwrite=False&op=CREATE HTTP/1.1\r\nHost: localhost:50070\r\nUser-Agent: python-requests/2.24.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\ncontent-type: application/octet-stream\r\nCookie: hadoop.auth="u=hdfs&p=hdfs&t=simple&e=1601537407498&s=EGQqo2bXwW8uY/G2BNKOiuTinjE="\r\nContent-Length: 0\r\n\r\n'
reply: 'HTTP/1.1 307 TEMPORARY_REDIRECT\r\n'
header: Cache-Control: no-cache
header: Expires: Wed, 30 Sep 2020 21:32:21 GMT
header: Date: Wed, 30 Sep 2020 21:32:21 GMT
header: Pragma: no-cache
header: Expires: Wed, 30 Sep 2020 21:32:21 GMT
header: Date: Wed, 30 Sep 2020 21:32:21 GMT
header: Pragma: no-cache
header: Content-Type: application/octet-stream
header: X-FRAME-OPTIONS: SAMEORIGIN
header: Location: http://3493ed742452:50075/webhdfs/v1/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e?op=CREATE&user.name=hdfs&namenoderpcaddress=impala:8020&overwrite=false
header: Content-Length: 0
DEBUG:urllib3.connectionpool:http://localhost:50070 "PUT /webhdfs/v1/__ibis/ibis-testing-data/7970396e0c3941f193673832f570795e?user.name=hdfs&overwrite=False&op=CREATE HTTP/1.1" 307 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 3493ed742452:50075
```

That  `Location` header on the failing attempt doesn't look right, but I haven't had time to track this down or figure out why this is intermitent.

**Comment by gerrymanoim** [comment]
Oh also make sure you've stopped any postgressql service you have running locally. That may prevent the postgres container from starting (since it can't bind to the port) which will then cause the impala container to misbehave.

**Comment by ZeroCool2u** [comment]
> Oh also make sure you've stopped any postgressql service you have running locally. That may prevent the postgres container from starting (since it can't bind to the port) which will then cause the impala container to misbehave.

@gerrymanoim I feel like an idiot right now. I've spent a bunch of time trying to figure out what's going wrong and all this time it was just metasploit's postgres instance running in the background and somehow I didn't see any reference to the port being in use. Will give it a try with metasploit shutdown and report back.

**Comment by gerrymanoim** [comment]
Happy to help - I was lucky enough to be actively working on something that required postgres locally and randomly spotted the message in all the logs.

**Comment by matthewmturner** [comment]
hi @gerrymanoim @ZeroCool2u 
Im looking into #2455 and it looks like one of the issues is due to impala benchmarks not running against impala docker image.  Consequently, I was directed here.  Has there been any progress on this issue?
Thx!

**Comment by datapythonista** [comment]
@jreback do you know why the Impala docker container requires postgres? It doesn't look like the Impala backend should require postgres, not sure if I'm missing something.

Btw, do you have the password of the `ibisproject` user in Docker hub? Or do you know who has it?

**Comment by jreback** [comment]
> @jreback do you know why the Impala docker container requires postgres? It doesn't look like the Impala backend should require postgres, not sure if I'm missing something.
> 
> Btw, do you have the password of the `ibisproject` user in Docker hub? Or do you know who has it?

no idea :-< 

will ping @cpcloud offline

**Comment by jreback** [comment]
@datapythonista what do we need here?

**Comment by datapythonista** [comment]
I need to continue working on #2480, and researching what's the problem connecting to Impala. I managed to make it start, but Ibis was failing to connect. Will be back to that PR after the release.

**Comment by jreback** [comment]
ok I have access to the dockerhub images now, let me add you as well @datapythonista
