### ISSUE TITLE
CI: Make GitHub Actions builds compatible with Windows

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2389]
GitHub actions support executing bash script in Windows. But currently, our bash script to setup the environment doesn't work, because the path to conda is not set correctly for Windows (only for Linux): https://github.com/ibis-project/ibis/blob/master/ci/setup_env.sh#L10 (the conda location is defined in GitHub actions with the env variable `$CONDA` if I'm not wrong).

We should fix the script so it works on Windows, and then we should add `windows-latest` to the build of backends that don't require a docker container: https://github.com/ibis-project/ibis/blob/master/.github/workflows/main.yml#L18

**Comment by zbrookle** [comment]
@datapythonista You may want to look into the Miniconda_setup GitHub action, it can do all of the setup for the Conda environment and it also makes it pretty easy to cache the environment to speed up builds. It's pretty easy to set up and I have it in a lot of my repos so I'd be happy to set that up if it's something you'd like

**Comment by datapythonista** [comment]
I personally find it simple to just have to call a script to set up the environment for every build. Bash is supported by Windows builds on GitHub actions, so I don't think it should be that difficult. But apparently there are some issues with that (not sure which). There is some work to set up the GitHub action in #2408. I'm ok with the action, even if I think it's more verbose, since it has a decent amount of parameters, and we still have the call to `setup_env.sh`. Being able to remove the Windows builds from pipelines will be very helpful on keeping the CI stable, so any option is ok, and we can try to simplify things later.

**Comment by zbrookle** [comment]
Ah ok got it, yeah, I know the windows build can actually be added into the matrix on the action so I figured that would simplify this a bit by taking out the possible complexity of building a bash script. Also it looks like that PR actually has windows in the matrix already, so maybe it should be linked to this?

**Comment by datapythonista** [comment]
> so maybe it should be linked to this?

That issue has a `Closes #2389`, they are linked already. :)

Not sure if we'll be able to use a matrix in all cases. If we still want to test mysql/postgres (or other backends) in Windows, I don't think we can use the same approach. GitHub Actions don't implement the `services` (docker containers) in Windows afaik.

**Comment by EdAbati** [comment]
Hi @datapythonista ,
(I am quite new to GitHub Actions but) I had a look at this one:
My idea is that I could add an extra argument when executing `./ci/setup_env.sh` in order to pass the OS name (ubuntu-latest or windows-latest)
An if-else statement in the `setup_env.sh` file will check which OS is executing the script and set the `CONDA_PATH` accordingly. 
(I am also not a Windows user but from [here](https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-Miniconda.ps1) it seems that Conda is in `"C:\Miniconda"`.)

Is it what you had in mind?

**Comment by datapythonista** [comment]
Yes, that sounds right. Just couple of small comments. I think GitHub actions has an environment variable pointing where conda is available. I think in Windows and Linux it's not the same subdirectories that need to be added to the `PATH`, there are subdirectories `bin` and `Scripts` if I'm not wrong, and executables are in different places. Also, not sure how in Windows you add things to the `PATH` in a bash script, I don't think adding them to the `PATH` variable is the way like in Linux.

For the `if`, that makes sense, but no need to pass an argument to `setup_env.sh`, there are ways (like `uname`) to know in which OS are you in from within the script.

You'll see as you make the changes, but your general idea sounds good.

**Comment by EdAbati** [comment]
Ok Thanks! :) I will give it a try.
Very basic question: is there a way to test GitHub Actions before submitting a PR? is there any best practise?

**Comment by datapythonista** [comment]
You could run it in your fork by just opening the PR against your fork master, instead of the main repo master. You can also remove the builds and steps you don't need if you are going to do lots of tests. But it's fine to open a normal PR and keep testing here. If you do that you can prefix the title with `WIP` so we know it's not yet ready.
