### ISSUE TITLE
ci: benchmarks don't fail the CI when asv crashes

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2403]
See for example this: https://github.com/ibis-project/ibis/runs/1128924525?check_suite_focus=true#step:10:67

For some reason, asv doesn't seem to exit with an exit code different than 0 when something goes wrong. Ideally we'd like to contribute a patch to asv, so they fix it for everybody.

But in the meantime, we may want to fix it in our end, with the same approach as pandas: https://github.com/pandas-dev/pandas/blob/master/.github/workflows/ci.yml#L86

**Comment by gerrymanoim** [comment]
Apologies if I'm missing something, but looking at https://github.com/airspeed-velocity/asv/pull/865, that seems to be what `--strict` should do?

**Comment by datapythonista** [comment]
Thanks for having a look @gerrymanoim, I think that's exactly what we need. We've got a sprint next week, this seems like a great good first issue (even if we'll have to fix the failures first).

**Comment by gerrymanoim** [comment]
Ah - looks like that hasn't been released yet, the last release (v0.4.2) is from May.

**Comment by cpcloud** [comment]
Actually, if we're not using `--strict` that should be really easy to add

**Comment by cpcloud** [comment]
After some discussion, it seems like asv is abandoned and we're going to look into other alternatives for benchmarking like `pytest-benchmark`.

**Comment by cpcloud** [comment]
xref https://github.com/airspeed-velocity/asv/issues/982

**Comment by cpcloud** [comment]
Sorry for the issue noise!

**Comment by jreback** [comment]
note that @datapythonista is working with a group to refresh asv

**Comment by datapythonista** [comment]
Yep, no opinion on whether it could be a good idea to consider pytest-benchmark anyway, but we've got a grant to have two people working in asv part time for two months, and I expect asv will be in good shape and maintained soon.
