### ISSUE TITLE
fix bigquery version

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#2413]
https://dev.azure.com/ibis-project/ibis/_build/results?buildId=3396&view=logs&j=8f09edc2-e3b7-52de-126a-0225c4f3efa1&t=78a72aec-b398-558e-7c0d-2d33604b9e53

I think we need to limit the upper bound of bigquery library here.

**Comment by jreback** [comment]
cc @tswast (IIRC you just did this for pandas-gbq)

**Comment by tswast** [comment]
Yes, `google-cloud-bigquery` 2.0 made some breaking changes in the `google.cloud.bigquery_v2` package, though I wasn't expecting the stacktrace you've linked to. It appears there are incompatible versions of protobuf.

Makes sense to add an upper bound / pin on BQ in at least the test sessions that use any version of pandas-gbq older than the version 0.13.3 that I released yesterday.
