### ISSUE TITLE
bug: filters not applied to joined tables

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2427]
Given, two tables, if they are joined, and then a filter is applied, the filter is actually being ignored:

```python
import ibis

ibis.options.interactive = True

connection = ibis.sqlite.connect('data/geography.db')
countries = connection.table('countries')
gdp = connection.table('gdp')

expr = (countries.inner_join(gdp,
                             predicates=countries['iso_alpha3'] == gdp['country_code'])
                 .filter(gdp['year'] == 2017))
expr
```
Intuitively, the result should only contain the rows with `year == 2017`, but the filter is not applied.

The database in this example can be found at: https://github.com/datapythonista/ibis/tree/tutorial/docs/source/tutorial/data

The SQL compiled from the expression, can be obtained with:
```python
>>> str(expr.compile())
SELECT t0.iso_alpha2, t0.iso_alpha3, t0.iso_numeric, t0.fips, t0.name, t0.capital, t0.area_km2, t0.population, t0.continent, t0.country_code, t0.year, t0.value 
FROM (SELECT t1.iso_alpha2 AS iso_alpha2, t1.iso_alpha3 AS iso_alpha3, t1.iso_numeric AS iso_numeric, t1.fips AS fips, t1.name AS name, t1.capital AS capital, t1.area_km2 AS area_km2, t1.population AS population, t1.continent AS continent, t2.country_code AS country_code, t2.year AS year, t2.value AS value 
FROM base.countries AS t1 JOIN base.gdp AS t2 ON t1.iso_alpha3 = t2.country_code) AS t0, base.gdp 
WHERE base.gdp.year = ?
```

**Comment by cacrespo** [comment]
Hola! Me gustaría tomar este issue. No estoy seguro de poder resolverlo pero quiero intentarlo 😋

**Comment by datapythonista** [comment]
Thanks @cacrespo, feel free to give it a try.

**Comment by cacrespo** [comment]
I have not been able to fix it. 😞 
So I'll let someone with more experience take it.

**Comment by matthewmturner** [comment]
I'm interested in this.

@cacrespo anything you can share about your approach or what you found?

**Comment by matthewmturner** [comment]
from what i see i get the correct results when updating `WHERE base.gdp.year = ?` to `WHERE t0.year = ?`

im not too familiar with internals of sql execution. but from looking at the expr tree...are filters applied on the inner join (i.e. the `WHERE` should pick up gdp.year or on the materializedjoin where it would be t0).  if the latter i would think that means the SQL is compiling incorrectly and the gdp["year"] == 2017 predicate should be converted to `t0` in SQL.  if not that...then ill need to dig further.

will dig more into this.

**Comment by datapythonista** [comment]
No idea how that part works in detail unfortunately. You'll have to check the code.

**Comment by matthewmturner** [comment]
Just to confirm - should the code work the way that you had it? i.e.
```
connection = ibis.sqlite.connect('data/geography.db')
countries = connection.table('countries')
gdp = connection.table('gdp')

expr = (countries.inner_join(gdp,
                             predicates=countries['iso_alpha3'] == gdp['country_code'])
                 .filter(gdp['year'] == 2017))
```

I was reviewing the documentation (http://ibis-project.org/docs/tutorial/02-Aggregates-Joins.html) and came across the same scenario implemented as follows:

```
gdp_2017 = gdp.filter(gdp['year'] == 2017)
countries_and_gdp = countries.inner_join(gdp_2017,
                                         predicates=countries['iso_alpha3'] == gdp_2017['country_code'])
```

So im just trying to confirm that being able to apply a filter after a join is done on one of the original tables is actually expected behavior. 

Separately i tried the following as i thought it might have been an alternative but got an error:

```
expr = countries.inner_join(gdp, predicates=countries["iso_alpha3"] == gdp["country_code"])
expr.filter(expr["year"]==2017)
````
Generates the following error.
```
IbisError: Table operation is not yet materialized
```

**Comment by datapythonista** [comment]
I wrote that tutorial recently, and I implemented it that way because I faced this issue. I think the example in this issue should apply the filter.

Materialization is a bit tricky, I think filtering before materializing should be possible. If it's not, then making the example work may be a feature, and the bug is that no error is being reported in the issue example.

**Comment by matthewmturner** [comment]
thx for clarification. makes sense.  will look into it further.

this one will likely take more time as i try to understand internals / expressions.  when is next release / did you want this included?

**Comment by datapythonista** [comment]
I would like to release after finishing the refactoring of the backends. Whenever that happens, but I think it'll probably be in one week or two. If this is implemented by then it can surely be released, but I don't see this as a blocker.

**Comment by matthewmturner** [comment]
i got the expected results when doing the following:

```
connection = ibis.sqlite.connect('data/geography.db')
countries = connection.table('countries')
gdp = connection.table('gdp')

expr = (countries.inner_join(gdp,
                             predicates=countries['iso_alpha3'] == gdp['country_code']))

expr[countries, gdp].filter(gdp['year'] == 2017)
```

The sql for this `str(expr[countries, gdp].filter(gdp['year'] == 2017).compile())`


```
SELECT t0.iso_alpha2, t0.iso_alpha3, t0.iso_numeric, t0.fips, t0.name, t0.capital, t0.area_km2, t0.population, t0.continent, t1.country_code, t1.year, t1.value 
FROM base.countries AS t0 
JOIN base.gdp AS t1 
ON t0.iso_alpha3 = t1.country_code 
WHERE t1.year = ?
```

Does it make sense that `expr[countries, gdp]` would be required before `.filter()` in order to make it work?

**Comment by datapythonista** [comment]
I think specifying the columns materialize the join, so the behavior makes kind of sense, but I don't think it's the one we want. The filter shouldn't be ignored, if there is any reason why it can be applied an exception should be raised.

But unless there are repeated columns or any other reason for the operation to not be able to be executed, I think the code in the issue description should work in the expected way (applying the filter).

Thanks a lot for having a look at this.

**Comment by matthewmturner** [comment]
Ok. Im going to take a shot in the dark at this.  First guess is to see if i can figure out why the `WHERE` in the sql in the issue description is on `base.gdp.year` instead of `t1.year`.  My assumption being that since the filter is applied after the join, and the filter is using a table from the join, that it should have mapped to the joined table (`t1`).

Does this sound reasonable?

**Comment by datapythonista** [comment]
> Does this sound reasonable?

Not so familiar with that code to know, but sound reasonable to me.

**Comment by matthewmturner** [comment]
was thinking about this more after your description from #2485 .  Since sqlite uses sqlalchemy compiler does that mean in theory i should be able to reproduce this error with pure sqlalchemy?

**Comment by datapythonista** [comment]
> was thinking about this more after your description from #2485 . Since sqlite uses sqlalchemy compiler does that mean in theory i should be able to reproduce this error with pure sqlalchemy?

I'm not familiar enough with that code to know exactly. But my guess is that you are right. I guess the fix is probably changing how we call sqlalchemy (I doubt the error is in sqlalchemy).

**Comment by matthewmturner** [comment]
Ive tried tracing back through the different methods for how this compiles and ive been reading the docs to try to understand the internals better but still struggling to determine tangible location of error.

Any guidance on this would be much appreciated.

**Comment by cpcloud** [comment]
This is definitely a bug.

The workaround in this case is to project out all the columns from each table and then filter, or to filter inside the join predicate and then project out what you need.

Solution 1:

```python
import ibis

connection = ibis.sqlite.connect("docs/source/tutorial/data/geography.db")
countries = connection.table("countries")
gdp = connection.table("gdp")

expr = countries.inner_join(
    gdp,
    predicates=[countries["iso_alpha3"] == gdp["country_code"], gdp["year"] == 2017],
)[countries, gdp]
```

Solution 2:

```python
import ibis

connection = ibis.sqlite.connect("docs/source/tutorial/data/geography.db")
countries = connection.table("countries")
gdp = connection.table("gdp")

expr = countries.inner_join(
    gdp, predicates=countries["iso_alpha3"] == gdp["country_code"]
)[countries, gdp].filter(lambda t: t["year"] == 2017)
```

**Comment by cpcloud** [comment]
A third alternative is to call `materialize` in the filter:

```python
import ibis

connection = ibis.sqlite.connect("docs/source/tutorial/data/geography.db")
countries = connection.table("countries")
gdp = connection.table("gdp")

expr = countries.inner_join(
    gdp, predicates=countries["iso_alpha3"] == gdp["country_code"]
).filter(lambda t: t.materialize()["year"] == 2017)
```

**Comment by cpcloud** [comment]
We are planning to get rid of `materalize` entirely in an upcoming release, it's a really confusing and non-obvious API.
