### ISSUE TITLE
Clean up potentially unreachable code in Window.agg (Pandas backend)

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2438]
There is logic in `Window.agg` (in the Pandas backend) that I believe is unreachable:
https://github.com/ibis-project/ibis/blob/master/ibis/pandas/aggcontext.py#L459-L483

If `group_by` and `order_by` are both `None`, then a `Window` aggcontext **should not exist in the first place** because of this upstream logic that creates a `Summarize` aggcontext instead of a `Window` aggcontext:
https://github.com/ibis-project/ibis/blob/4fc17ab801b8d1b0b02a25551b4753247d837dfd/ibis/pandas/execution/window.py#L132-L133

It is definitely not reached by the tests, so possibly contains bugs.

We need to:
1. Determine whether it really is unreachable or not
2. If reachable, add tests for it and possibly fix broken logic
3. If unreachable, remove

**Comment by cpcloud** [comment]
This is logic that was split out into `Summarize` and `Transform` but never deleted. PR inbound.
