### ISSUE TITLE
DEPS: Increase minimum pandas version and remove old compatibility functionality

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2454]
xref: https://github.com/ibis-project/ibis/pull/2450/files#r500471390

We are currently [supporting pandas 0.21+](https://github.com/ibis-project/ibis/blob/master/requirements.txt#L3), which was released in 2017. And we've got some functionality to support moved APIs in `ibis/compat.py`. We can increase the version of pandas, so that compatibility stuff is not needed anymore. Not sure what version of pandas is the minimum that has the new API that doesn't require that compat stuff, but that would be a good one to require as minimum.

**Comment by EdAbati** [comment]
Hi @datapythonista ,

I did some digging and (if I understood correctly) it seems that all those functions and classes were moved in the current location in version 0.20:
 - `pandas.tseries.tools.to_datetime` and `to_time` were moved to `pandas.core.tools.datetimes` in https://github.com/pandas-dev/pandas/pull/16040
- `pandas.types.dtypes.CategoricalDtype`, `DatetimeTZDtype` and `infer_dtype` were moved in https://github.com/pandas-dev/pandas/pull/16099 and https://github.com/pandas-dev/pandas/pull/16023

So I think we can just delete those lines in `ibis/compat.py` without increasing the minimum pandas version. What do you think?

**Comment by jreback** [comment]
yep sounds right
