### ISSUE TITLE
BENCH: cleanup errors around benchmarks

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#2455]
we are showing some errors in the benchmark suite: https://github.com/ibis-project/ibis/pull/2451/checks?check_run_id=1220781799

would be nice to have these run fully w/o errors.

**Comment by datapythonista** [comment]
asv doesn't fail when there are exceptions, see #2403

**Comment by matthewmturner** [comment]
I've been looking into this. Quick question - should I be able to replicate the errors that occur during benchmarking locally with asv? I'm not familiar with asv so I'm looking into both how that works and the ibis implementation. 

Thanks!

**Comment by datapythonista** [comment]
You can install asv with `pip install asv` and simply run:
```python
asv machine --yes && asv dev
```

**Comment by matthewmturner** [comment]
Thanks @datapythonista

For the impala compile errors I think it's due to there being ImportError of ibis.impala.api because impyla is missing. 

Would we add impyla as dependency for benchmarking or is there another approach?

**Comment by matthewmturner** [comment]
For the PandasBackend errors it looks like the functions low_card_grouped_rolling_udf and high_card_grouped_rolling_udf weren't implemented in the PandasBackend class. 

Do they simply need to be implemented, if so what type of function should be implemented? Or is there something else going on?

Thanks!

**Comment by datapythonista** [comment]
> Would we add impyla as dependency for benchmarking or is there another approach?

If the benchmarks are testing against impala, then we can't get them working until #2388 is fixed. The benchmarks job is not using the impala docker image, and can't use it until that problem is fixed.

**Comment by matthewmturner** [comment]
Okay looks like there are people working on that already - will check in there.  What about for the pandas backend errors i referenced above? Do `low_card_grouped_rolling_udf` and `high_card_grouped_rolling_udf` need to be implemented?

thx!

**Comment by datapythonista** [comment]
> Do `low_card_grouped_rolling_udf` and `high_card_grouped_rolling_udf` need to be implemented?

Not as part of this issue I would say. Not so familiar with those functions, but if they are not implemented for the pandas backend, I'd simply have an `if` to not run them for that backend. May be @jreback has more info on why that is failing.

**Comment by matthewmturner** [comment]
@jreback checking on the above.  do you have preference for adding those functions (`low_card_grouped_rolling_udf` and `high_card_grouped_rolling_udf` to pandas backend vs simply not running them?

**Comment by jreback** [comment]
ideally running them
