### ISSUE TITLE
FEAT: Adjust context properly for mixed rolling window, cumulative window and non window ops for pyspark backend

### ISSUE THREAD

**Issue by LeeTZ** [ibis-project/ibis#2457]
Overview
=======
With context adjustment implemented, the time context will be adjusted accordingly for every op. User may mix rolling window (adjust time context), cumulative window(doesn't adjust time context), and non-window ops (doesn't adjust time context) in one single `mutate` operation.  

We should make sure:
 1. The sematic and the behavior is well-defined.
 2. The results are the same for every backend (pandas vs pyspark).

Example
======
Consider the following case: 

We have a table of 
```
time       value
2020-01-01   a
2020-01-02   b
2020-01-03   c
2020-01-04   d
```
with `context = (2020-01-02, 2002-01-04)`, we calculate a 1-day rolling window, and a cumulative window for `count()`

In the current implementation, the result is:
```
time       value  roll_count  cumulative_count
2020-01-02   b      2            2
2020-01-03   c      2            3
2020-01-04   d      2            4
```
Cumulative start from 2 instead of 1, because the rolling window has extended the time context to be one day more ahead. Then cumulative count is counting on a 4-row table, instead of 3.

However, if we run cumulative separately on this table, with same context `context = (2020-01-02, 2002-01-04)`, we got:
```
time       value  cumulative_count 
2020-01-02   b      1            
2020-01-03   c      2            
2020-01-04   d      3            
```
Which is the expected behavior, and this matches the result for pandas backend.  Similar examples apply to non-window ops that don't adjust time context.

Suggested Fix
=======
For non-window ops and cumulative windows that doesn't adjust time context, we should calculate on user context, instead of the extended one. There shouldn't be a change in result if we run the cumulative window alone vs run the cumulative window together with a rolling window.

**Comment by cpcloud** [comment]
Sounds like you have a really good idea about how to go about fixing this. PRs welcome!
