### ISSUE TITLE
ibis.postgres table expressions dont recognize macaddr datatype

### ISSUE THREAD

**Issue by esamuel1** [ibis-project/ibis#2461]
Impacts ibis 1.3.0

Ibis doesn't appear to recognize macaddr data types in postgres when trying to build an ibis table expression. A simple reproduction of the issue is below:

```
pgcon = ibis.postgres.connect(
    database=database,
    host=host,
    user=user,
    password=password,
    port=port
)

tblnm='mactbl'
mactbl='''
create table if not exists {} (
sometime timestamp,amac macaddr);
'''.format(tblnm)
pgcon.raw_sql(mactbl)
mactblexp=pgcon.table(tblnm)
```

```
NotImplementedError: Could not find signature for dtype: <PGDialect_psycopg2, MACADDR>
```

Looking at the sqlalchemy docs, it seems they do support macaddr for postgres.

**Comment by datapythonista** [comment]
Thanks for the report @esamuel1, I don't think this should be difficult to add. If you want to have a look at the code, and try to submit a pull request, that would be great.
