### ISSUE TITLE
Move Impala operation registry to base_sql backend

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2463]
For historical reasons, some code shared among backends live in the Impala backend. An important part of the shared code has been moved to a new `base_sql` backend in #2449.

What is pending to move in a similar way is the operation registry (and its dependencies). Each backend has a registry of the operations it defines. And many backends are using the [impala one](https://github.com/ibis-project/ibis/blob/master/ibis/impala/compiler.py#L1044) to then overwrite what it's different.

What we should do is to move the common operations to `base_sql`. The registry dictionary, and also the functions that define the operations such as `unary`, `reduce`... which need to get the heading underscore removed, since they'll become public.. And leave in Impala the operations that are specific to Impala (using the moved registry as a base, as the other backends are doing).

**Comment by matthewmturner** [comment]
this can be closed. sry i didnt link to my PR.

**Comment by datapythonista** [comment]
Closed via #2469
