### ISSUE TITLE
enable MacAddr / INET for pandas backend

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#2465]
note that we can use this package to enable these for pandas: https://cyberpandas.readthedocs.io/en/latest/ (by @TomAugspurger) and uses pandas extension arrays. happy to take a PR for that.

_Originally posted by @jreback in https://github.com/ibis-project/ibis/pull/2464#issuecomment-707385882_

**Comment by cpcloud** [comment]
PRs welcome. No need for an issue.
