### ISSUE TITLE
Move ibis/sql to ibis/backends/base_sqlalchemy

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2466]
We're working on having the backends in a more standardized and structured way. We are finishing moving backends to the `backends/` directory, and moving shared code among backends to `backends/base_*`. The backends based on SQLAlchemy historically lived in `ibis/sql`. We moved them (MySQL move is still not merged at the time of writing this, see #2446), and after all backends are moved, would be good to move the SQLAlchemy shared code from `ibis/sql` to `ibis/backends/base_sqlalchemy`.

**Comment by renato2099** [comment]
hey @datapythonista  I made this change in https://github.com/ibis-project/ibis/pull/2468 but I am unsure how to run test to verify that the change didn't break anything, I'd appreciate any suggestions :) thanks!
