### ISSUE TITLE
Avoid repetitive code among backends

### ISSUE THREAD

**Issue by matthewmturner** [ibis-project/ibis#2475]
Some functions seem to be very similar accross backends:

base_sql
```
def fixed_arity(func_name, arity):
    def formatter(translator, expr):
        op = expr.op()
        if arity != len(op.args):
            raise com.IbisError('incorrect number of args')
        return format_call(translator, func_name, *op.args)

    return formatter
```

clickhouse
```
def fixed_arity(func_name, arity):
    def formatter(translator, expr):
        op = expr.op()
        arg_count = len(op.args)
        if arity != arg_count:
            msg = 'Incorrect number of args {0} instead of {1}'
            raise com.UnsupportedOperationError(msg.format(arg_count, arity))
        return _call(translator, func_name, *op.args)

    return formatter
```

Originally, many backends were build on top of the Impala backend. And the ones that didn't, like clickhouse, seem to have copied code from it. We are now moving the code reused from backends to a base backend `base_sql` and `base_sqlalchemy` mainly. Once that is done, would be good to not have code repeated among backends, like the example, and instead have the common functionality in the base backends, and import from the others.

xref https://github.com/ibis-project/ibis/pull/2472#issuecomment-710302802_

**Comment by cpcloud** [comment]
PRs welcome.
