### ISSUE TITLE
Consider changing get_name to return None instead of throwing exception for unnamed expressions

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis#2484]
As part of https://github.com/ibis-project/ibis/pull/2473, we noticed any if/else code needs to be added when extracting names from a list of expressions because `get_name()` currently throws exception for unnamed expressions.

We should consider changing the behavior of `get_name()` to simply the code.

**Comment by cpcloud** [comment]
PRs welcome. No need to keep an issue open for over a year for this though.
