### ISSUE TITLE
BUG: Add support for pandas new StringDtype

### ISSUE THREAD

**Issue by ZeroCool2u** [ibis-project/ibis#2488]
As of v1.3 Impala does not yet support the new pandas StringDtype. This is problematic, because for pandas versions > ~1.0, DataFrame.convert_types() will cast strings to this datatype and cause upload/insertion failures.

**Comment by ZeroCool2u** [comment]
Note for anyone else encountering this issue, you can still use `DataFrame.convert_types()` and side step this issue like this 

```python
import pandas as pd

df = pd.DataFrame()

df = df.convert_types(convert_string=False)
```

**Comment by datapythonista** [comment]
Is it Impyla that doesn't support the string dtype? I guess we can use `convert_string=False` for now to fix the bug.

**Comment by ZeroCool2u** [comment]
That's a good question. I believe it's on our end, because Ibis is throwing the error. Also, from what I can tell, the only pandas related code in Impyla is just converting the impala response to a dataframe, which is just a few lines. 

Here's the [documentation for the introduction of the new Pandas StringDtype](https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html), which is considered experimental, but it doesn't seem like it's going anywhere. There is also StringArray, which we should anticipate. 

I think to get this fixed we'd need to:
1. Update the inferable datatypes mapping.
2. Update the schema inference function. 
3. Add a new example to the pandas 'exhaustive_dataframe' wherever it shows up, because it's not so exhaustive now. There's actually quite a few tests that involve inferring the schema and converting to/from datatypes, so this will not be a small amount of work. 

I think 1 and 2 can be accomplished mostly by changes to the [pandas client](https://github.com/ibis-project/ibis/blob/5e4da1e4da/ibis/backends/pandas/client.py) object. The

**Comment by cpcloud** [comment]
It'd be real swell if we could move to a DataFrame composed entirely of extension dtypes with proper null support.

I think a lot of this will be covered in our upcoming epics to make the result type configurable, possibly defaulting to something more sane than a pandas DataFrame.
