### ISSUE TITLE
Conda solver taking too long 

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2489]
xref: https://github.com/ibis-project/ibis/pull/2476#issuecomment-714429790

Looks like the conda package build is taking too long (2 hours in some cases).

That build is installing all the dependencies of all the backends, which seem to be causing the problem. `pymapd` has been in the past the main source of conda solving time, so #2356 (moving omnisci to a separate repo should help). Also, for that particular build, #2448 (have independent conda packages for each backend) should fix the problem.

As a more immediate solution, #2486 (bumping `pymapd` version) seems to be decreasing the solver time significantly.

**Comment by matthewmturner** [comment]
@datapythonista @jreback tying back to the issues on #2435 with CI / conda.

I can make a PR for this if youd like.  I assume we would be removing some of the run requirements form `ci/recipe/meta.yaml`.  If thats the case do you already have in mind what should be removed?

**Comment by jreback** [comment]
yes remove spark omnisc impala bigquery

**Comment by datapythonista** [comment]
Can we release next week with all backends for the last time, and soon after release with the entry points, and each backend separately (with omnisci in a separate repo, and maybe others)?

I think having separate conda packages that work and that don't work with entrypoints will make things complicated.

**Comment by datapythonista** [comment]
Superseded by #2670
