### ISSUE TITLE
bug: fix set_value behavior for scope when timecontext is None

### ISSUE THREAD

**Issue by LeeTZ** [ibis-project/ibis#2490]
What is the Problem
=============
When `timecontext` is `None`, `set_value` method of scope will not override and set value.

Currently in `set_value` :
```
    def set_value(
        self, op: Node, timecontext: Optional[TimeContext], value: Any
    ) -> None:
        if self.get_value(op, timecontext) is None:
            self._items[op] = ScopeItem(timecontext, value)
```
While when `timecontext` is `None` and if `op` is already in `scope`,  `self.get_value(op, timecontext)` will return the value stored in `scope`, which is not `None` probably. Then `set_value` will not update `scope`.

The correct behavior when `timecontext` is `None`, is to overwrite whatever already in `scope`.

**Comment by cpcloud** [comment]
@LeeTZ We'd happily accept a PR! Do you have a test case for this that you can paste here?

**Comment by cpcloud** [comment]
Closing. Please reopen if it's still a problem.
