### ISSUE TITLE
refactor: remove coerce_to_dataframe from execute_udaf_node_groupby in pandas backend

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis#2496]
In https://github.com/ibis-project/ibis/pull/2487, we added a this to execute_udaf_node_groupby to coerce the output to the right shapes when executing struct UDF, however, this is not great because this does similar things to `pandas.execution.util.coerce_to_output` but we cannot use `pandas.execution.util.coerce_to_output` because we are in the inner loop. (`pandas.execution.util.coerce_to_output` only works after getting the result from inner loop).

Would be nice to clean this up and conform to a single coercion function.

**Comment by cpcloud** [comment]
PRs welcome! We're trying to keep the issue backlog tidy, so going to close this out. Feel free to submit refactors as PRs directly.
