### ISSUE TITLE
Improve tests for pandas rank based/window functions

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2502]
As pandas is used to check the other backends results, it would be good to add tests for rank based and window functions for pandas that compares with fixed results. 

Follow-up of https://github.com/ibis-project/ibis/pull/2224/files#r514197533

ref: https://github.com/ibis-project/ibis/blob/master/ibis/backends/pandas/tests/execution/test_window.py

**Comment by cpcloud** [comment]
PRs welcome
