### ISSUE TITLE
Move base_sql functionality that inherits from base_sqlalchemy

### ISSUE THREAD

**Issue by matthewmturner** [ibis-project/ibis#2503]
Not in this PR, but feels like it could make sense to move these few methods and attributes to their parent classes in base_sqlalchemy, and just use those. If you think this can make sense and is worth having a look, can you create an issue for it please?

_Originally posted by @datapythonista in https://github.com/ibis-project/ibis/pull/2501#discussion_r514599759_

**Comment by datapythonista** [comment]
`base_sql` doesn't exist anymore, this is fixed.
