### ISSUE TITLE
broken link to tutorials

### ISSUE THREAD

**Issue by olszewskip** [ibis-project/ibis#2504]
Hi!
The link to tutorials at the bottom of https://ibis-project.org/getting_started.html
takes me to 404 under https://hub.gke2.mybinder.org/user/ibis-project-ibis-tr9c47u4/tree/docs/source/notebooks/tutorial

**Comment by datapythonista** [comment]
Thanks a lot for letting us know @olszewskip. If you want to submit a contribution to fix it, that would be great. You have documentation on how to contribute here: https://ibis-project.org/contribute.html

**Comment by olszewskip** [comment]
Thanks for letting me in on the process, @datapythonista! I've never done anything like that before, but here I go trying
/take
I'm going to assume, that swapping the broken link to binder for one to the tutorial section in the documentation would be helpful.
