### ISSUE TITLE
FEAT: support SipHash as "how" type for support in pandas backend

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#2512]
Pandas supports hashes that output int64 values (corresponding to the hash function) https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.util.hash_pandas_object.html?highlight=hash#pandas.util.hash_pandas_object

This appears to be implemented as a version of the SipHash algorithm.

https://github.com/pandas-dev/pandas/blob/de9c771e0bcea5119a7a69f331cd3d6c5bc4a5be/pandas/_libs/hashing.pyx#L149

Follow-up to #2508

**Comment by cpcloud** [comment]
Happy to investigate this, but need more clarify on the use case.
