### ISSUE TITLE
Update milestones

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2525]
We currently have several milestone in GitHub (next major release, next bugfix release, next feature release...).

Afaik we're not using them, just one for the next release. I'd prefer to just have a milestone `Next release` for now, get rid of the rest, so we can label what we'd like to see in the next release. If in the future we start doing major, minor... we can add them back as needed.

@jreback ok with this?

**Comment by jreback** [comment]
yep that's fine

**Comment by datapythonista** [comment]
Thanks, updated.
