### ISSUE TITLE
Create external table workflow on Parquet file partitioned in the style of Impala

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#253]
See, for example the `alltypes_parquet` directory in the Impala test-warehouse, which is partitioned by year and month. It might not be possible or desirable to try to "discover" the partition schema, but if the user indicates a partition schema in the `create_table` call, we should find a parquet file, infer the schema, and issue the right `CREATE EXTERNAL TABLE` DDL.

**Comment by cpcloud** [comment]
Closing as needs a use case and/or PR.
