### ISSUE TITLE
question: how to create / insert into ibis tables from a Pandas dataframe?

### ISSUE THREAD

**Issue by Hoeze** [ibis-project/ibis#2546]
Hi, I just tried out ibis because it seemed to be an easy-to-use and fast interface to SQL databases.

I am especially interested in SQLite, Postgres and Omniscidb.
However, I could not find out how to write my Pandas dataframes into those databases with Ibis.

As it seems, Impala is the only database backend with some insert method.
Is this true?

**Comment by tswast** [comment]
https://github.com/ibis-project/ibis/issues/2613 has been created to implement `insert()` for SQLite.

**Comment by raheems** [comment]
Bumped into writing a table to postgres backend-- any solutions available yet? Thanks.

**Comment by cpcloud** [comment]
You can do this with the `Backend.insert` method. If the method isn't implemented, PRs are welcome!
