### ISSUE TITLE
CLN: Remove or consolidate dev dependencies from setup.py and environment.yml

### ISSUE THREAD

**Issue by mroeschke** [ibis-project/ibis#2549]
I noticed in https://github.com/ibis-project/ibis/pull/2547#issue-529169508 that the dev dependencies are not in sync in https://github.com/ibis-project/ibis/blob/master/setup.py#L63 and https://github.com/ibis-project/ibis/blob/master/environment.yml#L24

`environment.yml` looks more up to date; the dev dependencies in `setup.py` should either be synced with that file or just removed.

**Comment by datapythonista** [comment]
@jreback do you want to keep `ibis[dev]`? I'm not sure if it's useful (surely not to me), I'd simply get rid of that, and use conda and `environment.yml` for setting up the development environment.

**Comment by jreback** [comment]
yeah we should get rid of this and use environment.yml
