### ISSUE TITLE
Doc links e.g. http://ibis-project.org/api.html return 404

### ISSUE THREAD

**Issue by ohtrahddis** [ibis-project/ibis#2559]
Any ibis doc links return 404, e.g. http://ibis-project.org/api.html

![image](https://user-images.githubusercontent.com/1168930/101129879-48b46000-35b7-11eb-8495-69287bb6285c.png)
12-03-2020

Might be related to https://github.com/ibis-project/ibis/issues/2555

**Comment by niviksha** [comment]
Yes, facing the same since this morning

**Comment by ohtrahddis** [comment]
Looks like its fixed now! thanks 
![image](https://user-images.githubusercontent.com/1168930/101232577-43aee980-3667-11eb-861e-8435ae73971d.png)
