### ISSUE TITLE
String built-in function blitz

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#256]
Expand coverage of Impala built-ins on string types. Track here
- [x] instr
- [x] locate
- [x] space
- [x] trim
- [x] regex_extract
- [x] regex_replace
- [x] ascii
- [x] concat_ws
- [x] concat
- [x] find_in_set
- [x] lpad / rpad
- [x] ltrim / rtrim
- [x] repeat
- [x] reverse
- [x] translate

**Comment by pteehan** [comment]
Hello, I'm looking for concat() in Ibis and the only reference I have found is this issue.  Has this been implemented?

**Comment by tdhopper** [comment]
@pteehan Pretty sure not.

**Comment by wesm** [comment]
@pteehan try `sep.join([e1, e2, e3])`, e.g.

```
comma = ibis.literal(',')
comma.join(['foo', 'bar', 'baz'])
```

this compiles to

```
concat_ws(',', 'foo', 'bar', 'baz')
```

**Comment by pteehan** [comment]
Great, thank you.
