### ISSUE TITLE
refactor: merge testing round and comparing classes into the main backend testing class

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2564]
The methods of the classes `RoundAwayFromZero`, `RoundHalfToEven` and `UnorderedComparator` can be merged into the `Backend` class, and then implement an attribute to select which method to use, for example:

```
class Spark(Backend):
    round_method = 'half_to_even'
```

This would make things simpler, than the current mixin approach.

**Comment by cpcloud** [comment]
Sure, PRs welcome.
