### ISSUE TITLE
bug: key error using sort by on pandas backend

### ISSUE THREAD

**Issue by zbrookle** [ibis-project/ibis#2569]
```python
ibis_table = table[[table.col1]].sort_by(
        [
            (table.col2, False),
            (table.col3, True),
        ]
    )

ibis_table.execute()
```

This results in a 'KeyError' on the pandas backend, presumably because the selection is occurring, which removes col2 and col3. However, since ibis is supposed to be SQL-like this should still work. A potential work around would be to add columns back into the table to sort if they're not present, and then remove them. (Also I'd be happy to take this issue)

**Comment by jreback** [comment]
yeah this should raise as the columns acted don't exist

i am not sure that this should be fixed as it's simple to just include the missing columns

**Comment by zbrookle** [comment]
@jreback In SQL, you can do

```SQL
select col1 order by col2
```

without including the column in the initial selection. I guess that's my point as to why I would think you'd be able to do that here

**Comment by jreback** [comment]
what happens when u execute and the column actually doesn't exist? this is just failing fast

**Comment by zbrookle** [comment]
If the column doesn't exist then the job would fail when it's retrieving the columns in the order by clause

**Comment by cpcloud** [comment]
This is a legitimate bug. You should definitely be able to sort by columns that aren't in the final projection.
