### ISSUE TITLE
TST: ibis/backends/tests not running in CI

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#2572]
Apologies if I've missed something, but I don't believe that tests under `ibis/backends/tests` are running after the merge of https://github.com/ibis-project/ibis/pull/2566. I believe that https://github.com/ibis-project/ibis/blob/master/ci/run_tests.sh#L6 needs to be updated to account for the new directory structure.

**Comment by jreback** [comment]
https://github.com/ibis-project/ibis/runs/1540361930?check_suite_focus=true is the latest run on master, what is supposed to be running that is not? e.g. i see tests/expr/* running.

**Comment by gerrymanoim** [comment]
I believe we're missing all of https://github.com/ibis-project/ibis/tree/master/ibis/backends/tests, but I might be just misunderstanding how this all works now.

**Comment by datapythonista** [comment]
Thanks for catching this @gerrymanoim, not sure why I had in mind that all tests in `ibis/backends` were being called, my bad. Opened #2573.
