### ISSUE TITLE
CI: LinuxBuildDocs failing

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2578]
LinuxBuildDocs is failing for my PR #2577. I've also reproduced the error locally on master.

Most relevant part of the stack trace:
```
...
  File "/opt/conda/envs/ibis-env/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1829, in should_suppress_value_header
    return (self.object == UNINITIALIZED_ATTR or
  File "/ibis/ibis/expr/api.py", line 612, in f
    other = as_value_expr(other)
  File "/ibis/ibis/expr/types.py", line 1265, in as_value_expr
    val = literal(val)
  File "/ibis/ibis/expr/types.py", line 1229, in literal
    'passing it explicitly with the `type` keyword.'.format(value)
TypeError: The datatype of value <object object at 0x7f93e0bbc270> cannot be inferred, try passing it explicitly with the `type` keyword.

Exception occurred:
  File "/ibis/ibis/expr/types.py", line 1229, in literal
    'passing it explicitly with the `type` keyword.'.format(value)
TypeError: The datatype of value <object object at 0x7f93e0bbc270> cannot be inferred, try passing it explicitly with the `type` keyword.
```

You can see the full stack trace in this failing job:
https://dev.azure.com/ibis-project/ibis/_build/results?buildId=3994&view=logs&j=8f09edc2-e3b7-52de-126a-0225c4f3efa1&t=e3ba5a33-21a6-5484-d0be-59baf122f79c

**Comment by timothydijamco** [comment]
I'm currently looking into it. So far, my guess based on the stack trace is that while building the docs, Sphinx is now comparing some Ibis expression(s) to some Sphinx constant `UNINITIALIZED_ATTR`. Ibis tries to create a Literal expression out of `UNINITIALIZED_ATTR` but cannot.

I think this new failure in our CI is triggered by a Sphinx version change.
[Sphinx version in the most recent succeeding docs build:](https://dev.azure.com/ibis-project/ibis/_build/results?buildId=3991&view=logs&j=8f09edc2-e3b7-52de-126a-0225c4f3efa1&t=e3ba5a33-21a6-5484-d0be-59baf122f79c)
```
sphinx                    3.3.1              pyhd8ed1ab_1    conda-forge
```
[Sphinx version in the failing docs build:](https://dev.azure.com/ibis-project/ibis/_build/results?buildId=3994&view=logs&j=8f09edc2-e3b7-52de-126a-0225c4f3efa1&t=e3ba5a33-21a6-5484-d0be-59baf122f79c)
```
sphinx                    3.4.0              pyhd8ed1ab_0    conda-forge
```

**Comment by timothydijamco** [comment]
Fairly sure the above is correct, and this change linked below is what is causing the issue. This is included in Sphinx 3.4.0, which was released a few days ago.
https://github.com/sphinx-doc/sphinx/pull/8500/files#diff-e43bdd6f8f37a12d2536e09e57c5e8999cb8de18b9c7ba49126f90576c4328acR1813

I'll open an issue in Sphinx in a bit

**Comment by jreback** [comment]
this is reported in multiple places already

just ping sphinx for now
3.4.1 should fix

**Comment by timothydijamco** [comment]
The docs build should succeed now that sphinx is pinned

I opened an issue on the sphinx side for the underlying issue (https://github.com/sphinx-doc/sphinx/issues/8583), and we can unpin sphinx once it is resolved
