### ISSUE TITLE
cannot import name 'cfg' from 'config'

### ISSUE THREAD

**Issue by vjamishi** [ibis-project/ibis#2581]
i was trying to import cfg from config in jupyter notebook but it is showing this error: cannot import name 'cfg' from 'config'
<img width="816" alt="Screenshot 2020-12-25 120418(1)" src="https://user-images.githubusercontent.com/30191005/103123276-d44a7980-46a9-11eb-8026-4c0990e59ca3.png">

**Comment by jreback** [comment]
not sure what the has to do with ibis
