### ISSUE TITLE
CI: Failing tests in Windows CI jobs when python-graphviz version is 0.16

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2585]
Recently, our CI jobs had begun using `python-graphviz` version `0.16` rather than `0.15`.

These tests began failing:
```
FAILED ibis/tests/expr/test_interactive.py::TestInteractiveUse::test_repr_png_is_not_none_in_not_interactive
FAILED ibis/tests/expr/test_visualize.py::test_optional_graphviz_repr - Asser...
FAILED ibis/tests/expr/test_visualize.py::test_html_escape - assert None is n...
= 3 failed, 4357 passed, 452 skipped, 229 xfailed, 1 xpassed, 116 warnings in 252.71s (0:04:12)
```
in these CI jobs:
* Tests pandas / files (windows-latest, 3.7)
* Tests pandas / files (windows-latest, 3.8)
* Tests dask (windows-latest, 3.7)
* Tests dask (windows-latest, 3.8)

These tests succeed when pinning `python-graphviz<=0.15` (see #2583)

We'll need to figure out why those tests were failing for `python-graphviz` `0.16` so we can unpin

**Comment by cpcloud** [comment]
We're no longer pinning graphviz.
