### ISSUE TITLE
Use pip instead of conda in the CI?

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2591]
Even after removing OmniSci and pymapd, installing all the backend dependencies takes 30 minutes. I think conda is becoming not very usable, we're already pinning everything massively to reduce the search space. Having to update all the pinning to keep reducing the solver time every few months doesn't seem sustainable.

I'd simply use pip instead of conda. But also open to Mamba or other solutions.

@jreback thoughts?

**Comment by jreback** [comment]
the pinning is itself the problem

do not change to anything else
just revert of the pins

**Comment by datapythonista** [comment]
> the pinning is itself the problem

Will give it a try, but the pinning was introduced to make the solving much faster (and it did when we added them).

**Comment by datapythonista** [comment]
@jreback gave it a try, but several builds double the time they take when removing the pins, see #2592

**Comment by jreback** [comment]
ok you would know better than me, but IIRC there are some options that you can enable in conda to show where time is being spent and why.

**Comment by datapythonista** [comment]
I will have a look, but I'm only aware of the verbose flag that adds a bit of extra information, but not much. In the past I modified conda code to be able to see all candidate dependencies, but that was a significant amount of work, and didn't add as much value as expected.

**Comment by jreback** [comment]
looks ok on master now.
