### ISSUE TITLE
STYLE: add precommit checks

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#2595]
in pandas we have a lot of precommit checks: https://github.com/pandas-dev/pandas/blob/master/.pre-commit-config.yaml

we should at the very least add flake, blacken, mypy here. these make code formatting a snap.

**Comment by jreback** [comment]
cc @MarcoGorelli

**Comment by datapythonista** [comment]
Looks like we already have them: https://github.com/ibis-project/ibis/blob/master/.pre-commit-config.yaml

**Comment by MarcoGorelli** [comment]
Hi - is the suggestion to run them in CI? If so, [here](https://github.com/pandas-dev/pandas/blob/0b16fb308b7808f193a5a8d86d71b6e57d99d4e7/.github/workflows/pre-commit.yml)'s the file which does that

**Comment by datapythonista** [comment]
@jreback can you clarify what do you want here? As I commented, there is a pre-commit config file in Ibis already, not sure if you want to see it being used in the CI as Marco says (I'm -1 on it, but we can discuss after I understand better).

Also, is this a blocker for Ibis 2.0? If it's not I'll remove the "Next release" milestone.

**Comment by MarcoGorelli** [comment]
> I'm -1 on it, but we can discuss after I understand better

Just to make the case for it: it means you can just use one file (`.pre-commit-config.yaml`) to store configurations for all linters/formatters, and then for each tool you include or write you don't need to reinvent recursive / multiprocessing / run-on-tracked-files-only / include / exclude / run-only-on-certain-types

**Comment by datapythonista** [comment]
Not sure I understand. Maybe easier with an example. We use `flake8`, and we have its configuration in `setup.cfg`. Would you move it to the pre-commit file and not use `setup.cfg` then? Can I run `flake8` directly for a single file or the whole project then? For example, would `flake8 ibis/setup.py` use the configuration in the pre-commit yaml file then?

**Comment by MarcoGorelli** [comment]
Sure - look at the [pre-commit-config file in pandas](https://github.com/pandas-dev/pandas/blob/8e0b74401c5c1d28718edef1b142b5a8ea315ea1/.pre-commit-config.yaml), note how to specify which folders, file, and file types to include, we can just use
```yaml
- files:
- exclude:
- types:
- types_or
```
and it's the same for each tool. By default, each tool will only run on tracked files, so you don't need to exclude venv/.venv/build/etc... for each one. And if you make you own local linter, you can just write it so it runs from the root of the repo on a list of files (e.g. [check_for_inconsistent_namespace_usage](https://github.com/pandas-dev/pandas/blob/8e0b74401c5c1d28718edef1b142b5a8ea315ea1/scripts/check_for_inconsistent_pandas_namespace.py)) and list it as a local hook in `.pre-commit-config.yaml`.

Any additional configs you specify e.g. in setup.cfg will continue to be respected

**Comment by datapythonista** [comment]
Thanks for the information, I was misunderstanding. Thought that it would manage the error codes that we are validating in flake8 and things like that.

No strong opinion on whether it makes sense to standardize the skipped files or not, but I don't think in Ibis we should be skipping anything from the linting. I think that the only file that is being skipped for a reason now is `versioneer.py` (opened #2674 to remove unused stuff). And I'm not sure whether using it is a good idea to use versionner (iirc it's unmaintained and there are better alternatives that can be used as a dependency instead of copying the file into the project). And we can fix the issues with the file if we want to keep it.

So, if I'm not misunderstanding anything, I think pre-config fixes a problem that we don't have in Ibis, and I think we better avoid exceptions.

**Comment by jreback** [comment]
are we actually running the precommit checks in the ci? that's what this issue is about. having a single source for running these checks in local development and in CI

**Comment by datapythonista** [comment]
We don't run pre-commit checks in the CI. We just use `black .`, `isort .`...

Happy to learn more about it, but still unsure on what problem do we have that is solved by pre-commit, things are simple and working fine IMHO.

In any case, can we remove the milestone from this, and discuss for the next release? I don't think this is a blocker, and would be nice to focus in the blockers for the next release first. We've got a decent amount: https://github.com/ibis-project/ibis/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Next+release%22

**Comment by jreback** [comment]
exactly the problem

what does a user run? and in which order 

precommit is the one true way

**Comment by datapythonista** [comment]
hehe, the "one true way" sounds a bit radical for a tool that it's clearly a personal preference.

In any case, I'm not arguing, we can surely add a build with precommit if you find it useful. But I don't think this should be a blocker for the next release, and if nobody took care of this when the rest of the tasks in https://github.com/ibis-project/ibis/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Next+release%22 are addressed, we should move forward anyway.

So, please let me know if it's ok to remove the milestone here.

**Comment by datapythonista** [comment]
Cool, removed the milestone. I'll have a look at precommit eventually, I think I'm still missing something if you see the advantages so much and I don't. But I'll focus on the pending stuff for 2.0 for now.
