### ISSUE TITLE
Permission denied Temporary File - From Pandas Dataframe to Impala

### ISSUE THREAD

**Issue by Cesaaar** [ibis-project/ibis#2598]
I get **Permission Denied** error when I try to create an impala table from a Dataframe.

Es. 
df = xxx # Pandas Dataframe
db.create_table('test', df)

I get the problem on line 59 of the pandas_interop.py file
> with tempfile.NamedTemporaryFile() as f:

I solved it this way:
> import os
> ...
> with tempfile.NamedTemporaryFile(delete=False) as f:
>...
>os.unlink(f.name)

Is there a better solution?

**Comment by datapythonista** [comment]
This seems related to #2308. @ZeroCool2u do you mind having a look?

**Comment by ZeroCool2u** [comment]
Sure! @Cesaaar, can you confirm the version of Python you're using and the version of Ibis? This shouldn't happen on Python v3.7 or higher with the current latest release of Ibis.

**Comment by Cesaaar** [comment]
I confirm, Python 3.7 and last ibis

**Comment by Cesaaar** [comment]
The configuration is Python 3.7.9, ibis-framework 1.3.0, on Windows 10

**Comment by ZeroCool2u** [comment]
Gotcha, Ibis v1.30 is the last version released without my bug fix for this issue merged, so if you update to Ibis v1.40 or greater you should be good to go I believe.

**Comment by Cesaaar** [comment]
I upgraded to 1.4 and it worked
