### ISSUE TITLE
Dask backend execute should return a pd.DataFrame/pd.Series

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#2604]
Right now, the daskbackend returns a Dask TaskGraph that then the user should run `compute()` on. 

As mentioned in https://github.com/ibis-project/ibis/pull/2596#discussion_r566183742 this is a bit different from other backends. 

Perhaps we should use `compile` to perform the construction of the dask task graph, and then execute to perform the compute.

Also - when this is fixed, we also need to 

- [ ] remove the `pandas_df` test fixture.

**Comment by gerrymanoim** [comment]
cc @jreback @icexelloss

**Comment by jreback** [comment]
yeah we should separate these steps

the spark backend does it this way as does most (exception is pandas)

**Comment by icexelloss** [comment]
+1 to return pd.DataFrame from dask execute and have another method to return the dd.DataFrame. (compile is fine for this)
