### ISSUE TITLE
Implement .insert() for SQLite

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2613]
Some backends implement the `.insert()` method, to insert rows into tables. SQLite doesn't, and besides being useful for users, it'd be good to have it working, and add an example in the tutorial 5, so it's useful as a reference for other backends too.

**Comment by harsharaj96** [comment]
I have implemented a version of insert for SQLite with similar limitations as the Impala database one and have submitted a pull request [here](https://github.com/ibis-project/ibis/pull/2719). Hope this helps.
