### ISSUE TITLE
np.array support still spotty

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2619]
#2603 enhanced support for `np.array` literals in the Ibis backends. However, I've been doing some more testing with `ArrayColumns` and `ArrayScalars` backed by `np.arrays`, and there are a couple more changes we need to make to have `np.arrays` fully supported.

This is also important because #2615 adds the `ArrayColumn` op, and during execution of that op, the Pandas and Dask backends create a series with `np.arrays` as the elements.

## Expression layer

Checking equality between `np.array` literals (`ArrayScalars`) ❌
```
>>> ibis.literal(np.array([1, 2, 3])).equals(ibis.literal(np.array([1, 2, 3])))
Traceback (most recent call last):
  ...
  ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
This breaks other parts of the API because checking equality between expressions is common.

## Pandas backend

| Operation        | on `ArrayScalars`                     | on `ArrayColumns`   |
| ---------------- | -------------------------------- | ---------------------- |
| `ArrayLength`    | ❌ (dispatch rule incomplete) | ✔️ |
| `ArrayIndex`       | ❌ (dispatch rule incomplete) | ✔️ |
| `ArraySlice`        | ❌ (dispatch rule incomplete) | ✔️ |
| `ArrayConcat`    | ❌ (expression creation fails)  | ❌ (incorrect result) |
| `ArrayRepeat`   | ❌ (expression creation fails)  | ❌ (incorrect result) |

## Dask backend

| Operation        | on `ArrayScalars`                     | on `ArrayColumns`   |
| ---------------- | -------------------------------- | ---------------------- |
| `ArrayLength`    | ❌ (dispatch rule incomplete) | ✔️ |
| `ArrayIndex`       | ❌ (dispatch rule incomplete) | ✔️ |
| `ArraySlice`        | ❌ (dispatch rule incomplete) | ✔️ |
| `ArrayConcat`    | ❌ (expression creation fails)  | ❌ (incorrect result) |
| `ArrayRepeat`   | ❌ (expression creation fails)  | ❌ (incorrect result) |

## PySpark backend

I have not tested, but I believe the PySpark backend is fine because `np.arrays` can only be introduced through `ibis.literal(np.array([1, 2, 3]))`, which is compiled into PySpark's internal array representation
https://github.com/ibis-project/ibis/blob/6a99eafe05b94551028a69274d24e15938bb551e/ibis/backends/pyspark/compiler.py#L328-L331

## Postgres backend

Same with the PySpark backend, I think this is fine
https://github.com/ibis-project/ibis/blob/6a99eafe05b94551028a69274d24e15938bb551e/ibis/backends/postgres/compiler.py#L610-L611

## MySQL backend

Arrays in general not supported

## SQLite backend

Arrays in general not supported

## Other backends

TBD (I haven't taken a look at the rest of the backends yet)

**Comment by cpcloud** [comment]
Seems like we should just normalize the types of these as `list` and call it done. PRs welcome
