### ISSUE TITLE
CI: Add pair of keys for docs deployment

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2637]
@jreback can you give me admin rights to the repo `ibis-project.org` (where the docs are published) please?

Otherwise, feel free to create a pair of keys, and we need to add:
- private as a secret in this `ibis` repo, with the name `github_key`
- public as a deploy key with write access in the `ibis-project.org` directory

Thanks!

**Comment by jreback** [comment]
add you to ibis-project.org with admin access. lmk if you need further.

**Comment by datapythonista** [comment]
Added. Thanks Jeff!
