### ISSUE TITLE
Use a class for the backends registry

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2659]
For many backends, most of the logic seems to be in the registry, where the available operations are defined. This is currently implemented in `compiler.py`, with a dictionary, and mostly private functions. For example:

```python
_operation_registry.update(
    {   
        ops.Literal: _literal,
        # strings
        ops.Substring: _substr,
        ops.StringFind: _string_find,
        ops.Capitalize: _capitalize,
        ops.RegexSearch: infix_op('REGEXP'),
        # math
        ops.Log: _log,
        ops.Log2: unary(sa.func.log2),
```

This is working ok, but I think the code would be more readable, more compact and easier to maintain, if instead we use classes. Something like:

```python
class OperationRegistry(BaseOperationRegistry):
    def Literal(self, t, expr):
       ...
    def Substring(self, t, expr):
        ...
```
This is quite a big refactor, but I think it's worth, since many operations are the same, and at the moment they are simply repeated (for example, `Substring` has the same exact code, 13 lines of code, that are exactly the same between MySQL and Postgres), or in some cases the same function is reused, but updating dictionaries is not as clear as proper subclassing IMHO.

Another advantage is that by using class, we can have an ABC and define some required operations. Besides making things clearer for users, with a more explicit API, this would make development of backends easier.

While this is a significant amount of work, I think it can be done by steps. Starting by defining the classes, and just call the existing functions, and then move the code to directly to the methods, consolidate... slowly. An option is also to implement both dictionaries and classes at the same time, and keep refactoring one backend at a time.

Any feedback on this highly appreciated.

**Comment by cpcloud** [comment]
PRs welcome. This would be a nice refactor.
