### ISSUE TITLE
Remove dask builds for Windows

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2663]
@gerrymanoim is there a particular reason to test Dask on Windows? I guess dask itself is already tested in Windows, The core of Ibis is also tested in one build. And I don't think there should be anything in the dask backend that is sensitive to fail in WIndows only.

If there are no objections, I'd prefer to remove the two Dask/Windows builds. Our list of builds is long (17 builds at the moment), and it's getting more time consuming to find things in the list. Removing those two would help if not really needed.

CC: @jreback

**Comment by gerrymanoim** [comment]
Nope - I think I covered the same platforms/python combos as the pandas backend. No objections from me.

**Comment by datapythonista** [comment]
I guessed that. Copying the pandas build made sense, but I think we can better remove the windows builds. Thanks for the fast answer!
