### ISSUE TITLE
Replace backend options by something else

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2671]
xref #2593
xref https://github.com/ibis-project/ibis/pull/2379#issuecomment-785510513

At the moment, this is valid Ibis valid code:
```python
import ibis

ibis.options.impala.temp_db = 'foo'

client = ibis.impala.connect(...)
```

Ideally, we would like load a backend only if it's used (on `ibis.impala.connect`). But the code `ibis.options.impala.temp_db = 'foo'` would fail if the backend has not yet been loaded. So, we are currently loading all backends on startup (skipping the ones raising `ImportError`).

Personally, I think what makes more sense is that backends can't implement global options, but they use connection parameters. With a unified `connect` function (see #2532), it could look like this (it could also be implemented if we don't unify `connect`):

```python
conn = ibis.connect('impala://user@impala/ibis_testing',
                    temp_db='foo')
```

There are probably other options, like making `options` load backends, adding a `.set_option` to the client... But I think the one above is clearer.

**Comment by tswast** [comment]
Looks like this may happen sooner rather than later in the BigQuery backend. I'm getting errors such as the following since the BigQuery backend was removed from this repo:


```
____________ test_timestamp_column_parted_is_not_renamed ____________

self = {'clickhouse': {'temp_db': '__ibis_tmp'},
 'context_adjustment': {'time_col': 'time'},
 'default_backend': None,
 'gra...: False,
 'pandas': {'enable_trace': False},
 'sql': {'default_limit': 10000},
 'verbose': False,
 'verbose_log': None}
key = 'bigquery'

    def __getattr__(self, key):
        """Get value for the given attribute name.
    
        Parameters
        ----------
        key : str
    
        Returns
        -------
        object
        """
        prefix = self.prefix
        if prefix:
            prefix += "."
        prefix += key
    
        try:
>           v = self.d[key]
E           KeyError: 'bigquery'

../ibis/ibis/config.py:201: KeyError

During handling of the above exception, another exception occurred:

client = <ibis_bigquery.client.BigQueryClient object at 0x7fdcda62ff10>

    def test_timestamp_column_parted_is_not_renamed(client):
>       t = client.table('timestamp_column_parted')

tests/system/test_client.py:617: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ibis_bigquery/client.py:434: in table
    return rename_partitioned_column(t, bq_table)
ibis_bigquery/client.py:308: in rename_partitioned_column
    col = ibis.options.bigquery.partition_col
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = {'clickhouse': {'temp_db': '__ibis_tmp'},
 'context_adjustment': {'time_col': 'time'},
 'default_backend': None,
 'gra...: False,
 'pandas': {'enable_trace': False},
 'sql': {'default_limit': 10000},
 'verbose': False,
 'verbose_log': None}
key = 'bigquery'

    def __getattr__(self, key):
        """Get value for the given attribute name.
    
        Parameters
        ----------
        key : str
    
        Returns
        -------
        object
        """
        prefix = self.prefix
        if prefix:
            prefix += "."
        prefix += key
    
        try:
            v = self.d[key]
        except KeyError as e:
>           raise AttributeError(*e.args)
E           AttributeError: bigquery

../ibis/ibis/config.py:203: AttributeError
```

**Comment by tswast** [comment]
Moving it to a `connect` argument is working. Do we want to support something like `ibis.config.option_context`?

I can mutate the `client.partition_column` attribute to get the relevant test to pass, but this isn't quite the same as having a context manager.

**Comment by datapythonista** [comment]
Not sure what's the problem, but this should work regardless of where is the repo, if the backend entrypoint is available.

See [this code](https://github.com/ibis-project/ibis/blob/master/ibis/__init__.py#L48). We check all registered entrypoints, and on `import ibis` we register all their options.

Is this locally or in the CI? Did you do `pip install -e <ibis-bigquery-repo-dir>`? Maybe you can debug that part of the code and check if bigquery is detected from the entrypoints, and if it is, if it's `register_options` method is being called.

**Comment by tswast** [comment]
This is locally. Yes, I've installed both `ibis-bigquery` and `ibis-framework` via the `-e` option locally.

We've got https://github.com/ibis-project/ibis-bigquery/issues/34 open to investigate the entrypoint issue.

**Comment by datapythonista** [comment]
> Do you think I should move forward with removing the option in [ibis-project/ibis-bigquery#37](https://github.com/ibis-project/ibis-bigquery/pull/37)?

Personally, I think the best for users would be using `ibis.connect(connection_string)` (see #2532). Not sure if when you mean `ibis_bigquery.connect` you mean `Backend.connect`. But yes, I think it's a good idea to make `partition_col` a connect parameter instead of an ibis option.

**Comment by cpcloud** [comment]
It would be great to see what this would look like in a PR, but we can't keep the issue open forever.
