### ISSUE TITLE
"Filtered array" syntactic sugar

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#268]
Some operations provide a `where` argument that expands from

`expr.FUNC(where=COND)`

to SQL like

`FUNC(CASE WHEN COND THEN expr ELSE NULL)`

Assuming that `FUNC` ignores nulls automatically (many SQL aggregation functions do). It might be nice to be able to write

`expr[COND].FUNC()`

How this gets implemented is somewhat of an open question, though. It might require new data types, or `array_expr[BOOLEAN_COND]` might be a masking operation (become NULL on False/NULL, but otherwise stay semantically the same size)

**Comment by wesm** [comment]
This also includes filtering arrays / table columns -- I think the best approach here will be to create an `AnalyticExpr` that can be adapted to the appropriate form depending on how it's used.

**Comment by cpcloud** [comment]
We have tests for expressions like `t[t.a == 'bar'].baz.mean()`. Is there something else that was desired here?

**Comment by wesm** [comment]
Does that expand to the code above in an aggregate expression? I can't remember if I implemented that

**Comment by cpcloud** [comment]
Here's how the translation is working right now:

```python
In [19]: print(t[t.year == 2010].month.mean().compile())
SELECT avg(t0.month) AS mean 
FROM "default".functional_alltypes AS t0 
WHERE t0.year = ?
```

Is there a meaningful difference between that and

```sql
SELECT avg(CASE WHEN t0.year = ? THEN t0.month ELSE NULL END) AS mean
FROM "default".functional_alltypes AS t0
```

**Comment by wesm** [comment]
Yes, you might want:

```python
t.groupby(expr)
 .agg(foo=t.col.mean(),
      bar=t[t.region == 'ni'].col.mean())
```

This allows you to produce conditional means within an aggregate expression. this is something that isn't very easy to do in pandas right now. I'd also like to see

```
t.groupby(expr)
 .agg(foo=t.col.mean(),
      bar=t.col.mean(mask=t.region == 'ni'))
```

In DataPad we got a pretty huge speed boosts by pushing filters down into aggregations functions

**Comment by cpcloud** [comment]
You can do the following in master, which gets you conditional means:

```python
In [31]: from ibis.pandas.api import connect

In [32]: df = pd.DataFrame({'a': list('abcd'), 'b': np.random.rand(4), 'c': list('ddee')})

In [33]: client = connect({'df': df})

In [34]: t = client.table('df')

In [35]: expr = t.groupby(t.c).aggregate(a_filt=t.b.mean(where=(t.a == 'a') | (t.a == 'c')), bmean=t.b.mean())

In [36]: result = expr.execute()

In [37]: result
Out[37]: 
   c    a_filt     bmean
0  d  0.210326  0.578260
1  e  0.220912  0.482058
```

**Comment by wesm** [comment]
Right, the idea of this JIRA was an expression transform which would convert from a filtered array to the where aggregation
