### ISSUE TITLE
refactor: deprecate `udf` from the pandas backend

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#2681]
Backends should use the `udf.vectorized` interface. 

_Originally posted by @jreback in https://github.com/ibis-project/ibis/pull/2648#discussion_r592796939_

**Comment by cpcloud** [comment]
This isn't a breaking change, since we can add a shim to preserve the existing API.

**Comment by cpcloud** [comment]
Feel free to submit a PR!
