### ISSUE TITLE
Support SQLAlchemy 1.4

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2689]
Looks like `sqlalchemy.Binary` has been removed in 1.4, released in conda-forge 4 hours ago, and it's breaking Ibis.

There are some other issues in SQLAlchemy, and also, our `setup.py` requires old versions, and 1.3.7 is not supported.

**Comment by gerrymanoim** [comment]
https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-214869a306f72f33237772d33fc332ec
