### ISSUE TITLE
bug: error processing columns of type timestamp with null values (ibis 1.4.0 on postgres)

### ISSUE THREAD

**Issue by ivergara** [ibis-project/ibis#2692]
Currently I'm stumbling over an issue when trying to execute `value_counts()` or `distinct()` on a column of type `timestamp` and with `null` value on a `postgres` database as backend.

The problem is found in the following function in the `pandas` client backend

```python
def convert_timezone(obj, timezone):
    """Convert `obj` to the timezone `timezone`.

    Parameters
    ----------
    obj : datetime.date or datetime.datetime

    Returns
    -------
    type(obj)
    """
    if timezone is None:
        return obj.replace(tzinfo=None)
    return pytz.timezone(timezone).localize(obj)
```

where it happens that the `null` value from `postres` is stored/interpreted by `ibis` as `None`, and clearly this function fails since `None` has no `replace` method. The fact that it's failing for `null` values was not something I had expected from `ibis`, and actually from what I can tell it doesn't fail for columns with other types.

I'm using `ibis` version 1.4.0 via conda forge on Windows running on Python 3.8

My current workarround, although less than ideal, is to cast the `timestamp` into `string` and then use `distinct()` on the new column. I guess a relatively easy solution would be to put a guard checking if the `obj` is indeed a `datetime` or equivalent. Although such a check might be against performance priorities in the project. Probably a cleaner solution would be that instead of a `null` being interpreted as `None` to be interpreted as `pandas.NaT`, which does implement the `replace()` method.

Or is there some other way to deal with this situation?

I see some somewhat related issues: [enhancement proposal](https://github.com/ibis-project/ibis/issues/1595) and [error report](https://github.com/ibis-project/ibis/issues/1159). The error, although in origin seemingly similar to mine, the traceback is very differently. But also the version is 0.11.2.

Thanks in advance!

**Comment by datapythonista** [comment]
Thanks for the issue. Feel free to open a pull request with the fix. Otherwise, would be helpful to have a minimal example that reproduces the problem.

**Comment by ivergara** [comment]
Yes, I'll try to come up with a more explicit minimal example. I can also try to open a pull request. But I'd like to go for the better solution (in my view) and move to parse the `null` as `pandas.NaT`. It'd be great if you can point me a bit in the correct direction where to find the parsing logic in the codebase.

**Comment by ivergara** [comment]
A deeper investigation showed the real problem. It shows up when there are `null` values and a date beyond the supported datetime in pandas ([timestamp limits pandas documenation](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-timestamp-limits)).

It is clearly a very corner case. It can be reproduced by having the following table (inspired by) issue #1159

```
create table test_ts (col timestamp);
insert into test_ts values (null), (null), (null);
insert into test_ts(col) values ('2419-10-11 10:10:25-07'); 
```

Running a `distinct()` over that column will raise an exception, where I'd have expected to interpret the `None` value coming from the `null` in the database as a `pd.NaT`, which is the case if the timestamps are within `pandas` supported range.

Currently, I do have a fix in my fork, but I don't understand the test suite good enough to see how I could add as a test the example above. It'd be great to get some help with that! In the meantime, I'll make a draft PR with the suggested fix.

**Comment by cpcloud** [comment]
Without pandas having the ability to represent a larger range of dates the "best" solution is to cast the column to a string.

In the medium term we'd like to move away from using pandas as the core in-memory representation.

**Comment by cpcloud** [comment]
This appears to be working now by representing out-of-range timestamps with object dtype. I suspect that a recent version of pandas allows this to work.

**Comment by cpcloud** [comment]
This appears to be working now by representing out-of-range timestamps with object dtype. I suspect that a recent version of pandas allows this to work.

**Comment by cpcloud** [comment]
I will put up a PR to add a test for this and close it out.
