### ISSUE TITLE
Java version on spark builds

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2701]
The latest Ubuntu docker image in GitHub actions seems to bring a newer Java version by default. See https://github.com/ibis-project/ibis/pull/2690#issuecomment-803002778

In #2695 we stopped using the latest for the spark builds, and used the previous instead. Ideally it would be pyspark that would manage the Java dependency in conda, and force installing a compatible version, but doesn't seem this is the case.

So, it'd probably be good to manage things at the code level, so a useful message is shown to users if they have a broken environment. I think we should eventually:
- Restore `ubuntu-latest` in the spark builds
- See if we can get an environment that is guaranteed to be compatible regardless of the OS installed versions
- Add a descriptive error message when the Java version doesn't match a supported one

**Comment by cpcloud** [comment]
Spark documents their supported java versions here https://spark.apache.org/docs/latest/#downloading, and we test against 8 and 11 in CI, there's nothing else to do here.
