### ISSUE TITLE
question: check if custom table and database classes are needed

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2708]
At the moment, each backend is using custom table and database classes. In most cases, those are just empty subclasses. For example, for SQLite we have:

```python
import ibis.backends.base_sqlalchemy.alchemy as alch
from ibis.client import Database


class SQLiteTable(alch.AlchemyTable):
    pass


class SQLiteDatabase(Database):
    pass
```

In #2660 the definition of these classes is being moved to the `Backend` classes, which use an ABC. If the parent classes for table and database can be used directly, and subclasses are not needed, we could just set the classes in the `BaseBackend` class, and not have to define those classes or set them.

So, this code for each backend:

```python
class SQLiteTable(alch.AlchemyTable):
    pass

class Backend:
    table_class = SQLiteTable
```

would be replaced by a single atttribute in the base class:

```python
class BaseBackend:
    table_class = AlchemyTable
```

and same for database. And only backends that really need it would define their custom tables and databases, which I think it's only Impala at the moment.

**Comment by datapythonista** [comment]
Looks like for the pandas backend and related, there is a dispatch system for `ibis.backends.pandas.dispatch.execute_node` that is using the table classes to register functions. So, for pandas this is at least not immediate.

**Comment by cpcloud** [comment]
xref: #2307
