### ISSUE TITLE
bug: `ibis.range_window()` has incorrect behavior on Pandas, PySpark, CSV, and Parquet backends

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2709]
When using an `ibis.range_window()` spec, the Pandas, PySpark, CSV, and Parquet backends seem to treat it as a non-range window. They treat the values of `preceding` and `following` as **the number of rows** to include in the window (this is incorrect), rather than treating them as **the range of values** in the `order_by` column to accept.

# How to reproduce
### Pandas
```
from pathlib import Path

import ibis
from ibis.backends.pandas.tests.conftest import TestConf as PandasTestConf

ibis_backend = PandasTestConf.connect(Path('../ci/ibis-testing-data'))
```

### PySpark
```
from pathlib import Path

import ibis
from ibis.backends.tests.base import get_pyspark_testing_client

ibis_backend = get_pyspark_testing_client(Path('../ci/ibis-testing-data'))
```

### CSV
```
from pathlib import Path

import ibis
from ibis.backends.csv.tests.conftest import TestConf as CsvTestConf

ibis_backend = CsvTestConf.connect(Path('../ci/ibis-testing-data'))
```

### Parquet
```
from pathlib import Path

import ibis
from ibis.backends.parquet.tests.conftest import TestConf as ParquetTestConf

ibis_backend = ParquetTestConf.connect(Path('../ci/ibis-testing-data'))
```

## Main code to execute (same for all four backends)

```
## Setup test data
alltypes = ibis_backend.table('functional_alltypes')

## Execute ibis.range_window() on Pandasbackend
window = ibis.range_window(
    preceding=10, following=0, order_by='id', group_by='string_col',
)
expr = alltypes.mutate(val=alltypes.double_col.sum().over(window))
result = expr.execute().set_index('id').sort_index()

df = alltypes.execute()
expected = (
    df.assign(
        val=df.apply(
            lambda x: df.double_col[
                (df.string_col == x.string_col)
                & ((x.id-10) <= df.id)
                & (df.id <= x.id)
            ].sum(),
            axis=1,
        )
        .sort_index(level=1)
        .reset_index(drop=True)
    )
    .set_index('id')
    .sort_index()
)

comparison_df = pd.concat([
    result.val.rename('val_result'),
    expected.val.rename('val_expected'),
], axis=1)

print(comparison_df[0:30].to_markdown())
```

## Output (same for all four backends)

|   id |   val_result |   val_expected |
|-----:|-------------:|---------------:|
|    0 |          0   |            0   |
|    1 |         10.1 |           10.1 |
|    2 |         20.2 |           20.2 |
|    3 |         30.3 |           30.3 |
|    4 |         40.4 |           40.4 |
|    5 |         50.5 |           50.5 |
|    6 |         60.6 |           60.6 |
|    7 |         70.7 |           70.7 |
|    8 |         80.8 |           80.8 |
|    9 |         90.9 |           90.9 |
|   10 |          0   |            0   |
|   11 |         20.2 |           20.2 |
|   12 |         40.4 |           40.4 |
|   13 |         60.6 |           60.6 |
|   14 |         80.8 |           80.8 |
|   15 |        101   |          101   |
|   16 |        121.2 |          121.2 |
|   17 |        141.4 |          141.4 |
|   18 |        161.6 |          161.6 |
|   19 |        181.8 |          181.8 |
|   20 |          0   |            0   |
|   21 |         30.3 |           20.2 |
|   22 |         60.6 |           40.4 |
|   23 |         90.9 |           60.6 |
|   24 |        121.2 |           80.8 |
|   25 |        151.5 |          101   |
|   26 |        181.8 |          121.2 |
|   27 |        212.1 |          141.4 |
|   28 |        242.4 |          161.6 |
|   29 |        272.7 |          181.8 |

**Comment by cpcloud** [comment]
@timothydijamco This is another great issue, thank you for that. This is indeed a problem.

**Comment by cpcloud** [comment]
I think at the very least for 3.0.0 we can fail here as opposed to giving incorrect results.
