### ISSUE TITLE
CSV splitting / recompressing utility

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#271]
It's not uncommon for medium sized data sets to arrive in the following form:
- one big CSV file (compressed with gzip or bz2)
- column names

Impala will operate perfectly well (right? perhaps even better) on a directory of smaller CSV files, and the header row should be removed anyway

Unfortunately, the CSV splitter will need to be written as a state machine to account for different newline / delimiter / quoting conventions and things like newlines embedded in quoted strings.

At the moment the Ibis schema has to be written down, but reminder that we can and should provide schema inference tools (which may or may not be exhaustive. related #207)

**Comment by cpcloud** [comment]
Closing as out of scope.
