### ISSUE TITLE
Simplify and unify translators

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2715]
Translator classes add a decent amount of repetitive code, and unnecessary inconsistencies. Besides an extra layer of complexity.

Instead of each backend implementing its own translator class, seems like it'd be better that the attributes of the translator class are defined directly in the `Backend` class. Also, there are several base classes for the translators, that could possibly be unified.

The main attributes of translators defined by backends are:
- `_registry`
- `_rewrites` (only SQLAlchemy?)
- `_type_map` (only SQLAlchemy?)
- `context_class` (not in pandas or SQLAlchemy)

The details of what every class implements are next:

**SQLAlchemy**

backend | base translator | attributes
---|---|---
mysql | ibis.backends.base_sqlalchemy.alchemy.AlchemyExprTranslator | _registry, _rewrites, _type_map
postgres | ibis.backends.base_sqlalchemy.alchemy.AlchemyExprTranslator | _registry, _rewrites, _type_map
sqlite | ibis.backends.base_sqlalchemy.alchemy.AlchemyExprTranslator | _registry, _rewrites, _type_map

**pandas**

backend | base translator | attributes
---|---|---
csv | None | _registry, _rewrites
dask | None | _registry, _rewrites
hdf5 | None | _registry, _rewrites
pandas | None | _registry, _rewrites
parquet | None | _registry, _rewrites

**Others**

backend | base translator | attributes
---|---|---
bigquery | ibis.backends.base_sql.compiler.BaseExprTranslator | _registry, _rewrites, context_class, _trans_param
clickhouse | ibis.backends.base_sqlalchemy.compiler.ExprTranslator | _registry, context_class, name
impala | ibis.backends.base_sql.compiler.BaseExprTranslator | _registry, context_class
pyspark | None | _registry, context_class, compiles, translate
spark | ibis.backends.base_sql.compiler.BaseExprTranslator | _registry, context_class

**Comment by Hoeze** [comment]
Is there a reason why ibis only supports sqlite, MySQL and PostgreSQL?
I thought that SQLAlchemy would abstract away all the SQL dialect differences.

**Comment by datapythonista** [comment]
> Is there a reason why ibis only supports sqlite, MySQL and PostgreSQL?
> I thought that SQLAlchemy would abstract away all the SQL dialect differences.

Good point. I'm not sure if having a backend per SQLAlchemy engine is for legacy reasons, or there is something that needs to be defined for each. The refactoring in this issue is to simplify things and define a better API for backends. But later, I'd like o check this in more detail. In my view, there is no reason to not be able to do:

```python
engine = sqlalchemy.create_engine('db://server:port/database')
con = ibis.connect(engine)
```
And have all Ibis backends simply implemented as regular SQLAlchemy engines. But not 100% if it's possible, and we are far from it right now.

**Comment by cpcloud** [comment]
> Is there a reason why ibis only supports sqlite, MySQL and PostgreSQL?
I thought that SQLAlchemy would abstract away all the SQL dialect differences.

This could be done, but would require some refactoring of the backend. PRs for such things are most welcome. I'm closing this issue out as it's very old and hasn't had any activity for months.
