### ISSUE TITLE
`build_ast` in BigQuery backend missing

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2717]
It looks like the `build_ast` function in the BigQuery backend is missing. It causes an error when `.compile()` is called. Here is a repro:

```
import ibis
from ibis.expr.types import TableExpr
import ibis.expr.operations as ops

def _get_ibis_client():
    ibis_client = ibis.backends.bigquery.BigQueryClient
    ibis_client = ibis_client()
    return ibis_client

def _get_test_table(ibis_client):
    names = ['Class',                  
  'end_of_period',          
  'M_Total_Dollars_Total',
            ]
    types = ['string', "date", 'float64']
    schema = ibis.Schema(names, types)
    t = TableExpr(ops.SQLQueryResult("select * from t", schema, ibis_client))
    return t

def test_window_compile():
    ibis_client = _get_ibis_client()
    t = _get_test_table(ibis_client)
    key_cols = ['Class', 'end_of_period']
    order_col = 'end_of_period'
    window = ibis.range_window(
        preceding=ibis.interval(days=62),
        order_by=t[order_col],
        group_by=[t['Class']],
    )
    t = t.mutate(window=t["M_Total_Dollars_Total"].sum().over(window))
    t.compile()
    return t

test_window_compile()
```
```
AttributeError: module 'ibis.backends.bigquery.compiler' has no attribute 'build_ast'
```

Here is a trace of how `.compile()` depends on `build_ast`:
* `SQLClient.compile` calls `SQLClient._build_ast_ensure_limit` ([ibis/client.py#L255](https://github.com/ibis-project/ibis/blob/07f0016abed82be1df5278c29833fd7ab41de0e4/ibis/client.py#L255))
* `SQLClient._build_ast_ensure_limit` calls `SQLClient._build_ast` ([ibis/client.py#L261](https://github.com/ibis-project/ibis/blob/07f0016abed82be1df5278c29833fd7ab41de0e4/ibis/client.py#L261))
* `BigQueryClient._build_ast` tries to call `build_ast` from `ibis/backends/bigquery/compiler.py` ([bigquery/client.py#L439](https://github.com/ibis-project/ibis/blob/165f78de8f4f0121ba2c601b5c9f89bc0f65a593/ibis/backends/bigquery/client.py#L439)) but it doesn't exist

I believe it may have been inadvertently removed in #2661 ([diff](https://github.com/ibis-project/ibis/pull/2661/files#diff-d7c2d45959c2baa00df6631a8818c081adecd87626c52ab82b7560933609e91cL79-L81))

**Comment by datapythonista** [comment]
Thanks for the heads up @timothydijamco 

I'm going to have a look at the bigquery tests, which run after PRs are merged. I received the notification that they failed, but they've been always broken, so didn't pay attention. @tswast can we xfail all broken bigquery tests, so we have a green build and we detect when things break.

**Comment by timothydijamco** [comment]
Thanks @datapythonista! That sounds good—in the meantime I'd like to take a shot at restoring `build_ast` to get `.compile()` working again for now. I will create a PR in a minute, please let me know what you think of it
