### ISSUE TITLE
update datatype in alchemy.py to conform with latest version of sqlalchemy

### ISSUE THREAD

**Issue by cuxcrider** [ibis-project/ibis#2723]
On ibis-framework 1.4.0
I updated to sqlalchemy 1.4.6 today.  I ran into this issue:

module 'sqlalchemy.types' has no attribute 'Binary'

I found that a file in Ibis is using the old 'Binary' datatype which is now 'LargeBinary'
this file:
```/ibis/backends/base_sqlalchemy/alchemy.py```
Simply changing 'Binary' to 'LargeBinary' in two locations (line 47 and 248) on this file fixed this.

More info:  https://stackoverflow.com/questions/65851741/attributeerror-module-sqlalchemy-has-no-attribute-binary

**Comment by datapythonista** [comment]
Thanks for reporting @cuxcrider. We already fixed it in master, and Ibis will work with the latest SQLAlchemy once released. We can't do anything for the version already released, you'll have to use SQLAlchemy prior to 1.4 for now.

**Comment by cpcloud** [comment]
This is fixed.
