### ISSUE TITLE
DEPR: Remove add_operation from SQLAlchemy backends

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2726]
SQLite, MySQL and Postgres implement a `compiler.add_operation` function to add operations to the backend. Those are not being used in Ibis, and are not part of the documentation.

If I'm not missing something, in case it's useful, this could be added for all SQL-based backend (or all backends), and there is nothing in particular in SQLAlchemy backends that make it worth having this function implemented in each backend.

Planning to remove the `add_operation` functions from the 3 SQLAlchemy backends, if any concern, please let me know.

**Comment by saschahofmann** [comment]
I am little confused about what functionality is deprecated now: the `compiles` decorator or the `add_operation`?

#2729 makes it sound that this issue can be closed and we should use `add_operation` instead of `compiles`?

**Comment by datapythonista** [comment]
`compiles` was used internally in many cases, and in a somehow hacky way, creating aliases. That is gone, except for the pyspark backend, where it's still being used.

For `add_operation`, the function was added to the Backend, in case the user (not us in our code) has to register an operation. Besides the better name, this is in the Backend class, making it clear that it's public (compiles was ambiguous IMHO, since it was in the compiler and had to be imported). The `add_operation` of SQLAlchemy backends is not the same as the one in `Backend`, and is the one that should be removed. Among other things, the one in Backend is defined just once for all backends. The ones in SQLite... are repeated.

We're now cleaning and refactoring the backends, so changes here are expected. But these 3 repeated functions don't add value and can be safely deleted.

**Comment by saschahofmann** [comment]
Ah ok. I guess that makes sense. 

I think I am confused because the bigquery backend seems to use it extensively as well.

**Comment by datapythonista** [comment]
There is a mapping (dict) of Ibis operations, to the functions that return the string to build the SQL. `compiles` simply adds a key to that dictionary, and things were very fragmented and confusing. Since `compiles` is not a great name I think, and for the operations defined directly in the backend (not added by a user), is more intuitive to just define the dictionary with all operations, instead of creating it empty and adding them with `compiles`. Particularly since `compiles` was being used in different modules, and it was difficult to know what was being executed, and what exactly was being added to the dictionary. I think pyspark and bigquery should eventually move away from `compiles`. But that whole part is being refactored, we'll see how things are. Ideally the dictionary should become a class, so it's easier to subclass instead of the current dict updating approach. But with so many backends all those changes take a lot of time.

**Comment by saschahofmann** [comment]
If you point me on where to start I could have a look at refactoring some
of the bigquery baclend

**Comment by datapythonista** [comment]
For pyspark, there is this issue: #2730

For bigquery is the same, but it's in a separate repo.

CC @tswast who maintains it, so he can let you know if he's happy with the change.

**Comment by tswast** [comment]
I recall seeing some documentation for this in https://ibis-project.org/docs/user_guide/extending/extending_reduce_expr.html#Step-3:-Turn-the-Expression-into-SQL

Regarding BigQuery, it does appear this code is relevant. https://github.com/ibis-project/ibis-bigquery/blob/0ba15c380b0af90c33bd15bc03e345116b0dfbe1/ibis_bigquery/compiler.py#L529-L539

My main concern is to maintain compatibility with folks that have extended the backend(s), such as in https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/third_party/ibis/ibis_addon/operations.py but it appears they didn't use `add_operation` there.

**Comment by tswast** [comment]
I'm okay with refactoring the BigQuery backend to align with the other backends.

**Comment by saschahofmann** [comment]
If I understand this correctly, we would replace the `compiles` method and somehow add a _registry.py_ plus a `add_operation` function? 

I might have a look at that later.

**Comment by saschahofmann** [comment]
Pandas, for example, seems to use yet another way of registering new functions?

https://github.com/ibis-project/ibis/blob/master/ibis/backends/pandas/execution/strings.py

**Comment by saschahofmann** [comment]
Ok, I think I am going to give this a shot,

Do you have any guidelines on how you would like to structure the backends? 

e.g. some backends seem to have a _translator.py_ that consumes the `operation_registry` from _registry.py_

I think an agreed on structure will greatly help with navigating the different backends 🤓 .

**Comment by datapythonista** [comment]
> Do you have any guidelines on how you would like to structure the backends?

This is unfortunately work in progress. Currently backends are very repetitive, even a hello world backend needs to implement more than 10 empty classes o use all the defaults, and there is no clear API of what a backend needs to implement.

That's why we're breaking things in the backends and restructuring. I'll write base classes and documentation once things in the base backend start to look good. So far I'm just cleaning a lot of very cumbersome code that makes any change very challenging.

**Comment by saschahofmann** [comment]
Ok, no problem. I just started refactoring some of the bigquery backend (see PR above) might be premature though if the wanted structure is quite clear yet? Anyway let me know what you think, nothing too exciting thoug.

**Comment by datapythonista** [comment]
I think it's good if you keep adapting it to the latest Ibis version and standards. Every change I'm making needs to be done to 10 backends at once, so things don't change so quickly (unfortunately I'd say). And all the changes should simplify things.
