### ISSUE TITLE
Use a registry instead of the decorator compiles for pyspark operations

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2730]
xref #2729

Most of the operations are defined in a `registry.py` file in the corresponding backend. An alternative way is to use a `compiles` decorator on a function, that would simply add the operation to the same registry. This makes things unnecessarily complicated and confusing. Simply using the registry makes things easier to understand. For most backends, the  `compiles` decorator has been removed (see #2729). `pyspark` doesn't use the registry directly like the others, but instead uses the `compile` decorator.

It would make sense to use the same approach as the rest of the backends.

**Comment by datapythonista** [comment]
@icexelloss does this make sense to you?

**Comment by cpcloud** [comment]
I think we should be moving towards `@compiles`, not away from it. I think it's fine to have both.
