### ISSUE TITLE
docs: link to the documentation of known Ibis backends in the Ibis website

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2735]
We've got some backends in this repo, and some as third-party, including some of the ones previously here omniscidb and bigquery. And some developed directly as third-party, like mssql.

Since the API documentation requires the code to be generated by Sphinx, we've moved the docs to the third-party backend repos. Which it makes sense anyway, since it's where it should be maintained.

But since the reasons to have a backend in this repo are not very relevant for the users (problems with dependencies, number of maintainers of the backend...), I don't see why we shouldn't keep publishing the backend documentation in the main Ibis repo. That would make things easier for users in my opinion.

I think there are different ways to achieve this. Like having a standard path in the repo for the rst file, and fetch it during the doc build. Or building the page in the backend CI, with the Ibis template, publish it as an artifact in a standard place, and fetch that at the end of the doc build. Then having in the Ibis docs a list of the known backends (e.g. `ibis-project/ibis-bigquery`, `quansight/ibis-mssql`...), and fetch whatever we decide from all them.

I think the workflow adds a bit of complexity, but not much if things are standardized in the backends. And IMHO the benefit for the user of having all docs in a central place, and visibility of all available backends, make it worth.

@jreback @tswast @amueller does this sound good?

**Comment by tswast** [comment]
One of the reasons for splitting them out was that even for rendering the docs there can be dependency conflicts. (I'm thinking of OmniSciDB and the old version of pyarrow conflicting with BigQuery requirements.) I'm okay with whatever conventions we come up with if the dependency issue is overcome.

Otherwise, I'm okay with a page of backends with links to their separate docs. (Similar to SQLAlchemy: https://docs.sqlalchemy.org/en/14/dialects/)

**Comment by jreback** [comment]
yeah i was just proposing a link to the other backends docs

i wouldn't add complexity actually build things

**Comment by cpcloud** [comment]
This is done.
