### ISSUE TITLE
Implement OperationRegistry class and replace translator classes with it

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2736]
Currently, the attributes of the translator classes (e.g. `ExprTranslator`) are "public", and mostly the operation registries are  accessed and reused from one backend to another. This is making things difficult to understand, there is repetitive code, and in general things could be way cleaner.

Also, the translator class are at the same time used for logic for a single expression (e.g. `ExprTranslator(expr).get_result()`) and for the whole registry (e.g. `ExprTranslator.translate(expr)`), and methods don't seem to be decorated with the correct level (e.g. `classmethod`, `staticmethod`...).

I think a better approach would e creating a class for the operations, as defined in #2659. As a first step to move in that direction (#2659 is a huge issue requiring lots of changes) would be to hide the registry details, and create an API for the registry+translator that encapsulates all its logic. This won't only move into the direction of the better syntax s #2659, but will also make things much clearer and easy to deal with by itself.

Some code that could be replaced would be:
```python
_operation_registry = dict(base_operation_registry)
```
by
```python
class MyBackendTranslator(BaseTranslator):
    ...
```

Also
```python
ExprTranslator(expr).get_result()
```
by
```python
OperationRegistry.translate_and_name(expr)
```

**Comment by cpcloud** [comment]
It's better to put up a PR for this sort of thing than to spend a lot of time discussing it. That said, would welcome a PR for this.
