### ISSUE TITLE
Difficulty installing ibis in editable mode with latest pip

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#2738]
I was encountering permissions issues in setting up the CI for ibis-bigquery: https://github.com/ibis-project/ibis-bigquery/pull/38/checks?check_run_id=2439821596

```
    WARNING: The user site-packages directory is disabled.
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/test-easy-install-1708.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/local/lib/python3.8/dist-packages/
    
    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.
```

I believe the usual workaround for this is to add `--user`, which installs packages to the `$HOME` directory instead of the system packages path. The problem is `WARNING: The user site-packages directory is disabled.`, which has been reported at https://github.com/pypa/pip/issues/7953

There is a workaround https://github.com/pypa/pip/issues/7953#issuecomment-645133255

```
import site
import sys
site.ENABLE_USER_SITE = "--user" in sys.argv[1:]
```

which I have added to the `ibis-bigquery` `setup.py` in https://github.com/ibis-project/ibis-bigquery/pull/38 as well as a patch to `ibis`'s `setup.py`, which does indeed fix this issue.

I think we should add this workaround to the `ibis` `setup.py`, at least temporarily, until the bug is fixed in pip.

**Comment by datapythonista** [comment]
Why not create a conda or virtualenv environment?

**Comment by tswast** [comment]
I'm trying to follow the GitHub Actions Python guide for now. Indeed long-term I'd like to run the tests from a conda environment, but that's more setup than I'd like to do right now.

**Comment by datapythonista** [comment]
GitHub Actions comes with conda, I think your problem is solved if you create a conda environment, even if after it you install everything with pip. I don't think that's more setup, seems like a one liner. And I'd prefer that than adding a hack to our setup.py (which may end up causing other problems).

**Comment by tswast** [comment]
Closing in favor of https://github.com/ibis-project/ibis-bigquery/issues/39
