### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by floriancastelain** [ibis-project/ibis#2756]
It is not possible to open issues in the https://github.com/ibis-project/ibis-project.org repo, so here I am.

In this page: https://ibis-project.org/getting_started.html

The `advanced installation instruction page` link is dead (https://ibis-project.org/docs/getting_started/install.html)

**Comment by datapythonista** [comment]
Thanks for reporting this @floriancastelain. I just opened a pull request with a fix, should be working soon.
