### ISSUE TITLE
Enhance SQLAchemy backend insert implementation to include usage of table_expr for inserting data

### ISSUE THREAD

**Issue by harsharaj96** [ibis-project/ibis#2778]
Apart from inserting data using a dataframe or by giving a table name, if a user gives table expression as input then insert operation must be performed into the desired table.

**Comment by datapythonista** [comment]
Not for the current work, but for the future, I think it probably makes more sense to have a single argument `source` that can be a dataframe, an expression, another table.... and perform the operation based on the type. Instead of having a different argument for each source kind.

**Comment by harsharaj96** [comment]
Using the `obj` variable in the `.insert()` function to take either pandas DataFrame or table_name or ibis TableExpr like what we wanted to do with the `source` variable. Added test cases for this scenario as well.
