### ISSUE TITLE
test: add test for multi-col reduction UDF that returns np.ndarrays

### ISSUE THREAD

**Issue by emilyreff7** [ibis-project/ibis#2788]

**Comment by cpcloud** [comment]
Closing, but PRs welcome. Can you give a short example for anyone who may want to pick this up later? Thanks!

**Comment by emilyreff7** [comment]
This issue would expand our test coverage in [this file](https://github.com/ibis-project/ibis/blob/master/ibis/backends/tests/test_vectorized_udf.py) by creating a new test similar to [test_reduction_udf_array_return_type](https://github.com/ibis-project/ibis/blob/master/ibis/backends/tests/test_vectorized_udf.py#L291), except instead of using the single-column UDF [quantiles](https://github.com/ibis-project/ibis/blob/master/ibis/backends/tests/test_vectorized_udf.py#L231), it would use a new multi-column reduction UDF that returns >1 `dt.Array`.
