### ISSUE TITLE
feat: implement DDL API for Backends

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2796]
Currently, only Impala and Spark support DDL. The Impala implementation is in `backends/base`, but it's far from generic. Spark inherits from it, but it needs to change most things. From around 500 lines of code in the original implementation, the Spark one has to write 300 to make it work.

This doesn't seem great. I don't think a generic DDL system is feasible, and doesn't seem most backends find DDL useful anyway. I think we should make the Spark implementation independent of the Spark one, and move the Impala one to its own backend.

So, backends can implement ddl if they want to, but Ibis doesn't know anything about it.

@icexelloss @jreback thoughts?

**Comment by cpcloud** [comment]
Closing in favor of #5392.
