### ISSUE TITLE
CI: Dask builds are broken

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2800]
We've got tests failing in the dask build with errors like `TypeError: No dispatch for <class 'numpy.float64'>`.

See https://github.com/ibis-project/ibis/pull/2799/checks?check_run_id=2717960792#step:4:131

CC: @icexelloss @gerrymanoim

**Comment by gerrymanoim** [comment]
Weird - this was fine a few days ago. I'll grab this and take a look. Thanks for flagging.

**Comment by gerrymanoim** [comment]
I can't repro this in my existing ibis env - likely some dependency bump broke in a weird way. Digging.

**Comment by gerrymanoim** [comment]
3.9 tests are definitely broken because of the dask 2021.5.1 upgrade. 

Not sure yet why 3.7 tests are broken.

**Comment by gerrymanoim** [comment]
@datapythonista - if I'm understanding the envs in tests correctly - the 3.7 envs are now running pypy python. Is that expected?

Looking at https://github.com/ibis-project/ibis/runs/2723263474?check_suite_focus=true. 

For the failing 3.7 dask run:

```
platform linux -- Python 3.7.10[pypy-7.3.4-final], pytest-6.2.4, py-1.10.0, pluggy-0.13.1
```

For the successful 3.9 run:

```
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
```

You can also see it in the envs. The pandas 3.7 linux tests are also using pypy. 

The other package diffs I see don't seem to really be significant, so I think this is the problem.

**Comment by datapythonista** [comment]
I don't think there is anything in our code base related to pypy, feels like this is a gift from conda, no idea where it comes from.

**Comment by gerrymanoim** [comment]
Agreed - looks like it is coming in from the original `ibis-dev` install.
