### ISSUE TITLE
CI: Broken pyarrow

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2801]
Seems like the build of the pyarrow version resolved by conda for the Python 3.7/pandas builds may be broken.

```
  pyarrow                                      3.0.0  py37he0739d4_3       pkgs/main/linux-64         2 MB
```

```
ibis/backends/tests/conftest.py:162: in <module>
    @pytest.fixture(params=_get_backends_to_test(), scope='session')
ibis/backends/tests/conftest.py:63: in _get_backends_to_test
    for backend in sorted(backends)
ibis/backends/tests/conftest.py:63: in <listcomp>
    for backend in sorted(backends)
ibis/backends/tests/conftest.py:42: in _backend_name_to_class
    f'ibis.backends.{backend_str}.tests.conftest'
ibis/backends/parquet/__init__.py:3: in <module>
    import pyarrow as pa
/usr/share/miniconda/site-packages/pyarrow/__init__.py:63: in <module>
    import pyarrow.lib as _lib
E   ModuleNotFoundError: No module named 'pyarrow.lib'
```

See: https://github.com/ibis-project/ibis/pull/2799/checks?check_run_id=2717960396#step:4:9

**Comment by datapythonista** [comment]
@kszucs do you know anything about this failure? Not sure why conda is installing this version, since there is a 4.0 for what I saw. But would be good to fix without pinning things ideally.

**Comment by kszucs** [comment]
Going to take a look, meanwhile cc @xhochy

**Comment by jreback** [comment]
shall we just pin for 3.7?

**Comment by kszucs** [comment]
We should install pyarrow from the conda-forge channel rather than `pkgs/main`.

**Comment by xhochy** [comment]
> Going to take a look, meanwhile cc @xhochy

Don't expect help from me if the package is not coming from conda-forge 😛

**Comment by datapythonista** [comment]
We only have `conda-forge` in the channels of our `environment.yml`, but looks like `mamba` is not respecting it, and `mamba env update` doesn't have an argument to force the channel. I'll see what I can do.

> Do we use `setup_env.sh` locally or just on GHA?

You can use it locally, if you want to get dependencies and tests loaded for a set of backends. I usually do it manually, but did both in the past.

**Comment by xhochy** [comment]
Can you add the magic channel `nodefaults` to the `environment.yml`? Otherwise conda and mamba will also use the channels from the global conda config.

**Comment by datapythonista** [comment]
> Can you add the magic channel `nodefaults` to the `environment.yml`? Otherwise conda and mamba will also use the channels from the global conda config.

That's very useful, thanks a lot for sharing. Seems like it works and fixes our problem.
