### ISSUE TITLE
feat: IBM DB2, Cloud Spanner, Oracle, Snowflake, Teradata

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#2803]
As part of a data validation tool, which was recently open-sourced (https://github.com/GoogleCloudPlatform/professional-services-data-validator) Google in coordination with Quantiphi developed several Ibis backends. The source code of which is available here: https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/third_party/ibis

It'd be nice to move these over to separate packages so that they can be brought back in to the Ibis community. For example, I know we have https://github.com/ibis-project/ibis-oracle for the Oracle connector, which was one of the first that Quantiphi developed.

**Comment by cpcloud** [comment]
@tswast Awesome, didn't know this work had been done!

Any update on the status/state of these backends? Would be great to roll them in if we can set up testing.

**Comment by tswast** [comment]
All working in production last I saw. Stuck on ibis v1, though.

**Comment by tswast** [comment]
I've got https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/317 open to update them to v2, but don't expect to have time to do so.

**Comment by cpcloud** [comment]
I'm going to remove `ibis-project/ibis-oracle`, there's a 2 line README that hasn't seen changes in almost two years.

I would love for someone from the Google team to move one or more of those repos into ibis-project, but the current set of maintainers doesn't have the bandwidth to do this as part of our roadmap at the moment.

**Comment by cpcloud** [comment]
I'm going to close this out for now.

**Comment by rupurt** [comment]
It looks like the Db2 backend was never brought into the main project. Are there any plans to do that?

**Comment by gforsyth** [comment]
> Are there any plans to do that?

Not at the moment, but it's a reasonable feature request to open.  Generally we're more likely to add a backend if there's a docker container available (so we can test it in CI) and an up-to-date sqlalchemy dialect.  

DB2 does seem to have both of those things:
https://hub.docker.com/r/ibmcom/db2
https://github.com/ibmdb/python-ibmdbsa

**Comment by cpcloud** [comment]
To update, here are the backends in ibis since this issue was created:

- [ ] db2
- [ ] cloud spanner
- [x] oracle
- [x] snowflake
- [ ] teradata

**Comment by rupurt** [comment]
@gforsyth cool :smile: 

FWIW we are using the https://hub.docker.com/r/ibmcom/db2 image successfully. It starts quickly in Linux but takes ~10 minutes on Apple ARM. We have built a private custom image which adds caching to start instantly.
