### ISSUE TITLE
CLN: Refactor compiler

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2812]
xref #2765

This is what I've been working on for a while now. But now I've got better understanding of the exact problems with the compiler, and a clearer picture of what I want to do. Writing it here for visibility.

The code to compile expressions is very cumbersome, difficult to understand, and breaks mysteriously at any change. The main problem is that it has a unconventional structure of classes that point to other classes, that end up being in an infinite loop, `QueryContext > QueryBuilder > SelectBuilder > Select > ExprTranslator > QueryContext > ...`. So, to start with, it's difficult to know where the process starts. Also, there are two separate functions, `to_sql` and `build_ast` that use those classes, and the `Dialect`, which is an even more cumbersome concept, that builds on top of it.

What it makes sense to me (and already did some work in that direction), is to start by the `Connection` object (the future merge of `Backend` and `Client`, see #2678). And add a `_compiler` attribute to it, that will be an entry point for the compilation:
```python
class Connection:
    _compiler = Compiler
```
This `Compiler` class will mostly be the current `QueryBuilder` class. And it will have two main public methods, `to_sql` and `build_ast`. So, to generate the SQL of an expression, it should be possible to call `connection._compiler.to_sql(expr)`.

For this to happen, few classes are involved. All these classes will be specified in the compiler (not one class pointing to the immediate that needs, and that one pointing to the next). So, we'll have something like:
```python
Class Compiler:
    _select_builder = SelectBuilder
    _select_class = Select
    _translator = ExprTranslator
    _table_set_formatter = TableSetFormatter
    _query_context = QueryContext
    _registry = operation_registry
```

It will also include the operation registry. Which is the main part that backends usually need to specify in the compiler. So, for most backends, it'd be expected, that basides the `Connection` (aka `Client`). So, instead of backends having to implement all the classes of the compiler, like until now, most of them should simply implement a `Compiler` class with the updated registry:
```python
Class MyBackendCompuiler(Compiler):
    _registry = custom_operation_registry
```
Everything else should work just with the defaults in most cases. In cases when one of those classes need to be extended with a subclass, instead of having to define the whole sequence of classes that are just the parent class, changing only the attribute to the next class, just a class will need to be changed.
```python
class CustomTranslator(ExprTranslator):
    ...

Class MyBackendCompuiler(Compiler):
    _registry = custom_operation_registry
    _translator = CustomTranslator
```

This should reduce most of the duplicate code among backends (which is very significant at the moment.

Any comments please let me know.

**Comment by jreback** [comment]
i think we should release and make sure the backends not in this repo catch up before going further

**Comment by datapythonista** [comment]
> i think we should release and make sure the backends not in this repo catch up before going further

I'm open to it, but my preference is to wait until this is done. Releasing soon, but when the API between Ibis and the backends is defined. The original goal of this work is to be able to add an abstract class (or classes) to implement a backend. So, we know what to expect from backends, they are easy to implement, and we don't have obvious inconsistencies. The clean up is because this code is impossible to deal with (at least to me), and this public API would end up being 12 classes and +100 methods.

I think once we've got well defined what backends implement, we can keep backward compatibility, and not break things, at least not without future warnings first. And I think adapting the backends won't be very difficult once the base class exists (it'll mostly be deleting many repetitive classes), and subclassing the base class.

Personally I think releasing now creates more trouble than value. Without the base class it's more time consuming to see what changed. And dealing with compatibility, when in the following release we will still break things, will be trickier. Like, a backend that is updated to the release you're proposing, but not anymore, it'll be broken for Ibis 2.1. While it should work for the long run if we release once we're done with breaking changes.

We're at the end of all these changes, this issue summarizes what's pending, and it should be just few more weeks. I understand the concern, but I personally think it's worth waiting a bit more.
