### ISSUE TITLE
bug: fix verify_meta=False usage in dask udfs

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#2815]
Fix/Remove usage of `verify_meta=False` in the dask udf code for scalar outputs as that's blocking us from updating dask.

**Comment by cpcloud** [comment]
@gerrymanoim Is this still a problem?

**Comment by gerrymanoim** [comment]
We still have this piece of code: https://github.com/ibis-project/ibis/blob/master/ibis/backends/dask/udf.py#L160. Clearly it hasn't stopped us from updating dask, but I don't know if that's still required. Let me try removing it.

**Comment by cpcloud** [comment]
@gerrymanoim Did you get a chance to look into this?

**Comment by gerrymanoim** [comment]
I put this fix up https://github.com/ibis-project/ibis/pull/3316, but this implementation required basically doing extracting all the pieces of `dd.from_delayed` besides the meta verification. Given that, I'm going to just close this issue and change my PR to simply remove the shim we don't need anymore.

**Comment by cpcloud** [comment]
Awesome, thanks!
