### ISSUE TITLE
chore: enable passing mypy checks

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2823]
We've got a mypy check in the CI, but we force it to be green, since mypy has errors.

I see that at the moment there are some issues with duplicate names of files, and mypy is not even checking or reporting errors other than that.

It'd be good to spend some time soon in fixing mypy errors, and failing the CI for mypy errors, otherwise we're adding type annotations for nothing.

**Comment by cpcloud** [comment]
Over the next year or so we should make decision about whether to spend more time adding type annotations and enabling their verification in CI.

There are a number of challenges in either approach, but we should settle the issue this year.

**Comment by cpcloud** [comment]
I think we're going to go about this incrementally as opposed to a mega-PR that addresses all the code in ibis and runs mypy in CI.

Feel free to submit PRs that add type annotations.
