### ISSUE TITLE
Best efforts cleanup of temporary constructs via signal handlers

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#284]

**Comment by cpcloud** [comment]
@wesm Do you remember what the temporary constructs you're referring to here are?

**Comment by wesm** [comment]
Temporary Impala tables and databases. I think it does try to drop everything now. I'm not sure if there's more we could be doing to make it more robust

**Comment by cpcloud** [comment]
Signals are not the right mechanism for this. We're cleaning up well enough on tests. The remaining clean up would be temporary CSVs created when constructing external tables from user data.
