### ISSUE TITLE
BUG: File pseudo-backends failing for missing pandas option

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2844]
The next code is failing in master since #2833:

```python
>>> import ibis
>>> con = ibis.csv.connect('/home/mgarcia/src/ibis/ci/ibis-testing-data/')
>>> expr = con.table('functional_alltypes')['double_col'] * 2
>>> print(expr.execute())
OptionError: "No such keys(s): 'pandas.enable_trace'"
```

The problem is when the `csv` backend  (or other file backends) are loaded, but the pandas backend is not. This is because `ibis.pandas` loads the pandas options, which looks like they are needed by the file pseudo-backends.

The CI is not failing, I guess because we test pandas and the file backends are tested together, and pandas is loaded when the file backends are tested.

**Comment by gerrymanoim** [comment]
This also fails when trying to run pandas individual tests themselves.
