### ISSUE TITLE
Union except and intersect

### ISSUE THREAD

**Issue by saschahofmann** [ibis-project/ibis#2845]
A lot (all?) backends support some kind of except/intersect UNION 

E.g postgres https://www.postgresqltutorial.com/postgresql-union/
or bigquery https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#intersect

Does it make sense to implement these in the main repo? Do you have a feature freeze until the 2.0 release?

I could have a look at this myself if you agree this should go into ibis directly!

**Comment by datapythonista** [comment]
Maybe not in the docs, but UNION is implemented in Ibis already.

**Comment by saschahofmann** [comment]
Ahhh I see you implemented intersect and Except separately.! Yeah just discovered it in the [code](https://github.com/ibis-project/ibis/blob/master/ibis/backends/base/sql/compiler/query_builder.py#L493)?

Sorry! I think this might be broken in Bigquery then but will test and write there separately

**Comment by datapythonista** [comment]
Bigquery needs to be adapted to the last changes in Ibis, but other than that, that part should be working.

Should we close this issue, or is there anything else that is missing from what you requested here?

**Comment by saschahofmann** [comment]
Yes sorry closing this. Needs to be addressed in BigQuery https://github.com/ibis-project/ibis-bigquery/issues/87

**Comment by saschahofmann** [comment]
Hey sorry,
I was just playing around with `difference` in bigquery and postgres. I can do things like this

```python
table.difference(table2)
```
But if I try to create a projection like this
```python
table.difference(table2).projection(['column1', 'column2'])
```

I get a `NotImplementedError: <class 'ibis.expr.operations.Difference'>`

Originating from here https://github.com/ibis-project/ibis/blob/1.4.0/ibis/backends/base_sqlalchemy/compiler.py#L401

It works for Union any ideas how I can work around this e.g. with what if I want to run a filter on a difference query, @datapythonista ?

**Comment by saschahofmann** [comment]
*Note* this is for ibis 1.4.0. since main looks very different this could be fixed there alread?

**Comment by datapythonista** [comment]
Not so familiar with this part, from the code looks like it should be implemented, not sure what is missing. I don't think there has been any change in that part recently, other than moving code from one place to another. Happy to take PRs for this, before or after the release.

**Comment by saschahofmann** [comment]
Ok I'll have a look

**Comment by saschahofmann** [comment]
Will probably create a PR for this tomorrow just for completeness. I am monkey-patching 1.4.0 like this in our project right now

```python
from ibis.backends.base_sqlalchemy import compiler

def _collect_Difference(self, expr, toplevel=False):
    if toplevel:
        raise NotImplementedError()


compiler.SelectBuilder._collect_Difference = _collect_Difference
```
