### ISSUE TITLE
CI: Setup mamba with GitHub action

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2846]
We are currently setting up our conda environment in the CI with the `ci/setup_env.sh` script. We could simplify things, and make the environment more stable if we use this GitHub action: https://github.com/mamba-org/provision-with-micromamba

This will not only let us remove the code to install mamba and the environment manually, but it will also install the dependencies in a clean environment, instead of reusing the default base environment from the actions image. We're currently using the base environment to avoid having to setup the PATH for conda manually in each build. But with the action that wouldn't be needed.

What we should do is:
- Create a new script with the code that edits `environment.yml` before it's installed
- Create a new script with the code that installs the data in the testing server instances
- Delete the original `ci/setup_env.py` where the code lives now
- Update `.github/worflows/main.yml` to call the first script, the github action, and the second new script, instead of `setup_env.sh`

**Comment by cpcloud** [comment]
This is no longer relevant because we use poetry in CI for these cases. Using `poetry` in CI is just oodles faster than anything in the conda/mamba ecosystem.
