### ISSUE TITLE
refactor(dask): remove da.select shim after dask min version is 2021.6.1

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#2847]
https://github.com/ibis-project/ibis/pull/2843 uses `da.select`, which is only available starting in dask 2021.6.1. For compatibility this PR also introduced a shim which ports the function directly from https://github.com/dask/dask/commit/868cba2405676442a7f4fe07ad82b038797ecdc4#diff-be1ec6725c3829aa2f919897e0d4cfc1e00b8db1e70e90c82531c5a12fd727afR1876. We should remove this once the min version reaches 2021.6.1.

**Comment by cpcloud** [comment]
Closed by #3297
