### ISSUE TITLE
refactor: fix mypy errors in the Dask backend

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2852]
xref #2823

Running `mypy ibis/backends/dask/` reports 166 errors, related to missing or inconsistent type annotations. We should fix them, and make that command finish in a clean way.

Here there are some sample fixes: #2857

**Comment by cpcloud** [comment]
Rolling this up under #2823. Great job on the progress here @sofide, most of the errors are fixed!

We're down to 22 errors!
