### ISSUE TITLE
refactor: fix mypy errors in the Impala backend

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2853]
xref #2823

Running `mypy ibis/backends/impala/` reports 11 errors, related to missing or inconsistent type annotations. We should fix them, and make that command finish in a clean way.

Here there are some sample fixes: #2857

**Comment by cpcloud** [comment]
The impala backend needs a champion for issues like this. Adding mypy would be lower on the priority list than bug fixes or features. Of course, a PR of any kind is accepted!
