### ISSUE TITLE
refactor: fix mypy errors in the pandas backend

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2854]
xref #2823

Running `mypy ibis/backends/pandas/` reports 35 errors, related to missing or inconsistent type annotations. We should fix them, and make that command finish in a clean way.

Here there are some sample fixes: #2857

**Comment by cpcloud** [comment]
There's only 1 error left and it's not actually related to ibis per se, which is awesome. Thanks @arielrossanigo.
