### ISSUE TITLE
refactor: fix mypy errors in the clickhouse backend

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2856]
xref #2823

Running `mypy ibis/backends/clickhouse/` reports 5 errors, related to missing or inconsistent type annotations. We should fix them, and make that command finish in a clean way.

Here there are some sample fixes: #2857

**Comment by napoles-uach** [comment]
So it seems to me that one on the errors is related to a list that is turned into a dictionary.. This is the error message:
`ibis/backends/clickhouse/registry.py:698: error: Incompatible types in assignment (expression has type "Dict[AnnotableMeta, Callable[[Any, Any, VarArg(Any)], Any]]", variable has type "List[AnnotableMeta]")`

and here is the code:

```
675 _unsupported_ops = [
676     ops.WindowOp,
677     ops.DecimalPrecision,
678     ops.DecimalScale,
679     ops.BaseConvert,
680     ops.CumulativeSum,
681     ops.CumulativeMin,
682     ops.CumulativeMax,
683     ops.CumulativeMean,
684     ops.CumulativeAny,
685     ops.CumulativeAll,
686     ops.IdenticalTo,
687     ops.RowNumber,
688     ops.DenseRank,
689     ops.MinRank,
690     ops.PercentRank,
691     ops.FirstValue,
692     ops.LastValue,
693     ops.NthValue,
694     ops.Lag,
695     ops.Lead,
696     ops.NTile,
697 ]
698 _unsupported_ops = {k: _raise_error for k in _unsupported_ops}`
``

So I'm not sure if Ii is valid to use a temporal variable, or change the name of the  list to avoid the conflict @datapythonista 
or what would be a best practice??

**Comment by datapythonista** [comment]
You can rename the first one

**Comment by cpcloud** [comment]
Rolling this up into #2823. Thanks @napoles-uach for the PR!

**Comment by napoles-uach** [comment]
My pleasure!!
