### ISSUE TITLE
refactor: export Intersection and Difference from compiler init

### ISSUE THREAD

**Issue by saschahofmann** [ibis-project/ibis#2872]
As noted [here](https://github.com/ibis-project/ibis-bigquery/pull/88#issuecomment-883162640) the `Intersection` and `Difference` classes aren't exported in _compiler/\_\_init\_\_.py_ but `Union` is I probably should have added this in my last PR but should be easy enough.

Are you ok with me simply adding the two classes to the _\_\_init.py\_\__ I think it would be the more consistent experience.

As a side question, is it possible that the classes were introduced after 1.3. because I can't find them anywhere there?

**Comment by cpcloud** [comment]
This issue is stale. No need to keep it open. If you're interesting in creating a PR, let's discuss there.
