### ISSUE TITLE
perf: optimize path for many reductions in dask backend

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#2880]
This feels a bit suboptimal because when you have many udfs inside (people often compute many window summarization for different columns at once), you would ended up doing many merging. 

Not an issue for this PR but I suggest leaving a note here to look into better ways of doing this in the future.

_Originally posted by @icexelloss in https://github.com/ibis-project/ibis/pull/2858#discussion_r677500099_

**Comment by cpcloud** [comment]
@gerrymanoim Thanks for opening the issue. I agree this might be an issue, but let's profile first! Look forward to the PR!
