### ISSUE TITLE
bug: installation may fail on Windows for Impala backend due to aggressive kerberos support in setup.py

### ISSUE THREAD

**Issue by ZeroCool2u** [ibis-project/ibis#2892]
This is a subtle bug that was introduced by a previous PR of mine [here](https://github.com/ibis-project/ibis/pull/2357/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R19), which was meant to simplify kerberos dependencies. 

However, some updates to the Impyla library have caused this bug to become a bigger problem for folks trying to install Ibis with the Impala backend on Windows. 

The source of the issue is that when an Impyla install is requested with kerberos support, ```pip install impyla[kerberos]```, Impyla now attempts to install the [kerberos ](https://github.com/apple/ccs-pykerberos)library [here](https://github.com/cloudera/impyla/blob/6255bbf84f12c6800fb50b1c35c4e8f1e63baa2c/setup.py#L46).

On *nix based platforms this is fine, but on Windows, this is a problem. The kerberos library does not seem to support Windows and based on my research the typical pattern of library authors is using [winkerberos ](https://github.com/mongodb/winkerberos)or kerberos based on the platform detected by Python in the libraries setup.py. 

I think this could easily be resolved by modifying our setup.py the same way I've suggested in this [Impyla issue](https://github.com/cloudera/impyla/issues/466#issuecomment-892076639).

**Comment by cpcloud** [comment]
I think this needs to be solved in impyla and not in ibis. The workaround is a pretty big maintenance headache.
