### ISSUE TITLE
Implement .set_database() for all backends or remove it from the API

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2913]
In #2909 the method `.set_database()` has been standardized, but this does not include making it always available in all backends. There are several backends, such as SQLAlchemy backends, File backends or clickhouse, that don't implement it, and don't let changing the backend.

The reason in most cases seems to be that the underlying connection object doesn't support changing the database. But in those cases, we can keep a `_current_database` attribute ourselves, and use that database on queries.

Having `.set_database()` always implemented should make things easier for users.

Another alternative is to simply remove it from the few databasets that implement it. Users can connect to a different database, and have different variables with connections to different databases.

**Comment by cpcloud** [comment]
-1 on adding complex mutable state such as a database connection that ibis needs to track.

+1 on removing `set_database` from the API.

It's not that onerous to just connect to the other database.
