### ISSUE TITLE
refactor: remove the `resolve_name` method

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#2921]
`resolve_name` is mostly useless, and it's really hard to develop against because most relational operations simply don't have a non-arbitrary name. Consider something simple like:

```python
t = ibis.table([('a', 'double')], name='t')
expr = t.a + 1
```

What should `expr.op().resolve_name()` return? Unless a user has explicitly said `.name(something)`, there is no reasonable choice here. Even then, the name `something` is not a property of the operation, it's a property of the expression.

Proposal:

Remove `resolve_name` from operations, and simplify code generation to expression names rather than operation names.

**Comment by Heril18** [comment]
May I work on removing resolve_name from operations ?
