### ISSUE TITLE
refactor: remove underspecified type aliases

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#2928]
Type aliases such as `int_` and `uint_` are misleading, as you can't really do anything useful with them. Moreover, they provide a false illusion that users can ignore specific integer types when in fact they cannot.

This is a breaking API change.

**Comment by saulpw** [comment]
#3437 addresses this, cleaning up the basic data type system in general. The underspecified aliases have not been strictly removed, but are kept around for convenience and are docprecated.  The old `uint_` is now an alias to `int64`; `float` and `double` are now both aliases for `float64`.  But the general recommendation is to use size-specified types in production cases.
