### ISSUE TITLE
feat: add support for aggregate ordering where sensible

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#2929]
Postgres and other systems support an `ORDER BY` statement in various operations where ordering is meaningful, e.g., [`string_agg`/`array_agg`](https://www.postgresql.org/docs/9.4/sql-expressions.html#SYNTAX-AGGREGATES). We should support this in ibis as well.

**Comment by cpcloud** [comment]
One question is whether this should be included in all aggregates, including `Sum`, `Mean` etc.

**Comment by cpcloud** [comment]
This could be useful, but let's wait until someone asks for it.

**Comment by judahrand** [comment]
@cpcloud Can we reopen this?

**Comment by cpcloud** [comment]
Yep!

**Comment by cpcloud** [comment]
@judahrand In the mean time if you're blocked, you can always use `.sql` for something that doesn't (yet) have an ibis equivalent.

**Comment by cpcloud** [comment]
I think for the `DESC` `LIMIT 1` syntax we won't bake that into `collect()` but will allow this syntax:

```python
ibis.array(t.select("value").order_by(ibis.desc("timestamp")).limit(1).subq())  # subq doesn't exist
```

Otherwise aggregate functions end up with a bunch of mostly unused arguments that emulate a `SELECT` statement.
