### ISSUE TITLE
No equijoin expression found error for Cross JOIN ?

### ISSUE THREAD

**Issue by chowyik** [ibis-project/ibis#2935]
SELECT rdate as rdate
      , stime / 100 as stime
      , ttime /100 as etime 
      , c as endreturn 
      ,upsteps.steps as urange 
      , downsteps.steps as drange 
      , CASE WHEN Uptime.MinTime IS NULL THEN 2555 ELSE Uptime.MinTime END  as utime 
      , CASE WHEN Downtime.MinTime IS NULL THEN 2555 ELSE Downtime.MinTime END  as dtime 

   FROM HL as A
   Cross JOIN upsteps
   Cross JOIN downsteps

   OUTER APPLY (SELECT MIN(ttime) /100 AS MinTime FROM HL as B WHERE B.rdate = A.rdate AND B.ttime > A.stime AND b.ttime <= A.ttime AND H > upsteps.steps ) as Uptime
   OUTER APPLY (SELECT MIN(ttime) /100 AS MinTime FROM HL as C WHERE C.rdate = A.rdate AND C.ttime > A.stime AND C.ttime <= A.ttime AND L < downsteps.steps ) as Downtime
    WHERE rdate / 100 = 201103

I run the code above and raised error as follows ... 

Hash join failed, reason(s): No equijoin expression found | Cannot fall back to loop join for intermediate join quals

I used Cross join..

**Comment by datapythonista** [comment]
Can you provide the python/ibis code, and the full traceback please?

**Comment by cpcloud** [comment]
@chowyik It loos like this error is coming from a specific backend, since ibis doesn't know anything about specific join algorithms like hash/nested loop/merge.

If you show the ibis code here we might be able to help you figure out a way to express what you want while hopefully avoiding the cross join

**Comment by cpcloud** [comment]
Without more information this issue isn't actionable.
