### ISSUE TITLE
test: use pytest fixtures to initialize and populate the backends

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#2952]
I propose to port the click commands from `datamgr.py` and `impalamgr` to pytest fixtures (with `scope="session"` to execute once per pytest invocation).

The python testing suite is dependent on the files under the `ci/` directory. Examples:

`PYTEST_BACKEND=pandas pytest ibis/backends` or `pytest --enable-pandas ibis/backends` should:
1. Check that the testing data exists under the target directory
2. If not, download it otherwise skip
3. Execute the tests with pandas marker enabled

`PYTEST_BACKEND=clickhouse pytest ibis/backends` or `pytest --enable-clickhouse ibis/backends` should:
1. Check that the testing data exists under the target directory
2. If not, download it otherwise skip
3. Check that the required tables exist in clickhouse
4. If not, populate the tables otherwise skip
3. Execute the tests with clickhouse marker enabled

We can add pytest flags to `--force-download`/ `--skip-download` and `--force-populate`/`--skip-populate` the requested backends. 

Even though the first run would take more time since it would implicitly download the data (the second run would be instant), new contributors could use the a single `pytest` command to execute the testing suite. We can add additional logging / progress bar to inform the developer about the data[base] initialization.

**Comment by datapythonista** [comment]
This makes a lot of sense to me. Another option I was thinking was to build docker images with the data already loaded. Instead of pytest fictures we would have docker files replacing datamgr.py. and we wouldn't need to run anything on the CI. Just load the docker container in services.

But the approach here is surely much better than what we've got now. Happy with it too.

**Comment by kszucs** [comment]
That's a possible improvement, though we should evaluate how much time it takes to download the testing data with GHA's bandwidth. Also the docker containers must be downloaded at each run, so we may not benefit from it at all.

**Comment by datapythonista** [comment]
Agree. Not sure about time, whether the extra download time would be more or less that the time saved in loading the data to the engines. I think the main advantage would be the simplicity. Once the docker images are generated, we don't need to care about scripts for loading the data or anything related in the CI. Also, for local testing, would make things easier. But I agree, we should evaluate the implications, but worth considering IMO.

**Comment by cpcloud** [comment]
I think we should avoid making outbound connections to the internet a hard requirement for testing. I would like to be able to run tests with existing downloaded data, and not have to worry about an unreliable resource to run tests.

How about a middle ground where we keep `datamgr.py download` (maybe rename it to something else, and move it to a one line `curl` script?) but replace all the data loading with the proposed fixtures?

**Comment by jreback** [comment]
> I think we should avoid making outbound connections to the internet a hard requirement for testing. I would like to be able to run tests with existing downloaded data, and not have to worry about an unreliable resource to run tests.

there is probably a pytest-y way to do this, we have this really old decorator in pandas: https://github.com/pandas-dev/pandas/blob/master/pandas/_testing/_io.py#L104

**Comment by kszucs** [comment]
Thanks Jeff for the reference! I'm fine with both solutions.

**Comment by xmnlab** [comment]
that sounds very nice.

just an extra comment here, sometime ago I tried to use the fixture session approach for creating and removing database for tests, but it didn't work for me because it was conflicting with other things. 

in my case I needed to use: `pytest_sessionstart(session)`and `pytest_sessionfinish(session, exitstatus)`.

**Comment by anjakefala** [comment]
I would like to learn about Ibis, and have a bundle of experience with `pytest`. I would like to pick up this issue, if no one else is currently working on it.

The approach I currently want to take is the one outlined by @cpcloud:
> How about a middle ground where we keep datamgr.py download (maybe rename it to something else, and move it to a one line curl script?) but replace all the data loading with the proposed fixtures?

But, this may change after beginning to take a look at it. 

I want to evaluate this as part of the work:
> we should evaluate how much time it takes to download the testing data with GHA's bandwidth.

**Comment by cpcloud** [comment]
Heck yeah!

Welcome @anjakefala.

Right, `download` is very simple and does a `git clone` of `ibis-project/ibis-testing-data`. Feel free to take a look at it, but it's pretty bare bones.

The bulk of the work is going to be in figuring out how to move all the functionality in the `load` subcommands like

```python
python ci/datamgpr.py load postgres
python ci/datamgpr.py load duckdb
```

into a `pytest.fixture` (that was my initial thought, not set in stone in any way).

**Comment by anjakefala** [comment]
There are a lot of configurable settings in the `click` `load`s.

For e.g. for the postgres:

```
@click.option(
    '-p',
    .....
    default=5432,
    envvar="PGPORT", "IBIS_TEST_POSTGRES_PORT"],
    ....
```

I am making my best guess on reasonable `pytest` defaults based on what is in the conftest.py, and what the default settings are in `click.options`. But, if we actually need some of these loads to be configurable, or different from my guess at the default, that is going to be something to discuss in the PR. 

Am I right to set reasonable `pytest` defaults or is this something that needs to be configurable?

**Comment by anjakefala** [comment]
Found testing defaults in `ibis/backends{backend_name}/tests/conftest.py` !
