### ISSUE TITLE
CI: Enable auto merge?

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#2969]
Should we enable auto-merge so that we can "set it and forget it" once a PR is approved?

This is a couple clicks in the GitHub UI, but wanted to hear from maintainers before enabling this.

cc @jreback @datapythonista.

**Comment by jreback** [comment]
not a huge fan of the auto merge
we don't have that many prs

**Comment by cpcloud** [comment]
Cool, we can revisit this if we start getting lots of PRs :)
