### ISSUE TITLE
Issue: 1. Writing data to impala/kudu table from a pandas dataframe by using IBIS failed in CDP but worked in CDH.  Issue: 2. When you read an empty table in IBIS and try to execute the table_obj.execute() function to get the result, it failed in CDP but worked in CDH.

### ISSUE THREAD

**Issue by kancharana** [ibis-project/ibis#2982]
# Issue: 1
Writing data to impala/kudu table from a pandas dataframe by using IBIS failed in CDP but worked in CDH. 
# Issue: 2 
When you read an empty table in IBIS and try to execute the table_obj.execute() function to get the result, it failed in CDP but worked in CDH.
# Root Cause 
When a user creates a table in impala by not mentioning the stored as clause, In CDH 6.3.3 (impala 3.2), the default create table store format is TEXT but in CDP 7.2.10 (impala 4.0) it is PARQUET
# Bug in IBIS packages
There is no provision to mention the stored as clause for the "__ibis_tmp.ibis_tmp_pandas_<guid>" temp table creation. 
# When will this issue happen? 
When you read an impala table by using ibis and convert that as pandas dataframe (table_obj.execute()) and try to save the dataframe to another table. 
As part of this process, IBIS creates a temp table and stores that dataframe data as a .csv file, and then it saves it to the targeted table.
In CDH, the default table store clause (if not mentioned in the DDL) is TEXT but when it comes to the CDP, it is PARQUET
# Reference
https://docs.cloudera.com/cdp/latest/data-migration/topics/cdp-data-migration-impala-fileformats.html

# Error Details
errorCode=None, errorMessage='File \'hdfs://hanameservice/tmp/ibis/pandas_127ea94b7d6e4321be7bce37317b5369/0.csv\' has an invalid Parquet version number: 55 4c 4c a .\n
Please check that it is a valid Parquet file. This error can also occur due to stale metadata. If you believe this is a valid Parquet file, 
try running "refresh __ibis_tmp.ibis_tmp_pandas_127ea94b7d6e4321be7bce37317b5369".\n', hasResultSet=None)
Exception caused by SELECT count(*) AS `count`
FROM __ibis_tmp.`ibis_tmp_pandas_127ea94b7d6e4321be7bce37317b5369`: Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 120, in execute
    cursor.execute(query)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 238, in execute
    self._wait_synchronous()
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 263, in _wait_synchronous
    raise OperationalError("Operation is in ERROR_STATE")
impala.error.OperationalError: Operation is in ERROR_STATE

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 498, in insert
    writer, expr = write_temp_dataframe(self._client, obj)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/pandas_interop.py", line 124, in write_temp_dataframe
    return writer, writer.delimited_table(path)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/pandas_interop.py", line 105, in delimited_table
    persist=False,
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 1317, in delimited_file
    return self._wrap_new_table(name, database, persist)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 1428, in _wrap_new_table
    cardinality = t.count().execute()
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/expr/types.py", line 224, in execute
    self, limit=limit, timecontext=timecontext, params=params, **kwargs
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/client.py", line 383, in execute
    expr, limit=limit, params=params, timecontext=timecontext, **kwargs
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/client.py", line 222, in execute
    result = self._execute_query(query, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/client.py", line 229, in _execute_query
    return query.execute()
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/client.py", line 59, in execute
    self.compiled_sql, results=True, **kwargs
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/client.py", line 155, in _execute
    cur = self.con.execute(query)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 120, in execute
    cursor.execute(query)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 238, in execute
    self._wait_synchronous()
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 263, in _wait_synchronous
    raise OperationalError("Operation is in ERROR_STATE")
impala.error.OperationalError: Operation is in ERROR_STATE
>>>

# Table 1 for manual insert
CREATE EXTERNAL TABLE IF NOT EXISTS user_test.test_impala (                                                  
source_table_id BIGINT,
id BIGINT, 
id_dt timestamp,   
name STRING,                                                                                       
latitude bigint,                                                                                   
address STRING,                                                                                         
status STRING
)                                                                                                          
STORED AS PARQUET
LOCATION 's3a://preprod-bucket/test/user_test/test_impala';

# Table 2 for ibis insert with Pandas DF
CREATE EXTERNAL TABLE IF NOT EXISTS user_test.test_impala_new (                                                  
source_table_id BIGINT,
id BIGINT, 
id_dt timestamp,   
name STRING,                                                                                       
latitude bigint,                                                                                   
address STRING,                                                                                         
status STRING
)                                                                                                          
STORED AS PARQUET
LOCATION 's3a://preprod-bucket/test/user_test/test_impala_new';

# Python Code to read from and write into an Impala/Kudu table
The below code works perfectly in CDH but when it comes to the CDP it fails.
import ibis
ibis.options.verbose = True
import logging
logging.basicConfig(level=logging.DEBUG)

hdfs_host_name = "hdfs_host_name_or_active_name_node_host"
hdfs_port_number = "9871"

auth_mechanism = "GSSAPI"
ssl_cert_verify = "False"
kerberos_service_name = "impala"
use_ssl = "True"

ca_cert = "/var/lib/cloudera-scm-agent/agent-cert/cm-auto-global_cacerts.pem"
impala_host_name = "impala_coordinator_host_name"
impala_port_number = "21050"

db_name = "user_test"
tbl_name = "test_impala"
new_tbl_name = "test_impala_new"

ibis.options.sql.default_limit = None
hdfs = ibis.impala.hdfs_connect(host=hdfs_host_name, port=eval(hdfs_port_number),
                                auth_mechanism=auth_mechanism, verify=eval(ssl_cert_verify))
ibis_client = ibis.impala.connect(
                host=impala_host_name, port=eval(impala_port_number), hdfs_client=hdfs,
                kerberos_service_name=kerberos_service_name, auth_mechanism=auth_mechanism,
                use_ssl=eval(use_ssl), ca_cert=ca_cert
            )
            
query = "INSERT OVERWRITE TABLE user_test.test_impala VALUES \
 (2,1,'2018-10-07 11:21:00','abc',100,'123 abc','active'),\
 (2,2,'2018-10-06 11:21:00','def',200,'456 abc','closed'),\
 (2,3,'2018-10-05 11:21:00','ghi',300,'789 abc','active'),\
 (2,4,'2018-10-04 11:21:00','jkl',400,'012 abc',NULL),\
 (2,9,'2018-10-03 11:21:00','jkl',400,'012 abc',NULL),\
 (2,10,'2018-10-02 11:21:00','jkl',600,'012 abc',NULL),\
 (2,1,'2018-10-08 11:21:00','abc',100,'123 abc','active'),\
 (2,2,'2018-10-08 11:21:00','def',200,'456 abc','closed'),\
 (2,3,'2018-10-08 11:21:00','ghi',300,'789 abc','active'),\
 (2,4,'2018-10-08 11:21:00','jkl',400,'012 abc',NULL),\
 (2,9,'2018-10-08 11:21:00','jkl',500,'012 abc',NULL),\
 (2,10,'2018-10-08 11:21:00','jkl',600,'012 abc',NULL),\
 (2,10,'2018-10-09 11:21:00','jkl',700,'012 abc',NULL);"

ibis_client.raw_sql(query)

obj_table = ibis_client.table(tbl_name, database=db_name)
df_tbl = obj_table.execute()
df_tbl
tbl = ibis_client.table(new_tbl_name, database=db_name)
tbl.insert(obj=df_tbl, overwrite=False, partition=None, values=None, validate=False)

# Sample Show Create table on ibis temp table in CDH 6.3.3 (Impala Version 3.2):

 CREATE EXTERNAL TABLE __ibis_tmp.ibis_tmp_pandas_edeb7844496141cdaee93ef109eaa145 (                                                                                          
   source_table_id BIGINT,                                                                                                                                                    
   id BIGINT,                                                                                                                                                                 
   id_dt TIMESTAMP,                                                                                                                                                           
   name STRING,                                                                                                                                                               
   latitude BIGINT,                                                                                                                                                           
   address STRING,                                                                                                                                                            
   status STRING                                                                                                                                                              
 )                                                                                                                                                                            
 ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' ESCAPED BY '\\'                                                                                                                
 WITH SERDEPROPERTIES ('escape.delim'='\\', 'field.delim'=',', 'serialization.format'=',')                                                                                    
 STORED AS TEXTFILE                                                                                                                                                           
 LOCATION 'hdfs://hanameservice/tmp/ibis/pandas_403b3af64c9a479fb4615d85cd79a660'                                                                                             
 TBLPROPERTIES ('STATS_GENERATED_VIA_STATS_TASK'='true', 'numFiles'='1', 'numFilesErasureCoded'='0', 'numRows'='22', 'serialization.null.format'='#NULL', 'totalSize'='4924') 

# Sample Show Create table on ibis temp table in CDP 7.2.10 (Impala Version 4.0):

 CREATE EXTERNAL TABLE __ibis_tmp.ibis_tmp_pandas_127ea94b7d6e4321be7bce37317b5369 (                                                                      
   source_table_id BIGINT,                                                                                                                                
   id BIGINT,                                                                                                                                             
   id_dt TIMESTAMP,                                                                                                                                       
   name STRING,                                                                                                                                           
   latitude BIGINT,                                                                                                                                       
   address STRING,                                                                                                                                        
   status STRING                                                                                                                                          
 )                                                                                                                                                        
 ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' ESCAPED BY '\\'                                                                                            
 WITH SERDEPROPERTIES ('escape.delim'='\\', 'field.delim'=',', 'serialization.format'=',')                                                                
 STORED AS PARQUET                                                                                                                                        
 LOCATION 'hdfs://hanameservice/tmp/ibis/ibis_tmp_pandas_127ea94b7d6e4321be7bce37317b5369'                                                                
 TBLPROPERTIES ('OBJCAPABILITIES'='EXTREAD,EXTWRITE', 'numFiles'='1', 'numFilesErasureCoded'='0', 'serialization.null.format'='#NULL', 'totalSize'='607') 

# IBIS Code causing the issue:

https://github.com/ibis-project/ibis/blob/88ffe3367cb6a34936e578f6a9b68dc30d559507/ibis/backends/impala/pandas_interop.py
https://github.com/ibis-project/ibis/blob/88ffe3367cb6a34936e578f6a9b68dc30d559507/ibis/backends/impala/client.py

Function name in pandas_interop.py: def delimited_table(self, csv_dir, name=None, database=None)
Function name in client.py: def delimited_file(
        self,
        hdfs_dir,
        schema,
        name=None,
        database=None,
        delimiter=',',
        na_rep=None,
        escapechar=None,
        lineterminator=None,
        external=True,
        persist=False,
    ):

**Comment by kancharana** [comment]
Here is the log for Issue 2:
obj_table = ibis_client.table("test_impala_new_empty", database="user_test")

>>> obj_table
ImpalaDatabaseTable[table]
  name: user_test.`test_impala_new_empty`
  schema:
    source_table_id : int64
    id : int64
    id_dt : timestamp
    name : string
    latitude : int64
    address : string
    status : string


obj_table.execute()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/expr/types.py", line 224, in execute
    self, limit=limit, timecontext=timecontext, params=params, **kwargs
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/client.py", line 383, in execute
    expr, limit=limit, params=params, timecontext=timecontext, **kwargs
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/client.py", line 222, in execute
    result = self._execute_query(query, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/client.py", line 229, in _execute_query
    return query.execute()
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/client.py", line 61, in execute
    result = self._fetch(cur)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 295, in _fetch
    df = _column_batches_to_dataframe(names, batches)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 310, in _column_batches_to_dataframe
    return pd.DataFrame(cols, columns=names)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 196, in init_dict
    nan_dtype)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1175, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
>>>

**Comment by cpcloud** [comment]
@kancharana Thanks for the report. I wonder if there's a way we can bypass the temporary table creation altogether. The need to do that creates other annoying problems like having to make sure those tables get cleaned up at some point.

**Comment by gforsyth** [comment]
Hey @kancharana !
Impala is not being actively developed right now so I'm going to go ahead and close this out.
