### ISSUE TITLE
question: thread safety

### ISSUE THREAD

**Issue by roveo** [ibis-project/ibis#2988]
Hi! I'm investigating if I can use Ibis as a backend in an analytics web app.

Is Ibis thread-safe? What happens if I execute the same expression from multiple threads? Is it backend-specific? What about connection pooling and such?

**Comment by cpcloud** [comment]
Hi @roveo.

Great question.

As you allude to, ibis's thread safety is almost exclusively dependent on what backend you're using.

The support for executing queries in multiple threads varies quite a lot by backend, and sometimes even within a backend (SQLite comes to mind there, you can adjust thread safety at compile time).

That said, if you observe a problem executing ibis expressions in multiple threads please open an issue and we can triage it here to see whether it might be an ibis issue, a middleware issue (e.g., SQLAlchemy), or a backend issue/limitation.

You should be able to execute ibis expressions in multiple threads if the backend supports it so if you can't that's probably a bug in ibis that we need to fix.

**Comment by cpcloud** [comment]
Regarding connection pooling: all connection pooling is handled by SQLAlchemy where possible, that is, backends compiling to SQLAlchemy expressions.

The sole exception is the Impala backend, where there's a very primitive thread pool implemented using a `collections.deque`.

**Comment by cpcloud** [comment]
@roveo Do any of my responses answer your question(s)?

**Comment by roveo** [comment]
@cpcloud yes, thank you
