### ISSUE TITLE
feat: support non-equality join predicates

### ISSUE THREAD

**Issue by emilyreff7** [ibis-project/ibis#2996]
Most if not all ibis backends raise an error on non-equality join predicates. It would be nice to start to support this.

**Comment by cpcloud** [comment]
Interesting, I really thought we had some testing around this for the backends that support them like sqlite, mysql, and postgres.

**Comment by emilyreff7** [comment]
Ah I missed this `and not self._non_equijoin_supported` in the SQL backends which is set to True above: https://github.com/ibis-project/ibis/blob/master/ibis/backends/base/sql/compiler/query_builder.py.

We do raise in other backends though that could support it, e.g. Pyspark supports non-equi joins directly, while Pandas and Dask could support it with additional filtering.

**Comment by cpcloud** [comment]
I think it would be good to support this in the various backends that do support it, but a PR from an interested party is needed. Currently, I'm not sure there's anyone interested in inequality joins for backends that don't already support them.

Marked as a good first issue, would happily accept a PR, but no reason to keep the issue open for now.
