### ISSUE TITLE
feat: support suffixes in join API

### ISSUE THREAD

**Issue by emilyreff7** [ibis-project/ibis#2997]
Ibis' `join` API does not currently accept suffixes as a parameter, leaving backends to either use some default value or raise an error at execution time. It would be nice to directly support suffixes in the API itself.

**Comment by cpcloud** [comment]
This seems like a nice usability improvement.

**Comment by emilyreff7** [comment]
As I looked into this more, it started to make sense why ibis currently uses default internal constants for suffixes rather than exposing them in the join API. Based on my understanding, I think exposing suffixes at the API-level would simultaneously require some refactoring of the current `Join` vs. `MaterializedJoin` design. @cpcloud if you could please check my understanding of this and/or provide insight on the origins of this design, that would be very helpful!

Let's say this is our table set-up:

A:
|key | value|
|-----|------|
|1 | 10|
|2 | 20|

B:
|key | value|
|-----|------|
|1 | 30|
|2 | 40|

The following code raises an error:
```
>>> A.join(B, 'key').execute()
...
ibis.common.exceptions.IbisError: Table operation is not yet materialized
```
This is because `Join` claims that it does not have a schema [here](https://github.com/ibis-project/ibis/blob/master/ibis/expr/operations.py#L1743) (at the same time, it does define `_get_schema` which is a bit confusing).

The only way to actually execute any join expression in ibis is to do a projection on it immediately after, e.g. 
```
>>> A.join(B, 'key')[A.key, B.value].execute()
   key  value
0    1      3
1    2      5
```
Also, the projection cannot use string column names since that leaves room for ambiguity, e.g. 
```
>>> A.join(B, 'key')['key', 'value'].execute()
...
ibis.common.exceptions.IbisError: Table operation is not yet materialized
```
Given this design, it makes sense that suffixes are purely internal - they only exist as arbitrary constants so that internal calls like `pd.merge` and `dd.merge` don't fail, but ultimately since the user has to do some projection on the joined expression of the left and/or right table columns, the suffixes will never make their way to the materialized result.

So it seems that exposing suffixes at the API layer would not make sense in the current design, unless we also refactored this concept of materialized/non-materialized Joins, e.g. `Join` would have to define and compute a schema to incorporate these suffixes at node-creation time - this would also obviate `MaterializedJoin` and suffix computation logic elsewhere in the execution stack.

I think ultimately my question is around the original motivation non-materialized Joins. With this design we're essentially forcing the user to resolve schema ambiguity by projecting the columns they want (and specifying their table origin). Couldn't we just as easily resolve that ambiguity ourselves by having `Join` define a schema (which would necessitate some sort of suffix computation at node-creation time)?
