### ISSUE TITLE
TST: hdf5 tests are skipped

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#2998]
It looks like most or all of the backend tests for the `hdf5` backend are skipped, because we're not creating any of the necessary testing data.

PR incoming.

**Comment by datapythonista** [comment]
I don't think we should skip tests if data is missing. We are explicit on which backends should be tested, so if we use `PYTEST_BACKENDS="hdf5"`, tests should fail if there is no data.

**Comment by cpcloud** [comment]
Agree. I'll open another issue about that.
