### ISSUE TITLE
refactor: remove ir.ExprList, ops.ExpressionList and ibis.expr_list()

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#3000]
My guess is that these constructs are a band aid for accepting multiple expressions instead of a single one - though I need to verify this. 

There is another operation called `ops.ValueList` which does almost the same but creates a `ir.ListExpr` instead.

According to a [github search](https://github.com/search?q=ibis+expr_list&type=code) the publicly exposed `api.expr_list()` function is not widely used.

**Comment by datapythonista** [comment]
Checked that in the past, and I didn't find a use case for those, so happy to see them removed.

**Comment by cpcloud** [comment]
@kszucs Is this done?

**Comment by cpcloud** [comment]
Done in #3112
