### ISSUE TITLE
refactor: move methods implemented in Client to corresponding Backend methods

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#3017]
xref #2678

Follow up of discussion in #3014

Seems like it's quite challenging at this point to make `Backend.connect()` methods return an instance of `Backend. See [this comment](https://github.com/ibis-project/ibis/pull/3014#issuecomment-927156539) for a list of the possible options we've got.

Regardless of implementing this particular change (making `connect` return `Backend` instead of `Client`), we've been working on moving methods from `Client` classes to `Backend` classes, and then creating a proxy method in `Client` that calls the method in the new location. This was done while standardizing the API.

A first step towards the new backend API structure would be to finish moving all the remaining methods. This will need to eventually be done. And even if we don't fully remove `Client`, or if the API is not fully specified or standard, it'll greatly simplify the code of backends having all methods in the same classes, and not arbitrarily split between `Client` and `Backend`.

To move forward with this approach, the next PRs will be open:
- Delegate all objects not found in `Client` to the corresponding `Backend` instance
- Move methods from `Client` classes into `Backend`, one backend at a time

**Comment by cpcloud** [comment]
Partially addressed by #3127.

**Comment by cpcloud** [comment]
@datapythonista Does #3127 fully address this issue?
