### ISSUE TITLE
feat: finish defining Backend public API

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#3019]
xref #2678

The new `BaseBackend` started defining what is expected from backends to implement, and gives a user an standard API on what to expect. Many attributes have been standardized and defined there, such as `name`, `version`, `connect`, `list_tables`... But since it's very time consuming to define the huge Ibis backend API, we ended up adding all existing methods in `Client` classes into the specific `Backend` methods of each backend. Without having an abstract method to standardize signatures among backends, and define what's part of the Ibis backend API (and what are custom backend methods).

A list of what has been moved without standardizing exists in `ibis/backends/base/client.py`, in the `Client` class, which is a proxy of what clients implement, since `Client` doesn't define the methods anymore, but `Backend`.

**Comment by cpcloud** [comment]
xref: #2307 

Thanks @datapythonista! We're going to close this out, and tackle as part of #2307.
