### ISSUE TITLE
test: pandas and dask backends tests are not inferring the correct schema

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#3020]
The next tests were xfailed because pandas and dask don't implement `drop_table`, even if it seems somehow unrelated:

- `ibis/backends/tests/test_client.py::test_create_table_from_schema`
- `ibis/backends/tests/test_client.py::test_nullable_input_output`

When executed, the tests fail because nullable fields in the schema are not nullable in the created table.

We moved to xfail the tests only when `create_table` is not implemented, ignoring `drop_table`, which is not used in the test. Manually xfailing the tests for pandas and dask in #3018, but we probably want to revisit this, and see if it's a bug.

**Comment by cpcloud** [comment]
The reason `create_table_from_schema` is failing is unrelated to the presence of nulls.

Again, xfailing tests without understanding why they are failing leads to a bunch of work that has to be done later.
