### ISSUE TITLE
test: clarify fixtures once Backend replaces Client

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#3021]
We've got three main fixtures to access backends from backend tests:

- `backend`: An instance of `BackendTest`
- `con`: The instance of `Client` after connecting to the backend
- `backend_instance`: The `Backend` instance related to `con`

The name `backend` is misleading, since seems to be `Backend`, but it's `BackendTest` instead. When `Client` and `Backend` are fully merged, we should just have one fixture named `backend`.

I think it'd be a good idea, to instead of having independend `BackendTest` classes, to have an attribute of `Backend` named for example `Backend._test_config`, where the stuff in `BackendTest` can be accessed, and it's not necessary to have one specific fixture for it.

**Comment by cpcloud** [comment]
xref: #3017
