### ISSUE TITLE
Environment can't solve with conda for ibis-framework 2.0.0 package 

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#3041]
Seems like the problems we used to have in the CI, with conda not solving an environment because having too many backend dependencies is now happening to our newly released `ibis-framework=2.0.0`.

Tried with a clean environment and just our package for 10 minutes until I cancelled, and conda couldn't solve:
```
(base) [mgarcia@xps ~]$ time conda create -n ibis2only ibis-framework
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | / \ / \ 
real	10m57.168s
user	10m28.621s
sys	0m5.524s
```

Personally, I would move the next backends to their own repos, own pypi packages, and own conda-forge packages:
- Impala
- Clickhouse
- Dask
- PySpark

I don't think this will only help with dependencies and packaging, but also with maintenance. Besides allowing backends to release more often than Ibis itself.

**Comment by cpcloud** [comment]
Why don't we observe this problem in our current CI?

**Comment by cpcloud** [comment]
Is this a problem for ibis to solve though? It seems like this is an issue with conda's implementation, for the developers of conda to solve.

Many (most?) production environments have a *far* larger closure than the ibis package and its dependencies. Of course, a bigger closure doesn't necessarily a long solve time so there's probably some specific set of dependencies that is particularly difficult for conda to resolve here.

To me that suggests we should try giving conda a bit less wiggle room for solving.

Can we try constraining dependencies using semantic versioning-style constraints?

We'd move most dependencies to be constrained between the current major version and the next.

**Comment by datapythonista** [comment]
I agree conda should fix the solver, but the question to me is if `conda install ibis-framework` should work, and if it should, we need to do something to make it work with conda as is. Conda solver has been broken for years, and I don't think a fix in their side is expected anytime soon.

Regarding constraining versions, I used to do that regularly for the CI (until I moved it to mamba). Not a good experience with constraining, and even after fixing the problem was back just few weeks later. Feel free to give it a try if you want.

In any case, not only for the dependencies problem, but also for scalability in the number of backends, I think we shouldn't have backends in this repo or in the ibis-core package. Maybe few exceptions like pandas or sqlite are fine, but I personally think things will be easier if backends are maintained separately. Some of the advantages I see:
- No scalability problems as the number of backends grow (Google developed like 5 more for a tool they've got, and afaik they will eventually publish them independently)
- Backends should mostly have code specific to the engine they support, and specialized maintainers should be better than general Ibis devs
- Having them separate makes it easy for backends to be replaced (like Impala being replaced by a new SQLAlchemy backend)
- It also can be helpful for projects other than Ibis to use them (I guess having the translation of SQL dialects is not only useful for Ibis). Or even Ibis itself could get competitors
- Being able to release backends faster than Ibis itself

Do you think it's better to have many backends in this repo? If you think so, is there a criteria for which, or would you have all them (maybe 25) in this repo? And what are the advantages?

**Comment by jreback** [comment]
@datapythonista you are saying that we separate the repos, ok that's fine. but we cannot do that YET because it breaks the world. 
sure one by one these backends can be removed but needs to be done piece by piece. You make good points, but let's go slow.

**Comment by xmnlab** [comment]
maybe something simple we could do is to create an extra output (e.g. https://github.com/conda-forge/omniscidb-feedstock/blob/master/recipe/meta.yaml#L31) for ibis-framework-feedstock, maybe ibis-core, just with the core dependencies. 

we will keep the ibis-framework with no changes and we will provide this extra package that would help  independent backends or anyone who wants to just install the core library.

If I am not interpreting it wrong ... the core depends on these libraries: https://github.com/ibis-project/ibis/blob/master/requirements.txt

**Comment by xmnlab** [comment]
I opened a PR on ibis-framework-feedstock following the idea I presented in the comment above. https://github.com/conda-forge/ibis-framework-feedstock/pull/57

A review would be very appreciated. Let me know if it is ok to address that into that feedstock or if I should create a new one independent.

**Comment by cpcloud** [comment]
This works when using `mamba`. Unfortunately, we can't continue to support things that won't get fixed upstream (in conda in this case).
