### ISSUE TITLE
chore(deps): drop 3.7

### ISSUE THREAD

**Issue by jreback** [ibis-project/ibis#3052]
prob no hurry, but others are dropping at the end of the year (pandas / numpy)

**Comment by goodwanghan** [comment]
I think 3.7 is still widely used, are you sure you want to do it now?

**Comment by jreback** [comment]
numpy pandas and the rest of the eco system have dropped 3.7

3.10 is already out and 3.11 is around the corner

supporting more than 3 versions is way too much

**Comment by cpcloud** [comment]
@goodwanghan We're planning on adopting [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html) going forward to avoid having to support so many versions.

3.10 still isn't quite there yet for the `conda-forge` ecosystem, for example all of our development dependencies cannot be turned into a conda lock file yet. It's very close though and I don't think it's a blocker for dropping 3.7.
