### ISSUE TITLE
test: consolidate timecontext tests

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#3109]
Currently, there are separate timecontext tests for each backend
- [Pandas](https://github.com/ibis-project/ibis/blob/master/ibis/backends/pandas/tests/execution/test_timecontext.py)
- [Dask](https://github.com/ibis-project/ibis/blob/master/ibis/backends/dask/tests/execution/test_timecontext.py)
- [PySpark](https://github.com/ibis-project/ibis/blob/master/ibis/backends/pyspark/tests/test_timecontext.py)

There is duplication, especially across the Pandas and Dask backend tests for timecontext

To be able to consolidate our timecontext tests, we need a shared test dataset that has a `time` column (see https://github.com/ibis-project/ibis/pull/3104#discussion_r742055012). Then we can define shared tests in a `ibis/backends/tests/test_timecontext.py` and remove the backend-specific tests for this.

**Comment by cpcloud** [comment]
@timothydijamco Are you planning on tackling this issue any time soon?

**Comment by cpcloud** [comment]
Closing. Feel free to submit a PR!
