### ISSUE TITLE
feat: implement dropna for SQL backends

### ISSUE THREAD

**Issue by emilyreff7** [ibis-project/ibis#3110]
See #3097 which introduces support for Pandas, Dask, and Pyspark.

**Comment by cpcloud** [comment]
Thanks for making the issue. This is actually a good first issue I think.

**Comment by Abhijnan-Bajpai** [comment]
Hey @cpcloud I would like to work on this. Could I be assigned?

**Comment by cpcloud** [comment]
@Abhijnan-Bajpai Sorry for the delay! Feel free to work on the issue without being assigned! I've assigned you now though :)

**Comment by Abhijnan-Bajpai** [comment]
Thanks, I'll try getting this done asap.
