### ISSUE TITLE
feat: allow dicts in ibis.literal for structs

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#3118]
Currently a struct must be an `OrderedDict`, but since 3.6 there's no reason we can't allow at least `dict`s any possibly any mapping:

```
>>> import ibis
>>> ibis.literal({"a": "b", "c": "d"}, type="struct<a: string, c: string>")
TypeError: Value {'a': 'b', 'c': 'd'} cannot be safely coerced to struct<a: string, c: string>
```

**Comment by jjram20** [comment]
\take

**Comment by jjram20** [comment]
I would like to take this issue. /take

**Comment by cpcloud** [comment]
@jjram20 Cool, just write only `/take`!

**Comment by jjram20** [comment]
Hi, did it work now?

**Comment by jjram20** [comment]
```/take```

**Comment by cpcloud** [comment]
It might be backed up in the CI queue, give it a few minutes.

**Comment by saulpw** [comment]
We're going to keep `ibis.literal()` as it is for constructing plain literal expressions (int, float, string, etc), and add new constructors for compound literal expressions, just like the existing `ibis.array()`:

- `ibis.struct()`
- `ibis.map()`

These new constructors take a Python `dict` as the value, and an optional `type` kwarg like `ibis.literal()` (this `type` kwarg is also added to `ibis.array()` for symmetry).  `struct()` creates a literal value expression in which the field names and value types are fixed, and the value types can be heterogenous within the same struct.  `map()` creates a literal value expression in which the types of the keys and values are fixed and homogenous, but which can have any set of key/value pairs (and any number of them).

`literal()` will still continue to work as it has (e.g. it needs an `OrderedDict` specifically to construct a StructValue), but these special constructors should be preferred for non-plain literals in new code.
