### ISSUE TITLE
Option keys cannot have more than 2 levels?

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#3145]
It looks like while fixing mypy issues (https://github.com/ibis-project/ibis/issues/2823) there was an interface change to options: https://github.com/ibis-project/ibis/commit/c2000c2ef11ce7c14672fc7a0b575d36d2107138#diff-0f9cc26677da8931e7536cb28b981ad29623420291ee197ad5f4d3eaa217793aR573 such that you cannot have more than two levels. 

Is this limitation necessary? We currently use a nested structure to set backend specific options.

cc @jreback

**Comment by jreback** [comment]
yep this should be reversed

**Comment by cpcloud** [comment]
@gerrymanoim @jreback What's the plan here? What's the urgency?

**Comment by jreback** [comment]
we are internally updating to ibis 2.0; we were substantially delayed because we needed ibis-bigquery compatibility which is now resolved. It turns out a number of things broke / unintentiallly changed during a lot of the refactorings, this is one of them.

**Comment by cpcloud** [comment]
Cool. Glad to hear y'all are updating. Happy to squash whatever arises.

**Comment by gerrymanoim** [comment]
@cpcloud - I'll grab this one, wanted to triage our internal stuff first and make all the open source changes at once.
