### ISSUE TITLE
ibis.expr.datatypes.parse_type raises parsy.ParseError not IbisTypeError

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#3147]
This changed during the refactor to using parsy. Is this intended? If so, should we remove `IbisTypeError`? Otherwise should we try/except to raise `IbisTypeError`

**Comment by jreback** [comment]
yeah i think we should retain the original error type here

**Comment by cpcloud** [comment]
The reason the error was changed was because the error is a parse error not a type error. In other words, there are no ibis types in play when a parse fails since they're still in the process of being parsed.

**Comment by gerrymanoim** [comment]
Thanks for the clarification - will fix on our side.
