### ISSUE TITLE
Should VectorizedUDF `func_args` accept `ibis.expr.types.TableExpr`

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#3150]
As best as I can tell this is a behavior change, but I'm not entirely if the change is intentional/behavior should be supported. 

If you have a `TableExpr` and perform a selection on it, you get a back a `TableExpr`. If you pass that to `VectorizedUDF`, it fails validation of `func_args` https://github.com/ibis-project/ibis/blob/52fa8a97faf5856e0c7b05f52ad461f117c066b2/ibis/expr/operations/vectorized.py#L14, as `TableExpr` is ultimately not a value expression. `rlz.column(rlz.any)` -> `instance_of(ir.ColumnExpr, inner(arg, **kwargs))` where inner is `value`, and you'll get an exception here: https://github.com/ibis-project/ibis/blob/faa2c368bfd56a34813ceba962bf98540f061312/ibis/expr/rules.py#L241. 

So I think the validator is correct, but I wanted to confirm this understanding/behavior.

**Comment by cpcloud** [comment]
@gerrymanoim do you have an example of this breaking?

It's certainly possible that this might be a regression. Would be useful to have a breaking example to add to a test

**Comment by gerrymanoim** [comment]
Sorry - please ignore this. Bad ibis usage on our part.
