### ISSUE TITLE
Allow column_from to take `ColumnExpr` 

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#3152]
Right now `rlz.column_from` https://github.com/ibis-project/ibis/blob/master/ibis/expr/rules.py#L426 only allows you to pass `str` and `int`. Given that it is returning the column itself, I'd like to change this to allow it to take a `ColumnExpr` and pass it through unchanged. 

cc @jreback

**Comment by cpcloud** [comment]
`rlz.column_from` should not accept arbitrary `ColumnExpr`s, it's designed to be a rule that pulls out a column from a child table by name or schema index. Passing `ColumnExpr`s through without validation would allow invalid columns through.

It'd be fine to allow them through if the result of accessing them by name or index equals the input column expression, though that seems redundant.

@gerrymanoim Can you describe the use case a bit more?

**Comment by cpcloud** [comment]
@gerrymanoim If you just want to allow any column expression, you can use `rlz.column(rlz.any)` for that.

**Comment by gerrymanoim** [comment]
We have certain logic that takes ibis nodes and rewrites them, creating a new operation. Because we can't pass a `ColumnExpr`, we can't take the arguments from something like a `DropNa` and pass them in again to a new `DropNa`. This we now need to special case, just to extract the column names from the list of column exprs, so we could pass them back in again. 

I'd be fine checking if the root table is the same or if the getattr produces the same expr.

**Comment by cpcloud** [comment]
> I'd be fine checking if the root table is the same or if the getattr produces the same expr.

Cool, the latter sounds good to me. Want to PR it? It should be a pretty small change and test.
