### ISSUE TITLE
Clarify why EPS == 1e-13

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#3154]
Found this while closing issues with @gforsyth and @saulpw 

https://github.com/ibis-project/ibis/blob/faa2c368bfd56a34813ceba962bf98540f061312/ibis/backends/base/sql/compiler/select_builder.py#L491

**Comment by gforsyth** [comment]
It looks like this was first added in 3d4d2b4344f00e492ee486bd6c6801c3c2fd8bdb

**Comment by gforsyth** [comment]
Which squashed it from here: 8dac292b0dd7553afe41af16d544d5b391f7504e

**Comment by cpcloud** [comment]
Seems reasonably clear.
