### ISSUE TITLE
feat: support of arrays and tuples for clickhouse

### ISSUE THREAD

**Issue by hikitani** [ibis-project/ibis#3179]
I have column `score_history` in CH table with type `Tuple(Array(Float32), Array(DateTime))`. But ibis doesn't know what is this type.

I wrote wrapper for `ClickhouseDataType.__init__` and `ClickhouseDataType.to_ibis` outside of this project.  And it worked, but it looks terrible:). This allowed me to make only a simple selection.

**Comment by cpcloud** [comment]
Hi @hikitani, thanks for the feature request. I think we could support this by modeling tuples as `struct` types (with generated field names like `_0` or `f0` or similar), and we already have support for arrays.

Would that work?

**Comment by hikitani** [comment]
Do you mean to use the expression `select t.1 as t1, t.2 as t2 from table` for the tuple `t`?

**Comment by cpcloud** [comment]
@hikitani

Not quite. What I mean is that a `Type(Array(Float32), Array(DateTime))` would show up in ibis as `struct<_0: array<float32>, _1: array<timestamp>>` and you'd be able to access the `N`th element of the tuple as a field with name `_N`.

**Comment by hikitani** [comment]
That would look good.

**Comment by cpcloud** [comment]
Closed by #3185, thanks @hikitani looking forward to this in 3.0.0!
