### ISSUE TITLE
How to I use the HiveServer2Error exception in my code ?

### ISSUE THREAD

**Issue by floriancastelain** [ibis-project/ibis#3208]
With ibis 2.0.0 and the Impala backend, I need to catch the HiveServer2Error.

My use case is that, when the user does not specify a database when connecting, the HiveServer2Error exception is raised.

How can I import the HiveServer2Error so that I can catch it ?
If this is not the optimal way, how can I catch the fact that the connection failes/failed due to the database missing ?

**Comment by cpcloud** [comment]
@floriancastelain Can you show the code that's causing an error? It sounds like `ibis.impala.connect(...)` is raising an exception when you don't specify a database. Can you show the call to `ibis.impala.connect` that fails?

**Comment by floriancastelain** [comment]
```
try:
    database = ""
    impala = ibis.impala \
        .connect(host=impala_ip,
                 database=database,
                 hdfs_client=hdfs,
                 user=user,
                 password=password,
                 auth_mechanism='PLAIN')
    logging.info("ALL GOOD ?")
except HiveServer2Error as e:
    logging.error(e.__class__.__name__)
```

output:

`ERROR:root:HiveServer2Error`

**Comment by cpcloud** [comment]
@floriancastelain Thanks.

Are you sure that the empty string is a valid database? Ibis use `default` as the default database name. Does that not work for your use case?

**Comment by floriancastelain** [comment]
I am sure the empty string is NOT a valid database. But this is exactly what I want to test here. If the `database` string is not valid, `connect` raises `HiveServer2Error`, and I need to catch it.

**Comment by cpcloud** [comment]
Ah! Thanks, got it.

You can access `HiveServer2Error` from the `impala` module, which **is not** part of the ibis package. You read that right.

```python
import impala  # the importable name of the impyla package


try:
    ...
except impala.error.HiveServer2Error:
    ...
```

For some reason, the `impyla` pip package's Python package must be imported as `impala`. I have no idea why they made the incredibly confusing choice to not use the distribution name as the package name.

**Comment by floriancastelain** [comment]
That is exactly what I need. Thanks !

Indeed, weird naming choice. But you know what it is said: "Why making it easy when you can make it complicated ?" (word to word translation of a saying from my place.

Have a good day !
