### ISSUE TITLE
feat(api): keep nulls in pandas backend in group by

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#3235]
In #3211, @goodwanghan points out that ibis's behavior for grouping keys with nulls isn't consistent across backends.

I am not aware of any SQL engines that drop nulls in grouping keys.

In fact, it's a hard blocker for a `GROUPING SETS` feature because grouping keys that are null indicate levels of a particular column that are aggregated over.

The idea is to pass `dropna=False` to `.groupby` invocations which will preserve null in outputs.

**Comment by goodwanghan** [comment]
Thank you, and also Dask needs to be tested.

**Comment by cpcloud** [comment]
cc @jreback, curious if this would cause big breakage for y'all

**Comment by jreback** [comment]
this prob should be fine as null key grouping is something we don't typically see

**Comment by goodwanghan** [comment]
Oh, by the way, when you test on Dask, please make sure you have multiple-group-key test cases. I remember that caused some troubles with my projects.

**Comment by cpcloud** [comment]
@goodwanghan Makes sense! Thanks.

**Comment by cpcloud** [comment]
We'll tackle this in 3.1

**Comment by cpcloud** [comment]
@goodwanghan After thinking about this some more, I think we're not going to prioritize this over other work right now. Originally, I thought it would be a straightforward thing to do and I just chucked it on the queue without thinking more about what it would entail.

This isn't out of scope for ibis generally, but we can't devote time to it right now.
