### ISSUE TITLE
feat(pandas): match SQL semantics in join with NaNs in join keys

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#3236]
Similarly reported in #3211, join keys with `nan`s do not follow the SQL semantic of dropping join keys where `==` would return NULL.

**Comment by goodwanghan** [comment]
Thank you this is awesome!

**Comment by cpcloud** [comment]
@goodwanghan This is an interesting problem.

Pandas handling of `NaN` here is consistent with the way in which `NaN`s are doubles, but it's not consistent of pandas using `NaN` as the NULL value. NULL values in a join predicate evaluate to `false`, so given the IEEE definition of NaN it's not surprising the semantics differ: NaN and NULL aren't the same thing.

However, since pandas treat `NaN`s as NULL in basically every other scenario it seems reasonable to favor the approach of treating NaNs as NULL in join predicates.

**Comment by goodwanghan** [comment]
So look at this code

```python
import pandas as pd

df1 = pd.DataFrame([[0.0, None], [pd.NA, "abc"], [float("nan"), "def"]], columns=["a", "b"])
df2 = df1.copy()

print(df1.merge(df2, on="a"))
print(df1.merge(df2, on="b"))
```

And the result:

```
      a   b_x   b_y
0     0  None  None
1  <NA>   abc   abc
2  <NA>   abc   def
3   NaN   def   abc
4   NaN   def   def
    a_x     b   a_y
0     0  None     0
1  <NA>   abc  <NA>
2   NaN   def   NaN
```

I think pandas treats (or tries to treat) nulls and nans in the same way in merge. For example in the string column, nulls are also joined together.
