### ISSUE TITLE
No pre-commit without nix?

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#3293]
Looks like https://github.com/ibis-project/ibis/commit/1e4c71fa0fe5615bcb8602a99bc07f27120ed8fb#diff-320a046d4946253b4b69d332e2c3ad4f81f1adbb50fd84945d9fcad88f1bccb2 deleted` .pre-commit-config.yaml `. 

Unless I'm missing something, that means you can't use pre-commit without setting up everything with `nix` and using `pre-commit.nix`. 

Is this correct? The dev instructions claim that we still support conda development: https://ibis-project.org/contribute/.

**Comment by cpcloud** [comment]
Hm, yep. `pre-commit` is currently handled by nix.

It might be possible to bring that back into the repo and leave nix out of it (and still work with both nix and conda!).

I will make sure to investigate this before the 3.0.0 release.

**Comment by gerrymanoim** [comment]
Even if we just added the file back for people doing local dev, that would probably be good enough.
