### ISSUE TITLE
bug: merge asof raises an error when the predicate column(s) are overlapping

### ISSUE THREAD

**Issue by jayceslesar** [ibis-project/ibis#3295]
Not sure how this is happening but I keep getting `ibis.common.exceptions.RelationError: Joined tables have overlapping names:`.

Both dataframes have 3 columns, where one column in each is `timestamp`. Unsure how that is happening, and unsure how [this test](https://github.com/ibis-project/ibis/pull/1162/files#diff-dd3a3bc8a96180b07abe227b7f3dd9edf5c5f75ec3d4303fa96755d0bbca07e0R732) even passes given I have the exact same scenario.

**Comment by cpcloud** [comment]
Hi @jayceslesar, thanks for the report.

Would you mind sharing the exact failing code?

**Comment by jayceslesar** [comment]
Sure can @cpcloud 

```py
import ibis
import ibis_bigquery


def merge_example():
    """do some math across signal_one current and signal_two voltage signals
       which are sampled at different rates but multiplied together to get
       more accurate values of power.
    """
    conn = ibis_bigquery.connect(
        project_id='some_project',
        dataset_id='some_dataset'
    )

    table = conn.table('some_table')

    signal_one = table[table['field'].contains('signal_one') & test['field'].contains('current')]
    signal_one = signal_one['value', 'timestamp_received', 'field']  # select columns we care about
    signal_one = signal_one.relabel({'value': 'current', 'field': 'signal_one'})

    signal_two = test[test['field'].contains('signal_two') & test['field'].contains('voltage')]
    signal_two = signal_two['value', 'timestamp_received', 'field']  # select columns we care about
    signal_two = signal_two.relabel({'value': 'voltage', 'field': 'signal_two'})

    merged = ibis.api.asof_join(signal_one, signal_two, 'timestamp_received')
```

**Comment by jayceslesar** [comment]
@cpcloud first idea is that there just needs to be a different case [here for as_of](https://github.com/ibis-project/ibis/blob/db512a89c14edc7e216558f2c051c4a0e905b543/ibis/expr/operations/relations.py#L182)?

**Comment by jayceslesar** [comment]
Definitely a nontrivial task to get this asof implemented....I am wondering if the above assumes that the tables are of equal size? As in my case they are not. This is something I am willing to work towards, although my SQL chops are far from my pandas ones. `tolerance` seems the most trivial to implement (just have an or clause that takes the difference either way, could ideally specify a positive only tolerance and a negative only tolerance as well)

**Comment by cpcloud** [comment]
@jayceslesar I've just been tinkering with this and found that this *might* be possible using window functions. Her's the rewrite of the StackOverflow answer using window functions:

```python
import ibis

cases = ibis.table(
    [
        ("id", "int64"),
        ("resolution", "string"),
        ("timestamp", "timestamp"),
    ],
    name="cases",
)

classification = ibis.table(
    [("id", "int64"), ("value", "string"), ("timestamp", "timestamp")],
    name="classification",
)

c = classification
c1 = c.view()

following = (1, None)
win = ibis.range_window(following=following, order_by="timestamp")
class_ = c.mutate(timeend=c.timestamp.min().over(win))

res = cases.left_join(
    class_,
    [
        cases.timestamp >= class_.timestamp,
        (cases.timestamp < class_.timeend) | class_.timeend.isnull(),
    ],
).select([cases.id, cases.resolution, cases.timestamp, class_.value])

print(ibis.impala.compile(res))
```

which produces:

```
SELECT t0.`id`, t0.`resolution`, t0.`timestamp`, t1.`value`
FROM cases t0
  LEFT OUTER JOIN (
    SELECT *,
           min(`timestamp`) OVER (ORDER BY 1000000 * unix_timestamp(`timestamp`) RANGE BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING) AS `timeend`
    FROM classification
  ) t1
    ON (t0.`timestamp` >= t1.`timestamp`) AND
       ((t0.`timestamp` < t1.`timeend`) OR (t1.`timeend` IS NULL))
```

The BigQuery backend is based on the Impala backed (though I don't know if they share any code), so this might work for you as a workaround.

**Comment by jayceslesar** [comment]
@cpcloud that was pretty awesome, was able to mimic the pandas functionality of `merge_asof` with the above on BigQuery.

It came out unsorted but that was because I did not `order by timestamp_received`.
When comparing the two in a plot we get the exact same graph after ordering.
(can't see the two traces here as they are in the same spot but take my word!)
![image](https://user-images.githubusercontent.com/47452474/149384477-0c793c3a-0cb7-466a-8939-225ddef9cc9f.png)

The full impala query that I threw into BigQuery looked like:
```
SELECT t0.`value`, t0.`timestamp_received`, t1.`value`, t1.`timestamp_received`
FROM (
  SELECT `value`, `timestamp_received`, `field`
  FROM (
    SELECT *
    FROM `my_table`
    WHERE regexp_contains(field, 'signal1') AND regexp_contains(field, 'current')
  ) t2
) t0
  LEFT OUTER JOIN (
    SELECT *,
           min(`timestamp_received`) OVER (ORDER BY `timestamp_received` RANGE BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING) AS `timeend`
    FROM (
      SELECT `value`, `timestamp_received`, `field`
      FROM (
        SELECT *
        FROM `my_table`
        WHERE regexp_contains(field, 'signal2') AND regexp_contains(field, 'voltage')
      ) t3
    ) t2
  ) t1
    ON (t0.`timestamp_received` >= t1.`timestamp_received`) AND
       ((t0.`timestamp_received` < t1.`timeend`) OR (t1.`timeend` IS NULL))

order by t0.`timestamp_received`
```
Did manually have to change some stuff but this means that there is a path forward

**Comment by jayceslesar** [comment]
Also want to document some what I believe to be best practices for a merge_asof (at least with timeseries)

- Should `some_table.left_join where` where `some_table` is the table that has less data, means we are copying less data and are closer to what I believe is the truth
- `tolerance` should be configurable to go backward some tolerance, forward some tolerance, or either way tolerance (whichever direction is closer to a difference of 0)

**Comment by cpcloud** [comment]
@jayceslesar You're dangerously close to a PR there. Care to try your hand? Happy to help as much as you need.

**Comment by jayceslesar** [comment]
Definitely going to take me some time to figure out where to place this...don't want to introduce any breaking changes and need to familiarize myself with the API...
