### ISSUE TITLE
feat: rethink expr repr

### ISSUE THREAD

**Issue by emilyreff7** [ibis-project/ibis#3334]
### Context
By default, `Expr`'s repr does a tree traversal to give a [representation of the full expression tree](https://github.com/ibis-project/ibis/blob/a3583c3ffd711a220d9269d9f13f98ec68b99f8f/ibis/expr/format.py#L68). While this repr can contain useful debugging information, it can also have adverse performance implications that are difficult to catch until after the fact. Performance regressions can occur for example when the repr is included in error messages, particularly when the tree is large and/or when the repr is requested in a tight loop (e.g. within an error message that is hit on validation of each table column, which itself may be called within an arbitrary-sized loop depending on user code).

### Proposal
To avoid future performance regressions, it may be beneficial to rethink the default repr for expression trees. Perhaps a more reasonable approach would define a simpler, constant-time implementation for `__repr__`, and also expose a new `Expr` method (e.g. `explain`, `inspect`, `info`, etc.) that would display the entire expression tree. If we go this route, we should decide what exactly to include in the repr (e.g. the type of the expr, any schema information? column names but up to a set limit?)

### Relevant PRs
https://github.com/ibis-project/ibis/pull/2917
https://github.com/ibis-project/ibis/pull/3335

**Comment by saulpw** [comment]
I think this is a good idea, @emilyreff7.  How about `.get_repr()` with a kwarg to indicate how much information to display (by default the entire tree), and then `__repr__()` would call something like `.get_repr(depth=None)`?

**Comment by cpcloud** [comment]
Closing this out, we've got a much improved repr in both UX and speed.
