### ISSUE TITLE
RFC: Vectorized UDF interface rethink

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis#3336]
In 2020 I introduced the Vectorized UDF API in ibis (currently works on pandas, PySpark and Dask backend). The API for defining UDFs are decorator based, e.g.:

During the past two years of building a time series analysis API internally, we've adopted an UDF API is a bit different. From what we learned from the users, the internal API seems quite more convenient comparing to the ibis API and therefore I'd like to open a discussion for potentially changing the ibis vectorized UDF API.

The following section I will lay out proposed API:

### Existing API
```
@udf.elementwise('double')
def plus(a: pd.Series, b: pd.Series) -> pd.Series:
      return a + b

t.select(plus(t['a'], t['b']))
```
 
### Proposed API
```
from ibis import functions as F

def plus(a: pd.Series, b: pd.Series) -> pd.Series:
    return a + b

t.select(F.map(plus, t['a'], t['b'], output_type='double'))
```

The main difference is that the decorator `elementwise` is replaced by `map` when invoking the UDF.

The benefit of the proposed API is:
* The shape of the UDF is specified on the line that the UDF is invoked, which makes it easier to read / reason the code. Imagine if `plus` in the existing API is defined very far away, then when reader see `t.select(plus(t['a'], t['b']))`, it's kind of hard to tell the shape of "plus". Whereas, in the proposed API, it's clear that it's doing a "map" operation.
* Make it easier to use existing function. For example, if I want to map a column with `scipy.stats.norm.ppf`, I can write it like this
```
from scipy.stats.norm import ppf
t.select(F.map(ppf, t['c'], output_type='double'))
```

For the proposed API, we can also allow the author of the UDF to decorate the UDF so that the user don't need to provide information like output_type, this is more of an advanced mode for people that want to write UDF libraries or define reused module, and used less frequently in one-off research code, e.g.

```
# Author code:
@udf(output_type='double', shape="n->n")
def foo(a):
    ...

# User code:
t.select(F.map(foo, t['a']))
```
In this case, the user code is similar, except for that the user doesn't need to specify "output_type" because it's defined by the UDF author.

There are a few small variations of the API for convivence but I don't want to overload with too much information here. 

Thoughts?

**Comment by saulpw** [comment]
@icexelloss Thanks for the proposal, this is interesting.  In particular, the ability to use existing functions like `ppf` easily would be very convenient.  However, the proposed `map` API is pretty different from existing Ibis APIs (more like Spark than Pandas?).  How does the API look alongside the reduction (like `mean`) and analytic (`row_number`) generators?

**Comment by icexelloss** [comment]
Good point. Let me think about this a bit more. Close this for now.
