### ISSUE TITLE
docs: bad link on team page

### ISSUE THREAD

**Issue by jmsdnns** [ibis-project/ibis#3390]
The [generated URL for the bad volunteers link](https://github.com/ibis-project/ibis-project.org/blob/master/about/team/index.html#L1573) looks like this: `https://github.com/https://github.com/ibis-project/ibis//graphs/contributors`

Just gotta delete the `https://github.com/` in front of `{{ config.repo_url }}` in [the template for the team page](https://github.com/ibis-project/ibis/blob/master/docs/about/team.md)

**Comment by cpcloud** [comment]
Thanks, on it.

**Comment by cpcloud** [comment]
Really appreciate the report!
