### ISSUE TITLE
Add support for Ray (modin?) and Rapids AI?

### ISSUE THREAD

**Issue by vv111y** [ibis-project/ibis#3399]
Any plans for this?

> Hey, can you also add the support for Ray (modin?) and Rapids AI? I think they are all similar

_Originally posted by @goodwanghan in https://github.com/ibis-project/ibis/issues/2245#issuecomment-657176380_

**Comment by cpcloud** [comment]
@vv111y Thanks for bumping the issue! cc @goodwanghan

There are two issues here: one for modin and one for cudf (assuming this is what you mean by Rapids AI)?.

We'd happily accept a PR and would work with the community on this, but this isn't on the immediate roadmap.
