### ISSUE TITLE
bug(testing): importorskip swallows valid import errors

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#3480]
Intentionally making an import error:

```diff
diff --git a/ibis/backends/base/sql/compiler/select_builder.py b/ibis/backends/base/sql/compiler/select_builder.py
index 86bfedc6..b5a6e970 100644
--- a/ibis/backends/base/sql/compiler/select_builder.py
+++ b/ibis/backends/base/sql/compiler/select_builder.py
@@ -5,7 +5,7 @@ import ibis.expr.analysis as L
 import ibis.expr.datatypes as dt
 import ibis.expr.operations as ops
 import ibis.expr.types as ir
-import ibis.util as util
+import ibis.common.util as util

 from .extract_subqueries import ExtractSubqueries
```

Causes to skip the builds instead of raising an `ImportError`

```
$ pytest -sv -m sqlite ibis/backends/tests/test_numeric.py
ibis/backends/tests/test_numeric.py::test_floating_mod[sqlite] SKIPPED (could not import 'ibis.backends.sqlite.tests.conftest': No module named 'ibis.common.util')
ibis/backends/tests/test_numeric.py::test_math_functions_literals[sqlite-round-digits] SKIPPED (could not import 'ibis.backends.sqlite.tests.conftest': No module named 'ibis.common.util')
ibis/backends/tests/test_numeric.py::test_complex_math_functions_columns[sqlite-log2] SKIPPED (could not import 'ibis.backends.sqlite.tests.conftest': No module named 'ibis.common.util')
...
```

I assume this is caused by `pytest.importorskip` in `_get_backend_conf()`.

cc @cpcloud

**Comment by cpcloud** [comment]
Yep, definitely a problem.

**Comment by kszucs** [comment]
> Wait, I didn't realize that this isn't actually happening right now.

We may have import errors not surfacing on the CI.

> Thoughts on how to go about making sure this doesn't happen in the future?

Making it mandatory to import `backend.TestConf`?

**Comment by cpcloud** [comment]
> > Wait, I didn't realize that this isn't actually happening right now.
> 
> We may have import errors not surfacing on the CI.

Ah, yeah you're right.

> 
> > Thoughts on how to go about making sure this doesn't happen in the future?
> 
> Making it mandatory to import `backend.TestConf`?

Yep, I'll look into it.
