### ISSUE TITLE
bug: sqlalchemy backends create unbound anon column when projecting a mutated column

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#3529]
A join with `batting` and `awards_players` works as expected:

    con = ibis.sqlite.connect("ci/ibis-testing-data/ibis_testing.db")
    batting = con.table("batting")
    awards_players = con.table("awards_players")
    awards_players
    left = batting
    right = awards_players
    expr = left.join(right, "yearID")
    expr.limit(10).execute()

If I `mutate` to rename a column in `batting` things still work:

    awards_players = con.table("awards_players")
    batting = con.table("batting")
    left = batting.mutate(year=batting.yearID)
    right = awards_players
    expr = left.join(right, left.year == right.yearID)
    expr.limit(10).execute()

But if I then create a projection with the newly created column it goes badly:

    awards_players = con.table("awards_players")
    batting = con.table("batting")
    left = batting.mutate(year=batting.yearID)
    left = left['year', 'RBI']
    right = awards_players
    expr = left.join(right, left.year == right.yearID)
    expr.limit(10).execute()

Fails with

    OperationalError: (sqlite3.OperationalError) no such column: anon_1.year
    [SQL: SELECT t0.year, t0."RBI", t1."playerID", t1."awardID", t1."yearID", t1."lgID", t1.tie, t1.notes
    FROM (SELECT t2.year AS year, t2."RBI" AS "RBI"
    FROM (SELECT t3."playerID" AS "playerID", t3."yearID" AS "yearID", t3.stint AS stint, t3."teamID" AS "teamID", t3."lgID" AS "lgID", t3."G" AS "G", t3."AB" AS "AB", t3."R" AS "R", t3."H" AS "H", t3."X2B" AS "X2B", t3."X3B" AS "X3B", t3."HR" AS "HR", t3."RBI" AS "RBI", t3."SB" AS "SB", t3."CS" AS "CS", t3."BB" AS "BB", t3."SO" AS "SO", t3."IBB" AS "IBB", t3."HBP" AS "HBP", t3."SH" AS "SH", t3."SF" AS "SF", t3."GIDP" AS "GIDP", t3."yearID" AS year
    FROM main.batting AS t3) AS t2) AS t0 JOIN main.awards_players AS t1 ON anon_1.year = t1."yearID"
     LIMIT ? OFFSET ?]
    [parameters: (10, 0)]
    (Background on this error at: https://sqlalche.me/e/14/e3q8)

The workaround is to create the column `year` separately and name it outside of `mutate`:

    batting = con.table("batting")
    awards_players = con.table("awards_players")
    year = batting.yearID.name("year")
    left = batting[year, 'RBI']
    right = awards_players
    expr = left.join(right, left.year == right.yearID)
    expr.limit(10).execute()

**Comment by cpcloud** [comment]
I think the issue may lie in this code https://github.com/ibis-project/ibis/blob/master/ibis/backends/base/sql/alchemy/query_builder.py#L91-L110.
