### ISSUE TITLE
feat(api): add support for local table

### ISSUE THREAD

**Issue by rtpsw** [ibis-project/ibis#3562]
A local table is like a named table except that it loads data from local files. It corresponds to `ReadRel.LocalFiles`.

**Comment by rtpsw** [comment]
https://github.com/ibis-project/ibis/pull/3563

**Comment by cpcloud** [comment]
@rtpsw Can we close this and #3563 out?

**Comment by rtpsw** [comment]
Not sure if you mean to cancel this, move the code into ibis-substrait (maybe unify with https://github.com/ibis-project/ibis-substrait/issues/100), or something else. I'd be happy to prepare a commit accordingly.

**Comment by cpcloud** [comment]
@rtpsw Looks like this can be closed.

We're going to tackle this in `ibis-substrait`.

**Comment by rtpsw** [comment]
> We're going to tackle this in `ibis-substrait`.

@cpcloud, where is this tracked?
