### ISSUE TITLE
feat(sqlite): concat nor join does not work on a string column

### ISSUE THREAD

**Issue by drabastomek** [ibis-project/ibis#3611]
This is specific to SQLite. Trying to use 

Quick example.

```python
import ibis
import pandas as pd

db = ibis.sqlite.connect('./example.db')
db.drop_table('test')
db.create_table('test', schema=ibis.Schema(names=['a', 'b'], types=['String', 'String']))

df = pd.DataFrame({'a': ['A', 'B', 'C'], 'b': ['A', 'C', 'E']})
db.load_data('test', df, if_exists='replace')

test = db.table('test')

sep = ibis.literal('-')
test.mutate(c = sep.join([test.a, test.b])).execute()
```

Neither the above nor this code works, albeit they throw different errors.

```python
test.mutate(c = test.a.concat(test.b))
```

The former code throws `OperationNotDefinedError: No translation rule for <class 'ibis.expr.operations.strings.StringJoin'>` while the latter one complains about `AttributeError: 'StringColumn' object has no attribute 'concat'`.

**Comment by cpcloud** [comment]
@drabastomek

The `StringConcat` operator is mapped to `+`, so you should be able to write `test.a + test.b`.

`StringJoin` I believe requires an array input, but we may be able to relax that.
