### ISSUE TITLE
Client-level tool for managing background tasks and long-running queries

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#363]
One problem that may occur right now is queries taking a long time will block the user from continuing to use their current session.

We should offer users an API to run tasks and execute Ibis expressions in a separate thread and be notified when the query finishes, say, to examine the results later.

**Comment by wesm** [comment]
step 1 here is the async query API. We can revisit management of many background processes separately

**Comment by cpcloud** [comment]
Closing as out of scope for now. Potentially useful though for clients like Visidata. cc @saulpw
