### ISSUE TITLE
Feature Request: Forward and Backward Fill like in Pandas API

### ISSUE THREAD

**Issue by pybokeh** [ibis-project/ibis#3652]
I'm sure there is probably a way to do this using native ibis API which I'm guessing will be a bit more verbose compared to a one-liner functionality that is available in Pandas API.

**Comment by contang0** [comment]
The document by @gforsyth is certainly very helpful, but in the end it is a workaround.

It would be nice if we could simply call bfill/ffill on a column like we do in pandas. I ran into this issue while working with lag function. The column it creates has values for every 2nd row, but I want to also backfill the nulls.

p.s. is it okay to comment on closed issued? Is it preferable to create new ones?

**Comment by tswast** [comment]
> It would be nice if we could simply call bfill/ffill on a column like we do in pandas.

This would require a deterministic ordering to be particularly useful (which is what we do in BigQuery DataFrames to support bfill), but in ibis I think these could make sense as a window function.

Aside: Looks like the documentation location has changed, as the wiki no longer works. https://ibis-project.org/posts/ffill-and-bfill-using-ibis/index.html appears to be new location.
