### ISSUE TITLE
feat(hive): add HiveQL support

### ISSUE THREAD

**Issue by EricSchles** [ibis-project/ibis#3688]
Hi!

I'd like to add HiveQL support (as a backend) to this project.  Is that something the development team would be interested in?

**Comment by cpcloud** [comment]
Hey @EricSchles we're closing this out. Definitely still open to you building out the Hive backend, let us know if you're still interested!

**Comment by EricSchles** [comment]
I def am.  I caught covid and haven't been able to do anything.  Will
circle back when I'm well.

**Comment by cpcloud** [comment]
Ah sorry to hear that. Will reopen then! Feel better.

**Comment by cpcloud** [comment]
Closing this! Please reopen when you'r ready to pick it up again, we'll be here :)
