### ISSUE TITLE
bug: Wrong parameter order in `AnnotableMeta`. 

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#3730]
The following code which was working as of 3ce4f2a8 is now no longer working. Reasonably sure it is because of the changes in https://github.com/ibis-project/ibis/commit/088169ae96c476e0363baaa1fa5f116be5d7aae6 around constructing the `__signature__` in `AnnotableMeta` (https://github.com/ibis-project/ibis/commit/088169ae96c476e0363baaa1fa5f116be5d7aae6#diff-1ba248744f86eb25b4e863648c19353294f34c47b637d1fe88d66eccfc1e1119R100-R108). 

```python
import ibis.expr.operations as ops
import ibis.expr.rules as _rlz
import ibis.expr.types as ir

class SomeOp(ops.ValueOp):
    a = _rlz.instance_of(ir.TableExpr)
    b = _rlz.optional(_rlz.instance_of(ir.TableExpr), default=None)
    c = _rlz.instance_of(bool)
```
now raises 
```
Traceback (most recent call last):
  File "/home/gmanoim/tmp/tmp.py", line 5, in <module>
    class SomeOp(ops.ValueOp):
  File "../ibis/common/grounds.py", line 116, in __new__
    signature = inspect.Signature(
  File "../python3.9/inspect.py", line 2817, in __init__
    raise ValueError(msg)
ValueError: non-default argument follows default argument
```

**Comment by cpcloud** [comment]
I believe this is intentional so that we conform to Python's signature restrictions. @kszucs would know more.

**Comment by kszucs** [comment]
That wasn't intentional, so this is a valid issue. Thanks @gerrymanoim for reporting!

**Comment by cpcloud** [comment]
Ah, great! Thanks for the quick fix @kszucs.
