### ISSUE TITLE
bug: Cannot use `_rlz.instance_of(list)`

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#3736]
The following code now raises a `TypeError`

```python
import ibis.expr.rules as _rlz
import ibis.expr.operations as _ops

class Blah(_ops.TableNode):
    test = _rlz.instance_of(list)

Blah(test=["abc"])
```

```
Traceback (most recent call last):
  File "/home/gmanoim/tmp/tmp.py", line 12, in <module>
    Blah(test=["abc"])
  File ".../ibis/common/grounds.py", line 21, in __call__
    return cls.__create__(*args, **kwargs)
  File ".../ibis/common/grounds.py", line 152, in __create__
    return super().__create__(**kwargs)
  File ".../ibis/common/grounds.py", line 30, in __create__
    return type.__call__(cls, *args, **kwargs)
  File ".../ibis/common/grounds.py", line 163, in __init__
    object.__setattr__(self, "_hash", hash((self.__class__, args)))
TypeError: unhashable type: 'list'
```

**Comment by cpcloud** [comment]
@kszucs Can you have a look?

**Comment by kszucs** [comment]
All operation nodes must be hashable now, which means that it cannot store any unhashable types like list. 

```
class Blah(_ops.TableNode):
    test = _rlz.instance_of(tuple)
```

or coerce the already validated test value to a tuple:

```python
import ibis.expr.rules as _rlz
import ibis.expr.operations as _ops

class Blah(_ops.TableNode):
    test = _rlz.instance_of(list)

    def __init__(self, test):
        # note that the rule has already been executed on the `test` argument
        super().__init__(test=tuple(test))
```

**Comment by gerrymanoim** [comment]
Would it make sense to do this internally as part of a new validator? I understand that ops nodes must be hashable, but it is useful from a UX perspective to be able to take list args from users.

**Comment by kszucs** [comment]
By 'ibis.common.validators.tuple_of(inner_validator)' any iterable should be accepted but still represented as a tuple internally. Could you please try that?

**Comment by gerrymanoim** [comment]
Should `_rlz.list_of` be removed then since you can no longer use that? 

I was able to get this working:

```python
class Blah(_ops.TableNode):
    test = _rlz.tuple_of(_rlz.any)
```

However, when I tried the following, I got a hash error:

```python
class Blah(_ops.TableNode):
    test = _rlz.tuple_of(rlz.column)
```

```
  File "../ibis/common/grounds.py", line 163, in __init__
    object.__setattr__(self, "_hash", hash((self.__class__, args)))
  File "../toolz/0/9/0/dist/lib/python3.9/toolz/functoolz.py", line 271, in __hash__
    frozenset(self.keywords.items()) if self.keywords
TypeError: unhashable type: 'dict'
```

**Comment by kszucs** [comment]
> Should `_rlz.list_of` be removed then since you can no longer use that?

Yes, it should be removed.

> 
> I was able to get this working:
> 
> ```python
> class Blah(_ops.TableNode):
>     test = _rlz.tuple_of(_rlz.any)
> ```
> 
> However, when I tried the following, I got a hash error:
> 
> ```python
> class Blah(_ops.TableNode):
>     test = _rlz.tuple_of(_rlz.column)
> ```

`_rlz.column` requires another validator, please try:

```python
class Blah(_ops.TableNode):
    # tuple of any column expressions
    test = _rlz.tuple_of(_rlz.column(_rlz.any))
```

**Comment by gerrymanoim** [comment]
Got it - thanks!

**Comment by cpcloud** [comment]
Closing, please reopen if this is still an issue.
