### ISSUE TITLE
docs(perf): figure out how to stop re-rendering all jupyter notebooks during mkdocs serve

### ISSUE THREAD

**Issue by p-a-a-a-trick** [ibis-project/ibis#3739]
mkdocs renders all jupyter notebooks during `mkdocs serve`, slowing documentation update/checking to a snail's pace.  It's tedious.  Is there some way to speed it up, have them render concurrently, or allow the user to pick-and-choose if/when notebooks should be re-rendered?

task: speed up mkdocs serve wrt rendering jupyter notebooks

**Comment by cpcloud** [comment]
We're going to move the tutorial notebooks to [the ibis-examples repo](https://github.com/ibis-project/ibis-examples). Closing this out to avoid forgetting about it when that is finished.
