### ISSUE TITLE
Simulating UDF polymorphism through multiple dispatch with the Ibis type system

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#377]
Imagine multiple udfs:

IntVal ProcessInt(IntVal val)
StringVal ProcessString(StringVal val)

and you want to add a method `process` that is valid if and only if a value type features an implicit cast to either `int32` or `string`, so you can write:

```
int_expr.process()
string_expr.process()
```

One way is to do the multiple dispatch by hand, but it would be nice to offer some user API to do this in a more general way.

**Comment by cpcloud** [comment]
Closing as out of scope for now.
