### ISSUE TITLE
Platform independent UDF inline compilation (like PyCUDA or scipy.weave) and distribution with clang and LLVM IR

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#378]
Many users will be using Ibis from a platform that is different (e.g. OS X) from the platform where Impala is running. If clang and the Impala UDF SDK is available, it would be possible (and extremely useful) to do C++ to LLVM IR translation client-side and turn these directly into Ibis-callable UDFs. 

Kind of the way that scipy.weave or PyCUDA and PyOpenCL work. For example:

``` python
udf_module = ibis.impala.udf_module("""
#include "impala/udf.h"

IntVal DoSomething(IntVal val) {
    // omitted
}
""")

func = udf_module.get_function('DoSomething')
func.create_in(client, 'get_down', database='foo')

op = func.to_operation()
def get_down(self):
    return op(self).to_expr()

IntegerValue.get_down = get_down
```

I'm not sure if we can easily hide all the type magic or if the user will have to write them out, but it's worth examining. 

If you're super clever, you can automatically store deduped LLVM IR according to MD5 hash in some common location in HDFS

**Comment by cpcloud** [comment]
Out of scope.
