### ISSUE TITLE
All cells failing from documentation notebooks

### ISSUE THREAD

**Issue by astrojuanlu** [ibis-project/ibis#3819]
For example, in https://ibis-project.org/docs/3.0.0/tutorial/02-Aggregates-Joins/, all cells have errors, starting with `No such table`.

Possibly related: https://github.com/ibis-project/ibis/discussions/3738

**Comment by cpcloud** [comment]
I think this is just me being a silly goose and not setting TEMPDIR.

**Comment by cpcloud** [comment]
This is fixed.
