### ISSUE TITLE
bug: loss of decimal precision in aggregate in 3.x

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#3833]
With ibis 2.1.1:

```
In [1]: import ibis.expr.datatypes as dt

In [2]: import ibis

In [3]: t = ibis.table(
   ...:     [
   ...:         ("l_quantity", dt.Decimal(15, 2)),
   ...:     ],
   ...:     name="t",
   ...: )

In [4]: lquantsum = t.aggregate(sum_qty=lambda t: t.l_quantity.sum())

In [5]: lquantsum._get_type("sum_qty")
Out[5]: Decimal(precision=38, scale=2, nullable=True)
```

On 3.x.x
```
In [1]: import ibis.expr.datatypes as dt

In [2]: import ibis

In [3]: t = ibis.table(
   ...:     [
   ...:         ("l_quantity", dt.Decimal(15, 2)),
   ...:     ],
   ...:     name="t",
   ...: )

In [4]: lquantsum = t.aggregate(sum_qty=lambda t: t.l_quantity.sum())

In [5]: lquantsum._get_type("sum_qty")
Out[5]: Decimal(precision=None, scale=None, nullable=True)
```

This is causing some understandable issues when serializing to substrait

**Comment by cpcloud** [comment]
Darn.

This is a fun area to work in because of the maximum decimal precision being a backend-dependent type.

We can probably bring back the max precision of `38` without breaking support for arbitrary precision decimal types.

**Comment by gforsyth** [comment]
I think I've got a semi-reasonable solution -- defaulting to `None` for `precision` and `scale` on the call to `largest` if `scale` and `precision` are `None`, but if they've been set to a non-`None` value, default to `38` and `2`.  Probably missing some edge cases
