### ISSUE TITLE
feat: expression for creating timestamp from component fields

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#386]
This may need to be implemented in Impala or as an add-on UDF

```
as_timestamp(int year, int month, int day)
as_timestamp(int year, int month, int day, int hours, int minutes, int seconds, int milliseconds, int microseconds)
```

**Comment by saulshanabrook** [comment]
Just noting that this would be useful in order to represent something similar to Vega's [`datetime`](https://vega.github.io/vega/docs/expressions/#datetime) function, which we need when compiling vega expression to ibis.

**Comment by cpcloud** [comment]
Not impala specific, and in fact would need to be implemented in at least one other backend.

**Comment by cpcloud** [comment]
First thing to do would be to see if this already exists.
