### ISSUE TITLE
docs: Pin the table header of the Operation Support Matrix

### ISSUE THREAD

**Issue by toryhaavik** [ibis-project/ibis#3860]
https://ibis-project.org/docs/dev/backends/support_matrix/

It would be nice if the header was pinned as you scroll down, so you can tell what backends support which operations further down the page

**Comment by gforsyth** [comment]
Thanks for the nudge @toryhaavik!  @cpcloud was successfully nerd-sniped and you can now enjoy pinned columns AND rows on https://ibis-project.org/docs/dev/backends/support_matrix/
