### ISSUE TITLE
Overwriting Intersection or Difference operation requires monkey patching

### ISSUE THREAD

**Issue by saschahofmann** [ibis-project/ibis#3863]
As described in ibis-project/ibis-bigquery#87 , trying to overwrite the operations used for Intersection or Difference operations requires monkey patching them.

Before ibis 2.0 it was possible to replace the `intersect_class` and `difference_class`, I am not sure why they were removed but `union_class` kept but is there another way to replace the classes or change how differences are compiled.

Bigquery for example doesn't have a `EXCEPT` statement only `EXCEPT DISTINCT`.

**Comment by tswast** [comment]
I believe this issue can now be closed by #4006
