### ISSUE TITLE
Ibis 3.0 doesnt export now()

### ISSUE THREAD

**Issue by saschahofmann** [ibis-project/ibis#3888]
After updating to ibis 3.0.2 I am getting a `AttributeError: module 'ibis' has no attribute 'now'`. Its still mentioned as a top level function in the docs and I can't find anything in the changelog so I assume it's a bug?

**Comment by cpcloud** [comment]
It sounds like your environment is broken or you have [the other ibis](https://github.com/ibis-project/ibis/issues/3716) installed . Here's what I get on the `3.0.2` tag:

```
In [1]: import ibis

In [2]: ibis.now()
Out[2]: TimestampNow()

In [3]: ibis.__version__
Out[3]: '3.0.2'
```

I see the same on `master`.

**Comment by anjakefala** [comment]
@saschahofmann One way to check which `ibis` you are loading is through the python interpreter:

```
$ python3
>>> import ibis
>>> ibis
<module 'ibis' from '/home/anja/git/ibis/ibis/__init__.py'>
```

That should give you the location of where the imported ibis is installed. Then you can double-check that it is what you expect. 

If you did `pip3 install --upgrade ibis`, that would lead to the installing of [the other ibis](https://github.com/ibis-project/ibis/issues/3716) which does not have a version 3.0.2 (but it does have 3.2.0). This ibis' install is `pip3 install --upgrade ibis-framework`.

**Comment by saschahofmann** [comment]
🤦 beginners mistake should have realised.

**Comment by cpcloud** [comment]
@saschahofmann No worries! Thanks for opening an issue.
