### ISSUE TITLE
Extending docs show failing stacktrace and resolve_name error

### ISSUE THREAD

**Issue by saschahofmann** [ibis-project/ibis#3892]
The doc page about extending ibis shows a failing stacktrace.
https://ibis-project.org/docs/3.0.2/user_guide/extending/elementwise/#create-and-execute-a-julianday-expression

The fix for the first one is easy and I could do it. I just need to replace the old output_shape with output_dtype and output_shape.

But locally I am also struggling with the apparently new (? I couldnt find much about it in the changelog) name/resolve_name logic.

e.g. I am trying to add a startswith function like this 

```python
class StartsWith(ValueOp):
    value = rlz.string
    start_string = rlz.string
    output_dtype = rlz.dtype_like("value")
    output_shape = rlz.shape_like("value")


def startswith(value, start_string):
    return StartsWith(value, start_string).to_expr()

StringValue.startswith = startswith

# compiles for bigquery
@compiles(StartsWith)
def _startswith(t, expr):
    # pull out the arguments to the expression
    value, start_string = expr.op().args
    # compile the argument
    t_value = t.translate(value)
    t_start = t.translate(start_string)
    # return a SQL expression that calls the BigQuery STARTS_WITH function
    return f"STARTS_WITH({t_value}, {t_start})"

```

Where should I define the `resolve_name` function and how should it look?

**Comment by cpcloud** [comment]
@saschahofmann This is fixed in the `dev` docs: https://ibis-project.org/docs/dev/user_guide/extending/elementwise/#create-and-execute-a-julianday-expression.

You shouldn't have to define `resolve_name`. Can you show the stack trace from the error you're encountering?

**Comment by saschahofmann** [comment]
Sure thing
```

    def resolve_name(self):
>       raise ExpressionError(f'Expression is not named: {type(self)}')
E       ibis.common.exceptions.ExpressionError: Expression is not named: <class 'apps.base.core.ibis.compiler.EndsWith'>

.venv/lib/python3.9/site-packages/ibis/expr/operations/core.py:93: ExpressionError
```

Which makes sense since I am inheriting from `ValueOp` which inherits from `Node` which defines that function

**Comment by cpcloud** [comment]
Can you show the expression?

**Comment by saschahofmann** [comment]
It should be the one from above (sorry I showed the error for endswith but the code is the same)
```python
class StartsWith(ValueOp):
    value = rlz.string
    start_string = rlz.string
    output_dtype = rlz.dtype_like("value")
    output_shape = rlz.shape_like("value")
```
```ibis.common.exceptions.ExpressionError: Expression is not named: <class 'apps.base.core.ibis.compiler.StartsWith'>```

**Comment by cpcloud** [comment]
@saschahofmann What I mean is: how are you constructing the expression?

For example, the notebook has this code:

```
julianday_expr = day.julianday().name("jday")
```

Can you show all of the code you're trying to run, including the method call to construct the expression?

**Comment by cpcloud** [comment]
If you're trying to project your custom operation, you must name it. For example:

```python
t = ibis.table(dict(my_string_col="string"))
t[t.my_string_col.my_custom_startswith("foo")]  # this will not work
t[t.my_string_col.my_custom_startswith("foo").name("bar")]  # this will work
```

**Comment by cpcloud** [comment]
If you show the *entire* stack trace, I may be able to help more!

**Comment by saschahofmann** [comment]
Ok here a reproducible example together with the code from above (it lives in my *compiler.py* file)

```python
t = ibis.table([('a', 'string')], name='b')
t[t.a.startswith( 'c')]
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/ibis/expr/types/relations.py", line 136, in __getitem__
    return self.projection(what)
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/ibis/expr/types/relations.py", line 660, in select
    op = projector.get_result()
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/ibis/expr/analysis.py", line 837, in get_result
    return ops.Selection(self.parent, self.clean_exprs)
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/ibis/common/grounds.py", line 20, in __call__
    return cls.__create__(*args, **kwargs)
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/ibis/common/grounds.py", line 151, in __create__
    return super().__create__(**kwargs)
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/ibis/common/grounds.py", line 29, in __create__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/ibis/expr/operations/relations.py", line 410, in __init__
    assert self.schema
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/ibis/expr/operations/relations.py", line 430, in schema
    names.append(projection.get_name())
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/ibis/expr/types/core.py", line 78, in get_name
    return self.op().resolve_name()
  File "/Users/saschahofmann/Projects/gyana/.venv/lib/python3.9/site-packages/ibis/expr/operations/core.py", line 93, in resolve_name
    raise ExpressionError(f'Expression is not named: {type(self)}')
ibis.common.exceptions.ExpressionError: Expression is not named: <class 'apps.base.core.ibis.compiler.StartsWith'>
```

**Comment by saschahofmann** [comment]
wait a sec I think I made a mistake when replacing the output_dtype

**Comment by cpcloud** [comment]
@saschahofmann 

```python
t[t.a.startswith( 'c')]
```

is the source of the failure. A call to `.name(...)` is required here, ibis will not make up names for output columns.

**Comment by saschahofmann** [comment]
Yeah ok I mis typed the output_dtype to string instead of bool. I guess there is some logic that makes it a where clause when  the output isnt a string but a bool. in which case it doesnt need to be named.

**Comment by cpcloud** [comment]
Right, expressions in `WHERE` clause don't need to be named, but anything that will be turned into the list of columns in a `SELECT ...` expressions (a projection) must be named.

Thanks for raising the issue!
