### ISSUE TITLE
feat(api): add support for local write

### ISSUE THREAD

**Issue by rtpsw** [ibis-project/ibis#3893]
This is similar to https://github.com/ibis-project/ibis/issues/3562 just for local-writing.

**Comment by rtpsw** [comment]
The proposed design can be seen [here](https://github.com/rtpsw/ibis/compare/0eb9bc50..93ac74c9#diff-8f6e03b936fae42459cef36d6bb2691392fb1ed9bd03c9846152ac6ebb6da892R5267-R5284) and [here](https://github.com/rtpsw/ibis-substrait/compare/2e93a1d8..7ea2888d#diff-14bbad08fcc797e6913a5f446547e349f60aefe5b2ede385c32c87826baabdbaR658-R677). If this design is acceptable, I'll set up a corresponding PR.

**Comment by cpcloud** [comment]
Closing in favor of #4444.
