### ISSUE TITLE
Instigate a common optimized fork of cloudpickle

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#39]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Wednesday Jan 07, 2015 at 19:32 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/39_

---

Spartan features a significantly optimized fork of PiCloud's cloudpickle:

https://github.com/spartan-array/spartan

Being Apache-licensed code, it would be beneficial to factor this out into a standalone module in PyPI that we (and other libraries needing the enhanced pickling capability) can rely on.

**Comment by cpcloud** [comment]
`cloudpickle` has been removed from ibis.
