### ISSUE TITLE
notin() error when passing an empty sequence

### ISSUE THREAD

**Issue by rcutler-ursa** [ibis-project/ibis#3900]
Filtering in version 3.0.2 based on values in a column "notin" an empty sequence raises a TypeError: Type null is not a primitive or string type.

```
active_values = []
inactive_data = data.filter(data["col"].notin(active_values))
```

This works correctly when `active_values` is not an empty list.

This used to work correctly in version 2.1.1.

**Comment by cpcloud** [comment]
Thanks for the report! Fix should be up shortly.

**Comment by gforsyth** [comment]
Hey @rcutler-ursa -- which backend are you using for this?  and what is the type of `data["col"]` in your example?

**Comment by rcutler-ursa** [comment]
Postgres backend.  Data["col"] are strings.

**Comment by gforsyth** [comment]
Hey @rcutler-ursa -- I can confirm that it's broken on 3.0.2, but I also get an error trying to run this on 2.1.1 with the postgres backend.

Do you have a self-contained example that we can try out on 2.1.1 to try to figure out where the regression happened?

**Comment by rcutler-ursa** [comment]
I don't have a self-contained example, unfortunately.  I can try to pull some data and put one together if that would help.

**Comment by gforsyth** [comment]
I think we've got it narrowed down, actually.  Thanks!

**Comment by rcutler-ursa** [comment]
Cool.  Thanks for the quick response on this!
