### ISSUE TITLE
refactor(operations): split Any into reduction and non-reduction operation

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#3925]
`Any` is currently coupled into a `bool_or`-style reduction and an `EXISTS`-style column operation. We should split these into two different operations internally while preserving the user-facing API.

**Comment by kszucs** [comment]
Also remove `Reduction._reduction` property and all `getattr(obj, "_reduction", False)` checks across the codebase since this is the only operation where we utilize a dynamic check rather than an `isinstance(obj, Reduction)` which should be the preferred.
