### ISSUE TITLE
errors in ibis.udf.vectorized.analytic doctest example

### ISSUE THREAD

**Issue by rtpsw** [ibis-project/ibis#3927]
I bumped into errors in ibis.udf.vectorized.analytic doctest example that I managed to work around but would like to know what the right solution for is.

I'm using commit d52a2d (with some minor local changes that shouldn't matter) and got an AssertionError when running the following code, taken from the ibis.udf.vectorized.analytic doctest example:
```
import ibis
import ibis.expr.datatypes as dt
from ibis.udf.vectorized import analytic
@analytic(input_type=[dt.double], output_type=dt.double)
def zscore(series):  # note the use of aggregate functions
    return (series - series.mean()) / series.std()

@analytic(
    input_type=[dt.double],
    output_type=dt.Struct(['demean', 'zscore'], [dt.double, dt.double])
)
def demean_and_zscore(v):
    mean = v.mean()
    std = v.std()
    return v - mean, (v - mean) / std

win = ibis.window(preceding=None, following=None, group_by='key')
table = ibis.table([('key', 'int32'), ('v', 'float64')], name="kv")
table = table.mutate(
    demean_and_zscore(table['v']).over(win).destructure()
)
table
```
This produced an AssertionError:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/user/github/rtpsw/ibis/ibis/expr/types/core.py", line 37, in __repr__
    return self._repr()
  File "/user/github/rtpsw/ibis/ibis/expr/types/core.py", line 54, in _repr
    return fmt(self)
  File "/user/github/rtpsw/ibis/ibis/expr/format.py", line 58, in fmt
    fmt_root(root, name=expr._safe_name, aliases=aliases, deps=deps)
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/user/github/rtpsw/ibis/ibis/expr/format.py", line 117, in _fmt_root_table_node
    return fmt_table_op(op, **kwargs)
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/user/github/rtpsw/ibis/ibis/expr/format.py", line 385, in _fmt_table_op_selection
    raw_parts = fmt_fields(
  File "/user/github/rtpsw/ibis/ibis/expr/format.py", line 372, in fmt_fields
    field_fmt = [formatter(expr, aliases=aliases) for expr in exprs]
  File "/user/github/rtpsw/ibis/ibis/expr/format.py", line 372, in <listcomp>
    field_fmt = [formatter(expr, aliases=aliases) for expr in exprs]
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/user/github/rtpsw/ibis/ibis/expr/format.py", line 451, in _fmt_selection_column_value_expr
    assert raw_name is not None, (
AssertionError: `_safe_name` property should never be None when formatting a selection column expression
```
To work around this, I first named the destructure:
```
table = table.mutate(
    demean_and_zscore(table['v']).over(win).destructure().name("vs")
)
```
which produced a different error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/user/github/rtpsw/ibis/ibis/expr/types/relations.py", line 586, in mutate
    mutation_exprs = an.get_mutation_exprs(exprs, self)
  File "/user/github/rtpsw/ibis/ibis/expr/analysis.py", line 535, in get_mutation_exprs
    raise ExpressionError(
ibis.common.exceptions.ExpressionError: Cannot name a destruct column: vs
```
and then I commented out the code that raises this error:
```
diff --git a/ibis/expr/analysis.py b/ibis/expr/analysis.py
index 8cf96cd1..bb8bcde1 100644
--- a/ibis/expr/analysis.py
+++ b/ibis/expr/analysis.py
@@ -532,9 +532,10 @@ def get_mutation_exprs(
         expr_contains_overwrite = False
         if isinstance(expr, ir.DestructColumn):
             if expr.has_name():
-                raise ExpressionError(
-                    f"Cannot name a destruct column: {expr.get_name()}"
-                )
+                #raise ExpressionError(
+                #    f"Cannot name a destruct column: {expr.get_name()}"
+                #)
+                pass
             for name in expr.type().names:
                 if name in table_schema:
                     # The below is necessary to ensure that:
```
which produced a reasonable-looking result for `table`:
```
r0 := UnboundTable: kv
  key int32
  v   float64

Selection[r0]
  selections:
    r0
    vs: WindowOp(AnalyticVectorizedUDF(func=demean_and_zscore, func_args=[r0.v], input_type=[float64], return_type=struct<demean: float64, zscore: float64>), window=Window(group_by=[r0.key], how='rows'))
```

**Comment by rtpsw** [comment]
cc @icexelloss

**Comment by icexelloss** [comment]
The code you had looks similar to this:

https://github.com/ibis-project/ibis/blob/master/ibis/backends/tests/test_vectorized_udf.py#L589

Does this test pass for you?

**Comment by rtpsw** [comment]
> The code you had looks similar to this:
> 
> https://github.com/ibis-project/ibis/blob/master/ibis/backends/tests/test_vectorized_udf.py#L589
> 
> Does this test pass for you?

This code doesn't format the table, which is where I'm seeing the error. As note, I have a workaround, and I'm just wondering what the right (non-workaround) solution should be.

I get a different problem when trying to run ibis tests, but this will be discussed elsewhere, to keep things focused here.

**Comment by cpcloud** [comment]
@rtpsw @icexelloss It would be great if one of y'll submitted a PR to fix this!

**Comment by rtpsw** [comment]
@cpcloud, my workaround above is not based on a good understanding of the cause. I was hoping someone else could say what the right solution is. I don't feel confident removing a check that someone coded up for a reason I don't know.

**Comment by rtpsw** [comment]
Pinging authors to push this forward:

@emilyreff7, since you appear on the commit history for the [above-mentioned test](https://github.com/ibis-project/ibis/blob/e6aee859767d9de5069b8cb5a6f3f6185f0e9850/ibis/expr/analysis.py#L251-L254) that raises the error described here, could you provide some insight about it or refer to someone who can explain its rationale?

@icexelloss, since you appear on the commit history for the [above-mentioned doctest](https://github.com/ibis-project/ibis/issues/3927#issue-1239009931), could you take a look to see whether the example there is correct?

**Comment by emilyreff7** [comment]
From what I can tell, raising an error on a named destruct column has been long-standing logic prior to my commits, with the rationale being that it represents multiple column expressions which each should be named individually. I am wondering why naming the destruct column seems to fix the formatting error, given that the original error hits [here](https://github.com/ibis-project/ibis/blob/master/ibis/expr/format.py#L451) (e.g. I would have expected this code to hit [here](https://github.com/ibis-project/ibis/blob/master/ibis/expr/format.py#L466) instead).

My guess would be that there is something wrong with the example itself - you could try formatting one of the [similar test cases](https://github.com/ibis-project/ibis/blob/master/ibis/backends/tests/test_vectorized_udf.py#L589) to see if they also hit that same formatting error.

**Comment by cpcloud** [comment]
This looks to be fixed by https://github.com/ibis-project/ibis/pull/4231.
