### ISSUE TITLE
docs: broken link on the tutorial's introduction page

### ISSUE THREAD

**Issue by helensilva14** [ibis-project/ibis#3942]
Hello! 

The first link provided on https://ibis-project.org/docs/3.0.2/tutorial/01-Introduction-to-Ibis/#getting-started is the one indicating to follow the SQLite instructions, but the link is broken, it currently is defined like that: `Follow the [installation instructions for SQLite](https://ibis-project.org/backends/SQLite/#install) to setup an environment.`

And it should point to this one https://ibis-project.org/docs/3.0.2/backends/SQLite/.

I start to edit the file to have the right link, but since it has the version on the path, I did not know how to proceed. If someone give me instructions regarding this, I would be help to fix it.

Thanks!

**Comment by cpcloud** [comment]
Hi Helen!

If you edit the file and push up a PR for the change it'll be pushed to the dev site (https://ibis-project.org/docs/dev/) when merged to `master`.

It would be visible in the next release as well (3.1).
