### ISSUE TITLE
bug: Projection ignores mutation

### ISSUE THREAD

**Issue by saschahofmann** [ibis-project/ibis#4027]
If you perform a projection after mutation using strings for the columns it will revert the mutation. If I use the column references from the mutated query it works as expected. My expectation was that the string name refers to the latest instance of that column on a query

```python
import ibis
from ibis.expr import datatypes as dt
from ibis_bigquery import compile

t = ibis.table([('a', 'int32'), ('b', 'str')], name='table')
compile(t.mutate(a=t['a'].cast(dt.string)).projection(['a','b']))
# SELECT `a`, `b`\nFROM table

t = t.mutate(a=t['a'].cast(dt.string))
compile(t.projection([t['a'], t['b']]))
# SELECT `a`, `b`\nFROM (\n  SELECT CAST(`a` AS STRING) AS `a`, `b`\n  FROM table\n) t0

**Comment by cpcloud** [comment]
@saschahofmann Thanks for creating the issue!

I think this exact bug was reported in https://github.com/ibis-project/ibis/issues/4003 and fixed shortly thereafter in https://github.com/ibis-project/ibis/pull/4005.

Can you give a try against `master`?
