### ISSUE TITLE
perf: "large compile" test failing with some recent commit

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#4036]
I noticed while working on https://github.com/ibis-project/ibis/pull/4006 that after some recent sync with master that the "large compile" test in the BigQuery backend started failing.

https://github.com/ibis-project/ibis-bigquery/blob/d3acf50de9d8e9015819efe300b4b5f9615c027a/tests/unit/test_compiler.py#L425

I was hoping this was just a misconfiguration with my local machine, but I see now that it is failing / infinitely looping on the GitHub Actions setup as well: https://github.com/ibis-project/ibis-bigquery/runs/6711618312?check_suite_focus=true

**Comment by cpcloud** [comment]
It looks like this is a performance issue because the test did eventually finish. I can confirm locally that https://github.com/ibis-project/ibis/commit/55a0b356176d8e086c3c3592869bf9c477516a8b is in fact the commit that introduced the performance issue.

**Comment by tswast** [comment]
Wow, it did! 51 minutes versus a few seconds before this commit. 😳
