### ISSUE TITLE
Normalize references in docs and code to different clients etc

### ISSUE THREAD

**Issue by laserson** [ibis-project/ibis#405]
There are references to `IbisClient`, `ImpalaClient`, `ImpalaConnection`, "HDFS Client", `WebHDFS`, `InsecureClient`, etc, which sometimes appear to be inconsistent, and are a bit confusing.

**Comment by wesm** [comment]
@laserson can you take a look at this one?

**Comment by cpcloud** [comment]
We will definitely address specific inconsistencies, but a generic "everything is inconsistent" issue is not actionable.
