### ISSUE TITLE
Milliseconds extraction problem in duckdb (and possibly, postgres)

### ISSUE THREAD

**Issue by evgenygr** [ibis-project/ibis#4054]
Consider the following code snippet:
```
import ibis
from sqlalchemy.dialects import postgresql

table = ibis.table(name='A', schema=[('a', 'timestamp')])
print(str(
    ibis.duckdb.compile(
        table['a'].millisecond()
    ).compile(
        dialect=postgresql.dialect(paramstyle="named"),
        compile_kwargs={"literal_binds": True}
    )
))
```
The result is the following:
`'SELECT CAST(floor(EXTRACT(millisecond FROM t0.a)) AS SMALLINT) % 1000 AS millisecond \nFROM "A" AS t0'`
Here typecast to SMALLINT cannot be done in general case. For example:
```
import duckdb
import pyarrow as pa
from datetime import datetime

dtm = datetime.fromisoformat

arrow_table = pa.table([
    pa.array([
        dtm('2020-01-12T23:34:45.567891'),
        dtm('2022-02-24T04:34:13.067123'),
        None
    ])],
    names=['a']
)
conn = duckdb.connect(database=':memory:')
conn.register('A', arrow_table)
conn.execute('SELECT EXTRACT(millisecond FROM a) AS a FROM A').arrow()
```
Here the result is
```
pyarrow.Table
a: int64
----
a: [[45567,13067,null]]
```
This it is ok to do '% 1000' to eventually get milliseconds, since we see here whole seconds as well, but SMALLINT is not able to store 45567 because it has a range [-32768 to 32767](https://duckdb.org/docs/sql/data_types/numeric), while we need 0 to 60000. So, USMALLINT should be good for milliseconds.
From the example above if we try to run a query on duckdb connection:
`conn.execute('SELECT CAST(floor(EXTRACT(millisecond FROM t0.a)) AS SMALLINT) % 1000 AS millisecond \nFROM "A" AS t0').fetchall()`
it produces an error:
`'RuntimeError: Conversion Error: Type DOUBLE with value 45567.0 can't be cast because the value is out of range for the destination type INT16'`
which makes sense.

PROPOSAL: USMALLINT looks like a better choice then SMALLINT

**Comment by evgenygr** [comment]
Also, i tried to do the same thing with duckdb-engine (`pip install duckdb-engine`). The result is the same:
```
import ibis
from sqlalchemy import create_engine

eng = create_engine("duckdb:///:memory:")
table = ibis.table(name='A', schema=[('a', 'timestamp')])

str(
    ibis.duckdb.compile(
        table['a'].millisecond()
    ).compile(eng, compile_kwargs={"literal_binds": True})
)
```
the output:
`'SELECT CAST(floor(EXTRACT(millisecond FROM t0.a)) AS SMALLINT) % 1000 AS millisecond \nFROM "A" AS t0'`

**Comment by cpcloud** [comment]
@evgenygr Thanks for the bug report. Indeed this looks like a bug. Ibis is assuming that the result of `extract(milliseconds from thing)` which is `seconds * 1000 + milliseconds` is less than the max value of a signed 16-bit integer (`32767`) which is incorrect.
