### ISSUE TITLE
Docs versioning tool is not building working relative links for ibis-project.org

### ISSUE THREAD

**Issue by anjakefala** [ibis-project/ibis#4064]
E.g. https://ibis-project.org/backends/SQLite/#install linked to from here: https://ibis-project.org/docs/3.0.2/tutorial/01-Introduction-to-Ibis/.

Source code shown: https://github.com/ibis-project/ibis/pull/4038/files#diff-15dc5f0c70736230279998fc98d3472bfe89bed557277c4e5e5640e41898bbc1L26.

From chatting with @cpcloud, when built locally the links are built appropriately, but it is not working with the docs versioning tool being used to build the website in production.

List of links with the problem:
docs/tutorial/01-Introduction-to-Ibis.ipynb:    "To start using Ibis, you need a Python environment with Ibis installed. Follow the [installation instructions for SQLite](/backends/SQLite/#install) to setup an environment.\n",

https://ibis-project.org/backends/SQLite/#install 

docs/tutorial/04-More-Value-Expressions.ipynb:    "The [Ibis type system](/api/datatypes) supports the most common data types used in analytics, including support for nested types like lists, structs, and maps.\n",

https://ibis-project.org/api/datatypes

**Comment by cpcloud** [comment]
I think it might be an issue with `mkdocs-jupyter`, since we do have relative links elsewhere in the documentation e.g., [here](https://github.com/ibis-project/ibis/blob/master/docs/contribute/02_workflow.md?plain=1#L54).

**Comment by anjakefala** [comment]
I am still exploring this, but initial findings hint that this might be tricky to do: https://github.com/danielfrg/mkdocs-jupyter/issues/27

**Comment by anjakefala** [comment]
For folks in the future:

mkdocs-jupyter cannot find relative links in upper directories with the
standard markdown syntax
(https://github.com/danielfrg/mkdocs-jupyter/issues/27).

The solution is to use html `<a>` tag (e.g. Follow the <a href='../../backends/SQLite#install'>installation instructions for SQLite</a> to setup an environment.\n",)
