### ISSUE TITLE
feat(api): Add support for Recursive Common Table Expressions (CTE's)

### ISSUE THREAD

**Issue by prmoore77** [ibis-project/ibis#4137]
Please add support for Recursive CTE's in Ibis as a way to interact with hierarchical data using Python.

Please see repo:
https://github.com/prmoore77/ibis-olap-aggregation - for an example where we use Recursive CTEs to manually create table structures that allow aggregation of fact data along a dimensional hierarchy.

This can help with Business Intelligence workloads in Ibis that need to aggregate data hierarchically.  The business problem (and solving SQL) is detailed in this medium [article](https://medium.com/@philipmoore_53699/olap-hierarchical-aggregation-with-sql-6c45ebc206d7).

Thank you!

**Comment by prmoore77** [comment]
If it helps - I converted the "HierarchyDimension" class to now use SQLAlchemy Core for the Recursive CTE (per suggestion from @cpcloud) - see: https://github.com/prmoore77/ibis-olap-aggregation/blob/main/classes/hierarchy_dimension_table.py

This may help for the ibis api feature...

**Comment by cpcloud** [comment]
Closing this out for now. This is an interesting idea, but it needs some API design work.
