### ISSUE TITLE
Fix broken link in "Introduction to Ibis" tutorial

### ISSUE THREAD

**Issue by apreshill** [ibis-project/ibis#4201]
In this section: https://ibis-project.org/docs/3.0.2/tutorial/01-Introduction-to-Ibis/#getting-started

The link here for the installation instructions is broken:
<img width="728" alt="Screen Shot 2022-07-06 at 11 19 20 AM" src="https://user-images.githubusercontent.com/12160301/177617044-bbf18b40-59f2-4235-9b9c-8b46ba335641.png">

The link that does not work is this one: https://ibis-project.org/backends/SQLite/#install

It looks like the working link is here: https://ibis-project.org/docs/3.0.2/backends/SQLite/#install

I didn't want to offer a PR because I'm not sure how to template the version number out of that url.

**Comment by anjakefala** [comment]
Thanks for opening an issue. =)

We already have an open issue for this problem: https://github.com/ibis-project/ibis/issues/4064. Unfortunately, the fix is a bit tricky, and your intuition was correct on that.
