### ISSUE TITLE
Add ParquetFormat

### ISSUE THREAD

**Issue by ihodes** [ibis-project/ibis#426]
This is basically like AvroFormat.

**Comment by cpcloud** [comment]
It looks like this was added in #792, though it looks untested.

**Comment by cpcloud** [comment]
@wesm Can this be closed? Is there something that supersedes this?

**Comment by wesm** [comment]
If the `ParquetFormat` is being used then this can be closed, otherwise we should add a unit test

**Comment by cpcloud** [comment]
Closing as done.
