### ISSUE TITLE
bug(impala) A delimited table should be explicitly stored as textfile

### ISSUE THREAD

**Issue by yi-you** [ibis-project/ibis#4260]
https://github.com/ibis-project/ibis/blob/88ffe3367cb6a34936e578f6a9b68dc30d559507/ibis/backends/impala/ddl.py#L67
when the cluster's default format is set as parquet, this will cause an exception. It should be explicitly stored as textfile. such as

```python
        if self.lineterminator is not None:
            yield f"LINES TERMINATED BY '{self.lineterminator}'"

        yield 'STORED AS TEXTFILE'
        yield f"LOCATION '{self.path}'"
```

**Comment by cpcloud** [comment]
@yi-you Thanks for the issue. Would you mind submitting a pull request for this? Looks like you've already done most of the work!
