### ISSUE TITLE
Add API to determine version of the connected Impala cluster

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#430]
For version-dependent feature enabling (or falling back on older implementations of things)

**Comment by laserson** [comment]
Is there a doc for this that outlines the version compatibility of all the relevant features?

**Comment by wesm** [comment]
We can get this via regular expression parsing the HTML returned from a request to port `25000` (this should be a configurable) but a bit hacky. Hoping that Impala will get a REST API with this data at some point

**Comment by cpcloud** [comment]
We may want a `server_version` (alongside `version`) for backends, but nothing that is Impala-only.
