### ISSUE TITLE
bug(pandas): pandas backend does not support aggregation with list-based where condition

### ISSUE THREAD

**Issue by brendanbikes** [ibis-project/ibis#4300]
Pandas backend throws a `NotImplementedError` when evaluating an ibis expression that contains a `groupby()` with an `aggregate()` that depends on a list-based `where` condition using `isin()`.

MWE

```
import ibis
import pandas as pd

test_df = pd.DataFrame({
    'id': ['1', '1', '2', '3', '4', '4'],
    'value': ['a', 'a', 'b', 'c', 'd', 'a']
})

conn = ibis.pandas.connect({'sample_df': test_df})
table = conn.table('sample_df')

expr1 = table.groupby("id").aggregate([
    table.id.count(table.value == "a")
])

expr2 = table.groupby("id").aggregate([
    table.id.count(table.value.isin(["a", "b"]))
])

#this works
print(expr1.execute())

#this fails
print(expr2.execute())
```

The specific error yielded is `NotImplementedError: Could not find signature for execute_node: <Contains, SeriesGroupBy, list>`

**Comment by cpcloud** [comment]
@brendanbikes Thanks for the MWE!

Looks like this functionality just isn't implemented.
