### ISSUE TITLE
question: ibis.table created table is no such table ?

### ISSUE THREAD

**Issue by hengaini2055** [ibis-project/ibis#4313]
Ibis.options.default_backend is <ibis.backends.sqlite.Backend at 0x7f48267728e0>. When I create a table using such code:
```
t2 = ibis.table([('key', 'string'), ('value', 'float')], 'dim_table')
```
THis is success. But when I check the t2, then I get the following errors:
```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
File ~/.conda/envs/jupyterl/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1819, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1818     if not evt_handled:
-> 1819         self.dialect.do_execute(
   1820             cursor, statement, parameters, context
   1821         )
   1823 if self._has_events or self.engine._has_events:

File ~/.conda/envs/jupyterl/lib/python3.9/site-packages/sqlalchemy/engine/default.py:732, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    731 def do_execute(self, cursor, statement, parameters, context=None):
--> 732     cursor.execute(statement, parameters)

OperationalError: no such table: dim_table

The above exception was the direct cause of the following exception:
........
........
perationalError: (sqlite3.OperationalError) no such table: dim_table
[SQL: SELECT t0."key" 
FROM dim_table AS t0]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

What's the problem? Thanks!

https://ibis-project.org/docs/3.1.0/ibis-for-sql-programmers/#select-equivalent In [13]

**Comment by cpcloud** [comment]
@hengaini2055 Thanks for the issue!

`ibis.table` doesn't create tables inside of any database, that is, it will not trigger execution of `CREATE TABLE` or similar constructs (e.g., `CREATE VIEW`).

`ibis.table` constructs what are called "unbound tables" which are expressions that represent tables that are not bound to any data source. You can use these unbound tables to build expression trees independent of any backend.

Setting the default backend has no effect on this behavior.

What exactly are you trying to do?

With more information I can help you get to where you need to be!

**Comment by hengaini2055** [comment]
ibis.table created table such as above t2, should the same as backend table. When I ```t2``` in a jupyter cell, I get the above errors.
```

[101] t = ibis.table(
    [('one', 'string'), ('two', 'float'), ('three', 'int32')], 'my_data'
)
[102] t

---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
File ~/.conda/envs/jupyterl/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1819, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1818     if not evt_handled:
-> 1819         self.dialect.do_execute(
   1820             cursor, statement, parameters, context
   1821         )
   1823 if self._has_events or self.engine._has_events:

File ~/.conda/envs/jupyterl/lib/python3.9/site-packages/sqlalchemy/engine/default.py:732, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    731 def do_execute(self, cursor, statement, parameters, context=None):
--> 732     cursor.execute(statement, parameters)

OperationalError: no such table: my_data

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
File ~/.conda/envs/jupyterl/lib/python3.9/site-packages/IPython/core/formatters.py:707, in PlainTextFormatter.__call__(self, obj)
    700 stream = StringIO()
    701 printer = pretty.RepresentationPrinter(stream, self.verbose,
    702     self.max_width, self.newline,
    703     max_seq_length=self.max_seq_length,
    704     singleton_pprinters=self.singleton_printers,
    705     type_pprinters=self.type_printers,
    706     deferred_pprinters=self.deferred_printers)
--> 707 printer.pretty(obj)
    708 printer.flush()
    709 return stream.getvalue()
```

**Comment by hengaini2055** [comment]
```
OperationalError: (sqlite3.OperationalError) no such table: my_data
[SQL: SELECT t0.ts 
FROM web_events AS t0]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by hengaini2055** [comment]
I get the point. The ibis.expr.types.relations.Table can't be execute in jupyter cell itself, but It can be referenced by expr as in [ibis doc](https://ibis-project.org/docs/3.1.0/ibis-for-sql-programmers/#non-trivial-grouping-keys)

**Comment by hengaini2055** [comment]
```
conn = ibis.sqlite.connection('/some/database.db')
countries = conn.table('countries')
events = ibis.table(
    [('ts', 'timestamp'), ('event_type', 'int32'), ('session_id', 'int64')],
    name='web_events',
)
```
type(countries) is ```ibis.expr.types.relations.Table```, type(events) is the same as ```ibis.expr.types.relations.Table```.

The code ```countris``` in jupyter cell will display all data, and ```events``` gets errors 
``` OperationalError: (sqlite3.OperationalError) no such table: my_data```

**Comment by gforsyth** [comment]
Hey @hengaini2055!  

When you define `events` above it is an `UnboundTable` -- it might be representative of an actual table in a given database, but that isn't something that `ibis` knows about.

It looks like you have `ibis.options.interactive = True` set.  I would recommend that you set that to `False` instead while you explore a little bit.

When `interactive == True`, then typing `events` is equivalent to running `events.execute()`, which in this context means "fetch me the contents of some table named `events`".

Because you have set the default backend to `sqlite` and connected to the sample data db, it tries to look up the contents of `events` in that database, and it does not exist, so it errors.

If you aren't in `interactive` mode, you'll instead see the representation of that unbound table, like:

```python
In [12]: ibis.options.interactive = False

In [13]: events = ibis.table(
    ...:     [("ts", "timestamp"), ("event_type", "int32"), ("session_id", "int64")],
    ...:     name="web_events",
    ...: )

In [14]: events
Out[14]: 
UnboundTable: web_events
  ts         timestamp
  event_type int32
  session_id int64
```

but if you then run `events.execute()`, it will error in the same way as before, unless you are connected to a sqlite database (or other) that has a table named `web_events` that matches the schema specified.

**Comment by hengaini2055** [comment]
@gforsyth Thank you. I close this issue.
