### ISSUE TITLE
feat: extend UDF operations with volatility flags

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#4355]
We should consider to extend the UDF operations to mark them idempotent, [see how spark handles deterministic VS non-deterministic UDFs](https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.functions.udf.html). DataFusion uses the [volatility enum](https://github.com/apache/arrow-datafusion/blob/41b4e491663029f653e491b110d0b5e74d08a0b6/datafusion/expr/src/signature.rs#L25-L37) for this purpose.

_Originally posted by @kszucs in https://github.com/ibis-project/ibis/pull/4217#discussion_r946631482_

**Comment by cpcloud** [comment]
This requires more work on the UDF interface and it's not clear we'll need this optional for awhile even then.
