### ISSUE TITLE
bug(api): make `date` work with deferred `_` api

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#4365]
Currently you can't use `date(_.foo)` to make a deferred expression in `ibis`. Right now you have to use a `lambda`:

```python
t.mutate(year=lambda _: ibis.date(_.date_column).year())
```

We should make `date(_)` work so you can instead do:

```python
t.mutate(year=ibis.date(_.date_column).year())
```

**Comment by cpcloud** [comment]
I think to make this work we need to bake in deferred handling to rules. I believe this can be done in one or two places to make it work everywhere.
