### ISSUE TITLE
feat(ir): consider to support deferred arguments for value rules

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#4382]
@kszucs The first approach I took was to try to integrate it into the `value` rule, I couldn't figure out a way to do it. Rules are "eager" in their validation, will construct operations with deferred instances. I think we'd ultimately have to add support for operations to hold deferred objects and that just doesn't seem worth the churn given the limited number of APIs that are functions.

_Originally posted by @cpcloud in https://github.com/ibis-project/ibis/issues/4377#issuecomment-1221317661_

**Comment by cpcloud** [comment]
Closing this out as I think the only thing remaining that doesn't support deferred is the `array`/`map`/`struct` functions.

cc @jcrist
