### ISSUE TITLE
refactor(ir): remove the remaining unnecessary expr-op roundtrips

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#4406]
_Originally posted by @cpcloud in https://github.com/ibis-project/ibis/pull/4378#discussion_r953728200_

I have marked the occurences using todo notes similar to:
`TODO(kszucs): avoid expression roundtrip`

**Comment by cpcloud** [comment]
I don't think we really need to track this since we have `TODO`s everywhere this exists. Those are slowly going away as we touch those parts of the codebase.
