### ISSUE TITLE
Ibis scaling to noSQL databases

### ISSUE THREAD

**Issue by GayathriRipple** [ibis-project/ibis#4420]
Adding connectivity to noSQL database will be really helpful.

I created a hive external table on top of hbase, and tried to establish connection with the hbase data pointed by hive.
That failed in ibis with the following error:
File "python3.9/site-packages/ibis/backends/impala/client.py", line 263, in _wait_synchronous
raise OperationalError("Operation is in ERROR_STATE")
impala.error.OperationalError: Operation is in ERROR_STATE

Kindly let me know if there is a way to fix this.
Does the tool support HBASE data validation, or just the HDFS? If not, is that a part of the future scope?
Please clarify, thanks!

**Comment by cpcloud** [comment]
Hi @GayathriRipple 👋🏻, thanks for opening an issue!

There are many reasons this error can occur, which may or may not be related to ibis.

The impala backend is in maintenance mode and will see no further development except critical bug fixes.

Thanks again!
