### ISSUE TITLE
fix(duckdb): `array_length` implementation generates incorrect code

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#4438]
```
In [16]: print(ibis.duckdb.compile(ibis.array([1]).length().name("n")).compile(compile_kwargs=dict(literal_binds=True)))
SELECT CASE WHEN (CAST(list_value(1) AS ARRAY) IS NULL) THEN NULL ELSE coalesce(array_length(CAST(list_value(1) AS ARRAY), 1), 0) END AS n
```

The `0` as the second argument to `array_length` is generated by the postgres implementation because it supports computing the length in a particular dimension of an array.

DuckDB doesn't support this, so our implementation should just call `sa.func.array_length(translated_arg)`.

The `ops.ArrayLength` translation rule should be specialized for duckdb.

**Comment by jcrist** [comment]
Based on https://github.com/ibis-project/ibis/pull/4439#issuecomment-1230616375, it sounds like this wasn't actually a bug. Closing.
