### ISSUE TITLE
docs: add information on how to report code-of-conduct violations

### ISSUE THREAD

**Issue by anzelpwj** [ibis-project/ibis#4442]
Hi folks,

I was looking at the CoC for Ibis at https://ibis-project.org/docs/3.1.0/community/coc/ and I noticed there is no way to submit a report if there is a concern. Would you please add this information?

Thank you!
Paul

**Comment by cpcloud** [comment]
Thanks @anzelpwj! We'll add this before the 3.2.0 release.
