### ISSUE TITLE
question: anaconda packages are very out-of-date

### ISSUE THREAD

**Issue by kesmit13** [ibis-project/ibis#4511]
I don't know if you have any control over the packages available on anaconda.org, but the most recent version of Ibis there is 1.3. We are doing work with Ibis at SingleStore, but we are using version 3.2. I just wondered if you were able to update those packages, or have a connection who can make that happen?

**Comment by gforsyth** [comment]
We don't have control over what Anaconda builds and publishes on their channel, but we have up-to-date versions available on `conda-forge`

**Comment by cpcloud** [comment]
@kesmit13 Is there any particular reason to update the anaconda.org packages? `conda-forge` is our preference for conda things, not least because of this issue.

**Comment by kesmit13** [comment]
Mostly for customer requirements. We've had some that won't install from anything except the main Anaconda channel. I did send a request in to Anaconda to see what it takes to trigger a new package build, but I agree their process is definitely not optimal.

**Comment by kesmit13** [comment]
Although they will install from our channel, so I guess one option is to mirror an Ibis package in our channel.

**Comment by jcrist** [comment]
Yeah, anaconda manages their own builds for the defaults channel, there's not much we can do here other than open an issue upstream (done [here](https://github.com/ContinuumIO/anaconda-issues/issues/13049)). If there's any way you can use the conda-forge version (or mirror it to your own channel) that'd be our recommendation. Closing.
