### ISSUE TITLE
dev: place the pull request number into the commit

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#4516]
It would be great to be able to locate the pull request and possibly relevant discussions for a certain commit. As an example it's pretty easy to locate the pull request a commit belongs to in the [apache/arrow commit history](https://github.com/apache/arrow/commits/master). We cannot currently do that for ibis.

**Comment by jcrist** [comment]
For other projects (e.g. dask) we squash merge PRs using the github ui, which automatically adds the PR number to the commit message by default. Another nice thing about that is that the commit message can be updated on merge (by default it takes the PR title), so we could fix the commit message formatting to fit what the changelog script expects without forcing the PR author to worry about such things.

Not saying that's the best solution here, but it's an option.

**Comment by kszucs** [comment]
Actually I'd like to have a one-to-one mapping between commits and PRs, after doing plenty of cherry-picking for the arrow project I prefer squashed PRs. 

@cpcloud does the changelog generator support squashed commits? There was some issue with squashing PRs if I recall correctly.

**Comment by cpcloud** [comment]
The changelog generator is only a single component of the automated release process and is not the the thing that analyzes commits to determine the version. The component that does that is called the commit analyzer, and lives in the `@semantic-release/commit-analyzer` NPM package.

> We cannot currently do that for ibis.

Maybe you mean we can't do that by looking at the commit log?

It's definitely possible get the PR associated with a commit using the GitHub API. It's a one liner:

```
❯ gh api 'repos/ibis-project/ibis/commits/1961bad26/pulls' --jq '.[].html_url'
https://github.com/ibis-project/ibis/pull/4508
```

I don't find the argument that being able to look at the commit log and know that there's a one-to-one mapping between commits and PRs compelling.

Why do we need that to be the case? Is there something that is incredibly inconvenient or impossible that we need to do on a regular basis that would be made easier or possible by having this 1:1 mapping?

Things like cherry picking and long running branches should be avoided, which I think obviates the need for any kind of precise mapping between PRs and commits, which again can be recovered quite easily using `gh`.

**Comment by gforsyth** [comment]
I'm not going to suggest that this is something we need to do on a _regular_ basis, but I do think that it can be easier to `bisect` if all commits pass CI at time of merge -- that doesn't necessarily mean a 1:1 mapping, but it's often the "simplest" way to get there.

**Comment by cpcloud** [comment]
I think this might be possible, but it's also not something that I think anyone is motivated to do. However, if someone else is interested in making this work with automated releases we will happily review a PR for that.
