### ISSUE TITLE
visualize.py `to_graph(...)` adds same node multiple times to graphviz graph AND doesn't display all nodes

### ISSUE THREAD

**Issue by ams1** [ibis-project/ibis#4528]
When running the "example" from:
https://github.com/ibis-project/ibis/blob/9edbbc0cc22fc8d2db8c5e5614c6c5a0c40c33a0/ibis/expr/visualize.py#L124-L138

...and setting a breakpoint at the end of the `to_graph(...)`
https://github.com/ibis-project/ibis/blob/9edbbc0cc22fc8d2db8c5e5614c6c5a0c40c33a0/ibis/expr/visualize.py#L75-L106

1) You will see that the graphviz `DOT code` (aka `print(g.source)`) generated by the `graphviz` lib via `ibis/ibis/expr/visualize.py`s' `to_graph(...)` contains duplicated nodes (highlighted with red in below debugging screenshot).

![image](https://user-images.githubusercontent.com/10154357/190893103-4ac38a6d-f913-4fa7-91d8-da4ee8f8584c.png)

These duplicated nodes do NOT impact the visual representation because they have the same "node id" and **graphviz basically takes into consideration only the LAST declaration of a node**, `BUT` they impact a bit the performance:

```
the same `node` should be present (added/"seen") only once in the graphviz graph.
```

_The same `edge` (from, to) can be present more than once if we want to see it duplicated._

One solution would be to check if the node has already been added to the `g` graph BEFORE adding it, BUT...

2. ....Also there seem to be different nodes with the same id (with green in the screenshot above), which can IMPACT the visual representation, ex:
```
1st appearance:
-7147190702382226628 [label=<<I>having</I>: <B>NodeList</B> ⟶ ∅>]
...
2nd appearance with:
-7147190702382226628 [label=<<I>sort_keys</I>: <B>NodeList</B> ⟶ ∅>]
```
Reusing the same node ID for a different subsequent node _- (at least) before creating an edge with that ID -_ will cause the 1st node not to be rendered -> ex. indeed searching for "having" in the graphviz svg of the above-mentioned example will yield NO RESULTS (`"having" is missing`).

I'll try to investigate why is `hash(...)` returning the same thing for different instances and get back to you...

**Comment by cpcloud** [comment]
@ams1 Great find, great writeup!

This does seem like a bug. Slated for 4.0.0.

**Comment by ams1** [comment]
@cpcloud Thanks for fixing this!

I also super-like that you made the graph more compact by reducing the width of each node (via showing only the class name).
Given that real life graphs like this can be HUGE, these `per node width reductions` matter - ex. further width reductions could be made by placing the return type above/below the class name.

As the graph is one of key features of ibis I'll be using, I'll probably open subsequent issues/PRs regarding this - I promise I won't overwhelm you as I think it is not one the "popular" features 😄.
