### ISSUE TITLE
Question: How to compose multiple projections into a single call

### ISSUE THREAD

**Issue by kesmit13** [ibis-project/ibis#4555]
I have a question that I haven't been able to find an answer to in the documentation. I want to do the equivalent of a simple query as follows:
```
select count(distinct(overall)), count(distinct(reviewerName)) from phones
```

I tried using the `table.select` method and passing in phones.overall.nunique() and phones.reviewerName.nunique() in a list, but that causes a windowed query to be constructed. I just want the simple one above.

**Comment by jcmkk3** [comment]
I believe that if you use the `aggregate` method, then you should get the query that you expect. It would look like this.

```python
phones.aggregate([
    phones.overall.nunique().name("n_overall"),
    phones.reviewerName.nunique().name("n_reviewers")
])
```

**Comment by kesmit13** [comment]
That does work. Thanks!
