### ISSUE TITLE
How do I convert IntervalColumn to days?

### ISSUE THREAD

**Issue by alexkyllo** [ibis-project/ibis#4562]
It looks like ToIntervalUnit isn't supported by any of the backends yet, so the `.days` accessor doesn't work.

```python
t = ibis.table([('a', 'date'), ('b', 'date')], 'my_data')
ibis.duckdb.compile(t.mutate(diff=(t.a - t.b).days))

~/.pyenv/versions/3.9.9/lib/python3.9/site-packages/ibis/backends/base/sql/__init__.py in compile(self, expr, limit, params, timecontext)
    277             backend.
    278         """
--> 279         return self.compiler.to_ast_ensure_limit(
    280             expr, limit, params=params
    281         ).compile()

~/.pyenv/versions/3.9.9/lib/python3.9/site-packages/ibis/backends/base/sql/compiler/base.py in compile(self)
     38     def compile(self):
     39         compiled_setup_queries = [q.compile() for q in self.setup_queries]
---> 40         compiled_queries = [q.compile() for q in self.queries]
     41         compiled_teardown_queries = [
     42             q.compile() for q in self.teardown_queries

~/.pyenv/versions/3.9.9/lib/python3.9/site-packages/ibis/backends/base/sql/compiler/base.py in <listcomp>(.0)
     38     def compile(self):
     39         compiled_setup_queries = [q.compile() for q in self.setup_queries]
---> 40         compiled_queries = [q.compile() for q in self.queries]
     41         compiled_teardown_queries = [
...
--> 258             raise com.OperationNotDefinedError(
    259                 f'No translation rule for {type(op)}'
    260             )

OperationNotDefinedError: No translation rule for <class 'ibis.expr.operations.temporal.ToIntervalUnit'>
```

I also can't divide by `ibis.interval(days=1)` because the division operator isn't defined for these types:

```python
t = ibis.table([('a', 'date'), ('b', 'date')], 'my_data')
ibis.duckdb.compile(t.mutate(diff=(t.a - t.b) / ibis.interval(days=1)))

TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_11460/3261144050.py in <module>
      1 t = ibis.table([('a', 'date'), ('b', 'date')], 'my_data')
----> 2 ibis.duckdb.compile(t.mutate(diff=(t.a - t.b) / ibis.interval(days=1)))

TypeError: unsupported operand type(s) for /: 'IntervalColumn' and 'IntervalScalar'
```

If I have an interval column representing a length of time, how can I transform it to an (integer or float type) count of days?

I'm using `ibis-framework==3.2.0`. Tested with duckdb both 0.4.0 and 0.5.1.

**Comment by alexkyllo** [comment]
By the way, I believe the equivalent of `IntervalColumn.days` is supported by DuckDB, see `extract()` here: https://duckdb.org/docs/sql/functions/interval 
It looks Ibis' codegen for it just isn't implemented yet, is that right?

**Comment by cpcloud** [comment]
@alexkyllo Thanks for opening an issue!

It looks like we may not have implemented a couple things here, as you noticed :)

1. Translation of `ToIntervalUnit` looks unimplemented for any of the backends, that's a relatively straightforward thing to implement, though there may be a very long tail of annoyances for one or more of the backends.
2. It looks like the division operator is just not implemented at the API level for intervals. This would need of course the implementation as `__div__` on `IntervalValue` as well as a translation rule for one or more backends.

**Comment by cpcloud** [comment]
I think we'll tackle this for 7.0, likely by introducing a new `delta` or `diff` API that computes an integer number of `$UNIT`s between two temporal types.

**Comment by cpcloud** [comment]
There's a new [`delta` API](https://ibis-project.org/reference/expression-temporal#ibis.expr.types.temporal.TimestampValue.delta) in 7.0.0 that allows you to compute the number of units between two timestamps, two dates, or two times! Closing as completed!
