### ISSUE TITLE
feat: add polars as a backend

### ISSUE THREAD

**Issue by ritchie46** [ibis-project/ibis#4564]
I would like to add polars as a backend of IBIS. Would that be in the scope of the project? 

What would be required to make this work? Does IBIS generate SQL or subtrait IR, or is the mapping more direct?

**Comment by cpcloud** [comment]
@ritchie46 👋🏻 Welcome!

A polars backend is definitely in scope!

I would suggest using the polars API directly, and following the pattern in the [DataFusion backend](https://github.com/ibis-project/ibis/blob/master/ibis/backends/datafusion/compiler.py).

Outside of implementing the backend, there are a few steps needed to get the backend automatically enrolled in the backend test suite and make it possible to install `ibis-framework[polars]` for users who only want the `polars` backend:

1. Add `polars = { version = "...", optional = true }` to `tool.poetry.dependencies`
1. Add a `polars = ["polars"]` extra to `tool.poetry.extras`
1. Add `"polars"` to the `all` extra, so developers get this dependency automatically
1. Add `polars = "ibis.backends.polars"` to `[tool.poetry.plugins."ibis.backends"]` in `pyproject.toml`
1. Run `poetry lock --no-update` to update `poetry.lock`.

**Comment by jcrist** [comment]
Fixed by #4566. Closing.
