### ISSUE TITLE
bug: visualize label_edges fails after recent (?) merged PRs

### ISSUE THREAD

**Issue by ams1** [ibis-project/ibis#4619]
Hey,

Just synced my local repo with ibis master and I noticed:

- a GOOD thing:

   The `predicates` of `ops.Join`(s) are now returned by the `Graph.from_bfs`  -> in recent earlier versions they were NOT returned (I wanted to open an issue about that, but didn't want to bother you with non-essential feature requests)

- an...OTHER thing: 😄 
  Because these `ops.Join predicates` recently appeared (?), the following snippet now started failing:

  ```py
  import ibis
  
  t = ibis.table((("a", "int32"), ("b", "string")))
  t1 = ibis.table((("c", "int32"), ("b", "string")))
  
  expr = t[(t["a"] == 1) & (t["b"] == "x")]
  joined = expr.join(t1, (t["b"] == t1["b"]))
  
  joined.visualize(label_edges=True)
  ```
  - The problem:
    ![image](https://user-images.githubusercontent.com/10154357/194530692-9fce060d-af78-41d6-b6b7-2a3841f07df9.png)

  - A quick-and-really-dirty fix:

![image](https://user-images.githubusercontent.com/10154357/194578747-cd181217-60ce-43a3-ae84-3cb6e9cf7c28.png)

  - A question - **pls don't answer if it takes you a long time**:
    **For me it seems wierd that the `ops.Join predicates` are a `tuple` (!) and not a `NodeList` like the predicates of other nodes. Why aren't they a `NodeList`?**

After fixing the bug, the `ops.Join predicates` are shown as expected:

![image](https://user-images.githubusercontent.com/10154357/194532833-eae82596-48fa-4543-8545-4eb47d6b7de4.png)

Thanks

**Comment by gforsyth** [comment]
Thanks for opening this @ams1 and sorry for the delay in responding!  It's been on our radar but we forgot to actually write anything :woozy_face: 

I've put up a PR with a quick fix for the join predicates issue.

> * For me it seems wierd that the `ops.Join predicates` are a `tuple` (!) and not a `NodeList` like the predicates of other nodes. Why aren't they a `NodeList`?

They should be a `NodeList` -- it's on our list of things to fix up!
