### ISSUE TITLE
Inconsistencies and *possible* improvements when working with columns

### ISSUE THREAD

**Issue by jcmkk3** [ibis-project/ibis#4629]
I've been enjoying exploring Ibis now that I've gotten over the hump of getting it setup (thanks for the help!). I've been trying to record my exploration while I learn it. One thing that I've noticed is some inconsistencies in the capabilities of the different ways that a user can specify column transformations. I tried to summarize them in the table below, along with a slightly more lengthy explanation in [this gist](https://gist.github.com/jcmkk3/691fc7e40ec5f165f2f5a8b8bd8f076a).

---

## Comparison Matrix

| Feature                                      | TA Attr | TA Item | Magic Attr | Magic Item | lambda Attr | lambda Item | def Attr | def Item |
|:---------------------------------------------|:-------:|:-------:|:----------:|:----------:|:-----------:|:-----------:|:--------:|:--------:|
| Select a column with valid python identifier | ✔️     | ✔️      | ✔️        | ✔️         | ✔️         | ✔️          | ✔️      | ✔️       |
| Select a column with spaces or other symbols | ❌     | ✔️      | ❌        | ✔️         | ❌         | ✔️          | ❌      | ✔️       |
| Auto completion for column names             | ✔️     | ❌      | ❌        | ❌         | ❌         | ❌          | ❌      | ❌       |
| Auto completion for common methods           | ✔️     | ✔️      | ❌        | ❌         | ❌         | ❌          | ❌      | ❌       |
| Auto completion for type specific methods    | ✔️     | ❌      | ❌        | ❌         | ❌         | ❌          | ❌      | ❌       |
| Expression can return a result standalone    | ✔️     | ✔️      | ❌        | ❌         | ❌         | ❌          | ❌      | ❌       |
| Column can be renamed using `.name`[^1]      | ✔️     | ✔️      | ✔️        | ✔️         | ❌         | ❌          | ❌      | ❌       |
| Column can be renamed using kwargs[^2]       | ✔️     | ✔️      | ✔️        | ✔️         | ✔️         | ✔️          | ✔️      | ✔️       |
| Can reference columns created during query   | ❌     | ❌      | ✔️        | ✔️         | ✔️         | ✔️          | ✔️      | ✔️       |

[^1]: Specific to assigning to a variable and renaming when using it in a query

[^2]: Can only be a valid python identifier unless using dictionary unpacking `**{}`

---

Some of these restrictions seem understandable, but some seem a bit more arbitrary and might be possible to improve. Ideally, it would be nice for the different styles to be as interchangeable as possible.

For instance, it would be nice for the *Table Attached, item based* style to give auto completion of the column names (like pandas) and give auto completion for methods of that column type. These table attached methods are a bit more wordy, but they do have the most opportunity for autocompletion since they know more about the table.

I also think that both *Table Attached* styles should allow referencing columns that don't exist on the attached table. This would simplify things for the user so they do not have to switch to the magic underscore or call back styles if they are trying to manipulate a column that was created during the current query.

It seems like the *magic underscore* style could get the more generic method auto completion so the user at least doesn't need to remember every method.

Lambdas could potentially get a similar treatment. I've seen lambdas autocomplete in vscode before, but I think it is language server and typing dependent.

I think this last one might be a bug, but magic underscores and call backs don't seem to be able to overwrite existing columns in a `mutate` with the `name` method. It works fine when using kwargs or if the name is different than any existing columns. See the gist for an example of this.

**Comment by gforsyth** [comment]
Hey @jcmkk3 -- thanks for the great writeup!  It's really helpful to be able to spot potential opportunities for improvements.

> For instance, it would be nice for the Table Attached, item based style to give auto completion of the column names (like pandas) and give auto completion for methods of that column type. These table attached methods are a bit more wordy, but they do have the most opportunity for autocompletion since they know more about the table.

The column names should be doable but I'll have to look up how to offer dict-like keys as completion options because I can't remember how that works.

> I also think that both Table Attached styles should allow referencing columns that don't exist on the attached table. This would simplify things for the user so they do not have to switch to the magic underscore or call back styles if they are trying to manipulate a column that was created during the current query.

I understand the ergonomics of this and it makes sense, but it also seems like it opens the door to some typo footguns.


> It seems like the _magic underscore_ style could get the more generic method auto completion so the user at least doesn't need to remember every method.

Do you have any suggestions on which methods are sufficiently generic for this?  We don't want to offer invalid completions and the deferred nature of the operator precludes looking up valid methods.



> Lambdas could potentially get a similar treatment. I've seen lambdas autocomplete in vscode before, but I think it is language server and typing dependent.

Yeah, I think this is an LSP thing.

> I think this last one might be a bug, but magic underscores and call backs don't seem to be able to overwrite existing columns in a `mutate` with the `name` method. It works fine when using kwargs or if the name is different than any existing columns. See the gist for an example of this.

That looks like a bug.

**Comment by jcrist** [comment]
> The column names should be doable but I'll have to look up how to offer dict-like keys as completion options because I can't remember how that works.

This is done in #4635.

**Comment by jcmkk3** [comment]
Thanks for the improvements from this discussion! I've been pretty busy this week, but here are some responses to your questions.

> > I also think that both Table Attached styles should allow referencing columns that don't exist on the attached table. This would simplify things for the user so they do not have to switch to the magic underscore or call back styles if they are trying to manipulate a column that was created during the current query.
> 
> I understand the ergonomics of this and it makes sense, but it also seems like it opens the door to some typo footguns.

I can also understand why it behaves the way that it does currently, I just find it a bit unfortunate that I have to switch syntax in this case (more so that I have to teach others to switch syntax). My thinking was that in cases where the expression was referring to a  column that was not currently in the table, it would produce a `deferred` expression like the current underscore does. Maybe there could be a comment in the repr letting users know that they will need to use it within a table where the column is available.

Edit: I see that there is even more to the checks than just whether they column is in the current table and that it is also connected to the attached table in general.

![Screenshot 2022-10-16 10 52 36 AM](https://user-images.githubusercontent.com/45919695/196050462-70a2a533-3333-4bb3-ac66-9e14eb22899b.png)

I'm not really sure what the right approach is. I guess the way it stands is fine. I don't like the other methods because they offer nothing for autocompletion. It can be hard to get autocompletion for both column names and methods in APIs like these. I've played around with different ideas in [my own library experiments](https://github.com/jcmkk3/opossom#column-expressions), but it is hard to know what the right tradeoff is.

> Do you have any suggestions on which methods are sufficiently generic for this? We don't want to offer invalid completions and the deferred nature of the operator precludes looking up valid methods.

I thought that there were already methods that were considered generic based on what the previous autocomplete of the item style access, but I think that maybe they are just the numeric methods.
 
![generic_autocomplete](https://user-images.githubusercontent.com/45919695/196051122-3ba38ca3-84ac-4e04-a282-507ee46429fd.png)

Again, thanks for reading my feedback. I've been enjoying the library
