### ISSUE TITLE
How to connect to Impala using ODBC / DSN?

### ISSUE THREAD

**Issue by matthiasgomolka** [ibis-project/ibis#4643]
I would like to use `ibis` to run queries against an Impala backend. When I use `pyodbc` to connect to Impala, I use the DSN:

```python
con_odbc = pyodbc.connect("DSN=my_dsn_name", autocommit=True)
```

Unfortunately, I have not managed to use ODBC and the DSN to connect using `ibis`.

Is this possible, and if yes, how?

**Comment by cpcloud** [comment]
@matthiasgomolka I don't think we have support for ODBC in the Impala backend. I think the best I can recommend right now is to construct your ibis expressions from `ibis.table` (unbound tables) and then execute the compile expressions against `con_odbc`.

Something like this:

```python
con_odbc = ...
t = ibis.table(...)
expr = ... # something based on t
sql = ibis.impala.compile(expr)
results = con_odbc.execute(sql)
```

It's not quite so convenient, but we're reluctant to do any work on the impala backend given that Impala itself is no longer developed.

**Comment by matthiasgomolka** [comment]
@cpcloud, thanks for the quick response!

May I ask where you got the information that Impala is no longer developed? [The last release was in June](https://twitter.com/ApacheImpala/status/1541565509250043905?s=20&t=elavZGz8KWLnFYtBiv5iAw), [their Jira](https://issues.apache.org/jira/projects/IMPALA/issues/IMPALA-11568?filter=allopenissues) seems to be quite active and [their homepage](https://impala.apache.org/) does not state anything like this...

**Comment by cpcloud** [comment]
Ah I was aware that a lot of the team left, so I assumed that development had ramped down. It's good to see that that's not the case!

**Comment by saulpw** [comment]
@matthiasgomolka Does the provided snippet solve your issue?  We thought about adding generic DBAPI2 connection support to Ibis but it doesn't seem like there would be much value.

**Comment by matthiasgomolka** [comment]
@saulpw, yes, this answers my question. I won't use Ibis for now since I would not really benefit from the consistent API across different backends. And Impala is the most important one for me right now.

Thanks for the snippet, anyway!

**Comment by juliuscrn** [comment]
I spent an entire day trying to get Ibis to connect to Impala with no success. SQLalchemy works, bare impyla works, Ibis doesn't, and the errors are not helpful.  I tried every port/host combination and just nothing works. I get either `TTransportException: Could not connect to any of...`, `TTransportException: TSocket read 0 bytes`, or `HiveServer2Error: Failed after retrying 3 times`

**Comment by cpcloud** [comment]
@juliuscrn Happy to help, but can you open a new issue with more details, such as your code, ibis version, impyla version etc?

Thanks!

**Comment by juliuscrn** [comment]
Yes, of course, will try to do so tomorrow.
