### ISSUE TITLE
`ibis.desc(col)` in a `order_by` in a windowed operation is causing an error

### ISSUE THREAD

**Issue by kesmit13** [ibis-project/ibis#4644]
If I use `ibis.desc(...)` in a `order_by`, I get the following error:
```
~/.pyenv/versions/3.9.4/lib/python3.9/site-packages/ibis/expr/types/groupby.py in _get_window(self)
    232                 map(self.table._ensure_expr, util.promote_list(groups))
    233             ),
--> 234             order_by=list(
    235                 map(self.table._ensure_expr, util.promote_list(sorts))
    236             ),

~/.pyenv/versions/3.9.4/lib/python3.9/site-packages/ibis/expr/types/relations.py in _ensure_expr(self, expr)
    181             return expr.resolve(self)
    182         elif not isinstance(expr, Expr):
--> 183             return expr(self)
    184         else:
    185             return expr

TypeError: 'DeferredSortKey' object is not callable
```

I believe the value returned by `ibis.desc` should have `resolve` called on it, but the code that does the resolution only checks for subclasses of `Deferred`. The `DeferredSortKey` does not inherit from that. I don't know if the correct solution is to inherit from `Deferred` or add a case to the code that checks for the `resolve` method.

**Comment by jcrist** [comment]
Can you provide a reproducible example expression demonstrating this issue? You might make use of unbound tables (e.g. `ibis.table(some_schema)`) to avoid depending on any specific backend or data. For example:

```python
t = ibis.table({"x": "int", "y": "string"})
expr = # some expression here
```

**Comment by kesmit13** [comment]
This is an example I'm running against our backend which is based on MySQL.
```
df = pd.DataFrame(dict(a=[1,2,3], b=[6,5,4]))
tbl = conn.create_table('test', df, force=True)
tbl.group_by('a').order_by(ibis.desc('a')).mutate(foo=ibis.row_number()).execute()
```

**Comment by jcrist** [comment]
Closing as stale, feel free to reopen if the problem persists.
