### ISSUE TITLE
bug(deps): cannot install impala dialect on Windows

### ISSUE THREAD

**Issue by kissgyongyver** [ibis-project/ibis#4666]
I am trying to install ibis with impala dialect on Windows:
pip install ibis-framework[impala]

But I get an error that it cannot build Kerberos:

 Building wheel for kerberos (setup.py) ... error
  ERROR: Command errored out with exit status 1:
 "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I<env>\include -I<env>\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcsrc/base64.c /Fobuild\temp.win-amd64-3.8\Release\src/base64.obj 'krb5-config' is not recognized as an internal or external command, operable program or batch file.

**Comment by jcrist** [comment]
I think that's the best option for us. I pushed up https://github.com/cloudera/impyla/pull/504 to fix the issue upstream, but that may take a while to resolve.

**Comment by kissgyongyver** [comment]
Thanks for the fast reaction!!!!

**Comment by kissgyongyver** [comment]
Thanks for the fast reaction!!!

**Comment by juliuscrn** [comment]
I'm trying to get Ibis to work on Windows with no success. Still seems to try to build Kerberos:

![image](https://github.com/ibis-project/ibis/assets/10067941/2ebcb67e-f59e-4555-b4ce-a3b435b908ba)

**Comment by lostmygithubaccount** [comment]
@juliuscrn per the error message do you have microsoft visual C++ 14.0 or greater installed? I don't have a windows machine so it's difficult to try to reproduce (not sure any of the maintainers have windows)

**Comment by juliuscrn** [comment]
Somehow the issue went away by upgrading from python 3.7 to 3.10

**Comment by cpcloud** [comment]
> the issue went away by upgrading from python 3.7 to 3.10

The minimum Python version for the latest release of ibis is 3.9 per our [versioning policy](https://ibis-project.org/versioning/#supported-python-versions).

The older version didn't have the relevant PRs merged before it was released, hence the installation issues.
