### ISSUE TITLE
Kerberos authentication in jenkins script should be parametrized

### ISSUE THREAD

**Issue by laserson** [ibis-project/ibis#467]
Currently, we hardcode the Kerberos authentication in the jenkins script that's specific to Cloudera's internal infra.  This should be parametrized to make it easier for others to use.

**Comment by raderaj** [comment]
+1; We're having trouble installing ibis because of the dependencies on request-kerberos. Don't know if this is related or not.

**Comment by cpcloud** [comment]
Jenkins is thankfully not involved at all anywhere in ibis anymore!
