### ISSUE TITLE
docs(api): backend specific connection parameters in the docstring of the connect method

### ISSUE THREAD

**Issue by ogrisel** [ibis-project/ibis#4675]
At the moment the docstring of the main public factory method for a given backend is not helpful because it does not document what are the backend-specific connection parameters:

```python
>>> help(ibis.duckdb.connect)
Help on method connect in module ibis.backends.base:
 
connect(*args, **kwargs) -> 'BaseBackend' method of ibis.backends.duckdb.Backend instance
    Connect to the database.
    
    Parameters
    ----------
    args
        Connection parameters
    kwargs
        Additional connection parameters
    
    Notes
    -----
    This returns a new backend instance with saved `args` and `kwargs`,
    calling `reconnect` is called before returning.
    
    Returns
    -------
    BaseBackend
        An instance of the backend
```

However the docstring of the concrete `do_connect` method is more helpful:

```python
>>> help(ibis.duckdb.do_connect)
Help on method do_connect in module ibis.backends.duckdb:
 
do_connect(database: 'str | Path' = ':memory:', path: 'str | Path' = None, read_only: 'bool' = False, **config: 'Any') -> 'None' method of ibis.backends.duckdb.Backend instance
    Create an Ibis client connected to a DuckDB database.
    
    Parameters
    ----------
    database
        Path to a duckdb database.
    read_only
        Whether the database is read-only.
    config
        DuckDB configuration parameters. See the [DuckDB configuration
        documentation](https://duckdb.org/docs/sql/configuration) for
        possible configuration values.
    
    Examples
    --------
    >>> import ibis
    >>> ibis.duckdb.connect("database.ddb", threads=4, memory_limit="1GB")
```

and the example actually documents the usage of the `connect` method instead of the `do_connect` method.

I think the `ibis.duckdb.connect.__doc__` attribute should be updated one way or another to either include the content of `ibis.duckdb.do_connect.__doc__` or at least refer to the `do_connect` method of the backend for more details.

**Comment by gforsyth** [comment]
Thanks for raising this @ogrisel -- I think this is a great idea.

**Comment by ogrisel** [comment]
I am working on a PR.

**Comment by ogrisel** [comment]
@gforsyth Note that the backends docs already redirect the user to the docstrings of the `do_connect` method of the backend subclasses:

https://ibis-project.org/docs/dev/backends/ClickHouse/

So a dynamic docstring for the `connect` "meta"-method would be nice but I think it's good enough the way it is now that #4680 has been merge.
