### ISSUE TITLE
Infer avro schemas using Python tools

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#468]
Impala doesn't yet support Avro record schema inference. It would be relatively easy for us to do this ourselves -- the main challenge will be determining the number of bytes that need to be read from an example avro file to parse the schema

e.g. https://pypi.python.org/pypi/fastavro/ will work

**Comment by cpcloud** [comment]
Out of scope. We'd use a 3rd party library for this, and push upstream changes needed to extract schema information.

**Comment by th0ger** [comment]
Late for the party. Looking for ways to infer avro schemas from data records (objects) in Python.
@cpcloud Did you have a spceific 3rd party lib in mind at writing?

I have only found Spark json->arvo inference so far, but trying to avoid Spark.

**Comment by cpcloud** [comment]
I'd probably start by looking into https://avro.apache.org/docs/1.11.1/getting-started-python/ and if that doesn't suit your use case for performance reasons then I'd look into https://fastavro.readthedocs.io/en/latest/.

**Comment by th0ger** [comment]
@cpcloud I already know the avro lib well. In fact I'm trying to rewite [avro.schema](https://github.com/apache/avro/blob/master/lang/py/avro/schema.py) into an inference lib, but hoping to find existing methods.
