### ISSUE TITLE
feat: better tracebacks for type comparison errors

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#4710]
I have an expression something like this, but with more comparisons and more operations, generally (so harder to visually parse)
```python
expr = basics.join(ratings, basics.tconst == ratings.tconst).filter(
                    [_.titleType == "movie", _.numVotes > 10, _.averageRating > 3.5]
                    )
```

When I wrote that, I didn't know that `numVotes` was actually a string column, so I get this error:

```python
         64 if not rlz.comparable(left, right):
    ---> 65     raise TypeError(
         66         f'Arguments with datatype {left.output_dtype} and '
         67         f'{right.output_dtype} are not comparable'
         68     )
         69 super().__init__(left=left, right=right)
    
    TypeError: Arguments with datatype string and int8 are not comparable
```

which is definitely valid, but even if I scroll all the way to the top of the traceback, all I'm going to find is that the offending line is the _single line_:

```python
----> 1 expr = basics.join(ratings, basics.tconst == ratings.tconst).filter(
      2     [_.titleType == "movie", _.numVotes > 10, _.averageRating > 3.5]
      3 )
```

So I'm thinking we can add in the names of these expressions to the error message.
I think we can probably iterate a bit on how the information is presented, but I think even without the exact logical operation that led to this error, giving the user a pointer to which expression names are involved should save a bunch of time when working interactively.

```python
         64 if not rlz.comparable(left, right):
    ---> 65     raise TypeError(
         66         f'Arguments "{left.name}" ({left.output_dtype}) and '
         67         f'"{right.name}" ({right.output_dtype}) are not comparable'
         68     )
         69 super().__init__(left=left, right=right)
    
    TypeError: Arguments "numVotes" (string) and "10" (int8) are not comparable
```

Are there cases where the expression would be unnamed?  Is it weird to have the literal `"10"` presented as the argument name?

**Comment by cpcloud** [comment]
Expressions always have names now, we generate something like `Add(x, 1)` for example for `x + 1`. Perhaps for literals we can make the error message reflect that by special casing them?

**Comment by cpcloud** [comment]
Very in favor of improving these messages.
