### ISSUE TITLE
bug(duckdb): re-registered view doesn't reflect changed schema

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#4729]
I initially register a `csv` file using `con.register`

```python
[ins] In [81]: movielens = con.register("/home/gil/data/movielens/ratings.csv", table_name="movielens")

[ins] In [82]: movielens
Out[82]: 
AlchemyTable: movielens
  column0 int32
  imdb_id int32
  rating  int32
```

This _looks_ correct but `imdb_id` is actually a string column and I haven't told DuckDB to sample enough rows to detect that.  But if I use `ALL_VARCHAR=True` to force all columns to load as strings, the returned table has the same schema as before:

```python
[ins] In [83]: movielens = con.register(
          ...:     "/home/gil/data/movielens/ratings.csv", table_name="movielens", ALL_VARCHAR=True
          ...: )

[ins] In [84]: movielens
Out[84]: 
AlchemyTable: movielens
  column0 int32
  imdb_id int32
  rating  int32
```

But if I register and change the underlying table name, the new schema is reflected:

```python
[ins] In [85]: movielens = con.register(
          ...:     "/home/gil/data/movielens/ratings.csv", table_name="_movielens", ALL_VARCHAR=True
          ...: )

[ins] In [86]: movielens
Out[86]: 
AlchemyTable: _movielens
  column0 string
  imdb_id string
  rating  string
```

The underlying call is `CREATE OR REPLACE VIEW` -- the view _is_ being replaced in `DuckDB`

```python
[ins] In [93]: con.con.execute("DESCRIBE movielens").fetchall()
Out[93]: 
[('column0', 'VARCHAR', 'YES', None, None, None),
 ('imdb_id', 'VARCHAR', 'YES', None, None, None),
 ('rating', 'VARCHAR', 'YES', None, None, None)]
```

but something in duckdb-engine or ibis seems to be caching the alchemy table schema.

**Comment by jcrist** [comment]
IIRC having traced this problem before, this caching happens at the SQLAlchemy level in the `MetaData` object.
