### ISSUE TITLE
bug: pandas backend returns incorrect results for grouped rolling windows

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#4746]
I'm going to leave this marked as broken for now, in the interest of merging the PR. I'll create a follow up issue for it.

_Originally posted by @cpcloud in https://github.com/ibis-project/ibis/pull/4739#discussion_r1008829322_

**Comment by ogrisel** [comment]
Is this related to #4676?

**Comment by cpcloud** [comment]
Ah, possibly. I'll look into deduplicating them tomorrow!

**Comment by cpcloud** [comment]
I think this issue is slightly different, so I'll leave it open for now.
