### ISSUE TITLE
Why ibis have no connect()? How to connect to postgresq?

### ISSUE THREAD

**Issue by hengaini2055** [ibis-project/ibis#4776]
I want to using ibis connect to postges db, but ibis have no connect. Why?
```
import ibis
ibis.__version__
'3.2.0'
```
OS: windows 10
Jupyter lab
python:  3.9.11
ibis                       3.2.0
ibis-framework             3.2.0

**Comment by hengaini2055** [comment]
```
conn = ibis.sqlite.connect("g:/temp/geography.db")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [29], line 1
----> 1 conn = ibis.sqlite.connect("g:/temp/geography.db")

AttributeError: module 'ibis' has no attribute 'sqlite'
```

**Comment by cpcloud** [comment]
Hi @hengaini2055. You have [the other ibis](https://github.com/ibis-project/ibis/issues/3716) installed. You cannot have both `ibis` (the web library) and `ibis-framework` (this library) installed.

**Comment by hengaini2055** [comment]
Thank you!  @cpcloud
