### ISSUE TITLE
feat(read): add support for https?:// prefix

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#4796]
DuckDB will ingest `http://` and `https://` prefixed parquet and CSV files with the `httpfs` extension -- we may need a new rule in the dispatcher because we don't want to use `pyarrow.datasets` for this.  Should be something like

```
CREATE OR REPLACE {view} AS SELECT * FROM 'https://...'
```

**Comment by gforsyth** [comment]
lol, @cpcloud already did this.

**Comment by cpcloud** [comment]
🎉
