### ISSUE TITLE
Create/Insert data into one backend from another backend

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#4800]
I'd like to be able to take a query from one backend and use it to create a table (or insert into an existing table) in another backend.

Example user session:

```python
import datetime

import ibis
from ibis import _

# Get the last day's worth of data from bigquery
bigquery = ibis.bigquery.connect(...)
query = bigquery.tables.some_table.filter(_.timestamp >= (ibis.now() - datetime.timedelta(days=1))

# Save it to a local sqlite database
sqlite = ibis.sqlite.connect("local.db")
sqlite.create_table("snapshot", query)
```

A few use cases:

- Downloading a subset of data from a large remote database (say bigquery) into a smaller local database (say duckdb or sqlite) for further analysis.
- ETL workloads where the data source and sink are in different databases (for example, load the last day's worth of data from bigquery, transform it, then insert it into an existing table in postgres).

I'm not sure if there are backend pairs where the data transfer wouldn't have to go through the ibis client process directly (meaning writing from backend1 to backend2 might have some optimized path), but if there are then it might be useful to design in a way that we could support that at some point.

For now a default implementation *might* be using the `to_pyarrow_batches` method on the source table and doing incremental writes to the sink table.

**Comment by lostmygithubaccount** [comment]
closing in favor of #8115, which we're planning on doing this quarter
