### ISSUE TITLE
bug(docs): broken dev instructions

### ISSUE THREAD

**Issue by craustin** [ibis-project/ibis#4812]
The [dev environment setup instructions](https://ibis-project.org/docs/dev/contribute/01_environment/) for `conda`/`mamba` and `pip` say to run `pip install -e .` from the `ibis` folder - but that yields:

```bash
$ pip install -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: ~/code/ibis/ibis
```

Has something changed recently - or am I doing something wrong?

**Comment by cpcloud** [comment]
@craustin Welcome! Thanks for opening an issue about this.

Can you try running

```sh
pip install 'poetry>=1.2'
```

and then running `pip install -e .` again?

We do make it a point to [test this setup in CI](https://github.com/ibis-project/ibis/blob/master/.github/workflows/check-generated-files.yml#L24) but it looks like we're possibly missing the installation of `poetry`.

**Comment by cpcloud** [comment]
@craustin Were you able to get set up? Let us know if you need any help!

**Comment by cpcloud** [comment]
Closing this out! @craustin Let us know if you still can't get things working.
