### ISSUE TITLE
feat: dremio backend

### ISSUE THREAD

**Issue by craustin** [ibis-project/ibis#4813]
What is the best way to create a Dremio backend? Would it make sense to create a new `BaseAlchemyBackend`-derived backend @ `/ibis/ibis/backends/dremio/`? There is a Dremio dialect for SQLAlchemy [here](https://github.com/narendrans/sqlalchemy_dremio) - but I'm not sure yet where/how that would be used in the creation of the Ibis backend.

**Comment by cpcloud** [comment]
@craustin Thanks again for opening an issue about this!

I would start by looking at the [postgres backend](https://github.com/ibis-project/ibis/blob/master/ibis/backends/postgres/__init__.py). It's the most mature and has the least backend hacks and workarounds of probably all the backends and should serve as a decent template for SQLAlchemy-based backend.

Feel free to put up a draft PR and we can help you iterate on it, especially around setting up a dremio container in our `docker-compose.yml` to use for local testing and CI runs!

**Comment by p-a-a-a-trick** [comment]
I've included "How to create a backend" as a list item in #4385.  Let me know if I should remove it or include any detail.

Side note: if someone finishes this before I start on that guide (it'll probably be one of the next three or four I do), feel free to a) write the guide yourself or b) include any notes you took along the way in this issue and I'll reference them while I'm writing up the guide.

**Comment by cpcloud** [comment]
@craustin Thanks for the issue. Since it's gone a bit stale I'm going to close it out.
