### ISSUE TITLE
feat: specifying schema with postgres

### ISSUE THREAD

**Issue by njesp** [ibis-project/ibis#4890]
### Is your feature request related to a problem?

How do I specify which schemaname(s) that will be searched for table t in the Postgres backend? 

Other than doing a 
alter user username set search_path=schema_name;
when connected to the database. 
```
import ibis
con = ibis.postgres.connect(url = "postgresql+psycopg2:///?service=service_name")
t = con.table("t")
y = t.group_by("b").mutate(z=t.a.sum())
```

### Describe the solution you'd like

I'd like to be able to specify search_path in python code. This could be as a ibis.options or something. 

### What version of ibis are you running?

3.2

### What backend(s) are you using, if any?

Postgres

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
In the meantime you can pass the schema in as a keyword argument to `con.table`:

```python
con.table("t", schema="my_schema")
```

**Comment by cpcloud** [comment]
Closing this out, since you can specify the schema in the `table` call.

**Comment by njesp** [comment]
Ah. Nice. I could not figure this out from the documentation. However, I still don't see a way to specify schema, when accessing con.tables.
