### ISSUE TITLE
bug(ClickHouse): incorrect implementation of 'list_tables' method

### ISSUE THREAD

**Issue by kosavinads** [ibis-project/ibis#4896]
### What happened?

Incorrect implementation of 'list_tables' method in ClickHouse backend. How can I push my fix?
Correct version:

    def list_tables(self, like=None, database=None):
        if database is not None:
            data, _ = self.raw_sql("SELECT name FROM system.tables WHERE database = '{}'".format(database))
        elif self.con.connection.database is not None:
            data, _ = self.raw_sql(
                "SELECT name FROM system.tables WHERE database = '{}'".format(self.con.connection.database))
        else:
            data, _ = self.raw_sql("SELECT name FROM system.tables")
        if not data:
            return []
        tables = list(data[0])
        return self._filter_with_like(tables, like)

### What version of ibis are you using?

3.2.0

### What backend(s) are you using, if any?

ClickHouse

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ender-4029** [comment]
In order to push a fix you will want to make a [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request). The link to the github docs should help if you want to try it out!

**Comment by kosavinads** [comment]
![image](https://user-images.githubusercontent.com/117784139/203879747-0a81a876-9fc6-490c-b124-b4dc620d3f5d.png)

Should I request permission to push to remote?

**Comment by cpcloud** [comment]
@kosavinads Please take a look at the link posted by @Ender-4029.

**Comment by cpcloud** [comment]
Make sure to include the rationale in your PR description as well as a test that fails without your changes and succeeds with your changes. We need a minimal record of _why_ the current implementation is wrong to prevent regressions.
