### ISSUE TITLE
bug: insert failing on postgres backend when primary keys exist

### ISSUE THREAD

**Issue by robdmc** [ibis-project/ibis#4974]
### What happened?

Using the postgres backend.

- Create a table with arbitrary columns, but having a primary key (either integer, or uuid)
- Use ibis to insert records into that table without supplying values for the primary key (e.g. id column)
- It appears ibis tries to insert null values into the id field causing postgres to raise an error

### What version of ibis are you using?

3.2.0

### What backend(s) are you using, if any?

postgres

### Reproducing setup
For a docker setup that reproduces the problem, see: https://github.com/robdmc/ibis_pg_test

### This code is in the `doit.py` file and is failing.

```python
import os
import ibis
import pandas as pd

def get_postgres_creds():
    kwargs = {
        'host': os.environ['PGHOST'],
        'user': os.environ['PGUSER'],
        'password': os.environ['PGPASSWORD'],
        'database': os.environ['PGDATABASE']
    }
    return kwargs


def get_postgres_ibis_connection():
    kwargs = get_postgres_creds()
    conn = ibis.postgres.connect(**kwargs)
    return conn


conn = get_postgres_ibis_connection()
conn.raw_sql("drop table if exists test")

# Both integer and uuid currently failing
try_uuid = False
if try_uuid:
    conn.raw_sql("create table test (id uuid, x float, PRIMARY KEY (id))")
else:
    conn.raw_sql("create table test (id integer, x float, PRIMARY KEY (id))")

# For integer primary key, this works
df = pd.DataFrame({'id': [1, 2, 3], 'x': [1., 2., 3.]})
conn.insert('test', df)

# Fails
df = pd.DataFrame({'x': [1., 2., 3.]})
conn.insert('test', df)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@robdmc Thanks for the report.

The `PRIMARY KEY` modifier isn't enough to induce autoincrement behavior AFAIU. You also need an autoincrementing type for the column, such as `SMALLSERIAL`/`SERIAL`/`BIGSERIAL`.

**Comment by robdmc** [comment]
@cpcloud That appears to be the issue.  I changed the `doit.py` script in the reproducer to use bigserial, and everything works as expected.  I will close this out, as I don't think it's actually a bug.

Thanks for your quick response.
