### ISSUE TITLE
Design a UDF/UDA extension API for Ibis

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#50]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Wednesday Jan 07, 2015 at 23:57 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/50_

---

Not going to get done in a first cut of the project, but we ought to think about how to weave user-defined functions through the expression IR and subsequent SQL generation. For example, a UDF operating on strings would be made available as a new instance method on `StringValue`, or multiple UDFs could be coalesced into a single Python API with some options, which could down the road be compiled to the correct concrete SQL UDF call. 

``` python
# new UDF registration code omitted

transformed_expr = table['some_strings'].my_udf()
```

**Comment by cpcloud** [comment]
Closing. We will want to improve UDFs and implement UDAs, but this issue is stale.
