### ISSUE TITLE
Support for getting nested-type data via Impyla

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#502]
To coincide with impala 2.3 release. cc @laserson 
- schemas
- row fetching

**Comment by laserson** [comment]
Missed this.  Created cloudera/impyla#131

Is there a cluster/data set I can use to experiment?

**Comment by wesm** [comment]
You can probably use the 10-node Impala perf cluster

**Comment by cpcloud** [comment]
Now that we have the ability to test impala, and we can create data using Hive, I'm going to put up a PR and close this out. Marking for 0.11, in case it's not 100% straightforward.

**Comment by kszucs** [comment]
What's the status of this? Are nested types supported by impyla?

**Comment by cpcloud** [comment]
Stale.
