### ISSUE TITLE
bug: Negative string index gives incorrect results for some SQL backends

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#5037]
### What happened?

Depending on the backend used, a negative string index can give incorrect results. Things are usually incorrect in one of two ways:
- Off-by-one (sqlite, duckdb, probably others)
- Empty string (postgres, probably others)

```python
In [1]: import ibis, pandas as pd

In [2]: df = pd.DataFrame({"x": ["abcd", "xy"]})

In [3]: sqlite = ibis.sqlite.connect()

In [4]: sqlite.create_table("test", df)

In [5]: sqlite.tables.test.x[-2].execute()  # wrong, off-by-one
Out[5]: 
0    d
1    y
Name: Substring(x, -2, 1), dtype: object

In [6]: postgres = ibis.connect("postgres://postgres:postgres@localhost:5432")

In [7]: postgres.create_table("test", df)

In [8]: postgres.tables.test.x[-2].execute()
Out[8]: 
0    
1    
Name: Substring(x, -2, 1), dtype: object

In [9]: ibis.show_sql(postgres.tables.test.x[-2])
SELECT
  SUBSTR(t0.x, -2 + 1, 1) AS "Substring(x, -2, 1)"
FROM test AS t0
```

This has to do with how `Substring` is implemented - for most SQL backends we translate `string_col[index]` as:

```
SUBSTR(column, index + 1, 1)
```

which is correct for nonnegative indices, but incorrect for negative ones. Duckdb and SQLite support negative indices for `SUBSTR`, while postgres silently ignores negative indices.

A few options:
- We could outlaw negative indices. Negative slices currently error. This wouldn't work if the `index` is an expression though.
- We could fix this for literal values only. This is easy to do for all backends I've surveyed, but wouldn't work if `index` is an expression.
- We could implement this at the SQL level where the proper `SUBSTR`/`RIGHT` calls are made dynamically based on the value of `index` (fully supporting expressions for `index`).

### What version of ibis are you using?

dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I suppose we ought to fully support this if we can, to ensure that our Pythonic APIs are in fact Pythonic.

**Comment by anjakefala** [comment]
It was `/take` lol. Thank you @gforsyth =)
