### ISSUE TITLE
versions of ibis-framework newer than 2.0.0 have a upper cap on supported Python to <3.11

### ISSUE THREAD

**Issue by tacaswell** [ibis-project/ibis#5047]
This leads to `pip install ibis-framework` installing v2.0.0 on py311 and py312 which was very surprising.  It does not look like ibis has any (non-test) c-extensions so it should be safe to just drop the pin?

I do not mind having to deal with compilation or dependency management if I am an early adopter / working past the stable edge, but it is very frustrating to both not be able to install the currently supported and to be silently down-graded to an older version.

I'm not sure what the fix here is other than to un-pin future releases.

**Comment by cpcloud** [comment]
Thanks for the heads up! We fixed this a while ago.

**Comment by cpcloud** [comment]
If you want to use > py310 you'll have to develop against `master` until we release 4.0
