### ISSUE TITLE
bug: Tutorial docs examples are broken due to the data not being downloaded properly

### ISSUE THREAD

**Issue by AndrewRook** [ibis-project/ibis#5066]
### What happened?

(I couldn't find an open issue about this, but if I missed it and this is already known my apologies!)

The code samples [in the tutorial](https://ibis-project.org/docs/dev/tutorial/) are almost entirely broken because the underlying data the tutorials rely on is not being downloaded. Whatever is being used to run the code in those docs can't find `curl`:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/923682/209174218-9a7241c1-5861-4ec8-8e29-109a19c8c775.png">

This then has the downstream impacts you'd expect, where an empty DB gets loaded and then all the commands that try to use tables in the DB fail, e.g:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/923682/209174400-03c35e2a-f9ba-4362-ba09-c58505520dc7.png">

### What version of ibis are you using?

N/A

### What backend(s) are you using, if any?

N/A

### Relevant log output

```sh
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @AndrewRook !! 

Thanks for the report -- it looks like our docs environment is missing curl, should be a pretty quick fix. Thanks for bringing it to our attention!

**Comment by cpcloud** [comment]
Ah yeah, probably just need to chuck `curl` into the `mkShellEnv` in `flake.nix`.

I wonder if there's a way we can make the notebook builds properly error when they fail to render.
