### ISSUE TITLE
Examine dplyr test suite for missing functionality

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#51]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Thursday Jan 08, 2015 at 00:04 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/51_

---

Will help catch some of the obvious things we're currently missing:

https://github.com/hadley/dplyr/tree/master/tests/testthat

I have not started looking yet. We can use this issue to track progress as necessary

**Comment by cpcloud** [comment]
Closing.
