### ISSUE TITLE
Simplifying long-to-wide transformations

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#52]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Thursday Jan 08, 2015 at 00:35 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/52_

---

as seen here: http://sqlschool.modeanalytics.com/common-problems/pivoting-rows-to-columns.html

punchline, this query:

``` sql
SELECT conference,
       SUM(players) AS total_players,
       SUM(CASE WHEN year = 'FR' THEN players ELSE NULL END) AS fr,
       SUM(CASE WHEN year = 'SO' THEN players ELSE NULL END) AS so,
       SUM(CASE WHEN year = 'JR' THEN players ELSE NULL END) AS jr,
       SUM(CASE WHEN year = 'SR' THEN players ELSE NULL END) AS sr,
  FROM (
        SELECT teams.conference AS conference,
               players.year,
               COUNT(1) AS players
          FROM benn.college_football_players players
          JOIN benn.college_football_teams teams
            ON teams.school_name = players.school_name
         GROUP BY 1,2
       ) sub
 GROUP BY 1
 ORDER BY 2 DESC
```

Ew. Becomes more difficult when you don't know a priori the distinct values of a particular field (in which case multiple queries may be necessary). cf pandas / tidyr unstacking code

**Comment by cpcloud** [comment]
Closing. An interesting issue, but stale.
