### ISSUE TITLE
bug: CTEs for SQL backends generate invalid forward references

### ISSUE THREAD

**Issue by santind** [ibis-project/ibis#5215]
### What happened?

# Summary
When constructing a complex transformation graph for use with a SQL backend, the non-recursive CTEs extracted from the graph can contain forward references to CTEs defined later in the query.  Per the ANSI SQL standard, forward references for non-recursive CTEs are not standards-compliant, so the generated SQL may fail to execute on standards-compliant backends like BigQuery.

# Reproduction
This Ibis code is as simple as I could make it while still exhibiting the issue, derived from a valid real-world use case.  Depending on the graph construction, the forward-referenced CTE can appear in different places.
```python
import ibis


def _select_lowest(idf_table, key_columns):
    idf_keys = (
        idf_table.group_by(key_columns)
        .order_by(['value'])
        .mutate(__row_num__DROP=ibis.row_number())
    )
    idf_keys = idf_keys.filter(idf_keys['__row_num__DROP'] == 0)
    idf_return = idf_keys.join(
        idf_table,
        key_columns + ['value'],
        how='inner',
        suffixes=('', '__DROP'),
    )
    idf_return = idf_return[[c for c in idf_return.columns if not c.endswith('__DROP')]]
    return idf_return


def _table_schema():
    import ibis.expr.datatypes as dtypes
    return ibis.schema([
        ('key1', dtypes.int),
        ('key2', dtypes.int),
        ('value', dtypes.float),
    ])


def min_repro_bq():
    from ibis.backends import bigquery
    backend = bigquery.Backend()
    # conn = backend.connect(project_id='bigquery-public-data', dataset_id='bls')
    # mr0 = conn.table('wm')
    mr0 = ibis.table(_table_schema(), 'test_tbl')

    mr1 = mr0[mr0.key2 >= 50]
    mr2 = mr1['key1', 'key2', 'value']
    mr3 = mr2.distinct()

    mr4 = mr3['key1', 'key2']
    mr5 = mr1.left_join(mr4, mr1.key1 == mr4.key1, suffixes=('', '_y'))
    mr6 = _select_lowest(mr5, ['key1', 'key2'])
    mr7 = mr6['key1', 'key2', 'value']

    mr8 = mr3.union(mr7)

    final = mr8
    sql = backend.compile(final)
    print(final)
    print('\n\n\n\n\n')
    print(sql)
```

This generates the following SQL when run with Ibis 4.0.0.  Note the forward reference from `t0` to `t3`.
```sql
WITH t0 AS (
  SELECT `key1`, `key2`
  FROM t3
),
t1 AS (
  SELECT *
  FROM test_tbl
  WHERE `key2` >= 50
),
t2 AS (
  SELECT `key1`, `key2`, `value`
  FROM t1
),
t3 AS (
  SELECT DISTINCT `key1`, `key2`, `value`
  FROM t1
)
SELECT *
FROM t3
UNION ALL
SELECT `key1`, `key2`, `value`
FROM (
  SELECT `key1`, `key2`, `value`, `key1_y`, `key2_y`
  FROM (
    SELECT t6.`key1`, t6.`key2`, t6.`value`, t6.`key1_y`, t6.`key2_y`,
           t6.`__row_num__DROP`, t7.`key1_y` AS `key1_y__DROP`,
           t7.`key2_y` AS `key2_y__DROP`
    FROM (
      SELECT t8.*
      FROM (
        SELECT t1.`key1`, t1.`key2`, t1.`value`, t0.`key1` AS `key1_y`,
               t0.`key2` AS `key2_y`,
               (row_number() OVER (PARTITION BY `key1`, `key2` ORDER BY `value`) - 1) AS `tmp`
        FROM t1
          LEFT OUTER JOIN t0
            ON t1.`key1` = t0.`key1`
      ) t8
      WHERE t8.`__row_num__DROP` = 0
    ) t6
      INNER JOIN (
        SELECT t1.`key1`, t1.`key2`, t1.`value`, t0.`key1` AS `key1_y`,
               t0.`key2` AS `key2_y`
        FROM t1
          LEFT OUTER JOIN t0
            ON t1.`key1` = t0.`key1`
      ) t7
        ON (t6.`key1` = t7.`key1`) AND
           (t6.`key2` = t7.`key2`) AND
           (t6.`value` = t7.`value`)
  ) t5
) t4
```

Subquery extraction and alias assignment [happen in separate passes](https://github.com/ibis-project/ibis/blob/8d53d724275ebe4b2a0bb0bd7e2c2dfc399e049b/ibis/backends/base/sql/compiler/base.py#L96-L98), which I suspect is contributing to the lookahead issue.

### What version of ibis are you using?

Confirmed in in 3.0.0, 3.2.0, 4.0.0 (trunk)

### What backend(s) are you using, if any?

BigQuery, but the subquery extraction and aliasing logic lives in the base SQL backend

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@santind Thanks for the report! This looks pretty gnarly. Hopefully we can fix this for 4.1!

**Comment by cpcloud** [comment]
I was able to whittle this down into:

```
def test_invalid_forward_cte_refs(snapshot):
    mr0 = ibis.table(schema=ibis.schema(dict(key=dt.int)), name='leaf')

    mr1 = mr0.filter(ibis.literal(True))

    mr2 = mr1.join(mr1[['key']], ["key"])
    mr3 = mr2.join(mr2, ['key'])

    sql = ibis.to_sql(mr3, dialect="bigquery")
    snapshot.assert_match(str(sql), "out.sql")
```

Incorrect generated SQL:

```sql
WITH t0 AS (
  SELECT
    t1.`key`
  FROM t1
), t1 AS (
  SELECT
    t4.*
  FROM leaf AS t4
  WHERE
    TRUE
), t2 AS (
  SELECT
    t1.`key`
  FROM t1
  INNER JOIN t0
    ON t1.`key` = t0.`key`
)
SELECT
  t2.`key`
FROM t2
INNER JOIN t2 AS t3
  ON t2.`key` = t3.`key`
```

The first `t0` is reference an as-of-that-query undefined `t1` relation.

**Comment by cpcloud** [comment]
This issue is because our expression traversal algorithm assumes a tree (it's currently pre-order), that is, that no node has more than one parent. If we move the traversal to [a post-order (or reverse post-order) traversal](https://eli.thegreenplace.net/2015/directed-graph-traversal-orderings-and-applications-to-data-flow-analysis/) this problem should be fixed.
