### ISSUE TITLE
feat: Add `Column.get_table()` to look up owning `Table`

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5227]
### Is your feature request related to a problem?

I have a util function:

```python
def unnest_labeled(column: Column, label: str = "original_row") -> Table:
    """unnest(), but keep a row label so you can groupby and recombine later.

    Empty arrays are dropped.

    my_col
    [0, 1]
    []
    [2, 3, 4]

    ->
    my_col, original_row
    0, 0
    1, 0
    2, 2
    3, 2
    4, 2
    """
    owning_table = find_first_base_table(column.op()).to_expr()
    row_number = {label: ibis.row_number()}
    return owning_table.select(column.unnest(), **row_number)
```
so that for example I can split a string into tokens, apply a function to each token, and then recombine the transformed tokens.

I stole this use of `find_first_base_table(column.op()).to_expr()` from the `Column.topk()` method, but grepping for `find_first_base_table` reveals that `Column.value_counts()` and `StructValue.lift()` also use it.

I could change my util function to have the signature `def unnest_labeled(table: Table column_name: str, label: str = "original_row") -> Table`, but this makes it much harder to compose because then I would need a reference to the owning table. I want my functions to be able to take plain Columns.

### Describe the solution you'd like

Add this public method to a Column:

```python
def get_table(self: Column) -> Table:
    from ibis.expr.analysis import find_first_base_table

    return find_first_base_table(self.op()).to_expr()
```
This would allow my unnest_labeled() to do `owning_table = column.get_table()`.

I was following the naming convention of `Column.get_name()`, but am definitely open to other names.

### What version of ibis are you running?

4.0.0

### What backend(s) are you using, if any?

Should work with all.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NickCrews** [comment]
Another example function I use:

```python
def count_appearances(col: Column, other: Column | None = None) -> IntegerColumn:
    """Count the number of times a value in `col` appears.
    
    By default count then number of appearances in the `col` itself.
    If `other` is given, then count the number of appearances in `other`.

    This is equal to `col.map(other.value_counts())` in pandas.
    """
    if other is None:
        other = col
    other = other.name(col.get_name())
    vcs = other.value_counts()
    col_as_table = get_table(col)
    return col_as_table.left_join(vcs, col.get_name())["count"]
```

**Comment by cpcloud** [comment]
> Another example function I use:
> 
> ```python
> def count_appearances(col: Column, other: Column | None = None) -> IntegerColumn:
>     """Count the number of times a value in `col` appears.
>     
>     By default count then number of appearances in the `col` itself.
>     If `other` is given, then count the number of appearances in `other`.
> 
>     This is equal to `col.map(other.value_counts())` in pandas.
>     """
>     if other is None:
>         other = col
>     other = other.name(col.get_name())
>     vcs = other.value_counts()
>     col_as_table = get_table(col)
>     return col_as_table.left_join(vcs, col.get_name())["count"]
> ```

I think in this particular case you can use `.as_table()`, which is a method on all expr types including tables (a no-op), columns (single column table), scalars (it's complicated 😬).

It sounds like the original issue is a desire to promote `find_first_base_table` to an expression method, which is slightly different than converting a non-table expression into a table.

@NickCrews Am I capturing that correctly?

**Comment by NickCrews** [comment]
If I do:
```python
import ibis
import pandas as pd
from ibis.expr.types import Column, IntegerColumn, Table

def count_appearances(col: Column, other: Column | None = None) -> IntegerColumn:
    """Count the number of times a value in `col` appears.
    
    By default count then number of appearances in the `col` itself.
    If `other` is given, then count the number of appearances in `other`.

    This is equal to `col.map(other.value_counts())` in pandas.
    """
    if other is None:
        other = col
    other = other.name(col.get_name())
    vcs = other.value_counts()
    col_as_table = col.as_table()
    return col_as_table.left_join(vcs, col.get_name())["count"].fillna(0)


    return find_first_base_table(self.op())

df = pd.DataFrame(
    {
        "x": [1,2,3],
        "y": [1,1,3],
    }
)
t = ibis.memtable(df)
app = count_appearances(t.x, t.y)
t.mutate(app=app)
```
then I run into https://github.com/ibis-project/ibis/issues/5281. I think (don't exactly remember) that when I filed this issue, I thought https://github.com/ibis-project/ibis/issues/5281 was expected behavior, and I was trying to get around it with this solution. But I think now that you're right, `.as_table()` should work, we just need to fix https://github.com/ibis-project/ibis/issues/5281

**Comment by NickCrews** [comment]
I think this might be the same as #5281, where operating on columns and then trying to re-assign to the parent table isn't well-defined. I think I need to make it so my functions are Table -> Table, instead of Column -> Column. @cpcloud close this out if you agree. There might be a different example where get_table() is needed, but my two examples above (unnest_labeled and count_appearances) should both be Table -> Table functions I think.

**Comment by cpcloud** [comment]
@NickCrews I think that makes sense. A `Column` may have a different cardinality or parent table, but at least with a table you know how to combine that with other things: join :)
