### ISSUE TITLE
bug: Value.typeof() doesn't work in duckdb

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5231]
### What happened?

commit ba2ec59aa47a38220c3e480507e90bf1170fef61 removed typeof() from duckdb. It was working for me before and I relied on it. I couldn't find a PR or an issue that explained this, was this an accident?

### What version of ibis are you using?

master

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NickCrews** [comment]
Or I guess since expressions are statically typed, I can just do `isinstance(col, StringValue)` as a trivial workaround. But still, that function is present in duckdb, seems like it should be supported?

**Comment by cpcloud** [comment]
The idea with https://github.com/ibis-project/ibis/commit/ba2ec59aa47a38220c3e480507e90bf1170fef61 was to make sure that we don't have untested operations, but it looks like we may have inadvertently removed some inadvertently working things :)

Happy to add that back.

FWIW the utility of `typeof` is somewhat limited, though it can be useful to inspect what type the database thinks a particular value is. If you only need information like "is this a string" then we have some new utility functions on types:

```
In [8]: import ibis

In [9]: t = ibis.read_csv("https://ibis-project.org/docs/dev/backends/raw_support_matrix.csv")

In [10]: t.columns
Out[10]:
['FullOperation',
 'bigquery',
 'clickhouse',
 'dask',
 'datafusion',
 'duckdb',
 'impala',
 'mssql',
 'mysql',
 'pandas',
 'polars',
 'postgres',
 'pyspark',
 'snowflake',
 'sqlite',
 'trino']

In [11]: t.bigquery.type().is_boolean()
Out[11]: True
```

**Comment by NickCrews** [comment]
@cpcloud You're a machine! IDK who I can pass along my compliments to, but the quality, volume, and speed of work you're doing here is nuts!
