### ISSUE TITLE
Support for scalar parameters in expressions

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#53]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Thursday Jan 08, 2015 at 05:28 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/53_

---

A query or analytics task might depend on one or more as-yet-undefined scalar parameters. It would be useful to get typed scalar value expressions (which ought to be named in some unambiguous way) that can be used when forming expressions, and later the user can see all parameters an expression and specify values during evaluation

So two specific things to do here:
- Make some API to create typed ScalarExpr values wrapping parameter objects
- Add a public API to show all unbound parameters in an expression
- Add some way to specify values for the parameters during execution (so this will touch the SQL compiler). Could be so simple as:

```
expr.execute(conn, params=params)
```

**Comment by cpcloud** [comment]
This will be needed fairly soon. I'll assign myself and likely get to it over the weekend or early next week.
