### ISSUE TITLE
feat: Make string columns be dtype "string", not object, after execute()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5316]
### Is your feature request related to a problem?

If a table has any string columns, those columns in table.execute() are of dtype object, not "string".

### Describe the solution you'd like

They should be dtype "string". This would be breaking for some people I'm sure. But we need to move to the newer pandas dtypes.

### What version of ibis are you running?

4.0.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Well, we've got 5.0.0 coming up, seems like as good a time as any to make this change!

**Comment by NickCrews** [comment]
@cpcloud relatedly, int64 columns with nulls are turned into floats when executed into pandas dataframes. Really those should be pd.Int64(). And similar for all other nullable int dtypes.

**Comment by cpcloud** [comment]
Do you have any idea how widespread the use of these types is?

TBH I haven't followed whether these nullable types are now the common case or not.

**Comment by cpcloud** [comment]
Thanks @jreback!

I think we can do the following:

1. Add experimental support for this in 5.0, with an option `use_nullable_dtypes` (?) defaulting to `False`
2. If all goes well, switch that option to `True` for 6.0

@NickCrews @jreback Thoughts?

**Comment by jreback** [comment]
agtm

**Comment by NickCrews** [comment]
Yeah sgtm.

One tricky case: consider an int64 column: if it has nulls then it should be turned into an pd.Int64(), but what if there are no nulls? Should it be a simple np.int64, or still get upcast to the nullable type? Perhaps the flag shouldn't just be boolean, but `"never"`/`"as_needed"`/`"always"`?

IDK if pandas already has an API for choosing how to do this conversion, but if we can mirror/leverage that API then it would reduce the impedance mismatch.

**Comment by cpcloud** [comment]
The issue with that kind of optionality is that `has_nulls()` will introduce yet another scan of the data.

I think this is going to be an all or nothing option, and not that smart of an implementation (but correct!)

**Comment by NickCrews** [comment]
Cool, always going to nullable works for me

**Comment by NickCrews** [comment]
I can make a new issue for this if you ask, but I think I ran across another flavor of this today. Is this what we want the behavior to be, or should we make more assumptions about casting "object" in pandas to "string" in ibis?

```python
import ibis
import pandas as pd

df = pd.DataFrame(
    {
        "string": pd.Series(["a", "b", "c"], dtype="string"),
        "str": pd.Series(["a", "b", "c"], dtype="object"),
        "all_null": pd.Series([None, None, None], dtype="object"),
        "cat": pd.Series(["a", "b", "c"], dtype="category"),
    }
)
# works
ibis.memtable(df.drop(columns="all_null")).execute()
# IbisTypeError: DuckDB cannot yet reliably handle `null` typed columns; got null typed columns: ['all_null']
ibis.memtable(df).execute()
# IbisTypeError: DuckDB cannot yet reliably handle `null` typed columns; got null typed columns: ['str', 'all_null']
ibis.memtable(df.iloc[:0]).execute()
```

**Comment by gforsyth** [comment]
I'm going to close this out -- if the `pandas` string dtype situation had stabilized around pyarrow string dtypes we might've been able to do this, but this doesn't seem like something we're going to be able to handle.
I think using `to_pyarrow` and then creating a dataframe from that should be a viable workaround.
