### ISSUE TITLE
feat: Standardize interchangeable arguments to `read_csv()`

### ISSUE THREAD

**Issue by ksuarez1423** [ibis-project/ibis#5331]
### Is your feature request related to a problem?

The new `ibis.read_csv()` function is neat, but ultimately I find that I still have to visit the documentation of the backends themselves if I have anything other than the most well-formed files. In some cases, I'm okay with this -- not everyone has every feature, like DataFusion's 'infinite' option. However, in other cases, like arguments for separator declaration, I think that it'd be good if there was a route to pass some arguments through an API defined set, instead of using kwargs and checking the backend docs.

### Describe the solution you'd like

I'd like to see about adding Ibis-side arguments to `read_csv()` for the interchangeable arguments, at least as much as possible. I've dug through the API for the backends Ibis currently implements `read_csv()` for, and identified some candidates. 

The following top 3 can be implemented for all currently supported backends:

- The concept of delimiter specification exists identically between Polars, DuckDB, and DataFusion
- The concept of passing true/false for existence of a header row exists identially between the 3 backends.
- Column naming is top-level in Polars, and part of schema definition in DuckDB and DataFusion. However, Polars does have a separate argument to allow declaration of data types, so could just split up schema when inputting into Polars?

The rest work for Polars and DuckDB, but not DataFusion:

- Defining character for quoting data
- Skipping some number of rows at the start of a file

I identified others beyond this that are a bit more temperamental to reason out, but I think this set is something I'd really like to see available by default in Ibis without finding the right kwargs from the backends. 

I think these arguments could be implemented either as Ibis setting a standard then translating (e.g., making it so you have to use just delimiter), or supporting the different ones directly and documenting that (e.g., like Pandas, making it so you can use sep or delimiter and get the same result). I'm definitely open to seeing other routes, though!

### What version of ibis are you running?

4.1.0

### What backend(s) are you using, if any?

DuckDB, DataFusion, Polars

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krzysztof-kwitt** [comment]
I would love to see a table in our documentation that will show the compatibility of the methods that the backends provide. As part of this, one of the methods is `read_csv`, but we also have `create_table`, `drop_table` and others.

**Comment by krzysztof-kwitt** [comment]
Documentation that shows which backends have UDFs would be helpful too.

**Comment by ksuarez1423** [comment]
@krzysztof-kwitt I think you're referring to a support matrix of backend vs methods? If so, I believe the repo already has that, at: https://ibis-project.org/docs/dev/backends/support_matrix/ (note that, at the time of writing this reply, Streamlit apps are failing, so the raw CSV may be the best you can get at the present moment.) 

I am not sure, due to Streamlit apps currently not loading, if it includes UDF support in that matrix. If it would be helpful to extend it further, or if I am completely off the mark, would you be willing to make a new issue? This concern seems very worthy of being an issue instead of a comment.

**Comment by krzysztof-kwitt** [comment]
This table contains only operation matrix eg `ops.Greatest`, `ops.Date`, `ops.Literal`, mostly based on operation registry.
https://github.com/ibis-project/ibis/blob/7da56d0ef42a72f6c1fad6fffb6888d02f5a8e18/ibis/backends/bigquery/registry.py#L565
There is no information in our documentation about whether a given backend implements additional methods or features.
https://github.com/ibis-project/ibis/blob/7da56d0ef42a72f6c1fad6fffb6888d02f5a8e18/ibis/backends/base/sql/__init__.py#L113
https://github.com/ibis-project/ibis/blob/7da56d0ef42a72f6c1fad6fffb6888d02f5a8e18/ibis/backends/base/sql/__init__.py#L376
https://github.com/ibis-project/ibis/blob/7da56d0ef42a72f6c1fad6fffb6888d02f5a8e18/ibis/backends/base/__init__.py#L323
https://github.com/ibis-project/ibis/blob/7da56d0ef42a72f6c1fad6fffb6888d02f5a8e18/ibis/backends/base/__init__.py#L629
https://github.com/ibis-project/ibis/blob/7da56d0ef42a72f6c1fad6fffb6888d02f5a8e18/ibis/backends/base/__init__.py#L658
https://github.com/ibis-project/ibis/blob/7da56d0ef42a72f6c1fad6fffb6888d02f5a8e18/ibis/backends/base/__init__.py#L704
https://github.com/ibis-project/ibis/blob/7da56d0ef42a72f6c1fad6fffb6888d02f5a8e18/ibis/backends/base/__init__.py#L721
https://github.com/ibis-project/ibis/blob/7da56d0ef42a72f6c1fad6fffb6888d02f5a8e18/ibis/backends/base/__init__.py#L749

But I agree. This should be handled as a separate issue.

**Comment by cpcloud** [comment]
Closing as stale.
