### ISSUE TITLE
bug: Table.alias("same").alias("same") causes infinite recursion

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5381]
### What happened?

Causes `BinderException: Binder Error: infinite recursion detected: attempting to recursively bind view "alias"`

which makes sense. This can be avoided with a simple check of Table.get_name() and seeing if the name already matches. If already is set to that alias, then noop.

### What version of ibis are you using?

4.0.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NickCrews** [comment]
I wasn't doing it directly, but in a function that executes some custom sql and therefore requires the table to be a certain name:

```python
def with_reps(t: Table, col: str, result_name: str | None = None) -> Table:
    """For each val in col, map it to the number of times it appears in the column.

    Returns a new table with an extra `result_name` column.

    Similar to col.groupby(col).transform("count") in pandas.
    """
    # The simpler way is with window functions, but that is super slow:
    # https://github.com/duckdb/duckdb/discussions/6042
    t = t.alias("input")
    if result_name is None:
        result_name = col + "_count"
    sql = f"""
    WITH vcs AS (
        SELECT {col}, COUNT(*) AS {result_name} FROM input GROUP BY {col}
    )
    SELECT input.*, {result_name} FROM input, vcs WHERE input.{col} = vcs.{col}
    """
    return t.sql(sql)
```

I want to use the function multiple times in a row eg 
```python
t = with_reps(t, "column_a")
t = with_reps(t, "column_b")
t = with_reps(t, "column_c")
```
so I would hope that the aliasing was idempotent.

But you make me realize that this wouldn't work, because calling alias() actually creates a view on the backend. Subsequent calls would keep on using the same "input" table over and over. Really I need to call alias() with a unique name each time.

So as long as alias() creates a view, I think you're right, this expression should be invalid. In an ideal world, alias() would have no side effects on the backend, and then this expression should be valid. Closing.

**Comment by cpcloud** [comment]
Thanks @NickCrews!

If I may, you might be able to avoid `.sql` here and use window functions:

```
t.group_by(col).mutate([t.count().name(result_name)])
# alternatively
t.mutate([t.count().over(ibis.window(group_by=t.col)).name(result_name)])
```

You can avoid the join and the `.sql` that way!

**Comment by cpcloud** [comment]
Ha! I just saw you your comment and issue link!

**Comment by NickCrews** [comment]
I know, really a bummer, it would be so slick if it actually was fast enough :)
