### ISSUE TITLE
Deprecate `Backend.load_data`

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#5390]
`con.load_data` is identical to `con.create_table` with `force=True`. We should:

- Deprecate `load_data` in favor of `create_table`
- Rename `force` to `overwrite` in `create_table` to better match the `overwrite` kwarg in `insert`.

**Comment by cpcloud** [comment]
> con.load_data is identical to con.create_table with force=True

This isn't quite true. `force=True` doesn't overwrite if the table exists, it does nothing and leaves the table as is.

However, `overwrite` will have the `create or replace` behavior.
