### ISSUE TITLE
Review DDL APIs for uniformity across backends

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#5392]
There are a few existing DDL apis that we think are fine as is, but may not be uniformly supported across all backends. It would be good to review that all backends _uniformly_ support the following operations (where it makes sense), and that generic backend tests exist for the following operations:

- [ ] `drop_table(name, database=None, force=False)`
- [ ] `drop_view(name, database=None, force=False)`
- [ ] `truncate_table(name, database=None)`

**Comment by krzysztof-kwitt** [comment]
It would be fantastic if we could add user documentation that describes compatibility between different backends for these methods.

**Comment by NickCrews** [comment]
The arg names are inconsistent between backends, eg "obj" vs "expr" for create_table(). This would be a breaking change, but ideally they should all have the same arg names.

**Comment by NickCrews** [comment]
Could we make it so `temp` and `force` are available in all .create_table() and .create_view() implementations?
