### ISSUE TITLE
feat: support creating temporary tables

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#5393]
We should support creating temporary tables. I _think_ the cleanest way to do this would be to add a new `temp` (or `temporary`?) boolean kwarg to `create_table`, which defaults to `False`.

For backends that don't support temporary tables I think we should error nicely rather than trying to emulate things with a non-temporary table and an `atexit` handler. Since these APIs modify the backing database and potentially move lots of data around, I think relying on `atexit` to clean things up would be too risky (`atexit` handlers aren't guaranteed to run, and often don't in some common jupyter notebook workflows).

**Comment by jcrist** [comment]
One potential use case for this is computing an intermediate result and stashing it in an efficient way native to the backend. This would be similar to `.persist()` in dask. This was also discussed in #2339.

A concrete use case: currently our `read_csv`/`read_parquet`/`read_json` calls all create _views_ of the data, meaning any computations will have to redo the data parsing. Adding a new `.persist()` (or `.checkpoint()`, there's a few common names here) method that called `con.create_table(f"temp_{uuid}", expr, temp=True)` and returned the temporary table would be a more intuitive way of caching the parsed table inside the backing backend.

```python
t = ibis.read_csv("some_large_file.csv").persist()
```

Currently the user has to do:

```python
t = ibis.read_csv()
con = ibis.get_backend()
con.create_table("temp", t)
t = con.tables["temp"]
# do some work...
con.drop_table("temp")  # since it's not a temporary table
```

**Comment by lgonzalezsa** [comment]
Was exploring the usage of ibis mainly because of the deferred execution feature, to speed up my analysis. One of the main workflows I do have is the usage of temp tables in MSSQL engines, facing issues and just found this. Hope this can be implemented, the workaround using tables works but is not ideal.

**Comment by ogrisel** [comment]
I was just googling this myself after [reading this section](https://www.pola.rs/posts/the-expressions-api-in-polars-is-amazing/#cherry-on-top-clever-caching) of a polars tutorial that speaks about how natural it is with polars to cache intermediate results when interactively crafting a data processing pipeline.

I think it would be nice to have such streamlined caching API with various kinds of possible caching strategies:

- backend-specific, temporary tables as you suggest (I assume tied to the Python GC);
- backend-agnostic in-memory results (e.g. a-la `ibis.memtable`);
- backend-agnostic parquet or arrow files in a temporary folder managed by ibis, possibly as spill-over for the backend agnostic in-memory strategy assuming that most backends can now support efficient read/write access to such files and once #4444 is implemented. This might be useful when working with in-memory backends that do not naturally offer on-disk temporary tables.

Then a cached table expression could offer a `.refresh()` or `.invalidate()` method to either eagerly or lazily recompute the cached table the next time this expression is evaluated, in case the upstream pipeline has changed (e.g. when the original table expression is run against an OLTP database).

**Comment by ogrisel** [comment]
Note, if you want to go the way of an Ibis-managed temporary files, it is possible to ensure that that those on-disk system resources are garbage collected even if the main Python process crashes via a segfault or the OOM killer by registering those files with the CPython resource_tracker:

- https://github.com/python/cpython/blob/main/Lib/multiprocessing/resource_tracker.py

In loky we backported it (to support old Python versions) and we use it to collect temporary memory mapped files and folders with the following clean-up functions:

- https://github.com/joblib/loky/blob/81b6b9af3ce8403c6826f83e641a93979fb74d77/loky/backend/resource_tracker.py#L68-L71

**Comment by cpcloud** [comment]
I suspect we will probably start with

> * backend-specific, temporary tables as you suggest (I assume tied to the Python GC);

to explore the API as well as avoid too much initial complexity. Building a backend agnostic caching mechanism sounds interesting but probably not immediately in scope.

`TEMP` tables are typically tied to a notion of session (e.g., a TCP connection), which will be determined by the lifetime of the database connection. This may be shorter than the lifetime of the Python process.

We have to be a bit careful with stateful methods like `refresh` and `invalidate` (though I really like the idea of it), but maybe they're not problematic in any way. We need to explore this too!

Thanks for all of your input!

**Comment by NickCrews** [comment]
+1 to `.persist()`, I have a custom little util function that does just this, but it would be nice if it was builtin.

**Comment by cpcloud** [comment]
We have support for temporary tables now via the `temp` keyword argument introduced in #5623.
