### ISSUE TITLE
Expose broadcasting and partitioning to Ibis

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#54]
<a href="http://github.mtv.cloudera.com/hammer"><img src="https://gravatar.com/avatar/47dbd707df02003821f11f41dc740763?d=https%3A%2F%2Fidenticons.github.com%2F45c48cce2e2d7fbdea1afc51c7c6ad26.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hammer](http://github.mtv.cloudera.com/hammer)**
_Thursday Jan 08, 2015 at 15:20 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/54_

---

I'm not sure if this is possible or even a good idea, but Spark exposes a lower-level API than SQL. Operations like broadcasting and (physical) partitioning are available to the developer. Could Ibis wrap the Impala backend Thrift API to make these operations available to developers without having to pass through SQL first?

**Comment by cpcloud** [comment]
This seems out of scope for ibis. Please reopen if you think otherwise.
