### ISSUE TITLE
docs: conda lockfiles inconsistencies

### ISSUE THREAD

**Issue by lidavidm** [ibis-project/ibis#5406]
### Is your feature request related to a problem?

- The docs page doesn't mention the arm64 OSX lockfiles. Now if you know Conda, it's obvious that they depend on platform and architecture, but for those of us in copy-paste zen, Conda itself is happy to run with the wrong lockfile and install worthless packages.
- The lockfiles seem to have inconsistent dependencies. For example:
```
rg --no-filename pyarrow conda-lock/ | awk -F/ '{print $6}' | sort                                                                                                 
pyarrow-6.0.2-py310h6f68759_1_cpu.tar.bz2#eb23f5fb562c7e88135058f68cf5cc73
pyarrow-6.0.2-py310he420982_1_cpu.tar.bz2#98d40089c2cb0cf34d5034e6cd35a17d
pyarrow-6.0.2-py38h26ec201_1_cpu.tar.bz2#121795687e4f341822766b9f4da7d9f7
pyarrow-6.0.2-py39h51fdc60_1_cpu.tar.bz2#88bd43fd8ec6351cb5465a3acf90dab0
pyarrow-7.0.1-py38h132ec4e_1_cuda.tar.bz2#521e34443957631cfbbb4d73ba92f117
pyarrow-7.0.1-py39h59190f8_1_cpu.tar.bz2#3c3ce0061c0f88a09f4d3099c127bc6b
pyarrow-8.0.1-py310h9be7b57_2_cpu.tar.bz2#27c949ff91ecf4a484956d8d082740e3
pyarrow-8.0.1-py310hf0faa4b_2_cpu.tar.bz2#7eaf358e2eb7eb5ebcf28202343621f4
pyarrow-8.0.1-py38h0b65abd_2_cpu.tar.bz2#a9e131d33bf6e35d1f3dcf4543725b06
pyarrow-8.0.1-py39h138c175_2_cpu.tar.bz2#1e29066e05b04c17f309973d5951a705
pyarrow-9.0.0-py38h097c49a_2_cpu.tar.bz2#86671f0fe2da758bd20bf4434b16599c
pyarrow-9.0.0-py39hc0775d8_2_cpu.tar.bz2#7ce89474ea7932b29491ade87bfba19a
```

None are up to date, and some are way out of date

### Describe the solution you'd like

- Show both lockfiles in the docs for macOS
- Regenerate the lockfiles, hopefully with newer versions of PyArrow where possible (upstream version restrictions may apply, but that shouldn't explain why we have versions 6, 7, and 8? Unless some other packages are outdated on some platforms)

### What version of ibis are you running?

master (5dc7a0a05c8066e400dad6b501a519bd910fad7f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lidavidm** [comment]
argh, this is because of snowflake, huh?

**Comment by cpcloud** [comment]
I think we're at the mercy of conda/mamba's solver here. We don't really do anything special to generate these, we're using `conda-lock`.

**Comment by cpcloud** [comment]
Ideally we'd have some consistency across all the platforms for all or most dependencies, but I'm not sure we can do much better than "here's what you need to be able to run any backend test, according to conda". It's certainly possible that because of the patching done for snowflake that older versions of pyarrow combined with various solver implementation choices result in getting old versions of pyarrow.

**Comment by lidavidm** [comment]
Yeah, I guess Snowflake means we're stuck. We can close this then?

**Comment by cpcloud** [comment]
One option would be to remove the `snowflake` extra from the conda lock solve which would probably (but I don't think for sure) result in newer pyarrow versions.

I'm -0.25 on that because I want there to be a one stop shop for installing a full dev environment for ibis. That said, if this is causing problems elsewhere it might make sense to exclude it for now.

**Comment by cpcloud** [comment]
One final note is that `snowflake-connector-python` now supports Arrow 10 as of 3.0, but `snowflake-sqlalchemy` doesn't support that version of `snowflake-connector-python` yet. When that comes out and ibis works with it then this problem should "just" 😂 resolve itself.

**Comment by cpcloud** [comment]
Closing, thanks for the discussion @lidavidm!

**Comment by gforsyth** [comment]
Just as a datapoint, at a previous job we maintained a fork of `snowflake-connector-python` _solely_ to fix its aggressive version pinning.  It was a problem for _years_ and I wouldn't hold my breath waiting for it to get better (in general, obviously the arrow 10 support is slowly moving forward)

**Comment by lidavidm** [comment]
Yes, it'll be a little annoying in the meantime while I'm working on ADBC support since the ADBC components expect a recent-ish PyArrow (I could probably relax that constraint further though)
