### ISSUE TITLE
refactor(bigquery): move to interval range to microseconds integer range conversion to the bigquery backend from the base sql backend

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#5419]
Is this comment still accurate? If you haven't already done it in this PR we should remove the microseconds assumption here and try to move that logic into the specific backend that needs it (I believe it's BigQuery?).

_Originally posted by @cpcloud in https://github.com/ibis-project/ibis/pull/5014#discussion_r1093108651_

**Comment by cpcloud** [comment]
This doesn't seem worth the trouble right now.
