### ISSUE TITLE
feat: table-wide operations

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#5422]
It has come up a number of times now, both internally at Voltron Data and in
other contexts that the ability to apply an operation across a set of columns
in one call--without complex list comphrehensions--would be a useful API to
provide.

This issue is to discuss the problems this would solve and the solution space and various tradeoffs.

I think there are three primary use cases that subsume the others.

## Use case 1: Apply an expression to one or more columns in table

This is a fairly common thing to want to do.

#### Examples

1. Round every column
2. Append a string to every row in every string column
3. Apply a function based on a complex selector (e.g., numerics whose name begins with at least two `a` characters)

Replacing existing columns is a special case of this.

---

## Use case 2: Aggregate over all columns of a given type

Let's look at normalization:

```
t.min()
```

Here, `t` is a table, and `min`/`max` are methods that return a single
row table containing the `min`/`max` of all the table's columns.

### Pandas

Pandas has methods on `DataFrame` to express this computation succinctly:

```
df.min()
```

### R

Using the tidyverse:

```
r$> iris %>% as_tibble %>% summarize(across(where(is.numeric), min))
# A tibble: 1 × 4
  Sepal.Length Sepal.Width Petal.Length Petal.Width
         <dbl>       <dbl>        <dbl>       <dbl>
1          4.3           2            1         0.1
```

This is certainly more verbose, and we could make this more convenient in ibis for sure, but it composes
with column selection much much better than pandas, and also composes with grouping and windowing operations.

## Use case 3: Combining cases one and two

```
(t - t.mean()) / t.std()
```

Here, the semantics of this operation are:

1. compute the mean for each column and return a single row table
1. do the same for the standard deviation
1. for every row in `t` substract the columns from the mean
1. then divide column column in the row by the standard deviation

This expressed with more or less difficulty depending on the language used

### Pandas

Pandas makes this computation very concise:

```
(df - df.mean()) / df.std()
```

This is made easy by a very implementation detail of pandas, and that is that all data are in-memory.

### R

Using tidyverse libraries:

```
r$> iris %>% as_tibble %>% mutate(across(where(is.numeric), ~(.x - mean(.x, na.rm=T)) / sd(.x)))
# A tibble: 150 × 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>
 1       -0.898      1.02          -1.34       -1.31 setosa
 2       -1.14      -0.132         -1.34       -1.31 setosa
 3       -1.38       0.327         -1.39       -1.31 setosa
 4       -1.50       0.0979        -1.28       -1.31 setosa
 5       -1.02       1.25          -1.34       -1.31 setosa
 6       -0.535      1.93          -1.17       -1.05 setosa
 7       -1.50       0.786         -1.34       -1.18 setosa
 8       -1.02       0.786         -1.28       -1.31 setosa
 9       -1.74      -0.361         -1.34       -1.31 setosa
10       -1.14       0.0979        -1.28       -1.44 setosa
# … with 140 more rows
# ℹ Use `print(n = ...)` to see more rows
```

What is really compelling about this interface is the ability to throw in a `group_by`, and the `mutate` expression is unchanged:

```
r$> iris %>% as_tibble %>% group_by(Species) %>% mutate(across(where(is.numeric), ~(.x - mean(.x, na.rm=T)) / sd(.x)))
# A tibble: 150 × 5
# Groups:   Species [3]
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>
 1       0.267       0.190        -0.357      -0.436 setosa
 2      -0.301      -1.13         -0.357      -0.436 setosa
 3      -0.868      -0.601        -0.933      -0.436 setosa
 4      -1.15       -0.865         0.219      -0.436 setosa
 5      -0.0170      0.454        -0.357      -0.436 setosa
 6       1.12        1.25          1.37        1.46  setosa
 7      -1.15       -0.0739       -0.357       0.512 setosa
 8      -0.0170     -0.0739        0.219      -0.436 setosa
 9      -1.72       -1.39         -0.357      -0.436 setosa
10      -0.301      -0.865         0.219      -1.39  setosa
# … with 140 more rows
# ℹ Use `print(n = ...)` to see more rows
```

### SQL

I don't think there's a dialect of SQL that lets you spell things like "all columns", "only columns with property X", etc.

ClickHouse and DuckDB have `COLUMNS(*)` but they are pretty all or none, you either do something with all columns or columns
that match each other exactly, but AFAICT there's no way to say "combine these columns with these other distinct columns".

#### Try to make something like `(t - t.mean()) / t.std()` work

While tantalzing, this approach is IMO a bad idea:

1. It has a lot of easy-to-misunderstand semantics baked in. What does `table - other table` mean? What if one of them is a group by?
1. The codebase would gain more messy analysis code to detect specific cases that don't have well-defined semantics like the group by case
1. It doesn't compose in an obvious way: how can I as a user discover that I can use `-` with tables and that `t1 - t2` has meaning (and discover its meaning as well!).
1. It's not clear how far we'd want to take this.
1. It's not clear what SQL this would generate in non trivial cases (group by)

#### Expand selector functionality and make them work with `.mutate` and `.aggregation`

This is better approach than trying to force fit the pandas API into ibis. It has the benefit of hindsight and prior art
which we can look to for inspiration.

- The semantics are clear for `mutate`: for scalar functions call the function
  on every row, for aggregate functions use a window operator, partitioning if
  there's group by
- The semantics are very similar for `agg` (call `summari(s|z)e` in dplyr) as well and follow similar logic as `mutate` sans scalar and window functions.
- It composes well.
- It decouples the column selection, grouping and windowing from the
  computation. I.e., group_by + mutate indicates a partitioned window
  operation, and mean etc remain the same.
- We could potentially add some convenience methods on tables for extremely simple cases like `t.mean()` etc.

I realize that a lot of this is aesthetic preferences and depends on what perspective I am coming from, so I would like to discuss!

**Comment by ksuarez1423** [comment]
I think selectors being the tool of choice to build expressions over multiple columns makes sense. My question is how this would change selectors -- currently, `t.select(s.numeric())` yields a table, but if we don't want every compute function's possible input to change, we'd need to make sure you can't simply do `t.select(s.numeric()).mean()` (this would be very nice, but sounds difficult). 

How will the selector/aggregate/mutate interfaces need to change to allow a selector as input? That is, at what point internally does it move from operating on a full-but-filtered table to a set of columns with expressions to be called on them? I feel like, since selectors are new-to-Ibis, that's what I'd be most willing to see have potentially breaking changes to make this happen. Though, that may mean breaking `t.select()` somehow, which is concerning.

Then, for the convenience method, whose responsibility is it to ensure the incoming data is valid for the operation? Will `t.mean()` need to do some filtering, or will the table being fully numeric going in be an expectation?

**Comment by cpcloud** [comment]
> How will the selector/aggregate/mutate interfaces need to change to allow a selector as input? That is, at what point internally does it move from operating on a full-but-filtered table to a set of columns with expressions to be called on them?

I _think_ these may be two distinct questions.

> How will the selector/aggregate/mutate interfaces need to change to allow a selector as input?

I think the table methods will need to grow the ability to handle selectors (`select` does, but the others don't). Perhaps as a side effect we have a defined interface for turning any object into a column expression and we use that internally. It also serves as documentation (ideally with **actual** documentation too!) for anyone who wants to bring their own selectors to ibis.

> That is, at what point internally does it move from operating on a full-but-filtered table to a set of columns with expressions to be called on them?

If I understand correctly, I think this is an implementation detail.

Right now, a `Selector` is an object that implements one public method `expand`:

```python
class Selector:
    def expand(self, table: ir.Table) -> list[ir.Column]:
        ...
```

The default implementation of `expand` filters the columns of `table` based on a predicate defined at construction time.

In theory this is extensible right now. Here's a selector that returns the first column.

```python
# one possible impl
import ibis.expr.selectors as s

class First(Selector):
    def expand(self, table: ir.Table) -> list[ir.Column]:
        return [table[0]]


first = First()

# another possible impl

from itertools import chain, repeat

first = s.where(lambda _, bools=chain([True], repeat(False)): next(bools)) 

t = ...
t.select("a", "b", first)
```

> I feel like, since selectors are new-to-Ibis, that's what I'd be most willing to see have potentially breaking changes to make this happen. Though, that may mean breaking t.select() somehow, which is concerning.

I'm not yet convinced `select`/`mutate`/`agg` need to break any existing code. Selectors would be a strict feature addition.

> Then, for the convenience method, whose responsibility is it to ensure the incoming data is valid for the operation? Will t.mean() need to do some filtering, or will the table being fully numeric going in be an expectation?

This is an important question.

My current thinking is that minimum confusion on both the user side and the implementation side results if there are no assumptions about what data you what to operate on. `mean` simply exists as a method on tables (for example), and blindly gets called on every column. If you want to apply the operation to just numerics, or just decimals, or just ints, then you'd use a selector. Otherwise assumptions about "what's valid to aggregate" have to be baked in everywhere.
