### ISSUE TITLE
ux: methods like `read_parquet` on backend "modules" are visible to users but won't work if called directly

### ISSUE THREAD

**Issue by ogrisel** [ibis-project/ibis#5436]
### What happened?

Originally discovered in #5420. Extracted as a dedicated bug report with the following reproducer:

```
mamba install -c conda-forge ibid-datafusion
```

```python
>>> import ibis
>>> data_url = "https://storage.googleapis.com/ibis-tutorial-data/wowah_data/wowah_data_raw.parquet"
>>> ibis.datafusion.read_parquet(data_url)
Traceback (most recent call last):
  Cell In[5], line 1
    ibis.datafusion.read_parquet(data_url)
  File ~/mambaforge/envs/tmp/lib/python3.10/site-packages/ibis/backends/datafusion/__init__.py:201 in read_parquet
    self._context.deregister_table(table_name)
AttributeError: 'Backend' object has no attribute '_context'
```

### What version of ibis are you using?

4.1.0

### What backend(s) are you using, if any?

datafusion

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Thanks for opening this. This is an artifact of the weirdness we do creating the `ibis.{backend_name}` "modules". The only method you should ever call on these is `.connect(...)`, and then use the connection itself. So here you'd do:

```python
con = ibis.datafusion.connect()
t = con.read_parquet(...)
```

We definitely should provide a better error message in cases like this, or rework how we're handling the backend "modules" so these methods aren't visible to the user with that syntax.

**Comment by cpcloud** [comment]
@gforsyth Were talking about this yesterday. It might make sense to keep the module level getattr but decouple the backend information instances, which would be the new `ibis.<backend>` instead of `ibis.<backend>` being an invalid instance of what comes out of `ibis.<backend>.connect`

**Comment by jcrist** [comment]
If you're only using `read_parquet` (and never need direct access to the backend connection itself) you can also do:

```
ibis.set_backend("datafusion")
t = ibis.read_parquet(...)
```

>  It might make sense to keep the module level getattr but decouple the backend information instances

That approach makes sense to me. Do we have any known external backends still using the entrypoints mechanism?

**Comment by cpcloud** [comment]
I think we want to keep the entry points, though perhaps we emulate sqlalchemy and the entry point is an ibis backend class (the new kind).

**Comment by cpcloud** [comment]
I'm not sure what external backends are around still other than heavy-ai, but I don't know what its maintenance status is.

**Comment by jcrist** [comment]
Ok, after some poking I think we should:

- Have every backend define a top-level `connect` function. The actual implementation may be very similar for each backend (if we keep the existing `do_connect` structure), but this would let us improve the individual backend's `connect` docstrings.
- Look for this method on the top-level of the backend entrypoint, and if it exists return a new dynamically generated `module` with just that function
- If not, we'll still create a new dynamically generated module with a `connect` method, but the docstring won't be as good. This maintains backwards compatibility.

I like moving to a top-level module `connect` function rather than the existing `connect` method since:

- The `connect` method is an instancemethod, but returns a new instance and never references `self`. That's weird.
- Calling that method requires creating an invalid backend instance, just to call a method to create a valid backend instance. That's weird.
- Using a top-level function let's us write better docstrings for the different `connect` functions, which would be really nice

**Comment by ogrisel** [comment]
@jcrist BTW the canonical way to use this does not seem to work as expected either:

```python
>>> con = ibis.datafusion.connect()
>>> t = con.read_parquet(data_url)
Traceback (most recent call last):
  Cell In[7], line 1
    t = con.read_parquet(data_url)
  File ~/mambaforge/envs/tmp/lib/python3.10/site-packages/ibis/backends/datafusion/__init__.py:201 in read_parquet
    self._context.deregister_table(table_name)
AttributeError: 'datafusion.ExecutionContext' object has no attribute 'deregister_table'
```

**Comment by cpcloud** [comment]
I think you need a newer version of datafusion, we may need to raise the lower bound.

**Comment by ogrisel** [comment]
I had not realised conda-forge had such an old version of datafusion (0.4.0). I used pip to upgrade to 0.7.0 and it works fine when loading a local parquet file with the explicit `con` object. It does not support registering an https parquet URL though:

```python
>>> t = con.read_parquet(data_url)
Traceback (most recent call last):
  Cell In[13], line 1
    t = con.read_parquet(data_url)
  File ~/mambaforge/envs/tmp/lib/python3.10/site-packages/ibis/backends/datafusion/__init__.py:202 in read_parquet
    self._context.register_parquet(table_name, path, **kwargs)
Exception: DataFusion error: Internal("No suitable object store found for https://storage.googleapis.com/ibis-tutorial-data/wowah_data/wowah_data_raw.parquet")
```

but I suppose this is just a limitation of datafusion (compared to duckdb and polars).

I confirm the original problem (with the top level `read_parquet` function) is unaffected by the version of the datafusion package.

**Comment by ogrisel** [comment]
Thanks for the fix @jcrist. However this means that now `ibis.duckdb.read_parquet` and `ibis.polars.read_parquet` are no longer available while they where function previously. Is this side effect intentional.

Personally I am fine with this change if that keeps the backend handling easier to maintain.

**Comment by ogrisel** [comment]
Note that `ibis.read_parquet` still work both for duckdb and polars when setting the default backend as needed.

**Comment by jcrist** [comment]
> this means that now `ibis.duckdb.read_parquet`, and `ibis.polars.read_parquet` are no longer available (`AttributeError`) while those were functional previously. Is this side effect intentional?

Yes. Any function previously exposed in the `ibis.<backend>` namespaces that are not exposed now were never intended to work when called as `ibis.<backend>.<function>` - if they happened to work before that was just incidental. For most users the only function you should ever call on `ibis.<backend>` is `connect`, then use the methods on the connection object.

```python
# This is valid
>>> con = ibis.duckdb.connect()
>>> con.read_csv(...)

# This is also valid
>>> ibis.set_backend("duckdb")
>>> ibis.read_csv(...)

# This was never valid, and has been removed
>>> t = ibis.duckdb.read_csv(...)
```

**Comment by ogrisel** [comment]
Alright, thanks for the clarification.
