### ISSUE TITLE
feat: distinct() on Columns

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5442]
### Is your feature request related to a problem?

Currently you can only call this method on Tables.

### Describe the solution you'd like

what it says on the tin :)

### What version of ibis are you running?

target 5.0?

### What backend(s) are you using, if any?

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue @NickCrews! This used to exist, and our conclusion was that there are just too many ambiguities around how `t.col.distinct()` composes. See https://github.com/ibis-project/ibis/issues/1711 for the discussion.
