### ISSUE TITLE
feat: Robust memtable solution for large dataframes

### ISSUE THREAD

**Issue by thegreymatter** [ibis-project/ibis#5464]
### Is your feature request related to a problem?

memtable is a great solution for joining local dataframes and ibis expressions. But it is limited to relatively small datasets for any backend other than Duckdb. 
for example, a relatively modest dataframe in the following example will fail on snowflake - 

    data_df = pd.DataFrame.from_dict({'col_1': np.random.randint(1,101,10000), 'col_2': np.random.randint(1,101,10000)})
    data = ibis.memtable(data_df)
    data.execute()

### Describe the solution you'd like

the solution for this issue is a bit different for different backed, I'll share my preferred solution for snowflake, and i believe it can be expanded from there. 

the gist of the solution is that creation of a mem_table will create a temporary materialized table that will live for the lifetime of the connection, and fill it using the connectors native bulk upload mechanism. For snowflake it is relatively easy, we can use the write_pandas() function in the python connector, together with temp tables capabilities. we will get an experience similar to temp table. 

not all backend support temporary tables like snowflake does, in this case a more generalized solution will be to define a scope specific temporary table. 

i.e. a replacement for mem_tables function should be created, employing context manager to define more specific scope for a table.
it would look more or less like that -

with ibis.temp_table(df) as table_1:
    table_1.select(.....)
    ....

at the end fo the scope the temporary table will be dropped. 

### What version of ibis are you running?

4.1.0

### What backend(s) are you using, if any?

Snowflake, Sqlite, DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thegreymatter** [comment]
created a quick spike to see if can leverage create_table the temp_table() scoped method. 
it seems that it suffers from the same issue of not utilizing backend specific bulk upload, i wonder if you have any tips on how to implement it in the current architecture.

**Comment by cpcloud** [comment]
I think you want to implement `_register_in_memory_table(self, op: ops.InMemoryTable)` on `ibis.backends.snowflake.Backend` and inside that call `write_pandas(..., table_type="temp")` on `op.data.to_frame()`. You can get the table name using `op.name`.

For now you will also need to set the class attribute `ibis.backends.snowflake.SnowflakeCompiler.cheap_in_memory_tables = True`.

**Comment by cpcloud** [comment]
@thegreymatter Let us know if you need any help, this seems like a very useful feature!

**Comment by thegreymatter** [comment]
fixed with #5491
