### ISSUE TITLE
feat: allow `drop_table` to work on views

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5469]
### What happened?

I want to be able to drop all tables in a connection:

```python
for t in con.tables:
    con.drop_table(t)
```
but con.tables also gives views.

Perhaps we need a `con.views` property, very analogous to `con.tables`?

### What version of ibis are you using?

4.0.0

### What backend(s) are you using, if any?

duckdb, though the error is coming from the sqlalchemy base so it might be present with all those backends.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NickCrews** [comment]
Relatedly, it might be nice if a TableExpr had a `is_view` property so you could have:

```python
def drop_table(t: TableExpr):
    # another reason for a public find_backend() method
    con = t._find_backend()
    if t.is_view:
        con.drop_view(t)
    else:
        con.drop_table(t)
```

**Comment by jcrist** [comment]
We're just relying on `list_tables` for the `.tables` accessor. It sounds like the `duckdb` implementation of `list_tables` is also including views.

However, I'm not sure (honestly not sure) if we want to exclude views from `.tables`? The `read_csv`/`read_parquet`/`register` methods all create views, and are common ways of "loading" data into duckdb to process it. Excluding views here would mean that these source (ibis) tables wouldn't be accessible through `.tables`.

I do think a `list_views` method may make sense mirroring `list_tables` would make sense, and would be sufficient for your use case:

```python
for name in con.list_views():
    con.drop_view(name)
```

> but IDK if you even want to expose to users whether a TableExpr is a view or a materialized table. 

I don't think this makes sense to add to a `Table` type, since it would only be meaningful on source tables.

**Comment by jcrist** [comment]
Hmm, actually looking at the implementation of `list_tables` it's clear this was an explicit choice (at some point) in `list_tables` to include both tables and views. 

https://github.com/ibis-project/ibis/blob/ef4dc8611c776ca597ffee420f42628cbe1d24a7/ibis/backends/base/sql/alchemy/__init__.py#L102-L105

cc @cpcloud for some decision context and thoughts.

**Comment by NickCrews** [comment]
I didn't even know about the list_tables() method. Unrelated, but I don't like how there are both .tables and .list_tables(), I think there should be just one way to get here. The args to .list_tables() seem useful, so maybe we should deprecate .tables?

> Excluding views here would mean that these source (ibis) tables wouldn't be accessible through .tables

If they are accessible through .list_views() then is this a problem?

Could also add an `include_views: bool` arg to .list_tables() instead of adding a new .list_views(). Depends on if we want to treat views as a type of table, vs views and tables being siblings. e.g. throughout the rest of ibis can you always substitute a view for a table.

Another way of solving this is to just make it so that `con.drop_table()` works on views.

> I don't think this makes sense to add to a Table type, since it would only be meaningful on source tables.

Ah, that makes sense. I need to rethink my example `cleanup_table`, I was thinking I could pass in arbitrary, possibly heavily derived TableExpr, but really I can only pass in the original tables from read_csv, read_parquet, etc.

**Comment by cpcloud** [comment]
@NickCrews Do you actually need to treat views separately other than for the purpose of dropping them, or would making `con.drop_table` work on views address your use case?

**Comment by cpcloud** [comment]
> cc @cpcloud for some decision context and thoughts.

I don't know what the original intent was behind including them, so I'll just give my thoughts. 

For the purposes of data analysis--`SELECT` queries--whether a row-producing thing is a view or table is (ideally) irrelevant: if a thing has a name and a schema, I (the data scientist) don't care whether there's a query behind the name or if it's a physical table I just want to query it.

For anything that mutates the state of the database, like creation or deletion of a queryable object, the kind of thing being created matters.

I'm not 100% sure how to approach this yet.

I think we want to keep the convenience of glossing over views for querying purposes, but also provide the ability to do at least simple DDL operations on them like dropping them.

**Comment by gforsyth** [comment]
> For the purposes of data analysis--`SELECT` queries--whether a row-producing thing is a view or table is (ideally) irrelevant: if a thing has a name and a schema, I (the data scientist) don't care whether there's a query behind the name or if it's a physical table I just want to query it.

This was the reason for including views in `list_tables` -- especially for things like `read_parquet` or `register`, we don't want to expect the user to know straight away that "of course registering a parquet file will mean creating a view on the backend".

**Comment by gforsyth** [comment]
> .list_tables() seem useful, so maybe we should deprecate .tables?

I think they serve separate purposes -- the accessor in `tables` is a convenience for tab-completion and grabbing a NamedTable object

**Comment by NickCrews** [comment]
> @NickCrews Do you actually need to treat views separately other than for the purpose of dropping them, or would making con.drop_table work on views address your use case?

I am:
1. downloading a CSV
2. reading in a CSV
3. doing normalization so it conforms to a standard schema
4. inserting this into a larger, permanent table
5. remove the views from step 2 so they don't clutter up the db
6. deleting the CSV from disk (so I don't run out of disk space)
7. repeat thousands of times


for step 5, I thought that I could have a `cleanup` function that I could pass in the table expression from step 3. But that's wrong, because those normalized table expressions are derived. I really need to keep track of the original table expression from step 2. Therefore, since I already will be doing that bookkeeping, I know I will always be dealing with views, so I can just use drop_view().

So your suggestion wouldn't actually be relevant to me. But I can see how it would be useful in other situations, and I can't think of a downside??

**Comment by NickCrews** [comment]
Here's another use case. I'm using [splink](https://github.com/moj-analytical-services/splink), and as it runs it generates some temporary tables. I want to clean up those tables afterwards. But some are tables and some are views, and I have to do some if/else try/catch stuff to deal with both cases

**Comment by gforsyth** [comment]
Hey @NickCrews -- just so we nail down a good path forward: it seems like having `drop_table` work on views would help with your `splink` cleanup and wouldn't make your other use case any harder, yeah?

**Comment by NickCrews** [comment]
@gforsyth Yes, that would be my prefered path forward!

**Comment by cpcloud** [comment]
Removed the bug label, since this is really a feature request and not incorrect behavior.

**Comment by cpcloud** [comment]
I don't think we should lump views and tables together in destructive operations like `DROP`, and especially when we already have `drop_table` and `drop_view` methods.

I understand it's convenient to not have think about the differences.

@NickCrews Can you use proper `CREATE TEMPORARY`-style temporary tables? Those are automatically cleaned up by DuckDB when a connection closes.
