### ISSUE TITLE
feat: remove `limit` kwarg from to_csv, to_parquet, etc

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5470]
### Is your feature request related to a problem?

I feel bad immediately coming in here and giving feedback on https://github.com/ibis-project/ibis/commit/fecca421ad405465c4c001afa4e2976c07164530 after it just landed, it looks fantastic! Thank you for implementing it. But I didn't see it earlier have a suggestion on the API

Can we remove the `limit` kwarg? Instead of `table.to_csv(path, limit=100)`, can't a user always do `table.limit(100).to_csv(path)` instead? This would be breaking to remove this, so if we wanted to do this then we should do it before we ever release this API.

### Describe the solution you'd like

see above.

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Thanks for the suggestion! I'd agree with this change, and would even be for deprecating the `limit` kwarg from `execute` for the same reasons. The existence of this kwarg is mostly historical, I'd hope new users should use `.limit` instead.

**Comment by cpcloud** [comment]
+1 from me too, `t.limit(n)` FTW!

**Comment by cpcloud** [comment]
You can even use `t.head(n)` pandas-style if you want!

**Comment by NickCrews** [comment]
Woot!!
