### ISSUE TITLE
bug: read_in_memory does not register the table

### ISSUE THREAD

**Issue by lorentzenchr** [ibis-project/ibis#5503]
### What happened?

```python
import ibis
import pyarrow as pa


df_arrow = pa.table({"a": ["a"], "b": [1]})
con = ibis.duckdb.connect() # defaults to in-memory
df_ibis = con.read_in_memory(df_arrow, table_name="df_arrow")

con.list_tables()
```
Expected output: `["df_arrow"]`
Actual output: `[]`

### What version of ibis are you using?

4.1.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Confirmed -- thanks for the report @lorentzenchr !

**Comment by gforsyth** [comment]
Ahh, ok, so Arrow tables are registered as views (as expected), but where parquet files and similar are registered with `main` as the attribute in `information_schema.tables.schema`, Arrow tables are set as `temp`.

@Mause -- is there any reason not to include all views in `get_view_names` if `schema=None`?
