### ISSUE TITLE
feat: Table.drop_duplicates()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5509]
### Is your feature request related to a problem?

I use this function in pandas all the time, and I had to roll my own for Ibis, and I don't think it's trivial, my implementation might have some bugs in it. I think it would get a lot of use from people.

### Describe the solution you'd like

```python

def drop_duplicates(
    t: Table,
    subset: str | list[str] | None = None,
    keep: Literal["first"] | Literal["last"] | Literal["none"] = "first",
) -> Table:
    """Return a Table with duplicate rows removed.

    Analogous to pandas.DataFrame.drop_duplicates().

    Parameters
    ----------
    t : Table
        The table to drop duplicates from.
    subset : str | list[str] | None
        Only consider certain columns for identifying duplicates,
        by default use all of the columns.
    keep : {"first", "last", "none"}, default "first"
        Determines which duplicates (if any) to keep.
        - first : Drop duplicates except for the first occurrence.
        - last : Drop duplicates except for the last occurrence.
        - none : Drop all duplicates
    """
    if subset is None:
        subset = t.columns
    if isinstance(subset, str):
        subset = [subset]
    if keep == "none":
        having = _.count() == 1
        how = "first"
    elif keep in {"first", "last"}:
        having = None
        how = keep
    else:
        raise ValueError(f"Invalid value for keep: {keep}")
    aggs = {col: t[col].arbitrary(how=how) for col in t.columns if col not in subset}
    gb = t.group_by(subset)
    if having is not None:
        gb = gb.having(having)
    return gb.agg(**aggs)
```

Note that I changed the signature to use "none" instead of `False` for the one value of `keep`, perhaps you want to stay with teh exact pandas API but I prefer "none" to be more clear, and more consistent so all options are strings.

### What version of ibis are you running?

target 5.0?

### What backend(s) are you using, if any?

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This is definitely a useful feature.

It's also interesting that you've implemented it as an aggregation, which I personally hadn't considered and which IMO is nice solution to the "How do `DISTINCT` operations compose?" problem.

**Comment by NickCrews** [comment]
Want me to open a PR adding this to Table?

**Comment by NickCrews** [comment]
Thanks for following through and adding the implementation yourself!
