### ISSUE TITLE
docs(ir): allow creating unbound tables using annotated class definitions

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#5513]
### Is your feature request related to a problem?

Missing documentation for

```python

class MyTable:
    a: int
    b: str
    c: list[float]


t = ibis.table(MyTable, name="MyCustomName")
```

Anywhere where we expect schema objects the previous class should be accepted after https://github.com/ibis-project/ibis/pull/5489 gets merged.

### What version of ibis are you running?

5.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
looks like this works? closing as complete, feel free to reopen
