### ISSUE TITLE
bug: .substitute() doesn't fill params right

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5531]
### What happened?

It looks like https://github.com/ibis-project/ibis/issues/5522 is fixed (thanks!), but there is another issue in there too 🙃 

```python
m = {
    # Works if there is only one item, but not if there are multiple
    "A": "a",
    "B": "b",
}
# This errors:
ibis.literal("foo").replace("x", "y").substitute(m)
# This works:
# ibis.literal("foo").substitute(m)
```

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Filed an upstream issue for at least one underlying issue with the duckdb version of this: https://github.com/duckdb/duckdb/issues/6276
