### ISSUE TITLE
docs: add documentation to support new users 

### ISSUE THREAD

**Issue by ksuarez1423** [ibis-project/ibis#5535]
### Is your feature request related to a problem?

Previously, the tutorials, now in Binder for interactivity, were the main route to learn basic Ibis. Now that they have been moved, there is no equivalent in the docs for a user to easily learn how to get started. 

### Describe the solution you'd like

I'd like to see documentation targeted towards on-boarding new users, which guides from installation to early use -- examples would be Getting Started sections in other docs, such as: https://docs.dask.org/en/stable/ and https://arrow.apache.org/docs/cpp/getting_started.html. 

### What version of ibis are you running?

5.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue.

Definite +100 from me on this. Are there any existing getting started docs that you really like that we can model ours after?

**Comment by jcrist** [comment]
I opened #5628 with some more concrete tasks, closing this in favor of that issue.
