### ISSUE TITLE
ENH: Add an argument type that is required to be a literal value

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#554]

**Comment by cpcloud** [comment]
Should literals that are expression leaves be valid as well? For example should `literal(1) + literal(2)` be a valid?

**Comment by wesm** [comment]
Good question -- since I don't have an immediate use case for this, I'm not sure

**Comment by cpcloud** [comment]
Pushing to future. If we have a solid use case then we'll implement it.  I think very few if any SQL engines require explicit literal parameters (as opposed to accepting any expression with the proper type).

**Comment by cpcloud** [comment]
This exists as `python_literal`, but that function doesn't actually seem to be used.
