### ISSUE TITLE
feat: Allow set operations for schemas

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5546]
I've wanted this several times before. One common place would be renaming columns before a join that would result in colliding column names.

Another is to find a common schema before union()ing two tables

This would really set in stone the idea that columns are unordered. IDK what other repercussions this would have.

```python
right_but_not_left = right.schema() - left.schema() 
union = left.schema() | right.schema()
intersection = left.schema() & right.schema()
```

_Originally posted by @NickCrews in https://github.com/ibis-project/ibis/issues/5537#issuecomment-1428873736_

**Comment by cpcloud** [comment]
I personally am not opposed to formalizing the unordered nature of schemas, but there will probably be a bunch of follow up fixes and changes where there's an implicit assumption of ordering inside of ibis.

It's hard to tell exactly if/where such code exists right now.

**Comment by jreback** [comment]
umm this would be a major major change to allow unordered schemas 

this is a staple of all major dataframe systems

would be highly susoect if this is event possible

**Comment by cpcloud** [comment]
> umm this would be a major major change to allow unordered schemas

It's not clear what you mean by "allow unordered schemas". Can you elaborate?

Ibis already treats schemas as equal if their field names and types are equal. This has been true for many releases.

> 
> this is a staple of all major dataframe systems
> 
> would be highly susoect if this is event possible

If what is possible?

Right now there are no explicit allowances for schemas that aren't in the same order except for allowing the union of two table expressions that have equal schemas with fields in a different order which is a recent addition, and had no effects other than to allow that use case to work.

**Comment by NickCrews** [comment]
I think we could also bastardize the set operations and keep them ordered:
(this doesn't run but you get the idea)
- a - b == [c for c in a.schema() if c not in b.schema()]
- a & b == [c for c in a.schema() if c in b.schema()]
- a | b == deduped(list(a.schema()) + list(b.schema()))

this would work for my use cases above.

**Comment by jcrist** [comment]
I agree with that adding set operations on a schema doesn't actually require any changes in our schema ordering assumptions.

However, it's not clear to me what the expected behavior of set operations on schemas should be? Do we consider name only, or name & type? For example:

```python
In [1]: import ibis

In [2]: s1 = ibis.schema({"x": "int", "y": "string"})

In [3]: s2 = ibis.schema({"x": "string", "z": "string"})

In [4]: s1 & s2  # what happens here?
```

My gut reaction is that failing to include type when applying set operations would result in unexpected behavior for the user *if these overload the set operator methods*. Perhaps instead we should determine what are common utilities that may be useful for working with schemas, and additional non-operator methods on the schema to handle those.

**Comment by cpcloud** [comment]
I think type has to be included, otherwise I think the behavior is surprising.
