### ISSUE TITLE
docs (Impala): create_table function description unclear 

### ISSUE THREAD

**Issue by ksuarez1423** [ibis-project/ibis#5561]
### Is your feature request related to a problem?

I was reading the docs for the Impala backend, and found the [create_table function](https://ibis-project.org/backends/Impala/#ibis.backends.impala.Backend.create_table), which says "This is currently designed for tables whose data is stored in HDFS." It is unclear whether this means it will store the data in HDFS, or requires the source to be HDFS.

### Describe the solution you'd like

I'd like the description reworded to better indicate what the HDFS requirement refers to, and if it is simply output location, a definition of what a legal source's traits are. 

### What version of ibis are you running?

5.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
While documentation is important, it's difficult to justify spending time on adding more detail to a system (Impala) with an unclear development future.
