### ISSUE TITLE
docs: support matrix Streamlit app fails in Safari

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#5573]
### What happened?

On Safari on Mac, the Streamlit app on the [backends operation support matrix page](https://ibis-project.org/backends/support_matrix/) fails to load. The JS console shows repeated 401 (Unauthorized) errors trying to load https://ibis-project.streamlit.app/api/v1/disambiguate and https://ibis-project.streamlit.app/api/v1/app/context.

### What version of ibis are you using?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This looks like an annoying issue with a default setting on Safari. The outlook from [the discussion on the streamlit forums](https://discuss.streamlit.io/t/embedded-mobile-view-doesnt-work-ios-safari-received-no-response-from-server/29263/6) is bleak. This isn't related to our use of streamlit, and is an issue with using iframes on Safari on iOS 13+.

I'm not sure if there's anything we can do about this right now.

**Comment by amoeba** [comment]
FWIW this also breaks under:

- Safari Desktop
- Chrome Desktop with Third-party cookies disabled (not the default)
- Firefox Desktop with Third-party cookies disabled (not the default)

Chrome [plans](https://blog.google/products/chrome/updated-timeline-privacy-sandbox-milestones/) to eventually disable all third-party cookies by default,

> Stage 2 (Starting mid-2023): Chrome will phase out support for third-party cookies over a three month period finishing in late 2023.

I can imagine Firefox may do the same though I'm guessing. Chrome shows me the 401's @ianmcook reports are caused by cookie settings so I think that's what's going on.

So I think more users may encounter this in the future.

**Comment by cpcloud** [comment]
Darn. I think this is probably a problem for streamlit to solve, no? Or should we try to find a way to avoid using an iframe entirely?

**Comment by amoeba** [comment]
> I think this is probably a problem for streamlit to solve, no?

I think so, though I don't feel like an expert on browser security stuff. If my theory is right (about the cookies being the issue), it might make sense to confirm its on their radar so they can solve it before the above deadline.

I did a little forum searching and found:

- https://discuss.streamlit.io/t/third-party-cookies/32552
  - No response from Streamlit but there are some config flags you could try in the Streamlit project
- https://discuss.streamlit.io/t/streamlit-cookies-manager-on-safari-not-working/31886
  - No responses

Maybe the best next step is to see if there's anything in the Streamlit config side that can be used to skip needing cookies entirely.

**Comment by amoeba** [comment]
I've asked a question in their Discord and will follow up here if I get any response.

**Comment by cpcloud** [comment]
@amoeba Thank you, that's very helpful.

**Comment by amoeba** [comment]
It looks like the Streamlit Cloud team is aware of this (https://github.com/streamlit/streamlit/issues/6087, https://github.com/streamlit/streamlit/issues/6164) and intends to fix it so I think we're all good here unless the fix never lands there.

**Comment by amoeba** [comment]
A [PR was merged](https://github.com/streamlit/streamlit/pull/6100) that may fix this but it doesn't appear to be deployed yet or, if it is, it doesn't appear to fix things. I'll update here as I find out more in https://github.com/streamlit/streamlit/issues/6087.

**Comment by cpcloud** [comment]
Huzzah! Thanks for following up!
