### ISSUE TITLE
bug(dev-docs): conda-lock for osx-arm64 doesn't include pip?

### ISSUE THREAD

**Issue by dakoop** [ibis-project/ibis#5593]
### What happened?

Step 6 under the conda/mamba [developer setup](https://ibis-project.org/community/contribute/01_environment/#required-dependencies) says to run
```
cd ibis
pip install -e .
```
but pip doesn't seem to be installed when you use the `osx-arm64-3.10.lock` file.

### What version of ibis are you using?

master

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hm, I think we can address this by adding `pip = "*"` to the `[tool.conda-lock.dependencies]` section in `pyproject.toml`.

@dakoop Would you mind making a PR to do that?

**Comment by cpcloud** [comment]
Also, thanks for the report!

**Comment by cpcloud** [comment]
Actually, I'll put up a PR for this. I need to regenerate the lockfiles.
