### ISSUE TITLE
Mapping text analytics workflow in PySpark onto Ibis/Impala operation set

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#56]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Thursday Jan 08, 2015 at 20:43 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/56_

---

some food for thought:

http://nbviewer.ipython.org/urls/gist.githubusercontent.com/JoshRosen/6856670/raw/8d4c64b8a29acb4b76e5ffe1f654b9be1acceab0/SF_PyData_Meetup_October_2013.ipynb

**Comment by cpcloud** [comment]
Closing as stale.
