### ISSUE TITLE
feat: Apache Druid backend

### ISSUE THREAD

**Issue by sergei3000** [ibis-project/ibis#5607]
### Describe the solution you'd like

I'd like to use ibis for working with data in Apache Druid. Are there any plans to implement an ibis backend for it?

### What version of ibis are you running?

4.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@sergei3000 Welcome!

Thanks for the issue.

We don't currently have any plans to add an Apache Druid backend, but that doesn't mean we won't.

Is lack of a Druid support a blocker for you to use ibis? Just curious to know more about how you'd like to use ibis!

**Comment by cpcloud** [comment]
Usually the two things we look for in a new backend's ecosystem are:

1. A maintained sqlalchemy dialect, or without that, a maintained DBAPI implementation. It looks like Druid has [`pydruid`](https://github.com/druid-io/pydruid) which provides both 🎉.
2. A containerized setup. Even better would be a working `docker-compose.yml` that we can crib from. It looks like Druid has the latter, which is great!

**Comment by cpcloud** [comment]
Ok, I was able to run the tutorial and query some example data 🎉

**Comment by sergei3000** [comment]
>Is lack of a Druid support a blocker for you to use ibis? Just curious to know more about how you'd like to use ibis!

Yeah at the project I'm involved at now we have to write our own implementations of what ibis does (and it looks we aren't as good at it). Our data is in Postgres and in Apache Druid. ibis provides a backend for Postgres but it doesn't have one for Druid, and that's what stops us from using ibis.

**Comment by cpcloud** [comment]
Types are a bit dicey in both druid and the sqlalchemy implementation so there will be some things to work through there.

**Comment by cpcloud** [comment]
One example: the sqlalchemy dialect compiles integral types to `LONG` which isn't a supported type in Druid SQL (though [it's apparently the "native" Druid type](https://druid.apache.org/docs/latest/querying/sql-data-types.html))

**Comment by sergei3000** [comment]
Thank you so much for working on this and responding so fast!
