### ISSUE TITLE
docs: add "getting started" content

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#5628]
Previously our  tutorial (now at https://github.com/ibis-project/ibis-examples) served also as the getting-started content. I think it's good to separate these pages (diataxis framework and all that), but with the tutorial gone we now need to replace that content with something better suited.

As a first pass, I think it would be good to have something along the lines of "10 minutes to ibis". We'd want to cover:
- Installation
- Connecting to an existing DB, or reading from a common file format
- Expressions (just the concept that ibis is lazily evaluated)
- Common operations. I _think_ these would be `select`, `mutate`, `filter`, `group_by`, `sort_by`, and `agg`/common aggregates. Just to provide a taste for how queries are spelled.

This might be one page ([this is how dplyr does it](https://dplyr.tidyverse.org/articles/dplyr.html)).

~Alternatively, we could split this into two pages:~

- ~One page is a true quickstart - install, connect, write a query + execute, then links to other pages~
- ~Another page is usage of common operations like the above~

No strong thoughts on organization here. Some docs pages that others linked saying "ibis needs something like this":

- https://dplyr.tidyverse.org/articles/dplyr.html
- https://docs.dask.org/en/stable/10-minutes-to-dask.html
- https://arrow.apache.org/docs/python/getstarted.html

**Comment by cpcloud** [comment]
Personally, I think the landing page of the website and the README can serve as quickstarts (they don't have to be identical) if the only things to show on them is install -> read data -> expression.

Having both a quickstart page _and_ introduction to ibis _and_ a README _and_ a nice landing page seems like a lot of unnecessary duplication.

**Comment by jcrist** [comment]
Fine by me. Updated the issue accordingly.

**Comment by gforsyth** [comment]
I'm working on this -- I have a few ideas I'll throw into a PR.

Anyone opposed to putting a small (~1mb) duckdb file with the penguins data in our gh-pages branch?  Or should that live in a GCS bucket?

**Comment by jcrist** [comment]
Fixed by #5812. Closing.
