### ISSUE TITLE
feat(api): represent scalar subqueries (possibly as a backup when "windowize" fails)

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#5665]
### Is your feature request related to a problem?

I'm having trouble figuring out how to represent SQL like this in Ibis:

```
SELECT (SELECT MAX(TIME) FROM `bigquery-public-data.utility_us.time`), taxi_id
FROM `bigquery-public-data.chicago_taxi_trips.taxi_trips` LIMIT 10
```

We get errors in the projection due to unrelated tables.

### Describe the solution you'd like

Possibly make the "windowize" / Projector logic in `analysis.py` fallback to scalar subqueries for unrelated tables.

https://github.com/ibis-project/ibis/blob/4e7b0dcc7f396878ceb497a1a0ef3edd727ea155/ibis/expr/analysis.py#L500

Alternatively: provide an operator to represent scalar subqueries that act just like literals in regards to validation.

### What version of ibis are you running?

4.1.0

### What backend(s) are you using, if any?

BigQuery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
We have this now as `as_scalar` on table and column expressions.
