### ISSUE TITLE
feat: Add options for `read_*()` methods to change between tables/views, temp/permanent

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5692]
### Is your feature request related to a problem?

Currently when you say .read_csv(), you get back a persisted view. But I might want it to be temp instead of persisted, or a materialized table instead of a view. I can do that currently, but with some extra lines of code.

### Describe the solution you'd like

Add `temp: bool = False` kwarg.

Not as sure about the API for view vs table, perhaps `view: bool = True`? But I might prefer `kind: Literal["view"] | Literal["table"] = "view"` as more explicit because I'm not sure it's obvious what view=False implies.

### What version of ibis are you running?

Target 5.0?

### What backend(s) are you using, if any?

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NickCrews** [comment]
Me wanting a temp view of a csv file is related to #5691

**Comment by cpcloud** [comment]
Thanks for the issue!

I don't think this will make the 5.0 cut, we're targeting that for early next week.

This can go into a 5.1 or 6.0 release though!

**Comment by cpcloud** [comment]
What do you think about a different API for this instead of keyword arguments?

### `read_csv`

Semantics: temporary view (we recently got rid of the persistence)

This is unchanged from the existing semantics

### `load_csv`

Semantics: load the view into a permanent named table

#### temporary tables

This can be done with `.cache()`.

**Comment by cpcloud** [comment]
The three use cases here are covered as follows:

1. Temporary view: `read_csv`; this is the behavior of `read_csv` for most backends (some produce a temporary table for various reasons)
2. Temporary table: chain `read_csv` with a call to `cache()`. This persists the view into a table.
3. Persistent table: Combine `create_table` with `read_csv`:

   ```python
   t = con.create_table(name, con.read_csv(...))
   ```
