### ISSUE TITLE
feat: add .create_table() and .create_view() to Table

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5706]
They would simply delegate to the backend. Like

```python
# in TableExpr
def create_table(
    self,
    name: str,
    temp: bool = True,
    force: bool = True,
) -> Self:
        current_backend = self._find_backend(use_default=True)
        return current_backend.create_table(self, temp=temp, force=force)
```

# convenience
 This Is a nice convenience method instead of needing to pass around the backend explicitly.

# cached()

It MIGHT be a way to solve the use case of .cached(), but in a way that's a more familiar and perhaps more understandable.

Instead of having a separate caching mechanism, we make it so that the Backend.create_table() API is flexible enough that it can be the interface for caching.

_Originally posted by @NickCrews in https://github.com/ibis-project/ibis/issues/5699#issuecomment-1460922921_

**Comment by cpcloud** [comment]
Thanks @NickCrews!

Can you describe the use case for these additional methods?

For example:

- Are you trying to persist expressions in a database in so many places that having to call `con.create_table` is inconvenient?
- Do you want to avoid repeating computation, but you want to clean up any cached objects at some later, well-defined point?
- Something else?

I want to have an idea of why you might need this before we go implement anything!

**Comment by NickCrews** [comment]
Both of those points:

An example of this is the union-find algorithm to find the connected components of a graph. eg what https://github.com/moj-analytical-services/splink/blob/32714c932d58b044b4865dfdbc7575e7a4db37bc/splink/connected_components.py#L395 does.
This requires having a set of working tables that hold the "representative" of each node, and we loop many times, updating this table, stopping at convergence. The user of this connected components algorithm doesn't care about the intermediate results, and they don't want them present in the DB at the end of the function. I just want the API of
`connected_components(edges: Table) -> Table`
