### ISSUE TITLE
bug: `CompileError: Multiple, unrelated CTEs` on union of complex Tables

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5708]
### What happened?

```python
import ibis
from ibis import _
from ibis import examples as ex

t1 = ex.Aids2.fetch()
t2 = ex.Aids2.fetch()
cols = ["diag", "status"]
t1 = t1.select(*cols)
t2 = t2.select(*cols)
t1 = t1.mutate(diag = _.diag + 1)
t2 = t2.mutate(diag = _.diag + 1)
t1 = t1.mutate(diag=_.diag.cast("int32"))
t2 = t2.mutate(diag=_.diag.cast("int32"))
u = ibis.union(t1, t2)
u.execute()
```

Results in `CompileError: Multiple, unrelated CTEs found with the same name: 't0'`

If I skip one of these modifications, it does not error. If I re-order them, then it still errors.

This appears way too down in the guts of Ibis for me to want to tackle myself, sorry :)

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I looked into this. We're being too clever about alias generation.
