### ISSUE TITLE
feat:  Read and retrieve hdf5 big dataset

### ISSUE THREAD

**Issue by hengaini2055** [ibis-project/ibis#5714]
### Is your feature request related to a problem?

Why is there no support for hdf5? Hdf5 is similar to parquet, and can also have high compression ratios, large data volumes, and even cubes. According to the introduction of the latest pytables, it can achieve tens of billions of data reading efficiency and use a smaller memory.
https://www.blosc.org/posts/100-trillion-baby/

### Describe the solution you'd like

I'd like to add hdf5 as a backend.

### What version of ibis are you running?

4.1.0

### What backend(s) are you using, if any?

NO

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @hengaini2055!

Answers inline.

> Why is there no support for hdf5?

What does it mean to you for ibis to support this format? Do you want to be able to run SQL queries on it, or something else?

You can always read in the contents of an HDF5 file into a pandas DataFrame and then use any number of ibis backends to operate on that DataFrame.

> Hdf5 is similar to parquet

I can see why this is a tempting conclusion, but HDF5 and Parquet are pretty different.

Parquet is pretty much exclusively designed for sequential full scans of tabular data, while HDF5 targets random access (and likely supports sequential scans too). HDF5 also appears to lack proper support for missing data, and frankly it's going to be hard to justify working with any format that doesn't support SQL-style missing values.

> and can also have high compression ratios, large data volumes, and even cubes.

High compression ratios are not a feature of HDF5 per se, but of the fact that it supports compressing data with a wide variety of compression algorithms. This is definitely a nice feature of HDF5. Large data volumes are nice too, but we have plenty of support for large data across our backends.

Cubes is a bit of an ambiguous term. Do you mean a three-dimensional array, or a data cube in the data warehousing sense? I'm guessing HDF5's "cubes" are closer to the former than the latter.

> According to the introduction of the latest pytables, it can achieve tens of billions of data reading efficiency and use a smaller memory.

I think I would ask "relative to what?" regarding the memory usage. Smaller than DuckDB, pandas, numpy, Postgres?

Perhaps the most important question is: How do you want to use ibis with HDF5?

**Comment by hengaini2055** [comment]
I want to be able to run SQL queries on it. As you suggest, I think I can use duckdb instead it. Thank you!
