### ISSUE TITLE
feat: Allow single table inputs to ibis.union()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5715]
### Is your feature request related to a problem?

I am loading a variable number of .csvs and merging them into one table. If I only have one .csv, then `ibis.union(*chunks)` errors. I would like it to not, it just returns the single table unchanged. The len==0 case should still error.

### Describe the solution you'd like

Some examples of other libraries that follow this behavior (no-op on a single iterable):

- np.concatenate
- pandas.concat
- polars.concat
- dask.dataframe.concat

I didn't think of any libs that use our current behavior, but they very well might exist.

### What version of ibis are you running?

Target 5.0?

### What backend(s) are you using, if any?

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I think we can probably get this in for 5.0
