### ISSUE TITLE
feat: optional arrow-based query result for Snowflake

### ISSUE THREAD

**Issue by malthe** [ibis-project/ibis#5739]
### Is your feature request related to a problem?

In #5492, functionality to use the new Snowflake Fetch API for fast column-based results was removed because of various limitations in returning semi-structured query responses.

### Describe the solution you'd like

We can make this API available for users on an opt-in basis, for [example using a kwargs + url parameter](https://github.com/ibis-project/ibis/pull/5492#issuecomment-1468248944).

### What version of ibis are you running?

3.2.0

### What backend(s) are you using, if any?

Snowflake

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue! We'll tackle this after the 5.0 release.

**Comment by malthe** [comment]
@gforsyth so to use this, one would do:
```python
from snowflake.connector.constants import PARAMETER_PYTHON_CONNECTOR_QUERY_RESULT_FORMAT as FORMAT

conn = connect(..., connect_args={FORMAT: "ARROW"})
```
Is that correct?
