### ISSUE TITLE
does duckdb support for s3:// use fsspec or duckdb's native mechanism?

### ISSUE THREAD

**Issue by cboettig** [ibis-project/ibis#5748]
### Is your feature request related to a problem?

Queries generated by ibis against remote S3 resources using duckdb are taking about twice as long to run for me as when I call `duckdb.sql` with a SQL string directly (using duckdb's `httpfs` extension, not the fsspec support).  I was just wondering if the cause for this might be that ibis is passing the I/O through an additional python layer? (I notice considerably lower bandwidth load when the query is running in ibis too, data transfer rates of around 200 Mb/s instead of around 500 Mb/s).  

### Describe the solution you'd like

If ibis is currently using fsspec to handle the queries, would you consider using duckdb's native httpfs extension instead? I think it can provide considerably better performance in some cases.

### What version of ibis are you running?

4.1.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
We're using `pyarrow.dataset` to handle S3 authentication, because DuckDB only supports s3 auth via a single, home-rolled, method of specifying credentials.
I'm surprised it's that much slower, though.

**Comment by gforsyth** [comment]
It might be a little horrible, but we could try to use the duckdb `httpfs` builtin by default, then fall back to `pyarrow` if it fails (to try with credentials).  

xref https://github.com/duckdb/duckdb/issues/4021

**Comment by cboettig** [comment]
Thanks! yup, these are public resources, example benchmark below.  I may also be completely wrong about the cause for the speed differences here, it may just be due to Ibis generating less efficient SQL?  This should be a reproducible example on a moderate-sized public dataset, takes about 7-8min for 'pure duckdb' but abour 20min for ibis version on my machine:

## duckdb / sql

```
import duckdb
con = duckdb.connect()
con.execute("INSTALL httpfs")
con.execute("LOAD httpfs")

query = f'''
SELECT class, longitude, latitude, COALESCE(n, 0.0) AS n
FROM (
  SELECT class, longitude, latitude, COUNT(*) AS n
  FROM (
    SELECT DISTINCT
      class,
      genus,
      ROUND(decimallongitude,0) AS longitude,
      ROUND(decimallatitude, 0) AS latitude
    FROM read_parquet("s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*")
    WHERE (phylum = 'Chordata')
  )
  GROUP BY class, longitude, latitude
)
'''

df = con.execute(query).df()

```


## Ibis

```
con = ibis.duckdb.connect()
bucket = "gbif-open-data-us-east-1"
path = "occurrence/2023-02-01/occurrence.parquet"
gbif = con.register(f"s3://{bucket}/{path}")

tbl = (gbif
       .filter(gbif.phylum == "Chordata")
       .mutate(latitude = gbif.decimallatitude.round(0),
               longitude = gbif.decimallongitude.round(0))
       .select(["class", "genus", "longitude", "latitude"])
       .distinct()
       .group_by(["class","longitude", "latitude"])
       .size()
      )
#ibis.show_sql(tbl) # optionally peek at the SQL query
df = tbl.to_pandas()
```

**Comment by gforsyth** [comment]
Ok -- I'm guessing `dataset` is creating much more overhead than we expected, but I need to get better timings first.  

If you use `https` links to the buckets, then Ibis uses the `duckdb` `httpfs` plugin and the timings are more in-line with what I expect (a constant time difference of ibis vs. duckdb for compilation overhead)

(I also trimmed this down to just 3 of those parquet files to speed things up but the performance difference is consistent when I ramp up to 10)

```python
[ins] In [4]: con = ibis.duckdb.connect()
         ...: bucket = "gbif-open-data-af-south-1"
         ...: path = "occurrence/2023-02-01/occurrence.parquet"
         ...: gbif = con.read_parquet(
         ...:     [f"https://{bucket}.s3.af-south-1.amazonaws.com/{path}/00000{i}" for i in range(3)]
         ...: )
         ...: 
         ...: tbl = (
         ...:     gbif.filter(gbif.phylum == "Chordata")
         ...:     .mutate(
         ...:         latitude=gbif.decimallatitude.round(0), longitude=gbif.decimallongitude.round(0)
         ...:     )
         ...:     .select(["class", "genus", "longitude", "latitude"])
         ...:     .distinct()
         ...:     .group_by(["class", "longitude", "latitude"])
         ...:     .size()
         ...: )

[ins] In [5]: %time df = tbl.execute()
100% ▕████████████████████████████████████████████████████████████▏ 
CPU times: user 486 ms, sys: 119 ms, total: 605 ms
Wall time: 19.2 s

[ins] In [6]: %time df = tbl.execute()
100% ▕████████████████████████████████████████████████████████████▏ 
CPU times: user 1.42 s, sys: 589 ms, total: 2.01 s
Wall time: 20.3 s
```

```python
[ins] In [4]: import duckdb
         ...: 
         ...: con = duckdb.connect()
         ...: con.execute("INSTALL httpfs")
         ...: con.execute("LOAD httpfs")
         ...: 
         ...: files = [
         ...:     f"https://gbif-open-data-af-south-1.s3.af-south-1.amazonaws.com/occurrence/2023-02-01/oc
         ...: currence.parquet/00000{i}"
         ...:     for i in range(3)
         ...: ]
         ...: 
         ...: query = f"""
         ...: SELECT class, longitude, latitude, COALESCE(n, 0.0) AS n
         ...: FROM (
         ...:   SELECT class, longitude, latitude, COUNT(*) AS n
         ...:   FROM (
         ...:     SELECT DISTINCT
         ...:       class,
         ...:       genus,
         ...:       ROUND(decimallongitude,0) AS longitude,
         ...:       ROUND(decimallatitude, 0) AS latitude
         ...:     FROM read_parquet({files})
         ...:     WHERE (phylum = 'Chordata')
         ...:   )
         ...:   GROUP BY class, longitude, latitude
         ...: )
         ...: """

[ins] In [5]: %time df = con.execute(query).df()
100% ▕████████████████████████████████████████████████████████████▏ 
CPU times: user 9.09 s, sys: 4.08 s, total: 13.2 s
Wall time: 17.7 s

[ins] In [6]: %time df = con.execute(query).df()
100% ▕████████████████████████████████████████████████████████████▏ 
CPU times: user 2.72 s, sys: 1.4 s, total: 4.12 s
Wall time: 18.9 s
```

**Comment by gforsyth** [comment]
@cboettig -- we're going to switch over to using `duckdb` native parquet reader by default, but we've also just been made aware that there is a _massive_ performance regression for _some_ reason in recent openssl versions.
If you upgrade to openssl 3.1.0 we've seen 5-7x performance improvements in `pyarrow.dataset` reading from s3
