### ISSUE TITLE
bug(bigquery): new support for `BIGNUMERIC` is broken

### ISSUE THREAD

**Issue by dimitri-b** [ibis-project/ibis#5765]
### What happened?

Trying `conn.table("foo")` for a BigQuery table with BIGNUMERIC types raises a `parsy` error (see below).

I suspect that the cause of this is the lack of mapping for BIGNUMERIC in the `_DTYPE_TO_IBIS_TYPE` dict constant here:
https://github.com/ibis-project/ibis/blob/master/ibis/backends/bigquery/client.py#L20

So, when a conversion from BigQuery to Ibis data type is attempted, the BIGNUMERIC is simply left as is, i.e. a string.

### What version of ibis are you using?

5.0.0

### What backend(s) are you using, if any?

BigQuery

### Relevant log output

```sh
...
raise ParseError(result.expected, stream, result.furthest)
parsy.ParseError: expected one of '!', 'array', 'binary', 'bool', 'boolean', 'bytes', 'char', 'date', 'decimal', 'double', 'float', 'float16', 'float32', 'float64', 'geography', 'geometry', 'halffloat', 'inet', 'int', 'int16', 'int32', 'int64', 'int8', 'interval', 'json', 'linestring', 'macaddr', 'map', 'multilinestring', 'multipoint', 'multipolygon', 'null', 'point', 'polygon', 'set', 'str', 'string', 'struct', 'time', 'timestamp', 'uint16', 'uint32', 'uint64', 'uint8', 'uuid', 'varchar' at 0:0
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the bug report!

Looks like @krzysztof-kwitt is working on it!
