### ISSUE TITLE
bug: Inconsistent link in converted Jupyter notebook documentation

### ISSUE THREAD

**Issue by metab0t** [ibis-project/ibis#5776]
### What happened?

The link in converted Jupyter notebook documentation is inconsistent between the main text and the TOC on the right hand.

For example, in https://ibis-project.org/ibis-for-pandas-users/
The `Data types` link in main text is https://ibis-project.org/ibis-for-pandas-users/#Data-types but the corresponding link in TOC on the right side is https://ibis-project.org/ibis-for-pandas-users/#data-types

### What version of ibis are you using?

latest 5.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the report @metab0t!

This looks like an issue in `mkdocs-jupyter`, which we use to generate the HTML for the notebooks.

**Comment by cpcloud** [comment]
@danielfrg Is this bug on your radar?

**Comment by metab0t** [comment]
The link on [their demo site](https://mkdocs-jupyter.danielfrg.com/variational-inference-nb/) is correctly handled.

**Comment by cpcloud** [comment]
In that case, it might be an interaction with a plugin. Looking into it.

**Comment by cpcloud** [comment]
After disabling all plugins except for `mkdocs-jupyter` the HTML is still invalid, so I don't think it's a plugin interaction.

**Comment by gforsyth** [comment]
`mkdocs-jupyter` monkeypatches the `IPythonRenderer` from `nbconvert` to lower-case all the anchor links (https://github.com/danielfrg/mkdocs-jupyter/blob/main/mkdocs_jupyter/convert.py)

But it looks like the `header` method has been replaced with `heading`: https://github.com/jupyter/nbconvert/blob/6f77b0be07a494af5dcc55fb827ec0cfeb6bbfdd/nbconvert/filters/markdown_mistune.py#L207

**Comment by cpcloud** [comment]
@metab0t Thanks for fixing that upstream!

In the meantime I can patch in that PR for our docs build and close this out. That way we don't have to wait for a `mkdocs-jupyter` release to fix our docs.

**Comment by danielfrg** [comment]
`mkdocs-jupyter` `0.24.1` is out now
