### ISSUE TITLE
bug: `type` arg is ignored in ibis.literal(ibis.NA)

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5788]
### What happened?

```python
import ibis
ibis.show_sql(ibis.literal(ibis.NA, type="string"))
```
Gives 
```sql
SELECT
  NULL AS "None"
```
ie the type argument is ignored.

To get the desired behavior, I have to do `ibis.show_sql(ibis.literal(ibis.NA).cast("string"))`, which gives
```sql
SELECT
  CAST(NULL AS TEXT) AS "Cast(None, string)"
```

### What version of ibis are you using?

5.0.0

### What backend(s) are you using, if any?

duckdb. I'd guess this would be present in others as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue.

Seems like we should probably cast `NULL` to its output type.

In the meantime, `ibis.NA` is already an ibis expression so you don't need to call literal on it, you can just cast:

```
In [7]: ibis.show_sql(ibis.NA.cast("string"))
SELECT
  CAST(NULL AS TEXT) AS "Cast(None, string)"
```

**Comment by cpcloud** [comment]
@NickCrews Is this causing a particular problem for you? If so, can you elaborate on it a bit here?

**Comment by cpcloud** [comment]
If you can show the `parse_zipcode` code that'd be swell!

**Comment by NickCrews** [comment]
```python
def parse_zipcode(s: StringValue) -> StringValue:
    """Parse a zipcode into a 5-digit zipcode, correcting for common errors.

    Corrections include:
      - replacing the letters o and O, or the literal word "zero" with a "0"
      - adding back a leading 0 if the zipcode is only 4 digits (probably from
        when the zipcode was interpreted as an int and the leading 0 was stripped)
      - dropping the +4 if it's there
    """
    s = s.re_replace(r"[Oo]|[Zz][Ee][Rr][Oo]", "0")
    s = s.re_replace(r"^\s*(\d{4})(?:\s*|-\d{4})$", r"0\1")
    s: StringColumn = s.re_extract(r"(\d{5})", 1).cast("string")
    all_zeros_or_empty = s.re_search(r"^0*$")
    s = all_zeros_or_empty.ifelse(ibis.null(), s)
    return s
```

If I remove the `.cast()` within _call_as_ibis_value(), then I get `AttributeError: 'NullScalar' object has no attribute 're_replace'`

**Comment by cpcloud** [comment]
This may be a documentation issue:

```
In [5]: ibis.NA.equals(ibis.literal(None))
Out[5]: True
```

`ibis.NA` is untyped, so you should be able to use it anywhere you have `ibis.literal(None)`.

**Comment by NickCrews** [comment]
That makes sense and I think that is good behavior, but I would also expect that `ibis.literal(ibis.NA, type='string').equals(ibis.literal(None, type='string'))`, which it currently does not. Is there a problem with changing this?

**Comment by cpcloud** [comment]
> Is there a problem with changing this?

It doesn't really make sense to pass an ibis literal as an argument to the `literal` function.

If you substitute the definition of `ibis.NA` in the proposed call you get this:

```python
ibis.literal(ibis.literal(None, type="null"))
```

which doesn't make a whole lot of sense, since you can simply use `ibis.NA`.

The `literal` function is designed to convert Python literals into ibis expressions, and `ibis.NA` is already an ibis expression.
