### ISSUE TITLE
Move connection thread safety to impyla

### ISSUE THREAD

**Issue by laserson** [ibis-project/ibis#583]
It really shouldn't be handled in ibis.

**Comment by laserson** [comment]
Tracked in cloudera/impyla#117

**Comment by wesm** [comment]
@laserson also check out the way I had to hack around `execute_async` overhead (it seems codegen time is paid by the user, regardless of whether synchronous or asynchronous) in `ibis/impala/client.py`

**Comment by cpcloud** [comment]
Closing as an upstream bug
