### ISSUE TITLE
bug: conda lock files aren't being generated

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#5840]
### What happened?

https://github.com/ibis-project/ibis/actions/runs/4521978500/jobs/7964095204

### What version of ibis are you using?

`master`

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
oops -- let me fix that

**Comment by cpcloud** [comment]
This is fixed as of [this job run](https://github.com/ibis-project/ibis/actions/runs/4555511637/jobs/8034857502) from [this commit](https://github.com/ibis-project/ibis/commit/063e389ed0daed69ee56b0f3eac44e100c658468)
