### ISSUE TITLE
feat(sqlalchemy): allow creating backends from existing sqlalchemy engine

### ISSUE THREAD

**Issue by thegreymatter** [ibis-project/ibis#5852]
### Is your feature request related to a problem?

I would like the ability to connect ibis backend to existing sql alchemy backend. there are several use cases for that
- support connection parameters ibis will not (yet) support. (for example   connect_args={"check_same_thread": False}) in sqlite) 
- allow me to share the same session with other **legacy** systems which recieve the engine. 
- allow me to manage the session outside of ibis.

### Describe the solution you'd like

I would expect the ability to create backend directly from engine. 

engine = ...
backend = ibis.connect(engine)

### What version of ibis are you running?

5.0.0

### What backend(s) are you using, if any?

sqlite, snowflake, duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Closing this out for now. Happy to continue the discussion with more information about the two points listed above.

I've experimented with something similar to the request in this issue (but specific to snowflake/snowpark) in #6156, but it's difficult to get both snowpark and ibis to play nice together.

Snowpark uses qmark params and ibis uses snowflake-sqlalchemy which uses pyformat params, and snowflake sqlalchemy claims to support both styles but doesn't.
