### ISSUE TITLE
bug: snowflake connection issues

### ISSUE THREAD

**Issue by ededovic** [ibis-project/ibis#5856]
### What happened?

My console hangs when I attempt to connect to snowflake. Other databases work fine. I followed instruction from the below link, but it did not help, and I tried couple of different ways as well. to no avail. 
```
con = ibis.connect("snowflake://user:pass@account/database/schema")
```
hangs the iPython & Jupyter consoles.

Second approach: 
```
ibis.snowflake.connect(user=..., password=..., account=..., database=..., schema=..., warehouse=...)
```
I get this error: 
```
ValueError: Schema must be non-None. Pass the schema as part of the database e.g.
```
Third approach: 
```
ibis.snowflake.connect(user=..., password=..., account=..., database='database/schema,  warehouse=...)
```
Then it just hangs like the first approach. 

https://voltrondata.com/resources/how-to-use-snowflake-and-ibis-for-better-analytics

### What version of ibis are you using?

Ibis version 5.0

### What backend(s) are you using, if any?

snoflake

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
The only way I could get this hang forever is to put in a syntactically correct but invalid `account` name like `xx12345.us-central1.gcp`.

I suspect you're specifying the wrong account in some way, either the identifier (`xx12345`) or the region and cloud provider.

**Comment by ededovic** [comment]
You are absolute right and very helpful. I assumed that I was using the full account name, but it should be 
account.region.svc like `x12345.us-east-1.aws`.
