### ISSUE TITLE
bug(ux): choose a different character for `NULL` values in interactive repr

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#5860]
Currently we use display null values as `∅` in the interactive repr. This works, some supposedly-monospace fonts display this character with a double width, leading to the repr columns no longer being aligned.

See this screenshot of our new getting started guide, for example:

![image](https://user-images.githubusercontent.com/2783717/228329445-874508d8-8799-44d6-bbe3-c00600df9e3c.png)

While this could be fixed by changing the font, this has happened enough in enough locations that I think we should just pick a less fancy character.

A few options:

- No value. This is pretty common in table reprs (e.g. duckdb's table repr does this). Since we display the empty string as `~`, we shouldn't have issues distinguishing `""` from `NULL`.
- `*`
- `-`
- `~` (we currently use this for the empty string)
- `NA`

Thoughts?

**Comment by cpcloud** [comment]
I guess we just can't have nice textual things, ugh 😁 

+1 for `NA`. I'd like to keep it dimmed, so it doesn't look like just another string. Even better might be to add a color to it to make it pop out even more.

**Comment by jcrist** [comment]
I'm personally leaning towards no value (mirroring other common table reprs). I think nulls happen often enough that something like `NA` that stood out more would be a bit distracting. I'd rather have my attention drawn towards places where there is data than places where it's absent.

**Comment by cpcloud** [comment]
I dislike nothing because I think it's ambiguous with empty string (I explicitly added the empty string indicator for that reason as well), but for someone who didn't implement it's not obvious IMO that showing nothing means `NULL`. I don't really like it in all the other systems that do that either, like postgres and duckdb 😅

**Comment by cpcloud** [comment]
That said, this isn't a hill I'm ready to die on.

**Comment by kszucs** [comment]
Clickhouse uses: ᴺᵁᴸᴸ

**Comment by jcrist** [comment]
Here's screenshots of both options on a dark-background terminal:

**Using NA**

![image](https://user-images.githubusercontent.com/2783717/228347059-346773fd-f12e-499d-ae66-1b78850b27a5.png)


**Using nothing**

![image](https://user-images.githubusercontent.com/2783717/228357813-167833ab-1253-4d20-9a17-07c13952fa0a.png)

I think for numbers I find the color difference sufficient to make `NA` not stand out. But for strings, the `dim` and `white` colors aren't different enough, and I find it takes a sec to differentiate text from `NA`. This is easier if the text contains long strings, but harder when it's short strings (especially things like state abbreviations).

**Comment by cpcloud** [comment]
+1 on empty, looks good to me!

**Comment by kszucs** [comment]
How would a non-empty string look like containing only whitespaces?

My preference is:
1. `ᴺᵁᴸᴸ` (subscripting makes it easier to distinguish)
2. `NULL`

**Comment by cpcloud** [comment]
> How would a non-empty string look like containing only whitespaces?

Good point. It would be ambiguous with NULL. Ok, I'm now back in favor of showing **something** for `NULL` as opposed to empty string:

```
In [2]: t = ibis.memtable({"a": ["    "]})

In [3]: t
Out[3]:
┏━━━━━━━━┓
┃ a      ┃
┡━━━━━━━━┩
│ string │
├────────┤
│        │
└────────┘
```

**Comment by cpcloud** [comment]
We can also just add some color to strings to make this less ambiguous. Coloring them green is fine by me. In fact, I'm already -0.5 on the fact that strings don't have any highlighting, but everything else does.
