### ISSUE TITLE
feat: `import ibis.selectors as s`

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5861]
### Is your feature request related to a problem?

I can currently do `from ibis import selectors as s`, but not `import ibis.selectors as s`

### Describe the solution you'd like

as above

### What version of ibis are you running?

target 5.1?

### What backend(s) are you using, if any?

any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Thanks for opening this, I was just frustrated with this myself. This is an artifact of all our API expressions/methods living in `ibis.expr` (the public api is defined in https://github.com/ibis-project/ibis/blob/master/ibis/expr/api.py).

Two options:
- Move the definition of `selectors` to a true `ibis.selectors` module. This would break the old api though, and some may not like the definition of new api methods to live outside of the `ibis.expr` namespace
- Add a new module in `ibis.selectors` just for mirroring the api. This might look like:

```python
# ibis/selectors.py
from ibis.expr.selectors import *
```

**Comment by cpcloud** [comment]
I personally am okay with moving the definition, but that'd be for 6.0

**Comment by cpcloud** [comment]
Alternatively we could probably make it backwards compatible, deprecate and remove in 6.0.

**Comment by NickCrews** [comment]
Either of those options seem good to me, I don't think I have a preference.
