### ISSUE TITLE
feat: add a function that shows backends having translation rules for a given operation class

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#588]

**Comment by kszucs** [comment]
@wesm What would be the desired API for this?

**Comment by cpcloud** [comment]
The information to do this would be in `ibis/backends/base/sql/compiler/translator.py` around like 200:

```python
class ExprTranslator:

    """Class that performs translation of ibis expressions into executable
    SQL.
    """

    _registry = operation_registry
    _rewrites: Dict[ops.Node, Callable] = {}
```

**Comment by cpcloud** [comment]
We now have `ibis.${backend}.has_operation` as well as a big matrix showing the [operation support matrix](https://ibis-project.org/backends/support_matrix/).
