### ISSUE TITLE
refactor(dask): Consolidate Dask aggcontext logic with Pandas

### ISSUE THREAD

**Issue by patcao** [ibis-project/ibis#5911]

**Comment by cpcloud** [comment]
Just out of curiosity is this work planned, or is this a reminder issue?

**Comment by patcao** [comment]
The Dask aggcontext is pretty much a straight copy of the Pandas aggcontext but with Dasky handling in certain places.
This is a reminder issue to refactor it.

**Comment by cpcloud** [comment]
Is there any reason we can't do that in the PR?

**Comment by patcao** [comment]
I've needed to xfail a bunch of tests relating to the windowing and aggcontext in Dask. So I expect I will need to fix up some things in  the aggcontext to get all the tests passing.
Also, I didn't want to include any changes in any of the other backends, as the PR only gives initial support for windowing, there's still quite a bit more that needs to be done.
