### ISSUE TITLE
bug(ir): validate filter inputs in `ops.Selection`

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#5920]
That particular issue should be fixed at the operation node level, ideally using a rule. This would prevent invalid inputs from going into the `ops.Selection` constructor.

_Originally posted by @cpcloud in https://github.com/ibis-project/ibis/issues/5919#issuecomment-1497904801_

**Comment by kszucs** [comment]
The 7.x branch now defines predicas as follows:

```py
class Selection(Projection):
    predicates: VarTuple[Value[dt.Boolean]] = ()
    sort_keys: VarTuple[SortKey] = ()
```

Do we need additional validation there?

**Comment by cpcloud** [comment]
I don't think so, let's close this out.
