### ISSUE TITLE
docs: ibis for R users

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#5922]
We currently have:

- [Ibis for Pandas Users](https://ibis-project.org/ibis-for-pandas-users/)
- [Ibis for SQL Programmers](https://ibis-project.org/ibis-for-sql-programmers/)

It'd be nice to have an onboarding notebook like these for R users as well (probably coming from a tidyverse/dplyr perspective).

**Comment by ianmcook** [comment]
Limiting this only to "Ibis for dplyr Users" (at least initially) would make it a lot more straightforward. Later we could come back and address the other popular data manipulation APIs in R (base R, data.table).

**Comment by jcrist** [comment]
This was resolved in #6050. Closing.
