### ISSUE TITLE
bug: NameError: name 'pd' is not defined when calling create_table with clickhouse backend 

### ISSUE THREAD

**Issue by JackFielding** [ibis-project/ibis#5937]
### What happened?

I am **very** new to ibis, so apologies if this report is incorrect 🙂.

I am using the clickhouse backend and calling the `create_table` method. I see `NameError: name 'pd' is not defined`.

### Script to reproduce

```python
import ibis
print(ibis.__version__)  # prints 5.0.0

ibis.set_backend("clickhouse")

connection = ibis.clickhouse.connect()
connection.create_table(name="myTable", engine="MergeTree", schema=[])
```

The log output/stacktrace is included below. If it helps I am running on Python 3.8.13.

The issue appears to be to do with [TYPE_CHECKING](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING). The python docs say:
> It is False at runtime.

As a result the `import pandas as pd` code within the `if TYPE_CHECKING:` clause appears to not execute.

### What version of ibis are you using?

5.0.0

### What backend(s) are you using, if any?

clickhouse

### Relevant log output

```sh
5.0.0
Traceback (most recent call last):
  File "ibis_pd_name_error.py", line 7, in <module>
    connection.create_table(name="myTable", engine="MergeTree", schema=[])
  File "/home/jack/ibis_error/lib/python3.8/site-packages/ibis/backends/clickhouse/__init__.py", line 540, in create_table
    if isinstance(obj, pd.DataFrame):
NameError: name 'pd' is not defined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @JackFielding 👋🏻!

Thanks for the report! Your assessment is correct.

It looks like we are lacking some test coverage for the clickhouse backend's `create_table` implementation. I'll put up a PR to address this issue shortly.

**Comment by JackFielding** [comment]
Hi @cpcloud, that sounds great. I hacked the source code to ensure that `import pandas as pd` was called, and added a `print` statement to check what raw SQL was being generated. Here are a few things I noticed from some initial testing:

### CREATE from SELECT queries

When I call `create_table` passing an `ibis` `Table` as the  `obj`, the query generated had the `ENGINE` at the end, but ClickHouse expects it to be near the start:

```python
connection.create_table(name="hello2", engine="MergeTree", obj=an_ibis_table)
```

generated:

```sql
CREATE TABLE hello2 AS SELECT
  *
FROM (
  SELECT
    t0.transactionDate,
    t0.messageType
  FROM hello AS t0
) AS t1
LIMIT 3 ENGINE = MergeTree
```

The example in the ClickHouse docs has the `ENGINE` before the `SELECT`:
> `CREATE TABLE [IF NOT EXISTS] [db.]table_name[(name1 [type1], name2 [type2], ...)] ENGINE = engine AS SELECT ...`

So if I were writing this query I'd write something like:

```sql
CREATE TABLE hello2
Engine = MergeTree()
PARTITION BY toYYYYMM(transactionDate)
ORDER BY transactionDate
AS SELECT
    transactionDate,
    messageType
FROM hello
LIMIT 3
```

### CREATE with explicit schema queries

If I don't specify `obj` and instead specify a `schema`, then there seems to be a different issue.

In this type of `CREATE` query having the `ENGINE at the bottom is expected, so there's no issue there:
https://clickhouse.com/docs/en/sql-reference/statements/create/table#with-explicit-schema

```python
connection.create_table(name="hello2", engine="MergeTree()", schema=an_ibis_table.schema())
```

generates:

```sql
CREATE TABLE hello2 (ibis.Schema {
  transactionDate  !date
  messageType      string
}) ENGINE = MergeTree()
```

If I was writing this query manually I'd write something like:

```sql
CREATE TABLE hello2 (
    transactionDate Date,
    messageType Nullable(String)
) ENGINE = MergeTree()
```

**Comment by cpcloud** [comment]
Yep, both of those should be fixed in #5938

**Comment by cpcloud** [comment]
Thanks for trying this out, we're going to cut a release on Tuesday next week and I'm very happy this will make it in!

**Comment by JackFielding** [comment]
Thank you for your speedy help!

**Comment by JackFielding** [comment]
Thanks for merging the changes. I tried them out by installing from source, I'd be using `Memory()` engine (for test code), so they'd work for me.

I also tried creating a table with a `MergeTree()` engine (most common ClickHouse engine) from a `pd.DataFrame` and it didn't succeed, presumably because it is creating the time column with type `Nullable(DateTime)`. ClickHouse does not like nullable indexes.

I ran this script:

```python
import ibis
import pandas as pd
import datetime

ibis.set_backend("clickhouse")

connection = ibis.clickhouse.connect()

df = pd.DataFrame({
    "aTime": [
        datetime.datetime(2023, 1, 1),
        datetime.datetime(2023, 1, 2),
        datetime.datetime(2023, 1, 3)
    ],
    "aString": ["a", "b", None]
})

# using Memory() engine works just fine
connection.drop_table("hello2", force=True)
connection.create_table(
    name="hello2",
    engine="MergeTree()",
    order_by="aTime",
    partition_by="toYYYYMM(aTime)",
    obj=df
)

# using MergeTree() engine fails presumably because the column aTime is created as Nullable(DateTime)
connection.drop_table("hello2", force=True)
connection.create_table(
    name="hello2",
    engine="MergeTree()",
    order_by="aTime",
    partition_by="toYYYYMM(aTime)",
    obj=df
)
```

The key line from the stacktrace was:

```
DB::Exception: Partition key contains nullable columns, but `setting allow_nullable_key` is disabled.
```

As I said at the start, this isn't something that would block me, but I think people will run into it in future, so I thought I'd raise it.

**Comment by cpcloud** [comment]
You should be able to use the `schema` argument to force a specific schema. Without that there isn't really a safe way for us to infer the types of an arbitrary dataframe as not nullable yet.
