### ISSUE TITLE
feat: support for creating a new schema in Trino

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#5939]
### Is your feature request related to a problem?

The Trino backend does not currently implement `create_database`.

### Describe the solution you'd like

Implement `create_database` for the Trino backend. Trino uses the term "schema" to refer to a container that holds tables, views, etc. I believe this maps cleanly onto what is referred to as a "database" in Ibis. So it seems safe to implement `create_database` in the Trino backend in a way that generates and runs a Trino [`CREATE SCHEMA`](https://trino.io/docs/current/sql/create-schema.html) statement.

### What version of ibis are you running?

5.0.0

### What backend(s) are you using, if any?

Trino

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ianmcook** [comment]
This might be complicated by the concept of [catalogs](https://trino.io/docs/current/overview/concepts.html#catalog) in Trino

**Comment by cpcloud** [comment]
I'm not sure that catalogs complicate the issue. As I understand it a schema is inside of a catalog and that's it. I think mapping them to schemas makes sense.

I don't think Trino supports creating catalogs dynamically, so I'm not sure there's too much to do there. If they do, then it could complicate things.

**Comment by cpcloud** [comment]
Yeah, good point.

The notion of a "database" isn't well defined in ibis, and is inconsistent across backends. Some backends tie the notion of a database to the connection (postgres, mysql, etc), some do not (snowflake, clickhouse), some do not but do not have anything analogous to a database in other systems (trino, pyspark).

Many of these systems to overlap on the notion of a schema though, so perhaps that's the right level of abstraction for ibis too. `CREATE DATABASE ...` is not a particularly onerous bit of SQL (or IME common to write in the first place), so having an abstraction for it in ibis may be overkill.

Perhaps we deprecate `create_database` and add `create_schema`?

**Comment by ianmcook** [comment]
I suppose we need to decide whether to prioritize (a) portability across backends or (b) consistent naming within backends

**Comment by cpcloud** [comment]
Closing in favor of #6331.
