### ISSUE TITLE
feat(ddl): support PyArrow objects in `create_table`

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#5941]
### Describe the solution you'd like

It would be really nice if `create_table` allowed users to pass PyArrow Table and RecordBatch objects as `obj`.

### What version of ibis are you running?

5.0.0

### What backend(s) are you using, if any?

Trino

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Added in #6470 (we don't support using record batch readers because it leads to unpredictable behavior)
