### ISSUE TITLE
feat: list materialized views

### ISSUE THREAD

**Issue by dpprdan** [ibis-project/ibis#5962]
### Is your feature request related to a problem?

ibis does not `list_tables()` materialized views in Postgres.

``` sql
PS C:\> psql service=test
psql (15.2)
Type "help" for help.

postgres=# CREATE MATERIALIZED VIEW mymatview AS SELECT 1 AS col1;
SELECT 1
postgres=# \d
                 List of relations
 Schema |   Name    |       Type        |  Owner
--------+-----------+-------------------+----------
 public | mymatview | materialized view | postgres
(1 row)

postgres=# exit
```

``` python
import ibis
ibis.options.interactive = True

pg_url = "postgresql+psycopg:///?service=test"
con = ibis.postgres.connect(url=pg_url)

con.list_tables()
```

    C:\ProgramData\Miniconda3\envs\ibis_test\lib\site-packages\ibis\backends\postgres\registry.py:119: UserWarning: locale specific date formats (%c, %x, %X) are not yet implemented for Windows
      warnings.warn(

    []

### Describe the solution you'd like

IIUC (and that’s a big IF as I’ve been trying out Ibis only for a few days now) is using these SQLAlchemy inspector functions.

https://github.com/ibis-project/ibis/blob/6b2cbaaa33f0c9cc7b0174e082d5155f045cc2fe/ibis/backends/base/sql/alchemy/__init__.py#L101-L104

Fortunately, SQLAlchemy has gained a [`get_materialized_view_names()`](https://docs.sqlalchemy.org/en/20core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_materialized_view_names) function in version 2.0.

``` python
import sqlalchemy as sa
pg_eng = sa.create_engine(pg_url)
pg_con = pg_eng.connect()
inspector = sa.inspect(pg_con)
inspector.get_materialized_view_names()
```

    ['mymatview']

So a fix might possibly be as easy as (plus a SQLAlchemy version check)

``` python
def list_tables(self, like=None, database=None):
    tables = self.inspector.get_table_names(schema=database)
    views = self.inspector.get_view_names(schema=database)
    matviews = self.inspector.get_materialized_view_names(schema=database)
    return self._filter_with_like(tables + views + matviews, like)
```

`get_materialized_view_names()` seems to behave if an engine does not support materialized views (yet).

``` python
ddb_eng = sa.create_engine("duckdb:///palmer_penguins.ddb")
ddb_con = ddb_eng.connect()

ddb_inspector = sa.inspect(ddb_con)
ddb_inspector.get_materialized_view_names()
```

    []

Ideally Ibis would support materialized views even more, of course, e.g. with

- [`create_materialized_view()`](https://www.postgresql.org/docs/current/sql-creatematerializedview.html),
- [`refresh_materialized_view()`](https://www.postgresql.org/docs/current/sql-refreshmaterializedview.html), and
- [`drop_materialized_view()`](https://www.postgresql.org/docs/current/sql-dropmaterializedview.html).

Accessing materialized views does not seem to be a problem.

``` python
con.table("mymatview")
```

<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace">┏━━━━━━━┓
┃<span style="font-weight: bold"> col1  </span>┃
┡━━━━━━━┩
│ <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">int32</span> │
├───────┤
│     <span style="color: #008080; text-decoration-color: #008080; font-weight: bold">1</span> │
└───────┘
</pre>

### What version of ibis are you running?

5.0.0

### What backend(s) are you using, if any?

PostgreSQL (DuckDB as a does-not-support-matviews backend)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dpprdan** [comment]
Relatedly, I wonder whether `list_tables()` ought to list [temporary tables](https://ibis-project.org/api/backends/base/#ibis.backends.base.BaseBackend.create_table) and [views](https://ibis-project.org/api/expressions/tables/#ibis.expr.types.relations.Table.alias) as well ([`get_temp_table_names()`](https://docs.sqlalchemy.org/en/20/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_temp_table_names), [`get_temp_view_names()`](https://docs.sqlalchemy.org/en/20/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_temp_view_names))

**Comment by cpcloud** [comment]
Hi @dpprdan 👋🏻! Thanks for creating an issue about this.

Listing materialized views in `list_tables` is definitely something we can look into!

As far as DDL for `create`/`refresh`/`drop`, we'll need to get a list of the backends we support that support materialized views and take a look at their APIs and decide what options to support.

Here are the backend we support in ibis that support materialized views along with links to their documentation:

1. [PostgreSQL](https://www.postgresql.org/docs/current/rules-materializedviews.html)
2. [BigQuery](https://cloud.google.com/bigquery/docs/materialized-views-intro)
3. [Snowflake](https://docs.snowflake.com/en/sql-reference/sql/create-materialized-view)
4. [ClickHouse](https://clickhouse.com/docs/en/guides/developer/cascading-materialized-views)
5. [Trino](https://trino.io/docs/current/sql/create-materialized-view.html)

**Comment by cpcloud** [comment]
Closing in favor of #8382. Thanks for the discussion!
