### ISSUE TITLE
feat: DDL Materialized Views

### ISSUE THREAD

**Issue by dpprdan** [ibis-project/ibis#5964]
### Is your feature request related to a problem?

As mentioned in #5962 it would be nice to have DDL (`create`/`refresh`/`drop`) for materialized views.

### Describe the solution you'd like

Backends supported by ibis that support materialized views:

1. [PostgreSQL](https://www.postgresql.org/docs/current/rules-materializedviews.html) ([`create`](https://www.postgresql.org/docs/current/sql-creatematerializedview.html), [`refresh`](https://www.postgresql.org/docs/current/sql-refreshmaterializedview.html), [`drop`](https://www.postgresql.org/docs/current/sql-dropmaterializedview.html))

2. [BigQuery](https://cloud.google.com/bigquery/docs/materialized-views-intro) ([`create`](https://cloud.google.com/bigquery/docs/materialized-views-create), [`refresh`](https://cloud.google.com/bigquery/docs/materialized-views-manage#refresh), [`drop`](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_materialized_view_statement))

3. [Snowflake](https://docs.snowflake.com/en/user-guide/views-materialized) ([`create`](https://docs.snowflake.com/en/sql-reference/sql/create-materialized-view), `refresh` 🤷🏻‍♂️, [`drop`](https://docs.snowflake.com/en/sql-reference/sql/drop-materialized-view))

4. [ClickHouse](https://clickhouse.com/docs/en/guides/developer/cascading-materialized-views) ([`create`](https://clickhouse.com/docs/en/sql-reference/statements/create/view#materialized-view), `refresh` 🤷🏻‍♂️, [`drop`](https://clickhouse.com/docs/en/sql-reference/statements/drop#drop-view))

5. Trino ([`create`](https://trino.io/docs/current/sql/create-materialized-view.html), [`refresh`](https://trino.io/docs/current/sql/refresh-materialized-view.html), [`drop`](https://trino.io/docs/current/sql/drop-materialized-view.html))

6. MSSQL ([`create`](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-materialized-view-as-select-transact-sql?view=azure-sqldw-latest), [`refresh`](https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-materialized-view-transact-sql?view=azure-sqldw-latest&preserve-view=true), [`drop`](https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-view-transact-sql?view=azure-sqldw-latest&preserve-view=true))  ⚠️ Only in Azure Synapse

### What version of ibis are you running?

5.0.0

### What backend(s) are you using, if any?

PostgreSQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
We're not planning on tackling this any time soon.
