### ISSUE TITLE
SQLite: support a variant of NumericValue.summary

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#597]
Some of the metrics that are currently included aren't available in SQLite. 

I wonder if it's possible to create an aggregation or projection with expressions that are included conditionally based on whether they can be evaluated by a particular backend.

**Comment by hamedhsn** [comment]
@wesm as far as I am checking all the metrics are working fine with sqlite except the last one. in code it falls into the else part since exact_unique is false by default.
```javascript 
def _numeric_summary(arg, exact_nunique=False, prefix=None)
    metrics = [
        arg.count(),
        arg.isnull().sum().name('nulls'),
        arg.min(),
        arg.max(),
        arg.sum(),
        arg.mean()
    ]
    if exact_nunique:
        unique_metric = arg.nunique().name('nunique')
    else:
       unique_metric = arg.approx_nunique().name('approx_nunique')
```
not sure the differences between those two?
 but for exact_nunique of true summary works fine for sqlite as well.

**Comment by cpcloud** [comment]
Another option is to change the default to `True`, which is a breaking API change, but totally in line with our versioning policy.

More databases have count(distinct) than whatever the equivalent approximate version is, so having the default work out of the box even if it's slower is better.
