### ISSUE TITLE
feat: Connect to sqlite database from duckdb

### ISSUE THREAD

**Issue by ivirshup** [ibis-project/ibis#5981]
### Is your feature request related to a problem?

I would like to be able to use the python API to have a duckdb session attach to a sqlite database. This is separate from reading an individual table, as is currently supported.

This is currently possible to do via SQL:

```python
import ibis

connection = ibis.duckdb.connect()

connection.raw_sql("""
INSTALL sqlite;
LOAD sqlite;
CALL sqlite_attach('EnsDb.Hsapiens.v108.sqlite');
""")


connection.list_tables()
['protein_domain',
 'uniprot',
...
]
```

### Describe the solution you'd like

I would like there to be some python API for this. Potentially something like:

```python
connection = ibis.duckdb.connect()
connection.register("sqlite://EnsDb.Hsapiens.v108.sqlite")
```

### What version of ibis are you running?

'5.1.0'

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Can you try

```python
con = ibis.duckdb.connect()
t = con.read_sqlite("path/to/sqlite.db", table_name="mytable")
```?

**Comment by ivirshup** [comment]
Connecting to a single table from a sqlite store with the duckdb backend totally works right now.

But my feature request is for connect to the whole database, not just a single table.

**Comment by cpcloud** [comment]
Roger that! SGTM.

**Comment by gforsyth** [comment]
We could have `read_sqlite("path/to/sqlite.db")` default to reading in the whole db (if `table_name=None`)

Although would it be weird if `read_sqlite` returned None when you gave it a db with no table name specified?

**Comment by jcrist** [comment]
> Although would it be weird if `read_sqlite` returned None when you gave it a db with no table name specified?

Yeah, I don't love this. This is similar to how `ibis.connect("test.csv")` used to return a `Table`, and `ibis.connect("test.db")` would return a connection. I think we'll want a new method name for connecting to a whole db.

How about `attach_sqlite`, which returns `None`?

**Comment by cpcloud** [comment]
Another option (no strong opinions about it) is to implement an `attach` method (similar to the one that exists in the SQLite backend) that tries to attach its input as duckdb, or if that fails, as a sqlite database.

**Comment by ivirshup** [comment]
Wow, fast implementation! Thanks!
