### ISSUE TITLE
feat: support 2+ arguments to `ibis.interval()`

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#5983]
### Is your feature request related to a problem?

In Ibis, if you want to add 1 year + 1 month + 1 day to a date, you need to do:
```py
ibis.date('2023-04-12') + ibis.interval(years=1) + ibis.interval(months=1) + ibis.interval(days=1)
```
It would be nice if you could instead do:
```py
ibis.date('2023-04-12') + ibis.interval(years=1, months=1, days=1)
```
But this is not implemented and returns:
```
ValueError: Exactly one argument is required
```

### Describe the solution you'd like

Support passing multiple arguments to `ibis.interval()` and add the units together the construct the returned interval.

### What version of ibis are you running?

5.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@kszucs Thoughts on this?

Should we implement multiple arguments as the addition of the intervals?
