### ISSUE TITLE
docs: clarify which conda lock-file a user needs on osx in the dev docs

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#5985]
We had a contributor mistakenly use the `osx-64-*` lockfile when they should have used `osx-arm64-*`. We should rename the lockfiles so an install could use `"osx-$(arch)-3.10.lock"`, and update the dev docs accordingly.

**Comment by cpcloud** [comment]
Aren't these automatically generated names based on what conda outputs?

**Comment by cpcloud** [comment]
The osx x86_64 platform is called `osx-64` on conda. I'm not sure we should special case that.

**Comment by jcrist** [comment]
Ah, good point, didn't notice that we weren't generating these names.

Perhaps instead we should modify the dev docs slightly to better emphasize which osx lockfile a user should use.

**Comment by cpcloud** [comment]
Yeah, that makes sense 👍🏻

**Comment by jcrist** [comment]
Yeah, the contributor just missed the 2 tabs for macOS. I think a tiny comment in the osx ones reiterating the architecture would be sufficient.

**Comment by cpcloud** [comment]
Hm, okay. I think I may leave this one for someone else to do.

Not entirely sure about mentioning the architecture in two places right next to each other.
