### ISSUE TITLE
Maintaining aggregation state between task calls

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#6]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Tuesday Dec 09, 2014 at 20:08 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/6_

---

In order to reduce serialization / data transfer costs between consecutive Update tasks. In the case of a group-wise aggregation, many aggregation states might exist simultaneously in a particular Python worker process. These can be identified by a UUID and the UUID will have to be made known to the parent Impala process

One problem with this is that we would have to keep sending tasks to the same worker process, so releasing the worker back to the pool could become problematic.

**Comment by cpcloud** [comment]
@wesm Is this issue still relevant?

**Comment by wesm** [comment]
Nope
