### ISSUE TITLE
bug: LastValue for DUCKDB not supported

### ISSUE THREAD

**Issue by rongxin-yu** [ibis-project/ibis#6002]
### What happened?

I tried to run col.last() with duckdb and there was an error

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

DuckDB

### Relevant log output

```sh
ProgrammingError: (duckdb.CatalogException) Catalog Error: Scalar Function with name last_value does not exist!
Did you mean "list_value"?
LINE 1: ...ty * t0.last_px) / sum(t0.last_qty)) / last_value(t0.arrival_px) AS "Divide(Di...
                                                  ^
[SQL: SELECT t0.order_uid, (sum(t0.last_qty * t0.last_px) / sum(t0.last_qty)) / last_value(t0.arrival_px) AS "Divide(Divide(Sum(Multiply(last_qty, last_px)), Sum(last_qty)), LastValue(arrival_px))" 
FROM jp_exedb AS t0 
WHERE t0.date >= ? GROUP BY 1 
 LIMIT ?]
[parameters: ('2023-03-02', 5)]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @rongxin-yu 👋🏻!

Thanks for the report.

`first` and `last` correspond to `FIRST_VALUE`/`LAST_VALUE` in SQL and are only valid in a window function context.

I think what you're probably looking for is [`col.arbitrary(how="last")`](https://ibis-project.org/api/expressions/generic/#ibis.expr.types.generic.Column.arbitrary).

We have an issue to [unify `first`/`last`/`arbitrary`](https://github.com/ibis-project/ibis/issues/4149), but we haven't prioritized that at the moment.

In the mean time, the documentation could be better here and indicate that `first`/`last` are valid only in window function contexts, e.g., `t.col.first().over(...)` in ibis.

**Comment by rongxin-yu** [comment]
Hi @cpcloud,

Thank you for the explanation, appreciate it.

Best,
Rongxin

**Comment by cpcloud** [comment]
@rongxin-yu Circling back you should now be able to use `first`/`last` as an aggregate, for most backends including DuckDB.
