### ISSUE TITLE
feat: try_cast()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6009]
### Is your feature request related to a problem?

Say I have a columns of strings that are YYYY-MM-DD dates, but a few of them are malformed. If I call `.cast("date")` on them, I get `DataError: (duckdb.ConversionException) Conversion Error: date field value out of range: "4   -08-09", expected format is (YYYY-MM-DD)`

### Describe the solution you'd like

Can we have some sort of `on_error` optional arg to cast()? Or not exactly sure what the API should be. It would be fine if this just went to NULL for my case, but perhaps we could support any backup fill value?

For duckdb (what I'm using) this seems easy, but I'd imagine it is full of inconsistencies between backends. If you are using a backend that doesn't support a certain option, then we raise an error. I think there is precendent for this already in Ibis? But I don't know it off the top of my head.

### What version of ibis are you running?

5.1.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

I think a new `try_cast` method is probably the better option.

Some backends have an explicit API for this, e.g., Trino has a [`try_cast` function](https://trino.io/docs/current/functions/conversion.html#id1), BigQuery has a [`SAFE_CAST` function](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#safe_casting).

It's much easier to understand the semantics of `try_cast` when reading it, than a special argument with who knows how many options with various hard-to-predicate outputs.

**Comment by NickCrews** [comment]
I tried this, but sqlalchemy doesn't have a general TryCast op, I filed an issue above so we could leverage that. I tried a temp workaround with some string literals, but I don't understand the internals of ibis enough and I couldn't get it to work.

**Comment by cpcloud** [comment]
Backends that support some form of `try_cast`:

- trino
- bigquery
- duckdb
- snowflake
- clickhouse

**Comment by NickCrews** [comment]
OK, that change landed in sqlalchemy. Now need to add it to the specific engines. Started an issue for duckdb at https://github.com/Mause/duckdb_engine/issues/658 because that's the backend I care about.

**Comment by cpcloud** [comment]
I think to support this without requiring a change in dependencies means we'll have to write our own `TryCast` operation. We have a number of custom SQLAlchemy operations that we plumb through the entire SQLAlchemy compilation pipeline, like `struct_pack`.

Here are the steps to do that for DuckDB:

### Define the user-facing API

```python

# types/generic.py
#
# add a new try_cast method

class Value(...):
	def try_cast(self, to: dt.DataType) -> Value:
		return ops.TryCast(self, to).to_expr()

```

### Define the ibis IR operation

```python
# operations/generic.py

class TryCast(Value):
    ...  # same as cast, but don't inherit to avoid inheriting any behavior
```


### Define the SQLAlchemy function, its associated compilation and translation rules

```python
# duckdb/registry.py
#
# generalize later so other backends can use the operation definition

class try_cast(GenericFunction):
    def __init__(self, arg, to):
    	super().__init__()
		self.arg = arg
		self.type = to


@compiles(try_cast, "duckdb")
def compiles_try_cast(element, compiler, **kw):
	arg = compiler.process(element.arg, **kw)
    to = compiler.visit_typeclause(element)
    return f"try_cast({arg} as {to})"


_operation_registry = {
    ...,
	ops.TryCast: fixed_arity(sa.func.try_cast, 2),
}
```
