### ISSUE TITLE
bug: consistently alias `execute()` to `to_pandas()`

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#6011]
### What happened?

I noticed that with some Ibis backends (like Trino), the `execute()` and `to_pandas()` methods are synonymous, but for other backends (like DuckDB), `execute()` works but there is no `to_pandas()` method. I think we should make both methods available with all Ibis backends, for consistency.

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

I'm not seeing any backends that have a `to_pandas` method, this method only exists on expressions, schemas, and data types.

Where are you seeing that the Trino backend has a `to_pandas` method?

**Comment by ianmcook** [comment]
That's strange. Why is this working?
<img width="492" alt="image" src="https://user-images.githubusercontent.com/280509/233106755-ebae5ae3-c405-4292-9670-6699c90dc7c2.png">

**Comment by jcrist** [comment]
That `to_pandas` method is on an expression (everything after `t` is expressions), not on the backend (the `conn` object).

**Comment by ianmcook** [comment]
Strangely when I run the above in `python` it works fine, but in `ipython` it fails with this error:
```
AttributeError: 'Table' object has no attribute 'to_pandas'
```

**Comment by ianmcook** [comment]
> I suspect `ipython` is in a different Python environment with an older version of `ibis` installed.

Oops, yes, that was it 🤦‍♂️

**Comment by ianmcook** [comment]
Sorry, I was thrown off by version differences here.  It looks like `.to_pandas()` works consistently across backends in newer versions of Ibis.
