### ISSUE TITLE
feat: `read_iceberg` similar to `read_parquet`

### ISSUE THREAD

**Issue by wjones127** [ibis-project/ibis#6013]
### Is your feature request related to a problem?

Table formats like Apache Iceberg and Delta Lake have mostly been available in Spark / JVM, but with the Python modules [pyiceberg](https://py.iceberg.apache.org/) and [deltalake](https://delta-io.github.io/delta-rs/python/) we can load these table formats into Arrow data without the need for the JVM. pyiceberg already has [examples for importing to DuckDB](https://py.iceberg.apache.org/api/). deltalake supports reading a table into a PyArrow dataset, which DuckDB, DataFusion, and Polars support predicate and projection pushdown for ([various examples here](https://delta-io.github.io/delta-rs/python/usage.html#querying-delta-tables)).

### Describe the solution you'd like

It would be cool to design an API like `read_parquet` that is uniform between Spark and the Arrow-compatible backends (DuckDB, DataFusion, and Polars) for both of these formats.

### What version of ibis are you running?

NA

### What backend(s) are you using, if any?

Relevant backends: Spark, DuckDB, DataFusion, Polars

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

These indeed would be nice features to have.

Looking at [the `pyiceberg` implementation](https://github.com/apache/iceberg/blob/b756a5da3559be9deee9cdc674c4bf36ac291231/python/pyiceberg/table/__init__.py#L408-L429) I'm not sure this is ready for integration into ibis yet using the `to_arrow` and `to_duckdb` APIs.

Both of those implementations read everything into memory as a PyArrow table, and while this is nice I think it's unlikely that most heavy iceberg users have iceberg tables that can fit into their client machine's main memory.

That said, we could probably instead [pluck out the list of files](https://py.iceberg.apache.org/api/#query-a-table) backing the table and hand that to duckdb.

**Comment by lostmygithubaccount** [comment]
added for DuckDB and polars here: https://github.com/ibis-project/ibis/pull/6354

**Comment by cpcloud** [comment]
Changing the issue title to reflect @lostmygithubaccount's work on getting `read_delta` and `to_delta` up and running for various backends.

**Comment by cpcloud** [comment]
Took another look at pyiceberg, and it's still a bit too optimistic with respect to host memory (it's still reading everything into a pyarrow Table).

If there are ever improvements to that part of it or another API comes along that doesn't have the in-memory limitation then we can revisit adding `read_iceberg`.

**Comment by ianmcook** [comment]
DuckDB now has an Iceberg extension under development at https://github.com/duckdblabs/duckdb_iceberg. We should take a look at that.

**Comment by lostmygithubaccount** [comment]
per discussion it's not very active and doesn't support writes. once this (with at least some minimal docs) or the pyiceberg package supports write, I think this will be easy to add similar to delta lake tables
