### ISSUE TITLE
bug: band_members and band_instruments datasets from ibis.examples load incorrectly

### ISSUE THREAD

**Issue by amoeba** [ibis-project/ibis#6015]
### What happened?

I tried to load the `band_members` and `band_instruments` example datasets and they don't load with the column names I expect. See:

```
>>> import ibis
>>> import ibis.examples
>>> ibis.examples.band_members.fetch()
AlchemyTable: _ibis_read_csv_4gxnyi63115g6mkll0onyd6in
  column0 string
  column1 string
>>> ibis.examples.band_instruments.fetch()
AlchemyTable: _ibis_read_csv_ajf1l1updgbjpobsmf0c6jzhs
  column0 string
  column1 string
```

They should have columns like "name", "band", and "instrument". So far, other examples I've tried load just fine.

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

DuckDB

### Relevant log output

```sh
I checked the copy of `band_members.csv` stored in my `.cache` directory and it looks fine:


# cat band_members.csv
name,band
Mick,Stones
John,Beatles
Paul,Beatles
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks the issue.

Yeah, this is an artifact of the header inference algorithm for the backend (duckdb by default), and not a bug in ibis.

You can address the issue by passing `header=1`:

```
In [7]: from ibis.interactive import *

In [8]: ex.band_members.fetch(header=1)
Out[8]:
┏━━━━━━━━┳━━━━━━━━━┓
┃ name   ┃ band    ┃
┡━━━━━━━━╇━━━━━━━━━┩
│ string │ string  │
├────────┼─────────┤
│ Mick   │ Stones  │
│ John   │ Beatles │
│ Paul   │ Beatles │
└────────┴─────────┘

In [9]: ex.band_instruments.fetch(header=1)
Out[9]:
┏━━━━━━━━┳━━━━━━━━┓
┃ name   ┃ plays  ┃
┡━━━━━━━━╇━━━━━━━━┩
│ string │ string │
├────────┼────────┤
│ John   │ guitar │
│ Paul   │ bass   │
│ Keith  │ guitar │
└────────┴────────┘
```

**Comment by amoeba** [comment]
Thanks for the explanation @cpcloud. DuckDB having an issue with those two CSVs was pretty surprising. I realize this might be a tough sell, but would it be possible for the following statement to be true? "all ibis.example data loads into Ibis as expected (header names, column types, text encoding) when using the default backend"?

**Comment by cpcloud** [comment]
We could probably make that statement true for `header names`, but column types may slightly vary over longer periods of time (e.g., improvements or regressions to various CSV readers)

Text encoding is not something I spent any time on. These were all produced on my machine with the default encoding which is `sys.getfilesystemencoding()`. For me that's `UTF-8`.

I can update the example generation script to explicitly use `UTF-8`.

**Comment by cpcloud** [comment]
Re header names, I can report this as an issue upstream to duckdb.

**Comment by amoeba** [comment]
Makes sense @cpcloud, especially the point about not being able to control other CSV readers. Thank you!
