### ISSUE TITLE
feat: unique on all column types

### ISSUE THREAD

**Issue by wjones127** [ibis-project/ibis#6029]
### Is your feature request related to a problem?

I was trying to get the unique elements for a `array<string>` column. I noticed there is a `unique()` function for ArrayValue, but that gets unique sequences, and I just want elements. Easy enough, I can call `unnest`. But then I found that no other column type seems to implement unique. So I ended up with:

```python
df['components'].unnest().value_counts()['components']
```

which feels a bit clunky.

### Describe the solution you'd like

Since there's already `ArrayValue.unique()`, perhaps it's worth defining for other columns?

### What version of ibis are you running?

5.1.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @wjones127 -- the method for this in Ibis is `distinct` -- you need to call `distinct` on a table, but you can always have a one-column table, e.g.:

```python
[ins] In [8]: penguins[["species", "island"]].distinct()
Out[8]: 
┏━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ species   ┃ island    ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━┩
│ string    │ string    │
├───────────┼───────────┤
│ Adelie    │ Torgersen │
│ Adelie    │ Biscoe    │
│ Adelie    │ Dream     │
│ Gentoo    │ Biscoe    │
│ Chinstrap │ Dream     │
└───────────┴───────────┘

[ins] In [9]: penguins[["species"]].distinct()
Out[9]: 
┏━━━━━━━━━━━┓
┃ species   ┃
┡━━━━━━━━━━━┩
│ string    │
├───────────┤
│ Adelie    │
│ Gentoo    │
│ Chinstrap │
└───────────┘
```

**Comment by wjones127** [comment]
For context, I'm trying to convert an `array<string>` to a series of boolean indicator columns. So the result gets passed to:

```python
df = df.mutate(**{
    component: df.components.contains(component)
    for component in components
})
```

**Comment by cpcloud** [comment]
To be totally clear:

- `distinct` is compute unique values over all rows
- `unique` is **specific to arrays** and compute the unique array elements **per row**

Sounds like we may need to flesh this out in the documentation more.

**Comment by wjones127** [comment]
Oh that makes more sense 🤦
