### ISSUE TITLE
docs: make the backend operations matrix searchable

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#6031]
### Describe the solution you'd like

It's a minor nuisance that I can't cmd+f search the text on the backed operations matrix docs page. Even if I open it in its own browser tab at https://ibis-project.streamlit.app/ it's still not searchable. Is there a feature of Streamlit that we could use to make it searchable? It's just the operation names that it would be nice to be able to search for. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
cc-ing @krzysztof-kwitt, our resident streamlit expert - any tips for handling this?

**Comment by ianmcook** [comment]
Oh, I see—you first need to click on that column, then do cmd/ctrl + f. It didn't occur to me to click there first. Thanks!
