### ISSUE TITLE
Address behavioral differences between SQLite MAX/MIN varargs functions and pgsql/impala GREATEST/LEAST

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#604]
Postgres and Impala ignore NULL values while SQLite propagates them

**Comment by cpcloud** [comment]
To get postgres/impala behavior in sqlite, the workaround is to `coalesce` the argument with the proper identity element for the `max`/`min` binary operation. E.g.,:

```python
ibis.greatest(
    ibis.coalesce(
        t.a,  # possibly null int64
        dt.int64.bounds.min, 
    )
)
```

**Comment by cpcloud** [comment]
#605 is a similar issue.
