### ISSUE TITLE
feat: Better error message or support for joins involving multiple backends

### ISSUE THREAD

**Issue by amoeba** [ibis-project/ibis#6045]
### Is your feature request related to a problem?

I'm new to Ibis so I, a person new to Ibis, wanted to play with joins. I decided to bring pandas dataframes into Ibis to try that out. I first made two data frames that would be good candidates for a join:

```python
left_df = pd.DataFrame(
    [
        ['a', 2],
        ['b', 2]
    ], 
    columns=['key', 'two',],
)
right_df = pd.DataFrame(
    [
        ['a', 3],
        ['b', 3]
    ], 
    columns=['key', 'three',],
)
```
 
I then found the code to bring one into Ibis at the top of [Ibis for pandas users](https://ibis-project.org/ibis-for-pandas-users/) and wrote:

```python
t_left = ibis.pandas.connect({'left': left_df}).table('left')
```

Then to bring in my second dataframe I, a new person to Ibis, duplicated the above and added to the above:

```python
t_right = ibis.pandas.connect({'right': right_df}).table('right')
```

I then tried a join and got error:

```python
t_left.left_join(t_right, t_left.key == t_right.key)
```

> IbisError: Multiple backends found for this expression

### Describe the solution you'd like

My first thought when I saw the above error was that I needed to set or explicitly offer a backend because Ibis wasn't able to decide on which one to use to execute my expression. But after scrolling down in [Ibis for pandas users](https://ibis-project.org/ibis-for-pandas-users/), I see I need to load both dataframes into _the same backend_.

i.e., 

```python
pd_ibis = ibis.pandas.connect({'t_left': df_left, 't_right': df_right})
```

I guess I have two questions:

- What does that error message mean? Could it be improved? It sounds like I needed to give Ibis more info but I think it might have meant "you can't do this".
- Are cross-backend operations a thing? Could they be?

### What version of ibis are you running?

5.1.0

### What backend(s) are you using, if any?

Pandas, I think?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
> * What does that error message mean? Could it be improved? It sounds like I needed to give Ibis more info but I think it might have meant "you can't do this".

It means "you can't do this" -- and it can certainly be improved.  One bump in the road here is that the notion of connecting to a backend makes a lot more sense when you're dealing with something that isn't an in-memory dataframe.

I'm also inclined to change the ibis for pandas users to use the DuckDB backend instead -- the point of that guide is show users how to spell Ibis operations, but there's no reason for them to then be using the pandas backend.

> Are cross-backend operations a thing? Could they be?

The short answer is no.

The long answer is sometimes, kind of.  For backends that have arrow support, we can do some things between backends by grabbing results in arrow format and shuffling them around.

**Comment by amoeba** [comment]
Thanks for the context @gil, I'll watch https://github.com/ibis-project/ibis/pull/6048 and I'm okay with closing this issue now.
