### ISSUE TITLE
feat(duckdb): should we error/warn when executing against an already exhausted RecordBatchReader?

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#6062]
Currently `con.read_in_memory` can register a table from a pyarrow `RecordBatchReader`. However, record batch readers are stateful objects (like reading a file/socket/...), only allowing a single pass over the data. Subsequent computations using the same table will result in either an error or (more likely) a result with 0 rows since the batch stream was already consumed.

```python
In [1]: import ibis

In [2]: import pyarrow as pa, pandas as pd

In [3]: df = pd.DataFrame({"x": range(10), "y": range(10, 20)})

In [4]: pyarrow_table = pa.Table.from_pandas(df)

In [5]: con = ibis.duckdb.connect()

In [6]: reader = pyarrow_table.to_reader()  # a RecordBatchReader

In [7]: t = con.read_in_memory(reader)

In [8]: t.schema()  # Schema is inferred properly
Out[8]: 
ibis.Schema {
  x  int64
  y  int64
}

In [9]: t.count().execute()  # First execution works fine
Out[9]: 10

In [10]: t.count().execute()  # Second execution is possibly unexpected
Out[10]: 0
```

If you have a firm understanding of how `pyarrow.RecordBatchReader`, `duckdb`, and `ibis` are fitting together here, then the above behavior makes sense. However, I've now seen 2 separate users tripped up by this behavior.

Is there a way that we could make subsequent executions against `t` warn that the `RecordBatchReader` has already been exhausted? Or should that be an error instead? I think this would be a nice way of informing the user of the issue without preventing streaming over a reader in cases where that's useful.

**Comment by cpcloud** [comment]
Is it possible to determine whether a `RecordBatchReader` is exhausted in a backend agnostic way?

Is the behavior any more surprising than the exhaustion of a stateful iterator?

**Comment by jcrist** [comment]
Ok, I've poked at this and I'm not sure if it's possible.

- It is possible to wrap a `RecordBatchReader` to issue a warning if anything tries to read it again after it's already been consumed. The code for this is simple and works fine in isolation.
- However, passing this wrapper to `con.read_in_memory` doesn't seem to trigger the warning on multiple executions. I haven't read the duckdb code, but after the `RecordBatchReader` has been consumed the first time, it seems like `duckdb` will never attempt to read from it again. `duckdb` "remembers" that the reader has already been consumed, it doesn't try to consume it again.

Given this, it seems like there's not an easy way to add warning at the execution level here. We can detect when the underlying reader has been consumed and stash this information somewhere, but we can't use this to warn in the `RecordBatchReader` itself. If we re-registered every time (like we do for `memtable`) we could make this work, but I'm not sure if the extra complication is worth it.

> Is this behavior any more surprising than the exhaustion of a stateful iterator?

I do think that the existing behavior is confusing to users who don't have a firm understanding of the internals. Two separate users have run into this issue in the last few weeks. It would have been nice if this was easily fixable, but since it seems a bit more complicated I'm not sure if adding a nice warning here is worth the complications.

**Comment by gforsyth** [comment]
> I do think that the existing behavior is confusing to users who don't have a firm understanding of the internals.

I agree with this.  I think, too, that if we start looking at sending things between backends via `pyarrow`, that this becomes more of an issue.  
If we've elided from users that we are using a `RecordBatchReader` (which, at this point, I don't think we have, but IF), then we can't expect them to guard against exhausting it.

This is also a spot where, even if you do know the internals, that `interactive` mode can unexpectedly bite you. Nothing unrecoverable, but if you are iterating on some Ibis code, it's not really feasible to turn on `interactive` mode if you've got a `RecordBatchReader` in the mix.

**Comment by cpcloud** [comment]
Yeah, I am definitely now on the side of "this can lead to hard to debug or confusing behavior".
