### ISSUE TITLE
SQLite: esoteric built-in spillover

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#607]
Functions not implemented as part of #596 
- changes (`wontfix`)
- char (plausible)
- glob (implausible, would accept PR)
- hex (plausible)
- last_insert_rowid (`wontfix`)
- likelihood (`wontfix`)
- likely (`wontfix`)
- quote (implausible)
- random (likely, and easy to implement)
- unicode (plausible)
- soundex (plausible)
- total_changes (`wontfix`)
- unlikely (`wontfix`)
- datetime (part of `needs love`/`timestamps`)
- date (part of `needs love`/`timestamps`)
- time (part of `needs love`/`timestamps`)
- julianday (plausible)

see also https://docs.google.com/spreadsheets/d/11x29cmCBSj1V18g0kpxjoeooP9mTcJnQxsD1ikq9njg/edit#gid=0

**Comment by cpcloud** [comment]
I've annotated the list of functions according to implementation plausibility. Closing for now.
