### ISSUE TITLE
SQLite: add REGEXP Python UDF

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#609]
per #595

**Comment by cpcloud** [comment]
One small issue here is that users must have a sqlite extension installed. There are a few to choose from it looks like:
* https://github.com/liteglue/sqlite3-pcre
* https://github.com/ralight/sqlite3-pcre
I suppose we could write our own, but that seems like scope creep.

**Comment by cpcloud** [comment]
For now we're using Python's UDF API for this. I'd be surprised if the overhead of Python objects was surpassed by slow regex performance. It might be useful to revisit this once there's a more efficient way to get result data into memory via arrow.

**Comment by cpcloud** [comment]
Added regex function support in #996
