### ISSUE TITLE
SQLite: Python UDF API

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#610]
related: #609

**Comment by datnamer** [comment]
This may provide some ideas: https://github.com/quinnj/SQLite.jl/blob/master/src/UDF.jl

**Comment by cpcloud** [comment]
This exists here: https://github.com/cpcloud/numbsql. Sorry for the shameless self-promotion, but honestly, there's no sane way to get a UDF into sqlite, so why not use an insane way?
