### ISSUE TITLE
feat(backend): oracle

### ISSUE THREAD

**Issue by fcarpentey75012** [ibis-project/ibis#6105]
### Is your feature request related to a problem?

Hello, 

I'm currently using pyodbc to connect to my Oracle SQL database and I see that for the moment the Ibis backends do not support Oracle, do you know if there is a solution to connect with pyodbc + Oracle and Ibis?

Thank you,

### Describe the solution you'd like

Connect Oracle SQL to Ibis

### What version of ibis are you running?

5.1.0

### What backend(s) are you using, if any?

Oracle SQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Implemented in #6126, thanks for the feature request!
