### ISSUE TITLE
bug: pivot_longer() doesn't support iterable of strings

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6115]
### What happened?

The docstring claims this should work, but it only works with a single str or a full fledged selector. 

PS I love the names pivot_wider and pivot_longer. So much better than the melt and explode. Thanks for adding this function, this would have been a doozy for me to implement myself.

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Seems easy enough to remove this part of the docstring!

**Comment by NickCrews** [comment]
But it SHOULD work with multiple columns, should the long term goal be to fix it the other direction?

**Comment by cpcloud** [comment]
It does work with multiple columns, you can use a selector!


```python
t.pivot_longer(s.c("a", "b", "c), ...)
```

**Comment by NickCrews** [comment]
Yeah, but I've managed to avoid selectors through the rest of my code, I am importing selectors just to use them in this one place.
