### ISSUE TITLE
bug: backend operation matrix not loading on website

### ISSUE THREAD

**Issue by keithbritt** [ibis-project/ibis#6122]
### What happened?

Spinning wheel of death when trying to access the ibis-project.org website backend operation matrix.

### What version of ibis are you using?

5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by keithbritt** [comment]
Another attempt displays spinning wheel of death with "App is booting"

**Comment by keithbritt** [comment]
Further investigation shows that when I try to access this page from Chrome, the Chrome browser has about a 400% increase in CPU utilization (relative to overall CPU  processing).

**Comment by cpcloud** [comment]
I rebooted it. Let us know if it's still not back up for you.

**Comment by keithbritt** [comment]
Confirmed: it is back up and running.

**Comment by cpcloud** [comment]
Thanks for reporting!
