### ISSUE TITLE
bug: Mismatch of dense_rank output between backends

### ISSUE THREAD

**Issue by mesejo** [ibis-project/ibis#6140]
### What happened?

After creating a new column with `dense_rank`, the order of the rows varies between DuckDB and Pandas.

The following code using DuckDB as a backend:
```python
import pandas as pd
import ibis

df = pd.DataFrame(
    {
        "a": [5, 6, 6, 5],
        "b": [1.0, 2.0, 3.0, 1.0],
    }
)

print(ibis.get_backend().name)
t = ibis.memtable(df)

res = t.mutate(group_id=t[t.columns[1]].dense_rank().over(ibis.window(order_by="b")))
print(res.execute())
```
produces:

```
duckdb
   a    b  group_id
0  5  1.0         0
1  5  1.0         0
2  6  2.0         1
3  6  3.0         2
```
Note that the output is sorted by `group_id` 

Now, using pandas:
```python
import pandas as pd
import ibis

df = pd.DataFrame(
    {
        "a": [5, 6, 6, 5],
        "b": [1.0, 2.0, 3.0, 1.0],
    }
)

ibis.set_backend("pandas")
print(ibis.get_backend().name)
t = ibis.memtable(df)

res = t.mutate(group_id=t[t.columns[1]].dense_rank().over(ibis.window(order_by="b")))
print(res.execute())
```
produces:
```
pandas
   a    b  group_id
0  5  1.0         0
1  6  2.0         1
2  6  3.0         2
3  5  1.0         0
```
The output is not sorted by `group_id`. 

There is TODO that seems to be associated with this issue (see [here](https://github.com/ibis-project/ibis/blob/5a013ffd3032e596a16a6a71476c2754f9bc9c8b/ibis/backends/pandas/execution/window.py#L533)), but I think it goes beyond that because the method `build_df_from_projection` is (re-)sorting by the index value (see [this](https://github.com/ibis-project/ibis/blob/5a013ffd3032e596a16a6a71476c2754f9bc9c8b/ibis/backends/pandas/execution/selection.py#LL265C1-L268C45)):

 ```python
    for i in range(len(new_pieces)):
        new_pieces[i] = new_pieces[i].sort_index()
        if len(new_pieces[i].index) == len(data.index):
            new_pieces[i].index = data.index
```

In any case,  if someone can point me in the right direction, I'll be happy to fix it 😄 

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

DuckDB
Pandas

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for opening the issue @mesejo!

I'm not sure this is a bug, since the order of rows isn't guaranteed to be the same across backends.

Is this causing a problem for you in some way?

**Comment by mesejo** [comment]
> Is this causing a problem for you in some way?
Not really, but I didn't phrase the problem correctly. The` order_by="b"` doesn't seem to have any effect when using pandas:
```python
res = t[t.columns[1]].dense_rank().over(ibis.window(order_by="b")).execute()
print(res)
```
produces:
```
0    0
1    2
2    0
3    1
Name: DenseRank(b), dtype: int64
```
even though the result is processed (internally) by the function `_post_process_order_by`.

Shouldn't the result be sorted by the `order_by` clause?

**Comment by cpcloud** [comment]
The `order_by` in a window function is distinct from the `order_by` method on tables. These two `order_by`s have no relationship to each other in general.

It may be the case that the database outputs rows in the order of the window's `order_by`, for example if it turns out to be more efficient and there's no further ordering constraints, but a window's `order_by` only constrains the order in which rows are consumed by the window function, not the order of the rows of the output table.

**Comment by mesejo** [comment]
Got it! Closing as this is not a bug 😅
