### ISSUE TITLE
bug: nulls in pandas DF's with type "string" parsed as "<NA>" in memtable()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6147]
### What happened?

See xfail test #6146 

Weirdly, if the dtype is simply `object`, then it works.

A workaround is converting to pyarrow table, then to memtable.

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This is an issue in duckdb that's already fixed upstream.

**Comment by cpcloud** [comment]
The next release of duckdb is this month, so you shouldn't have to wait too long!

**Comment by cpcloud** [comment]
> IDK if that has perf implications

It does 😂, we were doing something like this previously and it made memtable registration very very slow.

> ... or if the underlying buffers are zero-copied.

They are in some cases. Coming from pandas, only non-object dtype columns can _potentially_ be zero-copied. If the array is a strided view of another array my understanding is that you have to make a copy unless your system understands the buffer protocol.
