### ISSUE TITLE
feat(snowflake): connect to snowflake using existing snowpark session/client

### ISSUE THREAD

**Issue by jacques-n** [ibis-project/ibis#6153]
### Is your feature request related to a problem?

We use Ibis for a bunch of things. We also use Snowflake. The great news is that Ibis and Snowflake integration are really solid. However, we've been using more and more code inside Snowflake itself (in the Snowpark python env). Unfortunately, right now it is difficult to make use of Ibis inside Snowflake. We think we've gotten something working (hope to blog soon about it) but one problem we have is that Snowpark's [current_session()](https://docs.snowflake.com/ko/developer-guide/snowpark/reference/python/api/snowflake.snowpark.functions.current_session.html) can't be passed to Ibis as a connection for the Snowflake backend. 

Some people may ask why not just use Snowpark dataframe operations when inside Snowflake. It's a fair question. Unfortunately, having analysts need to learn multiple different data abstraction libraries is more work. Additionally, we're heavily invested in Substrait and Ibis's Substrait backend is super awesome.

### Describe the solution you'd like

We wish there was a way to just tell Ibis "use the snowpark session" to run your Snowflake operations.  Something akin to:
```
ibis.connect("snowflake://", snowpark_connection=current_session())
```

We're pretty sure that below the scenes Snowpark is using the python Snowflake connector that Ibis also uses so it seems like it is more glue than an entirely backend.

### What version of ibis are you running?

We'd run any version of Ibis to be able to do this.

### What backend(s) are you using, if any?

Snowflake and Substrait

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@jacques-n Thanks for the issue!

This has been requested elsewhere, so I think we can start looking into it.

You're right that this probably wont be an entirely new backend, but a way to instantiate a snowflake backend from a snowpark session.

**Comment by cpcloud** [comment]
Closing this for now. We're still interested in it, but it's not a priority at the moment.
