### ISSUE TITLE
bug: backend operations matrix page crashing again

### ISSUE THREAD

**Issue by keithbritt** [ibis-project/ibis#6170]
### What happened?

When trying to access the backend operations matrix via ibis-project.org, it fails with the message:

ibis-project.streamlit.app redirected you too many times.

### What version of ibis are you using?

5.0

### Relevant log output

```sh
ibis-project.streamlit.app redirected you too many times.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I can't reproduce this, it shows up for me just fine in both the docs page and on the streamlit domain.

> ibis-project.streamlit.app redirected you too many times.

This looks like a client-related issue and not like an issue on the streamlit side.

**Comment by cpcloud** [comment]
Hm, I'm not sure what we can do about this, especially since it appears to be a streamlit issue.

**Comment by keithbritt** [comment]
FYI... I tried loading the backend operations matrix with Microsoft Edge (I'm told that's a web browser *sarcasm*) and it loads fine, but it still fails when trying to use Chrome.

**Comment by ogrisel** [comment]
I get a different error message from firefox:

```
Oh no.

Error running app. If this keeps happening, please [contact support](https://github.com/ibis-project/ibis/issues/new).
```

**Comment by cpcloud** [comment]
I think we may move back to the original table we had previously. While the streamlit app is nice, we aren't really willing to field issues about it not working for reasons out of our control, including various decisions that platforms/browsers make.

That said, we still appreciate the heads up!
