### ISSUE TITLE
feat: Limited `Table[Schema]` type annotation support

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6173]
Thanks for considering this.

```python
from ibis.expr.types import Table

class Person:
    name: str
    age: int

def is_adult(t: Table[Person]):
    # tab completion, syntax highlighting, better API documentation
    # because we know that `t` has an column `age` of type int
    return t.age > 18.
```

From https://github.com/ibis-project/ibis/issues/5410, we can't use type annotations to reason about runtime operations that modify the schema, such as `select` or `mutate`, but this would allow tab completion, syntax highlighting, and better API documentation, which honestly is more what I care about than mypy checking.

_Originally posted by @NickCrews in https://github.com/ibis-project/ibis/issues/5410#issuecomment-1430375491_

**Comment by jcrist** [comment]
> but this would allow tab completion

I'm assuming you're talking about static tab completion in your editor, as opposed to tab completion in a running python session (which already works). With the syntax you've provided above, this would only be possible with a `mypy` plugin,which is not something I think we're interested in maintaining.

> syntax highlighting

What do you mean by this? How would this affect syntax highlighting? Does your editor highlight differently based on `mypy`/`pyright` type information?

> better API documentation

Can you say more about what you mean by this?

If all you're looking for is a way to include the schema of `Table` args somewhere in the type hints to a function for personal reference, you could also do the following today with no extra effort from the `ibis` team (and without breaking `mypy` annotations as they currently exist):

```python
from typing import Annotated as WithSchema

from ibis.expr.types import Table

class Person:
    name: str
    age: int

# This just includes the `Person` object in the type signature, it has no runtime or type-analysis benefits
def is_adult(t: WithSchema[Table, Person]):
    return t.age > 18.
```

**Comment by NickCrews** [comment]
> static tab completion in your editor

Yes.

> How would this affect syntax highlighting? Does your editor highlight differently based on mypy/pyright type information?

If I use `x: list[str]`, then my editor (VSCode) understands that `x[0].upper` exists, highlights it differently, adds quick lookup, refactorings, etc etc. I believe that VScode uses pyright, not mypy, and I didn't purposefully install any additional plugins besides the most basic [VSCode python plugin](https://marketplace.visualstudio.com/items?itemName=ms-python.python). I therefore assumed that this was builtin functionality with typing. I thought you meant that plugins were required only for `.mutate`, `.select`, etc.

> better API documentation

This type hint will show up in generated documentation ie from mkdocstrings. Ideally it could be a link, but even if it is just a plain string it still is useful for readers of the docs.

I think that workaround will be adequate! I will check it out and report back.

**Comment by cpcloud** [comment]
@NickCrews Any updates here? Were you able to try out the workaround?

**Comment by cpcloud** [comment]
Closing this out! Please open a new issue if you're not able to get what you want!
