### ISSUE TITLE
feat: support PyArrow Dataset and Table in datafusion register function

### ISSUE THREAD

**Issue by wjones127** [ibis-project/ibis#6176]
### Is your feature request related to a problem?

DataFusion Python supports registering PyArrow datasets through the `register_dataset()` method. It would be nice if that was passed through the `con.register()` method. We support this in the DuckDB backend, although that might be by accident 😉.

### Describe the solution you'd like

Handle `source` types other than string, including `pyarrow.dataset.Dataset` and `pyarrow.Table`.

https://github.com/ibis-project/ibis/blob/63db64333e0a7a178008663657fec7fa2425c439/ibis/backends/datafusion/__init__.py#L103-L105

### What version of ibis are you running?

5.1.0

### What backend(s) are you using, if any?

Datafusion

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kszucs** [comment]
I agree, it should be fairly easy to implement. Thanks @wjones127 for the suggestion!

**Comment by cpcloud** [comment]
Supporting pyarrow Datasets and Tables in the DuckDB was never an accident :)

This would be a nice improvement for sure.

Ideally this issue doesn't stay open forever.

**Comment by wjones127** [comment]
> Supporting pyarrow Datasets and Tables in the DuckDB was never an accident :)

Oh good to know. I assumed datasets weren't since they aren't included in the type hint here

https://github.com/ibis-project/ibis/blob/3a590b75bfc71822e8bf441eacf0cbbd84372f05/ibis/backends/duckdb/__init__.py#L398-L402

If Krisztián isn't already looking at it, I'll look at tackling this in the next week or two.
