### ISSUE TITLE
bug:  BigQuery install fails due to protobuf version conflict

### ISSUE THREAD

**Issue by kenneth-copeland** [ibis-project/ibis#6180]
### What happened?

>pip install ibis-framework[bigquery]

fails due to conflicts with protobuf 3.20.1

seems that 'google-cloud-bigquery' explicitly prohibits 3.20.1

### What version of ibis are you using?

Multiple versions including 5.1.0

### What backend(s) are you using, if any?

bigquery

### Relevant log output

```sh
(ibis) ken::~/dev/ibis-examples$ pip install ibis-framework[bigquery]
Collecting ibis-framework[bigquery]
  Using cached ibis_framework-5.1.0-py3-none-any.whl (1.4 MB)
Requirement already satisfied: atpublic<4,>=2.3 in /home/ken/miniconda3/envs/ibis/lib/python3.11/site-packages (from ibis-framework[bigquery]) (3.1.1)
.
.
.
Requirement already satisfied: oauthlib>=3.0.0 in /home/ken/miniconda3/envs/ibis/lib/python3.11/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.0->pydata-google-auth<2,>=1.4.0->ibis-framework[bigquery]) (3.2.2)
Installing collected packages: protobuf, ibis-framework
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.1
    Uninstalling protobuf-3.20.1:
      Successfully uninstalled protobuf-3.20.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ibis-substrait 2.18.0 requires protobuf==3.20.1, but you have protobuf 4.23.0 which is incompatible.
Successfully installed ibis-framework-5.1.0 protobuf-4.23.0
(ibis) ken::~/dev/ibis-examples$
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @kenneth-copeland 👋🏻! Thanks for opening an issue.

I'm not sure I understand whether this failed or not.

First there's this message:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ibis-substrait 2.18.0 requires protobuf==3.20.1, but you have protobuf 4.23.0 which is incompatible.
```

But that's immediately followed by

```
Successfully installed ibis-framework-5.1.0 protobuf-4.23.0
```

It also looks like you have `ibis-substrait` installed, and yeah, that won't be compatible with `ibis-framework[bigquery]` for the reason stated in the `pip` error message.

1. Are you able to execute any ibis expressions using the BigQuery backend even though the install "failed" (it seems like it may not have)
2. Are you trying to use both ibis-bigquery and ibis-substrait in the same environment for a specific reason, or did you just happen to reuse the same environment?

**Comment by kenneth-copeland** [comment]
So, It is possible that this is not truly an error if protobuf is backwards compatible,  I will do some more testing to see if it actually works OK.  While I am a seasoned developer, I am a relative newbie to the python ecosystem, so sorry if this a bogus bug report.  I swear the my previous attemprs to build failed outright, but I could be wrong.  I definitely had failure when I tried to install the packages with conda.

IBIS looks really awsome, and I was just going through the tutrorial to investigate it.

All I really was trying to do was add the 'postgres' and 'bigquery' backends in requirements.txt and ran into problems.  

I did not explicitly install ibis-substrait or substrait packages.  That was alreday included to the requirements.txt for the tutorial.

Should I expect that different back-ends, and packages that are presumebly required for them would cause conflicts when used together?  Should I be worried about running a PROD environment with pack dependency errors?  Or is that typically OK ... ?
 
And thanks for the quick resonse.

**Comment by kenneth-copeland** [comment]
Sorry, I never said that I was running though the examples in [https://github.com/ibis-project/ibis-examples](url)

**Comment by anjakefala** [comment]
I just wanted an issue reference that I am running into this also when trying to install `ibis-framework[bigquery]` and `ibis-substrait` in the same environment:

```
    ibis-substrait 2.14.1 depends on protobuf==3.20.1
    google-cloud-bigquery 3.10.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
```

Going to review the recommendations in the thread.

**Comment by cpcloud** [comment]
Interesting. The Python 3.11-only fact is quite strange.

I think for now the recommendation is "don't install them into the same environment".

The actual solution is for us to loosen the version bounds of protobuf in `ibis-substrait`.

**Comment by kenneth-copeland** [comment]
Sorry, yes I meant 'package dependency'.  

I did a little investigation of the ibs-substrait and substrait github repos, and i looks like that ibis-substrait team is pinning their protobuf version constraints to the exact same version used by the 'substrait' project.  I saw at least one issue thread that indicated they might be able to relax that tight coupling.

I assume that both of those projuects could be updated to a newer version of protobuf that is NOT explicitly forbidden by google-cloud-bigquery.  I have no idea what the impact of updating the protobuf version in those 2 projects would be.

**Comment by kenneth-copeland** [comment]
I actually didn't see cpcloud's comment above before I commented.

**Comment by cpcloud** [comment]
I think we may be able to loosen the ibis-substrait bound without needing to change `substrait`. @gforsyth will have a better idea here.

**Comment by gforsyth** [comment]
Currently we're pretty strict re: the `protobuf` pins in `ibis-substrait`.  We _do_ need to make sure we're using `3.20.1` when we have to regenerate the `pb2` files, but once the file generation bit is handled by the new `python-substrait` package upstream we can definitely relax that.  I can push on that a bit this week and next.

**Comment by gforsyth** [comment]
I've relaxed the version pins for the `google.protobuf` package in `ibis-substrait` and once the next release is out this issue should be resolved (that should be quite soon).

**Comment by anjakefala** [comment]
Thank you! That's wonderful news. =)

**Comment by gforsyth** [comment]
```shell
$ pip install 'ibis-framework[bigquery]' ibis-substrait
Collecting ibis-framework[bigquery]
  Downloading ibis_framework-5.1.0-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 2.0 MB/s eta 0:00:00
Collecting ibis-substrait
  Downloading ibis_substrait-2.28.2.tar.gz (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 9.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
<snip>
Successfully built ibis-substrait
Installing collected packages: sqlglot, pytz, xxhash, urllib3, tzdata, typing-extensions, tqdm, toolz, six, pyyaml, pygments, pyasn1, protobuf, platformdirs, parsy, packaging, oauthlib, numpy, mdurl, idna, grpcio, google-crc32c, charset-normalizer, certifi, cachetools, bidict, atpublic, rsa, requests, python-dateutil, pyasn1-modules, pyarrow, proto-plus, multipledispatch, markdown-it-py, googleapis-common-protos, google-resumable-media, rich, requests-oauthlib, pooch, pandas, grpcio-status, google-auth, google-auth-oauthlib, google-api-core, db-dtypes, pydata-google-auth, ibis-framework, google-cloud-core, ibis-substrait, google-cloud-bigquery-storage, google-cloud-bigquery
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
protoletariat 1.0.1 requires click<9,>=7.1.2, which is not installed.
Successfully installed atpublic-3.1.1 bidict-0.22.1 cachetools-5.3.0 certifi-2023.5.7 charset-normalizer-3.1.0 db-dtypes-1.1.1 google-api-core-2.11.0 google-auth-2.18.0 google-auth-oauthlib-1.0.0 google-cloud-bigquery-3.10.0 google-cloud-bigquery-storage-2.19.1 google-cloud-core-2.3.2 google-crc32c-1.5.0 google-resumable-media-2.5.0 googleapis-common-protos-1.59.0 grpcio-1.54.2 grpcio-status-1.54.2 ibis-framework-5.1.0 ibis-substrait-2.28.2 idna-3.4 markdown-it-py-2.2.0 mdurl-0.1.2 multipledispatch-0.6.0 numpy-1.24.3 oauthlib-3.2.2 packaging-23.1 pandas-2.0.1 parsy-2.1 platformdirs-3.5.1 pooch-1.7.0 proto-plus-1.22.2 protobuf-4.23.0 pyarrow-12.0.0 pyasn1-0.5.0 pyasn1-modules-0.3.0 pydata-google-auth-1.8.0 pygments-2.15.1 python-dateutil-2.8.2 pytz-2023.3 pyyaml-6.0 requests-2.30.0 requests-oauthlib-1.3.1 rich-13.3.5 rsa-4.9 six-1.16.0 sqlglot-11.7.1 toolz-0.12.0 tqdm-4.65.0 typing-extensions-4.5.0 tzdata-2023.3 urllib3-1.26.15 xxhash-3.2.0
```

```shell
$ python -c "import ibis; print(ibis.__version__)"
5.1.0
$ python -c "import ibis_substrait; print(ibis_substrait.__version__)"
2.28.2
```

Thanks again for the report @kenneth-copeland!  Closing this out.

**Comment by kenneth-copeland** [comment]
Thanks for such a quick quick turnaround on this issue.
