### ISSUE TITLE
bug: Postgres transactions fail when `_CREATE_FIRST_LAST_AGGS_SQL` can not execute

### ISSUE THREAD

**Issue by dantegates** [ibis-project/ibis#6271]
### What happened?

Transactions with Redshift are failing with a Syntax error, e.g. the `connection.table()`, `connection.list_tables()` methods, etc. While I'm seeing the issue on Redshift it looks like it might be a more general error for Postgres users as well who don't have permissions to create functions as the exception is caught and user warning issue, but it seems like the cursor is not being cleaned up properly.

From what I can gather it seems that after upgrading from v4.xx to 5.1 this PR might be what is causing the error: #5780, specifically the `receive_before_execute` and `receive_after_execute` methods.

If I patch the first last aggs statements to empty strings as follows the code works as expected

```python
with mock.patch('ibis.backends.postgres._CREATE_FIRST_LAST_AGGS_SQL', ''), \
          mock.patch('ibis.backends.postgres._DROP_FIRST_LAST_AGGS_SQL', ''):
    connection.table(...)
```

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

Postgres as an interface to Redshift

### Relevant log output

```sh
UserWarning: Unable to create first/last aggregates: syntax error at or near "PARALLEL"
LINE 3: LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS
                                      ^

  warnings.warn(f"Unable to create first/last aggregates: {e}")
---------------------------------------------------------------------------
InFailedSqlTransaction                    Traceback (most recent call last)
~/virtualenvs/v3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1904                 if not evt_handled:
-> 1905                     self.dialect.do_execute(
   1906                         cursor, statement, parameters, context

~/virtualenvs/v3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    735     def do_execute(self, cursor, statement, parameters, context=None):
--> 736         cursor.execute(statement, parameters)
    737 

InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@dantegates Welcome! Thanks for the issue.

Looks like a bug :)

Slated for 6.0.

**Comment by cpcloud** [comment]
This is fairly easy to reproduce by intentionally introducing a syntax error into the postgres backend.
