### ISSUE TITLE
Question: How to perform chained mulitple joins/left joins?

### ISSUE THREAD

**Issue by pybokeh** [ibis-project/ibis#6276]
### What happened?

I looked at the documentation for performing multiple [joins](https://ibis-project.org/ibis-for-sql-programmers/#multiple-joins) but the example provided was confusing to me, so I resorted to trial and error.  I can do a single join fine, but when I try 2 chained joins, I get an error.  I tried without and with the "_." syntax, but still getting the same error.  But what is strange, I can sort of get it to work by doing a single join first, material the table or projection based on the single join, then when I perform 2 chained joins again, it then works fine.  Otherwise, I can just do the joins without chaining with intermediary results fine.  It's when I try to perform multiple joins in a chained manner, is when I am having issues.  I'm sure it is because there are some fundamentals of ibis that I am missing.  I have posted in [gitter](https://matrix.to/#/!qFaqnPAXbybqIpOgEf:gitter.im/$m8TD7sTCGuRVOQPK-wDrYH3zdBzBhSrXq4AqpLrUTVU?via=gitter.im&via=matrix.org&via=matrix.freyachat.eu) also.

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

PostgreSQL 15.2

### Relevant log output

See code cell # 9 in my jupyter notebook: https://github.com/pybokeh/data-sets/blob/main/us-population/ibis_workflow.ipynb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
hi @pybokeh, I believe you're just missing the import -- e.g. `from ibis import _` or `import ibis.deferred as _` or using `ibis._`

it would work in the second example because you've output `temp` and by default (in iPython? Jupyter? both?) that defaults to the wrong character

(I could be wrong here, someone more experienced will probably weigh in soon)

**Comment by pybokeh** [comment]
That was it thanks @lostmygithubaccount !

**Comment by lostmygithubaccount** [comment]
awesome! happy Ibis-ing
