### ISSUE TITLE
feat:  PySpark DataFrame to Ibis table conversion to avoid OOM error

### ISSUE THREAD

**Issue by RomuloDrumond** [ibis-project/ibis#6280]
### Is your feature request related to a problem?

Yes, the feature request mentioned is related to a problem involving Out-of-Memory (OOM) errors. The specific issue is related to converting a PySpark DataFrame to an Ibis table using Pandas, which results in OOM errors.

### Describe the solution you'd like

To address the problem and prevent OOM errors, one can consider alternative approaches that avoid collecting the entire DataFrame onto the driver node. Instead of using Pandas to convert the DataFrame, one can explore options within Ibis or PySpark to directly convert the DataFrame to an Ibis table without collecting all the data on the driver node.

### What version of ibis are you running?

3.2.0

### What backend(s) are you using, if any?

PySpark

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hi @RomuloDrumond !  Could you explain a little more what you're trying to do when you have OOM errors?

An Ibis table is mostly an abstraction -- except for in-memory tables (`memtable`) it doesn't hold any data, but represents the schema of a table that exists in one or more backends.

If you are having trouble when calling `execute`, one option is to upgrade `ibis` and then take advantage of the `to_parquet` or `to_pyarrow` methods on your table expression to collect your results in something besides a Pandas dataframe.

**Comment by RomuloDrumond** [comment]
Hi @gforsyth! I'm trying to use Ibis with PySpark backend without needing to register tables on the Hive Metastore. Using tables registered on it is easy as calling the below code:

```python
ibis_table = con.table(name=<table-name>, database=<database-name>)
```

But when I want to use Ibis for ad-hoc analysis I might not want to be registering tables on databases (i.e. using `read_csv` or `read_parquet` methods). The only way I've found to use PySpark backend without registering tables on the metastore was to load them in Pandas and pass it as a memory table to Ibis. There is a way to use PySpark direct on files? Does it makes sense for Ibis or does this deviate to the idea of the library?

(Note: Writing using Spark the final output of my analysis is easy as I can call `.compile()` and get back a pyspark.DataFrame, what I would like is the inverse of this capability: read a pyspark.DataFrame from file and convert it to an ibis expression)

**Comment by RomuloDrumond** [comment]
Hey, thanks for the help! Got it working after your observations. If I register the table as a temporary view I can see it with the Spark session, below goes a piece of code that does that:

```python
import ibis
from pyspark.sql import SparkSession

session = SparkSession.builder.getOrCreate()
parquet_file_path = "path/to/fancy/file.parquet"
df = spark.read.parquet(parquet_file_path)
df.createOrReplaceTempView("fancy_view")

con = ibis.pyspark.connect(session)
ibis_table = con.table(name="fancy_view")
print(f"{ibis_table = }") # here you can see the table

psdf = ibis_table.compile() # you also can go back to PySpark
display(psdf)
```

**Comment by gforsyth** [comment]
Great!  I'm glad that's working.  

This _should_ also work if you are using the latest version of Ibis:

```python
import ibis
from pyspark.sql import SparkSession

session = SparkSession.builder.getOrCreate()
con = ibis.pyspark.connect(session)

ibis_table = con.read_parquet("path/to/fancy/file.parquet", table_name="fancy_view")
print(f"{ibis_table = }")
```
