### ISSUE TITLE
feat: ibis.expr.rules.binary needed

### ISSUE THREAD

**Issue by kesmit13** [ibis-project/ibis#6282]
### Is your feature request related to a problem?

This issue is really more of a question. I'm wondering why there isn't a binary type in the ibis.expr.rules package. We are using arguments to functions that are binary columns and I'm specifying them as strings now, but I wasn't sure if there was a reason why binary wasn't an option.

### Describe the solution you'd like

Presumably, just add `binary = value(dt.binary)` to `ibis.expr.rules`.

### What version of ibis are you running?

5.1

### What backend(s) are you using, if any?

SingleStoreDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I think the main thing is a docker image that allows testing against singlestore. It seems like that exists, so since the implementation is there the bulk of the work is likely in xfailing the various tests.

**Comment by kesmit13** [comment]
I'm making a bunch of additions to the SingleStoreDB backend right now which need a fair amount of testing. I'll see what changes I need to make in our testing setup to match up with yours. Once I get that finished, I'll check back.
