### ISSUE TITLE
feat(snowflake): support a timezone in `to_timestamp` from a string expression

### ISSUE THREAD

**Issue by nagydavid** [ibis-project/ibis#6292]
### What happened?

I have the following query towards our snowflake db.

```
table = db.table(cfg.table)

condition = (
    (table.ASSET_NAME == id) &
    (table.MODEL_NAME == model_type) &
    (table.TIMESTAMP.between(start_date, end_date))
)

table_filtered = table.filter(condition)

table_subset = table_filtered[["TIMESTAMP", "ASSET_NAME", "INFERENCE_PERIOD", "FORECAST_MEAN","FORECAST_LOW_80","FORECAST_LOW_95", "FORECAST_HIGH_80", "FORECAST_HIGH_95"]]

table_subset_mutated = table_subset.mutate(TIMESTAMP=table_subset.TIMESTAMP)

table_split= table_subset.mutate(forecast_end_period = table_subset.INFERENCE_PERIOD.split("_")[1].replace("T", " "))

table_mutated = table_split.mutate(forecast_end_period = table_split.forecast_end_period.to_timestamp('YYYY-MM-DD HH24-MI-SS'))

table_grouped = table_mutated.group_by(table_mutated.TIMESTAMP).aggregate(table_mutated.forecast_end_period.max())

table_grouped = table_mutated.aggregate(table_mutated.forecast_end_period.max().name("latest_forecast"), by=table_mutated.TIMESTAMP)

table_joined = table_mutated.join(table_grouped, 
                                    [table_mutated.TIMESTAMP == table_grouped.TIMESTAMP ,
                                    table_grouped.latest_forecast == table_mutated.forecast_end_period],
                                    how="inner")

ibis.show_sql(table_joined)
```
I have 3 issue and 1 might be a bug.

1.  the `TIMESTAMP` column is a TIMESTAMP_NTZ , I cannot find any reference how to move it to TIMESTAMP_TZ like UTC.
2.  when I am creating the `forecast_end_period` from a STRING, using the `to_timestamp()` method, it automatically assumes UTC, and I cannot even specify anything else.
3. 
4. (Possible bug) I see that Ibis has a logic to transform different TZ  implicitly, but the` ibis.show_sql() `show a different query what the `.execute()` issues towards snowflake.

Here is the difference:
from `ibis.show_sql(): 
```
.....
CAST(
  CONVERT_TIMEZONE('UTC', t3."forecast_end_period") AS TIMESTAMPNTZ
) AS "forecast_end_period"
.....
```
whereas `.execute()`:
```
.....
CAST(
    t3."forecast_end_period" AT TIME ZONE 'UTC' AS TIMESTAMP_NTZ
) AS "forecast_end_period"
.....
```
 the AT TIME ZONE fails on snowflake as it doesnt understand the syntax.

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

snowflake

### Relevant log output

```sh
Syntax error: unexpected 'AT'. (line 15) from SNOWFLAKE
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @nagydavid! Welcome, and thanks for the issue!

I think your assessment is right on point and I agree it sounds like there are 3 separate issues here:

1. You'd like to be able to introduce a timezone to `TIMESTAMP_NTZ` values.
2. You'd like to be able to specify the timezone when converting a string to a `TIMESTAMP_TZ`.
3. Implicit conversion to UTC fails because we're generating incorrect code.

I think we can get to number 3 by 6.0, but 1 and 2 may need to wait for a feature release (6.1).

In any event this is great feedback, keep it coming!

**Comment by cpcloud** [comment]
#6295 is merged, you shouldn't see the `AS TIME ZONE` syntax error anymore!

**Comment by nagydavid** [comment]
Hi @cpcloud, thank you for the bug fix, actually the fix work as intended, although now every time I executing a query, I am getting the following 
`[1]    18001 segmentation fault  /Users/xxxxx/Documents/xx/.venv/bin/python `

I am using python 3.9.0.

:(

**Comment by cpcloud** [comment]
Converted this to a feature request since the bug mentioned here is fixed.

**Comment by cpcloud** [comment]
Pushing this off of the 7.2 milestone. @nagydavid if you're still interested in this please let us know!
