### ISSUE TITLE
dev: contributing instructions don't appear to be working on macOS

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#6299]
### Is your feature request related to a problem?

I followed the "conda / mamba" and "pip" instructions on my mac, and in both I'm unable to even get `pytest -m core` tests to run.

```
'spark' not found in `markers` configuration option
```

If I manually try to run the BigQuery tests, it appears the entrypoints aren't populated.

```
$ pytest ibis/backends/bigquery
======================================== test session starts ========================================
platform darwin -- Python 3.10.11, pytest-7.3.1, pluggy-1.0.0
Using --randomly-seed=2869571017
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/swast/src/github.com/ibis-project/ibis
configfile: pyproject.toml
plugins: snapshot-0.9.0, mock-3.10.0, clarity-1.0.1, randomly-3.12.0, hypothesis-6.75.3, httpserver-1.0.7, profiling-1.7.0, xdist-3.3.1, cov-4.0.0, repeat-0.9.1, benchmark-4.0.0
collected 133 items / 1 error

============================================== ERRORS ===============================================
________________ ERROR collecting ibis/backends/bigquery/tests/unit/test_compiler.py ________________
ibis/backends/bigquery/tests/unit/test_compiler.py:14: in <module>
    to_sql = ibis.bigquery.compile
ibis/__init__.py:58: in __getattr__
    raise AttributeError(msg)
E   AttributeError: module 'ibis' has no attribute 'bigquery'.
====================================== short test summary info ======================================
ERROR ibis/backends/bigquery/tests/unit/test_compiler.py - AttributeError: module 'ibis' has no attribute 'bigquery'.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 1 error in 0.68s ==========================================
```

### Describe the solution you'd like

Seems to be working fine on Linux. But even when I manually try to call `ibis.bigquery.connect` on macOS, it doesn't appear to work locally in my development environment either.

### What version of ibis are you running?

HEAD

### What backend(s) are you using, if any?

BigQuery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Perhaps a naive question but are you sure you have you installed `ibis` in the new environment? The entrypoints are only visible when the package is installed:

```
pip install -e .[bigquery]
```

**Comment by gforsyth** [comment]
We removed the `spark` marker quite some time ago -- this might be a weird pytest caching thing?

**Comment by tswast** [comment]
> We removed the spark marker quite some time ago -- this might be a weird pytest caching thing?

Could be. I removed everything I could find `*.pyc` files, `.pytest_cache`, and `__pycache__`. Still no luck. I'll try with a completely fresh clone and environment.

**Comment by tswast** [comment]
Working fine with a completely fresh environment and clone of the repo. No idea what state was leftover that was breaking it, but thankfully have it working now.
