### ISSUE TITLE
feat: Documentation for MSSQL connection, and others

### ISSUE THREAD

**Issue by valtterivalo** [ibis-project/ibis#6306]
### Is your feature request related to a problem?

I have no clue how to work the connection parameters to recreate the connection I create over Microsoft SQL Server Management Studio.

It looks like this:
![image](https://github.com/ibis-project/ibis/assets/108878090/13825ba4-c466-46b4-b0a6-6708c2c94b58)

Whereas this is what I'm trying to do programmatically:
![image](https://github.com/ibis-project/ibis/assets/108878090/00800c57-9f14-4eb5-9fe4-9254c2dcfdb0)

### Describe the solution you'd like

I'd like some documentation that gives a better sense of actual business cases and not just local tinkering. I can run the exact same database connection using pyodbc without much hassle, but due to lack of documentation I simply have no idea what I should be doing here.

### What version of ibis are you running?

ibis-framework==5.1.0

### What backend(s) are you using, if any?

MSSQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by valtterivalo** [comment]
Hey,
Here's an example of a connection made through pyodbc:
`# Connection parameters
DRIVER = 'SQL SERVER'
SERVER_NAME = 'MGKIVMTIRA,1433\MTIRA'
DATABASE_NAME = 'TIPSRA_ODS_MNT'
# Connection string
conn_str = f'''
DRIVER={{{DRIVER}}};
SERVER={SERVER_NAME};
DATABASE={DATABASE_NAME};
Trusted_Connection=yes;

# SQL query string .....

conn = pyodbc.connect(conn_str)
cur = conn.cursor()
cur.execute(sql_query)
'''`

This allows me to access the database and perform any queries through these SQL strings.

**Comment by gforsyth** [comment]
Hey @valtterivalo -- 

I have two things to try:

1. In your example using ibis with `pymssql` above, you only pass `MGKIVMTIRA` as the hostname, can you try passing the full `MGKIVMTIRA,1433\MTIRA`?

2. If that doesn't work, can you try connecting using `pyodbc` (or any working connection mechanism) and run this SQL snippet?  It should retrieve a fully qualified domain name for the server that you can then use as the argument to `host=`:
```sql
DECLARE @Domain NVARCHAR(100)
EXEC master.dbo.xp_regread 'HKEY_LOCAL_MACHINE', 'SYSTEM\CurrentControlSet\services\Tcpip\Parameters', N'Domain',@Domain OUTPUT
SELECT Cast(SERVERPROPERTY('MachineName') as nvarchar) + '.' + @Domain AS FQDN
```

**Comment by gforsyth** [comment]
Closing as stale -- please comment if we can help more.
