### ISSUE TITLE
docs: Create 'How to Get Data Out of Ibis' How To Guide

### ISSUE THREAD

**Issue by amoeba** [ibis-project/ibis#6307]
Ibis has a lot of documentation covering how to query data but not so much on how to get the results of queries _out_ of Ibis. At present, a user could find the documentation for their backend and piece this together but I think a higher-level guide that provides a reader with a good mental model would be useful.

My metal model at the moment is that the user can essentially:

- Call `execute()` to bring the result set into Python and use pandas' or other serialization routines
- Write the Table back to the backend and do the remainder of the work outside of Ibis
- Hope their backend has a utility function (like the DuckDB backend's array of `to_*` functions) for getting data out to disk

Part of what motivated this was a question around getting data out of Ibis and into cloud storage so that might be good to cover in this guide as well.

**Comment by cpcloud** [comment]
We have a how-to guide for this now: https://ibis-project.org/how-to/input-output/basics#file-formats
