### ISSUE TITLE
bug: README's `con.tables` doesnt work

### ISSUE THREAD

**Issue by AbdealiLoKo** [ibis-project/ibis#6312]
### What happened?

I was trying ibis for the first time - got it installed and tried running the commands in the readme.

The `con.tables` command throws an error

### What version of ibis are you using?

2.1.1

### What backend(s) are you using, if any?

sqlite

### Relevant log output

```sh
In [2]: import ibis

In [3]: ibis.options.interactive = True

In [4]: !curl -LsS -o geography.db 'https://storage.googleapis.com/ibis-tutorial-data/geography.db'

In [5]: con = ibis.sqlite.connect("geography.db")

In [6]: con.tables
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-a5367fc75c4c> in <module>
----> 1 con.tables

AttributeError: 'Backend' object has no attribute 'tables'
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbdealiLoKo** [comment]
I was looking at the pypi page and realized that the latest version of ibis is 5.1.0 and I had 2.1.1
Looks like an older version got installed with `pip install ibis-framework` because I was using py 3.7 ....

So, closing this as an expected behavior

**Comment by cpcloud** [comment]
Thanks for raising the issue! Yeah, we added `con.tables` after 2.1.1, glad you were able to resolve it quickly!
