### ISSUE TITLE
bug: `pivot_longer` doesn't work with field names containing spaces

### ISSUE THREAD

**Issue by wleescor** [ibis-project/ibis#6326]
### What happened?

when using pivot_longer, the names_to field and values_to arguments can't have a space in them

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

DuckDB

### Relevant log output

```sh
>>> import ibis
>>> import ibis.selectors as s
>>> from ibis import _
>>> ibis.options.interactive = True
>>> relig_income = ibis.examples.relig_income_raw.fetch()
>>> relig_income.pivot_longer(~s.c("religion"), names_to="in come", values_to="my count")

This produces a ParserException: Parser Error: syntax error at or near "in"
LINE 2: ...e" := ?, "my count" := t1."$100-150k"), struct_pack("in come" := ?, "my count"...

This can be fixed by removing the space, but would be nice to at least fix the error message or documentation to say there should be no spaces in the names and values
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@wleescor Welcome! 👋🏻 

Thanks for the report and the easy-to-reproduce failure!

Slated for 6.0.

**Comment by cpcloud** [comment]
The error appears to be in the `STRUCT` part of the `CAST` expression we're generating:

```
STRUCT(in come TEXT, my count BIGINT)[]
```

should be

```
STRUCT("in come" TEXT, "my count" BIGINT)[]
```
