### ISSUE TITLE
bug: make version from source install different than current release

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#6346]
### What happened?

when you install from source via cloning and `pip install /local/dir/ibis` or `pip install git+https://github.com/ibis-project/ibis.git@master`, the version shows as `5.1.0`, which can make it mildly annoying to distinguish between an install from PyPi and from source

not sure if this is a standard practice we can follow for this or if there are any concerns with changing the behavior

### What version of ibis are you using?

5.1.0/master

### What backend(s) are you using, if any?

n/a

### Relevant log output

```sh
(venv) cody@laptop: pip list | grep ibis
ibis-framework     5.1.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
or nightly releases could solve this? feel free to close out

**Comment by gforsyth** [comment]
There's https://github.com/mtkennerly/poetry-dynamic-versioning which we tried using a while back -- I can't remember why we stripped it out, but there was something that wasn't working well.

I think the remaining issue with that package (or really with older versions of `pip`) is that unless a user is using a sufficiently new version of `pip`, then the install builds the package in an isolated directly (sans git history) and so can't determine the version.

I think nightly pre-releases (or some cadence of pre-releases) would help, but I'm game for us to try either.

**Comment by cpcloud** [comment]
Hm, before we do that, lemme see if I can get it to work.

**Comment by gforsyth** [comment]
I think we just need to change the `build-backend`:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index ce71b74cc..c537d86c0 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -500,4 +500,4 @@ pattern = '^(?P<base>\d+(\.\d+)*)'
 
 [build-system]
 requires = ["poetry-core>=1.1.0", "poetry-dynamic-versioning"]
-build-backend = "poetry.core.masonry.api"
+build-backend = "poetry_dynamic_versioning.backend"
```

```sh
Successfully built ibis-framework
Installing collected packages: xxhash, ibis-framework
  Attempting uninstall: xxhash
    Found existing installation: xxhash 0.0.0
    Uninstalling xxhash-0.0.0:
      Successfully uninstalled xxhash-0.0.0
  Attempting uninstall: ibis-framework
    Found existing installation: ibis-framework 5.1.0
    Uninstalling ibis-framework-5.1.0:
      Successfully uninstalled ibis-framework-5.1.0
Successfully installed ibis-framework-5.1.0.post373+3ad2ac18a.dirty
```
