### ISSUE TITLE
feat: make return type of `execute` configurable

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#6351]
### Is your feature request related to a problem?

In re: question asked in https://github.com/ibis-project/ibis/discussions/6347#discussion-5252889

@nikhilmakan02 was asking if there was a way to have `execute` return a pyarrow table by default.

### Describe the solution you'd like

A config option to set the output type of `execute` to `pyarrow` or a record-batch-reader (or any other in-memory representations).  

Probably don't want to enable this for file outputs because we'd need a filename or have to generate one and it would be confusing.

If we set the default to `pandas` this wouldn't be a breaking change.

### What version of ibis are you running?

HEAD

### What backend(s) are you using, if any?

all of them

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I suspect the config value could just be the method name, to avoid having to make up new names for things that we already have names for.

**Comment by astrojuanlu** [comment]
I was also surprised that `.execute()` would always return a `pandas.DataFrame`, even for the DuckDB (default) and Polars backends.

**Comment by astrojuanlu** [comment]
Thanks @cpcloud, I actually like that API much more. I didn't know it existed, maybe the "Ibis for pandas users" and other tutorials could be adapted to reflect that?
