### ISSUE TITLE
docs: `TimeValue` docs appear to be missing information

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#6352]
### Discussed in https://github.com/ibis-project/ibis/discussions/6008

<div type='discussions-op-text'>

<sup>Originally posted by **rongxin-yu** April 14, 2023</sup>
Hi,

I started to try out the IBIS project and really like it. I ran a lot of SQL queries and it was hard to maintain. IBIS seems to come to rescue. 

One quick note I would like to leave is that the document seems to be outdated. For example, it seems to me that with TimeValue t, one can do things like t.hour(), t.day(). However this is not documented on 
https://ibis-project.org/api/expressions/timestamps/#ibis.expr.types.temporal.TimeValue

I had to infer it by checking the backend matrix and then guess it.</div>

**Comment by gforsyth** [comment]
The non-legacy python handler for `mkdocstrings` has not yet implemented inheriting objects from parent classes, which will make this a bit tricky to do.

**Comment by gforsyth** [comment]
Resolved by adding them manually in #6439
