### ISSUE TITLE
feat: add read_delta and to_delta for PySpark

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#6383]
### Is your feature request related to a problem?

related issues: https://github.com/ibis-project/ibis/issues/6013 and https://github.com/ibis-project/ibis/issues/6319

scope of this issue is specifically adding for PySpark, which may have some complications? and the `to_delta` should write remotely instead of how it's implemented right now

### Describe the solution you'd like

```
t = ibis.read_delta("/remote/spark/delta/table"
t.to_delta("/another/table", mode="append")
```

### What version of ibis are you running?

n/a

### What backend(s) are you using, if any?

pyspark

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amine-decathlon** [comment]
Much needed feature imo. How high is it on the priority list

**Comment by lostmygithubaccount** [comment]
hi @amine-decathlon thanks for raising! we can most likely get this in before the next release and merged in master soon if there are no unforeseen issues

**Comment by lostmygithubaccount** [comment]
this is merged and you can try it out by installing from source! or wait for the next release, or use the new pre-release once it's out on Sunday

let us know if you have any issues or additional requests!
