### ISSUE TITLE
feat: Ibis has no way to convert UDFs to substrait plan

### ISSUE THREAD

**Issue by Anindyadeep** [ibis-project/ibis#6425]
Ibis is doing some incredible work by integrating substrait for generating substrait plan of the user's query to support cross DB operations in python. 

Suppose we have a table like this :
```
┏━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┓
┃ cust_id ┃ income1 ┃ income2 ┃ income3  ┃
┡━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━┩
│ int64   │ float64 │ float64 │ float64  │
├─────────┼─────────┼─────────┼──────────┤
│       1 │ 20000.0 │ 3560.57 │      nan │
│       2 │ 34546.9 │ 6000.66 │   1000.0 │
│       3 │ 75430.2 │ 8111.01 │      nan │
│       4 │ 55430.2 │ 8111.01 │   1200.0 │
│       5 │     nan │ 8111.01 │      nan │
│       6 │     nan │     nan │ 100000.0 │
└─────────┴─────────┴─────────┴──────────┘
```

Right now we define udf's in ibis like this 

```python
import ibis.expr.datatypes as dt 
from ibis.backends.pandas.udf import udf

@udf.analytic(input_type = [dt.double, dt.double], output_type=dt.double)
def function(c1, c2):
    return c1 + c2 
```

And hence we can apply this function to our tables like this 
```python
function(table.income1, table.income2)
```
And applying this function returns this 
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ AnalyticVectorizedUDF() ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ float64                 │
├─────────────────────────┤
│                23560.57 │
│                40547.56 │
│                83541.21 │
│                63541.21 │
│                     nan │
│                     nan │
└─────────────────────────┘
```
Even we can mutate our existing table to add a new column with this function. 
```python
mutate_expression = table.mutate(
    added = function(table.income1, table.income2)
)
```

Before coming to the main problem, consider this, I have a simple expression like this 
```python
expression = table.income1 + table.income2
```
And now I can generate the substrait plan of this expression using this code : 

```python 
from ibis_substrait.compiler.core import SubstraitCompiler

compiler = SubstraitCompiler()
expression = table.income1 + table.income2
substrait_plan = compiler.compile(table.mutate(expression))
```
Hence I can get the substrait plan. But when I am trying to get the substrait plan through an user defined function then I am getting this error: 

```python 
udf_expression = table.mutate(
    added = function(table.income1, table.income2)
)

substrait_plan_udf = compiler.compile(table.mutate(udf_expression))
```

Doing this gives me the error : `KeyError: 'AnalyticVectorizedUDF'`. 

I even thought that substrait might also not provide the support for now. But it seems like [substrait do support](https://github.com/substrait-io/substrait/blob/9b763a008de8fac12622353ce65e856389dd1c0e/site/docs/expressions/user_defined_functions.md#L2) : 
- UserDefined defined `type` 
- ParameterizedUserDefined `type`
- UserDefined `relation` 

But [Not user defined relations](https://github.com/substrait-io/substrait/blob/9b763a008de8fac12622353ce65e856389dd1c0e/site/docs/relations/user_defined_relations.md#L3). 

This concludes that ibis is not supporting generating substrait plans for user defined functions. But it will be awesome if we have one. 

P.S I have already posted to `ibis-substrait` github repo. Though they did't have a template for feature. Lemme know I will delete this issue here, if needed. 

Thanks 

### Describe the solution you'd like

The solution I would like to have is a substrait plan similar like how we have for expression for user defined functions too.

### What version of ibis are you running?

5.1.0

### What backend(s) are you using, if any?

The backends I am using right now is 

- DuckDB
- Pandas 
- SQL 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for raising this @Anindyadeep !  I've responded over in https://github.com/ibis-project/ibis-substrait/issues/644 which I think is the more relevant place to continue this discussion, so I'm going to close out this issue here.
