### ISSUE TITLE
bug: .epoch_seconds() doesn't show up in docs

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#6428]
### What happened?

title; there is a docstring but it's not discoverable in documentation (other than mention in release notes)

### What version of ibis are you using?

latest

### What backend(s) are you using, if any?

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
This is, I believe, part of a larger issue where `mkdocstrings` cannot display docstrings for methods/attributes/properties that are inherited (and `epoch_seconds` and others are part of the `_DateComponentMixin`)
