### ISSUE TITLE
docs: raw SQL execution in duckdb

### ISSUE THREAD

**Issue by cboettig** [ibis-project/ibis#6485]
### Is your feature request related to a problem?

I'd like to use `ibis`+`duckdb` when working with alternative S3 endpoints but cannot figure out how to pass the necessary commands to ibis.  

In pure `duckdb` we do this:

```
import duckdb
endpoint="https://sdsc.osn.xsede.org"
con = duckdb.connect()
con.execute(f'''
INSTALL httpfs;
LOAD httpfs;
SET s3_url_style='path';
SET s3_endpoint='{endpoint}';
''')
```

### Describe the solution you'd like

I'd like to do the exact same thing with `ibis` duckdb connection but no dice.   

```
import ibis
con = ibis.duckdb.connect()
endpoint="https://sdsc.osn.xsede.org"

con.execute(f'''
INSTALL httpfs;
LOAD httpfs;
SET s3_url_style='path';
SET s3_endpoint='{endpoint}';
''')
```

I gather the syntax for the `execute()` for an ibis duckdb connection is clearly quite different from that in duckdb itself, but not sure what the correct method is for doing these setup commands.  Sorry I'm probably overlooking something obvious!

### What version of ibis are you running?

5.1.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @cboettig 👋🏻 

Yeah, docs are a little light on this topic and method (https://ibis-project.org/api/backends/sql/#ibis.backends.base.sql.BaseSQLBackend.raw_sql) 😅.

The way to execute SQL strings is using the `con.raw_sql` method:

```
In [1]: import ibis

In [2]: con = ibis.duckdb.connect()

In [3]: con.raw_sql("""
   ...: INSTALL httpfs;
   ...: LOAD httpfs;
   ...: SET s3_url_style='path';
   ...: """)
Out[3]: <sqlalchemy.engine.cursor.LegacyCursorResult at 0x7f3424d759c0>
```

In this case, there's no need to release the cursor, because no results are returned from the query.

**Comment by cboettig** [comment]
Thanks @cpcloud , really great.  um, some reason I'm still not seeing my way clear to doing an ibis-based filter on this.  

```
import ibis
endpoint="sdsc.osn.xsede.org"
con = ibis.duckdb.connect()

con.raw_sql(f'''
INSTALL httpfs;
LOAD httpfs;
SET s3_url_style='path';
SET s3_endpoint='{endpoint}';
''')
```

Now that we have the alternative endpoint setup, let's try to do a filter:

```
date = "2020-09-24"
bucket = "bio230014-bucket01"
path = f"neon4cast-drivers/noaa/gefs-v12/stage1/reference_datetime={date}"


noaa = con.read_parquet(f"s3://{bucket}/{path}")
```
But this gives an error: `Error: cannot start a transaction within a transaction`


for completeness, hoping to be able to write simple filters on this parquet data using ibis syntax instead of raw SQL, like 
````
df = (noaa.
      filter(noaa.site_id == "BART",
             noaa.variable == "TMP")
     )
```

what did I miss this time?  Maybe I do need to release the cursor?  (Note this is a public bucket so I think the above code should be fully reproducible in any python interface...)

**Comment by gforsyth** [comment]
Hey @cboettig -- maybe try upgrading to a recent pre-release?  `pip install -U --pre 'ibis-framework[duckdb]'`

```python

[ins] In [1]: import ibis
         ...: 
         ...: endpoint = "sdsc.osn.xsede.org"
         ...: con = ibis.duckdb.connect()
         ...: 
         ...: con.raw_sql(
         ...:     f"""
         ...: INSTALL httpfs;
         ...: LOAD httpfs;
         ...: SET s3_url_style='path';
         ...: SET s3_endpoint='{endpoint}';
         ...: """
         ...: )
Out[1]: <sqlalchemy.engine.cursor.LegacyCursorResult at 0x7f86ea0106a0>

[ins] In [2]: date = "2020-09-24"
         ...: bucket = "bio230014-bucket01"
         ...: path = f"neon4cast-drivers/noaa/gefs-v12/stage1/reference_datetime={date}"
         ...: 
         ...: 
         ...: noaa = con.read_parquet(
         ...:     f"s3://{bucket}/{path}/**"
         ...: )  # note the ** to use DuckDB recursive glob

[ins] In [3]: df = noaa.filter([noaa.site_id == "BART", noaa.variable == "TMP"])

[ins] In [4]: df.head().execute()
Out[4]: 
  ensemble cycle  horizon                  datetime  ... prediction    family reference_datetime site_id
0    gec00    00    64800 2020-09-24 18:00:00+00:00  ...  20.445673  ensemble         2020-09-24    BART
1    gec00    00   118800 2020-09-25 09:00:00+00:00  ...   9.695062  ensemble         2020-09-24    BART
2    gec00    00    10800 2020-09-24 03:00:00+00:00  ...  10.796503  ensemble         2020-09-24    BART
3    gec00    00   378000 2020-09-28 09:00:00+00:00  ...  16.455713  ensemble         2020-09-24    BART
4    gec00    00   270000 2020-09-27 03:00:00+00:00  ...  14.905908  ensemble         2020-09-24    BART

[5 rows x 9 columns]
```

I'm also running this against DuckDB 0.8.1

**Comment by cboettig** [comment]
@gforsyth brilliant that works perfectly.  

(with sql_raw I realized I could manually create the view, e.g.

```
con.raw_sql(f'''
CREATE VIEW noaa AS SELECT * FROM read_parquet('s3://{bucket}/{path}/*.parquet')
''')
```

but this is much nicer.  Still, I wonder if it would be possible for the `read_parquet()` method to take `endpoint` as an argument and take care of the setup for us?  

the block 

```
con.raw_sql(f'''
INSTALL httpfs;
LOAD httpfs;
SET s3_url_style='path';
SET s3_endpoint='{endpoint}';
''')
```

feels a little intimidating when trying to introduce this to new users.  (`arrow` syntax for this is nicer...)

**Comment by gforsyth** [comment]
Hey @cboettig -- glad that did the trick.

Which arrow syntax are you referring to?  I'd like to take a look.  

Exposing new keyword arguments is a little tricky -- we currently fall back to using `pyarrow.dataset` if reading with the built-in DuckDB `read_parquet` function fails.  We use that (terrible) heuristic to assume that the user is trying to hit something in a private bucket, and so we fall back to pyarrow so that the common cloud environment variables for authentication are picked up.
If we want `endpoint=` to work for both of those cases, it will probably get messy very quickly.

It might make more sense for us to provide separate `read_` methods for the native parquet vs. pyarrow reader, although that might also be a source of confusion.

**Comment by cboettig** [comment]
that makes sense.  My syntax for an arrow dataset connection to the same parquet data via the alternative endpoint would be:

```
import pyarrow.dataset as ds
date = "2020-09-24"
bucket = "bio230014-bucket01"
path = f"neon4cast-drivers/noaa/gefs-v12/stage1/reference_datetime={date}"
endpoint = "https://sdsc.osn.xsede.org"
uri = f"s3://{bucket}/{path}?endpoint_override={endpoint}"
dataset = ds.dataset(uri, partitioning=["site_id"])
```

(i.e. arrow understands the query parameter and duckdb does not -- it would be great if we could all agree more about how we did these things, maybe I should be opening an issue on duckdb instead).  

using different `read_` methods makes sense to me though, it would make it clearer to me as the user if I'm getting a native arrow or a duckdb connection (and with fsspec in the mix, it can be very very confusing how a connection to a remote bucket is being handled!  My observation has been that it's always easiest to find examples / tutorials showing fsspec, but that duckdb native extension is fastest, followed by arrow native s3, with fsspec in distant third place...)

**Comment by cpcloud** [comment]
Using

```python
import ibis

date = "2020-09-24"
bucket = "bio230014-bucket01"
path = f"neon4cast-drivers/noaa/gefs-v12/stage1/reference_datetime={date}"
endpoint = "https://sdsc.osn.xsede.org/"
uri = f"s3://{bucket}/{path}?endpoint_override={endpoint}"

t = ibis.read_parquet(uri)
```

I am able to access the data but ibis fails because we don't know how to convert sqlalchemy `INTERVAL` types to ibis types.

That's a bug, which we will fix for 6.0!

**Comment by cpcloud** [comment]
@cboettig The interval bug may not make the 6.0 cut, but we will do a follow up patch or feature release which will contain the fix.

**Comment by cboettig** [comment]
@cpcloud thanks for the heads up, I'll be watching this space!

**Comment by gforsyth** [comment]
> Using
> 
> ```python
> import ibis
> 
> date = "2020-09-24"
> bucket = "bio230014-bucket01"
> path = f"neon4cast-drivers/noaa/gefs-v12/stage1/reference_datetime={date}"
> endpoint = "https://sdsc.osn.xsede.org/"
> uri = f"s3://{bucket}/{path}?endpoint_override={endpoint}"
> 
> t = ibis.read_parquet(uri)
> ```
> 
> I am able to access the data but ibis fails because we don't know how to convert sqlalchemy `INTERVAL` types to ibis types.

The reason this works is that it falls back to the pyarrow dataset loading.  Doesn't change that we need to fix the `INTERVAL` stuff, but does speak to maybe splitting out the two parquet loading methods.

**Comment by lostmygithubaccount** [comment]
closing as the initial issue is resolved (feel free to reopen or create a new issue)
