### ISSUE TITLE
feat(duckdb): support `asof_join` in the DuckDB backend

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#6487]
### Discussed in https://github.com/ibis-project/ibis/discussions/6482

<div type='discussions-op-text'>

<sup>Originally posted by **derekmahar** June 18, 2023</sup>
Does the [Ibis](https://ibis-project.org/) table [`asof_join`](https://ibis-project.org/api/expressions/tables/#ibis.expr.types.relations.Table.asof_join) function work with the [DuckDB](https://duckdb.org/) backend?  Does it use the SQL [`ASOF JOIN`](https://duckdb.org/docs/sql/query_syntax/from#as-of-joins) operator that DuckDB [0.8.0](https://github.com/duckdb/duckdb/releases/tag/v0.8.0) introduced?</div>

**Comment by cpcloud** [comment]
@mesejo I think @gforsyth may already be working on this one!

**Comment by gforsyth** [comment]
@kszucs added this as part of `the-epic-split`
