### ISSUE TITLE
feat: use try_cast() in duckdb-engine

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6492]
### Is your feature request related to a problem?
EDIT: the PR has now landed in duckdb-engine

try_cast() is getting added to duckdb-engine in https://github.com/Mause/duckdb_engine/pull/696. Once that lands, I think we can redo our implementation of try_cast to just use that instead of re-inventing it ourselves.

### Describe the solution you'd like

NA

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NickCrews** [comment]
We _could_ backport the support for people with older versions of duckdb-engine:

```python
if duckdb_engine.__version__ < "0.9.0":

    @compiles(try_cast, "duckdb")
    def compiles_try_cast(element, compiler, **kw):
        return "TRY_CAST({} AS {})".format(
            compiler.process(element.clauses.clauses[0], **kw),
            compiler.visit_typeclause(element),
        )
```

but I think I would rather just delete that code, and if people want the support then they should update to duckdb-engine>=0.9.0

Thoughts?

**Comment by lostmygithubaccount** [comment]
given how recently the `try_cast` operation in Ibis landed, I think it's reasonable to only support the new DuckDB functionality and require users to upgrade

**Comment by cpcloud** [comment]
Closing this out.

Since we have to support sqlalchemy 1.4.x and it would be strictly additional code to use the duckdb-engine implementation because we'd also have to add a version check.

**Comment by NickCrews** [comment]
Sure. Can revisit once we can drop old versions. Should we add a TODO in the code that says this?
