### ISSUE TITLE
feat(duckdb): support MotherDuck

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#6514]
[MotherDuck](https://motherduck.com) publicly launched today. Can Ibis already support it through the DuckDB backend? Are changes required to the DuckDB backend to support it? Or would this require a new Ibis backend?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Looks like it's just a different connection string, but we'll know as soon as they let me into the user pool!
