### ISSUE TITLE
feat: squash merges on PRs

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#6549]
### Is your feature request related to a problem?

After some internal discussion, opening this issue for tracking. There were recently 2 issues with PRs due to the requirement to squash commits into a single commit, which can be a more complicated git operation (edit: adding a third more recent example, certainly others): 

1. https://github.com/ibis-project/ibis/pull/6543
2. https://github.com/ibis-project/ibis/pull/6460#issuecomment-1594987395
3. https://github.com/ibis-project/ibis/pull/7804

It would be easier to accept PRs if this requirement were removed. We should enable PR squash merge on GitHub. This likely involves some work to ensure the changelog and everything else works as expected.

### Describe the solution you'd like

As a user, I can simply push commits to a PR and have it merged without a rebase or other more advanced git operations.

### What version of ibis are you running?

n/a

### What backend(s) are you using, if any?

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
> It would be easier to accept PRs if this requirement were removed. We should enable PR squash merge on GitHub. This likely involves some work to ensure the changelog and everything else works as expected.

On some of the substrait repos (like substrait-python), we have a github action that checks that the PR title conforms to the conventional commits style -- since the PR title is the default commit message for a squashed PR, this (mostly) takes care of ensuring that the squash merge messages conform:

https://github.com/substrait-io/substrait-python/blob/main/.github/workflows/pr_title.yml

**Comment by gforsyth** [comment]
I think for the core devs, we still mostly squash and rebase our own PRs, but I agree this can be helpful, especially for new contributors.

**Comment by gforsyth** [comment]
(bonus, if the PR title lint fails and you edit the PR title, it doesn't require re-running the entire CI suite)

**Comment by cpcloud** [comment]
Seems legit, let's do it!

**Comment by gforsyth** [comment]
Ooooh, question: should we disable `commitlint`?
Or allow failures?

**Comment by cpcloud** [comment]
I think we can disable it in PRs, and continue to run it on a merge to `master`.

**Comment by cpcloud** [comment]
Which appears to be basically the opposite of what we're doing now!

**Comment by cpcloud** [comment]
It'll be annoying to specify the commit range though because there's no obvious reference point once the commit is merged. Perhaps just disable it for now.

**Comment by cpcloud** [comment]
Also there's not much value in checking after a merge to `master` because we disabled force pushing :)
