### ISSUE TITLE
bug: No early error and/or wrong behavior when mixing backends

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6551]
### What happened?

```python
import ibis
import pandas as pd

ibis.options.interactive = True

be2 = ibis.duckdb.connect()
be1 = ibis.duckdb.connect()
assert be1 is not be2

df1 = pd.DataFrame({"a": [0, 1, 2]})
df2 = pd.DataFrame({"a": [3, 4, 5]})
t1 = be1.create_table("a", df1)
t2 = be2.create_table("b", df2)

# This happily works, when it really should error at this point.
u = ibis.union(t1, t2)

# Only when you execute do you get the error:
u.execute()
# ProgrammingError: (duckdb.CatalogException) Catalog Error: Table with name b does not exist!
# Did you mean "a"?
# [SQL: WITH anon_1 AS 
# (SELECT t1.a AS a 
# FROM a AS t1), 
# anon_2 AS 
# (SELECT t1.a AS a 
# FROM b AS t1)
#  SELECT t0.a 
# FROM (SELECT anon_1.a AS a 
# FROM anon_1 UNION ALL SELECT anon_2.a AS a 
# FROM anon_2) AS t0 
#  LIMIT ?]
# [parameters: (11,)]
# (Background on this error at: https://sqlalche.me/e/20/f405)

# even more dangerous, if the two table names can be resolved within a backend,
# then this silently works, even though it gives the wrong result
t3 = be1.create_table("t3", df1)
t4 = be2.create_table("t3", df2)
ibis.union(t3, t4)
# ┏━━━━━━━┓
# ┃ a     ┃
# ┡━━━━━━━┩
# │ int64 │
# ├───────┤
# │     0 │
# │     1 │
# │     2 │
# │     0 │
# │     1 │
# │     2 │
# └───────┘

# Somewhat separately (split into a new bug?),
# duckdb's way of inserting local variables also
# can lead to it inserting tables into queries in unexpected ways.
# This is a duckdb-specific thing, none of the other backends do this,
# so if we could disable this I think it would be good. Otherwise
# I worry this is just inviting a really really nasty bug for someone,
# since this behavior of duckdb I think is not well known.
# Make a variable named "b" available, and the first query works again:
b = df1
u.execute()
```

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @NickCrews -- I understand the potential for footguns here with mixing backends, but I don't think these are bugs. 

The fact that `t1` and `t2` happen to be backed by data is almost an afterthought -- the `union` "works" because you can union two tables together.  This is also why we can execute the same expression against multiple backends (with the assumption that the table names match and the schema match).

It's not inconceivable to have some kind of "strict" mode, but I think that would entail a pretty large refactor.

Is this something that's bitten you multiple times?

> ```python
> # Somewhat separately (split into a new bug?),
> # duckdb's way of inserting local variables also
> # can lead to it inserting tables into queries in unexpected ways.
> # This is a duckdb-specific thing, none of the other backends do this,
> # so if we could disable this I think it would be good. 
> ```

This is a DuckDB thing and there's no option to stop duckdb peeking at python memory and grabbing things.   You can file an issue upstream to see if they're willing to put a toggle in front of it.

**Comment by NickCrews** [comment]
OK, my mental model of an Expr was that every Expr has a Backend that it lives within. But you're saying that is not true? The backend is only resolved at execution time? That would explain why there is method a called `Expr._find_backend()` instead of a simple attribute `Expr.backend`. I always wondered why the API worked that way.

Yes, this is something that has bitten me multiple times. Usually I have some util method for reading files, and each time I read I accidentally use a different backend.

I'm almost definitely missing some key history and reasonings here, but hear me out. I see the value of how the backing data and backend being separate from the Expr is good. But I think the semantics should be that every expression has a property of type `Backend | None`, None meaning that the Expr isn't bound to a backend. Then, it should be legal to combine expressions as long as they share no more than one Backend:

```python
a = ibis.read_csv(....)  # backend is None
b = ibis.read_csv(....)  # backend is None
c = ibis.duckdb.connect().read_csv() # backend is explicitly set
d = ibis.duckdb.connect().read_csv() # backend is explicitly set, different from b

ibis.union(a, b) # works, backend is still None
ibis.union(a, c) # works, backend is now c.backend
ibis.union(c, d) # errors, because which backend to use is ambiguous

# (maybe not a good idea)
# You can explicitly move an expression to another backend if you need
e = c.set_backend(d.backend)
```

Is this a performance question? every time you compose two expressions you would have to do this check?

Thanks for the duckdb memory peeking response, I'll file with them.

**Comment by gforsyth** [comment]
> every Expr has a Backend that it lives within. But you're saying that is not true?

Yes.  You can create `UnboundTable`s using `ibis.table` and build up expressions that have no notion of any backend.
Grabbing a table from an existing connection is effectively a shortcut to get a table schema from an existing table, but it would be effectively the same to manually write out the column names and types into a mapping and pass them to `ibis.table`.


> Is this a performance question? every time you compose two expressions you would have to do this check?

It probably wouldn't impact performance all that much, but it will require a refactor to set up all the checks in the appropriate places.


If you can provide some examples of how your file reading utilities are failing we might be able to help make them more robust to backend changes.
