### ISSUE TITLE
feat(api): expand support for range-based interval windowing

### ISSUE THREAD

**Issue by chloeh13q** [ibis-project/ibis#6564]
### What happened?

I'm not sure if this is intentional (or perhaps I'm misusing the API), but the support for range-based interval windowing in Ibis seems quite limited to me. I tested a few things and many of them throw errors:
```python
table = ibis.table([("c", "int32")], name="table")
table.c.mean().over(range=(-ibis.interval(minutes=30), ibis.interval(seconds=30)))
```
and 
```python
table.c.mean().over(range=(-ibis.interval(minutes=30), ibis.interval(0)))
```
both throw
```python
IbisTypeError: Cannot compute precedence for `interval()` and `interval()` types
```
because Ibis recognizes the `output_dtype` of `start` as `interval(<IntervalUnit.MINUTE: 'm'>)` and the `output_dtype` of `end` as `interval(<IntervalUnit.SECOND: 's'>)`.

It seems that the `.over()` syntax also does not support `timedelta`:
```python
table.c.mean().over(range=(-timedelta(seconds=30), 0))
```
throws 
```python
IbisTypeError: argument passes none of the following rules: any_of([value(Int64(nullable=True),), value(Float64(nullable=True),), value(,), value(Boolean(nullable=True),)],), interval()
```

### What version of ibis are you using?

5.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
hi @chloeh13q, apologies for the slow response here -- interval types are something we plan to improve in the coming months. @cpcloud or @jcrist are there any plans we can share here? thoughts on this specific issue?

**Comment by kszucs** [comment]
Thanks @chloeh13q for the bug report!

We have two issues here:
1. Currently we only consider an interval *implicitly* castable to another interval datatype if their units match
https://github.com/ibis-project/ibis/blob/cb1956ff25fb0e9d6d8a0c3dba9ddf512a6c42aa/ibis/expr/datatypes/cast.py#L132-L134

    Meaning we don't consider those units implicitly castable:

    ```py
    In [18]: dt.Interval('m').castable(dt.Interval('s'))
    Out[18]: False
    ```

We need to allow downcasting time units e.g. minutes to seconds. The relevant code is here:


2. Currently we prohibit constructing an interval from a timedelta containing both day and second/microsecond resolution components
https://github.com/ibis-project/ibis/blob/cb1956ff25fb0e9d6d8a0c3dba9ddf512a6c42aa/ibis/common/temporal.py#L165-L167

    ```py
    In [16]: -timedelta(seconds=30)
    Out[16]: datetime.timedelta(days=-1, seconds=86370)  # this is unfortunate
    ```
    Apparently negative timedeltas are turned into a "compound" timedelta containing negative days component.
    This could only be resolved by removing the restriction from the implementation, but interval operations involving both days and time components can get confusing due to daylight savings. An alternative definition could be to use `ibis.interval()` directly which construct an interval by adding the two components together:

    ```py
    In [2]: ibis.interval(days=1, seconds=1)
    Out[2]: IntervalAdd(1, 1): 1 s + 1 D
    ```

**Comment by binste** [comment]
Related to this, when I use `ibis.interval(days=...)` in Ibis 6.1 it does generate a query instead of raising the "IbisTypeError: Cannot compute precedence for `interval()` and `interval()` types` error" but the query is invalid, at least for duckdb:

```python
import datetime as dt
import ibis
import pandas as pd

df = pd.DataFrame(
    [
        [dt.datetime(2023, 8, 8), 1],
        [dt.datetime(2023, 8, 9), 2],
        [dt.datetime(2023, 8, 11), 5],
    ],
    columns=["record_at", "value"],
)

con = ibis.duckdb.connect()
table = con.read_in_memory(df)
rolling_mean = table.mutate(
        rolling_mean=table["value"]
        .mean()
        .over(
            ibis.window(
                order_by=table["record_at"],
                range=(ibis.interval(days=-2), ibis.interval(days=0)),
            )
        )
    )
ibis.show_sql(
    rolling_mean
)
```
```sql
SELECT
  t0.record_at,
  t0.value,
  AVG(t0.value) OVER (ORDER BY t0.record_at RANGE BETWEEN 2 PRECEDING AND CURRENT ROW) AS rolling_mean
FROM _ibis_read_in_memory_64szuz5shbgsno3burikmk7iee AS t0
```

This query is not valid in duckdb, tested both by running `execute` as well as in a pure `duckdb.DuckDBPyConnection`:
```python
rolling_mean.execute()
```
```python
InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: Binder Error: No function matches the given name and argument types '-(TIMESTAMP, TINYINT)'. You might need to add explicit type casts.
	Candidate functions:
	-(TINYINT) -> TINYINT
	-(TINYINT, TINYINT) -> TINYINT
	-(SMALLINT) -> SMALLINT
	-(SMALLINT, SMALLINT) -> SMALLINT
...

[SQL: SELECT t0.record_at, t0.value, avg(t0.value) OVER (ORDER BY t0.record_at ASC RANGE BETWEEN ? PRECEDING AND CURRENT ROW) AS rolling_mean 
FROM _ibis_read_in_memory_64szuz5shbgsno3burikmk7iee AS t0]
[parameters: (2,)]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

The expected query which works would be:
```sql
SELECT
  t0.record_at,
  t0.value,
  AVG(t0.value) OVER (ORDER BY t0.record_at RANGE BETWEEN INTERVAL 2 DAYS PRECEDING AND CURRENT ROW) AS rolling_mean
FROM _ibis_read_in_memory_64szuz5shbgsno3burikmk7iee AS t0
```
Only difference is `BETWEEN 2 PRECEDING` -> `BETWEEN INTERVAL 2 DAYS PRECEDING`.

**Comment by cpcloud** [comment]
@binste Your code should now work on `master`:

```
In [1]: import datetime as dt
   ...: import ibis
   ...: import pandas as pd
   ...:
   ...: df = pd.DataFrame(
   ...:     [
   ...:         [dt.datetime(2023, 8, 8), 1],
   ...:         [dt.datetime(2023, 8, 9), 2],
   ...:         [dt.datetime(2023, 8, 11), 5],
   ...:     ],
   ...:     columns=["record_at", "value"],
   ...: )
   ...:
   ...: con = ibis.duckdb.connect()
   ...: table = con.read_in_memory(df)
   ...: rolling_mean = table.mutate(
   ...:     rolling_mean=table["value"]
   ...:     .mean()
   ...:     .over(
   ...:         ibis.window(
   ...:             order_by=table["record_at"],
   ...:             range=(ibis.interval(days=-2), ibis.interval(days=0)),
   ...:         )
   ...:     )
   ...: )
   ...: ibis.show_sql(rolling_mean)
SELECT
  t0.record_at,
  t0.value,
  AVG(t0.value) OVER (ORDER BY t0.record_at ASC RANGE BETWEEN TO_DAYS(2) PRECEDING AND TO_DAYS(0) FOLLOWING) AS rolling_mean
FROM main.ibis_read_in_memory_oolvg4lowvfinkh6fkl3pzdcue AS t0

In [2]: rolling_mean.execute()
Out[2]:
   record_at  value  rolling_mean
0 2023-08-08      1           1.0
1 2023-08-09      2           1.5
2 2023-08-11      5           3.5
```

**Comment by binste** [comment]
Awesome, thank you! :)

**Comment by chloeh13q** [comment]
I can confirm that 
```py
table.c.mean().over(range=(-ibis.interval(minutes=30), ibis.interval(seconds=30)))
```
and 
```py
table.c.mean().over(range=(-ibis.interval(minutes=30), ibis.interval(0)))
```
both work now!

I'm not sure whether there is intention/whether it makes sense to support negative timedeltas because of the complications around the fact that they get turned into compound timedeltas and "interval operations involving both days and time components can get confusing due to daylight savings". If not, I think it would be helpful to document the fact that this doesn't work somewhere and I am happy to close this ticket.
