### ISSUE TITLE
udf input issue

### ISSUE THREAD

**Issue by Proteusiq** [ibis-project/ibis#6589]
In this example [Ibis on 🔥: Supercharge Your Workflow with DuckDB and PyTorch](https://github.com/ibis-project/ibis/blob/0ad3ce258af4258dbb2f29f3c48895980aba314a/docs/blog/rendered/torch.ipynb) uses `udf` which has access to `scalar.pyarrow`. I could not import or find where this has moved to.

```python
>>> from ibis.expr.operations import udf
... ImportError: cannot import name 'udf' from 'ibis.expr.operations' (/home/pwd/.pyenv/versions/3.10.10/lib/python3.10/site-packages/ibis/expr/operations/__init__.py)

>>> import ibis;ibis.__version__
... '5.1.0'
```
Is the package deprecated? What is the alternative?

**Comment by jcrist** [comment]
> Is the package deprecated? What is the alternative?

It was just released, you'll need to upgrade to 6.0.0 (released 2 hours ago).

**Comment by lostmygithubaccount** [comment]
You should also be able to `from ibis import udf` now. The legacy UDF support has moved under `ibis.legacy.udf`, so if you are intending to use the old UDFs you can `from ibis.legacy import udf`.

Thanks for trying it out and let us know if you have any further issues!

**Comment by Proteusiq** [comment]
version 6.0.0 has it fixed. Thank you!
