### ISSUE TITLE
bug: defining cumulative operations over a window

### ISSUE THREAD

**Issue by chloeh13q** [ibis-project/ibis#6594]
### What happened?

While trying to understand the intended usage of cumulative operators and windowing in Ibis, I came across the following code snippet that uses `cumsum()` in conjunction with `over()`.
```python
expr = t.f.cumsum().over(range=(-1, 1), group_by=[t.g, t.a], order_by=[t.f])
```
(Source: https://github.com/ibis-project/ibis/blob/master/ibis/tests/expr/test_window_functions.py#L43-L55)

I dug a bit into the code and looked into the usage of cumulative operators in, e.g., pandas, and am a little confused about the usage here. What does it mean for cumsum to be defined over a range? How does that differ from a regular "windowed sum" operation? 

I also tried compiling this into SQL, and got the following in the BigQuery backend:
```
SELECT sum(t0.`f`) OVER (PARTITION BY t0.`g`, t0.`a` ORDER BY t0.`f` ASC RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS `CumulativeSum_f`
FROM table t0
```
It seems from the SQL that Ibis is effectively ignoring the `range` that is passed in.

On the other hand, 
```python
table.f.sum().over(range=(-1, 1), group_by=[table.g, table.a], order_by=[table.f])
```
compiles into
```
SELECT sum(t0.`f`) OVER (PARTITION BY t0.`g`, t0.`a` ORDER BY t0.`f` ASC RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS `Sum_f`
FROM table t0
```
(as expected).

I also verified and did not find this behavior being tested in specific backends, other than [here](https://github.com/ibis-project/ibis/blob/92f29e6b820f207b16a306e5a39f91d396fe818a/ibis/backends/tests/test_window.py#L170), where the window is in fact unbounded.

### What version of ibis are you using?

5.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Thanks for opening this @chloeh13q! cc @kszucs - can you look take a quick look at this since you recently(ish) refactored our window handling logic?

**Comment by cpcloud** [comment]
This was fixed recently in https://github.com/ibis-project/ibis/pull/7600.

Here's the example from the original post:

```
In [9]: t = ibis.table({"a": "int64", "b": "int32", "g": "int64", "f": "int64"})

In [10]: expr = t.f.cumsum().over(range=(-1, 1), group_by=[t.g, t.a], order_by=[t.f])

In [11]: ibis.to_sql(expr, dialect="bigquery")
Out[11]:
SELECT
  sum(t0.`f`) OVER (PARTITION BY t0.`g`, t0.`a` ORDER BY t0.`f` ASC RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS `Sum_f`
FROM unbound_table_1 AS t0
```
