### ISSUE TITLE
question: types not working with pyright

### ISSUE THREAD

**Issue by masylum** [ibis-project/ibis#6619]
### What happened?

First of all, I'm pretty new to python and it's ecosystem, so this can very well be that "I'm holding it wrong".

I'm trying to use ibis for the expression to sql generation, but I'm stumbling upon very basic features. For instance, when using `isin` pyright complains that the types are not correct. They do not look correct to me either, so I'm wondering if this is a bug or not.

```py
t = ibis.table([("one", "string")], "my_data")
t.one.isin(["a", "b"]) # pyright: Argument of type "list[str]" cannot be assigned to parameter "values" of type "Value | Sequence[Value]" in function "isin"    "Literal['a']" is incompatible with "Value"
```

The type of `isin` clearly says `Value | Sequence[Value]` but on every single example, it can be used against lists of strings.

Thanks in advance!

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

postrgresql

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @masylum! Thanks for the issue.

Are you hitting a problem with ibis code generation or only type checking?

Our type annotations are currently best-effort, not for any reason other than there's never been a concerted effort to add them.

Are the imprecise type annotations a blocker for you?

**Comment by lostmygithubaccount** [comment]
going to close this out, @masylum let us know if you have additional information on the issue being caused here. we'll work to improve type annotation support where we can
