### ISSUE TITLE
bug: Array.filter() "Subqueries are not supported in lambda expressions!"

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6626]
### What happened?

If the predicate uses a table, the generated SQL contains a SELECT statement, which duckdb does not like. I think the solution should be that this CTE should be defined globally, not within the predicate.

```python
import ibis
ok_table = ibis.memtable({"ok_vals": [1, 3]}).cache()
vals = ibis.array([1, 2, 3])
vals.filter(lambda x: x.isin(ok_table.ok_vals))
```

Generates the error `Invalid Input Error: Subqueries are not supported in lambda expressions!`
```sql
SELECT list_filter(CAST(list_value(?, ?, ?) AS SMALLINT[]), (x) -> x IN (SELECT t0.ok_vals 
FROM _ibis_cache_2qh1jwxtt24snnbibhbix9zzq AS t0)) AS "ArrayFilter((1, 2, 3))
```

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue @NickCrews!

It sounds like you're suggesting that extracting the `SELECT` statement on the right side of the `IN` expression will address this issue.

I don't think it will, since you'll still need to `SELECT` from the CTE:

```
D with t0 as (select ok_vals from t) select list_filter([1, 2, 3], x -> x in (select ok_vals from t0));
Error: Invalid Input Error: Subqueries are not supported in lambda expressions!
```

Is there some syntax you found that allows you to achieve what you want without a subquery?

**Comment by cpcloud** [comment]
Closing since this is a limitation of DuckDB. Ibis is generating the intended SQL.

**Comment by NickCrews** [comment]
@cpcloud sorry for the late reply.

I simplified my use case in such a way that I removed an important detail: The needle and haystack for the .isin() are correlated. I want to find all values in `y` that are in `x`:
```SQL
CREATE OR REPLACE TABLE T AS SELECT [1,2,3] as x, [1,9] as y;
SELECT list_filter(y, elem -> list_contains(x, elem)) FROM T;
```
