### ISSUE TITLE
feat: allow chaining of `sql()` without using `alias()`

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#6659]
### Describe the solution you'd like

This is related to https://github.com/ibis-project/ibis/issues/6657. This is just an idea for a nice UX improvement, not something that is strictly needed:

Currently if an Ibis user wants to chain the `sql` method after other Ibis table methods, they need to:
- Chain on `alias('tablename')` immediately before `sql`
- Use `FROM tablename` in the SQL query string passed to `sql`

It would be a neat trick if Ibis could examine the query string passed to `sql` (maybe using sqlglot?), see if it was missing a FROM clause, and if so, transparently convert it internally to `.alias('tablename').sql('... FROM tablename')`.

### What version of ibis are you running?

5.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ianmcook** [comment]
I agree; the need to set an alias and use it in the FROM clause is the minorest of inconveniences. If there are nontrivial engineering downsides to making those inconveniences go away, then closing this as unplanned seems fine to me.

**Comment by cpcloud** [comment]
Thanks for the discussion! I'm going to close this as unplanned for now.

**Comment by ianmcook** [comment]
Relatedly, @lostmygithubaccount pointed out that DuckDB allows you to use the variable name of a Polars DataFrame in the FROM clause, and it looks for that in the current Python scope. This doesn't help with chaining per se, but it seems like a nice design that could create better convergence between the Ibis API experience and the Ibis `sql` experience

**Comment by ianmcook** [comment]
Also related: PySpark's SQLTransformer solves this by using `__THIS__` to represent the dataframe that it's called on: https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.ml.feature.SQLTransformer.html

**Comment by lostmygithubaccount** [comment]
could we use the underscore -- either something like `t.sql("select some_column from _")` or perhaps `t.sql("select some_column from ibis._")`? that could be nice to avoid needing to alias

**Comment by ianmcook** [comment]
@lostmygithubaccount unfortunately the underscore is a valid name/alias in at least some SQL dialects so this could create ambiguity
