### ISSUE TITLE
refactor: use `weakref.finalize` to clean up temp tables in backends that don't natively support temporary tables and views

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#6665]
The solution for the temp table behavior in oracle is to swap in `weakref.finalize` for `atexit` because we don't want to have to wait for the process to exit cleanly to remove temp tables.

_Originally posted by @gforsyth in https://github.com/ibis-project/ibis/issues/6637#issuecomment-1644316559_

**Comment by lostmygithubaccount** [comment]
@gforsyth is this issue still valid?

**Comment by cpcloud** [comment]
Perhaps we should close it as wontfix and add the `unresolved` label?

Doesn't seem worth keeping open if it's not currently a problem and we don't plan to work on it any time soon.
