### ISSUE TITLE
feat: support `True`, `ibis.literal(True)` as predicates to join

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6696]
### Is your feature request related to a problem?

I am trying to make a framework where users can specify a join condition, and I inject that into a `left.inner_join(right, predicates=condition)`.  If a user wants to do a cross join, in SQL they would be able to pass in `1=1`, so they should be able to do the equivalent of this by passing in a literal True.

### Describe the solution you'd like

support `True`, `ibis.literal(True)` as predicates. Maybe I'm not including some other values that make this more general. I guess `False` would also work, and should just give a table with the right schema, but 0 rows.

### What version of ibis are you running?

6.0.0

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue! Slated for 6.1.
