### ISSUE TITLE
Figure out a design for persistent user "sessions"

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#67]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Wednesday Jan 21, 2015 at 19:25 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/67_

---

We will want users to use Ibis to orchestrate more complex analytics workflows possibly involving many steps and many queries. As a result, users may cache many temporary tables or views in Impala which could be quite large. We should track all these somewhere and provide an API for administration / cleanup. Later on we can get clever about lineage, but that can be tackled later.

**Comment by cpcloud** [comment]
Closing. This is potentially interesting, but we need a use case fleshed out with more detail.
