### ISSUE TITLE
feat: overwrite=True for Bigquery backend

### ISSUE THREAD

**Issue by felipeangelimvieira** [ibis-project/ibis#6706]
### Is your feature request related to a problem?

Thank you for creating and maintaining this amazing library. 
I was using and exploring the code for BigQuery backend.
Currently, it seems that Bigquery backend's method create_table with overwrite=True raises NotImplementedError.

### Describe the solution you'd like

Couldn't overwrite=True be possible by calling drop_table method and then proceed with create_table?

### What version of ibis are you running?

5.1.0

### What backend(s) are you using, if any?

BigQuery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

You're right that this functionality is possible. I think we'd probably do this using `CREATE OR REPLACE ...` syntax, which looks like the most succinct way to enable this operation.
