### ISSUE TITLE
bug: Bigquery backend Table init does not respect the fully qualified table name input

### ISSUE THREAD

**Issue by maxshine** [ibis-project/ibis#6715]
### What happened?

In the case to initialize a Bigquery backend table object with a fully qualified name, e.g. `project.dataset.table_name`, the connection object will append its default project and dataset. This cause the wrong table name used in the executed SQL stmt.

The expected behavior should be that the backend logic check the input name and append the default proj / dataset if it is not a fully qualified one

The issue should be introduced via this commit: https://github.com/ibis-project/ibis/commit/5b009d2e2775f263628af12723cce6714cad6d22

### What version of ibis are you using?

6.0.0

### What backend(s) are you using, if any?

Bigquery

### Relevant log output

```sh
File "/usr/local/lib/python3.10/site-packages/ibis/backends/bigquery/__init__.py", line 480, in create_table
    self.raw_sql(f'CREATE TABLE {table_ref} AS ({sql_select})')
  File "/usr/local/lib/python3.10/site-packages/ibis/backends/bigquery/__init__.py", line 287, in raw_sql
    return self._execute(query, results=results, query_parameters=query_parameters)
  File "/usr/local/lib/python3.10/site-packages/ibis/backends/bigquery/__init__.py", line 271, in _execute
    query.result()  # blocks until finished
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result
    do_get_result()
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Invalid project ID 'gcp-project-default.bq_dataset_default.gcp-correct-project'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domai
n name separated by a colon. IDs must start with a letter and may not end with a dash.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue @maxshine!

Can you show the code that generated the traceback? Thanks!

**Comment by cpcloud** [comment]
It looks like maybe you're trying to write this:

```
con.create_table("project.dataset.table")
```

I think what you might want is:

```
con.create_table("table", ..., database="project.dataset")
```

**Comment by maxshine** [comment]
Hi @cpcloud 

Thanks for the prompt reply.

The code I used to init the Table obj is like this `con.table("proj.dataset.table")`. and finally I use this line to execute the stmt `con.create_table(name=name, obj=obj, database=database)`, in which the obj is created via the select on the table initted beforehand.

And the query causes the exception I pasted in traceback, that the selected table name is not corrected formatted

**Comment by maxshine** [comment]
I also created a small PR for this issue: https://github.com/ibis-project/ibis/pull/6717

If anyone can review it, I really appreciate it.

**Comment by cpcloud** [comment]
I think you may just need to write the `con.table` like this:

```python
con.table("table", database="proj.dataset")
```

Does that work for you?

**Comment by maxshine** [comment]
Thanks, I believe it also works. But I also think it should accept the table name as a whole fully qualified format. What do you think? :)

**Comment by maxshine** [comment]
To add some, my project used 5.1  which worked well with the existing project implementation with proj.dataset.table to init a Table obj.  Then the 6.0.0 breaks it. I hope the latest 6.0 version can be compatible backwards.

**Comment by cpcloud** [comment]
Interesting, I didn't realize it was a regression. Thanks for that information. Let me do a bit of investigation.
