### ISSUE TITLE
bug: function arbitrary doesn't seem to work with clickhouse

### ISSUE THREAD

**Issue by rongxin-yu** [ibis-project/ibis#6718]
### What happened?

When I try to run the following ibis code
`con = ibis.clickhouse.connect()`
`t = con.table('test')`
`t.groupby('a').aggregate(t.b.arbitrary())`

The `arbitrary` function will be translated into `Any` in sql, however that doesn't seem to be supported

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

clickhouse

### Relevant log output

```sh
Code: 46. DB::Exception: Unknown function ANY. Maybe you meant: ['and']: Or unknown aggregate function ANY. Maybe you meant: ['any']: While processing SELECT order_uid, ANY(id) AS id FROM table group by order_uid
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This seems to be working as intended on `master`:

```
In [13]: from ibis.interactive import *

In [14]: con = ibis.clickhouse.connect(host="localhost", database="ibis_testing")

In [15]: t = con.tables.array_types

In [16]: t.columns
Out[16]: ['x', 'y', 'z', 'grouper', 'scalar_column', 'multi_dim']

In [17]: t[["grouper", "scalar_column"]]
Out[17]:
┏━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ grouper ┃ scalar_column ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ string  │ float64       │
├─────────┼───────────────┤
│ a       │           1.0 │
│ a       │           2.0 │
│ a       │           3.0 │
│ b       │           4.0 │
│ b       │           5.0 │
│ c       │           6.0 │
└─────────┴───────────────┘

In [18]: t.grouper.arbitrary()
Out[18]: 'a'

In [19]: t.group_by("grouper").agg(value=_.scalar_column.arbitrary())
Out[19]:
┏━━━━━━━━━┳━━━━━━━━━┓
┃ grouper ┃ value   ┃
┡━━━━━━━━━╇━━━━━━━━━┩
│ string  │ float64 │
├─────────┼─────────┤
│ b       │     4.0 │
│ c       │     6.0 │
│ a       │     1.0 │
└─────────┴─────────┘
```

This looks like a bug in `sqlglot` that was fixed awhile ago. Can you try upgrading `sqlglot`?

**Comment by cpcloud** [comment]
Hm, it's possible that it could also a be a function that doesn't exist in your version of clickhouse.

**Comment by rongxin-yu** [comment]
> This seems to be working as intended on `master`:
> 
> ```
> In [13]: from ibis.interactive import *
> 
> In [14]: con = ibis.clickhouse.connect(host="localhost", database="ibis_testing")
> 
> In [15]: t = con.tables.array_types
> 
> In [16]: t.columns
> Out[16]: ['x', 'y', 'z', 'grouper', 'scalar_column', 'multi_dim']
> 
> In [17]: t[["grouper", "scalar_column"]]
> Out[17]:
> ┏━━━━━━━━━┳━━━━━━━━━━━━━━━┓
> ┃ grouper ┃ scalar_column ┃
> ┡━━━━━━━━━╇━━━━━━━━━━━━━━━┩
> │ string  │ float64       │
> ├─────────┼───────────────┤
> │ a       │           1.0 │
> │ a       │           2.0 │
> │ a       │           3.0 │
> │ b       │           4.0 │
> │ b       │           5.0 │
> │ c       │           6.0 │
> └─────────┴───────────────┘
> 
> In [18]: t.grouper.arbitrary()
> Out[18]: 'a'
> 
> In [19]: t.group_by("grouper").agg(value=_.scalar_column.arbitrary())
> Out[19]:
> ┏━━━━━━━━━┳━━━━━━━━━┓
> ┃ grouper ┃ value   ┃
> ┡━━━━━━━━━╇━━━━━━━━━┩
> │ string  │ float64 │
> ├─────────┼─────────┤
> │ b       │     4.0 │
> │ c       │     6.0 │
> │ a       │     1.0 │
> └─────────┴─────────┘
> ```
> 
> This looks like a bug in `sqlglot` that was fixed awhile ago. Can you try upgrading `sqlglot`?

Thanks @cpcloud 

This was caused by the fact that clickhouse is case-sensitive. After upgrading sqlglot (only allowed with ibis 6.0.0), the generated SQL changed `Any` to `any` and fixed the issue.
