### ISSUE TITLE
feat: document Array.__add__()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6720]
### Is your feature request related to a problem?

I was looking for Array.concat(), and couldn't find it. I had to go try `a + b`, and that worked, but that would be nice if it was discoverable.

### Describe the solution you'd like

Add __add__() to the docs. OR perhaps just add in an explicit `.concat()` method to Arrays so it is even easier. At least in the __add__method docstring include the keyword concat so that it shows up in search.

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

Na

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This makes sense to me. I'll do the same for `__mul__` and add a `repeat` method. We've got one for strings with the equivalent Python behavior.
