### ISSUE TITLE
bug(pyarrow): Decimal not supported in to_pyarrow()

### ISSUE THREAD

**Issue by kmagusiak** [ibis-project/ibis#6731]
### What happened?

Calling `tab.to_pyarrow()` results in `NotImplementedError: Unsupported type: Decimal(precision=8, scale=2, nullable=False)`. Probably https://arrow.apache.org/docs/python/generated/pyarrow.decimal128.html should be used.

```
AlchemyTable: test_table
  id             !int32
  statement_file string
  date           !date
  amount         !decimal(18, 2)
  description    string
  parsed         boolean
  counterparty   string
  tags           string
```

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

SQLite, DuckDB, pyarrow

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @kmagusiak 👋🏻 and thanks for the issue!

I believe this is fixed in 6.0.0 by https://github.com/ibis-project/ibis/pull/5967.

Can you give that a try?
