### ISSUE TITLE
feat: Better repr in VSCode debugger

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6746]
### Is your feature request related to a problem?

This is pretty specific to my workflow, and I have a workaround, so I understand if you don't make this a priority. I can submit a PR to fix this if you can point me in the right direction, but I don't have much experience with terminals etc

If I run a debugger session in VSCode and look at a table, the ANSI codes (I think that's what they are) from Rich are printed literally, which makes it pretty unreadable:

<img width="212" alt="image" src="https://github.com/ibis-project/ibis/assets/10820686/93ff52a8-0f13-43df-ab73-eb6a7c4d59c2">

[It looks like the VScode debugger should be able to render ANSI codes?](https://github.com/microsoft/vscode/issues/21423) Not sure how I can double check this.

### Describe the solution you'd like

1. Ibis/Rich could tell that the terminal can't handle it, and print a version without ANSI codes.
2. as an alternative, if we could detect the debugger, then repr() could instead of going through rich, use .to_pandas() as the renderer.

Bonus/sidenote: if we go about the work of detecting the debugger, it would be even nice if `ibis.options.interactive` was treated as True whenever in the debug environment.

### What version of ibis are you running?

5.1.0

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

This doesn't seem like an ibis-specific problem at first glance.

Can you try running `python -m rich.color` in the debug console?

Here's a screenshot of what the first ~70 rows look like in my terminal

![image](https://github.com/ibis-project/ibis/assets/417981/5934cbc3-96cf-4b0e-be92-6243d13e24ce)

**Comment by NickCrews** [comment]
hmmm, I'm not starting with the same debug console as you. I am getting to the debug console by going to a notebook, adding a breakpoint somewhere in my code, and then debugging a cell:

<img width="266" alt="image" src="https://github.com/ibis-project/ibis/assets/10820686/550dd5f2-671b-45a1-a2d0-c742e05fe221">

Doing it this way, my debug console is the python interpreter, not the unix shell, so I can't `python -m` anything. I am already inside the python process. How are you getting to that debug console?

**Comment by cpcloud** [comment]
Hm, I'm not using vscode.

I bet we could figure out whether this is a vscode issue if we did some pairing.

Shoot me an email and we can set up some time.

**Comment by cpcloud** [comment]
With this version of VS Code:

```
❯ code --version
1.80.2
2ccd690cbff1569e4a83d7c43d45101f817401dc
x64
```

I see this output in the debug console:

![image](https://github.com/ibis-project/ibis/assets/417981/61475317-74d3-4733-a690-386f2c82fe73)

Admittedly it doesn't render colors, but it's not showing raw ANSI escape codes either.

Can you reproduce this with a code snippet that involves no additional code beyond ibis?

**Comment by NickCrews** [comment]
OK, so i see the same thing as you if I debug a .py file. It only becomes garbled if I debug a .ipynb. @cpcloud can you try that same bit of a code in a .ipynb file?

FYI I have vscode 1.80.2

**Comment by cpcloud** [comment]
Would you mind printing out something using just rich, that doesn't involve ibis?

I'd like to rule out rich as the problem, and I don't really have the bandwidth to set up vscode notebooks.

**Comment by NickCrews** [comment]
This is something to do with how vscode chooses to render python objects. If I print explicity, it works:

<img width="541" alt="image" src="https://github.com/ibis-project/ibis/assets/10820686/9b0fd306-7f6f-42e5-acfe-f3792cc0a88f">

This is not ibis-specific:
```python
console = Console()
with console.capture() as capture:
    console.print("[bold red]Hello[/] World")
str_with_ansi = capture.get()


class WithAnsi:
    def __repr__(self):
        return str_with_ansi


wa = WithAnsi()
```
If I enter a debugger, then `wa` gives the garbled output, but `print(wa)` gives correct output.

I'll close this cuz it is not ibis's fault.
