### ISSUE TITLE
feat(sql-backends): Clarify distinction between database and schema

### ISSUE THREAD

**Issue by binste** [ibis-project/ibis#6754]
### Is your feature request related to a problem?

I'm a bit confused with the distinction of `database` and `schema` for the duckdb backend. When connecting to a local file with
```python
import ibis
con = ibis.duckdb.connect("test.db")
```
I get the following when listing databases:
```python
con.list_databases()
```
```python
['information_schema',
 'information_schema',
 'information_schema',
 'main',
 'main',
 'main']
```
In #6742 I saw that the values are already deduplicated, however according to that issue `list_schemas` will print the same names. Duckdb supports both multiple databases as well as schemas, see e.g. the [USE command](https://duckdb.org/docs/sql/statements/use.html). I think `list_databases` lists the schema names.

As there seems to be no difference, I can also not specify a schema when connecting. When connecting to Snowflake, I can pass e.g. `database="database_name/schema_name"` (as documented [here](https://ibis-project.org/backends/snowflake/#ibis.backends.snowflake.Backend.do_connect)). However, for the duckdb backend the `database` parameter accepts a file name, see [documentation](https://ibis-project.org/backends/duckdb/#ibis.backends.duckdb.Backend.do_connect) but not a schema name.

I noticed this while trying to create a table in a different schema then `main`:

```python
import ibis
import pandas as pd

df = pd.DataFrame([[1, 2]], columns=["a", "b"])
con = ibis.duckdb.connect("test.db")

con.raw_sql("create or replace schema test_schema")
# How can I specify "test_schema" here?
con.create_table("test_table", obj=df)
```

With duckdb itself, I'd do the following:
```python
con = duckdb.connect("test.db")
con.execute("create or replace schema test_schema")
con.execute(
                "create table test_schema.test_table"
                + " as select * from df"
            )
```

### Describe the solution you'd like

Be able to specify a schema when creating a table and in general referring to tables.

### What version of ibis are you running?

6.0.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue @binste!

I've got a PR up (#6753) to straighten this particular issue out (and a few related changes).

**Comment by cpcloud** [comment]
Here's an example of the new output for `list_databases` and `list_schemas`:

```
In [1]: from ibis.interactive import *

In [2]: con = ibis.duckdb.connect()

In [3]: con.list_databases()
Out[3]: ['memory', 'system', 'temp']

In [4]: con.current_database
Out[4]: 'memory'

In [5]: con.list_schemas()
Out[5]: ['information_schema', 'main', 'pg_catalog']

In [6]: con.current_schema
Out[6]: 'main'
```

**Comment by binste** [comment]
Thanks for the quick reply and looking into it, much appreciated! The example outputs look great.

**Comment by cpcloud** [comment]
I'll edit this issue to reflect the database/schema mixup only, so it can be closed when the PR lands, and we can track usage of schema in table creation and access in https://github.com/ibis-project/ibis/issues/6489.
