### ISSUE TITLE
Add `tol` parameter to `nullifzero` method

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#677]
To set values to null if they are sufficiently close to zero

**Comment by cpcloud** [comment]
This seems unnecessary since we already have `t.column.nullif(x.abs() <= tol)`.

**Comment by cpcloud** [comment]
Actually, `nullif` is only equality, not a generic predicate. Repoening and moving to 0.12

**Comment by cpcloud** [comment]
`CASE` statements are a workaround for this for now. Closing.
