### ISSUE TITLE
feat: combine scalar from one table with column from other table

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6800]
### Is your feature request related to a problem?

I'm not sure if this is even possible with SQL, I was playing around with duckdb and I couldn't get it to work, but it seems like it should be possible (ie "well-defined") to me, so I was guessing I just didn't find the right SQL. If this isn't possible in SQL then feel free to close this.

```python
import ibis

t1 = ibis.examples.penguins.fetch()
t2 = ibis.examples.penguins.fetch()
t1.body_mass_g + t2.body_mass_g.max()
# gives `RelationError: Cannot convert  expression involving multiple base table references to a projection`
```

### Describe the solution you'd like

The above should work.

### What version of ibis are you running?

6.0.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
It's possible, using `CROSS JOIN`:

`CROSS JOIN`:

```sql
with bm_max as (select max(body_mass_g) as bmx from other_penguins)
select t.body_mass_g + bmx from penguins t cross join bm_max
```

**Comment by NickCrews** [comment]
Ah, I see, the problem was that I needed to do the max() inside the CTE, thank you!

So, can we make Ibis clever enough to do this for us?

**Comment by cpcloud** [comment]
I realized there's another way that doesn't involve an explicit cross join:

```
select body_mass_g + (select max(body_mass_g) from other_penguins)
from penguins
```
☝🏻 might be easier to give sane behavior to than cross join rewrites.

**Comment by NickCrews** [comment]
related to #7655.

Yes this is good to close, the code snippet I posted now works on `master`! Thanks!
