### ISSUE TITLE
feat: Pass in mapping to Table.relabel() as **kwargs

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6801]
### Is your feature request related to a problem?

Often, I only am relabeling a single column using a simple boilerplate mapping. Needing to construct a dict with the string literals makes things less more verbose. I like the kwargs API of .select() and .mutate(), I wished .relabel() was consistent with that.

### Describe the solution you'd like

`t.relabel(**{"old": "new"})` should be able to be converted to `t.relabel(old="new")`

EDIT: this should actually be `t.mutate(new=_.old)`
Note that this is slightly different from `t.mutate(old=_.new)` (and thus I can't use that), because

1. column order is preserved with .relabel()
2. if "new" already exists, .relabel() errors, .mutate() does not

I think something like:

```python
# Use / to force `substitutions` to be positional-only
def relabel(self, substitutions = None, /, **kwargs: dict[str, str]) -> Table:
    if kwargs:
        if substitutions is not None:
            raise TypeError("Cannot specify both substitutions and kwargs")
        substitutions = kwargs
    # continue with old logic
```

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

I think the argument order would be swapped, like this:

```
t.relabel(new="old")
```

since that is how `mutate` works.

**Comment by cpcloud** [comment]
What's the problem with allowing both `substitutions` and `kwargs`?

**Comment by jcrist** [comment]
> I think the argument order would be swapped, like this:

That's opposite how relabel currently works. I personally would find it a bit confusing if `t.relabel(subs)` and `t.relabel(**subs)` weren't equivalent.

**Comment by cpcloud** [comment]
Perhaps we should decide whether we just accept the inconsistency, or change relabel to match our other methods.

**Comment by jcrist** [comment]
I do agree that `new_name=old_name` is more consistent with our other methods. It also better matches dplyr's `renmae`.

I'm not sure of a smooth way to deprecate this though; we could warn based on if columns are missing in the values but present in keys (indicating that the old syntax was used)?

**Comment by cpcloud** [comment]
Not a huge fan of this, but one possibility is to introduce a new method `rename` that has the desired behavior and deprecate `relabel`.

I suspect relabel is used a lot though 😬

**Comment by jcrist** [comment]
That's not a bad idea, and would be more robust than what I suggested. I've also found `relabel` to be a bit of a surprising name (I don't think we refer to column names as labels anywhere else). +1.

**Comment by NickCrews** [comment]
> t.mutate({'a': 'b'})
> t.relabel({'b': 'a'})

This has bitten me in the past. I would love for the order to be consistent.

> What's the problem with allowing both substitutions and kwargs?

What if they conflict? eg substitutions="{name}_suffix" and kwargs={"col": "prefix_col"}

> I personally would find it a bit confusing if t.relabel(subs) and t.relabel(**subs) weren't equivalent.

+1 to this, they must lead to the same thing.

+1 to rename() when I first came to Ibis I always got that wrong and I don't see how rename() is any worse.

**Comment by lostmygithubaccount** [comment]
> Not a huge fan of this, but one possibility is to introduce a new method `rename` that has the desired behavior and deprecate `relabel`.

I'm +1 on this too

> I suspect relabel is used a lot though 😬

almost certainly, but could give a deprecation warnings for a while? what's the typical deprecation policy?

**Comment by NickCrews** [comment]
Thinking about the .rename(kwargs) vs .rename(**kwargs), what about if we just kept it simpler and disallowed the .rename(kwargs) version? .mutate() and .select() don't support them. If I have a mapping it is pretty easy to add the ** in front.
