### ISSUE TITLE
feat: `Table.relocate` method

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#6803]
often a user will want to change the order of columns, see linked discussion

---

We could consider adding a `Table.relocate` method, similar to [R's method of the same name](https://dplyr.tidyverse.org/reference/relocate.html).

_Originally posted by @cpcloud in https://github.com/ibis-project/ibis/discussions/6795#discussioncomment-6662292_

**Comment by NickCrews** [comment]
I would enjoy this. I often want to group like columns together, so IDK if that would be supported, eg `t.relocate(["usr_*", "acct_*", "session_*"])`

Or, I want to bump a column to be first or last, eg `t.relocate(first="primary_key")`

I think it would be great to try to come up with as many of these patterns as possible so we choose an API that works for a lot of them.
