### ISSUE TITLE
feat(ddl): `create_table` should support inserting into different schemas

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#6821]
### Discussed in https://github.com/ibis-project/ibis/discussions/6402

<div type='discussions-op-text'>

<sup>Originally posted by **nikhilmakan02** June  8, 2023</sup>
Hi All

I am wondering if we have a pandas DataFrame can this be appended to an existing table in a MSSQL database using Ibis? I thought I saw this in the docs somewhere but after running through it again I can't seem to find it.

I am using MSSQL as my backend, I know I can build a query expression in SQL and execute this through Ibis as one option.

Thanks!</div>

**Comment by gforsyth** [comment]
```python
[ins] In [29]: team = con.tables.team

[ins] In [30]: team
Out[30]: 
┏━━━━━━━━┓
┃ name   ┃
┡━━━━━━━━┩
│ string │
├────────┤
│ john   │
│ joe    │
└────────┘

[ins] In [31]: df = pd.DataFrame.from_dict({"name": ["frank", "bob"]})

[ins] In [32]: con.insert("team", df)

[ins] In [33]: team
Out[33]: 
┏━━━━━━━━┓
┃ name   ┃
┡━━━━━━━━┩
│ string │
├────────┤
│ john   │
│ joe    │
│ frank  │
│ bob    │
└────────┘

[ins] In [34]: con
Out[34]: <ibis.backends.mssql.Backend at 0x76ee527a9f00>
```

stick a fork in it.
