### ISSUE TITLE
feat: handling of Postgres 9.3 Lateral Joins

### ISSUE THREAD

**Issue by earino** [ibis-project/ibis#683]
Lateral joins are a new feature in Postgres 9.3, from the [docs](https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.3#LATERAL_JOIN):

> Put simply, a LATERAL JOIN enables a subquery in the FROM part of a clause to reference columns from preceding items in the FROM list.

And an example query:

```
SELECT base.nr,
   multiples.multiple
FROM (SELECT generate_series(1,10) AS nr) base,
LATERAL (
    SELECT multiples.multiple FROM
      ( SELECT generate_series(1,10) AS b_nr, base.nr * 2 AS multiple ) multiples
           WHERE multiples.b_nr = base.nr
      ) multiples;
```

**Comment by cpcloud** [comment]
@earino I know it's been a while, but can you state whether there's something you can't express with ibis that would require `LATERAL join`?

**Comment by cpcloud** [comment]
It's been about a month, closing.
