### ISSUE TITLE
bug: unable to repr empty schema

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#6837]
### What happened?

```py
In [1]: import ibis
In [2]: ibis.table({}, name="e")
```

results in

```
File ~/Workspace/ibis/ibis/expr/format.py:151, in fmt_schema(schema)
    138 """Format `schema`.
    139
    140 Parameters
   (...)
    148     Formatted schema
    149 """
    150 names = schema.names
--> 151 maxlen = max(map(len, names))
    152 cols = [f"{name:<{maxlen}} {typ}" for name, typ in schema.items()]
    153 depth = ibis.options.repr.table_columns
```

### What version of ibis are you using?

master

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This should raise an error. An empty schema should fail to construct.

**Comment by kszucs** [comment]
I think we should allow constructing empty schemas. For example both pyarrow and pandas allow defining empty schemas:
- `pd.DataFrame(columns = [])`
- `pa.schema({})`

**Comment by cpcloud** [comment]
I don't think there's any value in them. What's the use case?

**Comment by kszucs** [comment]
```py
def pick_columns(table, column_list):
    actual_column_names = [f"c_{name}" for c in column_list]
    return table[actual_column_names]
```

if we disallow empty schemas the user of `pick_columns()` must be aware of the limitation and must place additional branches to handle it

```py
if column_list:
    table = pick_columns(table, column_list)
else:
   raise InputError("must provide at least a column")
```

or 

```py
try:
    table = pick_columns(table, column_list)
except ValidationError:
    raise InputError("must provide at least one column")
```

whereas `query_the_columns_im_interested_in([])` could return a table with an empty schema, so chaining the operations would be simpler.

Additionally I think it is more sound type-wise to support empty schemas.

**Comment by cpcloud** [comment]
> if we disallow empty schemas the user of pick_columns() must be aware of the limitation 

Why? There would be an error raised by the `Table.__getitem__` implementation. Why would anything about what the user is aware of need to change?

> Additionally I think it is more sound type-wise to support empty schemas.

Can you elaborate here? We can easily spell the length constraint with patterns, so I'm not sure how soundness is affected.

**Comment by kszucs** [comment]
Another aspect then, the user has an empty pyarrow table or pandas dataframe. 
Calling ibis memtable on that input would fail, as a user I'd be surprised since they are valid in the other framework.

**Comment by NickCrews** [comment]
I would vote for allowing empty schemas. What is the benefit of disallowing them?
