### ISSUE TITLE
Handling of Postgress 9.4 WITH ORDINALITY

### ISSUE THREAD

**Issue by earino** [ibis-project/ibis#684]
WITH ORDINALITY is a new feature in Postgres 9.4, from the [docs](https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.4#WITH_ORDINALITY):

> Set-returning functions are most frequently used in the FROM clause of a query, and now if it's suffixed with WITH ORDINALITY, a column containing an ordered sequence of numbers is added.

For example:

```
 postgres=# SELECT * FROM json_object_keys('{"mobile": 4234234232, "email": "x@me.com", "address": "1 Street Lane"}'::json) WITH ORDINALITY;
  json_object_keys | ordinality 
 ------------------+------------
  mobile           |          1
  email            |          2
  address          |          3
 (3 rows)
```

**Comment by cpcloud** [comment]
Can this be done with a window function?

**Comment by cpcloud** [comment]
This requires an `unnest` API, so closing for now.
