### ISSUE TITLE
feat(snowflake): catch file IO issues prior to attempting PUT

### ISSUE THREAD

**Issue by IndexSeek** [ibis-project/ibis#6863]
### Is your feature request related to a problem?

With adding direct "read_*" support on various file formats with the Snowflake backend, I think using the client to perform simple checks ahead of execution to bail early might be worthwhile. 

The current order of operations is as follows:
1. Create a temporary stage.
2. Create a temporary file format. (1 or 2 depending on schema inference format). 
3. PUT a file into the recently created stage.
4. Create a temporary table with INFER_SCHEMA from the stage with the file format specified.
5. COPY INTO table with file format specified, if needed.

Potential improvements:
- Bail early if the specified file to read isn't available to the client. If the file isn't present, it makes it to step 3 (above) and fails. Since the stage and file format are temporary, these fall away with the session, but we don't need to begin initiating commands if we can ensure they will fail due to an existing error. 
- Is it worthwhile to preemptively catch file format specifications if they are incompatible or allow the query to fail and return the connector's error message? That could be a lot of maintenance here as the provider could modify the configuration, but it would prevent the additional queries that would inevitably fail regardless. 

Potential Pitfalls/Concerns:
- Ensure proper formatting of file input: URI path, str, etc., for comparisons. 
- If glob patterns are allowed, this could help check exact or wild card matching patterns, but `file://penguins.avro` might not work and must be translated to a pathlib Path. 
- Is doing this too much handholding with a specific backend? Let the error roll through?

### Describe the solution you'd like

I'm currently seeing something like

```
ProgrammingError: (snowflake.connector.errors.ProgrammingError) 253006: File doesn't exist: ['penguins_F.avro']
[SQL: 
        PUT 'file://penguins_F.avro' @_ibis_stage_epdnjikvvfh3tpxkevgx7xvr24
        PARALLEL = 32
        AUTO_COMPRESS = FALSE
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

Having the error raised before statement execution could speed things up to help the user sooner. 

### What version of ibis are you running?

6.1.0

### What backend(s) are you using, if any?

Snowflake

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@IndexSeek Thanks for the issue!

Do you have an idea of how long "time to to first error" is in the case the file is invalid in some way (doesn't exist, wrong format, etc)?

My main concern is that the number of ways things can go wrong here is very large, and trying to account for all (or event most!) up front may be a very long game of whack-a-mole.

I could see an existence check, but at some point there's going to be an `open` syscall that will fail, and IME it usually suffices to let that bubble up.

To address some specific concerns:

> Ensure proper formatting of file input: URI path, str, etc., for comparisons.

Right now we're using `Path(path).absolute().as_uri()` which should be a robust way to get a `file://` URI on any platform.

> If glob patterns are allowed, this could help check exact or wild card matching patterns, but `file://penguins.avro` might not work and must be translated to a pathlib Path.

I'm not sure I follow exactly what we can improve here. Perhaps we should try implementing globs first 😅 

> Is doing this too much handholding with a specific backend? Let the error roll through?

I think so 😂

The error you show from trying to read a non-existent Avro file looks pretty solid to me!

**Comment by sfc-gh-twhite** [comment]
> @IndexSeek Thanks for the issue!
> 
> Do you have an idea of how long "time to to first error" is in the case the file is invalid in some way (doesn't exist, wrong format, etc)?

The average time taken for each loop iteration to complete is 470 ms. This delay may be due to Snowflake's processing and communication time to the client. 

I don't think there is any way to do any upstream format checking, but I can do an existing check pretty safely without compromising where the computing would happen to avoid the `ER_FILE_NOT_EXISTS = 253006` error. I'm still not sure if the "juice is worth the squeeze" here, as they say. 

> Right now we're using `Path(path).absolute().as_uri()` which should be a robust way to get a `file://` URI on any platform.

I agree, I think that is a safe way to do it. 

> > If glob patterns are allowed, this could help check exact or wild card matching patterns, but `file://penguins.avro` might not work and must be translated to a pathlib Path.

> I'm not sure I follow exactly what we can improve here. Perhaps we should try implementing globs first 😅

I started down this road, and after doing this, it feels like overkill, haha. 

```
from pathlib import Path

def encode_existing_files_with_wildcards(wildcard_pattern):
    dir_path = Path("/".join(wildcard_pattern.split("/")[:-1]))

    if any(file.is_file() for file in dir_path.glob(wildcard_pattern)):
        return Path(wildcard_pattern).expanduser().absolute().as_uri()
    else:
        raise ValueError("Invalid File Path: No matching files found.")

encode_existing_files_with_wildcards("pengui*.csv")
```

> The error you show from trying to read a non-existent Avro file looks pretty solid to me!

Thank you! I was working on trying to add Snowflake `read_avro` but was struggling to figure out how to test it without introducing a new dependency.

**Comment by cpcloud** [comment]
@sfc-gh-twhite In theory you should be able to upload an Avro file if Snowflake supports running `INFER_SCHEMA` on that file. Looking at [the relevant docs](https://docs.snowflake.com/en/user-guide/data-load-overview#label-detect-column-definitions-in-semi-structured-data-files) it seems like it does!

**Comment by cpcloud** [comment]
Also, we recently added glob support to snowflake's `read_*` functions :)

**Comment by cpcloud** [comment]
Closing as I think we're going to let this fall through to the backend for now.
