### ISSUE TITLE
feat: 'pip install ibis-framework' includes the default backend

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#6888]
if a user installs just `ibis-framework` with pip, they have no backend to use. we should install the default (DuckDB) backend in this case so they can get started without even thinking about backends

**Comment by jcrist** [comment]
I understand the desire for this, but I'm not sure it's possible without negative consequences for other users. `pip` currently lack's support for extras (e.g. `ibis-framework[snowflake]`) to exclude packages available in the base install (`ibis-framework`). Thus if `ibis-framework` included the `duckdb` backend, then there'd be no way to install other backends without including `duckdb` as a dependency.

---

One option: if we instead split the backend-specific code/dependencies into a bunch of separate subpackages, we could handle this using typical dependency management:

```
ibis-core: shared core, minimal common install dependencies only
ibis-framework: depends on ibis-duckdb, since it's our default backend currently
ibis-duckdb: depends on ibis-core & duckdb backend dependencies
ibis-snowflake: depends on ibis-core & snowflake backend dependencies
...
```

This is also how our conda packages are managed currently. This could be done by splitting out the backend code into separate packages (but still keeping them all in the same `ibis` repo), or through a hack by having all but the `ibis-core` library be "dependency-only" packages with no real code of their own.

To be clear: I'm not sure any benefit is worth the immediate engineering effort. But if we did decide to go through with this I'd expect after any immediate churn to make this work there wouldn't be a huge ongoing maintenance cost.

**Comment by ianmcook** [comment]
For reference, the DuckDB wheels are ~10–30 MB.

**Comment by kszucs** [comment]
Since pandas is a hard dependency of ibis (at least for now), there must be at least one backend already available with the `ibis-framework` package installed.

**Comment by cpcloud** [comment]
Perhaps it can suffice for now to avoid writing naked `pip install ibis-framework` commands in our documentation?

**Comment by lostmygithubaccount** [comment]
I think that's sufficient -- my take is this would be nice, maybe switching to core + ibis-{backend} installs as Jim suggested is the way forward. but I wouldn't prioritize this, let's just ensure we don't document it. I'll do a pass in the new Quarto docs

**Comment by cpcloud** [comment]
SGTM! Let's close this out as soon as that's addressed in the documentation.

**Comment by lostmygithubaccount** [comment]
closing as "not gonna do anything about this anytime soon but if there's popular demand we can probably do something"
