### ISSUE TITLE
feat: support for pyodide

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6889]
### Is your feature request related to a problem?

Being able run ibis in the browser using pyodide would be incredible. I could ship so much better interactivity and dashboards. I'm mostly filing this just so it's on your radar as a potential use case in the future, and so it's recorded somehwere. Feel free to close this since it's not that actionable.

### Describe the solution you'd like

I'm not sure there is really anything specific that ibis would have to do, besides wait for/support the underlying dependencies
- pyarrow: [WASM builds seem to be in the works](https://github.com/pyodide/pyodide/issues/2933).
- sqlite: Already works out of the box. Nothing to do here.
- duckdb: IDK what the story here is. 

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

Na

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kszucs** [comment]
How about datafusion and/or polars? Their pyodide integration could be easier due to the rust toolchain.

**Comment by lostmygithubaccount** [comment]
I believe it's largely blocked on this: https://github.com/pyodide/pyodide/issues/2933

I would be curious how much effort it would be for us to get this over the line, it'd be great for our getting started/documentation experience as well

**Comment by NickCrews** [comment]
datafusion and polars are still blocked by the above pyarrow issue I think.

The test is to go to https://jupyterlite.github.io/demo/lab/index.html and try running `%pip install ibis-framework[sqlite]`, you get 
```
ValueError: Can't find a pure Python 3 wheel for 'pyarrow<13,>=2'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.
```

**Comment by cpcloud** [comment]
This is because we made pyarrow a hard dependency at some point. The sooner we can get pyarrow into pyodide the sooner we can get ibis in the browser.

**Comment by lostmygithubaccount** [comment]
is there any way to push that forward?

**Comment by kszucs** [comment]
Actually polars has an [optional dependency on pyarrow](https://github.com/pola-rs/polars/blob/main/py-polars/pyproject.toml#L41), so its pyodide integration shouldn't be blocked on that.

Regarding ibis' hard arrow dependency: we can make it optional, although it would only make sense if we were implementing a polars output format, so ibis could run entirely upon polars without pandas and without pyarrow.

**Comment by cpcloud** [comment]
I think a `to_polars()` would make sense. For most backends it would probably go through pyarrow first though, so it wouldn't necessarily help with this problem except when using the polars backend. Maybe that's enough for a first pass at pyodide support?

**Comment by NickCrews** [comment]
I personally never use Polars and therefore selfishly would say to keep the API small. Adding .to_polars() just for pyodide seems nearsighted, I bet pyarrow is going to work in the next few months

**Comment by cpcloud** [comment]
> Adding .to_polars() just for pyodide seems nearsighted

Yeah, though I think this is supported for DuckDB incidentally 😂

**Comment by cpcloud** [comment]
I don't think there's anything we can do on the ibis side for this at the moment.
