### ISSUE TITLE
feat: easy and convenient execution over different backends

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#6894]
### Is your feature request related to a problem?

I have an expression depending on in memory tables or e.g. local files, I'd like to be able to easily switch execution over the available backends:

```py
In [1]: import ibis

In [2]: t = ibis.memtable({"words": [["a", "b"], ["a", "c"]]})

In [3]: t.words.unnest().execute()
Out[3]:
0    a
1    b
2    a
3    c
Name: words, dtype: object

In [4]: ibis.polars.execute(t.words.unnest())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 ibis.polars.execute(t.words.unnest())

AttributeError: module 'ibis.polars' has no attribute 'execute'
```

### Describe the solution you'd like

We already expose e.g. `compile()` on `ibis.<backend>` proxies, expose the `execute()` method as well.

If I'm not mistaken it was supported for earlier versions of ibis, so it might be a regression too.

### What version of ibis are you running?

main branch

### What backend(s) are you using, if any?

DuckDB, Polars

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I don't think a top level execute for every backend makes sense. At least half of our backends require connection to a remote resource. What would execute do in those cases?

**Comment by kszucs** [comment]
We could clearly raise in that case, that the backend requires parametrization.

**Comment by rongxinyu** [comment]
I think you can do the following:

`con = ibis.clickhouse.connect()`
`con.execute()`

**Comment by kszucs** [comment]
Sorry, the issue description could be misleading due to using clickhouse as an alternative backend. This feature wouldn't work for backends requiring additional parameters e.g. for a remote connection (like clickhouse). This could be applicable to local backends: `polars`, `duckdb`, `pandas`, `dask`, `datafusion`, `sqlite`.

**Comment by NickCrews** [comment]
what about if you wanted a pyarrow result instead of pandas? Then you need a .to_pandas() and a .to_pyarrow(). I like these explicit calls instead of the implicit .execute()

**Comment by cpcloud** [comment]
I'm not sure the additional code and maintenance is worth it to save a single line of code that is already very concise for the various backends for which this would work.
