### ISSUE TITLE
docs(udfs): document the new UDF APIs

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#6915]
### Is your feature request related to a problem?

Nope!

### Describe the solution you'd like

Documentation for UDFs, per https://github.com/ibis-project/ibis/issues/4707#issuecomment-1686427813.

### What version of ibis are you running?

The latest

### What backend(s) are you using, if any?

All of them

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
I think this would be a nice case for a Concept article (how UDFs work/are implemented in Ibis) and a How-to guide with relevant code snippets (how to use a Python scalar, PyArrow, etc)

**Comment by cpcloud** [comment]
We now have UDF API documentation: https://ibis-project.org/reference/scalar-udfs
