### ISSUE TITLE
deps: update pyspark dependency in the lockfile to 3.4

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#6927]
### What happened?

Apparently pyspark 3.4 now supports python 3.11, see build: https://github.com/ibis-project/ibis/actions/runs/5954276459/job/16150464305?pr=6876#step:13:756

### What version of ibis are you using?

6.1

### What backend(s) are you using, if any?

PySpark

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Did you try doing this?

It doesn't work for other reasons:

1. Pandas 2 isn't supported
2. NumPy>1.24 isn't supported
3. Timestamp support has a rather large break with TimestampType now meaning a timestamp with a time zone and TimestampNTZType meaning a timestamp without a time zone

**Comment by gforsyth** [comment]
I'm going to close this out -- I think if we have a feature request for PySpark 3.4 support we can look into it, but it's going to be a pain until pyspark can play nice with the rest of the ecosystem.
