### ISSUE TITLE
Window (also known as analytic) functions

### ISSUE THREAD

**Issue by robert-lucente** [ibis-project/ibis#695]
I found the blog at http://blog.ibis-project.org/sql-window-functions/.

You are probably aware of how conventional databases handle this type of thing. Just in case, check out the following reference

http://docs.oracle.com/cd/E11882_01/server.112/e41084/functions004.htm#SQLRF06174

For an example of a good write up on analytic fcns, check out Chapter 12 of the book Expert Oracle - Signaure Edition by T Kyte. I tried to attach the pdf but it did not work. Try the Google drive

https://drive.google.com/file/d/0BzUV6hGFqZHUYkd6TUlkYno4Vm8/view?usp=sharing

Perhaps you could use it as a template for a tutorial in Ibis?

Also, I have included as a text file an example of a "complex" query. Perhaps you could use it as a template for a complex exmaple in ibis? I tried to attach the pdf but it did not work. Try the Google drive

https://drive.google.com/file/d/0BzUV6hGFqZHUMFpyM3JqX2oxRms/view?usp=sharing

Humm. Maybe all this stuff already exists in Ibis and I just didn't find it?

**Comment by cpcloud** [comment]
https://ibis-project.org/docs/user_guide/sql.html#window-functions
