### ISSUE TITLE
Imputation operations

### ISSUE THREAD

**Issue by Hamster9** [ibis-project/ibis#696]
From today's [Planet Postgres](https://planet.postgresql.org/):
http://www.joyofdata.de/blog/locf-linear-imputation-postgresql-tutorial/

Is this higher-order than what Ibis is aiming for?

**Comment by wesm** [comment]
Seems perfectly reasonable if a sufficiently general API can be developed for it.

**Comment by cpcloud** [comment]
This would need a use case.
