### ISSUE TITLE
feat: SAP HANA backend

### ISSUE THREAD

**Issue by Excidion** [ibis-project/ibis#6966]
### Is your feature request related to a problem?

I would like to use ibis with a SAP Hana database.

### Describe the solution you'd like

Adding a back end class for Hana, for example based on the existing `BaseAlchemyBackend` together with [sqlalchemy-hana](https://github.com/SAP/sqlalchemy-hana/).

There also exists [this python module](https://pypi.org/project/hdbcli/)  but I don't know which would be the best way forward.

### What version of ibis are you running?

6.1.0

### What backend(s) are you using, if any?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
since this was opened, it looks like the sqlalchemy package has been released several times and updated: https://pypi.org/project/sqlalchemy-hana/#history

**Comment by lostmygithubaccount** [comment]
another option could be building on top of the hana.ml dataframes: https://help.sap.com/doc/1d0ebfe5e8dd44d09606814d83308d4b/2.0.06/en-US/hana_ml.dataframe.html

**Comment by Excidion** [comment]
With Ibis missing Hana support I am using those hana-ml DataFrames right now but must admit they are a bit odd to use. As they mention [here](https://pypi.org/project/hana-ml/) that library is itself build upon the aforementioned `hdbcli`.

**Comment by Excidion** [comment]
> since this was opened, it looks like the sqlalchemy package has been released several times and updated: https://pypi.org/project/sqlalchemy-hana/#history

And the updates keep coming. Seems like there is some life again in the project. With this in mind would it change your proposed solution or do you still think the sqlglot-based backend is the preferable approach?

**Comment by lostmygithubaccount** [comment]
we have since migrated all backends to sqlglot -- sqlalchemy is no longer a dependency for any backend (we'll have a blog on that soon, and these changes will be released in 9.0.0 very soon)

@Excidion any change you'd be up for contributing this? we don't exactly have a new backend guide since the refactor to SQLGlot but could provide guidance

**Comment by Excidion** [comment]
I am no expert on either ibis or SAP Hana. So some documents to look into how to get started and what is even needed would be very helpful. Even just to know the size/scope. Do you have some links? Or is this backend guide you mentioned somewhere on the horizon?

**Comment by cpcloud** [comment]
If someone is still interested, taking a look at the postgres backend or the duckdb backend in `ibis/backends/{postgres,duckdb}/__init__.py` would be the place to start.

Closing as not planned, as we won't be implementing this ourselves.
