### ISSUE TITLE
feat: Better tempfile deletion

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6974]
### Is your feature request related to a problem?

I have slowly been running out of disk space on my laptop over the last few months. I just investigated, and it was due to 32Gb of temp files in `/Users/nickcrews/.cache/ibis-duckdb/`. This must have been due to repeated process crashing and the temp files never getting cleaned up.

### Describe the solution you'd like

Ideally, these files get cleaned up automatically.

relevant code is at https://github.com/ibis-project/ibis/blob/d4ea3bf05a77a291b209c288d60dcc806cae7f75/ibis/backends/duckdb/__init__.py#L205-L210

Why not make the temp directory be under `/tmp`, which if I understand correctly is wiped at every boot? Really, I think these temp files should get cleaned up at the end of each process, right, since duckdb is in-process? I think XDG_CACHE_HOME is meant for between-run caches, like `pip` might use.

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

duckdb, but perhaps other backends also suffer?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
I did one time have 1.4 TB in there (silly cross join I let run for hours)

**Comment by cpcloud** [comment]
> Why not make the temp directory be under `/tmp`, which if I understand correctly is wiped at every boot?

It's complicated 😄

`/tmp` is only wiped at boot if your system uses tmpfs for `/tmp` which isn't always the case. You can use whatever file system you want to back `/tmp`. We can't really assume it's anything about the lifetime of the bytes in `/tmp`.

The primary reason to not use `/tmp`-backend-by-tmpfs is because it is [backed by virtual memory](https://www.kernel.org/doc/html/latest/filesystems/tmpfs.html#tmpfs), so you're not actually getting spill-to-disk behavior by using it.

Finally, the system temporary directory can pretty much be anything, it doesn't have to be `/tmp`.

These are the main reasons we chose to use a location that is very likely to be actual hard disk.

As to the issue of disk space filling up, I suspect it's a DuckDB issue: ibis simply sets the location of the temporary directory, but has no hand in its cleanup.

Do you have an example where the data are spilled to disk and not clean up on a successful exit of the process?

**Comment by cpcloud** [comment]
Regarding unsuccessful exits of the Python process: that's yet more complicated and depends on what caused the shutdown of the program. If it's a signal then that depends on what signal it is 😄.

Yep, it's all kind of a mess.

For example `SIGKILL` cannot be handled by a program, but `SIGTERM` and `SIGINT` can, for example.

However, a program can exit with a non-zero exit code and still clean up correctly. If that's what's happening then we should try to isolate an example where this happens and report it upstream.

**Comment by cpcloud** [comment]
So far, I've only be able to get duckdb to fail to clean up when I issue a `pkill duckdb` command in the middle of a query that spills to disk:

```
duckdb <<< "set temp_directory = './test'; set memory_limit = '1GB'; create table t as select * from range(1000000000);"
```

This is expected: `SIGKILL` cannot be handled.

I'm going to close this as unplanned, as things are working the way they are intended given the constraints and systems involved.

**Comment by NickCrews** [comment]
this seems like it is an upstream issue, want to file with duckdb? I would do that, but it appears you have thought about this more than I have, so you would probably write it better 🤣 

> Do you have an example where the data are spilled to disk and not cleaned up on a successful exit of the Python process?

I think I only have experienced this when I SIGKILLed it, and therefore the leftover files is expected behavior. So no, I don't think there is a bug.

Should we handle this out of band? ie the process isn't responsible for cleaning itself up, because per above, this is by definition not always possible. Instead, when we create a new duckdb connection, we check for orphaned temp dirs from old runs, and remove then? Something like

1. list all dirs under `.../ibis-duckdb/`
2. for each of these:
    a. they will be named with a unique key for each process, as "{pid}-{milliseconds since epoch}"
    b. look up the process from that pid. If it doesn't exist, then this dir is orphaned. If it does exist, look at the start time of that process. If the start time does not match, then this dir is orphaned. else, that process is still running, and therefore the dir is not orphaned.
    c. If orphaned, remove that dir
3. Continue as normal, but we create our temp dir following this scheme, so that sibling followup process can clean up after us.

**Comment by NickCrews** [comment]
@cpcloud I see you closed this (which seems reasonable), just tagging you so you saw my above comment.

**Comment by cpcloud** [comment]
I think I am against making something that complex to work around the consequences of `SIGKILL`.

**Comment by NickCrews** [comment]
lol, understandable.
