### ISSUE TITLE
feat: ArrayValue.any() and .all()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6975]
### Is your feature request related to a problem?

I can get emulate .all() with `array_val.filter(lambda x: x).length() > 0` (and similar for .any()), but it would be nice if these were built in.

A downside is that ArrayValue is not typed, so if we had an array of strings, then the expression would happily be constructed, but it would fail at runtime.

### Describe the solution you'd like

see above

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Since they're a subset of array aggregations, closing this in favor of #7073.
