### ISSUE TITLE
Connecting to Impala (S3)

### ISSUE THREAD

**Issue by contang0** [ibis-project/ibis#7011]
Is it at all possible to use Ibis with Impala that uses S3 as the filesystem? [Docs ](https://ibis-project.org/backends/impala/#queries-on-parquet-avro-and-delimited-files-in-hdfs)hint to such possibility:

> For functions like parquet_file and delimited_file, an HDFS directory must be passed **(we'll add support for S3 and other filesystems later)** and the directory must contain files all having the same schema.

However, I see an old issue #1370 which points to the contrary. Have things changed since 2021?

**Comment by jcrist** [comment]
Hi @contang0, thanks for opening this.

S3 is not currently supported in our impala backend (the comment in the docs is old and incorrect, I've removed it in #7088).

The `impala` backend is currently on life-support maintenance mode. We'd happily accept contributions fixing bugs or adding small features, but with 18 backends we're pretty strapped for maintenance support and Impala has fallen to a lower priority.

**Comment by contang0** [comment]
Thank you for clarifying this.

**Comment by contang0** [comment]
@jcrist I was just thinking that a developer guide for those wishing to contribute would be nice to have, as it's indeed not very realistic to expect that Voltron Data alone can support all these backends for years to come.

**Comment by jcrist** [comment]
We do have a contributor guide [here](https://ibis-project.org/contribute/01_environment); if that's insufficient in any way please open an issue so we can improve it (or better yet a PR :)).

Also, while Voltron Data does employ several active Ibis contributors, Ibis itself predates the company's existence and remains an open-source project. There are active contributors that don't work for Voltron Data, and we'd definitely love to grow the contributor base further if you're interested in helping out :).
