### ISSUE TITLE
feat(bigquery): use Pyodide instead of custom transpiler for BigQuery UDFs

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#7014]
### Is your feature request related to a problem?

Current BigQuery UDFs are pretty limited in what they can do. For example, there are no external packages available.

### Describe the solution you'd like

The Pyodide project has made a lot of progress since we last revisited UDFs in BigQuery. I believe it should be possible to use the [pyodide.runPython() JavaScript API](https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.runPython) in a BigQuery JavaScript UDF.

One requirement would be to host Pyodide in a Cloud Storage bucket that is accessible to any Ibis user. Assuming the prototype using Pyodide works out, I would suggest sending a pull request here for hosting: https://github.com/GoogleCloudPlatform/bigquery-utils/tree/master/udfs/js_libs

### What version of ibis are you running?

N/A

### What backend(s) are you using, if any?

BigQuery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@tswast I looked into this for a bit a few days ago, sans Ibis, trying to construct and run a JavaScript UDF in the BigQuery UI and I hit https://github.com/pyodide/pyodide/issues/3893 right away 🙂 

Here's the code I was tinkering with:

```sql
CREATE TEMPORARY FUNCTION my_udf()
RETURNS STRING
LANGUAGE js
OPTIONS (
  library=['gs://ibis-testing-libraries/pyodide.js']
)
AS """
return 1;
""";

SELECT my_udf();
```

This is what I see in the UI:

![image](https://github.com/ibis-project/ibis/assets/417981/234fcc04-0fd6-42a3-bf26-f0847b359acc)

**Comment by tswast** [comment]
Bummer! Thanks for giving it a try. Will watch that issue. Sounds like it's not just a problem for BQ.

**Comment by lostmygithubaccount** [comment]
closing in favor of #6889, should re-consider this issue once supported
