### ISSUE TITLE
Reporting details about Impala errors

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#703]
Impyla doesn't provide much information about errors. @laserson is it possible to get at the details?

```
/Library/Python/2.7/site-packages/ibis/impala/client.pyc in execute(self, stmt, async)
    198             self.cursor.execute_async(stmt)
    199         else:
--> 200             self.cursor.execute(stmt)
    201 
    202     def is_finished(self):

/Library/Python/2.7/site-packages/impala/hiveserver2.pyc in execute(self, operation, parameters, configuration)
    187                            configuration=configuration)
    188         log.info('Waiting for query to finish')
--> 189         self._wait_to_finish()  # make execute synchronous
    190         log.info('Query finished')
    191 

/Library/Python/2.7/site-packages/impala/hiveserver2.pyc in _wait_to_finish(self)
    240                       time.time() - loop_start)
    241             if self._op_state_is_error(operation_state):
--> 242                 raise OperationalError("Operation is in ERROR_STATE")
    243             if not self._op_state_is_executing(operation_state):
    244                 break

OperationalError: Operation is in ERROR_STATE
```

**Comment by laserson** [comment]
I think in this case all I get back is "ERROR_STATE" from HS2.

https://github.com/cloudera/impyla/blob/master/impala/thrift/TCLIService.thrift#L444

**Comment by wesm** [comment]
yes but looks like you can get the error message from `TStatus`

https://github.com/cloudera/impyla/blob/master/impala/thrift/TCLIService.thrift#L409

**Comment by laserson** [comment]
My understanding is that the `TStatus` object encodes the status of the RPC itself, not the query.  I.e., if the `TStatus` object was showing an error, it should've been caught here:

https://github.com/cloudera/impyla/blob/master/impala/hiveserver2.py#L871

Either way, just to make sure, can you reproduce the error above with debug-logging enabled?  It should spit out all the Thrift objects and we'll know for sure.

**Comment by toddlipcon** [comment]
hm, is this still the case? trying to use Impyla in some stress tests and it would be nice to know the error when an error happens

**Comment by wesm** [comment]
I haven't dug into it, but from the thrift definitions in theory you should be able to return the error message from TStatus with the exception.

**Comment by Manoj-red-hat** [comment]
Issue reproduced please find attached debug logs.
>Please help me how to recover from this.
[debug-log.txt](https://github.com/cloudera/ibis/files/555271/debug-log.txt)

**Comment by cpcloud** [comment]
The impala backend will continue to have subpar error messages until the upstream can provide more information.
