### ISSUE TITLE
docs: first example on homepage is out of date?

### ISSUE THREAD

**Issue by nglvnt** [ibis-project/ibis#7038]
### Please describe the issue

I have tried running the first example shown on the https://ibis-project.org/ homepage:

```python
>>> import ibis
>>> movies = ibis.examples.ml_latest_small_movies.fetch()
>>> rating_by_year = movies.group_by('year').avg_rating.mean()
>>> q = rating_by_year.order_by(rating_by_year.year.desc())
```

However, the fetched `movies` dataset contains only the columns `movieId`, `title`, `genres`, but not `year`, nor `avg_rating`. Has this dataset been changed sometime?  

Also, the second code chunk has a `con` object that is not defined before.

```python
>>> con.compile(q)

SELECT year, avg(avg_rating)
FROM movies t1
GROUP BY t1.year
ORDER BY t1.year DESC
```

I am using ibis (version 6.2.0) with the DuckDB backend, as suggested on the install page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
hi @nglvnt, apologies about that! we're in the middle of moving to a new website framework with a new front page that should ensure all examples on the home page are working, it'd be great to get your feedback on that! you can find the link here: https://ibis-quarto.netlify.app/

we're looking to move over to the site (with https://ibis-project.org pointed there) in the next week or two

**Comment by nglvnt** [comment]
Hello @lostmygithubaccount, thanks for the explanation, and the link to the new website. I will definitely check that out and report if anything is found! :)

Thanks again!
