### ISSUE TITLE
feat: user-facing method for installing duckdb extensions w/o SQL

### ISSUE THREAD

**Issue by amoeba** [ibis-project/ibis#7063]
### Is your feature request related to a problem?

If I want to use DuckDB with an extension such as httpfs, I have to drop into SQL to install and load it. Due to this, I might run into a situation where I set up a connection that attempts to configure behavior provided by a non-installed, non-loaded extension,

```python
c = ibis.duckdb.connect("database.ddb", s3_region="us-east-2")
```

This returns successfully. But if I run

```python
c.raw_sql("SELECT current_setting('s3_region')")
```

I get:

> (duckdb.CatalogException) Catalog Error: Setting with name "s3_region" is not in the catalog, but it exists in the httpfs extension.
> 
> To install and load the extension, run:
> INSTALL httpfs;
> LOAD httpfs;

This isn't hard to work around if you know about DuckDB and `raw_sql` but it might trip users up and could overall be improved.

### Describe the solution you'd like

It would be nice if I could specify extensions to load with the `ibis.duckdb.connect` call, similar to how I can specify configuration options as kwargs. It might also be nice to handle the above error message in a more useful way though that may be out of scope of this feature request.

### What version of ibis are you running?

6.2.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Thanks for opening this. I'd propose the following interface for this:

- A new optional `extensions` kwarg to `ibis.duckdb.connect` (handed by `ibis.backends.duckdb.Backend.do_connect`) for loading extensions immediately upon connection. This would be used as `ibis.duckdb.connect(extensions=["httpfs"])`.
- A user-facing `load_extension` method on the duckdb backend connection. This would both install and load the extension as necessary (the duckdb library has separate `install_extension` and `load_extension` methods for this). We already have much of the code for doing this in a private method, just need to make it public. This would let the user write `con.load_extension("httpfs")`.
