### ISSUE TITLE
feat: Array.sum(), .min(), .max(), mean(), etc.

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7073]
### Is your feature request related to a problem?

Also, I could see .mean(), .min(), etc.

[Here are the supported agg functions for duckdb](https://duckdb.org/docs/archive/0.8.1/sql/functions/nested#list-aggregates). Not sure about other backends.

Related to https://github.com/ibis-project/ibis/issues/6975, except in this case I can't do the workaround that I mention there. Perhaps that issue is a special case of this.

### Describe the solution you'd like

Probably top-level functions on ArrayValue, but that lends itself to only making sense for the few core agg functions that all backends support. Once you get to weird agg functions like `kurtosis` that duckdb supports, it becomes harder to justify adding a `ArrayValue.kurtosis()` just to support duckdb. Perhaps a "sparse" API similar to duckdb's of `ArrayValue.agg("sum")` makes more sense in that it allows access to rare aggregation functions that only are in some backends.

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I think these operations can be implemented for a variety of backends:

- BigQuery (operations on arrays can be done in a subquery)
- ClickHouse (there are a bunch of `arrayFoo` operations that we would map to, e.g., [`arraySum`](https://clickhouse.com/docs/en/sql-reference/functions/array-functions#arraysum))
- DuckDB (already discussed in the issue title)
- Trino (using the [`reduce`](https://trino.io/docs/current/functions/array.html#reduce) function where necessary)
- PySpark (has some of the requested functions [built in](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/functions.html#collection-functions))
- Polars (there are a bunch under the [`list`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/list.html) namespace)

**Comment by NickCrews** [comment]
Nice! What do you think about the dense (array.max()) vs sparse (array.agg("max")) API? Should we come up with a matrix of func vs backend to see which are commonly supported? Could also have dense API for the most common aggs, but also include sparse API to allow filling in the gaps

**Comment by cpcloud** [comment]
I think having both seems reasonable. `.agg` is also a bit more friendly for programmatic use.

**Comment by NickCrews** [comment]
proposal for list of dense ops:

- .any()
- .all()
- .min()
- .max()
- .sum()
- .prod()

possibly:
- .mean() (you can emulate this with arr.sum()/ arr.length())
- .var() (similarly you can emulate this, but it is nastier)

**Comment by cpcloud** [comment]
We're still interested in this functionality. A good place to start would be to pick one backend, say DuckDB, and one aggregation, say `sum` and open a pull request for that.
