### ISSUE TITLE
docs: deduplicate 6.2.0 and 7.0.0 release notes

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#7091]
### Please describe the issue

As a follow up to https://github.com/ibis-project/ibis/issues/7090:

When 7.0.0 is released, the 7.0.0 release notes will include all the changes that were released in 6.2.0. Manually dedupe them.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
@ianmcook 7.0.0 is out now fyi
