### ISSUE TITLE
bug: can't use functools.partial with Array.map()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7095]
### What happened?

small example:

```python
import ibis
from functools import partial

a = ibis.array([1,2,3])

def add_n(x, n):
    return x + n

add_2 = partial(add_n, n=2)
a.map(add_2)
```

causes `IbisTypeError: Callable has mandatory keyword-only arguments which cannot be specified`

What I'm actually trying to do is have a general function, but then specialize it for different values and have a different column for each one. eg:

```python
t = ibis.examples.penguins.fetch()
t2 = t.group_by("species").agg(
    years=_.year.collect()
)
m = {f"year_plus_{i}": _.years.map(partial(add_n, n=i)) for i in range(3)}
t2.mutate(**m)
```

I tried to do this:
```python
t = ibis.examples.penguins.fetch()
t2 = t.group_by("species").agg(
    years=_.year.collect()
)
m = {}
for i in range(3):
    def add_i(x):
        return x + i
    m[f"year_plus_{i}"] = _.years.map(add_i)
t2.mutate(**m)
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ species   ┃ years                  ┃ year_plus_0            ┃ year_plus_1            ┃ year_plus_2            ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ string    │ array<int64>           │ array<int64>           │ array<int64>           │ array<int64>           │
├───────────┼────────────────────────┼────────────────────────┼────────────────────────┼────────────────────────┤
│ Adelie    │ [2007, 2007, ... +150] │ [2009, 2009, ... +150] │ [2009, 2009, ... +150] │ [2009, 2009, ... +150] │
│ Gentoo    │ [2007, 2007, ... +122] │ [2009, 2009, ... +122] │ [2009, 2009, ... +122] │ [2009, 2009, ... +122] │
│ Chinstrap │ [2007, 2007, ... +66]  │ [2009, 2009, ... +66]  │ [2009, 2009, ... +66]  │ [2009, 2009, ... +66]  │
└───────────┴────────────────────────┴────────────────────────┴────────────────────────┴────────────────────────┘
```
but notice that the `i` is only using the last seen value of 2, which is to be expected with the semantics of how python doesn't bind that value at definition time. I can get it to work with a class:

```python
t = ibis.examples.penguins.fetch()
t2 = t.group_by("species").agg(
    years=_.year.collect()
)

class AddN:
    def __init__(self, n):
        self.n = n

    def __call__(self, x):
        return x + self.n

m = {}
for i in range(3):
    m[f"year_plus_{i}"] = _.years.map(AddN(i))
t2.mutate(**m)
```

but functools.partial is the canonical way to do this and I think it should be supported. IDK if there are other pathways that we should consider here.

### What version of ibis are you using?

6.1.0

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
cc @kszucs, this is an interesting challenge for the type system: modeling a function such that the type system accepts an N argument function as a single argument function if N - 1 arguments are already bound.

**Comment by kszucs** [comment]
This exception is raised by `ibis.common.patterns.CallableWith` mostly because I haven't had enough time to investigate how to properly type annotate and handle keyword only arguments. Strictly speaking this validation can be omitted.

I'd need to further investigate what kind of validation could/should we actually do in `CallableWith.match()`.

**Comment by jcrist** [comment]
I have a fix for this incoming - we can relax the check here since these keyword-only parameters have default values.
