### ISSUE TITLE
Add async option to more time consuming Impala DDL commands

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#711]
E.g. things like `drop_database` can be quite time consuming. 
- [ ] drop_database
- [ ] avro_table / parquet_file / delimited_file
- [ ] insert / create table as select
- [ ] compute_stats (cancellable)

**Comment by wesm** [comment]
Moved to 0.7. I'll make a pass through and add the generic notion of an `AsyncAction` (which may or may not be cancellable, depending on the underying DDL)

**Comment by cpcloud** [comment]
Closing.
