### ISSUE TITLE
feat: allow specifying `Optional` and/or `T | None` in UDFs

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#7133]
### Is your feature request related to a problem?

Yes, it's related to a problem.

I discovered this issue during #7134.

Defining this Python UDF:

```
In [24]: from ibis.interactive import *

In [25]: @udf.scalar.python
    ...: def maybe_add_one(x: int | None) -> int:
    ...:     if x is None:
    ...:         return 0
    ...:     return x
```

raises an exception:

```
SignatureValidationError: ValueOf(int | None) has failed due to the following errors:
  `dtype`: int | None is not either None or coercible to a DataType

Expected signature: ValueOf(dtype: Optional[DataType] = None)
```

(love the new error messages!)

Using `Optional[int]` raises a similar exception:

```
In [27]: from typing import Optional

In [28]: @udf.scalar.python
    ...: def maybe_add_one(x: Optional[int]) -> int:
    ...:     if x is None:
    ...:         return 0
    ...:     return x

...

SignatureValidationError: ValueOf(typing.Optional[int]) has failed due to the following errors:
  `dtype`: typing.Optional[int] is not either None or coercible to a DataType

Expected signature: ValueOf(dtype: Optional[DataType] = None)
```

### Describe the solution you'd like

I'd like to be able to use optional or union syntax to describe nullable dtypes in udf signatures.

### What version of ibis are you running?

`master`

### What backend(s) are you using, if any?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kszucs** [comment]
We should use `ibis.common.annotations.Signature.from_callable()` because different `Pattern` must be constructed based on the default value, that is handled in `from_callable()`.

**Comment by gforsyth** [comment]
Closing this out as unplanned.
