### ISSUE TITLE
bug: .sql does not correctly infer table name

### ISSUE THREAD

**Issue by contang0** [ibis-project/ibis#7145]
### What happened?

Hi,

I am trying to use `.sql` on Impala tables, however for whatever reason Ibis doesn't seem to infer the table name correct.

```
>>>t = con.tables['tbl_name']
>>>expr = t.sql("select * from tbl_name")
>>>expr

HiveServer2Error: AnalysisException: Could not resolve table reference: '_ibis_view_17'
```

A look at the generated SQL code:

```
>>>ibis.to_sql(expr)

SELECT
  t0.*
FROM `_ibis_view_1` AS t0
```
I would expect to see `tbl_name` in the where clause. I also tried using `.alias`, however here I seem to run into another problem:

```
>>>t = con.tables['tbl_name'].alias("test_table_ibis")
>>>expr = t.sql("select * from test_table_ibis")

HiveServer2Error: AnalysisException: Could not resolve table reference: 'test_table_ibis'
```

It seems that when using alias Ibis uses the correct name, but the call to `.sql` itself fails and the expression is not created.

### What version of ibis are you using?

master

### What backend(s) are you using, if any?

Impala

### Relevant log output

```sh
HiveServer2Error: AnalysisException: Could not resolve table reference: '_ibis_view_1'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@contang0 Thanks for the issue!

We weren't planning on adding new features to the impala backend, due to its development status being unclear to us.

I see active commits, but we hardly get any requests for Impala features 😅

This is probably an oversight in our error handling: this should fail without trying to produce or execute any code.

Would `con.sql` (different than `table_expr.sql`) work for your use case?

**Comment by contang0** [comment]
Feature-wise impala indeed seems to have stalled, but from what I can tell looking at their repo, it looks maintained. As it is a component of the Cloudera Data Platform, I think it will remain important for corporate users. I'll try to contribute where I can myself, when I am a little more familiar with the Ibis code base.

I was aware that no new features are planned for Impala, but this looked like a bug in existing functionality. Indeed, if the error was NotImplemented, I would have resorted to `con.sql`. I will try tomorrow.

**Comment by cpcloud** [comment]
Yeah, I think we're missing some clear documentation on the different ways to interact with SQL. I'll summarize it here, and then push up a how-to for our docs.

- `con.raw_sql(str)`: run arbitrary SQL, `CREATE`, `INSERT`, `SELECT` etc. Notably, `raw_sql` does **not** return Ibis expressions, it returns a backend-specific cursor object.
- `con.sql(str)`: run arbitrary `SELECT` statements. These produce Ibis table expressions. Passing anything but a `SELECT` is effectively undefined behavior.
- `table.sql`: run arbitrary `SELECT` statements that are based on another Ibis table expressions.

**Comment by cpcloud** [comment]
In your case, I think you want `con.rawl_sql` for the `CREATE` statement, and then possibly `con.sql` for any subsequent `SELECT` statements.

**Comment by contang0** [comment]
Thank you! `con.raw_sql` worked fine. I think we can close this, unless you prefer to keep it open until the docs are updated.
