### ISSUE TITLE
Client metadata caching and staleness

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#716]
Like Impala nodes, it would be useful, to improve performance and reduce excess cluster chatter, to cache table metadata (e.g. the results of `DESCRIBE` or `SHOW PARTITIONS`) within Ibis and to either set some staleness threshold (after which the cache will be invalidated) or add the option for explicit invalidation. 

It would make sense to do this at the client level, and to have metadata caching available as a developer API across all clients. Relevant calls will have a unique "metadata key" computed and stored with a timestamp in the client-level metadata cache. 

This might add complexity or result in unexpected results for some users. I am feeling like perhaps this is something you should explicitly opt-in for (i.e. user declares "I understand the metadata cache layer and accept responsibility for setting an expiry or explicitly invalidating")

**Comment by scottcode** [comment]
I stumbled across this issue when playing with ibis and Postgres. Here are the steps I followed and the problem that occurred. 

1. created a `test` table in Postgres
2. created an ibis table object via `con.table('test')`
3. changed the schema of `test` in Postgres
4. re-instantiated a table object pointing to that table: `con.table('test')`

**Problem:** The re-instantiated table object doesn't know about the new schema. 

I'm using **0.13.0**.  It looks like some caching is already in place. I haven't figured out yet how to manually invalidate the cache. If that's possible, could you let me know how. If not, that would be a good feature to add. 

Thanks!

**Comment by cpcloud** [comment]
xref: #3127
