### ISSUE TITLE
bug: Oracle: DESC / DESCRIBE is a SQL*Plus command only

### ISSUE THREAD

**Issue by kangshung** [ibis-project/ibis#7164]
### What happened?

DESCRIBE is not a valid SQL statement. It is only available in SQL*Plus and SQL Developer. It cannot be used by the client.

It is used in the [ibis/ibis/backends/oracle/__init__.py](https://github.com/ibis-project/ibis/blob/a4a69d0875e52d749f6f674cbce96c896974ab7b/ibis/backends/oracle/__init__.py#L184) in the _metadata method.

More info:
- [here](https://ss64.com/ora/desc.html)
- [and here](https://stackoverflow.com/questions/37133666/what-is-the-reason-for-not-working-of-describe-command-on-oracle)

### What version of ibis are you using?

ibis-framework 7.0.0.dev474 from the main branch

### What backend(s) are you using, if any?

Oracle

### Relevant log output

```sh
File "src/oracledb/impl/thick/cursor.pyx", line 243, in oracledb.thick_impl.ThickCursorImpl.execute
  File "src/oracledb/impl/thick/utils.pyx", line 431, in oracledb.thick_impl._raise_from_odpi
  File "src/oracledb/impl/thick/utils.pyx", line 421, in oracledb.thick_impl._raise_from_info
sqlalchemy.exc.DatabaseError: (oracledb.exceptions.DatabaseError) ORA-00900: invalid SQL statement
[SQL: DESCRIBE ORA$PTT_2be12eac96624008a42cfad09a63902a]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

Is there a way to access the same information using a more generic SQL query?

**Comment by kangshung** [comment]
No problem.

We can reuse the query from my first link (user_tab_columns table). However, I have doubts:
1. Why exactly do we need a schema of the returned data? What about a case when we read just 1 table?
2. Why there's a creation of a private temp table (PTT) with an unsupported prefix name AND a drop table statement, if PTT drops itself automatically along with the session? It could just be a normal table without prefix requirements then + try catch to always drop the table. Or I am missing something?

PTTs are not visible in `user_tab_columns` and `all_tab_columns` tables --> that's why I believe we should go with plain tables.

**Comment by gforsyth** [comment]
> Why exactly do we need a schema of the returned data? What about a case when we read just 1 table?

we need the metadata of a table so we can properly type the columns for the ibis expressions.  otherwise we can't validate the deferred expressions.  In particular, this gets used so we can properly type and chain `.sql()` calls.

> 2\. Why there's a creation of a private temp table (PTT) with an unsupported prefix name AND a drop table statement, if PTT drops itself automatically along with the session? It could just be a normal table without prefix requirements then + try catch to always drop the table. Or I am missing something?

we follow this pattern with other backends and it works -- if there are "cleaner" ways to handle it for a particular backend, those contributions are definitely welcome.
