### ISSUE TITLE
bug: Oracle: Support for setting PRIVATE_TEMP_TABLE_PREFIX for PRIVATE TEMPORARY TABLE

### ISSUE THREAD

**Issue by kangshung** [ibis-project/ibis#7165]
### What happened?

When creating a private temporary table in Oracle, the table name needs to have a predefined prefix (`PRIVATE_TEMP_TABLE_PREFIX`).

In ibis, the prefix is custom (`__ibis_oracle_metadata_`), which requires the user to set this exact name as a parameter in OracleDB.

It would be beneficial if the default in ibis was same as the default in Oracle (`ORA$PTT_`), with an option to change it during the connection initialization. Right now it is not possible and returns errors.

It is used in the [ibis/ibis/backends/oracle/init.py](https://github.com/ibis-project/ibis/blob/a4a69d0875e52d749f6f674cbce96c896974ab7b/ibis/backends/oracle/__init__.py#L178) in the _metadata method.

More info:
- [here](https://oracle-base.com/articles/18c/private-temporary-tables-18c#:~:text=Private%20temporary%20tables%20share%20the,is%20%22ORA%24PTT_%22.)
- [and here](https://docs.oracle.com/en/database/oracle/oracle-database/18/refrn/PRIVATE_TEMP_TABLE_PREFIX.html#GUID-57FE93DA-BFC6-4E9B-B14E-9D5A031157B4)

### What version of ibis are you using?

ibis-framework 7.0.0.dev474 from the main branch

### What backend(s) are you using, if any?

Oracle

### Relevant log output

```sh
File "src/oracledb/impl/thick/cursor.pyx", line 243, in oracledb.thick_impl.ThickCursorImpl.execute
  File "src/oracledb/impl/thick/utils.pyx", line 431, in oracledb.thick_impl._raise_from_odpi
  File "src/oracledb/impl/thick/utils.pyx", line 421, in oracledb.thick_impl._raise_from_info
sqlalchemy.exc.DatabaseError: (oracledb.exceptions.DatabaseError) ORA-00911: invalid character
[SQL: CREATE PRIVATE TEMPORARY TABLE __ibis_oracle_metadata_e094bd07def04efe926d973aa0e36031 AS SELECT 1 AS TEST FROM DUAL]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kangshung** [comment]
After changing the line with the table name to use `ORA$PTT_` prefix, the query has been executed successfully, but the process failed in the next step as explained in #7164 

Hence, my question is whether PRIVATE TEMPORARY TABLE is actually really needed in this case (assuming it's not possible to describe it in any way).

**Comment by cpcloud** [comment]
Is this issue required for anything other than fixing the metadata query bug in #7164?

**Comment by kangshung** [comment]
This issue is related only to the issue you mentioned, and is no longer valid if you're gonna remove PTTs
