### ISSUE TITLE
bug: .clip() doesn't preserve NULLs

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7168]
### What happened?

I would expect nulls to stay nulls. But they get turned into the upper value (if upper bound is provided) or the lower bound (if no upper bound is provided)

```python
import ibis

t = ibis.memtable({"values": [0, 1.0, 2.0, 3.0, 4.0, None]})
t.mutate(clipped1=t.values.clip(lower=2.5, upper=3), clipped2=t.values.clip(lower=2.5))
┏━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┓
┃ values  ┃ clipped1 ┃ clipped2 ┃
┡━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━┩
│ float64 │ float64  │ float64  │
├─────────┼──────────┼──────────┤
│     0.0 │      2.5 │      2.5 │
│     1.0 │      2.5 │      2.5 │
│     2.0 │      2.5 │      2.5 │
│     3.0 │      3.0 │      3.0 │
│     4.0 │      3.0 │      4.0 │
│     nan │      3.0 │      2.5 │
└─────────┴──────────┴──────────┘
```

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb, maybe this is irrelevant. Not sure how different backends handle NULLs in GREATEST() and LEAST()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

I think we should preserve NULLs here, since `NULL < x` would evaluate to `NULL`

**Comment by NickCrews** [comment]
That was my line of reasoning as well
