### ISSUE TITLE
bug: No error message when using pandas UDF with duckdb

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7200]
### Is your feature request related to a problem?

I installed the dev version so I could start using the UDFs in my product. Just a UX thing, but I don't get an error as soon as I would like:

```python
import ibis
t = ibis.examples.penguins.fetch()

@ibis.udf.scalar.pandas
def add_one(x: int) -> int:
    return x + 1

result = add_one(t.year)
# This doesn't error, just is blank
result
```
<img width="281" alt="image" src="https://github.com/ibis-project/ibis/assets/10820686/ee5bece7-ddd3-44b7-905d-64f98a273b3c">

Only when you .execute() do you see the error `NotImplementedError: duckdb doesn't support pandas UDFs`

### Describe the solution you'd like

I would expect to get the error from repr getting called on the expression

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Making this fail when the UDF is called would prevent calling a pandas UDF on an unbound expression, which seems like a valid thing to want to do.

**Comment by cpcloud** [comment]
You won't be able to execute it, but you'd be able to compile the SQL.

**Comment by cpcloud** [comment]
`result` is blank due to the behavior of ipython when `__repr__` raises an exception. This can happen in interactive mode.

**Comment by cpcloud** [comment]
Closing. I'm not sure there's much to do here. Thanks for the issue!
