### ISSUE TITLE
feat: return scalars from pyarrow UDFs

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7202]
### Is your feature request related to a problem?

If I return a scalar from a pyarrow UDF (IDK if this is also relevant for pandas UDFs):
```python
import pyarrow.compute as pc
import ibis

@ibis.udf.scalar.pyarrow
def get_one(x: int) -> int:
    return 1

t = ibis.examples.penguins.fetch()
get_one(t.year).execute()
```
then this crashes the kernel.

### Describe the solution you'd like

This should be possible. Or, it should at least not crash the kernel, but maybe that is duckdb's responsibility.

I realize this is a silly use case, but I was using this for a stub before I actually did the implementation and found it. Perhaps there is a real use case.

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Perhaps we need some better documentation.

We also might be able to wrap the user's function in another function that raises an exception if the output type isn't valid for the UDF.

The requirement is that your UDF implementation must return a pyarrow object (I haven't tried using `pa.scalar(1)`).

**Comment by NickCrews** [comment]
> wrap the user's function

This seems nice, but then we must keep this in sync with exactly what duckdb's UDF API is. Otherwise we will trigger false positives or false negatives. Could just issue warnings instead of actually erroring?

> documentation

This seems reasonable to just put the onus on the user, I'm fine with this and calling it a day (and revisiting later)
