### ISSUE TITLE
bug(bigquery): `TIMESTAMP` is unconditionally used for timestamp literals, even when lacking a timezone

### ISSUE THREAD

**Issue by EricLiJunting** [ibis-project/ibis#7233]
### What happened?

In BigQuery connector, the final SQL output always cast to TIMETSAMP regardless of the given value type. 

For example: `df `is a Ibis table connecting to a table in BigQuery. The column `col_A `is `DATETIME `in BigQuery schema. Regardless the value input, the output SQL query are always `TIMESTAMP '2023-01-01'`..... However, the first one should `DATETIME`, while the second one is `TIMESTAMP`

`df.col_A.fillna(ibis.literal("2023-01-01", type="timestamp")).compile()`
`"SELECT IFNULL(t0.`col_A`, TIMESTAMP '2023-01-01 00:00:00') AS `IfNull_col_A_ datetime_datetime_2023_ 1_ 1_ 0_ 0`\nFROM `beta-385421.test_integration_eric_1695754492_2081.table_na_datetimes` t0"`

`df.col_A.fillna(ibis.literal("2023-01-01", type="timestamp('UTC')")).compile()`
`"SELECT IFNULL(t0.`col_A`, TIMESTAMP '2023-01-01 00:00:00+00:00') AS `IfNull_col_A_ datetime_datetime_2023_ 1_ 1_ 0_ 0_ tzinfo=tzutc`\nFROM `beta-385421.test_integration_eric_1695754492_2081.table_na_datetimes` t0"`

### What version of ibis are you using?

6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks the report, I can confirm we are hardcoding the use of `TIMESTAMP` for literal compilation.

**Comment by EricLiJunting** [comment]
That explains the issue. But will this be changed in the future, since the output SQL query would break if the target column is be filled is not `TIMESTAMP`?

**Comment by cpcloud** [comment]
We're already treating `timestamp` types without a time zone as `datetime`s for the bigquery backend, this was just a missed changed from the PR that made those changes (https://github.com/ibis-project/ibis/pull/6144)

**Comment by EricLiJunting** [comment]
Thank you @cpcloud, it seems that this [PR](https://github.com/ibis-project/ibis/pull/6144) directly address my question.

If ibis timestamp has the UTC timezone, will map to BigQuery TIMESTAMP type
If ibis timestamp has no timezone, will map to BigQuery DATETIME type

Do you know which version of Ibis I should use to resolve this issue?

**Comment by cpcloud** [comment]
There is no released version that has a fix for this issue. #6144 did not have changes corresponding to `literal` compilation which is the problem you're seeing.

Good news is you opened this right before our 7.0.0 release which is slated for next Monday!

**Comment by EricLiJunting** [comment]
I think I misread your previous comments. Thanks @cpcloud for info

**Comment by cpcloud** [comment]
@EricLiJunting This should be fixed in the next release (7.0.0)!
