### ISSUE TITLE
feat: DateValue.median() .quantile()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7250]
### Is your feature request related to a problem?

I need to do some summary stats on date columns. At least the very basic ones would be super useful!

### Describe the solution you'd like

Not exactly sure what backends have this builtin, and which we might have to do some hack of casting to an int, doing the op, and then casting back...

### What version of ibis are you running?

6.2.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

Is the average of two or more date values a meaningful operation?

I think (discrete) quantiles make sense and are probably supported for most backends that support quantiles.

**Comment by NickCrews** [comment]
> Is the average of two or more date values a meaningful operation?

My first gut reaction would be yes for Dates and Timestamps, since they are orderable and linear. But no for Times, because they are cyclical. But IDK if backends don't support this then there probably is a reason I'm not thinking of

**Comment by cpcloud** [comment]
We can add support for quantile and related APIs (median) for these types, but not mean.

AFAICT there's no generic interpretation of what the average of a sequence of date or timestamp is.

However, we should have the primitives for you to give the operation meaning for your application.

**Comment by cpcloud** [comment]
Let's keep this scoped to `median` and `quantile`

**Comment by NickCrews** [comment]
Yes, chiming in that I agree mean (and even a simple datetimedelta difference) between two dates is ambiguous and we shouldn't attempt that.

Relevant xkcd: https://xkcd.com/2867/
