### ISSUE TITLE
bug: Clickhouse backend cannot register parquet files. 

### ISSUE THREAD

**Issue by seandavi** [ibis-project/ibis#7264]
### What happened?

See the log output below, but looking through the documentation [here](https://ibis-project.org/backends/clickhouse#ibis.backends.clickhouse.Backend.read_parquet), I would expect that the clickhouse can register both csv and parquet files. 

I'm happy to take a look if this is unexpected behavior. 

### What version of ibis are you using?

6.2.0

### What backend(s) are you using, if any?

clickhouse

### Relevant log output

```sh
>>> ppl = con.read_parquet('/Users/seandavis/Documents/git/cu_profile_utils/ppl.parquet')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/seandavis/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ibis/backends/base/__init__.py", line 385, in read_parquet
    raise NotImplementedError(
NotImplementedError: clickhouse does not support direct registration of parquet data.
>>> ibis
<module 'ibis' from '/Users/seandavis/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ibis/__init__.py'>
>>> ibis.__version__
'6.2.0'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This will land in 7.0. Can you install a pre-release and give it a try?

**Comment by cpcloud** [comment]
@seandavi 7.0.0 is out, so this is now in a proper release! Please open a new issue if you're still unable to read Parquet files with ClickHouse.
