### ISSUE TITLE
feat(oracle): support listing tables owned by other users

### ISSUE THREAD

**Issue by sidhreddy** [ibis-project/ibis#7272]
### What happened?

`tables` OR `list_tables` doesn't seem to list tables owned by other users.

### What version of ibis are you using?

 6.1.0

### What backend(s) are you using, if any?

Oracle

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Do you have a SQL query that can give this information? We might be able to roll that into `list_tables` for the oracle backend.

**Comment by sidhreddy** [comment]
@cpcloud The below query will give us all tables the current user has read access on:

```
SELECT
  table_name, owner
FROM
  all_tables
```

**Comment by gforsyth** [comment]
Hey @sidhreddy -- that query looks helpful, thanks!

It also looks like it will return a mixture of views and tables (this is fine) that are accessible by the current user -- but despite there being read access to those tables and views, a lot of them (and there are a LOT of them) seem pretty esoteric that most users might not want to see.

Usually we would only show the tables owned by the current user to also reduce clutter and then have a keyword argument like `schema=` to show the tables/views that are available under `SYS` (for instance).

Would that be helpful?  Or do you want the ability to list all tables across all users that you can access?

**Comment by sidhreddy** [comment]
@gforsyth Makes sense. It does list a whole lot of tables even from `SYS` which won't be of much help. Having a `schema` param onto `list_tables` (not sure if it already exists) to list tables under a specific user would be great as you suggested.

**Comment by sidhreddy** [comment]
@gforsyth Thanks for sharing this. `con.list_tables(database="SYS")` does work and for some reason `con.table` does work for some tables but not some. I still see the below error for some tables 😕 :
```
File [/usr/local/Caskroom/miniconda/base/envs/ibis/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py:625](https://file+.vscode-resource.vscode-cdn.net/usr/local/Caskroom/miniconda/base/envs/ibis/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py:625), in BaseAlchemyBackend.table(self, name, database, schema)
    622     if database != self.current_database:
    623         return self.database(name=database).table(name=name, schema=schema)
--> 625 sqla_table = self._get_sqla_table(name, schema=schema)
    627 schema = self._schema_from_sqla_table(
    628     sqla_table, schema=self._schemas.get(name)
    629 )
    630 node = ops.DatabaseTable(
    631     name=name, schema=schema, source=self, namespace=namespace
    632 )

File [/usr/local/Caskroom/miniconda/base/envs/ibis/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py:501](https://file+.vscode-resource.vscode-cdn.net/usr/local/Caskroom/miniconda/base/envs/ibis/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py:501), in BaseAlchemyBackend._get_sqla_table(self, name, schema, autoload, **_)
    495 warnings.filterwarnings(
    496     "ignore", message="Did not recognize type", category=sa.exc.SAWarning
    497 )
    498 warnings.filterwarnings(
    499     "ignore", message="index key", category=sa.exc.SAWarning
    500 )
...
   2175         pk_constraint
   2176         and index_name_normalized == pk_constraint["name"]
   2177     ):

AttributeError: Could not locate column in row for column 'index_name'
```

**Comment by gforsyth** [comment]
Glad we got you part of the way there, @sidhreddy -- I'm going to close this out for now, but let's continue troubleshooting the `AttributeError` over in #7321

**Comment by gforsyth** [comment]
Also, to be clear, we are going to try to improve the current situation re: keyword argument names and how to access tables in different databases / schemas / catalogs, but not tracking that work here.
