### ISSUE TITLE
docs: how to access a schema.table within a database

### ISSUE THREAD

**Issue by Sage0614** [ibis-project/ibis#7289]
### Please describe the issue

Not sure if it is a missing feature or a document issue, currently it is not documented how can I access a table under a schema in a database,

for example if I want to access the table named 'test' under schema 'public' in duckdb, what the syntax should be?

equavalent sql query is somthing like:
"select * from public.test limit 10"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue! We should definitely document this.

You should be able to pass `schema` to `con.table`. Here's DuckDB:

```
…/ibis-fork on  remove-magic-getitem is 📦 v7.0.0 via 🐍 v3.10.12 via ❄️  impure (ibis-3.10.12-env)
❯ duckdb /tmp/test.ddb
v0.8.1
Enter ".help" for usage hints.
D create schema my_schema;
D create table my_schema.t as select 1 as a, 'b' as b;
D

…/ibis-fork on  remove-magic-getitem is 📦 v7.0.0 via 🐍 v3.10.12 via ❄️  impure (ibis-3.10.12-env) took 23s
❯ ipython

In [1]: from ibis.interactive import *

In [2]: con = ibis.duckdb.connect("/tmp/test.ddb")

In [3]: t = con.table("t", schema="my_schema")

In [4]: t
Out[4]:
┏━━━━━━━┳━━━━━━━━┓
┃ a     ┃ b      ┃
┡━━━━━━━╇━━━━━━━━┩
│ int32 │ string │
├───────┼────────┤
│     1 │ b      │
└───────┴────────┘
```

**Comment by cpcloud** [comment]
This should be addressed now. You can try out the fix with

```
pip install --pre -U 'ibis-framework[duckdb]'
```
