### ISSUE TITLE
feat: clickable hyperlinks in rich repr

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7292]
### Is your feature request related to a problem?

I have a column of URLs. It would be awesome if they were clickable in the printed table repr from rich.

### Describe the solution you'd like

not sure how to do this.

Call [`.protocol()`](https://ibis-project.org/reference/expression-strings#ibis.expr.types.strings.StringValue.protocol) on all string columns, and if it is one of http,https,[something else?], then surround that string with the [rich [link] tags](https://rich.readthedocs.io/en/stable/markup.html#links)? Should this be done on a per-row basis, or if at least x% of rows match this condition then style all rows like this? Not sure what the performance implications of this would be, or how much we need to worry about it.

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I don't think we should use ibis methods for this. Not all backends implement `protocol()`, and we shouldn't tie the ability to print a table to a backend's operation support.

We can use `urllib.parse.urlparse` on the materialized results and check the `scheme` field and then add `[link]` tags based on that.
