### ISSUE TITLE
SQL simplification: aggregation on top of projected join in some cases

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#73]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Thursday Jan 22, 2015 at 01:02 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/73_

---

with the following sequence of operations
- join
- projection
- aggregation

If there are no non-trivial projected expressions, then rather than aggregating on top of a subquery, we can rewrite the AST without the projection and directly aggregate the join. so in other words, we want sql like:

``` sql
select foo, bar, sum(baz) as qux
from a
  inner join b
    on a.key = b.key
group by 1, 2
```

instead of the more complex

``` sql
select foo, bar, sum(baz) as qux
from (
  select a.*, b.baz
  from a
    inner join b
      on a.key = b.key
)
group by 1, 2
```

even though the user wrote in Ibis code:

``` python
# joined now has a materialized schema after projection
joined = a.inner_join(b, ['key'])[a, b.baz]

metrics = [joined.baz.sum().name('qux')]
result = joined.group_by(['foo', 'bar']).aggregate(metrics)
```

Performing the simplification might be less than trivial depending on which tables (whether the root tables, or the projection) the group keys and metrics reference. The expression rewrite should be possible with some wrangling

**Comment by cpcloud** [comment]
Closing as stale.
