### ISSUE TITLE
Create a workflow builder API for multi-step queries

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#732]
As a basic Impala example: INSERT followed by COMPUTE STATS. It would be nice to be able to build "action chains" or "workflows" involving multiple steps that can be monitored (or have a progress bar) and cancelled at will.

**Comment by hammer** [comment]
Seems like scope creep. Why not send people to [luigi](https://github.com/spotify/luigi) or one of the dozens of other Python workflow libraries?

**Comment by wesm** [comment]
A good chance. I'm not planning to build anything yet.

Hearing about cases where folks are assembling metadata management / ETL workflows with bash scripts and the Impala shell. Want to make sure these can be moved to Ibis or some combination of Ibis and a workflow manager like luigi

**Comment by hammer** [comment]
Yeah the problem with ETL libraries/frameworks is the cost of learning the library/framework. Most people will reach for bash when that's what they know and they don't bear the burden of maintenance or they don't have an environment with hundreds of workflows to manage. I don't think adding another workflow library will solve that problem.

**Comment by wesm** [comment]
Makes sense. My only near term plan with Ibis is enable any DDL action to be executed asynchronously. Currently you can do `expr.execute(async=True)` and get an `AsyncQuery` result from a data expression (that can also be cancelled), but it would be useful to have that be consistent with any Ibis actions causing queries to be sent to Impala — in some cases they can be cancelled and others not depending on the statement. 

My thought here was to take things 1 step further, i.e. to create the notion of an `Action` that can be executed, and actions can be chained and executed asynchronously. So kind of like async execution but leaving it to the user to initiate the query. Kind of like:

```python

action1 = ...
action2 = ...
action3 = ...

action_sequence = ibis.execute_async([action1, action2, action3])
```

This is already happening implicitly, but in ad hoc fashion, with functions like `ImpalaClient.parquet_file`, which have to issue multiple queries (`CREATE EXTERNAL TABLE` and then computing and setting some table stats).

**Comment by cpcloud** [comment]
Out of scope.
