### ISSUE TITLE
bug: con.table(schema='schema_name', name="table_name") fails

### ISSUE THREAD

**Issue by sidhreddy** [ibis-project/ibis#7321]
### What happened?

con.table(schema='schema_name', name="table_name") throws `AttributeError: Could not locate column in row for column 'index_name'`

### What version of ibis are you using?

6.1.0

### What backend(s) are you using, if any?

Oracle

### Relevant log output

```sh
File [/usr/local/Caskroom/miniconda/base/envs/ibis/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py:614](https://file+.vscode-resource.vscode-cdn.net/usr/local/Caskroom/miniconda/base/envs/ibis/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py:614), in BaseAlchemyBackend.table(self, name, database, schema)
    611     if database != self.current_database:
    612         return self.database(name=database).table(name=name, schema=schema)
--> 614 sqla_table = self._get_sqla_table(name, schema=schema)
    616 schema = self._schema_from_sqla_table(
    617     sqla_table, schema=self._schemas.get(name)
    618 )
    619 node = ops.DatabaseTable(
    620     name=name, schema=schema, source=self, namespace=namespace
    621 )

File [/usr/local/Caskroom/miniconda/base/envs/ibis/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py:482](https://file+.vscode-resource.vscode-cdn.net/usr/local/Caskroom/miniconda/base/envs/ibis/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py:482), in BaseAlchemyBackend._get_sqla_table(self, name, schema, autoload, **_)
    476 warnings.filterwarnings(
    477     "ignore", message="Did not recognize type", category=sa.exc.SAWarning
    478 )
    479 warnings.filterwarnings(
    480     "ignore", message="index key", category=sa.exc.SAWarning
    481 )
--> 482 table = sa.Table(
...
   2175         pk_constraint
   2176         and index_name_normalized == pk_constraint["name"]
   2177     ):

AttributeError: Could not locate column in row for column 'index_name'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@sidhreddy Thanks for the issue!

Can you point us to the docs on Oracle schemas?

From my research awhile ago, I couldn't find anything that corresponds to the notion of a schema similar to [the postgres notion of of a schema](https://www.postgresql.org/docs/current/ddl-schemas.html) in Oracle.

**Comment by sidhreddy** [comment]
@cpcloud In Oracle, `User` is a bit synonymous with a `Schema`. Each user can create tables, views etc. and associate it to any `User` that they have `CREATE` access on. So, I think we can associate Oracle's `USER` to ibis's `schema`.

 Ex: User `JOHN_DOE` can create a table EMPLOYEE within his User space or another User that he has access like. `JOHN_DOE.EMPLOYEE` OR `OTHER_USER.EMPLOYEE`. 

The official documentation doesn't seem to call this out well. I found this thread which explains this a bit: https://stackoverflow.com/questions/880230/difference-between-a-user-and-a-schema-in-oracle

**Comment by gforsyth** [comment]
@sidhreddy -- are there any tables defined in `SYS` that cause this error to occur?  Or alternatively, can you share the table schema for the table in question?  That will make it easier for us to try to debug.
