### ISSUE TITLE
bug: `dt.highest_precedence([dt.uint64, dt.int32])` gives `uint64`, not `int64`

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7331]
### What happened?

Came from exploring around exposing `highest_precedence()` publicly per https://github.com/ibis-project/ibis/issues/5707

```python
from ibis.expr import datatypes as dt

dt.highest_precedence([dt.int32, dt.uint64])
```
EDIT: this is a bit wrong, see cpclouds comment below.
gives uint64. I would expect it to be int64, because if you had a negative number in the int32 column, I would want that to still be negative in the unioned dtype. Maybe I'm not understanding this correctly though. 

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
The correct answer is probably `int128` (but we don't have that type and if we did we have the same problem again).

I think I would expect the current system to error if there's no type that can represent the set values common to both types.

`int64` wouldn't be correct here because it cannot represent many `uint64` values.

**Comment by gforsyth** [comment]
I think this means we would remove the ability to cast from signed to unsigned integers in all cases, which is more restrictive than the backends actually are -- although I recognize this is a bit intractable without knowing the bounds of the values in a given column.

**Comment by NickCrews** [comment]
> int64 wouldn't be correct

oh I see, my bad.

> I think this means we would remove the ability to cast from signed to unsigned integers in all cases, which is more restrictive than the backends actually are -- although I recognize this is a bit intractable without knowing the bounds of the values in a given column.

All uint32s are representable by int64s, so casting in that case should always be allowed. Are you talking about the `uintX` to `intX` case? I think casting there should be allowed because backends support it. I think there are two functionalities here:
## "is x castable to y?"

What needs to happen during an explicit `cast()` call. Is much more lenient, because the user is doing an explicit cast.
- uint64->int64 == true
- list->float == false

## "find a dtype that can represent both dtypes safely"

What happens during an implicit cast. For instance, with https://github.com/ibis-project/ibis/pull/7332 applied:

```python
uint8s = ibis.array([255]).cast("array<uint8>")
int8s = ibis.array([127, -128]).cast("array<int8>")
x = uint8s.concat(int8s)
print(x.type())
print(x)
# array<uint8>
# [255, 127, -128]
```

Really this should return `array<int16>`, or it should error, not sure which. In the case of `array<uint64>` and `array<int64>`, this should definitely error because there is no safe implicit casting option.

**Comment by gforsyth** [comment]
> Are you talking about the `uintX` to `intX` case?

No, those are tractable by going up by a power of 2 in bit-width, but `int` to `uint` requires knowledge of the underlying value to be able to say whether the cast is valid or not.

I think the split you've identified is good!  So if a user says "just cast it" we can allow it (within reason) and then let the backend fail or succeed.  

Implicit casting should find a dtype that can encompass both dtypes (or the implicit cast should fail, if it cannot).

**Comment by NickCrews** [comment]
> > Are you talking about the `uintX` to `intX` case?

Ah sorry I wasn't clear, I think we're on the same page I meant X was the same width for both eg uint32 to int32

**Comment by gforsyth** [comment]
There are valid issues here, but it's not currently blocking any of our work and fixing it is liable to be an insane :rabbit: :hole: -- if someone is interested in tackling this work without breaking the entire project, we're game to talk it through, but this isn't going to get picked up any time soon.
