### ISSUE TITLE
bug: `ibis.literal(129, type="uint8")` gives TypeError 

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7334]
### What happened?

Found when playing with https://github.com/ibis-project/ibis/issues/7331

`ibis.literal(129, type="uint8")` gives `TypeError: Value 129 is out of bounds for type UInt8(nullable=True) (bounds: Bounds(lower=0, upper=128))`
I would expect the bounds to be [0, 255], since the backends can actually handle that:

`SELECT 129::UINT8;` works on https://shell.duckdb.org/, and `(ibis.literal(127, type="uint8") * 2 ).cast("uint8")` gives the correct 254.

### What version of ibis are you using?

master

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
I was also playing with #7331 and ran into the incorrect bounds -- thanks for flagging it!  I've got a fix up.
