### ISSUE TITLE
feat: define if StringValue.re_replace() replaces the first occurence, or all

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7346]
### Is your feature request related to a problem?

EDIT: jk, it looks like the intention per https://github.com/ibis-project/ibis/commit/c138f0fd37fb4d3ccbebd99c9b53f85eecd5d241 is for it to be global. there is a test for it there as well. PR adding docs is at #7347

It is ambiguous. `ibis.literal("aaa").re_replace("a", "b")` results in "bbb", but perhaps it's different on backends other than duckdb.

I found this when I started poking around trying to find the root cause of this warning I got from `ibis.show_sql()`:

```
REGEXP_REPLACE does not support the following arg(s): ['position']
REGEXP_REPLACE does not support the following arg(s): ['position']
REGEXP_REPLACE does not support the following arg(s): ['position']
REGEXP_REPLACE does not support the following arg(s): ['position']
REGEXP_REPLACE does not support the following arg(s): ['position']
REGEXP_REPLACE does not support the following arg(s): ['position']
WITH t0 AS (
  SELECT
    t6.record_id AS record_id,
    t6.label_true AS label_true,
    t6.name_true AS name_true,
    t6.name AS name,
    REGEXP_REPLACE(
      TRIM(
        REGEXP_REPLACE(
          UPPER(REGEXP_REPLACE(TRIM(t6.name, ' 	
'), '\\s+', ' ')),
          '[^0-9A-Z ]',
          ''
        ),
        ' 	
'
......
```

### Describe the solution you'd like

We should

1. determine which we want. I vote "all"
2. document this
3. add tests
4. Possibly add an optional arg to choose the other variation

### What version of ibis are you running?

7.0.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Generally speaking we try to match the behavior of the equivalent Python API where possible.

In this case the equivalent Python API is `re.sub`, which replaces every occurrence:

```
In [1]: import re

In [2]: re.sub("a", "b", "aaa")
Out[2]: 'bbb'
```

**Comment by cpcloud** [comment]
As an aside the warning is coming from sqlglot. We may be able to silence that, or make some changes to our use of it to avoid the warning.

**Comment by cpcloud** [comment]
Given that we have a test, and you've done the work of documenting this (thank you!), shall we close this out?

**Comment by NickCrews** [comment]
yes! Sorry for the slow response.

**Comment by cpcloud** [comment]
No worries!
