### ISSUE TITLE
feat: GlareDB backend

### ISSUE THREAD

**Issue by universalmind303** [ibis-project/ibis#7348]
### Describe the solution you'd like

I'd like to be able to use https://github.com/GlareDB/glaredb as a backend

### What version of ibis are you running?

N/A

### What backend(s) are you using, if any?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@universalmind303 Thanks for the issue!

GlareDB looks interesting!

What do you think about contributing this backend in a PR? We'd love to have a person who works on GlareDB maintaining the ibis backend for it :)

You could potentially use the ClickHouse backend as a starting point.

**Comment by gforsyth** [comment]
I'm going to close this out as unplanned for now but we'd be happy to help someone from `glaredb` get this going!
