### ISSUE TITLE
bug: Command drop view IF EXISTS does not exist in Oracle

### ISSUE THREAD

**Issue by kangshung** [ibis-project/ibis#7363]
### What happened?

Oracle queries fail while dropping the view.

IF EXISTS is not supported in Oracle: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/DROP-VIEW.html

### What version of ibis are you using?

7.0.0

### What backend(s) are you using, if any?

Oracle

### Relevant log output

```sh
sqlalchemy.exc.DatabaseError: (oracledb.exceptions.DatabaseError) ORA-00933: SQL command not properly ended
[SQL: DROP VIEW IF EXISTS "_ibis_oracle_metadata_d4gbmh4h2fa2jnq5qo3o3rg6sa"]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
`IF EXISTS` is supported in later versions of Oracle (https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/DROP-VIEW.html#GUID-1A1BD841-66B9-47E4-896F-D36E075AE296) which is why this currently passes CI.
