### ISSUE TITLE
docs: https error connecting to Starburst Galaxy following the tutorial

### ISSUE THREAD

**Issue by dhuynh** [ibis-project/ibis#7365]
### Please describe the issue

https://ibis-project.org/tutorials/data-platforms/starburst-galaxy/0_setup

I don't think this shows how to send an HTTPS request to Starburst Galaxy, since the trino ibis con by default sends an HTTP request I believe. 

There is an error when using port 443. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
@dhuynh were you able to get by this by passing in `http_scheme="https"` to the `ibis.connect` call?

**Comment by dhuynh** [comment]
Does IBIS support SSO login? 

I can connect to Galaxy if I only have Username/Password set up in the domain, however if OKTA with single-sign on is enabled - I am not sure how to connect. 

In databricks / spark, the library would return a single sign and you would be able login in another tab before continuing in interactive mode.

**Comment by cpcloud** [comment]
@dhuynh In general, we try to pass `**kwargs` into the appropriate underlying backend connection API. In the SQLAlchemy case (and therefore Trino), we pass additional keyword arguments to `sqlalchemy.create_engine` like this

```python
import sqlalchemy as sa

sa.create_engine(..., connect_args=kwargs)
```

So, if the Trino sqlalchemy connector supports some set of additional keyword arguments that allow SSO to work then ibis supports it.

Do you have an example of how you'd do this without ibis, using the Trino Python client?

**Comment by dhuynh** [comment]
Hmm - it seems like in the trino docs - only username/password is supported for LDAP authentication. https://trino.io/docs/current/security/ldap.html. 

This seems like a case where single-sign on isn't supported then without vendor support.

**Comment by dhuynh** [comment]
Okay, I got authentication to work this way. We can close this issue and make a note for Okta single-sign on you need the oauth2 properties I added below. I have not gotten any databases to list tables outside of Sample/Demo. Is there another place to discuss? 

```
import ibis
from trino.auth import OAuth2Authentication

con = ibis.trino.connect(
  user="user",
  host="hostname",
  port=443,
  database="sample",
  schema="demo",
  auth=OAuth2Authentication(),
  http_scheme="https"
)
```

**Comment by cpcloud** [comment]
> Is there another place to discuss?

Check out our [Zulip chat](https://ibis-project.zulipchat.com/)

**Comment by dhuynh** [comment]
Perfect, will do there, thanks!!
