### ISSUE TITLE
bug:  truncating date column by week rounds the week up  instead of down 

### ISSUE THREAD

**Issue by michalshilo6** [ibis-project/ibis#7460]
### What happened?

When I use truncate on a date column it rounds up (to next monday) instead of down (to last monday)

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

I think SQLite but I'm not 100% sure

### Relevant log output

```sh
outreach_table.outreach_date.truncate('week').execute()
Out[8]: 
0   2023-09-11
1   2023-10-09
2   2023-09-11
3   2023-09-11
Name: DateTruncate(outreach_date), dtype: datetime64[ns]
outreach_table.outreach_date.execute()
Out[9]: 
0   2023-09-05
1   2023-10-03
2   2023-09-11
3   2023-09-10
Name: outreach_date, dtype: datetime64[ns]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for the report, @michalshilo6 !  It looks like we had a bug in the `sqlite` backend for week truncation.  I've opened a PR with a fix.  It should be available in our next release which will be 7.1
