### ISSUE TITLE
bug: inconsistencies in results when exporting `to_pandas` and `to_pyarrow` when there are nulls in a not-nullable column

### ISSUE THREAD

**Issue by inigohidalgo** [ibis-project/ibis#7487]
### What happened?

Hello,

I am experiencing some strange behavior when performing a join between two tables:

Depending on the method (right or inner, vs outer or left), I am getting an empty output when calling `to_pyarrow` on the result of the latter two methods, whereas I am getting the expected result when calling `to_pandas`. On the other hand, the first two methods give the same result in arrow or pandas.

One of the tables I'm joining is a slightly complex expression with self joins and aggregations.

```python
import ibis.deferred as ibd

conn.table("TABLE_2", schema="SCHEMA")
    .join(
        table_1_filtered, # result of various self-joins
        [
            ibd["date"] == table_1_filtered["date"],
            ibd["client"] == table_1_filtered["client"]
        ],
        how="outer"
    )
```

I get the same issue when calling `.outer_join` or `left_join`

### What version of ibis are you using?

Latest 8.x.x branch

### What backend(s) are you using, if any?

mssql

### Relevant log output

I can provide additional info on tables if needed, though will need to anonymize the info to post it, so lmk if you think it would be relevant.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by inigohidalgo** [comment]
Additional info:

Switching to interactive mode, the join gives a result, then calling to_pyarrow on that result removes all the rows. I have a feeling it might be related to the fact that table_1_filtered has a column which is not nullable, but when performing a left_join or outer_join it is actually inserting quite a few null values, which maybe to_pyarrow cannot handle?

**Comment by inigohidalgo** [comment]
Kept looking and it does seem to be the case.

Doing

```python
table_1_filtered.cast(
    {
        colname: type(coltype)(nullable=True) for colname, coltype in table_1_filtered.schema().items()
    }
)
```
(Feels wrong to do this operation this way, is there a cleaner method I'm missing?)

This results in the pyarrow result I was expecting, so it does seem to be a result of the difference with how arrow handles nulls in a not-nullable column. Updating issue title.

**Comment by gforsyth** [comment]
Thanks for the report and follow-up @inigohidalgo !  
I think you've got the correct workaround at the moment.  

I'm not sure what the correct fix is here.  
I would say that if we perform an outer join (or other join that can introduce NULL values) that we need to take that into account in the schema of the projection that results, but I don't know if this is specified in the SQL standard (it probably is?).

I think the root cause here is that Ibis should be setting the columns to `nullable` as a result of the outer join, so we can apply that schema to the pyarrow table as output.

It is strange to me that it's dropping only some rows instead of erroring -- for instance, if I try to force a non-nullable schema onto a pyarrow table with NULL values, I get a much more predictable error:

```python

[ins] In [1]: import ibis

[ins] In [2]: penguins = ibis.examples.penguins.fetch()

[ins] In [3]: non_null_penguins = ibis.schema({k: type(v)(nullable=False) for k, v in penguins.sch
         ...: ema().items()})

[ins] In [4]: non_null_penguins
Out[4]: 
ibis.Schema {
  species            !string
  island             !string
  bill_length_mm     !float64
  bill_depth_mm      !float64
  flipper_length_mm  !int64
  body_mass_g        !int64
  sex                !string
  year               !int64
}

[ins] In [5]: ibis.formats.pyarrow.PyArrowData.convert_table(penguins.to_pyarrow(), non_null_pengu
         ...: ins)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 ibis.formats.pyarrow.PyArrowData.convert_table(penguins.to_pyarrow(), non_null_penguins)

File ~/github.com/ibis-project/ibis/ibis/formats/pyarrow.py:253, in PyArrowData.convert_table(cls, table, schema)
    250     table = table.rename_columns(schema.names)
    252 if pa_schema != desired_schema:
--> 253     return table.cast(desired_schema)
    254 else:
    255     return table

File /nix/store/g7xcqrqc9gnad4f21xcy8qxdn8lssf05-python3-3.10.13-env/lib/python3.10/site-packages/pyarrow/table.pxi:3799, in pyarrow.lib.Table.cast()

ValueError: Casting field 'bill_length_mm' with null values to non-nullable
```

**Comment by gforsyth** [comment]
The difference in behavior might be at the `to_pyarrow_batches` layer, since the `to_pyarrow()` call in the MSSQL backend is going to call the underlying default `to_pyarrow_batches` which will grab the results as tuples and then "columnize" them.

**Comment by inigohidalgo** [comment]
Thanks for your reply Gil,

> it's dropping only some rows

It's dropping everything, I get an empty dataframe when doing left or outer, and no warnings or errors, it just seems to be silently returning an empty df.

> Ibis should be setting the columns to nullable as a result of the outer join, so we can apply that schema to the pyarrow table as output

Agreed, it seems reasonable to expect that in the case of an outer join, all the columns except for join keys, and in the case of a left or right join, the "other" side of the join should have all its columns become nullable, right?

**Comment by cpcloud** [comment]
@inigohidalgo We are able to reproduce this using an outer join of our test data and indeed it seems to be related to pyarrow and non-null columns.

**Comment by inigohidalgo** [comment]
Thanks for the update.

Is it related to MSSQL or a more general thing?

**Comment by cpcloud** [comment]
Not entirely sure yet, we're digging around in it. Will report back when we know more!

**Comment by cpcloud** [comment]
Narrowed it down to a simple failing test case:

SQL setup code:

```sql
DROP TABLE IF EXISTS win;

CREATE TABLE win (g VARCHAR(MAX), x BIGINT, y BIGINT);
INSERT INTO win VALUES
    ('a', 0, 3),
    ('a', 1, 2),
    ('a', 2, 0),
    ('a', 3, 1),
    ('a', 4, 1);
```

Test:

```python
def test_outer_join(con):
    left = con.tables.win
    right = left.filter(left.x >= 3).mutate(x=lambda t: t.x.cast("!int64"))
    expr = left.left_join(right, left.x == right.x)
    result = expr.to_pyarrow()
    assert len(result)
```

**Comment by cpcloud** [comment]
Without the `cast` to a non-nullable type the test passes

**Comment by cpcloud** [comment]
Ok, the root cause is that during the construction of a `pyarrow.Table` we're catching the `ValueError` that is returned by pyarrow when casting fails.

There are a few issues:

1. It's not great that pyarrow raises exception types that have no information in the type itself, but this code is also out of our control and unlikely to ever change
2. We shouldn't catch such as broad exception, regardless of what pyarrow is doing
3. We still have to handle the fact that nullability isn't correct for joins.

**Comment by gforsyth** [comment]
Hey @inigohidalgo!  I just merged in #7554 which fixes the pyarrow exports -- I know this won't immediately impact you working off of the `8.x.x` branch, but we'll rebase it in once we've cut the next 7.x release (which really will be very soon)

**Comment by inigohidalgo** [comment]
Thanks @cpcloud @gforsyth you're amazing. I'll keep an eye out for that next release :)

**Comment by cpcloud** [comment]
I'm going to rebase `8.x.x` on top of `master` now, stay tuned!

**Comment by inigohidalgo** [comment]
Verified that the same join which wasn't working on my initial report is working fine now!

**Comment by inigohidalgo** [comment]
Hi sorry for the spam, last Thursday this was working again on 8.x.x but it seems like the commits were removed from the `8.x.x` branch over the weekend?

**Comment by cpcloud** [comment]
Hm, I will take a look! Thanks for the report!

**Comment by cpcloud** [comment]
This looks like it was part of my accidental clobbering of a few commits from `master` while updating `8.x.x` 😬.

I've since disabled force pushes to `master` to prevent this in the future.

PR this again, and I will merge it and update `8.x.x` right after.

**Comment by cpcloud** [comment]
@inigohidalgo Sorry for the issue, `8.x.x` should have this fix in now. If you encounter any problems don't hesitate to create an issue 😅

**Comment by inigohidalgo** [comment]
Thank you! I am testing it again :)

PD: Do you have another place to communicate like a slack? For things which maybe don't reach the level of needing to post an issue

**Comment by gforsyth** [comment]
You can join our Zulip for asking questions, whatever else! https://ibis-project.zulipchat.com/
