### ISSUE TITLE
feat: PrestoDB backend

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#7503]
the Trino backend generally works w/ Presto, but users have run into issues. we should prioritize a Presto-specific backend

**Comment by gforsyth** [comment]
Worth noting here that the only sqlalchemy dialect with explicit support for Presto is [PyHive](https://github.com/dropbox/PyHive) which is currently not maintained.
Not clear if the Trino dialect is close-enough to work.

**Comment by lostmygithubaccount** [comment]
https://github.com/prestodb/presto-python-client plus sqlglot?

**Comment by gforsyth** [comment]
That is likely the way forward, but makes for a bigger lift in implementation (as opposed to something that is 95% similar to the trino backend)

**Comment by lostmygithubaccount** [comment]
closing as duplicate of #7324
