### ISSUE TITLE
bug: `pyarrow` security vulnerability

### ISSUE THREAD

**Issue by judahrand** [ibis-project/ibis#7515]
### What happened?

Ibis 0.7.0 is pinned to `pyarrow<14`. There are security vulnerabilities in versions before 14.0.1. Can we get a release which allows `ibis` to use a version without vulnerabilities?

https://arrow.apache.org/security/

### What version of ibis are you using?

0.7.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Yep! We should be able to cut one next week.

**Comment by gforsyth** [comment]
Yeah, there's also the bugfix package for backporting which we should also add

**Comment by gforsyth** [comment]
https://pypi.org/project/pyarrow-hotfix/

**Comment by cpcloud** [comment]
@gforsyth For 8.0.0, thoughts on moving the lower bound to 14.0.1?

**Comment by gforsyth** [comment]
My immediate reaction was to be a bit more conservative and use the `pyarrow-hotfix`, but I'm not sure I can back that up?  
I'll think on it for a bit, but I think I'm game to try either path.

**Comment by cpcloud** [comment]
`pyarrow_hotfix` is probably the way to go for now, we can ship it in 7.1 and give our users the confidence that they can continue to use older versions of arrow.

**Comment by cpcloud** [comment]
`pyarrow_hotfix` PR here: https://github.com/ibis-project/ibis/pull/7517

**Comment by cpcloud** [comment]
Closing this, as it will be fixed in 7.1 (and it's backwards compatible).
