### ISSUE TITLE
bug: parse_sql removes where clauses

### ISSUE THREAD

**Issue by AndrewRook** [ibis-project/ibis#7516]
### What happened?

Running the example from #4853 strips the where clause from the query. It's hard for me to say exactly why that's happening or whether it happens in all cases, but I did a couple of tweaks to that example and they all had this problem. Here is my test code:

```python
import ibis

sql = """
SELECT *, first_name as first FROM employee 
LEFT JOIN call ON employee.id = call.employee_id 
WHERE id < 5 
ORDER BY id DESC
"""

catalog = {
    "employee": {"first_name": "string", "last_name": "string", "id": "int64"},
    "call": {
        "start_time": "timestamp",
        "end_time": "timestamp",
        "employee_id": "int64",
        "call_outcome_id": "int64",
    },
    "call_outcome": {"outcome_text": "string", "id": "int64"},
}

expr = ibis.parse_sql(sql, catalog)

print(ibis.decompile(expr, format=True))
```
The output is missing the `.filter(...)` command, as shown in the log below. 

### What version of ibis are you using?

7.0.0

### Relevant log output

```sh
import ibis


employee = ibis.table(
    name="employee",
    schema={"first_name": "string", "last_name": "string", "id": "int64"},
)
call = ibis.table(
    name="call",
    schema={
        "start_time": "timestamp",
        "end_time": "timestamp",
        "employee_id": "int64",
        "call_outcome_id": "int64",
    },
)
leftjoin = employee.left_join(call, employee.id == call.employee_id)

result = leftjoin.select(
    [
        leftjoin.first_name,
        leftjoin.last_name,
        leftjoin.id,
        call.start_time,
        call.end_time,
        call.employee_id,
        call.call_outcome_id,
        leftjoin.first_name.name("first"),
    ]
).order_by(leftjoin.id.desc())
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AndrewRook** [comment]
> Note that this is an experimental feature which we haven't been focusing so far, although the implementation is pretty generic making quick iterations possible.

Yep totally understand if you don't plan on prioritizing support for it. It is pretty cool though so I've been playing around with it. If I shouldn't file additional bug reports just let me know and I will refrain 😄.

**Comment by cpcloud** [comment]
@AndrewRook Please keep filing bug reports! We're definitely interested to see how you're using it.
