### ISSUE TITLE
feat: Add from_string method on BigQueryType to support integration with dbt-ibis

### ISSUE THREAD

**Issue by binste** [ibis-project/ibis#7531]
### Is your feature request related to a problem?

I've created https://github.com/binste/dbt-ibis so that dbt models can be written with Ibis. The integration with various Ibis backends is rather straightforward and the package already supports 8 backends. The only thing I usually need is to be able to convert a column data type as it appears in the database, for example `NUMERIC(38, 10)`, to an `ibis.expr.datatypes.core.DataType` (relevant code in `dbt-ibis` is [here](https://github.com/binste/dbt-ibis/blob/main/dbt_ibis/_dialects.py#L47) for reference). 

With the refactoring in Ibis 7, for most backends this got very easy as I can just use the dialect specific type mappers in `ibis.backends.base.sqlglot.datatypes` such as `DuckDBType` as they all have a `from_string` classmethod.

### Describe the solution you'd like

The BigQuery backend in Ibis does not use SQLGlot and the `ibis.backends.bigquery.datatypes.BigQueryType` class does not have a `from_string` method defined. Would it be possible to add this?

### What version of ibis are you running?

7.0.0 and I also checked master

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
In the meantime you should be able to subclass `SqlglotType` from:

https://github.com/ibis-project/ibis/blob/39ed5f98db8d84f66c25a03b2bfccaf6956f188d/ibis/backends/base/sqlglot/datatypes.py#L124-L146

You'll have to set `dialect = "bigquery"` and potentially set some of the class variables, but you should be able to add support for BigQuery to `dbt-ibis` without waiting for the next release!

**Comment by binste** [comment]
Thanks @cpcloud for the help! I was worried that it would require too much configuration but I tested the following with a few datatypes and it indeed seems to work fine. 🥳  I'll cut a release with it and will switch to an implementation in Ibis if it gets added.

```python
class BigQueryType(SqlglotType):
    dialect = "bigquery"

    default_decimal_precision = 38
    default_decimal_scale = 9
```

**Comment by binste** [comment]
Awesome, thanks! :)
