### ISSUE TITLE
docs: support matrix appears to be broken

### ISSUE THREAD

**Issue by judahrand** [ibis-project/ibis#7535]
### Please describe the issue

The [support matrix](https://ibis-project.org/support_matrix) appears to be broken:

<img width="809" alt="image" src="https://github.com/ibis-project/ibis/assets/17158624/fffbfbf4-a7f7-4df4-af00-839bd7dd8a24">

I'm using Chrome so wouldn't expect it to be a browser issue. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@judahrand Thanks for the report!

The streamlit logs don't show anything informative so I've restarted the app and it's back up.
