### ISSUE TITLE
feat: disable always-failing CI runs in forks

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7568]
### Is your feature request related to a problem?

In my fork, some CI workflows always fail because only the upstream repo has the correct permissions, etc.

For example, it doesn't make sense for my fork to be uploading to GCS on a corn job: https://github.com/NickCrews/ibis/actions/runs/6885281429/workflow

nor this workflow:
https://github.com/NickCrews/ibis/actions/runs/6366788904/workflow

Can we add some `if` to this workflow so it only runs on the upstream repo?

I think this should work:

```
jobs:
  publish:
    if: github.repository_owner == 'ibis-project'
```

Thanks!

### Describe the solution you'd like

See above

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue! Happy to accept a PR!
