### ISSUE TITLE
feat: write to native dump method

### ISSUE THREAD

**Issue by jayceslesar** [ibis-project/ibis#7571]
### Describe the solution you'd like

There already exists `to_pyarrow` and `to_csv`, but not a way to `pg_dump` or something that will dump to something native for that backend?

### What version of ibis are you running?

Master Usually

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@jayceslesar Thanks for the issue! Good to see you around these parts again :)

Do you have a specific case in mind? Is `pg_dump` the main output format you're interested in, or are there other backends than Postgres that you're working with?

**Comment by jayceslesar** [comment]
Hey @cpcloud , I think it would make sense to have a standardize format depending on the backend you are working with. Not sure the exact nuances between `pg_dump`, `mysqldump` but it makes sense to have support for say backing up a database through a common interface. Im not sure if it makes sense for file oriented backends as just rewriting a bunch of parquet files could be costly.

**Comment by cpcloud** [comment]
Thanks!

Do you personally have a specific use case you're interested in? There's quite a large design space here, and we shouldn't build something without a bit more knowledge of what you're interested in.

**Comment by jayceslesar** [comment]
I am interested in using Ibis as the backend for a database/schema migration tool, and in a naive implementation I would not attempt a transactional migration and would just dump the db to a .sql file before running migrations as a safeguard.

**Comment by lostmygithubaccount** [comment]
would using `.raw_sql` to run `pgdump` or whatever be a sufficient workaround here?

**Comment by jayceslesar** [comment]
It would work for postgres 😉 haha. Even a to_pyarrow_batches could work followed by an insert for all the batches which might seem like a cleaner approach. Essentially doing the same thing but instead of the backends native export, it uses existing infra to accomplish the same goal?
