### ISSUE TITLE
bug: Can't execute sql string with clickhouse

### ISSUE THREAD

**Issue by Ssslakter** [ibis-project/ibis#7604]
### What happened?

With this line of code, where items is an arbitrary table
```py
item.sql("select * from items limit 10")
```
I get
```
DatabaseError: :HTTPDriver for server:port returned response code 404)
Unknown setting "json" for EXPLAIN PLAN query. Supported settings: actions, description, header
```

### What version of ibis are you using?

7.1.0

### What backend(s) are you using, if any?

Clickhouse 20.9.3.45 (official build)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue. I suspect that the version of ClickHouse you are on doesn't support `EXPLAIN` in JSON format.

I believe we can adjust our use of this to avoid needing the JSON output.

**Comment by Ssslakter** [comment]
Unfortunately there are not enough resources to migrate all the data at this point. (also considering that usual way sql from clickhouse client works well enough, though not as pretty as ibis interfaces) 
So I guess I'll close the issue on this topic.

By the way, taking the opportunity to ask, is it possible to express this part of clickhouse sql in ibis without raw sql?
```sql
where toYYYYMMDD(date) between 20230210 and 20230101 -- or similarly toYYYYMM(date)
-- and
select groupUniqArray(20)(replaceRegexpAll(table.name, '[^\w]|\d{20,}', ' ')) from table group by date
```
