### ISSUE TITLE
bug: `RelationError` when relating two scalar values from different relations

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7616]
### What happened?

I feel like I already filed a bug for this, but I couldn't find it with some searching? Apologies if so. Thanks for the help!

```python
import ibis
ibis.options.interactive = True

t = ibis.examples.penguins.fetch()
t.distinct().count() == t.count()
```

results in `RelationError: Selection expressions don't fully originate from dependencies of the table expression.`

`t.distinct().count()` and `t.count()` are both scalar values, so they should be able to be compared, even though they are coming from different relations. If we were comparing columns, eg `t.distinct().my_col == t.my_col`, then it makes sense to get this error because how would you "line up" these two columns.

### What version of ibis are you using?

7.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NickCrews** [comment]
A few ideas that I have had to do:

- `t1.count() == t2.count()` (where unlike in the original example t1 and t2 are totally unrelated eg from different parquet files)
- `(t1.ids.max() > t2.ids.max()).ifelse("foo", "bar")`
- `t2.mutate(ids=t1.ids.max() + ibis.row_number() + 1)` (this is relating scalar from t1 to a vector in t2, so a little different, but related)

**Comment by ncclementi** [comment]
Just to report, this on main now brings up a different error. More specifically a `RecursionError`. 

```python-traceback
    293 has_unbound = False
    294 node_types = (ops.UnboundTable, ops.DatabaseTable, ops.SQLQueryResult)
--> 295 for table in self.op().find(node_types):
    296     if isinstance(table, ops.UnboundTable):
    297         has_unbound = True

RecursionError: maximum recursion depth exceeded
```

that being said, I'm not sure if this is the expected bug or there is something else going on here.

**Comment by cpcloud** [comment]
The infinite recursion is definitely unintended 😅

**Comment by ncclementi** [comment]
This is also works as expected now, when using `as_scalar()`. 

```python
In [13]: t.distinct().count().as_scalar() == t.count().as_scalar()
Out[13]: 
┌──────┐
│ True │
└──────┘
```

xref: https://github.com/ibis-project/ibis/issues/10124#issuecomment-2352980478
