### ISSUE TITLE
bug: all-NULL columns are turned to int32 during rountrip to parquet

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7621]
### What happened?

Perhaps this is specific to duckdb? or perhaps it is a bug within duckdb itself?

```python
import ibis
ibis.options.interactive = True

before = ibis.memtable({"a": [None, None, None]}, schema={"a": "string"})
before.to_parquet("tmp.parquet")
after = ibis.read_parquet("tmp.parquet")
```

before appears as
```
┏━━━━━━━━┓
┃ a      ┃
┡━━━━━━━━┩
│ string │
├────────┤
│ NULL   │
│ NULL   │
│ NULL   │
└────────┘
```
after appears as
```
┏━━━━━━━┓
┃ a     ┃
┡━━━━━━━┩
│ int32 │
├───────┤
│  NULL │
│  NULL │
│  NULL │
└───────┘
```
I want the dtype to be preserved as string.

### What version of ibis are you using?

7.1.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Another option might be to insert a cast the columns on view creation of memtables.

**Comment by cpcloud** [comment]
Using only arrow here is probably a better option though if we can make it work.
