### ISSUE TITLE
feat: `ignore_nulls` option for windowing functions

### ISSUE THREAD

**Issue by coroa** [ibis-project/ibis#7649]
### Is your feature request related to a problem?

Especially for filling in nan's with `ffill` and `bfill` like methods, it is very helpful for `lag` and `lead` to support the `IGNORE NULLS` spec.

### Describe the solution you'd like

Windowing functions like `lag` and `lead` should get a new boolean argument `ignore_nulls` which defaults to `False`, so that:

```
SELECT x, COALESCE(y, LAG(y IGNORE NULLS) OVER ())  FROM df
```
can be written as
```
df.select(_.x, ibis.coalesce(_.y, _.y.lag(ignore_nulls=True).over()))
```

It is definitely helpful for
- `lag`
- `lead`
- `first_value`
- `last_value`
- `nth_value`

to a lesser degree to the `rank` functions, not at all, for instance, the `row_number` function.

(refer to duckdb support for instance: https://duckdb.org/docs/sql/window_functions.html#ignoring-nulls) 

### What version of ibis are you running?

7.0.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @coroa -- we are going to tackle this, but I'm going to close this out in favor of #9539 which is a superset issue of this one.

**Comment by coroa** [comment]
> Hey @coroa -- we are going to tackle this, but I'm going to close this out in favor of https://github.com/ibis-project/ibis/issues/9539 which is a superset issue of this one.

Reads more like a subset issue, but i'll watch it and complain then if its completion does not solve my use case :).

Best,
Jonas
