### ISSUE TITLE
refactor(duckdb): use pyarrow.Dataset for all cloudy reads

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#7654]
There will be a slight performance penalty in some situations because `pyarrow.Dataset` doesn't return statistics that DuckDB can use to selectively load data (in some situations).  

On the plus side, `pyarrow` has solved all of the horrible thorny auth issues for reading from various AWS, Azure, and GCP blob stores and it's much simpler to have a single method to point users at.

xref #7493

**Comment by inigohidalgo** [comment]
Pyarrow datasets have been very nice to use for cloud file-based IO. 

Would things like partitioning be within the scope of ibis?

**Comment by gforsyth** [comment]
The DuckDB native cloud readers have gotten better, so we probably won't do this.
