### ISSUE TITLE
feat: UX: `.nullif()` should work whenever `__eq__` does

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7658]
### Is your feature request related to a problem?

This gives `IbisTypeError: Cannot compute precedence for `date` and `string` types`

```python
import ibis

ibis.options.interactive = True

ibis.date("2023-01-01").nullif("2023-01-01")  # doesn't work
ibis.date("2023-01-01").nullif(ibis.date("2023-01-01"))  # this required
```

### Describe the solution you'd like

Whenever I could write my own `ifelse()` using `==`, then `.nullif()` should also work.

### What version of ibis are you running?

master (7.1.0)

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I see where you're coming from, but I don't think we should allow `date == string` as it opens a can of worms:

1. Why wouldn't `1 == "1"` work, or `[1] == "[1]"`? In general, why should strings-in-dates be treated differently than other values-in-strings?
2. What should `t.date_col == t.string_col` do? Should we really allow such an automatic conversion of `string_col` to date? If we don't, do we still allow `date == literal_string`? That seems pretty inconsistent.

```
In [5]: ibis.to_sql(ibis.date("2023-01-01") == "2023-01-01", dialect="duckdb")
Out[5]:
SELECT
  MAKE_DATE(2023, 1, 1) = '2023-01-01' AS "Equals(datetime.date(2023, 1, 1), '2023-01-01')"
```

This SQL looks pretty sketchy to me. For some backends, the string literal date will work for others it won't.

**Comment by cpcloud** [comment]
I realize that this is allowed right now, so this would probably be a breaking change.

**Comment by NickCrews** [comment]
Just noticed that duckdb [manages to support this](https://duckdb.org/docs/sql/data_types/literal_types.html), but only by adding in a special type just for integer and string literals. I could see how that owuld be technically be possible and would have the semantics we want, but I'm guessing that would be *way* too much special casing within ibis's guts to be worth it.
