### ISSUE TITLE
feat: Support for custom aggregation functions over distinct values

### ISSUE THREAD

**Issue by arun-k-bharathan** [ibis-project/ibis#7659]
### Is your feature request related to a problem?

I was not able to write a ibis query equivalent to below SQL query.
```sql
select count(distinct name) as name_count, sum(distinct age) as age_sum from dist
```

### Describe the solution you'd like

The
```sql
select count(distinct name) as name_count, sum(distinct age) as age_sum from dist
```
on this table
|  id | name  |  age |
|---|---|---|
|  1 | john  | 22  |
| 2  | jane  | 22  |
|  3 | john  | 24  |
|4|jimmy|25|
|5|jane|26|

should produce a result like this.
|name_count|age_sum|
|---|----|
|3|97|

### What version of ibis are you running?

7.1.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chloeh13q** [comment]
I think the problem here is that ibis doesn't support distinct on columns. There is `distinct()` on tables and `nunique()` on columns (and tables), which translates into count distinct as a single operation

**Comment by gforsyth** [comment]
this is gross, but functional:

```python
[ins] In [1]: import ibis

[ins] In [2]: from ibis import _

[ins] In [3]: ibis.options.interactive = True

[ins] In [4]: t = ibis.memtable(
         ...:     {
         ...:         "id": [1, 2, 3, 4, 5],
         ...:         "name": ["john", "jane", "john", "jimmy", "jane"],
         ...:         "age": [22, 22, 24, 25, 26],
         ...:     }
         ...: )

[ins] In [5]: t
Out[5]: 
┏━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃ id    ┃ name   ┃ age   ┃
┡━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ int64 │ string │ int64 │
├───────┼────────┼───────┤
│     1 │ john   │    22 │
│     2 │ jane   │    22 │
│     3 │ john   │    24 │
│     4 │ jimmy  │    25 │
│     5 │ jane   │    26 │
└───────┴────────┴───────┘

[ins] In [6]: expr = t.select(
         ...:     name_count=_.distinct(on="name").name.count(),
         ...:     age_sum=_.distinct(on="age").age.sum(),
         ...: ).distinct()

[ins] In [7]: expr
Out[7]: 
┏━━━━━━━━━━━━┳━━━━━━━━━┓
┃ name_count ┃ age_sum ┃
┡━━━━━━━━━━━━╇━━━━━━━━━┩
│ int64      │ int64   │
├────────────┼─────────┤
│          3 │      97 │
└────────────┴─────────┘
```

**Comment by cpcloud** [comment]
[Here's a long discussion](https://github.com/ibis-project/ibis/discussions/6222) about why column operations that change output cardinality are not easily modeled in the Ibis API.

The discussion is about slicing, but everything there applies to `distinct` as well.

**Comment by chloeh13q** [comment]
Thanks! That makes sense. Seems like it would be reasonable to close this then?
