### ISSUE TITLE
mssql server alternative schemas connection

### ISSUE THREAD

**Issue by carlsunderman** [ibis-project/ibis#7674]
I'm able to connect to any table in the dbo schema for mssql, but what about other schemas? I tried using schema="myschema" in the connection, but this doesn't work. can ibis connect to schemas other than dbo for mssql?

**Comment by carlsunderman** [comment]
I've tried both in ibis.mssql.connect and con.table  in the first, it just doesn't like the keyword, in the second , con.table, when i use schema="myschema" , "tablename" it throws an error "positional argument follows keyword argument", but if i define table = "tablename" it doesn't like the table keyword

**Comment by gforsyth** [comment]
@carlsunderman -- if you pass in the table name first it should work:

```python

[ins] In [11]: astronauts = con.table("astronauts", schema="guest")

[ins] In [12]: astronauts
Out[12]: 
DatabaseTable: astronauts
  id     int64
  number int64

[ins] In [13]: astronauts = con.table("astronauts", schema="dbo")

[ins] In [14]: astronauts
Out[14]: 
DatabaseTable: astronauts
  id                       int64
  number                   int64
  nationwide_number        int64
  name                     string
  original_name            string
  sex                      string
  year_of_birth            int64
  nationality              string
  military_civilian        string
  selection                string
  year_of_selection        int64
  mission_number           int64
  total_number_of_missions int64
  occupation               string
  year_of_mission          int64
  mission_title            string
  ascend_shuttle           string
  in_orbit                 string
  descend_shuttle          string
  hours_mission            float64
  total_hrs_sum            float64
  field21                  int64
  eva_hrs_mission          float64
  total_eva_hrs            float64
```

**Comment by carlsunderman** [comment]
@gforsyth ok, so it seems it was my error, passing the table name first does resolve the issue. Is this in the docs?

**Comment by gforsyth** [comment]
Hey @carlsunderman -- I'll take a look. I think it probably is but it would be buried in a not-so-helpful place.  We've recently refactored cross-schema + cross-database access and could use a short guide on how to use the new functionality.

**Comment by carlsunderman** [comment]
So I  do have a particular set of  schemas that when I try to connect to, I still receive an error. it says, "cannot find stored procedure <custom_schema name>.<tablename>" but it appears to be tables in SSMS and Sql Alchemy, connectorX, pyodbc,etc can connect and query. Any idea why this error would be thrown and why it would think it was a stored procedure vs a table?
