### ISSUE TITLE
bug: dev releases on PyPI are in weird order

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7678]
### What happened?

I would expect the [8.0.0dev{N} releases](https://pypi.org/project/ibis-framework/#history) to go in increasing N over time. But 109 was released on Dec 2, AFTER 321 on Nov 11. Am I misunderstanding something here?

<img width="358" alt="image" src="https://github.com/ibis-project/ibis/assets/10820686/9569a348-d3c7-427f-a2fc-11092b086842">

### What version of ibis are you using?

NA

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by inigohidalgo** [comment]
Hi

To me it looks like the releases are still in order, but the order got reset after november 19 which lines up with this https://github.com/ibis-project/ibis/issues/7487#issuecomment-1818904937

**Comment by cpcloud** [comment]
Ah, nice sleuthing @inigohidalgo!
