### ISSUE TITLE
feat: UX: add `n: int` arg to `Table.sample()`

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7689]
### Is your feature request related to a problem?

Instead of specifying the fraction, I want to sample an absolute number of rows.

This is a nice-to-have, I can get something working without it, but it seems like many people will be trying to do the same thing, and therefore it would be great to have one efficient, bug-free implementation here. Close this out if not currently a priority, but at least I wanted an issue up for this.

### Describe the solution you'd like

Some backends support this natively ([duckdb](https://duckdb.org/docs/sql/samples), [MSSQL](https://learn.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms189108(v=sql.105)?redirectedfrom=MSDN)), some don't (postgres).

When supported, do it natively. When not supported, could either:
- error, similar to when you ask for `seed` and it's not supported
- hack something together on the python end, eg oversampling and then LIMITing the result?

### What version of ibis are you running?

NA

### What backend(s) are you using, if any?

duckdb for me mostly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ogrisel** [comment]
> hack something together on the python end, eg oversampling and then LIMITing the result?

That would introduce a bias if the order is meaningful, unless your randomly reorder before limiting.

However `ibis.random()` (possibly used to reorder the sampled element before truncation) does not accept the `seed` argument, so that would not be repeatable, even when `table.sample` is.

**Comment by NickCrews** [comment]
Oops, indeed you are right!

**Comment by lostmygithubaccount** [comment]
I could use this as well. my use-case is creating an Ibis UDF that will randomly select a single row from one Ibis table to generate synthetic data for a second Ibis table (recreating the one billion row challenge w/ LLMs)

@NickCrews how are you accomplishing this now?

**Comment by NickCrews** [comment]
I don't actually need an exact amount, but somewhere in the ballpark, so I just use fraction and the result is usually within 10% of my goal. So I don't have anything useful to share :(

**Comment by cpcloud** [comment]
Closing as stale. Seems like there's a viable workaround for now.

**Comment by NickCrews** [comment]
I have found a maybe better way. Any suggestions would be greatly appreciated. I don't *think* we'd want to merge this into ibis, the properties are weird enough that I'm not sure we should "endorse" this method.

```python
import random

import ibis


def shuffle(t: ibis.Table, *, seed: int | None = None) -> ibis.Table:
    """Shuffle a table in a reproducible way.

    Uses `ibis.row_number().hash()` to generate a pseudo-random number for each row,
    and then sorts by that "random" number. This means that if you shuffle the same
    table with the same seed, you will get the same result. If you change the seed,
    you will get a different result.

    This results in several "weird" properties that you should be aware of,
    and make this unsuitable for cryptographic (or many other) purposes:

    1. If you shuffle two tables with different elements but the same number of rows,
    they will be shuffled "the same",
    eg row 0 of both tables will end up in row 8, row 1 will end up in row 3, etc.

    2. Say you shuffle a table with values ``[a, b, c, d]``.
    You might get an ordering of ``[c, b, a, d]``.
    Then, say you shuffle ``[a, b, c, d, e]`` (ie the exact same table, but with
    one appended row). You might get an ordering of ``[c, e, b, a, d]``.

    They look nearly the same, but with the new row inserted somewhere randomly.
    This is because the hashes of the first N rows remain the same,
    so relative to each other they will stay in the same order.
    It's just the new N+1 row that will get hashed to a new some random number
    and will end up somewhere in the middle of the sequence.

    Parameters
    ----------
    t :
        The table to shuffle
    seed :
        The seed to use for the shuffle. If None, a random seed is used.

    Returns
    -------
    The shuffled table
    """
    if seed is None:
        seed = random.randint(0, 2**32)
    return t.mutate(__rn=ibis.row_number() + seed).order_by(_.__rn.hash()).drop("__rn")


def sample(t: ibis.Table, n: int, *, seed: int | None = None) -> ibis.Table:
    """Sample a table to n rows.

    This uses the `shuffle` function to shuffle the table,
    and then takes the first n rows.
    This means that the randomness has the same properties as `shuffle`,
    see that function for more details.

    Parameters
    ----------
    t :
        The table to sample
    n :
        The number of rows to sample
    seed :
        The seed to use for the shuffle. If None, a random seed is used.

    Returns
    -------
    The sampled table
    """
    return shuffle(t, seed=seed).limit(n)
```
