### ISSUE TITLE
feat: support for NULLS FIRST / NULLS LAST in ordering

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#77]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Saturday Jan 24, 2015 at 20:55 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/77_

---

**Comment by saulpw** [comment]
I think `NULLS LAST` should be the default, because when I ask for the top N in a query, I want to get the top N, and not N nulls.  I don't know that we need an option to do something different though, to be honest.

**Comment by goodwanghan** [comment]
@saulpw @cpcloud `NULLS FIRST` and `NULLS LAST` are part of the SQL that major backends all support. I think this should be implemented. 

https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#order_by_clause

https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-order-by/

https://duckdb.org/docs/sql/query_syntax/orderby
