### ISSUE TITLE
docs: inherited backend functionality isn't documented

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis#7715]
### Please describe the issue

For example, I wanted to read the API reference of `create_view` for the DuckDB backend. However, I assume because it's inherited from `BaseAlchemyBackend`, it's nowhere in the doc. (I can go back to the code implementation on GitHub to read it, but that's only because I know where to find it.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
@deepyaman is this something you could take a stab at adding? it might need to be done explicitly, Phillip mentioned there might also be an upstream quartodoc issue on this one

**Comment by deepyaman** [comment]
> @deepyaman is this something you could take a stab at adding? it might need to be done explicitly, Phillip mentioned there might also be an upstream quartodoc issue on this one

Sure, happy to take a pass this week!
