### ISSUE TITLE
docs: replicate spatial dev guru blog w/ Ibis + DuckDB

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#7717]
### Please describe the issue

Replicate this blog: https://spatial-dev.guru/2023/12/09/geospatial-analysis-using-duckdb/ w/ Ibis + DuckDB

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ncclementi** [comment]
Blocked on https://github.com/ibis-project/ibis/issues/7716.
