### ISSUE TITLE
Bring your own API

### ISSUE THREAD

**Issue by ion-elgreco** [ibis-project/ibis#7721]
### Is your feature request related to a problem?

I don't particularly like the IBIS API, would be nice if I can simply use the Polars API and then dispatch the execution to another backend through Ibis.

### Describe the solution you'd like

Would it make sense it to allow users bring their own dataframe API, for example your API of preference (pandas/Polars) and then let IBIS handle the conversion.

### What version of ibis are you running?

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @ion-elgreco!

Thanks for the issue.

You're welcome to create an API that looks like Polars or Pandas and produces Ibis expressions.

However, we're not going to take on the maintenance burden of N APIs to M backends. Maintaining one side of this (the Ibis API to backends mapping) is already a lot of work.

The user-facing API in Polars (for example) is extremely unstable so we'd have to closely track upstream which would result in a large increase in maintenance. Doing this for Pandas would also be a huge amount of work.

**Comment by ion-elgreco** [comment]
Wouldn't this eventually be possible if all the libraries implement Substrait, then IBIS can be the glue between them?

**Comment by cpcloud** [comment]
Indeed it might!

**Comment by lostmygithubaccount** [comment]
@ion-elgreco I am curious what specifically about the Polars API you prefer compared to Ibis -- both are heavily inspired by pandas but Ibis is a bit more mature

if you or anyone finding this are interested in the pandas API on Ibis, Google's `bigframes` has already implemented a lot of the work needed: https://github.com/googleapis/python-bigquery-dataframes. it could probably be forked and made to support arbitrary Ibis backends with some amount of effort
