### ISSUE TITLE
conda ibis-pandas does not exist

### ISSUE THREAD

**Issue by jettdc** [ibis-project/ibis#7724]
### What happened?

the `ibis-pandas` package does not exist on conda but is listed on the installation website https://ibis-project.org/install

### What version of ibis are you using?

x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for flagging that, @jettdc !  I'll add that to our feedstock repo for consistency.

**Comment by gforsyth** [comment]
Should be available in about 20 minutes after the post-merge build finishes.  Thanks again!
