### ISSUE TITLE
docs: website takes forever to load

### ISSUE THREAD

**Issue by jettdc** [ibis-project/ibis#7725]
### Please describe the issue

The website consistently takes 10-15 seconds to load (in the USA). https://ibis-project.org/ should be served on a cdn or something similar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @jettdc -- which browser and OS are you using?  I get a pretty snappy response with both Firefox and Chrome (using private / incognito mode so I'm not re-using cached pages)

**Comment by lostmygithubaccount** [comment]
the docs are hosted on Netlify, presumably taking care of CDNs and whatnot. I'm also not seeing such slow load times and I'm on satellite internet

**Comment by jettdc** [comment]
Using chrome on macos, so must be my VPN setup or something 🤷
