### ISSUE TITLE
docs(flink): override default install instructions

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis#7738]
### Please describe the issue

Installing the Flink backend should be done with `pip install ibis-framework apache-flink` (or `pip install ibis-framework 'apache-flink>=1.18'`?). This differs from the installation instructions for every other backend, so probably needs to be overridden in the overlay.

Also, we don't yet have a path to supporting installation with `conda/mamba`, [pending Flink being made available via `conda-forge`](https://apache-flink.slack.com/archives/C065944F9M2/p1701811320307299).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
For the pip install question, was this the issue of the beamer pin leaving us with an older version of pyarrow?

Because that only impacts ibis developers and users of the flink backend and we've dealt with pyarrow pins before (mostly with snowflake)

**Comment by deepyaman** [comment]
> For the pip install question, was this the issue of the beamer pin leaving us with an older version of pyarrow?
> 
> Because that only impacts ibis developers and users of the flink backend and we've dealt with pyarrow pins before (mostly with snowflake)

@gforsyth Yes; in order to avoid that, we've not added `apache-flink` to the "flink" extra requirements.

I think @cpcloud also mentioned the Snowflake example (recently resolved), and that we could find a way to include the extra while not downgrading PyArrow for every other backend during development/testing.

I'm flexible on this; if you all think it's easy/convenient to override the PyArrow pin for dev/CI, it would obviously be nice to be able to just do `pip install ibis-framework[flink]`. That being said, `pip install ibis-framework apache-flink` isn't all that ugly, either.

**Comment by cpcloud** [comment]
Closed by #7751.
