### ISSUE TITLE
docs: Unclear who is behind Ibis from the docs

### ISSUE THREAD

**Issue by OlivierBinette** [ibis-project/ibis#7743]
### Please describe the issue

The docs don't provide much information about how well Ibis is supported and what is the long-term development roadmap. This information would be helpful when considering whether or not to use Ibis as a dependency in other software systems.

For instance, it would be useful to know:

- Does Ibis have any full-time developers or maintainers?
- Are there businesses commited to the development and support of Ibis?
- Can we expect long term support for Ibis?
- Is the API stable, or should we expect major changes or refactoring in the future?
- Are there known issues that should be considered when considering to adopt Ibis as a dependency of a software system (e.g., known incompatibilities)?
- Are there consulting companies that provide enterprise support for Ibis?
- Does Ibis follow well-known security standards?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
that's fair! one of the engineers can chime in, but to answer some of these here (will definitely add this in the documentation):

> Does Ibis have any full-time developers or maintainers?

yep! while Ibis receives contribution from many companies, it is primarily backed by [Voltron Data](https://voltrondata.com/) which has a team of (currently) 5 full-time developers (and one Technical Product Manager!) working on the project. some of the key developers are listed in the steering committee: https://github.com/ibis-project/governance/blob/main/governance.md#steering-committee-members

> Are there businesses commited to the development and support of Ibis?

yep! as mentioned, Voltron Data. additionally, [Google builds their pandas API clone on Ibis](https://github.com/googleapis/python-bigquery-dataframes), [Starburst Galaxy recommends Ibis alongside their proprietary dataframe library](https://www.starburst.io/blog/introducing-python-dataframes/), Claypot AI is currently contributing heavily on a new Flink backend, Exasol developers are contributing a new backend, [Microsoft did a project on Ibis](https://voltrondata.com/resources/microsoft-magpie-uses-ibis-to-optimize-computation) (this one's a bit old) -- we are working with other companies to increase (official) adoption of Ibis for their data platforms

> Can we expect long term support for Ibis?

generally, yes -- this one is a little hard to promise publicly, as you never know what will happen, but Voltron Data is well-funded, the Ibis project is an independently governed and currently thriving open-source product, and the developers have no plans of stopping support

> Is the API stable, or should we expect major changes or refactoring in the future?

it is generally stable and mature, though there are occasional breaking changes. most of these shouldn't affect normal usage and are typically backward compatible; Ibis is also relatively explicit about semantic versioning relative to other Python packages that have breaking API changes within major versions

> Are there known issues that should be considered when considering to adopt Ibis as a dependency of a software system (e.g., known incompatibilities)?

not really? Ibis does have a number of Python dependencies, and it's hard to avoid issues in the Python ecosystem, but no major known blockers

> Are there consulting companies that provide enterprise support for Ibis?

I'm not sure. Voltron Data [does offer enterprise support for open-source projects including Ibis](https://voltrondata.com/enterprise-support), though often collaborating via open-source is sufficient

> Does Ibis follow well-known security standards?

I think so -- this is better for the developers to answer, but in general it's just a Python package. we upgrade dependencies if there are security issues (e.g. happened with PyArrow recently) and address any security issues quickly 

we've also just started a (currently private) GitHub project to track the roadmap, our plan is to use that for a bit then evaluate making it public 

appreciate the issue @OlivierBinette! hope this helps answer some of the questions, I'll work on getting this info in a doc

**Comment by lostmygithubaccount** [comment]
also for some backstory -- Ibis was created by Wes McKinney, the creator of pandas, co-creator of Apache Arrow, and cofounder of Voltron Data (among other things) in 2015 as a pandas-like interface to Impala. the project had ups and downs in development, but in the past few years has been heavily invested in by Voltron Data, led by Phillip Cloud and others on the Ibis team at the company

the overall goal is a portable, Pythonic dataframe library for the composable data ecosystem. some good articles on backstory include:

- https://wesmckinney.com/blog/apache-arrow-pandas-internals/
- https://wesmckinney.com/blog/looking-back-15-years/
- https://voltrondata.com/codex

**Comment by OlivierBinette** [comment]
Thanks for the info! I only recently started using Ibis, but it has already been an amazing tool. This info should help me and others adopt Ibis.

**Comment by NickCrews** [comment]
Echoing that making the roadmap public would be awesome. Putting some of this other info (at least the stable stuff, like past users of ibis and the history) into the https://ibis-project.org/why might be nice.

@OlivierBinette, chiming as a user and occasional contributor as to my experience with Ibis: I have been very impressed with the responsiveness of the team. When I report bugs they are usually addressed within the next release in the next 1-2 months, and some feature requests of mine have been implemented with little convincing needed. The detailed CHANGELOG has made version transitions fairly easy, though there has been some bulk refactoring occasionally needed, but through the last 3 major version upgrades I've gone through the process has never been that bad. Nothing but good things to say :), I hope you join along!

**Comment by cpcloud** [comment]
@OlivierBinette If you're up for yet-another-chat-app, join our Zulip (https://ibis-project.zulipchat.com/)!
