### ISSUE TITLE
discuss: deprecate Expr.get_name()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7762]
### Is your feature request related to a problem?

Inspired by https://github.com/ibis-project/ibis/issues/7742#issuecomment-1855568774

Should/how we deprecate Expr.get_name()?

I would probably vote yes? But I think it would be useful to try to list the uses of it to see if removing it would really be painful. If you have a usecase, please add it in this thread?

I use it in one place in my codebase. I have to hand off some Tables to a [`splink.Linker` object](https://moj-analytical-services.github.io/splink/linker.html#splink.linker.Linker.__init__), which expects a list of table names in the underlying DB. So all of my input tables need to be named. To do that, I rely on:

```python
def ensure_named(t: Table, name: str | None = None) -> Table:
    if name is None:
        name = _unique_table_name()
    try:
        old_name = t.get_name()
    except AttributeError:
        pass
    if old_name == name:
        return t
    return t.alias(name)
```

There are other ways I could do this, using `.cache()` or similar. Basically, I want the semantics of

1. need: the table must end up with a name, either as a real table or as a view
2. need: I need to know the name of the table after that
3. want: I can name the table as I want
4. want: if the input table is already named in the DB, don't add another view.

Requirement #4 might be hard without .get_name(), is there some other way to tell if a table is already named in the DB?

### Describe the solution you'd like

NA

### What version of ibis are you running?

Na

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tswast** [comment]
What's the purpose of this deprecation? We use `get_name()` as really one of the core functionalities of Ibis in BigQuery DataFrames.

I suppose maybe it makes less sense for table expressions, but even these can have aliases in SQL.

**Comment by jcrist** [comment]
@NickCrews - how would you propose users get the underlying table name if `.get_name()` goes away?

**Comment by NickCrews** [comment]
Yeah I think this was half-baked, we need some way to know the name. Feel free to close this
