### ISSUE TITLE
feat: clean up UDF namespace

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7763]
### Is your feature request related to a problem?

Some internals are exposed:

<img width="349" alt="image" src="https://github.com/ibis-project/ibis/assets/10820686/bc316284-350b-4c6f-a871-4d25b3fcfc8d">

### Describe the solution you'd like

I would expect only

builtin
python
pyarrow
pandas

to be shown as hints

### What version of ibis are you running?

7.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This is what I see on 37dd1951699e26ff4dd9067efe858a7b25c1a622, using IPython:

![image](https://github.com/ibis-project/ibis/assets/417981/8081f4b5-4385-42fa-be1e-50fdbf0207b7)

![image](https://github.com/ibis-project/ibis/assets/417981/b90d9704-67dc-4b62-b42b-b7756f13e727)

The `register` method is coming from `ABCMeta`, which we don't have control over and overriding `__dir__` here on the subclass seems overkill.
