### ISSUE TITLE
bug: TypeError: unsupported operand type(s) for |: 'BooleanColumn' and 'NullScalar', regression in ibis 7.x

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#7775]
### What happened?

Previously (ibis 6.x), we could apply &, |, and other binary operators with null literal values. 

```
import ibis
ibis.literal(True) & ibis.null()
# Out[1]: And(True, None): True & None
```

Now, this causes an error:

```
import ibis
ibis.literal(True) & ibis.null()
# TypeError: unsupported operand type(s) for &: 'BooleanScalar' and 'NullScalar'
```

### What version of ibis are you using?

7.1.0

### What backend(s) are you using, if any?

N/A

### Relevant log output

```sh
Python 3.10.9 (main, Dec 14 2022, 20:14:08) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ibis
   ...: ibis.literal(True) & ibis.null()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 2
      1 import ibis
----> 2 ibis.literal(True) & ibis.null()

TypeError: unsupported operand type(s) for &: 'BooleanScalar' and 'NullScalar'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@kszucs This was broken in c20ba7f, can you look into it?

**Comment by cpcloud** [comment]
The issue is that `GenericInstanceOf` is too strict for the `Value` pattern:

```
In [1]: import ibis.expr.operations as ops

In [2]: ops.And(ops.Literal(None, dtype='null'), ops.Literal(True, dtype='boolean'))
...
SignatureValidationError: And(<ibis.expr.operations.generic.Literal object at 0x7f25727ee340>, <ibis.expr.operations.generic.Literal object at 0x7f257937e7f0>) has failed due to the following errors:
  `left`: <ibis.expr.operations.generic.Literal object at 0x7f25727ee340> is not coercible to a Value[Boolean, DataShape]

Expected signature: And(left: Value[Boolean, DataShape], right: Value[Boolean, DataShape])
```

`Value[T]` should always mean `Value[T | dt.Null]` so that we don't have to play whack-a-mole annotating every operation that allows `NULL` as input. We can restrict the very very small number of operations that do by using `~InstanceOf` if we actually ever need to.

**Comment by kszucs** [comment]
The only way to `GenericInstanceOf` less restrictive is to create a custom pattern which would defeat the point of the strict validation rules.

> Value[T] should always mean Value[T | dt.Null]

This is probably an oversimplification where we would end up with even more custom rules. So actually I would prefer to be explicit here and explicitly allow `dt.Null` where we need to. Actually we use plain `Value|Column|Scalar` most of the places where `dt.Any` is used supporting `dt.Null`. For numeric ops we use type aliases https://github.com/ibis-project/ibis/blob/168f3e82981f027500982c22d416d5e88ef65359/ibis/expr/operations/numeric.py#L14-L16 so being explicit is not that horrible.
