### ISSUE TITLE
docs: https://ibis-project.org/reference/expression-generic#examples-36

### ISSUE THREAD

**Issue by hengaini2055** [ibis-project/ibis#7787]
### Please describe the issue

There is an error:
```
IbisError: Expression contains unbound tables and therefore cannot be executed. Use ibis.<backend>.execute(expr) or assign a backend instance to `ibis.options.default_backend`.
```
I reproduce this. What about this one?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the report, definitely a bug!
