### ISSUE TITLE
feat: String.re_split()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7799]
### Is your feature request related to a problem?

I have to split a string not on a constant char, but on a pattern.

An easy workaround I can now easily (🎉 yay thank you!) do for duckdb is

```python
@ibis.udf.scalar.builtin
def re_split(s: str, pattern: str) -> list[str]:
    ...
```

Or do [other various shenanigans](https://github.com/pola-rs/polars/issues/4819) but I figure that this could be common enough to make it builtin.

### Describe the solution you'd like

 If a backend doesn't implement this natively, then I think the expression could be rewritten as a less efficient  and hacky `s.re_replace(split_pattern, "a-very-unlikely-substring".split("a-very-unlikely-substring")`

bankends known to implement:
- duckdb
- postgres
- trino
- pandas
- dask

 known to not implement
- bigquery
- polars

### What version of ibis are you running?

NA

### What backend(s) are you using, if any?

personally duckdb, but I understand ya gotta take the other backends in mind :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Just to put a finer point on it:

- BigQuery: doesn't exist, but we can probably use a JavaScript UDF here
- ClickHouse: `splitByRegexp` (https://clickhouse.com/docs/en/sql-reference/functions/splitting-merging-functions#splitbyregexp)
- Dask: same as pandas
- DataFusion: doesn't exist, but a pyarrow UDF would work
- Druid: Something named `STRING_TO_MV` (https://druid.apache.org/docs/latest/querying/sql-multivalue-string-functions/)
- DuckDB: `string_split_regex` (https://duckdb.org/docs/sql/functions/char.html)
- Exasol: Don't see it anywhere
- Flink: Doesn't exist AFAICT from looking at https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/functions/systemfunctions/
- Impala: ?
- MS SQL: (no arrays)
- MySQL: (no arrays)
- Oracle: (no arrays)
- Pandas: `series.str.split(pattern, regex=True)`
- Polars: a pyarrow UDF might work
- Postgres: `regexp_split_to_array`
- PySpark: `split` (https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.split.html)
- Snowflake: doesn't exist, but a JavaScript will probably work
- SQLite: (no arrays)
- Trino: `regexp_split` (https://trino.io/docs/current/functions/regexp.html)

**Comment by NickCrews** [comment]
wow that was fast, thank you so much!
