### ISSUE TITLE
feat: JSON data types

### ISSUE THREAD

**Issue by andrioni** [ibis-project/ibis#782]
Hi, I was wondering what would be the best way to treat JSON/JSONB columns from Postgres in Ibis. Currently I'm trying to treat it as a string (although it gets converted to a `dict` whenever I send the data to a pandas dataframe), but I'm not sure if that's the right solution.

**Comment by wesm** [comment]
Good question! What are you trying to do with the data? I haven't thought through how we could incorporate schema-less JSON into Ibis's data model. For nested data in Hive, Impala, Spark SQL, etc., it's a little more clear what should be done.

**Comment by cpcloud** [comment]
FWIW, Presto has a `JSON` type stored as a string. The main purpose is serves is to indicate that the underlying string is valid JSON. For example,

```sql
select json '[a"]'
```

fails because it can't be parsed as valid json, whereas

```sql
select json '["a"]'
```

is converted to json.

**Comment by cpcloud** [comment]
Additionally Presto uses a subset of [JSONPath](http://goessner.net/articles/JsonPath/) to let users pick out parts of the JSON blob that they want. 

An ibis-worthy API might look something like this:

```python
t.blob_of_json.extract('$.foo.bar')
t.blob_of_json.extract('$.foo.bar', type='int64')
t.blob_of_json.cast('$.foo', 'array<int64>')
```

**Comment by cpcloud** [comment]
We could also leverage [jsonpath-rw](https://github.com/kennknowles/python-jsonpath-rw) which is a Python DSL that generates JSONPath expressions.

**Comment by cpcloud** [comment]
Should we limit the scope here? E.g., arbitrary JSON is out of scope, but JSON with a well-defined, uniform schema per record (including arbitrary nesting) is in scope.

The [Apache Drill data model](https://drill.apache.org/docs/json-data-model) page is an excellent read and IMO a nice indication of reasonable expectations to set for JSON functionality.

@wesm thoughts?

**Comment by wesm** [comment]
Makes sense to me. I think one of the challenges will be supporting nested data generally given the diverging semantics of different SQL engines (for example: comparing Hive, Presto, and Impala).

**Comment by cpcloud** [comment]
For the record it looks like each of the systems mentioned by @wesm have three different ways of unnesting for arrays (similar for maps):

Given a table `t`:

```sql
CREATE TABLE t (
  elements ARRAY<STRING>
)
```

Hive:
```sql
SELECT element
FROM t
LATERAL VIEW explode(elements) s AS element;
```

Presto:
```sql
SELECT s.element
FROM t
CROSS JOIN unnest(elements) AS s (element)
```

Impala:
```sql
SELECT elements.item
FROM t, t.elements
```

I think we can come up with a reasonable API for doing these operations.

**Comment by wesm** [comment]
Cool thanks for looking into this. Might also be good to look at BigQuery for another data point. From the Ibis perspective, it might make the most sense to model this explicitly as a join. Expression analysis/validation may well become more complex, though.

**Comment by cpcloud** [comment]
BigQuery:

```sql
SELECT element
FROM t.elements
```
or
```sql
SELECT element
FROM UNNEST (t.elements)
```
The `UNNEST` is optional according to [the docs](https://cloud.google.com/bigquery/sql-reference/query-syntax#unnest)

**Comment by cpcloud** [comment]
I'll make a new issue for the array API. I've started work on it by way of getting the type system in place and also added an "array_agg" function (called `collect`), indexing/slicing, and length computation. More details in the issue.

**Comment by cpcloud** [comment]
We have JSON and JSONB types now, and with 3e2efb433 we have a minimal API for extracting object values or array elements. The remaining work is implement feature requests for additional APIs, so I'm going to close this out as completed.
