### ISSUE TITLE
[discussion] Support `always_xy` for GeoConvert 

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#7835]
After playing around a bit with duckdb `ST_Transform` function and our Ibis implementation `convert` I ran into couple of problems, that are mostly related to conventions, and choices of a what's the default.

After a discussion with @gforsyth we found out that in `duckdb`:

- Output is always in x, y format
- The assume input (with default value `always_xy=False`) is lat/long which is equivalent to y, x
- If the user is providing input data as lon/lat they need to pass `always_xy=True`

But it also depends on the projection parameters you pass in. I think the big source of confusion is that wgs84 (epsg 4326) is standardized to be in lat/lon (even though almost all gis systems ignore that and pretend its always lon/lat), while basically every other projection youd care about is in lon/lat. 

In `Geopandas` things are different (@jorisvandenbossche please correct us here if we are wrong) : 

- All the inputs are expected as lon/lat 
- Somehow things get handled for the case of `epsg 4326` 

I think this means that we should expose the `always_xy` variable to the user but maybe not?. That being said the name is terrible and we should change it, ideas are welcome.

**Comment by gforsyth** [comment]
We talked about this a bit offline, but I'll write out here what I think we should do (with the caveat that I don't know anything except what I've read in the last day or two).

It seems like PostGIS always expects coordinates in XY order (long/lat in ESPG4326).

For datasets that are in YX order, they have a function to flip those coordinates: https://postgis.net/docs/ST_FlipCoordinates.html

I think this is a reasonable approach to follow and DuckDB spatial does have a fast flip coordinates function we can make use of.


So all geospatial calls assume XY ordering, and if a user has data already ingested in YX ordering, then they can flip them and proceed from there.

This also seems much simpler from a documentation perspective -- we can state at the top of our geospatial docs that all operations assume XY ordering and explain using flip as necessary.

So I say we leave the `always_xy` argument hardcoded and users only have to think about coordinate order at the beginning of their analysis (if at all) and not every time they do a transform.

**Comment by gforsyth** [comment]
xref: https://github.com/duckdb/duckdb_spatial/issues/63

**Comment by ncclementi** [comment]
I agree and I think this is a sensitive choice. I'll leave this issue open until sorted and maybe there are more opinions but for now the TODOs are:
- [ ] Add extra line of docs to our `convert` function to state that we expect that all operations assume XY ordering (long/lat)  and to use `flip_coordinates` if needed to satisfy this.
- [ ] Implement `flip_coordinates`
