### ISSUE TITLE
test(pandas): re-enable `test_udaf_window_nan` test case

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#7893]
### What happened?

Follow-up for https://github.com/ibis-project/ibis/pull/7797

`ibis/backends/pandas/tests/test_udf.py::test_udaf_window_nan` is failing for pandas, but duckdb produces the same result while the expected is different. Need to check whether the expected value is correct or not and fix the implementations if required.

### What version of ibis are you using?

the-epic-split

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@kszucs Does this still need investigation?

**Comment by jcrist** [comment]
I think if we delete the legacy udf functionality (#8567) then this test case can just be deleted too.

**Comment by cpcloud** [comment]
Closing this, since we've deprecated legacy UDF functionality.
