### ISSUE TITLE
meta: Port backends to new relational operators/sqlglot

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#7909]
We currently have a [long running branch](https://github.com/ibis-project/ibis/tree/the-epic-split) porting backends to use the new relational operators (and sql backends to use sqlglot) introduced by:
- [x] #7752

This is a meta issue to track and organize remaining backends that need to be ported before that branch can be merged with main. Feel free to edit this list to keep it up to date.

**SQL Backends**

- [x] bigquery (#7968)
- [x] clickhouse (#7796)
- [x] druid (#8006)
- [x] duckdb (#7796)
- [x] exasol (#8032)
- [x] flink (#8268)
- [x] impala (#7993)
- [x] mssql (#7936)
- [x] mysql (#7926)
- [x] oracle (#8020)
- [x] postgres (#7877)
- [x] snowflake (#7853)
- [x] sqlite (#8154)
- [x] trino (#7871)
- [x] risingwave (#8171)

**Other Backends**

- [x] dask (#8005)
- [x] datafusion (#7846)
- [x] pandas (#7797)
- [x] polars (#7868)
- [x] pyspark (#7950)

**Comment by jcrist** [comment]
I'll start working on the `sqlite` backend now to familiarize myself with the new sqlglot code path. @cpcloud also just pinged on zulip saying he's working on the `mysql` backend. AFAIK all other backends are still available for work.

**Comment by cpcloud** [comment]
For Impala, we should be able to use the `hive` sqlglot dialect and supplement by adding rules to its `TRANSFORMS` `dict` (see the DataFusion backend for a custom dialect subclass).

**Comment by cpcloud** [comment]
I am starting on MS SQL now.

**Comment by kszucs** [comment]
Working on PySpark. Since the tests are really slow it will take some time.

**Comment by cpcloud** [comment]
I will start on BigQuery today or tomorrow, depending on how much progress I can make with mssql

**Comment by gforsyth** [comment]
I'll start on Oracle

**Comment by cpcloud** [comment]
I'm starting on the impala backend today.

**Comment by cpcloud** [comment]
I'll start on Druid today.

**Comment by lostmygithubaccount** [comment]
**Weekly Update**:
2024-01-18

This is the primary focus of the team, intending to get all backends refactored to the new relational model (building on previous refactor work) and in the process migrating from SQLAlchemy to SQLGlot. We are on track to get this done in Q1, with most backends already ported and the rest in progress (excluding Flink, RisingWave, and perhaps one more).

This week we landed the following backends in the port:

- druid
- impala
- pyspark
- BigQuery is ported and awaiting a final review.

Work is started on these backends:

- exasol
- sqlite
- oracle
- dask

(copying over last week's update on behalf of Phillip)

**Comment by cpcloud** [comment]
Work has completed on:

- exasol
- oracle

In PR:

- dask

In progress:

- sqlite

Not yet started:

- flink

**Comment by cpcloud** [comment]
Work has completed on:

* sqlite

In PR:

* dask

In progress:

* flink

Not yet started:

* risingwave

Others:

* risingwave-sans-sqlglot was merged

We're close to merging `the-epic-split` into main, and have reorganized remaining work items into `tes-required-for-merge` and `tes-required-for-release` labels to help identify blockers for the respective steps.

**Comment by cpcloud** [comment]
Work to port backends has completed on:

* dask
* risingwave

In review:

* flink


We're VERY close!

We've tagged a bunch of follow ups using the labels mentioned in the previous comment.

**Comment by lostmygithubaccount** [comment]
reopening and adding `[DONE]` in the title for keep in on the GH project 

great work everyone!

**Comment by cpcloud** [comment]
@lostmygithubaccount Why do we need to keep these open?

**Comment by lostmygithubaccount** [comment]
so they aren't removed from the GH project after 2 weeks and our roadmap is empty

**Comment by cpcloud** [comment]
We should try to come up with a way to address the specific concern without having to "hack" github issues by adding conventions.

A roadmap's issues IMO *should* be closed. It indicates that work is complete. We should also close milestones when they are reached, similar to how we close out release milestones when the release is complete.

If our roadmap is empty, and we don't want it to be empty, which seems reasonable, then we need to add more things to it.

**Comment by lostmygithubaccount** [comment]
re-closing per discussion
