### ISSUE TITLE
feat(postgres): support `asof` functionality using `lateral` join

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#7925]
Postgres could support asof join using lateral joins, see https://acyrl.github.io/posts/merge-asof-sql/

_Originally posted by @kszucs in https://github.com/ibis-project/ibis/pull/7877#discussion_r1443679524_

**Comment by jcrist** [comment]
Going to close this for now - if a user ever asks for ASOF joins in postgres we can reconsider.
