### ISSUE TITLE
feat: h3 indexing support

### ISSUE THREAD

**Issue by diehl** [ibis-project/ibis#7933]
### Describe the solution you'd like

I work with large geodataframes that I persist in DuckDB and would love to perform H3 polyfill operations in parallel for a specified geodataframe from Python via Ibis. In addition, it would be helpful to have the option of mapping from H3 cell IDs to their corresponding geometries.  

### What version of ibis are you running?

Not currently using Ibis

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
There's a third-party extension the implements all of the H3 API in DuckDB -- I think a big lift here is figuring out what the story is with third-party / unsigned extensions in DuckDB and how we install them for users (or how to make them optionally installable): https://github.com/isaacbrodsky/h3-duckdb

**Comment by diehl** [comment]
@gforsyth Some additional context on parallel processing which is important to me. I checked in with Isaac B. on the DuckDB Discord server.

![Screenshot 2024-01-08 at 12 15 06 PM](https://github.com/ibis-project/ibis/assets/349843/cfd08f89-4a4e-4edb-b970-e7e3e4f64169)

**Comment by gforsyth** [comment]
Hey @diehl -- coming back to this.  I think there's no good way for us to support the h3 plugin until it's installable via `duckdb` without disabling signature checks, etc.  Once it's more "official" we can revisit enabling support.  Thanks!

**Comment by diehl** [comment]
Hi @gforsyth - Appreciate the followup!
