### ISSUE TITLE
docs/feat: a public roadmap for the Ibis project 

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#7939]
### Please describe the issue

several users have requested a public roadmap for the Ibis project. this helps plan their adoption (e.g. awareness of a large SQLglot refactor or big new features they may be waiting to adopt) and instills confidence in the longevity of the project

we currently have a GitHub project with a roadmap view we should consider making public in a few months after we are confident in our use of it 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kszucs** [comment]
> large SQLglot refactor

For the record, the "large refactor" is about the new relational operations. SQLGlot-ifying the backends is a side effects since the backends must be rewritten and once we are there SQLGlot seems to be more appropriate than alchemy.

**Comment by lostmygithubaccount** [comment]
just noting the PR merged the roadmap blog, but didn't publish it yet -- that'll be next week after we announce 8.0
