### ISSUE TITLE
feat: support multi thread

### ISSUE THREAD

**Issue by ruiyang2015** [ibis-project/ibis#7953]
### Is your feature request related to a problem?

We have a project and using duckdb, also we multi thread to allow us to concurrently read/write to duckdb. 
we use cur = duckdb.connect().cursor() for each thread to achieve this.
but when we try to port the duckdb native to ibis.duckdb, there is no cursor object available, everything is operated on the global connection object, which is not thread safe, and also getting this error:
```
TransactionContext Error: cannot start a transaction within a transaction
```

### Describe the solution you'd like

looks like ibis is using SQLAlchemy under the hood, would like to have a way to be able start a session for each thread, so we can do thread safe operation for that session object.

### What version of ibis are you running?

7.2.0

### What backend(s) are you using, if any?

DuckDB, and will need to expand to BigQuery/Snowflake

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @ruiyang2015 👋🏻, welcome!

Can you give some more detail, ideally with some examples and comparisons of what you're doing?

- What are you doing with duckdb native that is working, that doesn't work with ibis? If you can show two representative code examples that would be most helpful.
- Can you show the application or library code that is using Ibis?
- What is the concurrency being used for? Ideally you can show any thread setup (`concurrent.futures`, `threading.Thread`, etc) and how you're managing the threads themselves.

Thanks!
