### ISSUE TITLE
docs: add example docstrings to geospatial methods

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#7959]
Now that the duckdb backend supports geospatial operations, we should be able to add example docstrings on any geo method that the duckdb backend supports.

Using the dataset (or datasets) added in #7958 may be useful here.

**Comment by ncclementi** [comment]
I wonder, where is a good place to document this examples. At the moment the only geospatial docs we have are https://ibis-project.org/reference/expression-geospatial which contains a list of all the geospatial expressions supported, but it's kind of useless, given that most of these are backend dependent and there is no clarity on which one is which. 

Is there a way we can have the duckdb-geospatial docs at the backend level? 

I think it would be great if we can have under the docs specific backend (like [here](https://ibis-project.org/backends/duckdb#ibis.backends.duckdb.Backend)), a tab that says geospatial and there render all the geospatial expresions supported for that backend.  Is this possible? I'm not sure if there is a way of grabbing the backend specific geospatial functions and somehow include them in the api template. 

https://github.com/ibis-project/ibis/blob/main/docs/backends/_templates/api.qmd

@cpcloud I see you add it the `_tenplates.api.qmd` Do you think with it's possible to somehow have backend specific geospatial docs pulled here?

**Comment by ncclementi** [comment]
At the moment blocked by: https://github.com/duckdb/duckdb_spatial/issues/236.
