### ISSUE TITLE
docs - improve search functionality

### ISSUE THREAD

**Issue by p-a-a-a-trick** [ibis-project/ibis#7995]
### Please describe the issue

I used the search tool on the website (ibis-project.org) to look for syntax/documentation on basic functionality and none of the top results were what I expected.

Attempting to find information on the sum method (or function) on any expression:
![image](https://github.com/ibis-project/ibis/assets/100629128/8ddf9685-cc1d-4fd0-8647-0f4fded4d948)

Attempting to find information on the aggregate method on a table expression:
![image](https://github.com/ibis-project/ibis/assets/100629128/826dbdb2-58d6-46ee-b0e9-366005b5e48f)

It would be helpful for new users if common operations were ranked higher on basic search results (looking up "sum" would lead you to the various sum functions/methods before the word "summary" or blog posts).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
potentially useful: https://quarto.org/docs/websites/website-search.html

also once Ibis Birdbrain is more properly done could be an interesting experiment to try search with it

**Comment by gforsyth** [comment]
@ogrisel posted these in #8086 and I wanted to not lose track of them:

So to conclude, here are some concrete recommendations:
    exact matches with Ibis public function / class names should probably always be ranked at the top;
    the result snippet should highlight the fact that it's an API exact match one or another (at least showing the function / class name in at the beginning of the snippet);
    the result snippet should ideally quote the beginning of the docstring rather than a random excerpt near the end of the docstring.
