### ISSUE TITLE
docs: interactive mode isn't persisted in some examples

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8001]
### Please describe the issue

I'm looking at https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.pivot_longer. The first `>>>` block is rendered in interactive mode. The rest are not, but should be.

This is caused by https://github.com/ibis-project/ibis/commit/502b88cb0c86d33b1bd6fdd0b35a6d19f283268b. I couldn't find the PR or other info on why that commit was motivated.

Should we go through these cases and turn on interactive mode before every example? This seems pretty boilerplatey. Perhaps better would be to add a `quartodoc: +INTERACTIVE` pragma or something to each docstring, similar to `quartodoc: +SKIP`? Not sure what the best semantics there should be.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the report. Yeah, this does look it's from 502b88c.

**Comment by cpcloud** [comment]
Nah, I think we just need to figure out what's happening with turning off interactive mode. This happens automatically as part of rendering, it's not something we need to manually alter.
