### ISSUE TITLE
bug: expressions with deferreds are `True` rather than raising

### ISSUE THREAD

**Issue by coroa** [ibis-project/ibis#8012]
### What happened?

`max(_.value, 0)` returns always 0, since `bool(0 < _.value)` returns `True`.

Instead both should make clear they are not implemented, ie. `__bool__` of `ibis.common.deferred.Deferred` should raise if it represents an expression.

Probably it should raise `ValueError: The truth value of an Ibis expression is not defined` to be consistent with `bool(df.value > 0)`.
 

### What version of ibis are you using?

7.1.0

### What backend(s) are you using, if any?

DuckDB, but not relevant

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Thanks for opening this, should be fixed by #8015.

**Comment by coroa** [comment]
Thanks for the quick turn-around!
