### ISSUE TITLE
bug: `ibis.array([ibis.literal(1), ibis.literal(2)])` returns ArrayColumn, not ArrayScalar

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8022]
### What happened?

as it says. PR incoming.

### What version of ibis are you using?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NickCrews** [comment]
Yay thank you @cpcloud and @kszucs !

**Comment by kszucs** [comment]
Thanks @NickCrews for both the report and the help!
