### ISSUE TITLE
feat: support generating a concat of all columns for ibis table

### ISSUE THREAD

**Issue by ruiyang2015** [ibis-project/ibis#8024]
### Is your feature request related to a problem?

we  use SQL like this to generate a row digest for a table:
```
SELECT
   Hash(coalesce(cast(col1) as str, "") || coalesce(cast(col2) as str, "") || coalesce(cast(col3) as str, "")) as row_hash
FROM some_table
```

it seems ibis does not have any built in function to concat all columns into one. 
would love to have this support since we want to use this ibis as a generic implement for all backend so we do not need tow tweak above query for different backend.

### Describe the solution you'd like

add a new table function to support concat all columns, 
so we can do something like this:
ibis_table.mutate(_row_hash=ibis.concat_all_columns(ibis_table.columns))

### What version of ibis are you running?

7.2.0

### What backend(s) are you using, if any?

duckdb snowflake and biguqery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
in the (potential) absence of a direct way to do this in Ibis expressions, I'd recommend using `table.sql()` to run the existing SQL string directly: https://ibis-project.org/how-to/extending/sql#table.sql

**Comment by cpcloud** [comment]
How about this?

```
In [29]: from ibis.interactive import *

In [30]: t = ibis.examples.penguins.fetch()

In [31]: t[0].concat(*(t[c].cast("string") for c in t.columns[1:]))
Out[31]:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ StringConcat()                           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ string                                   │
├──────────────────────────────────────────┤
│ AdelieTorgersen39.118.71813750male2007   │
│ AdelieTorgersen39.517.41863800female2007 │
│ AdelieTorgersen40.318.01953250female2007 │
│ AdelieTorgersen2007                      │
│ AdelieTorgersen36.719.31933450female2007 │
│ AdelieTorgersen39.320.61903650male2007   │
│ AdelieTorgersen38.917.81813625female2007 │
│ AdelieTorgersen39.219.61954675male2007   │
│ AdelieTorgersen34.118.119334752007       │
│ AdelieTorgersen42.020.219042502007       │
│ …                                        │
└──────────────────────────────────────────┘
```

**Comment by cpcloud** [comment]
Perhaps there's room for an API to make this even more succinct?

```
t[0].concat(*t.exprs[1:])
```

The new API being the `exprs` property. Very much in spitball phase.
