### ISSUE TITLE
[EPIC] Expand Flink backend support

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8063]
**Acceptance criteria**: With streaming backends introduced in Q1 2024 (#8036 and #8038), we will continue to improve these existing streaming backends and look to potentially introduce more (i.e. Spark Streaming).

More planning needed closer to the end of the quarter. 

TODOs:

- [ ]

**Comment by chloeh13q** [comment]
Update [4/26/24]

1. Array expansion - done #8511 
2. `distinct()` - pending #7556 

No update on the other tasks.

**Comment by chloeh13q** [comment]
Weekly update, 5/2/24

No update.

**Comment by chloeh13q** [comment]
Weekly update, 5/9/24

No update.

**Comment by chloeh13q** [comment]
Weekly update, 5/15/24

No update.

**Comment by chloeh13q** [comment]
Weekly update, 5/23/24

Talked about the status of this epic yesterday. Going to have some synchronous discussions in the next weeks to decide on the next steps of some stale PRs.

**Comment by chloeh13q** [comment]
Weekly update, 5/30,24

No upate.

**Comment by lostmygithubaccount** [comment]
we are no longer using epics in GitHub -- please look out for an updated Ibis roadmap blog soon!
