### ISSUE TITLE
bug: non-string Categorical from pandas crash memtable()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8066]
### What happened?

```python
import ibis
import pandas as pd

df = pd.DataFrame(
    {
        "cat_string": pd.Series(["a", "b", "c"], dtype="category"),
        "cat_int": pd.Series([1, 2, 3], dtype="category"),
    }
)
ibis.memtable(df).execute()
# ArrowTypeError: ('Expected a string or bytes dtype, got int64', 'Conversion failed for column cat_int with type category')
```

### What version of ibis are you using?

main (5998143f09add788bb569b9e3ea091240ba00a26, Jan 22, 2024)

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Thanks for opening this, this should be fixed by #8094.
