### ISSUE TITLE
docs: the search widget should probably rank matching API references higher and display less confusing result snippets

### ISSUE THREAD

**Issue by ogrisel** [ibis-project/ibis#8086]
### Please describe the issue

I have the impression that I always have a hard time using the search feature of the Ibis documentation to learn how to use Ibis' API correctly.

In this issue I tried to analyze two possible reasons why it happens.

Here are the top results for "sample":

![image](https://github.com/ibis-project/ibis/assets/89061/6862ed75-9078-4e99-8189-0136e12bbdaa)

If you scroll down to the end of the list you actually find what your are looking for:

![image](https://github.com/ibis-project/ibis/assets/89061/b7041caa-1c5d-41ca-a452-960716eeed06)

The formatting of the snippet is confusing, but at least it's matching the interesting part of the docstring (the beginning). This is not always the case:

For instance when typing "random", the top result actually matches the docstring for `ibis.random` but I find the quoted snippet in the results list really confusing:

![image](https://github.com/ibis-project/ibis/assets/89061/5b81186e-ce63-462c-b683-d4840005a800)

Indeed, it displays the title of the page ("Numeric and Boolean expressions") and then the unformatted content of the following table of the "Returns" section of the docstring (with the uninformative world "Returns" repeated twice):

```
Type | Description
-- | --
FloatingScalar | Random float value expression
```

instead of an excerpt of the actually interesting snippet of the API reference (that is the beginning of the docstring for `ibis.random`):

![image](https://github.com/ibis-project/ibis/assets/89061/057a5c86-4ea1-4ebd-ae43-21c8f425208a)

In comparison, here are the results for the same queries when using google with the `site:` filter:

- "sample site:ibis-project.org" on Google:

![image](https://github.com/ibis-project/ibis/assets/89061/684d2d87-7a0b-4b79-a670-9d58aae07058)

- "random site:ibis-project.org" on Google:

![image](https://github.com/ibis-project/ibis/assets/89061/48c97d2e-5b97-4534-ad86-f91a956eb5c7)

So to conclude, here are some concrete recommendations:

- exact matches with Ibis public function / class names should probably always be ranked at the top;
- the result snippet should highlight the fact that it's an API exact match one or another (at least showing the function / class name in at the beginning of the snippet);
- the result snippet should ideally quote the beginning of the docstring rather than a random excerpt near the end of the docstring.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
xref: https://github.com/ibis-project/ibis/issues/7995

**Comment by gforsyth** [comment]
I'm going to close this in favor of #7995 but we are tracking this and I'll include your concrete recommendations in that issue as a comment.  Thanks!
