### ISSUE TITLE
docs: the search tool bar becomes irresponcive when editing a long query

### ISSUE THREAD

**Issue by ogrisel** [ibis-project/ibis#8087]
### Please describe the issue

Steps to reproduce:

- click on the search icon on the https://ibis-project.org website;
- type a query with 5 to 10 search terms;
- try to delete the last word with backspace;
- observe that editing becomes quickly unresponsive.

Arguably, 10 search terms in a query is unusual, but it becomes slow with much fewer terms (2 or 3) on Firefox instead of Chrome for instance.

The search should probably be performed in non blocking / async way with a slight delay (e.g. 100 ms) after a key press when to avoid that typing quickly 20 characters triggers 20 search queries in a row with only the last query results matching what has been typed in the search field.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ncclementi** [comment]
This PR was merged upstream in quarto, https://github.com/quarto-dev/quarto-cli/pull/8570 . It should provide a better search experience.

**Comment by lostmygithubaccount** [comment]
going to close this given it's fixed upstream and will be fixed in the website when Quarto is updated
