### ISSUE TITLE
docs: Ibis for PySpark users tutorial

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#8090]
### Please describe the issue

It would be nice if we had an Ibis tutorial for users familiar with the PySpark DataFrame API. This could be similar in structure to the Ibis tutorials for pandas users and dplyr users.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
would be good to do if anyone's interested -- closing as not planned for now
