### ISSUE TITLE
bug: `ibis.examples.___.fetch()` can fail if Google Cloud SDK is installed

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#8093]
### What happened?

When I have the [Google Cloud SDK](https://cloud.google.com/sdk/) installed and configured, fetching example data from GCS fails with
```
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
```
This error goes away if I [uninstall the Google Cloud SDK](https://cloud.google.com/sdk/docs/uninstall-cloud-sdk).

Can we configure the example data fetch function to always send the GCS request anonymously, ignoring any local Google Cloud SDK configuration?

### What version of ibis are you using?

8.0.0.dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Sounds like a misconfigured client. We use gcs and other gcp services without having any issues like this. I'm not particularly inclined to change it without more information about why it's failing for you.

**Comment by ianmcook** [comment]
Fair enough, but would there be any reason _not_ to set `token='anon'` when connecting to GCS to fetch example data? https://gcsfs.readthedocs.io/en/latest/api.html#gcsfs.core.GCSFileSystem

**Comment by ianmcook** [comment]
Tested and confirmed that #8099 fixes my issue. Thanks!
