### ISSUE TITLE
bug: Table.filter(bool) crashes

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8103]
### What happened?

It can't handle python scalars:

```python
import ibis

t = ibis.examples.penguins.fetch()
t.filter(True)
```

```
SignatureValidationError: Selection(<ibis.expr.operations.relations.DatabaseTable object at 0x28daee860>, selections=[], predicates=[<ibis.expr.operations.generic.TableColumn object at 0x287332e80>]) has failed due to the following errors:
  `predicates`: [<ibis.expr.operations.generic.TableColumn object at 0x287332e80>] is not a tuple of coercibles to a Value[Boolean, DataShape]

Expected signature: Selection(table: Relation, selections: tuple[Union[Relation, Value], ...], predicates: tuple[Value[Boolean, DataShape], ...] = (), sort_keys: tuple[SortKey, ...] = ())
```

### What version of ibis are you using?

main, jan 25th 2024, 8e5c0af0c6cd7f43ee57b465da2271d311acdf9a

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
hi Nick! what are you expecting to happen in this case? the table is just returned?

**Comment by jcrist** [comment]
I agree this should be possible. I've pushed a fix for this to `the-epic-split` branch, which we're hoping should be released _after_ the upcoming 8.0 release. For now you can do

```python
import ibis

t = ibis.examples.penguins.fetch()
t.filter(ibis.literal(True))  # <- manually coerce to a literal
```

**Comment by NickCrews** [comment]
Yes @lostmygithubaccount , exactly.

Thanks @jcrist !

**Comment by cpcloud** [comment]
Fixed in `the-epic-split`
