### ISSUE TITLE
feat(flink): implement UDF support for the backend

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis#8108]
### Is your feature request related to a problem?

* I want to be able to execute the same UDFs that I can against other backends against the Flink backend.
* I want to be able to define custom aggregations.
* I want to use external libraries in UDFs.
* I want to load external resources (e.g. models) in UDFs.

##### Definition

Ibis supports four scalar backend-agnostic UDF definitions. For the full documentation, see https://ibis-project.org/reference/scalar-udfs.

* `builtin`:  is built in to the backend
* `pandas`: accepts pandas Series as inputs
* `pyarrow`: accepts PyArrow Arrays as inputs
* `python`: accepts Python scalars as inputs

Ibis also supports built-in aggregate UDFs (https://ibis-project.org/how-to/extending/builtin.html#aggregate-functions), but doesn’t expose an API for defining custom aggregate functions.

##### Registration

* Scalar UDFs are registered in pre-execute hooks: https://github.com/ibis-project/ibis/blob/7.2.0/ibis/backends/base/__init__.py#L1009
* Some backends also register vectorized UDFs in the _register_udfs method: https://github.com/ibis-project/ibis/blob/7.2.0/ibis/backends/datafusion/__init__.py#L146-L148
* Direct execution backends (e.g. [pandas](https://github.com/ibis-project/ibis/blob/7.2.0/ibis/backends/pandas/udf.py), [dask](https://github.com/ibis-project/ibis/blob/7.2.0/ibis/backends/dask/udf.py), polars) use other methods
* Some backends (e.g. [sqlite](https://github.com/ibis-project/ibis/blob/7.2.0/ibis/backends/sqlite/udf.py#L31-L53)) register custom UDFs with the connection

##### Translation

https://github.com/ibis-project/ibis/blob/7.2.0/ibis/backends/base/sql/__init__.py#L283-L294

#### UDF support in the PyFlink Table API

The PyFlink Table API supports:

* [Scalar functions](https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/dev/python/table/udfs/python_udfs/#scalar-functions): takes zero, one, or multiple scalar values as input parameters and returns a single value
* [Table functions](https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/dev/python/table/udfs/python_udfs/#table-functions): takes zero, one, or multiple scalar values as input parameters and returns an arbitrary number of rows consisting of one or more fields
* [Aggregate functions](https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/dev/python/table/udfs/python_udfs/#aggregate-functions): maps scalar values of multiple rows to a new scalar value
* [Table aggregate functions](https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/dev/python/table/udfs/python_udfs/#table-aggregate-functions): maps scalar values of multiple rows to an arbitrary number of rows consisting of one or more fields
* [Vectorized scalar functions](https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/dev/python/table/udfs/vectorized_python_udfs/#vectorized-scalar-functions): accepts pandas Series as inputs and returns pandas Series of the same length as outputs
* [Vectorized aggregate functions](https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/dev/python/table/udfs/vectorized_python_udfs/#vectorized-aggregate-functions): takes one or more pandas Series as inputs and returns one scalar value as the output

Other deployment considerations (e.g. using external libraries and resources): https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/dev/python/table/udfs/overview/

#### Mapping the Ibis and PyFlink Table APIs

Ibis | PyFlink Table API
-- | --
`ibis.udf.scalar.builtin` | Call an already-registered UDF (or a function not exposed by the Ibis API)
`ibis.udf.scalar.pandas` (`ops.ElementWiseVectorizedUDF`) | Register and call a vectorized scalar function
`ibis.udf.scalar.pandas` (`ops.ReductionVectorizedUDF`) | Register and call a vectorized aggregate function
`ibis.udf.scalar.pyarrow` | Not supported
`ibis.udf.scalar.python` | Call and register a scalar function
Not supported[^_1] | Table functions
`ibis.udf.agg.builtin` | Call an already-registered UDF (or a function not exposed by the Ibis API)
Custom aggregation functions are not currently supported | Aggregate functions
Custom aggregation functions are not currently supported | Table aggregate functions

#### Implementation

In order of ease:

* Built-in UDF support should be straightforward, if it doesn’t already work, since it doesn’t require definition/registration.
* Scalar Python and pandas UDFs will require registration, but the DataFusion backend looks like a reasonable example of how to do that.[^_2]
* Custom aggregation will require Ibis API design, and the resulting syntax should be useful across multiple backends. Is this already part of the upcoming milestone around UDFs?

[^_1]: I'm not 100% confident about this.
[^_2]: Question for somebody with more experience implementing Ibis UDFs: Is it a good example, or does the Postgres backend provide a better template?

### What version of ibis are you running?

dev

### What backend(s) are you using, if any?

Flink

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
> Scalar Python and pandas UDFs will require registration, but the DataFusion backend looks like a reasonable example of how to do that.[2](https://github.com/ibis-project/ibis/issues/8108#user-content-fn-_2-e7689338d3b3296e28705ea2f0879135)

`datafusion` or `duckdb` are both reasonable references to use here

> I'm not 100% confident about this. [referring to lack of table function support]

This is correct, these aren't currently supported

> Custom aggregation will require Ibis API design, and the resulting syntax should be useful across multiple backends. Is this already part of the upcoming milestone around UDFs?

We have an API for calling "builtin" aggregation functions via `ibis.udf.agg.builtin`, but no standard way of defining custom Python aggregation functions. There's a legacy version of this in the pandas API, but it's not something we want to support going forward. The issue here is that for backends that do support defining aggregates in python, they all want them defined in a different way, so uniting them across an interface may be tricky. We don't currently have plans to work more on python defined aggregation udfs, my preference would be to leave this unimplemented in flink for now and focus only on the existing interfaces.

**Comment by deepyaman** [comment]
> > Scalar Python and pandas UDFs will require registration, but the DataFusion backend looks like a reasonable example of how to do that.[2](https://github.com/ibis-project/ibis/issues/8108#user-content-fn-_2-e7689338d3b3296e28705ea2f0879135)
> 
> `datafusion` or `duckdb` are both reasonable references to use here
> 
> > I'm not 100% confident about this. [referring to lack of table function support]
> 
> This is correct, these aren't currently supported
> 
> > Custom aggregation will require Ibis API design, and the resulting syntax should be useful across multiple backends. Is this already part of the upcoming milestone around UDFs?
> 
> We have an API for calling "builtin" aggregation functions via `ibis.udf.agg.builtin`, but no standard way of defining custom Python aggregation functions. There's a legacy version of this in the pandas API, but it's not something we want to support going forward. The issue here is that for backends that do support defining aggregates in python, they all want them defined in a different way, so uniting them across an interface may be tricky. We don't currently have plans to work more on python defined aggregation udfs, my preference would be to leave this unimplemented in flink for now and focus only on the existing interfaces.

All makes sense! On the last point, yes--Flink's custom aggregate UDF definition was also very particular.

I will probably look into the scalar Python/pandas/built-in UDFs next week.
