### ISSUE TITLE
hdfs_connect does not support discovery of active namenode through configs

### ISSUE THREAD

**Issue by lordjc** [ibis-project/ibis#811]
It looks like in order to connect to hdfs you must know exactly which namenode is active.
Have we thought about referencing hdfs-site.xml for active namenode discovery through the logical name?

> > > conn = ibis.hdfs_connect(host='nameservice1',port=50470,protocol='webhdfs',auth_mechanism='GSSAPI',verify=False)
> > > conn.ls("/user/cops")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/anaconda/lib/python2.7/site-packages/ibis/filesystems.py", line 286, in ls
> > >     return self.client.list(hdfs_path, status=status)
> > >   File "/usr/lib/anaconda/lib/python2.7/site-packages/hdfs/client.py", line 887, in list
> > >     statuses = self._list_status(hdfs_path).json()['FileStatuses']['FileStatus']
> > >   File "/usr/lib/anaconda/lib/python2.7/site-packages/hdfs/client.py", line 90, in api_handler
> > >     *_self.kwargs
> > >   File "/usr/lib/anaconda/lib/python2.7/site-packages/hdfs/ext/kerberos.py", line 98, in _request
> > >     return super(KerberosClient, self)._request(method, url, *_kwargs)
> > >   File "/usr/lib/anaconda/lib/python2.7/site-packages/hdfs/client.py", line 179, in _request
> > >     *_kwargs
> > >   File "/usr/lib/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
> > >     resp = self.send(prep, *_send_kwargs)
> > >   File "/usr/lib/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
> > >     r = adapter.send(request, **kwargs)
> > >   File "/usr/lib/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
> > >     raise ConnectionError(e, request=request)
> > > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nameservice1', port=50470): Max retries exceeded with url: /webhdfs/v1/user/cops?op=LISTSTATUS (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb9c6d76290>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by wesm** [comment]
I would be happy to accept a patch for this if there are some accessible solutions. I have also been looking at using libhdfs (to go through JNI) to talk to HDFS rather than WebHDFS, so that is another option.

**Comment by napjon** [comment]
For me, I would connect to 1 namenode, test the hdfs status using `hdfs.status('\')`. Catch HDFSError and try to connect with other namenode. Always works for me.

**Comment by schaffino** [comment]
Another option is to use jmx rest query to get the active NN

something along the lines of

```python
['http://server2:50070','http://server1:50070']
for nn in nn_list:
    r = requests.get(nn+'/jmx?qry=Hadoop:service=NameNode,name=NameNodeStatus')
    if r.json()['beans'][0]['State'] == 'active':
        break
else:
    raise RuntimeError("No active namenode found. Cannot connect to hdfs.")
```
