### ISSUE TITLE
pip install ibis-framework[kerberos] build problem with Anaconda 4.0

### ISSUE THREAD

**Issue by Tagar** [ibis-project/ibis#812]
`$ sudo pip install ibis-framework[kerberos]`

>   building 'kerberos' extension
>   creating build
>   creating build/temp.linux-x86_64-2.7
>   creating build/temp.linux-x86_64-2.7/src
>   gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/cloudera/parcels/Anaconda/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o -DGSSAPI_EXT
>   gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/cloudera/parcels/Anaconda/include/python2.7 -c src/kerberosbasic.c -o build/temp.linux-x86_64-2.7/src/kerberosbasic.o -DGSSAPI_EXT
>   gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/cloudera/parcels/Anaconda/include/python2.7 -c src/kerberosgss.c -o build/temp.linux-x86_64-2.7/src/kerberosgss.o -DGSSAPI_EXT
>   gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/cloudera/parcels/Anaconda/include/python2.7 -c src/kerberospw.c -o build/temp.linux-x86_64-2.7/src/kerberospw.o -DGSSAPI_EXT
>   gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/cloudera/parcels/Anaconda/include/python2.7 -c src/base64.c -o build/temp.linux-x86_64-2.7/src/base64.o -DGSSAPI_EXT
>   creating build/lib.linux-x86_64-2.7
>   gcc -pthread -shared -L/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib -Wl,-rpath=/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib,--no-as-needed build/temp.linux-x86_64-2.7/src/kerberos.o build/temp.linux-x86_64-2.7/src/kerberosbasic.o build/temp.linux-x86_64-2.7/src/kerberosgss.o build/temp.linux-x86_64-2.7/src/kerberospw.o build/temp.linux-x86_64-2.7/src/base64.o -L/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/kerberos.so -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err
>   /usr/bin/ld: cannot find -lpython2.7
>   collect2: ld returned 1 exit status
>   error: command 'gcc' failed with exit status 1

Any thoughts?

```
$ env | grep PY
PYTHONHOME=/opt/cloudera/parcels/Anaconda

```

**Comment by Tagar** [comment]
Explicit 
`export LD_LIBRARY_PATH=/opt/cloudera/parcels/Anaconda/lib`

does not help.. 

I noticed Anaconda only has dynamic libraries:
```
$ pwd
/opt/cloudera/parcels/Anaconda/lib
$ ll | grep python
lrwxrwxrwx  1 root root       19 Apr  8 09:48 libpython2.7.so -> libpython2.7.so.1.0
-rwxr-xr-x  2 root root  6590780 Dec  6 17:11 libpython2.7.so.1.0
drwxr-xr-x 26 root root    20480 Apr 14 10:15 python2.7

```

Does Ibis-framework need static libpython2.7.a to build?

**Comment by Tagar** [comment]
Also tried adding /opt/cloudera/parcels/Anaconda/lib/
into a new anaconda.conf file in ld.so.conf.d
but build still fails with the same error after ldconfig shows python2.7 lib is cached.

>     creating build/lib.linux-x86_64-2.7
>     gcc -pthread -shared -L/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib -Wl,-rpath=/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib,--no-as-needed build/temp.linux-x86_64-2.7/src/kerberos.o build/temp.linux-x86_64-2.7/src/kerberosbasic.o build/temp.linux-x86_64-2.7/src/kerberosgss.o build/temp.linux-x86_64-2.7/src/kerberospw.o build/temp.linux-x86_64-2.7/src/base64.o -L/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/kerberos.so -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err
>     /usr/bin/ld: cannot find -lpython2.7
>     collect2: ld returned 1 exit status
>     error: command 'gcc' failed with exit status 1
>

**Comment by wesm** [comment]
@mariusvniekerk is it possible the conda-forge builds on anaconda.org will work for this (do they include the Kerberos dependencies)? https://anaconda.org/conda-forge/ibis-framework

**Comment by Tagar** [comment]
I have the same problem with some other packages under Anaconda 4.0:

`$ sudo pip install thrift_sasl`

gives 
>     building 'sasl.saslwrapper' extension
>     creating build/temp.linux-x86_64-2.7
>     creating build/temp.linux-x86_64-2.7/sasl
>     gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isasl -I/opt/cloudera/parcels/Anaconda/include/python2.7 -c sasl/saslwrapper.cpp -o build/temp.linux-x86_64-2.7/sasl/saslwrapper.o
>     cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
>     In file included from sasl/saslwrapper.cpp:254:
>     sasl/saslwrapper.h: In member function ‘void saslwrapper::ClientImpl::interact(sasl_interact_t*)’:
>     sasl/saslwrapper.h:437: warning: unused variable ‘input’
>     g++ -pthread -shared -L/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib -Wl,-rpath=/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib,--no-as-needed build/temp.linux-x86_64-2.7/sasl/saslwrapper.o -L/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib -lsasl2 -lpython2.7 -o build/lib.linux-x86_64-2.7/sasl/saslwrapper.so
>     /usr/bin/ld: cannot find -lpython2.7
>     collect2: ld returned 1 exit status
>     error: command 'g++' failed with exit status 1

the same error.

**Comment by Tagar** [comment]
I noticed in my first post here 15 days ago for pip install ibis-framework[kerberos] 
and the one today for pip install thrift_sasl

In both cases g++ called by pip was trying to use "/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib"

> -L/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib

notice "tmpQcQ0Zo" is the same.. not sure if this is Anaconda's or pip's problem.

Got fixed by creating a symlink:

> ln -s /opt/cloudera/parcels/Anaconda-4.0.0/lib/ /tmp/tmpQcQ0Zo/Anaconda-4.0.0/

Now both ibis-framework[kerberos] and thrift_sasl were installed successfully.

**Comment by wesm** [comment]
Sounds like an Anaconda problem, want to raise the issue with them about it?

**Comment by Tagar** [comment]
https://github.com/ContinuumIO/anaconda-issues/issues/772

**Comment by mariusvniekerk** [comment]
I haven't tried the kerberos builds on conda -Forge 

Guess it's worth a shot.  Do you know what is involved in compiling that on Windows?  Or do we just not target windows initially

**Comment by wesm** [comment]
I don't know, but it would be nice to get it to work
