### ISSUE TITLE
Link to conda packages build by conda-forge?

### ISSUE THREAD

**Issue by mariusvniekerk** [ibis-project/ibis#813]
I've set up some conda-forge feedstocks for ibis and its dependencies.  

This provides binary builds for all os platforms automatically via a bunch of CI tools.

https://github.com/conda-forge/ibis-framework-feedstock
https://github.com/conda-forge/impyla-feedstock

If someone wants to assist in being maintainers on these recipes i can add them in.

**Comment by wesm** [comment]
Sure, can you make a patch to the docs or README about it? 

What's the rationale for having a repo for every project? Versus the homebrew approach: https://github.com/Homebrew/homebrew-core

**Comment by mariusvniekerk** [comment]
Conda Forge splits it out automatically.  So that's mostly why.

I haven't built kerberos modules for it yet since I don't quite know how to build libsasl for Windows....

I'll send a PR amending the readme

**Comment by cpcloud** [comment]
We link to these in the README now.
