### ISSUE TITLE
feat:  Could the ClickHouse backend support overwriting a specific partition, or dropping a partition of a certain partition?

### ISSUE THREAD

**Issue by stereoF** [ibis-project/ibis#8131]
### Describe the solution you'd like

Add this operation in a dataframe or connection.

### What version of ibis are you running?

'7.1.0'

### What backend(s) are you using, if any?

clickhouse

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @stereoF, thanks for raising this!  We're thinking about ways to add better support for backend-specific DDL operations like this, but we're unlikely to add a single backend-specific method to a connection at the moment.  You can definitely accomplish these things using `raw_sql` right now.
