### ISSUE TITLE
Difficulty in connecting to Impala in Kerberos environment

### ISSUE THREAD

**Issue by kskrishnasangeeth** [ibis-project/ibis#814]
I am trying to connect to Impala from a CDH 5.5 environment which has implemented kerberos security.
I am referring to the [API docs](http://docs.ibis-project.org/generated/ibis.impala.api.connect.html#ibis.impala.api.connect) for connecting. 

My connection string looks like this 

`con = ibis.impala.connect(host=host_name, port=port_num, database=db_name,use_ssl=True,auth_mechanism='GSSAPI', kerberos_service_name=principal)`

I am getting the below stack trace while doing this.

>  Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.6/site-packages/ibis/impala/api.py", line 97, in connect
>     con = ImpalaConnection(pool_size=pool_size, *_params)
>   File "/usr/lib/python2.6/site-packages/ibis/impala/client.py", line 89, in **init**
>     self.ping()
>   File "/usr/lib/python2.6/site-packages/ibis/impala/client.py", line 176, in ping
>     self._new_cursor()
>   File "/usr/lib/python2.6/site-packages/ibis/impala/client.py", line 161, in _new_cursor
>     con = impyla.connect(database=self.database, *_params)
>   File "/usr/lib/python2.6/site-packages/impala/dbapi.py", line 147, in connect
>     auth_mechanism=auth_mechanism)
>   File "/usr/lib/python2.6/site-packages/impala/hiveserver2.py", line 644, in connect
>     transport.open()
>   File "/usr/lib/python2.6/site-packages/thrift_sasl-0.2.0-py2.6.egg/thrift_sasl/**init**.py", line 61, in open
>     self._trans.open()
>   File "/usr/lib64/python2.6/site-packages/thrift/transport/TSSLSocket.py", line 101, in open
>     ciphers=self.ciphers)
> TypeError: wrap_socket() got an unexpected keyword argument 'ciphers'

I have installed ibis using 

`pip install ibis-framework[kerberos]`

**Comment by wesm** [comment]
What version of Thrift-Python are you using? There are some fixes for Python 2.6 and SSL in Thrift but you may not have them with your version:

https://github.com/apache/thrift/blob/master/lib/py/src/transport/TSSLSocket.py#L199

**Comment by kskrishnasangeeth** [comment]
I am using Python 2.6.6 . 

Initially i got an error `ImportError : No module named thrift_sasl`

So , I had pip-installed `thrift_sasl` 

I am not sure what is the version that got installed. I can see from the snippet that there is some change in code. Will upgrading the module help me in getting this code.

Also I would have imagined that `thrift_sasl` was installed by default by being a requirement for ibis. Is that really the case or am i missing something here.

**Comment by wesm** [comment]
I recommend that you upgrade to the latest version of Thrift:

https://pypi.python.org/pypi/thrift/0.9.3

`pip install --upgrade thrift`

For Kerberos support you must also install the `sasl` and `thrift_sasl` packages as described here: https://github.com/cloudera/impyla

**Comment by jlsepulveda** [comment]
You need to install kerberos package. It had the same issues 

https://github.com/thobbs/pure-sasl/issues/20

**Comment by cpcloud** [comment]
@kskrishnasangeeth Python 2.6 is no longer supported. Can you try with a later version of Python?

@jlsepulveda Marking for 0.11.1, we can certainly notifying users using GSSAPI auth that they don't have the required libraries to do it when they try to connect.
