### ISSUE TITLE
Add instructions for using Ibis with HDFS clusters with HA namenode 

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#815]

**Comment by cpcloud** [comment]
HA == High Availability?

**Comment by wesm** [comment]
Yep. Together with this would be good to document HA in `pyarrow.HdfsClient`

**Comment by tyyzqmf** [comment]
refer to:
https://www.cloudera.com/documentation/enterprise/5-8-x/topics/cdh_hag_hdfs_ha_enabling.html#concept_p3p_55p_bp__section_d1v_r25_mj
