### ISSUE TITLE
feat: support PyArrow tables as input to Postgres `insert`

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#8155]
### Describe the solution you'd like

The Ibis Postgres backend supports passing PyArrow Tables to the `create_table` method, but not to the `insert` method. Is it possible to add support for this?

### What version of ibis are you running?

8.0.0.dev

### What backend(s) are you using, if any?

PostgreSQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ianmcook** [comment]
This is related to https://github.com/ibis-project/ibis/issues/8133

**Comment by cpcloud** [comment]
@ianmcook Do you mind if we consolidate on #8133?
