### ISSUE TITLE
feat: UX: strip eg `duckdb://` from URI when connecting to specific backend

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8167]
### Is your feature request related to a problem?

```python
import ibis

# includes duckdb:/ as part of the path
ibis.duckdb.connect("duckdb://test.duckdb").tables
# works
ibis.connect("duckdb://test.duckdb").tables
```

### Describe the solution you'd like

It would be great if the specific backends
1. look for a pattern like "^([a-zA-Z]+)://"
1. strips it
1. not sure: if it doesn't match, eg `ibis.duckdb.connect("postgressql://test.pg")`, then error? warn? silently strip it and ignore?

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue.

What's the use case for using multiple ways to connect in the same application or library?

**Comment by cpcloud** [comment]
The current approach, while less flexible is also easier to understand:

- `ibis.connect`: URLs
- `ibis.<backend>.connect`: dbapi kwargs

**Comment by cpcloud** [comment]
I think the handling of an arbitrary URL in the backend connect APIs alongside the current dbapi kwargs pattern is fraught with complexity.

There are a bunch of hacky decisions that would have to be made:

1. Is the first argument to the `do_connect` implementation always a URL, `kwargs`, something else?
2. What do we call the kwarg? If we call it `url` and that's a valid dbapi parameter, what should we do?
3. Users now have to be aware of mixed URLs and kwargs in a single interface. `ibis.connect` **does** accept kwargs, but it requires a URL (or `Path`) as its first argument. Even handling both those cases is messy.
