### ISSUE TITLE
docs: document Date.epoch_seconds() and others from mixin classes

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8179]
### Please describe the issue

any thing defined within
- _DateComponentMixin
- _TimeComponentMixin

don't appear in the docs for their subclasses

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ncclementi** [comment]
I was playing with this a bit trying to get the inherited methods to display. `quartodocs` has an option 
`include_inherited: true` but unfortunately this will also include all the inherited methods from `Value` and `Expr`. 

As is, it doesn't seem to be a way of including the methods defined inside `_DateComponentMixin` and `_TimeComponentMixin`. That being said, I noticed that 

- `_DateComponentMixin` is only used in  places:

https://github.com/ibis-project/ibis/blob/6f32374fd1add436635c2ea5a6da86ac127c5182/ibis/expr/types/temporal.py#L319
and 

https://github.com/ibis-project/ibis/blob/6f32374fd1add436635c2ea5a6da86ac127c5182/ibis/expr/types/temporal.py#L480

- `_TimeComponentMixin` is only used in  places:

https://github.com/ibis-project/ibis/blob/6f32374fd1add436635c2ea5a6da86ac127c5182/ibis/expr/types/temporal.py#L149

and

https://github.com/ibis-project/ibis/blob/6f32374fd1add436635c2ea5a6da86ac127c5182/ibis/expr/types/temporal.py#L480

One solution would be to duplicate the code, and avoid using the private classes. Thoughts?

**Comment by gforsyth** [comment]
I don't think we should duplicate the code, but maybe we can use a combination of `include_inherited` and then explicitly listing the members in the `quarto.yml` file.  let me take a quick look to see if that's a thing.

**Comment by gforsyth** [comment]
yeah, I think this will work.  I'll throw up a RP

**Comment by NickCrews** [comment]
Yeah I'd pretty much always prefer duplicates in the docs over dupes in code.
