### ISSUE TITLE
feat: UX: Support deferreds in addition to lambdas in Array.map, Array.filter

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8180]
### Is your feature request related to a problem?

these lambdas are often really simple, and it would be shorter and cleaner to use Deferreds

### Describe the solution you'd like

`gmails = emails.filter(_.contains("@gmail.com"))`

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Can you give this a try on `the-epic-split`? I believe we have addressed this there.

**Comment by cpcloud** [comment]
Oh, nevermind, this is slightly different than what I originally thought.

**Comment by kszucs** [comment]
I like this feature request. The implementation should be about checking for `Deferred` in `ArrayValue.filter()` method, and the input is indeed a deferred then wrap it with a function calling `.resolve()`.

Implementation suggestion:

```py
if isinstance(predicate, Deferred):
    body = predicate.resolve(parameter.to_expr())
else:
    body = predicate(parameter.to_expr())
```
