### ISSUE TITLE
perf(dask): avoid calling compute for `ops.Covariance`, `ops.ArgMin` and `ops.ArgMax`

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#8187]
> dask has built in covariance and correlation methods, why are they not sufficient here/why do we need to compute?
>
> IMO anything that needs to compute like this shouldn't warn, we should just not support it unless we can do it cleanly.

_Originally posted by @jcrist in https://github.com/ibis-project/ibis/pull/8005#discussion_r1473095470_

**Comment by jcrist** [comment]
See my comments [here](https://github.com/ibis-project/ibis/pull/8005#pullrequestreview-1854096466) and [here](https://github.com/ibis-project/ibis/pull/8005#issuecomment-1922235967). I'd strongly argue that we should either fix this before releasing, or drop support for these operations until they can be properly handled. IMO anywhere where we're explicitly calling `.compute()` outside of returning results to the end user is a bug in the dask backend.

**Comment by gforsyth** [comment]
@jcrist you mean before the 9.0 release, yes?

**Comment by jcrist** [comment]
Yes.

**Comment by cpcloud** [comment]
Going to move this off the 9.0 milestone. I think Dask performance isn't a blocker.
