### ISSUE TITLE
perf(dask): use global functions instead of lambdas where possible

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#8191]
When possible, it's better to use top-level functions instead of lambdas for cheaper pickling of tasks. This is probably negligible here, but it's good to keep in mind.

_Originally posted by @jcrist in https://github.com/ibis-project/ibis/pull/8005#discussion_r1473084588_

**Comment by cpcloud** [comment]
I think dask performance is out of scope for now.
