### ISSUE TITLE
bug: `ibis.to_sql` submits query to snowflake backend

### ISSUE THREAD

**Issue by dlovell** [ibis-project/ibis#8210]
### What happened?

when a snowflake backend expr has `ibis.to_sql` invoked on it, it makes a query and must wait for the result to come back

this seems like a bug because when a snowflake backend expr is `repr`ed, it makes no query and returns quickly

### What version of ibis are you using?

7.2.0

### What backend(s) are you using, if any?

snowflake

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Fixed in #8212, will be released in 9.0.0
