### ISSUE TITLE
docs(flink): update conda-based installation guide

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis#8228]
### Please describe the issue

Apache Flink is available on conda, so `ibis-flink` will be made available with the v8 release. We need to update the installation page to reflect that this is no longer infeasible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
xref https://github.com/conda-forge/ibis-framework-feedstock/pull/90
