### ISSUE TITLE
docs: blog on why DuckDB is the default backend

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8230]
### Please describe the issue

I think this would make a great blog -- the story behind why DuckDB became the default backend and why it still is today. Can setup motivation for deviations from pandas, composability (providing a Python interface for a SQL-only embeddable query engine), etc.

I don't think I'm the right person to write this but happy to help

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ncclementi** [comment]
Here @cpcloud explains it in few sentences https://www.youtube.com/watch?v=ARNonaNDfqM&t=91s, maybe we can expand on that.
