### ISSUE TITLE
feat(table): add namespace kwarg to ibis.table

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#8253]
A user asked about how to specify a table namespace when creating an unbound table.

The `UnboundTable` op does accept a namespace argument, but we don't expose that option in `ibis/expr/api.py::table`.

We will run afoul of the dual-definition of `schema` here, but if the user has to first construct the namespace object, at least that will be slightly separated.  

Still not a good solution, really, to the schema/schema issue, but I don't know what is, short of breaking all ibis code.

**Comment by cpcloud** [comment]
Break everything, and cut over to version 100?
