### ISSUE TITLE
bug: can't preview table containing UUIDs

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8261]
### What happened?

```python
import ibis
ibis.options.interactive = True

t = ibis.memtable(
    {
        "x": [1, 2, 3],
    }
)
con = ibis.duckdb.connect()
t = con.create_table("t", t, overwrite=True)
t = t.sql("SELECT *, uuid() as id FROM t")
t
```
After the .sql() call, there is to interactive preview showing up. If I remove the .sql() line, it does show up

<img width="421" alt="image" src="https://github.com/ibis-project/ibis/assets/10820686/26d952b9-97ef-4ae2-a4f9-f3019f7b4e85">

<img width="399" alt="image" src="https://github.com/ibis-project/ibis/assets/10820686/d41701b1-6bff-4a20-ae9b-57f54ff3328a">

### What version of ibis are you using?

8.0.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue. I suspect we're not handling the UUID type in formatting.

**Comment by NickCrews** [comment]
oh, that is totally all it it. changing the sql to "SELECT *, 5 as id FROM t" makes the preview show up

**Comment by NickCrews** [comment]
ah, it is because arrow doesn't support uuids. So in `to_rich_table()` when we execute the expression to_pyarrow, that fails.

**Comment by cpcloud** [comment]
Right, I think a `format_values` overload for the UUID dtype might do the trick.

**Comment by NickCrews** [comment]
changing [this line](https://github.com/ibis-project/ibis/blob/03acbd10ab55e6cdc9759682eafb79f13c4b4950/ibis/expr/types/pretty.py#L265)  to

```python
    head = table.limit(nrows + 1)
    # pyarrow can't handle UUID types, so we need to convert them to strings for now
    head = head.mutate(s.across(s.of_type("uuid"), lambda x: x.cast("string")))
    result = head.to_pyarrow()
```

makes it work

**Comment by cpcloud** [comment]
Hm, actually we _do_ have a UUID type. This is not an issue in PyArrow, it's an ibis issue.

**Comment by cpcloud** [comment]
@NickCrews Neither your solution nor mucking around in pyarrow is the right solution here 😅

**Comment by NickCrews** [comment]
haha love it when those are the options :)
