### ISSUE TITLE
feat: don't shadow builtin functions in python, pyrarrow, pandas UDFs

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8263]
### Is your feature request related to a problem?

If I define a UDF like

```python
from ibis.expr import datatypes as dt
import uuid as pyuuid

@ibis.udf.scalar.python
def uuid() -> dt.uuid:
    return pyuuid.uuid4()
```

then this creates a UDF in the backend called "uuid", which shadows the builtin duckdb function uuid(). Then if I do `table.sql("select uuid(), ...")` then I get my UDF, not the builtin.

### Describe the solution you'd like

When creating UDFs in the backend, we are free to create them under any name we want. so why not create them under some unique name like `__ibis_udf_0` to guarantee we don't get collisions? On the python side of course you still access it from the nice ergonomic name you provided. This would be a change for the python, pyarrow, and pandas UDFs, and we would remove the `name` param from the UDF creation signature. The name of the function inside the backend seems like it should be an implementation detail anyways, users shouldn't care or be able to see it. They only need to be able to set this for `builtin` UDFs. This does mean that the different UDF implementations will have different signatures, but I think that is worth it.

### What version of ibis are you running?

8.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Explicitly noting here that you _can_ pass the `name` arg to the decorator to change the name yourself.

```python
from ibis.expr import datatypes as dt
import uuid as pyuuid

@ibis.udf.scalar.python(name="_ibis_uuid")
def uuid() -> dt.uuid:
    return pyuuid.uuid4()
```

You could even wrap this up in your own decorator implementation that auto-generates unique names for you, giving you the UX you're asking for.

IMO consistency and clarity is more important here than the risk of trampling a builtin name.

- For `ibis.udf.scalar.builtin`, the whole point is exposing a builtin function by name. We'd want the SQL name to match the function name in most cases, having it be different for the other udf types may be surprising to a user.
- Ibis has both a dataframe and SQL api. There are real reasons why a user may want to register a udf using ibis but then call it from `.sql`. Clarity and consistency of the names would matter here as well.
- In general, I think the risk of tramping a builtin function name is low. You're running into this trying to patch around a bug in ibis preventing calling `uuid()` directly, but in general most users are unlikely to resort to a python udf for something the database can provide directly.

**Comment by NickCrews** [comment]
All three of those points are good (esp number 2), and the suggested workarounds are pretty trivial. Thanks for the patience and the brain energy!
