### ISSUE TITLE
ci(bigquery): bigquery ci takes a very long time compared to other backends

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#8294]
BigQuery CI times seem to have increased quite a bit:

https://github.com/ibis-project/ibis/actions/runs/7843309685/job/21403367026?pr=8056

At the time of writing the run is not quite halfway done and has taken nearly 30 minutes to get there:

![image](https://github.com/ibis-project/ibis/assets/417981/ede50165-79c8-4554-b807-c2f4aae2ee9f)

@tswast Is there any low-hanging fruit here we can look into to speed this up?

**Comment by cpcloud** [comment]
Closing as still an issue, but not actively impeding any work at the moment.

**Comment by tswast** [comment]
Since we're using on-demand slots, performance can be unpredictable compared to [BigQuery "Editions"](https://cloud.google.com/bigquery/docs/editions-intro). I'll see if I can setup editions on the test project.

**Comment by tswast** [comment]
I have created an "Enterprise" edition reservation and assigned it to the ibis-gbq project. If cost becomes an issue, I may need to reconfigure some billing, but that should be doable by me or anyone else on the BigQuery DataFrames team.

**Comment by cpcloud** [comment]
This seems to have gotten slightly worse, or no improvement.

Here's all the recent successful runs of our cloud backends. The total time to run both BigQuery and Snowflake is listed in the third column.

https://github.com/ibis-project/ibis/actions/workflows/ibis-backends-cloud.yml?query=event%3Apush+is%3Asuccess
