### ISSUE TITLE
Enable expression table references to be "promoted" when safe

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#83]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Tuesday Jan 27, 2015 at 22:10 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/83_

---

For example, when referencing a table underneath a projection, potentially with a join. Currently this will yield a RelationError, but we can examine the references and perform a reference substitution, thus making the expression valid.

**Comment by cpcloud** [comment]
Closing as #180 has a more concrete version of this.
