### ISSUE TITLE
feat ibis -> duckdb extenssions

### ISSUE THREAD

**Issue by ededovic** [ibis-project/ibis#8379]
### Is your feature request related to a problem?

I love the idea of ibis, but it is almost impossible to install/update it without a conflict with other conda packages due to numerous dependencies . 

### Describe the solution you'd like

Why not work with duckdb team and implement database extensions like they did for postgresql, sqlite and mysql. 
[https://duckdb.org/2024/01/26/multi-database-support-in-duckdb.html](https://duckdb.org/2024/01/26/multi-database-support-in-duckdb.html)
All of them run one syntax, improved version of postgresql like-ish .  DuckDb also has python version of the syntax for someone that wants to use the python. 
The biggest advantage of using ibis is one syntax many dialects which is achieved with duckdb extensions.

duckdb has no dependencies making it super simple to install. 

### What version of ibis are you running?

7.2

### What backend(s) are you using, if any?

duckdb and pandas

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ededovic** [comment]
Thank you very much. I like your comment on chained SQL building, as that can help one isolate issues more quickly, especially in longer queries. Other reasons I like Ibis include forward filling and succinctness of Python expressions that generate repetitive SQL statements.

@gforsyth I like the suggestion of having `ibis-framework` running in its own environment. But after running sql statements, if I need to use a package that does not exist in that environment, how would you go about writing it?  If you have a link that has more details that will be great. 

By the way, reducing the dependencies would make this package even better and easier to use. For example,  `pip download ibis-framework[duckdb,examples]` brings in some 67 packages. MySQL version adds one more and Snowflake adds another 14 to total around 82. To show you how this becomes complex, duckdb requires SQLAlchemy 2.0+ while Snowflake requires 1.4.51. In other words, Ibis project is requiring conflicting packages for two different connections. If you add different pace of development of over 50 other packages, one can expect that things will break or become hard to use/address in a span of even few weeks. conda/mamba are unable to solve too many conflicting dependencies.

It will be great if in one of the future releases, some refactoring is done to reduce the dependency complexity of installing and using this great package if the original suggestion is a no-go.

**Comment by cpcloud** [comment]
Thanks @ededovic!

> reducing the dependencies would make this package even better and easier to use

Indeed! We dislike lots of dependencies as much as the next person.

We're aware of the dependency conflicts, especially the sqlalchemy issue you're referring to. We've had to deal with it on effectively a daily basis with hacks and workarounds in our CI.

In the next release of Ibis, 9.0.0, we've completely removed sqlalchemy as an explicit dependency of Ibis. You will be able to use whatever version of sqlalchemy you want in your application, 1.4, 2.x, it doesn't matter.

> pip download ibis-framework[duckdb,examples] brings in some 67 packages. MySQL version adds one more and Snowflake adds another 14 to total around 82.

> duckdb requires SQLAlchemy 2.0+

The duckdb backend doesn't **require** 2.0, it's just not limited to 1.x. snowflake-sqlalchemy on the other does not support sqlalchemy 2.0

> In other words, Ibis project is requiring conflicting packages for two different connections.

Not quite.

Ibis requires X, which will have other dependencies as well as constraints. Ibis is bound by those constraints. There's nothing Ibis can do from a technical perspective to force, say, snowflake-sqlalchemy and duckdb-engine to both support sqlalchemy 2.0. Library authors need to do the work to support it.

Generally speaking, it's not Ibis's job to ensure that all possible combinations of backend dependencies don't result in dependency downgrades or conflicts _for your application_.

We spend a lot of time and effort making sure that dependency bounds are as wide as possible to avoid that situation.

We also invest in the community ourselves by contributing conda packages, upstream fixes, issues and suggestions to other libraries for improvements.

Ultimately we are at the mercy of the various dependency solvers as well as the package maintainers. Again, we actively try to help on both those fronts as much as we can.
