### ISSUE TITLE
Add an API to pass through HDFS data directly to pandas.read_csv

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#838]
This will be easier than downloading a file (or reading the bytes into memory) then invoking read_csv on the result

**Comment by cpcloud** [comment]
I think we can do this with `hdfs3.HDFileSystem.open`, since it returns an object that implements the file protocol. Moving to 0.11, in which the PR to close #918 will also close this one.

**Comment by wesm** [comment]
same with `pyarrow.HdfsClient.open` (e.g. see examples in http://wesmckinney.com/blog/python-hdfs-interfaces/). We should aim to deprecate the WebHDFS stuff in Ibis and defer to libhdfs or libhdfs3 based on what's available on the host system
