### ISSUE TITLE
feat: Is there a parameter that can control to automatically add columns when the column name does not exist while inserting into ClickHouse?

### ISSUE THREAD

**Issue by stereoF** [ibis-project/ibis#8403]
### Is your feature request related to a problem?

For the ClickHouse backend, the following code is used to insert data into the table:

```
for batch in df_user.to_pandas_batches(chunk_size=batch_size):
    con.insert("algo_user", batch)
```

Since new columns often appear in df_user, is there a way to automatically add these columns when they do not exist in algo_user?

### Describe the solution you'd like

Add such parameter .

### What version of ibis are you running?

'7.1.0'

### What backend(s) are you using, if any?

clickhouse

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Agree with Phillip's response here. Closing for now as a question answered.
