### ISSUE TITLE
feat: cuDF backend

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8435]
### Is your feature request related to a problem?

[while we verified (at least on one version of Ibis) that cuDF "just works" with the pandas backend](https://voltrondata.com/resources/ibis-cudf-pandas), it'd be good to have a proper dedicated and tested cuDF backend for a couple reasons:

1. a better story for IbisML
2. a better story for Theseus

"Use Ibis and IbisML to accelerate your ML preprocessing and XGBoost/LightGBM/PyTorch/Tensorflow training on a single GPU node. If hitting a wall, scale up w/ Theseus"

### Describe the solution you'd like

proper cuDF backend w/ testing. probably need a GPU 

documentation

blog

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
cc @mmccarty -- y'all have any pointers on cuDF CI setups?

**Comment by gforsyth** [comment]
I'm going to close this out for now -- we might pick it back up in the future but it isn't a current priority.
