### ISSUE TITLE
feat: move `fillna` and `dropna` rewrites back into the expression level

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#8454]
### Describe the solution you'd like

Over the course of the-epic-split, the rewrites for handling `fillna` and `dropna` migrated from the expression-level rewrite system into the compiler.  As noted in #8448 if we move them back into the expression-level, we can potentially fuse some selects and generate some nicer SQL.
Plus, we already have the rewrite rule available, we just aren't using them (currently).

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
This was fixed by #9134. Closing.
