### ISSUE TITLE
docs: dev environment setup instructions don't work

### ISSUE THREAD

**Issue by dlovell** [ibis-project/ibis#8470]
### Please describe the issue

The [development dependencies](https://ibis-project.org/contribute/01_environment#required-dependencies) installation step, `pip install -r requirements-dev.txt` fails and complains about `psycopg2`

```
(venv) me@here:~$ pip install -r requirements-dev.txt >/dev/null
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-yhjccfv9/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-yhjccfv9/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-yhjccfv9/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-yhjccfv9/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-yhjccfv9/psycopg2.egg-info/SOURCES.txt'

      Error: pg_config executable not found.

      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:

          python setup.py build_ext --pg-config /path/to/pg_config build ...

      or with the pg_config option in 'setup.cfg'.

      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.

      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

```
git log | head -n3
commit 8d27d14fac6e68f65da47512d2b3b106466dc51f
Author: Krisztián Szűcs <szucs.krisztian@gmail.com>
Date:   Tue Feb 27 10:40:14 2024 +0100
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
I think there are a few things to try noted here: https://stackoverflow.com/questions/11618898/pg-config-executable-not-found

we should fix up this doc 

@dlovell can you also confirm the OS and other details? 

cc: @chloeh13q

**Comment by gforsyth** [comment]
> we should fix up this doc

It's a rather large burden for us to have to cover installing system dependencies that `pip` can't handle across the matrix of operating systems and package managers users might be using.

I wonder if we should just remove `pip` as an advertised option altogether.

**Comment by cpcloud** [comment]
I'll put up a PR with a warning callout in the docs. I don't think we're going to maintain a list of all possible system dependencies that pip will not install and how to install them on 3 different operating systems.

The only real options for complete environment management are nix, conda, mamba, or pixi.

**Comment by cpcloud** [comment]
Oh, it looks like we already have this warning :)

![image](https://github.com/ibis-project/ibis/assets/417981/0279ded5-1c5f-4cf0-b263-0b87bc1e9831)
