### ISSUE TITLE
bug(duckdb): struct field access on CASE generates SQL that duckdb cannot parse

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8485]
### What happened?

OK, I'm really getting into the weeds here, this is a weird little case 😄 

```python
import ibis

s = ibis.struct({"a": 3})
x = ibis.case().when(s.a.isnull(), s).end()
y = x.a
print(ibis.to_sql(y))
# SELECT
#   CASE
#     WHEN (
#       {'a': CAST(3 AS TINYINT)}."a"
#     ) IS NULL
#     THEN {'a': CAST(3 AS TINYINT)}
#     ELSE CAST(NULL AS STRUCT(a TINYINT))
#   END."a" AS "a"
y.execute()  # Parser error due to the END."a"
```

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kszucs** [comment]
> OK, I'm really getting into the weeds here

Keep going! Apparently we lack test coverage here and there.

**Comment by cpcloud** [comment]
Yeah this is definitely a bug somewhere. Given the precedence of `CASE` in other expressions like arithmetic it's surprising that this fails to parse.

**Comment by cpcloud** [comment]
This seems to be an oversight in the duckdb parser: parenthesizing the `CASE` statement works. Looking at another backend that supports structs, trino has no issues with the unparenthesized `CASE` expression.

**Comment by NickCrews** [comment]
Thanks for the quick fix!!

**Comment by cpcloud** [comment]
Upstream issue here: https://github.com/duckdb/duckdb/issues/10902
