### ISSUE TITLE
docs: add RisingWave to the installs tab

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8488]
### Please describe the issue

in `docs/_tabsets/instal.qmd`, add the RisingWave backend

I took a stab at this and could not get it to regenerate while rewriting another document, opening this for tracking (and if anyone has a tip -- simply adding a new line for it in the backends list of dictionaries didn't work w/ a `just docs-preview`)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
If you can post the error then we might be able to help debug.

**Comment by cpcloud** [comment]
But also perhaps Zulip might be quicker and less noisy

**Comment by lostmygithubaccount** [comment]
no error message, it just doesn't update -- will throw something in Zulip in a bit

**Comment by gforsyth** [comment]
It rendered for me but I first had to nuke the `docs/.quarto` directory. 

That was probably a bigger hammer than was required, but if we figure out which folders to remove to force a "clean" rebuild we should encode that in the `justfile`.

**Comment by cpcloud** [comment]
Or perhaps in `.gitignore`, then `git clean` can do that.

**Comment by gforsyth** [comment]
ok, it's the `docs/.quarto/_freeze` directory that needs to be removed to force a regen of the install tabset (and a few other things)

**Comment by lostmygithubaccount** [comment]
got it working w/ that, will close in my PR for #8251
