### ISSUE TITLE
bug(bigquery): user-provided client's default job config is modified

### ISSUE THREAD

**Issue by shobsi** [ibis-project/ibis#8494]
### What happened?

Initialize a BigQuery (BQ) client:

```python
>>> from google.cloud import bigquery
>>> encryption_config = bigquery.EncryptionConfiguration(kms_key_name="projects/my-project/locations/global/myKeyRing/cryptoKeys/myKey")
>>> query_job_config = bigquery.QueryJobConfig(destination_encryption_configuration=encryption_config)
>>> bqclient = bigquery.Client(default_query_job_config=query_job_config)
>>> bqclient.default_query_job_config.destination_encryption_configuration
EncryptionConfiguration(projects/my-project/locations/global/myKeyRing/cryptoKeys/myKey)
>>>
```

Pass the BQ client to to ibis bigquery connection:

```python
>>> import ibis
>>> ibis.bigquery.connect(client=bqclient)
<ibis.backends.bigquery.Backend object at 0x7febe7bcfaf0>
```

Now the passed BQ client's default job config has been modified:

```python
>>> bqclient.default_query_job_config.destination_encryption_configuration
>>>
```

### What version of ibis are you using?

```python
>>> ibis.__version__
'7.1.0'
```

### What backend(s) are you using, if any?

BigQuery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shobsi** [comment]
I think this is whre the bug is: https://github.com/ibis-project/ibis/blob/c2a9ba9a1dd9134d32ba696c92f2de50e99117f9/ibis/backends/bigquery/__init__.py#L436

**Comment by shobsi** [comment]
Thanks for the change. Looks like technically we will still modify the passed client. E.g. if someone passes a client without a default job config they will have it modified with a default job config that has `use_legacy_sql`  and `allow_large_results` set.

I would suggest keeping a separate internal job config and passing that to the client. It internally merges that with the default config:
- Query job:
  - https://github.com/googleapis/python-bigquery/blob/53c2cbf98d2961f553747514de273bcd5c117f0e/google/cloud/bigquery/client.py#L3391
- Load Job:
  - https://github.com/googleapis/python-bigquery/blob/53c2cbf98d2961f553747514de273bcd5c117f0e/google/cloud/bigquery/client.py#L2398
  - https://github.com/googleapis/python-bigquery/blob/53c2cbf98d2961f553747514de273bcd5c117f0e/google/cloud/bigquery/client.py#L2494
  - https://github.com/googleapis/python-bigquery/blob/53c2cbf98d2961f553747514de273bcd5c117f0e/google/cloud/bigquery/client.py#L2634
  - https://github.com/googleapis/python-bigquery/blob/53c2cbf98d2961f553747514de273bcd5c117f0e/google/cloud/bigquery/client.py#L2850

**Comment by gforsyth** [comment]
@shobsi -- I think if we don't pass in `use_legacy_sql` and `allow_large_results` that we'll leave things in only a semi-functional state.
Is there a usability issue with not modifying these two parameters?

**Comment by shobsi** [comment]
@gforsyth,  I am not suggesting to not pass it. I meant let's pass it via a query time config instead of setting in the user's bqclient's default config. Looks like it's already being done at a couple of places in the ibis code, e.g. https://github.com/ibis-project/ibis/blob/6ba4e8d471e3cca4fe05419ed582756bc854a0d1/ibis/backends/bigquery/__init__.py#L600
