### ISSUE TITLE
bug: topk() always says a column contains 0 NULLs

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8518]
### What happened?

I would expect this to say that there is 1 NULL:
```python
import ibis

ibis.options.interactive = True

t = ibis.memtable({"x": [1, 1, 2, None]})
tk = t.x.topk(10)
tk
# ┏━━━━━━━━━┳━━━━━━━━━━┓
# ┃ x       ┃ Count(x) ┃
# ┡━━━━━━━━━╇━━━━━━━━━━┩
# │ float64 │ int64    │
# ├─────────┼──────────┤
# │     1.0 │        2 │
# │     2.0 │        1 │
# │    NULL │        0 │
# └─────────┴──────────┘
ibis.to_sql(tk)
# SELECT
#   "t1"."x",
#   "t1"."Count(x)"
# FROM (
#   SELECT
#     "t0"."x",
#     COUNT("t0"."x") AS "Count(x)"
#   FROM "ibis_pandas_memtable_46aexxpm3fdfhdexrstqhyuvyi" AS "t0"
#   GROUP BY
#     1
# ) AS "t1"
# ORDER BY
#   "t1"."Count(x)" DESC
# LIMIT 10
```

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This is expected behavior due to the `count(x)` in the group by. `count(expr)`, like most other aggregates ignores `NULL` inputs.

If you want to count `NULL` you can pass `t.count()` to `by`:

```python
tk = t.x.topk(10, by=t.count())  # or by=_.count()
```

**Comment by NickCrews** [comment]
Could we consider changing what is expected behavior to what I expect?

If we don't, the we definitely should remove the NULL: 0 row from the output, since that is actively wrong.

**Comment by NickCrews** [comment]
Whatever we decide, value_counts() should also have the same semantics

**Comment by cpcloud** [comment]
Hm, yeah the NULL *is* confusing in the output. I see what you mean. I think it makes sense to change this to be `_.count()` by default. This is already the behavior of `value_counts()` IIRC.

**Comment by NickCrews** [comment]
@cpcloud just to be sure you saw it, I edited my comment with some more info/context

**Comment by cpcloud** [comment]
Thanks, got it!

I think avoiding a loss of information is probably the way to go here. You can't recover uncounted nulls, whereas you can always discard the counted ones after the fact.

**Comment by NickCrews** [comment]
related: https://github.com/ibis-project/ibis/issues/8540
