### ISSUE TITLE
feat: support table.sql() for Polars

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8525]
### Is your feature request related to a problem?

`con.sql()` is implemented, but `table.sql()` is not:

```python
[ins] In [1]: import ibis

[ins] In [2]: ibis.options.interactive = True

[ins] In [3]: ibis.set_backend("polars")

[ins] In [4]: t = ibis.examples.penguins.fetch()

[ins] In [5]: t
Out[5]:
┏━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃ species ┃ island    ┃ bill_length_mm ┃ bill_depth_mm ┃ flipper_length_mm ┃ body_mass_g ┃ sex    ┃ year  ┃
┡━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ string  │ string    │ float64        │ float64       │ int64             │ int64       │ string │ int64 │
├─────────┼───────────┼────────────────┼───────────────┼───────────────────┼─────────────┼────────┼───────┤
│ Adelie  │ Torgersen │           39.1 │          18.7 │               181 │        3750 │ male   │  2007 │
│ Adelie  │ Torgersen │           39.5 │          17.4 │               186 │        3800 │ female │  2007 │
│ Adelie  │ Torgersen │           40.3 │          18.0 │               195 │        3250 │ female │  2007 │
│ Adelie  │ Torgersen │           NULL │          NULL │              NULL │        NULL │ NULL   │  2007 │
│ Adelie  │ Torgersen │           36.7 │          19.3 │               193 │        3450 │ female │  2007 │
│ Adelie  │ Torgersen │           39.3 │          20.6 │               190 │        3650 │ male   │  2007 │
│ Adelie  │ Torgersen │           38.9 │          17.8 │               181 │        3625 │ female │  2007 │
│ Adelie  │ Torgersen │           39.2 │          19.6 │               195 │        4675 │ male   │  2007 │
│ Adelie  │ Torgersen │           34.1 │          18.1 │               193 │        3475 │ NULL   │  2007 │
│ Adelie  │ Torgersen │           42.0 │          20.2 │               190 │        4250 │ NULL   │  2007 │
│ …       │ …         │              … │             … │                 … │           … │ …      │     … │
└─────────┴───────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┴───────┘

[ins] In [6]: t.sql("SELECT species, island, count(*) AS count FROM penguins GROUP BY species, island")
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[6], line 1
----> 1 t.sql("SELECT species, island, count(*) AS count FROM penguins GROUP BY species, island")

File ~/repos/ibis/ibis/expr/types/relations.py:3329, in Table.sql(self, query, dialect)
   3326     name = util.gen_name("sql_query")
   3327     expr = self
-> 3329 schema = backend._get_sql_string_view_schema(name, expr, query)
   3330 node = ops.SQLStringView(child=self.op(), query=query, schema=schema)
   3331 return node.to_expr()

File ~/repos/ibis/ibis/backends/polars/__init__.py:410, in Backend._get_sql_string_view_schema(self, name, table, query)
    409 def _get_sql_string_view_schema(self, name, table, query) -> sch.Schema:
--> 410     raise NotImplementedError("table.sql() not yet supported in polars")

NotImplementedError: table.sql() not yet supported in polars
```

### Describe the solution you'd like

support `table.sql()` with the Polars backend

this is mainly useful to me for consistency in example code for the documentation

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

Polars

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue.

Can you paste in a copy-pastable example 😁

**Comment by cpcloud** [comment]
We can't support anything but the most trivial queries until Polars has support for CTEs (common table expressions). I'll put up a draft PR to demonstrate the issue.

**Comment by lostmygithubaccount** [comment]
updated -- the PR works for the example I want to use for docs

**Comment by lostmygithubaccount** [comment]
looks like two relevant (currently open) issues in Polars:

- https://github.com/pola-rs/polars/issues/11154 -- unlikely to support recursive CTEs
- https://github.com/pola-rs/polars/issues/7227 -- CTEs are planned

**Comment by cpcloud** [comment]
The `WITH` box is checked, does that mean it's supposed to be done?

**Comment by alexander-beedie** [comment]
> The `WITH` box is checked, does that mean it's supposed to be done?

We've had basic (non-recursive) CTE support[^1] for about a year now 😉👌 

[^1]: https://github.com/pola-rs/polars/pull/8208

**Comment by lostmygithubaccount** [comment]
hi @alexander-beedie! I did ask [here](https://github.com/pola-rs/polars/issues/14704), but while you're here do you know if Polars is following any specific SQL dialect or doing its own thing? I'm mainly curious 1) if/when the SQL interface would catch up to the dataframe interface and 2) if it'd be easy to use SQLGlot via one of the existing dialects to interface with it

**Comment by cpcloud** [comment]
Polars doesn't seem to handle quoted identifiers. That's the main reason for the extremely limited support for SQL operations using the polars backend in Ibis.

**Comment by alexander-beedie** [comment]
> hi @alexander-beedie! I did ask [here](https://github.com/pola-rs/polars/issues/14704), but while you're here do you know if Polars is following any specific SQL dialect or doing its own thing? 

We follow PostgreSQL for standard SQL syntax; not everything fits there of course, so then we try to obey the "principle of least surprise" ;)

(For example, there is no standard PostgreSQL function for `skew` - I was just asked if we could expose that via the SQL interface, and I note that DuckDB uses "SKEWNESS" here, so the chances are that I'll follow there lead for that). 

I'm mainly curious 1) if/when the SQL interface would catch up to the dataframe interface and 

No fixed target for that, but it's continuing to build out - yesterday's release added a few more functions (greatest, least, median) and another table operation (truncate), for example. 

If you are being held back by a lack of specific functions/syntax, please raise an Issue with us as that can help us prioritise 👍

**Comment by alexander-beedie** [comment]
> Polars doesn't seem to handle quoted identifiers. That's the main reason for the extremely limited support for SQL operations using the polars backend in Ibis.

@cpcloud: Sure we do; got a specific instance where it goes wrong? If so, please let us know - if there's a bug but nobody reports it, we'll have quite a hard time fixing it. Feel free to tag me in an Issue/bug-report so I can take a look ;)

For example, the following quotes the table name, column name, and alias without issue:
```python
df = pl.DataFrame({
    "badge_num": [1,2,3,4],
    "name": ["John","Mark","Steve","Bob"],
    "surname": ["Smith","Jones","Smith","Smith"],
})

with pl.SQLContext(employees=df) as ctx:
    res = ctx.execute("""
      SELECT "employees"."surname", COUNT(*) AS "n" FROM "employees" GROUP BY "surname"
    """).collect()

    # shape: (2, 2)
    # ┌─────────┬─────┐
    # │ surname ┆ n   │
    # │ ---     ┆ --- │
    # │ str     ┆ u32 │
    # ╞═════════╪═════╡
    # │ Jones   ┆ 1   │
    # │ Smith   ┆ 3   │
    # └─────────┴─────┘
```

**Comment by alexander-beedie** [comment]
Got it; fixed with a one-liner - exclusively impacted CTE identifier names.
Landing the PR now: https://github.com/pola-rs/polars/pull/15564 👌

**Comment by alexander-beedie** [comment]
> hi @alexander-beedie! I did ask [here](https://github.com/pola-rs/polars/issues/14704)

Also, will follow up on this one; I just delved into the docs and was faintly horrified to see that PostgreSQL does actually claim to support grouping by[^1] ordinal position values - which seems genuinely horrible (not self-documenting, and presumably shockingly fragile, but... valid syntax nevertheless!) 🤣 

[^1]: https://www.postgresql.org/docs/current/sql-select.html#SQL-GROUPBY

**Comment by cpcloud** [comment]
> > hi @alexander-beedie! I did ask [here](https://github.com/pola-rs/polars/issues/14704)
> 
> Also, will follow up on this one; I just delved into the docs and was faintly horrified to see that PostgreSQL does actually claim to support grouping by[1](#user-content-fn-1-19da2a4fbaabd241d7a74e93a55aa26d) ordinal position values - which seems genuinely horrible (not self-documenting, and presumably shockingly fragile, but... valid syntax nevertheless!) 🤣
> 
> ## Footnotes
> 1. [postgresql.org/docs/current/sql-select.html#SQL-GROUPBY](https://www.postgresql.org/docs/current/sql-select.html#SQL-GROUPBY) [↩](#user-content-fnref-1-19da2a4fbaabd241d7a74e93a55aa26d)

It's a nice syntax for SQL-generating libraries to avoid repeating large group by expressions. It's used a lot more than you'd think.

**Comment by alexander-beedie** [comment]
FYI: the upcoming `0.20.20` (will likely release sometime in the next few days) has fixes for both issues (quoted CTE identifier names and ordinal/integer "GROUP BY" clauses). I'll take a look at adding ordinal support for "ORDER BY" clauses in the near future too; looks pretty straightforward.

**Comment by cpcloud** [comment]
Version bump here: https://github.com/ibis-project/ibis/pull/8960.

Will get shipped in the next Ibis release in a week or so.

**Comment by alexander-beedie** [comment]
FYI: ordinal support for the `ORDER BY` clause will be landing in the next release:
https://github.com/pola-rs/polars/pull/16745
