### ISSUE TITLE
docs(geospatial): plots not rendering on geospatial blog

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#8542]
### Please describe the issue

In this blog https://ibis-project.org/posts/ibis-duckdb-geospatial/ we have some problem rendering the vector layers. 

This problem is comes from leafmap and has a root on lonboard most recent updates. Looks like leafmap was using a private method internally and lonboard doesn't guarantee backwards compatibility in that case. 

I opened an upstream issue on leafmap, and they are working on a solution. I'll see if in the meantime we can pin some dependencies to get this working. 

xref: https://github.com/opengeos/leafmap/issues/699

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
shouldn't the outputs be frozen? why didn't that prevent it from breaking?
