### ISSUE TITLE
feat: add .cast() after every UDF

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8547]
### Is your feature request related to a problem?

first see this:

```python
import ibis

ibis.options.interactive = True


# in duckdb, array_sum() actually returns a float
@ibis.udf.scalar.builtin
def array_sum(x) -> int: ...


t = ibis.memtable({"a": [[1, 2, 3]]})
t = t.mutate(b=array_sum(t.a))
p = "./tmp.parquet"
t.to_parquet(p)
ibis.read_parquet(p)
# oops, b is a float
# ┏━━━━━━━━━━━━━━━━┳━━━━━━━━━┓
# ┃ a              ┃ b       ┃
# ┡━━━━━━━━━━━━━━━━╇━━━━━━━━━┩
# │ array<int64>   │ float64 │
# ├────────────────┼─────────┤
# │ [1, 2, ... +1] │     6.0 │
# └────────────────┴─────────┘
```

### Describe the solution you'd like

I'm not sure what ibis should do here:
1. this is my fault for not specifying the correct return type. ibis shouldn't try to put any guardrails here.
2. ibis should add a cast() after every UDF call to ensure the result is actually the return type specified in the signature. Seems like this should be a NOOP in the happy path with no perf problems, but it should catch bugs otherwise

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @NickCrews -- thanks for raising this.  I think we are probably going to go with Option 1 here.
We'd end up adding a bunch of casts and there's no guarantee that the `cast` is reflective of the user's intent.
