### ISSUE TITLE
bug: inner Deferred binds to wrong thing in `Table.select(_.x.map(_.b))`

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8553]
### What happened?

See https://github.com/ibis-project/ibis/pull/8552

I think what is happening:
1. ibis encounters the _.x when evaluating the .select
2. it tries to bind it to the parent expression, the Table
3. then it recurses down into the deferred to further evaluate it
4. It encounters the _.b
5. It isn't smart enough to understand that this now refers to each array element. It just binds it to that outer Table
6. raises AttributeError

This seems like it might be a doozy to solve. Would need to make the idea of a context much more nuanced, with nested scopes??

### What version of ibis are you using?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I think this is pretty tricky 🤓

There's also no reason to prevent use of underscore inside of a lambda afaict.

I think we're limited in our options.

**Comment by NickCrews** [comment]
> use of underscore inside of a lambda afaict.

I added a xfail example for this in the linked PR. It fails for a different reason though I think?

> I think we're limited in our options.

Yeah I bet. In these examples, we get an error. But I think it would be possible to make a query that doesn't crash, but just insidiously gives the wrong result (ie both the table and the struct have a field called "y", we wanted to reference struct.y, but it compiled to table.y). At the least we need to ensure that this doesn't happen. I'm fine with getting rid of the nice feature if that is the only way to get this correctness.
