### ISSUE TITLE
feat(api): shorthand for table topk

### ISSUE THREAD

**Issue by chloeh13q** [ibis-project/ibis#8574]
### Is your feature request related to a problem?

Currently, ibis only supports topk defined on top of columns. I.e., the topk shorthand works for something like "top 5 commenters by number of comments made" but not "top 5 commenters with the highest cumulative scores". This syntax can be quite verbose to write out and a shorthand could be valuable.

Examples:

Clickhouse:
```py
top_commenters_by_score = (
    t.filter(_.by != "")
    .group_by("by")
    .agg(total_score=_.score.sum())
    .order_by(ibis.desc("total_score"))
    .limit(5)
)
```

Flink:
```py
expr = t.window_by(time_col="i").tumble(
    window_size=ibis.interval(seconds=600),
)["a", "b", "c", "d", "g", "window_start", "window_end"]
expr = expr.mutate(
    rownum=ibis.row_number().over(
        group_by=["window_start", "window_end"], order_by=ibis.desc("g")
    )
)
expr = expr[expr.rownum <= 3]
```

### Describe the solution you'd like

A shorthand for table topk

### What version of ibis are you running?

8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
You can pass columns from the parent table to `by`:

```
In [8]: from ibis.interactive import *

In [9]: con = ibis.connect("clickhouse://play:clickhouse@play.clickhouse.com:443?secure=True")

In [10]: t = con.tables.hackernews

In [11]: t.by.topk(5, by=_.score.sum())
Out[11]:
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ by           ┃ Sum(score) ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ !string      │ int64      │
├──────────────┼────────────┤
│ ingve        │     405248 │
│ tosh         │     301694 │
│ pseudolus    │     295067 │
│ Tomte        │     276776 │
│ todsacerdoti │     269524 │
└──────────────┴────────────┘
```

Is there another use case you have in mind here?

**Comment by chloeh13q** [comment]
Oh wow! Perhaps we should update this documentation: https://ibis-project.org/tutorials/data-platforms/clickhouse.html#finding-top-commenters-by-score then?

**Comment by cpcloud** [comment]
SGTM, hopefully that is a straightforward PR 😬

**Comment by chloeh13q** [comment]
Can you do topk without groupby aggregation? E.g. given a table with `product_id STRING, category STRING, product_name STRING, sales BIGINT`, compute "the top five products per category that have the maximum sales"

**Comment by cpcloud** [comment]
I think you'd probably need a somewhat gnarly window function to express that.

**Comment by zhenzhongxu** [comment]
If the intent is to have top_k shorthand for the Flink backend, it seems we need to split up the implementation between [top-n](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/topn/) and [windowed top-n](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/window-topn/).

For Flink streaming mode, top-n behavior might be similar to batch but can be "updating" (meaning changing results will be sent as retraction updates, continuously, unbounded).
```
SELECT [column_list]
FROM (
   SELECT [column_list],
     ROW_NUMBER() OVER ([PARTITION BY col1[, col2...]]
       ORDER BY col1 [asc|desc][, col2 [asc|desc]...]) AS rownum
   FROM table_name)
WHERE rownum <= N [AND conditions]
```
Windowed top-n generally returns top n for each window firing, continuous, unbounded as well. 
```
SELECT [column_list]
FROM (
   SELECT [column_list],
     ROW_NUMBER() OVER (PARTITION BY window_start, window_end [, col_key1...]
       ORDER BY col1 [asc|desc][, col2 [asc|desc]...]) AS rownum
   FROM table_name) -- relation applied windowing TVF
WHERE rownum <= N [AND conditions]
```

**Comment by chloeh13q** [comment]
Some alternative approaches to express "the top five products per category that have the maximum sales":
1. Natively with ROW NUMBER:
```
t.mutate(rownum=ibis.row_number().over(
    group_by=[_.category], order_by=_.sales
))
```
(Feels natural if the user is coming from SQL, otherwise may not be immediately obvious; documentation would help)
1. We can express "the top five products that have the maximum sales" without `topk`, i.e., `t.order_by(t.sales).limit(5)`. "Per category" adds a group by and some type of aggregation is needed. Can `topk` be treated as an aggregation from the API perspective?
```python
t.group_by(_.category).order_by(_.sales).aggregate(_.topk(5))
```
1. We could add a table level `topk` API that looks something like
```python
t.topk(k=5, by="sales", group_by="category")
```
This feels like a reasonably intuitive extension to the current `topk` API, but does require some changes.

After spending some time looking at this, I wonder if option 1 is sufficient for the time being, if we provide appropriate documentation for it. Having a convenient shorthand would be nice, but doesn't save a ton of time & it seems to me that we haven't gotten any requests for it. I'm not sure how frequently people are actually doing these table topk's instead of column topk's.

**Comment by chloeh13q** [comment]
I'm going to close this ticket in favor of #8830. I think providing additional documentation is sufficient for this use case for the time being. We can revisit this issue if there is request from the community in the future.
