### ISSUE TITLE
feat: docs: update extending tutorial for custom operations

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8603]
### Is your feature request related to a problem?

As I was trying to solve https://ibis-project.zulipchat.com/#narrow/stream/405265-tech-support/topic/value.20counts.20for.20array.20elements/near/425615487, I think a possible solution would be to add a new ArrayValueCount Operation. But I noticed that (presumably due to the sqlglot refactor) the [old extending guide](https://github.com/ibis-project/ibis/blob/8da58d41f82e937cbe4ab446a76965dba2c7e4ad/docs/how-to/extending/elementwise.qmd) was deleted.

Can we bring back an updated version of that guide? Is that even a public API? (I hope so)

### Describe the solution you'd like

NA

### What version of ibis are you running?

Na

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I think for the specific case of the array value count operation you're after, we wouldn't bring back the custom operation tutorial as a way of extending ibis, but it has value as a guide for contributing a new operation.

Thoughts?

**Comment by NickCrews** [comment]
Sorry, not quite sure I get the distinction? Like aim the guide more for developers wanting to modify the core of ibis (ie with the end goal of code getting merged into this repo), not for 3rd party developers wanting to bolt on extra features (code is never going to get merged into this repo)?

**Comment by cpcloud** [comment]
That's right. Extending operations by adding a new operation class is not likely to be stable across minor versions.

**Comment by NickCrews** [comment]
Hmm, in that case then I think the value is more limited. Seems like the number of people who would want to do that is much smaller. I'm fine with closing this as not planned.
