### ISSUE TITLE
docs: Make links to sections in release notes stable across releases

### ISSUE THREAD

**Issue by amoeba** [ibis-project/ibis#8624]
### Please describe the issue

I noticed while grabbing a hyperlink to the latest Ibis release from https://ibis-project.org/release_notes that the fragment identifier for the most recent release is ambiguous: https://ibis-project.org/release_notes#section. I then noticed that all the anchor links are similar. Quarto (or pandoc?) appears to not like when headings start with numbers and falls back to some sort of other behavior. The result is that, on every new Ibis release https://ibis-project.org/release_notes#section will jump the user to the latest release and it won't be possible to have a stable link to a particular release section.

While Ibis' users may not expect these links to be stable, I think it's really nice to just have stable anchor hyperlinks.

I'd be happy to send in a PR for a change if this is of interest. I think just changing the headers is the way to go, rather than messing with any custom hacks with Pandoc or similar. Perhaps just prepending "v" or "Ibis " to each heading? While I'm in there I could take a look around the rest of the site to find any other issues.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lee-coates** [comment]
@amoeba I submitted a [PR](https://github.com/ibis-project/ibis/pull/8875) making the table of contents links non-ambiguous. I'm not sure visually the change is great, but like you mentioned, this seems to be a limitation in quarto. I'll keep looking, but feel free to accept the PR if this direction seems like the right one. Thanks!

**Comment by cpcloud** [comment]
This turned out to be a bit complicated, due to the fact that release note generation is automated.

I ended up solving the problem (in #8941) with a custom pandoc filter that forces header link elements to have the version tag as the href link.

This seems like a bug in Quarto that should be reported upstream. It doesn't seem like there's any particular reason to make numbers special here.

**Comment by amoeba** [comment]
Thanks for diving into that @cpcloud. And thanks for noticing this @lee-coates and submitting a PR.

**Comment by amoeba** [comment]
I filed an issue upstream, see https://github.com/quarto-dev/quarto/issues/413.
