### ISSUE TITLE
feat: add workarounds for duckdb MAP bugs

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8632]
### Is your feature request related to a problem?

see
https://github.com/duckdb/duckdb/issues/11115
and
https://github.com/duckdb/duckdb/issues/11116

This might be out of scope, and we should just wait for duckdb to fix these upstream, but we could add some workarounds for these bugs in ibis. I am running into these and am having to implement my own little wrappers, eg

```python
def _map_values(m: ir.MapValue) -> ir.ArrayValue:
    """workaround for https://github.com/duckdb/duckdb/issues/11116"""
    normal = m.values()
    null = ibis.literal(None, type=dt.Array(value_type=m.type().value_type))
    return m.isnull().ifelse(null, normal)
```

feel free to close this out if you don't want to take this on (I don't blame you if you don't 😉 )

### Describe the solution you'd like

I'm not sure where in the stack these fixes would need to go, at compile time, or just when creating expressions.

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks! Looks like you've gone down a map 🐰 🕳️ 

I think it's reasonable to add these workarounds for now.

**Comment by NickCrews** [comment]
yeah seriously talk about a 🐰 🕳️ . I was convinced for hours it was bugs in my code wheeeeee

here is what I currently use. I have unit tests for functions that use these, but I don't have unit tests for these as individuals.

```python
def map_keys(m: ir.MapValue) -> ir.ArrayValue:
    """workaround for https://github.com/duckdb/duckdb/issues/11116"""
    normal = m.keys()
    null = ibis.literal(None, type=dt.Array(value_type=m.type().key_type))
    return m.isnull().ifelse(null, normal)


def map_values(m: ir.MapValue) -> ir.ArrayValue:
    """workaround for https://github.com/duckdb/duckdb/issues/11116"""
    normal = m.values()
    null = ibis.literal(None, type=dt.Array(value_type=m.type().value_type))
    return m.isnull().ifelse(null, normal)


def map_(keys: ir.ArrayValue, values: ir.ArrayValue) -> ir.MapValue:
    """workaround for https://github.com/duckdb/duckdb/issues/11115"""
    either_null = keys.isnull() | values.isnull()
    regular = ibis.map(keys, values)
    null = ibis.literal(
        None,
        type=dt.Map(
            key_type=keys.type().value_type, value_type=values.type().value_type
        ),
    )
    return either_null.ifelse(null, regular)
```

**Comment by gforsyth** [comment]
Yeah, this would be good to get in for 9.0.  

@NickCrews do you have the bandwidth to PR this in?  We probably do want unit tests for them, and probably also some xfailed tests that will start to XPASS when the upstream issues are fixed.

**Comment by NickCrews** [comment]
In that PR I addressed https://github.com/duckdb/duckdb/issues/11115, which
- is more common
- leads to incorrect results in the NULL NULL case (!)

Once that is in then I can tackle https://github.com/duckdb/duckdb/issues/11116, which I think
- is much more rare
- usually leads to errors instead of incorrect reuslts.

**Comment by cpcloud** [comment]
I'll work on getting the rest of the map family of functions behaving consistently here.
