### ISSUE TITLE
bug: array(literal).zip() errors

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8641]
### What happened?

```python
import ibis

a = ibis.array([1, 2, 3])
z = a.zip(a)
z
```

causes `ParserException: Parser Error: syntax error at or near "["`

If I inspect the sql (ibis.to_sql() also errors, that could be a nice little ux improvement), then I think it is related to https://github.com/duckdb/duckdb/issues/11120

```sql
SELECT
  LIST_APPLY(
    RANGE(
      1,
      GREATEST(
        LENGTH([CAST(1 AS TINYINT), CAST(2 AS TINYINT), CAST(3 AS TINYINT)]),
        LENGTH([CAST(1 AS TINYINT), CAST(2 AS TINYINT), CAST(3 AS TINYINT)])
      ) + 1
    ),
    i -> {'f1': [CAST(1 AS TINYINT), CAST(2 AS TINYINT), CAST(3 AS TINYINT)][i], 'f2': [CAST(1 AS TINYINT), CAST(2 AS TINYINT), CAST(3 AS TINYINT)][i]}
  ) AS "ArrayZip()"
```

Perhaps we could generate list literals with `list_value(a, b, c)` syntax instead of `[a,b,c]` syntax as a workaround?

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Looked into this, and using `list_value` still has issues :)

https://github.com/tobymao/sqlglot/issues/3136
