### ISSUE TITLE
feat: Make `Struct`s a Mapping

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8670]
### Is your feature request related to a problem?

I want to treat Structs as a Mapping:

```python
def debug(**args):
    for k, v in args.items():
        print(f"{k}: {v}")


debug(**ibis.struct({"a": 1}))
# argument after ** must be a mapping, not StructScalar
```

### Describe the solution you'd like

PR incoming

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
See #8671, we decided this wasn't a good fit.
