### ISSUE TITLE
feat: Move BigQueryType from backends to sqlglot module

### ISSUE THREAD

**Issue by binste** [ibis-project/ibis#8681]
### Is your feature request related to a problem?

This is a follow-up to #7531. CC @cpcloud who closed it in #7597. I just wanted to release a new dbt-ibis version which uses this new `BigQueryType` if Ibis is >= 7.2 instead of the custom class I have implemented now. However, I noticed that `BigQueryType` is implemented in `ibis.backends.bigquery.datatypes` whereas the other sqlglot-based type mappers are in `ibis.backends.base.sqlglot.datatypes`.

### Describe the solution you'd like

Would you want to move it for consistency? For me, it would also be convenient in dbt-ibis as I can only import from `ibis.backends.bigquery` if the bigquery dependencies are installed where as I can always import from `ibis.backends.base.sqlglot`. Linking https://github.com/binste/dbt-ibis/pull/50 for reference.

### What version of ibis are you running?

8.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @binste -- we've already consolidated all of the sqlglot types on `main` in `ibis.backends.sql.datatypes` (note we've also removed the `base` part of that path as it was just an extra level of depth for no benefit).
The definitions are on these lines https://github.com/ibis-project/ibis/blob/main/ibis/backends/sql/datatypes.py#L697-L811

so I'll go ahead and close this out as completed, but let us know if you run into any other issues!
