### ISSUE TITLE
pyspark operation: WindowFunction

### ISSUE THREAD

**Issue by mark-druffel** [ibis-project/ibis#8715]
### Is your feature request related to a problem?

N/A

### Describe the solution you'd like

My team is trying to use Ibis to refactor our data pipeline. We would need access to a handful of operations to fully convert to Ibis from vanilla pyspark including Window. 

### What version of ibis are you running?

8.0.0

### What backend(s) are you using, if any?

pyspark

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepyaman** [comment]
Hi @mark-druffel! Just wanted to check, do you have an example of what's not working with the PySpark backend (but may be working on something else)? As far as I can tell, the PySpark backend does have window support implemented, and I see passing tests.

**Comment by mark-druffel** [comment]
Hey @deepyaman, thanks for the quick reply! I may have jumped the gun on opening this 😬  

I was just trying to plan my team's work and knew we had some pipeline nodes a couple sprints out that would rely on windowing. I looked at the [compatibility matrix](https://ibis-project.org/support_matrix) and based on that I thought it wouldn't work. We haven't actually written any code that failed... I should've gone through the work to create a reproducible example before opening this, I'm sorry for that.

**Comment by jcrist** [comment]
Thanks for opening this @mark-druffel! This led us to find a bug in the operation support matrix (a few other supported ops were erroneously marked as unsupported). It's still not perfect, but should be more accurate now.
