### ISSUE TITLE
feat(examples): add NYC flights data to R registry

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis#8718]
### Is your feature request related to a problem?

We are looking for an example dataset to demonstrate Ibis-ML functionality. @jcrist suggested that adding the `nycflights13` data to Ibis core would be useful for demonstrating a number of other functionalities, such as time series features.

### Describe the solution you'd like

`ibis.examples.nycflights13.fetch()` :airplane:

### What version of ibis are you running?

8.0.0

### What backend(s) are you using, if any?

Any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
I found that our friend Michael Chow uploaded some csvs of that dataset a few years back: https://github.com/machow/nycflights13-py/

The csvs have now been uploaded to the ibis examples bucket and I'll work on adding them to our examples registry generation.
