### ISSUE TITLE
feat(duckdb): add possibility to register mysql table

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#8728]
In https://github.com/ibis-project/ibis/pull/8656 we added support to read a table from mysql, but I noticed that we have a register api wehre we have teh possibility to register a postgres or sqlite table, see

https://github.com/ibis-project/ibis/blob/32b751444c131f03090bccf57d2d5958e44ef259/ibis/backends/duckdb/__init__.py#L555-L558

we can add mysql here too. 

Action Items: 
- add possibility to register a mysql table
- modify docstrings to include this and sqlite (they are missing)
- add tests for registering  mysql and postgres (I noticed there is no test for registering a postgres uri with the register api)

**Comment by gforsyth** [comment]
I think we should remove the `register` function entirely -- it predates most of the other more specific methods and it's a mess (and is completely untested).
So I think we just remove it and get it in for 9.0 as a breaking change.

**Comment by ncclementi** [comment]
Do we need add a deprecation cycle for the register function, or moving it out completely for 9.0?

**Comment by gforsyth** [comment]
We could give it a deprecation cycle -- we'll be removing a bunch of stuff in 10.0 already, so we can add this to the list.

**Comment by ncclementi** [comment]
Closing in favor of https://github.com/ibis-project/ibis/issues/8735
