### ISSUE TITLE
consider: should we use sqlglot's optimizer after compilation?

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8789]
### Is your feature request related to a problem?

As I worked on #8788, it got me wondering if there might be some optimizations that we don't do, but sqlglot would catch. If we upstream work there too, then others would benefit as well. Also, per https://github.com/ibis-project/ibis/issues/8770, this might help with optimizing queries that are impossible to optimize in the pre-compilation stage.

### Describe the solution you'd like

It looks like we already use `sqlglot.optimizer.optimize` already in ibis/expr/sql.py`, but maybe that only affects SubQueries? Can we apply it in more cases?

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NickCrews** [comment]
@kszucs sorry I wasn't very clear there. Often, as in https://github.com/ibis-project/ibis/issues/8770, inefficiencies are added back into the SQL during translation ibis->sqlglot, AFTER `rewrites.py` has done its magic, so `rewrites.py` isn't useful to us here.

**Comment by kszucs** [comment]
What I mean is that we can improve `rewrites.py` to avoid those inefficiencies.

**Comment by NickCrews** [comment]
I might be missing something here. Take a look at https://github.com/ibis-project/ibis/pull/8788/files#diff-cb487151de645f8616c295a297cf1bb685b77b639163934c40073dc8b692b83eR472-R488.

There, we have a self.if_ to ensure that all indexes are nonnegative. We only add this branching during compilation, because [some backends can handle negative indexing natively](https://duckdb.org/docs/sql/functions/char#array_slicelist-begin-end), so in our internal representation in ArraySlice, we allow storing negative `start` and `stop`. This means that this branching is only added during compilation, `rewrites.py` wouldn't ever see any branching. So, if we ever want to remove that branching, it can only happen after compilation. Does that make sense?

**Comment by NickCrews** [comment]
errr, or maybe I'm missing something and the rewrites can happen on a per-backend basis?

**Comment by kszucs** [comment]
> the rewrites can happen on a per-backend basis?

Yes.

**Comment by NickCrews** [comment]
ah, great, sorry for the noise! I'll take a look at solving these problems using that system. We can revisit using sqlglot's optimizer/simplifier if that is not sufficient.

**Comment by NickCrews** [comment]
@kszucs I'm realizing that the rewrites needed would have to be destructive/non-idempotent. Ie adding one to an index. Does the rewrite system support "apply this rewrite only once", or am I given no guarantees about if my rewrite is applied once or N times?

**Comment by kszucs** [comment]
We control the number of passes and replacements and currently we do them in a single pass. 

On the other hand if we were having multiple passes, idempotency depends on both the pattern and the replacement. The pattern wouldn't match the rewrite outcome again then no need to worry about it, otherwise a new node type can be introduced with the data.
