### ISSUE TITLE
Accept boolean expressions in case().when($HERE, result_expr)

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#879]
Brought up on the mailing list. Here's a minimal example:

```
In [9]: expr = ibis.literal('foo')

In [10]: expr.lower().case().when(expr.like('%some_text%'), 'hi').else_('no').end()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-870dbff07387> in <module>()
----> 1 expr.lower().case().when(expr.like('%some_text%'), 'hi').else_('no').end()

/home/wesm/code/ibis/ibis/expr/operations.py in when(self, case_expr, result_expr)
   1173 
   1174         if not self.base._can_compare(case_expr):
-> 1175             raise TypeError('Base expression and passed case are not '
   1176                             'comparable')
   1177 

TypeError: Base expression and passed case are not comparable
```

**Comment by cgc17** [comment]
I found the `where()` definition [here](https://github.com/cloudera/ibis/blob/f38880a38a4bc612eabde6039a320395c0084947/ibis/expr/operations.py#L1155-L1186), but where does the actual comparison for the case expression happen?  What's the difference in a SearchedCase and a SimpleCase?

Sorry for the basic questions, I'm just trying to orient myself.

**Comment by cpcloud** [comment]
`SimpleCase` has this form

```sql
CASE <expr>
WHEN <possible_value_of_expr>
...
WHEN<possible_value_of_expr>
ELSE ...
END
```

`SearchedCase` has this form

```sql
CASE
WHEN <predicate 1>
...
WHEN <predicate N>
ELSE ...
END
```

The first is roughly analogous to a `switch` construct in C, whereas the second is analogous to a series of `if () else if () else if () else ()` statements.

**Comment by cpcloud** [comment]
@wesm This seems like a correct failure, since the minimal example is mixing the two different types of case statements. My understanding is that `expr.case()` is *always* a simple case statement, and for a searched case statement there's the top-level function `ibis.case()`.

**Comment by wesm** [comment]
@cpcloud you are probably right. I'm wondering if there's a way to transform the simple case into a searched case to produce a more intuitive user experience?

**Comment by cpcloud** [comment]
Simple cases can be rewritten from

```sql
CASE a
  WHEN x
  WHEN y
  ...
  WHEN z
  ELSE ...
END
```

to

```
CASE
  WHEN a = x
  WHEN a = y
  ...
  WHEN a = z
END
```

But now I'm wondering why a `.case()` method on expressions exists at all, if not to somehow restrict the possible inputs. If `ibis.case()` and `expr.case()` are going to end up being the same it might make sense to either keep the constraint on `expr.case()` (and provide a more useful error message detailed the distinction) or deprecate it.

**Comment by cpcloud** [comment]
The motivation behind either keeping the current behavior or deprecating it is case expressions that have multiple columns in their cases. I think ibis code that looks like this would be very confusing:

```python
# e1, e2, and e3 are expressions
e1.lower().case().when(e1.like('abc%')).when(e2.like('%bar') | (e3 == 'a')).else_('foo').end()
```

The `.case()` call looks like it's operating only on `e1`, but then I use `e2` and `e3` in the `.when()`s, so calling it as a method seems to provide very little if any information.

**Comment by cpcloud** [comment]
I could see a `lambda` working here, but having an expression like this:

```python
expr.lower().case().when(expr.like('%a%'), 'c').else_('b')
```
semantically mean this:

```python
expr.lower().case().when(expr.lower().like('%a%'), 'c').else_('b')
```

seems confusing. Marking as a usability enhancement.

**Comment by cpcloud** [comment]
Closing as correct behavior.
