### ISSUE TITLE
perf: natively support `String.slice(start, end)` as well as `String.substr(start, length)`

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8796]
### Is your feature request related to a problem?

Currently, `ibis.literal("abc")[1:]` gets compiled to `SUBSTRING('abc', 2, LENGTH('abc') - CAST(1 AS TINYINT))` on duckdb. However,  duckdb has a builtin [`array_slice(string, start, end)`](https://duckdb.org/docs/sql/functions/char#array_slicelist-begin-end) function, that would 1. be simpler SQL and would avoid duplicating compiling the subexpression `'abc'` 2. probably be faster.

### Describe the solution you'd like

I think we need to have a data model in ibis that can represent both kinds of specification, (start, length) and (start, end). I could see this being either

1. Add a `StringSlice` Op in addition to the existing `Substring` op
2. Modify the existing `Substring` op so that it can either take a `length` or an `end`.

I would lean towards 1, I bet that would lead to less ifelse branching throughout the code.

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kszucs** [comment]
I think a `StringSlice` operation would be handy which we can rewrite to `Substring` for backends not natively supporting negative indices.
