### ISSUE TITLE
bug: Ibis broken in nixpkgs, might be fixed by a new tag that incorporates the update to sqlglot dependency

### ISSUE THREAD

**Issue by ElleNajt** [ibis-project/ibis#8800]
### What happened?

The most recent tag of ibis is broken in nixpkgs unstable, since it requires sqlglot<=20.11,>=18.12.0 but sqlglot in nixpkgs has been updated to 21. 

It seems that more recent commits of ibis upgraded all the way to 23: https://github.com/NixOS/nixpkgs/commit/fc7168d8d918b9a8fd11f0c27685b31d9a571f26

Would it be possible to release a new tag of ibis incorporating the sqlglot upgrade, so that (hopefully) sqlglot and ibis could both be upgraded to a state where ibis builds?

Also discussed this here: https://github.com/NixOS/nixpkgs/commit/fc7168d8d918b9a8fd11f0c27685b31d9a571f26#commitcomment-140226400

### What version of ibis are you using?

8.0.0

### Relevant log output

```sh
error: builder for '/nix/store/rh3bjhhznv03p438yph1sxmj4yp0k9gq-python3.11-ibis-framework-8.0.0.drv' failed with exit code 1;
       last 10 log lines:
       > Creating a wheel...
       > * Getting build dependencies for wheel...
       > * Building wheel...
       > Successfully built ibis_framework-8.0.0-py3-none-any.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for ibis_framework-8.0.0-py3-none-any.whl
       >   - sqlglot<=20.11,>=18.12.0 not satisfied by version 21.1.1
       For full logs, run 'nix-store -l /nix/store/rh3bjhhznv03p438yph1sxmj4yp0k9gq-python3.11-ibis-framework-8.0.0.drv'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue.

We have a fairly big release coming up and we still have a few kinks to work out. Hard to say exactly what the timeline is more specifically than "soon" :)

I hope that in the next few weeks we can cut a release.

**Comment by cpcloud** [comment]
Seems at least 9.1 is out in nixpkgs, closing.
