### ISSUE TITLE
refactor: make compilers testable without backends where possible

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#8828]
Thinking about the new compilers, and being a bit frustrated by having non-backend-needing tests, like compiler tests fail after merge, I wonder if we should split out the compilers into their own subpackage so that the compilers can be tested without being run as part of the backend test suite. This would hopefully allow us to write tests that run quickly and don't require a backend, but still hit everything up to execution.

**Comment by jcrist** [comment]
Would this include the snapshot tests (the primary culprits I run into regarding this)? If so, I'm a +100 on making this possible.

**Comment by cpcloud** [comment]
Definitely would like to include snapshots in this.

**Comment by cpcloud** [comment]
Also open to approaches that enable this without the churn, just mentioned the one in the issue description as a possible one.
