### ISSUE TITLE
bug: duckdb schema access error

### ISSUE THREAD

**Issue by lei0zhou** [ibis-project/ibis#8867]
### What happened?

```python
import ibis
import duckdb


df = ibis.memtable([("a", "int64"), ("b", "string"), ("c", "double")])


con = ibis.duckdb.connect(database="test_db.db")

con.raw_sql("CREATE SCHEMA IF NOT EXISTS test_db.test_schema;")
con.create_table(
    name="test",
    obj=df,
    database="test_db.test_schema",
    overwrite=True,
)

```
got error: CatalogException: Catalog Error: Schema with name test_db.test_schema does not exist!

### What version of ibis are you using?

9.0.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for kicking the tires on the new stuff, @lei0zhou!

I think we can make this a little more user-friendly, but for now, this will work if you remove the "test_db" part of the `database` kwarg in the `create_table` call:

```python
[ins] In [1]: import ibis
         ...: import duckdb
         ...: 
         ...: 
         ...: df = ibis.memtable([("a", "int64"), ("b", "string"), ("c", "double")])
         ...: 
         ...: 
         ...: con = ibis.duckdb.connect(database="test_db.db")
         ...: 
         ...: con.raw_sql("CREATE SCHEMA IF NOT EXISTS test_db.test_schema;")
         ...: con.create_table(
         ...:     name="test",
         ...:     obj=df,
         ...:     database="test_schema",
         ...:     overwrite=True,
         ...: )
Out[1]: 
DatabaseTable: test_schema.test
  col0 string
  col1 string

[ins] In [2]: con.list_tables()
Out[2]: ['ibis_pandas_memtable_blhyaufngvgghg642vnerchdyi']

[ins] In [3]: con.list_tables(database="test_schema")
Out[3]: ['test']
```

**Comment by lei0zhou** [comment]
thanks for responding so quickly! it is a good work-around. 

but hopefully later, it can support adding catalog name, since the `Backend.attach` is supported, there potentially are multiple catalogs.

**Comment by gforsyth** [comment]
I'm going to close this as fixed, but open a separate issue to track adding `catalog` support to backends post-9.0
