### ISSUE TITLE
feat: insert with partial data/columns

### ISSUE THREAD

**Issue by lei0zhou** [ibis-project/ibis#8873]
### Is your feature request related to a problem?

when inserting data, e.g. like the following, it will show error "BinderException: Binder Error: Column name/value mismatch for insert on diamonds: expected 2 columns but 1 values were supplied"

```python
import ibis

con = ibis.duckdb.connect()

schema = ibis.Schema({"cut": "string", "x": "string"})
diamonds = con.create_table(name="diamonds", schema=schema)
diamonds

con.insert(
    table_name="diamonds",
    obj={"cut": ["Fair", "Good", "Very Good"]},
)
```

### Describe the solution you'd like

It will be great that it can handle this, e.g. adding an option that fill other columns as null. 

### What version of ibis are you running?

9.0.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by subham-behera** [comment]
The schema for the "diamonds" table specifies two columns: "cut" and "x". However, during insertion, only one column ("cut") is provided with data, leading to the mismatch error.
To resolve this error, you need to provide values for both columns specified in the table schema.

**Comment by lostmygithubaccount** [comment]
@subham-behera is that an AI-generated comment?

@lei0zhou thanks for opening, this sounds like a reasonable request though could potentially lead to unexpected behavior. you can of course do this yourself as a workaround with something like:

```python
obj=ibis.memtable(obj).mutate(x=None)
```

adding the column of NULLs. you could also go through the schemas of two tables and add NULLs, etc.

**Comment by lostmygithubaccount** [comment]
no problem! more complete example:

```python
[ins] In [1]: import ibis

[ins] In [2]: con = ibis.connect("duckdb://")

[ins] In [3]: schema = ibis.Schema({"cut": "string", "x": "string"})

[ins] In [4]: diamonds = con.create_table(name="diamonds", schema=schema)

[ins] In [5]: data = {"cut": ["Fair", "Good", "Very Good"]}

[ins] In [6]: t = ibis.memtable(data)

[ins] In [7]: t
Out[7]:
InMemoryTable
  data:
    PandasDataFrameProxy:
               cut
      0       Fair
      1       Good
      2  Very Good

[ins] In [8]: ibis.options.interactive = True
         ...: ibis.options.repr.interactive.max_rows = 10
         ...: ibis.options.repr.interactive.max_columns = None

[ins] In [9]: t
Out[9]:
┏━━━━━━━━━━━┓
┃ cut       ┃
┡━━━━━━━━━━━┩
│ string    │
├───────────┤
│ Fair      │
│ Good      │
│ Very Good │
└───────────┘

[ins] In [10]: con.insert(table_name="diamonds", obj=t.mutate(x=None))

[ins] In [11]: t = con.table("diamonds")

[ins] In [12]: t
Out[12]:
┏━━━━━━━━━━━┳━━━━━━━━┓
┃ cut       ┃ x      ┃
┡━━━━━━━━━━━╇━━━━━━━━┩
│ string    │ string │
├───────────┼────────┤
│ Fair      │ NULL   │
│ Good      │ NULL   │
│ Very Good │ NULL   │
└───────────┴────────┘
```

**Comment by lostmygithubaccount** [comment]
this is more verbose than I expected but how you could do it programmatically, with some assumptions:

```python
[ins] In [1]: import ibis

[ins] In [2]: con = ibis.connect("duckdb://")
sch
[ins] In [3]: schema = ibis.Schema({"cut": "string", "x": "string"})

[ins] In [4]: diamonds = con.create_table(name="diamonds", schema=schema)

[ins] In [5]: data = {"cut": ["Fair", "Good", "Very Good"]}

[ins] In [6]: t = ibis.memtable(data)

[ins] In [7]: ibis.options.interactive = True

[ins] In [8]: for col in diamonds.columns:
         ...:     if col not in t.columns:
         ...:         t = t.mutate(**{col: ibis.literal(None, diamonds.schema()[col])})
         ...:

[ins] In [9]: con.insert(table_name="diamonds", obj=t)

[ins] In [10]: t = con.table("diamonds")

[ins] In [11]: t
Out[11]:
┏━━━━━━━━━━━┳━━━━━━━━┓
┃ cut       ┃ x      ┃
┡━━━━━━━━━━━╇━━━━━━━━┩
│ string    │ string │
├───────────┼────────┤
│ Fair      │ NULL   │
│ Good      │ NULL   │
│ Very Good │ NULL   │
└───────────┴────────┘
```

**Comment by lei0zhou** [comment]
thanks, that is fair, just want to point out when using sql to create a empty table and insert only a subset of columns, by default, it will add null values to those columns not in the subset.
