### ISSUE TITLE
perf(sql): regression test benchmarks

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8891]
### Is your feature request related to a problem?

In https://github.com/ibis-project/ibis/pull/8825, I was manually running a notebook to compare performance numbers on a complex query. It would be great if this was easier, or even ran on every PR

### Describe the solution you'd like

- some github action triggerend by eg `/benchmark`
- github action that runs on EVERY pr

What to use as the base? The last stable release? `main`? I would vote the last stable version.

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Going to add a smoke test benchmark that compiles the code from the original zip file.
