### ISSUE TITLE
bug(pyspark): export functions don't take param or limit

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis#8898]
### What happened?

Expect to be able to pass param or limit, as with other backends.

### What version of ibis are you using?

8

### What backend(s) are you using, if any?

PySpark

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alperentahta** [comment]
Could you please give more information, I can take this task

**Comment by deepyaman** [comment]
> Could you please give more information, I can take this task

If you look at the [`to_delta()` implementation](https://github.com/ibis-project/ibis/blob/1c7c6e3/ibis/backends/pyspark/__init__.py#L862), you'll notice that the signature doesn't take `params`, but the [base implementation](https://github.com/ibis-project/ibis/blob/1c7c6e3785900cabbf25abbea5ed8505c8391b60/ibis/backends/__init__.py#L518) does. `params` could be passed to the `compile()` call in `to_delta()`.

[This issue occurred in more places when I originally filed it](https://github.com/deepyaman/ibis/blob/feat/flink/native-parquet-and-csv-export/ibis/backends/pyspark/__init__.py#L707-L789); may just be a very minimal fix now, if anything?
