### ISSUE TITLE
docs: make numpydoc handling of kwargs consistent

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis#8899]
### Please describe the issue

From https://numpydoc.readthedocs.io/en/latest/format.html#parameters:

> When documenting variable length positional, or keyword arguments, leave the leading star(s) in front of the name:

For now, it's inconsistent, including a number of cases without star(s).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I'm going to close this out as it doesn't really impact much. Feel free to submit a PR addressing it.
