### ISSUE TITLE
feat: Define translation rule for TimestampDiff, TimeDiff and DateDiff

### ISSUE THREAD

**Issue by saschahofmann** [ibis-project/ibis#8907]
### Is your feature request related to a problem?

The operations TimestampDiff, TimeDiff, and DateDiff seem to be defined but at least in case of the BigQuery backend don't have a translation rule. For example, this
```python
import ibis
from ibis.backends import bigquery

a = ibis.timestamp('2022-01-01 20:00:00')
b = ibis.timestamp('2022-01-01 21:00:00')

bigquery.compile(b-a)
```
Leads to a `ibis.common.exceptions.OperationNotDefinedError: No translation rule for <class 'ibis.expr.operations.temporal.TimestampDiff'>` error.

### Describe the solution you'd like

I think the translation rule should simply be something like this `right.delta(left, 's')` for `TimestampDiff` and `TimeDiff` and `right.delta(left, 'd')`. for `DateDiff`. I'd be happy to implement this but would need a pointer to where the translations are defined.

### What version of ibis are you running?

8.0.0

### What backend(s) are you using, if any?

BigQuery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@saschahofmann We have the [`delta`](https://ibis-project.org/reference/expression-temporal.html#ibis.expr.types.temporal.TimestampValue.delta) method for this.

Thanks for the report!

**Comment by saschahofmann** [comment]
Wouldn't it make sense to remove the timestamp diff then?

**Comment by cpcloud** [comment]
Probably. The primary difference is that `a - b` returns an interval, and we're still deciding what to do with those.

**Comment by saschahofmann** [comment]
Not sure, I understand. Do you mean that the primary difference for subtraction for timestamps compared to other subtractions is that the type changes? Or that delta returns an integer and a-b returns a interval? Because what I tried to say above is that a-b doesn't work at all right now (at least with the bigquery backend, for postgres it seems to work).
