### ISSUE TITLE
feat: `ibis.connect("md:")` forwards to motherduck

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8922]
### Is your feature request related to a problem?

oh it just would be nice if it was clever enough to do this. Right now this crashes. Not a bit deal it's easy for me to get around it.

### What is the motivation behind your request?

connect to a db based on an environment variable.

### Describe the solution you'd like

probably every backend entrypoint needs to have a set of possible names to match against, eg duckdb, md, motherduck.

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
I'm a little confused on what you're trying to do, but you can connect to MotherDuck with `ibis.connect("duckdb://md:")` -- if you have the environment variable set for the MotherDuck API token it'll "just work"

**Comment by NickCrews** [comment]
ah, I think you are right, I think the `duckdb://` prefix should be required. This is user error on my part then.
