### ISSUE TITLE
ENH: Trigonometric functions

### ISSUE THREAD

**Issue by pteehan** [ibis-project/ibis#893]
I think there is currently no support for trigonometric functions, e.g. sin, cos, acos, atan etc, is that right?

Thank you

**Comment by wesm** [comment]
Appears not yet, want to take a shot at adding them?

**Comment by pteehan** [comment]
It will take me a while to figure out how, but I'd be happy to give it a try.  I'll be in touch.

**Comment by xmnlab** [comment]
We already make a own version for trigonometric functions:

https://github.com/Quansight/ibis/blob/master/ibis/mapd/operations.py#L565

We can move this to `ibis` operations
