### ISSUE TITLE
bug:  ibis duckdb not disconnect or close method

### ISSUE THREAD

**Issue by Liripo** [ibis-project/ibis#9045]
### What happened?

It get an error: 
```py
Ibis_con = ibis.duckdb.connect()
Ibis_con.disconnect()
```

### What version of ibis are you using?

8.0.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hi @Liripo -- this is implemented on `main` but not in 8.0.  We'll be releasing 9.0 quite soon, or you can try out a pre-release by running `python -m pip install -U --pre 'ibis-framework[duckdb]'`

**Comment by Liripo** [comment]
@gforsyth 
Thanks for such a quick reply, I don’t know if it can support the use of with syntax.
```py
with ibis.duckdb.connect() as con:
    con.creat_table('test',pd.DataFrame({"a": [1]}))
```

**Comment by gforsyth** [comment]
Hey @Liripo -- no, currently `connect` is not a context manager.  We could make that an option -- could you tell me a little bit about your use case?
