### ISSUE TITLE
Add Option to Pass psychopg2 Connection

### ISSUE THREAD

**Issue by gabeschulman** [ibis-project/ibis#9051]
### What is the motivation behind your request?

I'd like to be able to use ibis with my company's authorization pattern for our Postgres instance.

### Describe the solution you'd like

Currently I work with an auth pattern that requires SSL certificates and AWS role info to connect to an aurora Postgres database. I am able to pass connections generated using psychopg2 into methods like polars.read_database or pandas.read_sql, but for ibis I can only pass connection string params (which doesn't work for my use case). It would be great to have the option to pass a psychopg2 connection object to ibis and work with my database that way.

### What version of ibis are you running?

8.0.0

### What backend(s) are you using, if any?

Postgresql

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sidhreddy** [comment]
+1

**Comment by jcrist** [comment]
This was fixed in #9603 - as of `ibis` 9.2 you can create an ibis connection from an existing psycopg2 connection like

```python
con = ibis.postgres.from_connection(your_pg_connection)
```
