### ISSUE TITLE
bug: typing issue with `filter` method on the table column

### ISSUE THREAD

**Issue by fwojciec** [ibis-project/ibis#9108]
### What happened?

<img width="1552" alt="Screenshot 2024-05-02 at 10 25 53 AM" src="https://github.com/ibis-project/ibis/assets/1042048/1ff505ca-a560-42dc-9ab9-9a67bd602635">

Here is a repo with the reproduction of the issue on the screenshot: https://github.com/fwojciec/ibis-types-test

Legitimate uses of the `filter` method result in type errors reported by `pyright` and `pylance`. This is because the `filter` method expects the predicates to be `ir.BooleanValue | Sequence[ir.BooleanValue] | IfAnyAll` and the actual type of the predicates in the above examples is just a plain ol' `bool`.

Interestingly, the `equals` method provided by Ibis returns b `bool` for its result, which seems like an inconsistency.

I appreciate that static typing is not a priority for the project, so I'm happy to make a PR to try and fix any typing issues I come across, but I wanted to get some guidance first on how these types of issues should be addressed - in this case, is the solution basically adding `bool` as a type that's accepted by the `filter` method in addition to the internal Ibis types mentioned above? Or maybe this is just something that can be worked around by somehow casting the bool predicate into an instance of `BooleanValue`? Are there any documents/references I should look up to understand how static typing is supposed to work in Ibis?

### What version of ibis are you using?

`ibis-framework[duckdb]>=9.0.0`
specifically - on 9.0.0 right now

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Hi - thanks for opening this. Two things:

- Our type annotations aren't great. Ibis code is pretty dynamic, generally you can trust the _output_ of the method/function/whatever to be properly typed, but the types of arguments are likely stricter than things that are actually supported. In this case here `filter` is annotated to take a `BooleanValue` (which will accept a `BooleanScalar` or `BooleanColumn`), but it also will work with a standard `bool` (`ibis` will automatically coerce to a `BooleanScalar`). Going through the APIs to improve the accuracy of the type annotations and add tests to ensure they're accurate is a large project and not one we're prioritizing at the moment. Right now I recommend either submitting PRs to fix annotations for bugs that you run into, or (better, more feasible suggestion) just turn off typing for `ibis`.

- In your _specific_ case this is also a case of user error. The `.equals` method on an expression checks for expression-level equality (whether the left and right side are _identical_ expressions). `t.filter(t.a == 0)` is what you want here.

**Comment by fwojciec** [comment]
Thanks for the feedback - it all makes sense. I'm happy to close this as this is not really a bug, and I see if I can come up with a PR that addresses the specific issue here.
