### ISSUE TITLE
docs: add a technical blog on sqlglot refactor and technical details for 9.0

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#9129]
### Please describe the issue

A blog with details on what happened in 9.0.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
duplicate of https://github.com/ibis-project/ibis/issues/8889?

**Comment by cpcloud** [comment]
Yep, thanks!
