### ISSUE TITLE
bug: hash() in some backends returns a UINT64, but ops.Hash has dtype int64

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#9135]
### What happened?

```python
import ibis
ibis.options.interactive = True

t = ibis.memtable({"x": ["BATMAN"]})
t = t.mutate(y=t.x.hash())
t.cache()
```

The duckdb hash of "BATMAN" happens to be 18165473391510152529, which is a uint64 too big to fit into a int64. When we call .cache(), the backend first does a DDL to create a table, but it makes the dtype of the column int64. Then when it tries to insert, it fails of course with `Conversion Error: Type UINT64 with value 18165473391510152529 can't be cast because the value is out of range for the destination type INT64`.

postgres's hash for instance returns an int, not a uint. I assume other backends do different things.

I'm not sure what to do here: should we keep the ops.Hash always having a int64 type, and then fix duckdb's `visit_Hash()` to do some casting?

EDIT: yes, we get the right thing, and it should be pretty performant to do something like `select HASH('BATMAN')::BIT::int64;`

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
A quick low-effort survey of our implementations:

```
duckdb: uint64
clickhouse: uint64
snowflake: int64
mssql: int (doesn't say if signed or not)
bigquery: int64
spark: int64
impala: int64
oracle: uint32
```

Given this, I think coaxing to an `int64` seems fine, but we'll also probably need to do this for clickhouse too.
