### ISSUE TITLE
ENH: Support hdfs3.HDFileSystem as a valid argument to hdfs_client in ibis.impala.connect

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#918]

**Comment by wesm** [comment]
We can use `driver='libhdfs'` in the pyarrow driver also, these should be roughly API interchangeable anyway

**Comment by cpcloud** [comment]
Yeah, been working on it for the last hour or so. There are some differences in `put` that matter, e.g., the `HDFileSystem.put` API requires a path instead of something implement the file protocol.
