### ISSUE TITLE
bug: Installation issue: mamba on Windows 10

### ISSUE THREAD

**Issue by hennievn** [ibis-project/ibis#9184]
### What happened?

Not sure if the is the appropriate place for install issues, but I'll try in any case.
I'm trying to install ibis 9.0 in my conda environment (mambaforge) on Windows 10.  I see errors when running 
 ` mamba install --force-reinstall ibis-framework ibis-duckdb ibis-pandas ibis-mssql pyarrow gcsfs`

This appears to be Windows specifiec - I had no issues installing the same packages with mamba in a linux environment.

**Error messages**
The package for ibis-framework-core located at C:\Users\MYUSER\AppData\Local\mambaforge\pkgs\ibis-framework-core-9.0.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call0'
specified in the package manifest cannot be found.

The package for ibis-framework-core located at C:\Users\MYUSER\AppData\Local\mambaforge\pkgs\ibis-framework-core-9.0.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call1'
specified in the package manifest cannot be found.

The package for ibis-framework-core located at C:\Users\MYUSER\AppData\Local\mambaforge\pkgs\ibis-framework-core-9.0.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call2'
specified in the package manifest cannot be found.

The package for ibis-framework-core located at C:\Users\MYUSER\AppData\Local\mambaforge\pkgs\ibis-framework-core-9.0.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call3'
specified in the package manifest cannot be found.

CondaVerificationError: The package for ibis-framework-core located at C:\Users\MYUSER\AppData\Local\mambaforge\pkgs\ibis-framework-core-9.0.0-p0
appears to be corrupted. The path 'site-packages/ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call0'
specified in the package manifest cannot be found.

CondaVerificationError: The package for ibis-framework-core located at C:\Users\MYUSER\AppData\Local\mambaforge\pkgs\ibis-framework-core-9.0.0-p0
appears to be corrupted. The path 'site-packages/ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call1'
specified in the package manifest cannot be found.

CondaVerificationError: The package for ibis-framework-core located at C:\Users\MYUSER\AppData\Local\mambaforge\pkgs\ibis-framework-core-9.0.0-p0
appears to be corrupted. The path 'site-packages/ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call2'
specified in the package manifest cannot be found.

CondaVerificationError: The package for ibis-framework-core located at C:\Users\MYUSER\AppData\Local\mambaforge\pkgs\ibis-framework-core-9.0.0-p0
appears to be corrupted. The path 'site-packages/ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call3'
specified in the package manifest cannot be found.

### What version of ibis are you using?

9.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
hi @hennievn

> Not sure if the is the appropriate place for install issues, but I'll try in any case.

this is the appropriate place, thanks for opening! we might be a bit slow to address this given much of the team is at PyCon this week and I'm not sure any of the core maintainers work on windows

**Comment by gforsyth** [comment]
Hey @hennievn -- thanks for reporting!  I'm going to try rebuilding our conda packages but without even including the snapshot tests results, since it is very unclear to me why they're causing those errors.

**Comment by hennievn** [comment]
@gforsyth Let me also add that there was a similar issue with the 8.0 release.  I did not pay enough attention to know if it was the same issue, I simply used pip to work around.  As the 9.0 error subjectively felt the same, I thought its' probably time to see if it can be addressed.

**Comment by gforsyth** [comment]
Thanks for the info, @hennievn -- can you try reinstalling it now and see if the issue is resolved?  We've removed those snapshot files from the conda packages.

**Comment by hennievn** [comment]
@gforsyth Yes, this solves the problem.  Install is now OK and a few simple examples runs OK.  Thanks for the quick response!

**Comment by gforsyth** [comment]
Great!  Thanks for confirming!
