### ISSUE TITLE
`collect` does not respect order

### ISSUE THREAD

**Issue by efcaguab** [ibis-project/ibis#9187]
### What happened?

I expect collect to respect the order of the rows when supported by the backend. In the example below, I want to put the contents of `bar` into an array. I also want the order of the items in the array to be determined by column `n`

```python
import ibis
con=ibis.duckdb.connect()
dummy_table = con.create_table(
    "dummy_table",
    [
        {"foo": 1, "bar": 2, "n": 10},
        {"foo": 1, "bar": 1, "n": 20},
        {"foo": 1, "bar": 3, "n": 1},
    ]
)

with_ibis = (
    dummy_table.group_by("foo")
    .order_by(ibis.desc("n"))
    .aggregate(bar=ibis._.bar.collect())
)

with_duckdb = (
    con.sql(
        """
        SELECT foo, LIST(bar ORDER BY n DESC) AS bar
        FROM dummy_table
        GROUP BY 1
        """
    )
)
```

With ibis the order or the array is non-dererministic, often `[2, 1, 3]`, with duckdb the order is as expected `[1, 2, 3]`.

### What version of ibis are you using?

9.0.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
`order_by` doesn't transmit into `collect` - the `order_by` as you've specified is for the ordering of the rows in the subquery before. What you're looking for is #9170, which hasn't been implemented yet (but is something we plan to handle soon). For now unfortunately you'll have to make due with using `con.sql` to express this functionality.

**Comment by efcaguab** [comment]
Fantastic thanks for the clarification!
