### ISSUE TITLE
bug: names_sort argument in table.pivot_wider has no effect

### ISSUE THREAD

**Issue by contang0** [ibis-project/ibis#9203]
### What happened?

I'm using Table.pivot_wider to unstack rows into columns. pivot_wider has an argument names_sort, which is False by default. However, setting it True doesn't seem to have any effect. 

Here's an example to reproduce and the outputs. I expected the following sorting order after setting names_sort=True: 
col1_T1, col1_T2, col2_T1, col2_T2.

`        

        import ibis
        con = ibis.duckdb.connect(":memory:")

        data = pd.DataFrame(
            {
                "unique_id": ["A", "A", "B", "B"],
                "secondary_id": [
                    "T1",
                    "T2",
                    "T1",
                    "T2",
                ],
                "col1": ["x1", "x2", "x3", "x4"],
                "col2": ["y1", "y2", "y3", "y4"],
            }
        )

        tbl = ibis.memtable(data)
        
![image](https://github.com/ibis-project/ibis/assets/10067941/62fc0273-5ee4-462a-bcd9-d9ba52d46755)

        tbl.pivot_wider(
            id_cols=["unique_id"],
            names_from=["secondary_id"],
            values_from=["col1", "col2"],
            names_sort=False,
        )
        
        
![image](https://github.com/ibis-project/ibis/assets/10067941/03aa4b2e-eb4a-41ad-b104-b43de021879b)

        tbl.pivot_wider(
            id_cols=["unique_id"],
            names_from=["secondary_id"],
            values_from=["col1", "col2"],
            names_sort=True,
        )`

![image](https://github.com/ibis-project/ibis/assets/10067941/d0e85a34-6ab8-4ebd-8795-ad4091dae0a6)

### What version of ibis are you using?

9.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @contang0 -- it has an effect, but the names column you've given it is already sorted (taking into account that we only need a set of column names.

```python
[ins] In [1]: import ibis
         ...: import pandas as pd
         ...: 
         ...: ibis.options.interactive = True
         ...: 
         ...: con = ibis.duckdb.connect(":memory:")
         ...: 
         ...: data = pd.DataFrame(
         ...:     {
         ...:         "unique_id": ["A", "A", "B", "B"],
         ...:         "secondary_id": [
         ...:             "T2",
         ...:             "T2",
         ...:             "T1",
         ...:             "T1",
         ...:         ],
         ...:         "col1": ["x1", "x2", "x3", "x4"],
         ...:         "col2": ["y1", "y2", "y3", "y4"],
         ...:     }
         ...: )
         ...: 
         ...: tbl = ibis.memtable(data)

[ins] In [2]: tbl.pivot_wider(
         ...:     id_cols=["unique_id"],
         ...:     names_from=["secondary_id"],
         ...:     values_from=["col1", "col2"],
         ...:     names_sort=False,
         ...: )
Out[2]: 
┏━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┓
┃ unique_id ┃ col1_T2 ┃ col2_T2 ┃ col1_T1 ┃ col2_T1 ┃
┡━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━┩
│ string    │ string  │ string  │ string  │ string  │
├───────────┼─────────┼─────────┼─────────┼─────────┤
│ A         │ x1      │ y1      │ NULL    │ NULL    │
│ B         │ NULL    │ NULL    │ x3      │ y3      │
└───────────┴─────────┴─────────┴─────────┴─────────┘

[ins] In [3]: tbl.pivot_wider(
         ...:     id_cols=["unique_id"],
         ...:     names_from=["secondary_id"],
         ...:     values_from=["col1", "col2"],
         ...:     names_sort=True,
         ...: )
Out[3]: 
┏━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┓
┃ unique_id ┃ col1_T1 ┃ col2_T1 ┃ col1_T2 ┃ col2_T2 ┃
┡━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━┩
│ string    │ string  │ string  │ string  │ string  │
├───────────┼─────────┼─────────┼─────────┼─────────┤
│ A         │ NULL    │ NULL    │ x1      │ y1      │
│ B         │ x3      │ y3      │ NULL    │ NULL    │
└───────────┴─────────┴─────────┴─────────┴─────────┘
```
