### ISSUE TITLE
ENH: Add method to Argument types to create a copy with a new argument name

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#923]
This will require some refactoring to enable arguments to copy themselves (with a new name), but would be nice to be able to have

```
ARG = rules.{...}

input_type = [ARG.name('foo'), ...]
```

**Comment by kszucs** [comment]
@cpcloud 0.14?

**Comment by cpcloud** [comment]
Closing for now. This isn't high priority enough to keep getting pushed to the next release.
