### ISSUE TITLE
Polars backend can read only 1 csv 

### ISSUE THREAD

**Issue by djouallah** [ibis-project/ibis#9230]
### Is your feature request related to a problem?

Polars can read multiple files at the same time but in ibis, it can read only 1 file at the time which is not practical
https://ibis-project.org/backends/polars#ibis.backends.polars.Backend.read_csv

### Describe the solution you'd like

I would like ibis when using polars backend to be able to do this

ibis.read_csv(['file1,csv','file2.csv'])

### What version of ibis are you running?

10.0.0.dev71

### What backend(s) are you using, if any?

Polars

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for the issue, @djouallah !  We use `pl.scan_csv` to keep things lazy and they didn't used to support multiple files, but now that they do, this should be relatively straightforward to add.
