### ISSUE TITLE
bug: .insert() uses column position, not names, to align

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#9249]
### What happened?

When I insert new data, I expect the columns to get aligned by name. But we seem to be naive, and not ensure the src and dst schemas are in the same order, and thus we get the default SQL behavior of data being aligned by position:

```python
import ibis

ibis.options.interactive = True

db = ibis.duckdb.connect()
db.create_table("t", [{"a": 1, "b": 2}])
db.insert("t", [{"b": 22, "a": 11}])
db.table("t")
# ┏━━━━━━━┳━━━━━━━┓
# ┃ a     ┃ b     ┃
# ┡━━━━━━━╇━━━━━━━┩
# │ int64 │ int64 │
# ├───────┼───────┤
# │     1 │     2 │
# │    22 │    11 │
# └───────┴───────┘
```

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb, but I bet this is present in other backends too.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Nice catch, @NickCrews -- I've got a reasonably straightforward fix for this.
