### ISSUE TITLE
Revisit Impala's CASE expression type precedence rules

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#93]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Friday Jan 30, 2015 at 22:37 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/93_

---

see #31

**Comment by cpcloud** [comment]
The postgres algorithm for deciding the output type looks reasonable here: https://www.postgresql.org/docs/current/static/typeconv-union-case.html

**Comment by kszucs** [comment]
@cpcloud This issue seems a bit outdated, should we still revisit?

**Comment by cpcloud** [comment]
This is really a backlog issue, that we may or may not get to after other higher priority issues are done. We can still leave it open though.

**Comment by cpcloud** [comment]
@xmnlab This looks like a bug since the types you've written in your example are perfectly valid.

**Comment by cpcloud** [comment]
I'm going to move your example to a separate issue.

**Comment by cpcloud** [comment]
Closing as stale.
