### ISSUE TITLE
refactor: remove ibis.NA 

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#9311]
Opening an issue to discuss a separate the refactor of `ibis.NA` because doing it as part of https://github.com/ibis-project/ibis/pull/9300 will get messy. 

To discuss:
Does removing `ibis.NA`imply:

1. Replace `ibis.NA` for `ibis.null()`
2. Get rid of untyped nulls all together, as in not use `ibis.null()` but just None

**Comment by jcrist** [comment]
Another option is to rename it to `ibis.NULL`, but I'd vote for option 1.

I'm not really sure what option 2 means - in _many_ cases APIs that accept `None` should implicitly coerce it to a literal `NULL`, but not in all cases. There will always cases where calling `ibis.null()` (or `ibis.literal(None)`, which is the same thing) will be necessary or more ergonomic.

**Comment by cpcloud** [comment]
I don't think can we remove `ibis.null()`, it accepts a dtype and can create a typed null which is necessary and/or useful in some cases.

I would vote for the following:

1. Remove NA
2. Don't add NULL
3. Use `None` wherever _untyped_ NULLs previously worked.

`ibis.null(...)` remains unchanged.

**Comment by cpcloud** [comment]
As far implementation goes, we can basically search and replace `ibis.NA` with `ibis.null()`. If folks want an untyped NULL, that's `None` (after these changes).

**Comment by ncclementi** [comment]
For implementation purposes, do we want to deprecate `ibis.NA`or remove it as a breaking change. If it's a deprecation, how do we deprecate `ibis.NA = null()` the `@deprecated` seems to only work for methods/functions.
