### ISSUE TITLE
bug: `.collect()` handling of null values is backend-specific

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#9313]
The null handling behavior of `.collect()` is currently backend specific.

The `collect` method is an aggregation that returns an array of all items in the group. The difference in behavior here is what happens with `NULL` elements:

### Null behavior is configurable
- `bigquery`

### Nulls always excluded
- `clickhouse`
- `pyspark`
- `snowflake`

### Nulls included, but may be excluded with an extra filter
- `datafusion`
- `duckdb`
- `postgres`
- `risingwave`
- `trino`

Currently we just do whatever the backend does (except for `snowflake`, where there's a hacky hacky hack to keep nulls).

Since some backends have no way to include nulls (and most other aggregates exclude them), I'd vote to change the behavior in ibis to exclude nulls from `collect()` to unify this behavior across backends.

**Comment by jcrist** [comment]
An alternative would be to add an `ignore_nulls` kwarg (defaulting to `True` perhaps, since that's the only uniform behavior?) to make this configurable.

**Comment by cpcloud** [comment]
+1 to excluding `NULL`s. This is also consistent with I think most or every other aggregation function.

**Comment by cpcloud** [comment]
Somewhat related: I'm working on `ignore_nulls` for window functions to unblock a much less verbose way of implementing `ffill`/`bfill` (no group by required for example).
