### ISSUE TITLE
feat: Unsuccessfully tried to mimic "unbounded" column behavior, as `pyspark` API allows

### ISSUE THREAD

**Issue by filipeo2-mck** [ibis-project/ibis#9328]
### Is your feature request related to a problem?

I'm trying to create columns with `ibis` and managing them independently from an existing `ibis` Table, as I can do with `pyspark` but I'm not being succesfull. I couldn't figure out how to do it from the docs, happy if you can enlighten me :)

### What is the motivation behind your request?

In `pyspark` programming model we can create an independent column (not attached to any table containing just an expression and an alias) by using:
```py
def create_col_from_a_random_expr(expr: str, new_col_name: str)
    # Create a pyspark column (independently from which table it will be later attached to) and return it
    return f.expr(expr).alias(new_col_name)  # create an object of type `pyspark.sql.types.Column`
```

This column above can be added for downstream table projections:
```py
new_col_A: Column = create_col_from_a_random_expr("col_a + col_b", "col_aplusb")
new_col_B: Column = create_col_from_a_random_expr("col_c + col_d", "col_cplusd")

my_df = my_df.select("*", new_col_A, new_col_B)
```
----------

I'm trying to mimic this behavior using `ibis` and tried some approaches:
1. I was not able to create/instantiate an independent `Column` object that is not bounded to an existing table. `ibis` has the concept of [unbounded tables](https://ibis-project.org/how-to/extending/unbound_expression#unbound-tables) using object-based API but no docs about "unbounded columns" (like the `pyspark.sql.functions.expr()` above)
2. I tried using plain SQL to solve it too, by creating a new table that is derived from an existing `penguins` table, extracting a "pure" column object from it and later projecting it again from the original `penguins` table:
    ```py
    # Receive a dataframe from function input
    penguins_df.alias("penguins")
    .sql(f"SELECT {my_exp} as {my_col}  FROM penguins") # -> Returns a new table `ibis.expr.types.relations.Table`, getting its MRO gives us:

    # [ibis.expr.types.relations.Table,
    #  ibis.expr.types.core.Expr,
    #  ibis.common.bases.Immutable,
    #  ibis.common.typing.Coercible,
    #  ibis.common.bases.Abstract,
    #  ibis.expr.types.core._FixedTextJupyterMixin,
    #  rich.jupyter.JupyterMixin,
    #  object]
    ```

    To get such **Column** object, we need to extract it by specifying the column . If we return it's MRO we get:
    ```py
    type(penguins_tmp["test"]).mro()
    # [ibis.expr.types.numeric.FloatingColumn,
    #  ibis.expr.types.numeric.NumericColumn,
    #  ibis.expr.types.generic.Column,
    #  ibis.expr.types.numeric.FloatingValue,
    #  ibis.expr.types.numeric.NumericValue,
    #  ibis.expr.types.generic.Value,
    #  ibis.expr.types.core.Expr,
    #  ibis.common.bases.Immutable,
    #  ibis.common.typing.Coercible,
    #  ibis.common.bases.Abstract,
    #  ibis.expr.types.core._FixedTextJupyterMixin,
    #  rich.jupyter.JupyterMixin,
    #  object]
    ```

    Using above approach to extract a **Column** object using the snippet below:
    ```py
    def test():
        my_col = "test"
        my_exp = "bill_length_mm / bill_depth_mm"
        penguins_tmp = penguins_df.alias("penguins").sql(f"SELECT {my_exp} as {my_col} from penguins")
        return penguins_tmp["test"]  # Returns a `FloatingColumn` object

    my_cols_dict = {
        "test": test()
    }
    type(my_cols_dict["test"])  # Gives us ibis.expr.types.numeric.FloatingColumn

    penguins.select("species", "island", my_cols_dict["test"])
    ```

    It gives us:
    ```txt
    IntegrityError: Cannot add <ibis.expr.operations.relations.Field object at 0x15b549d80> to projection, they belong to another relation
    ```

**My conclusion to this:** it looks like this "dettached"/"unbounded" approach that is possible in `pyspark` cannot be reproduced in `ibis`.

> Note that: the issue is not about the lack of a corresponding `pyspark.sql.functions.expr()` function (just used as an example, and I couldn't find a corresponding one in `ibis` but this is another issue) but about the creation of independent `Column` objects to be used in downstream projections. Lots of `pyspark.sql.functions.*` return new independent columns that can be later used in dataframe projections.

### Describe the solution you'd like

I would like to be able to instantiate pure `ibis.expr.types.generic.Column` from scratch, move it around and reuse it as many times as I want.

### What version of ibis are you running?

9.0.0

### What backend(s) are you using, if any?

`pyspark`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepyaman** [comment]
I think this is very similar to #8304. However, looking at the discussion/code there, it seems `_ensure_expr` has since been removed.

**Comment by cpcloud** [comment]
What's the specific use case other than that pyspark allows it and why can't it be done with existing functionality?

**Comment by deepyaman** [comment]
@filipeo2-mck You're correct that there's no such thing as an unbounded column.

However, something like this will work:

```pycon
>>> def test(t):
...     return (t.bill_length_mm / t.bill_depth_mm).name("test")
... 
>>> my_cols_dict = {
...     "test": test(_)
... }
>>> type(my_cols_dict["test"])
<class 'ibis.common.deferred.Deferred'>
>>> penguins.select("species", "island", my_cols_dict["test"])
r0 := DatabaseTable: penguins
  species           string
  island            string
  bill_length_mm    float64
  bill_depth_mm     float64
  flipper_length_mm int64
  body_mass_g       int64
  sex               string
  year              int64

Project[r0]
  species: r0.species
  island:  r0.island
  test:    r0.bill_length_mm / r0.bill_depth_mm
>>> penguins.select("species", "island", my_cols_dict["test"]).execute()
       species     island      test
0       Adelie  Torgersen  2.090909
1       Adelie  Torgersen  2.270115
2       Adelie  Torgersen  2.238889
3       Adelie  Torgersen       NaN
4       Adelie  Torgersen  1.901554
..         ...        ...       ...
339  Chinstrap      Dream  2.818182
340  Chinstrap      Dream  2.403315
341  Chinstrap      Dream  2.725275
342  Chinstrap      Dream  2.673684
343  Chinstrap      Dream  2.684492

[344 rows x 3 columns]
```

This leverages the deferred expression API, better explained on https://ibis-project.org/how-to/analytics/chain_expressions.

You can also do:

```pycon
>>> my_cols_dict = {
...     "test": test(penguins)
... }
>>> penguins.select("species", "island", my_cols_dict["test"]).execute()
       species     island      test
0       Adelie  Torgersen  2.090909
1       Adelie  Torgersen  2.270115
2       Adelie  Torgersen  2.238889
3       Adelie  Torgersen       NaN
4       Adelie  Torgersen  1.901554
..         ...        ...       ...
339  Chinstrap      Dream  2.818182
340  Chinstrap      Dream  2.403315
341  Chinstrap      Dream  2.725275
342  Chinstrap      Dream  2.673684
343  Chinstrap      Dream  2.684492

[344 rows x 3 columns]
```

I think you want the first option, given you want to be able to apply it without knowing the parent table upfront.

As to more reasons why some of the things you tried may not work, `.sql()` specifically is a black box, where we can't guarantee the number of columns will even remain the same. Further, aliasing the table is basically creating a new table, which is why you get the `IntegrityError`.

Echoing @cpcloud, what is the exact use case, and will this help? If you do specifically have strings, maybe you'll have to use some `eval` (`ast.literal_eval`?) magic to bridge the gap.

**Comment by filipeo2-mck** [comment]
Thank you for the explanation, I'll discuss this approach with my team today :)

About my use case, I'm experimenting the conversion of an existing functionality from `pyspark` to `ibis`, where the `pyspark.sql.functions.expr(string)` and it's column creation as a result is possible.
This issue covers specifically the column creation and I also had the idea of trying `literal_eval()` for the `expr(string)` too 👍

**Comment by filipeo2-mck** [comment]
Hello, @deepyaman ,

Your suggested approach above works fine, tks for this. I believe this issue can be closed, as we have some kind of workaround for it 👍 

I played a little with `literal_eval()`/`eval()` when trying to replace `pyspark.sql.functions.expr()` (as you suggested too) and it turns out that after python 3.7, [operations like additions or subtractions in `literal_eval()` are not permitted anymore](https://github.com/python/cpython/pull/4035/files) (discussion [link](https://github.com/python/cpython/issues/75959)) so it's not possible to evaluate common expressions and a `# ValueError: malformed node or string on line 1: <ast.BinOp object at 0x...>` is returned instead:
```py
literal_eval("penguins.bill_length_mm + penguins.bill_depth_mm")
```
```txt
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[69], line 1
----> 1 literal_eval("penguins.bill_length_mm + penguins.bill_depth_mm")

File ~/lib/python3.10/ast.py:110, in literal_eval(node_or_string)
    108                 return left - right
    109     return _convert_signed_num(node)
--> 110 return _convert(node_or_string)

File ~/lib/python3.10/ast.py:102, in literal_eval.<locals>._convert(node)
     99     return dict(zip(map(_convert, node.keys),
    100                     map(_convert, node.values)))
    101 elif isinstance(node, BinOp) and isinstance(node.op, (Add, Sub)):
--> 102     left = _convert_signed_num(node.left)
    103     right = _convert_num(node.right)
    104     if isinstance(left, (int, float)) and isinstance(right, complex):

File ~/lib/python3.10/ast.py:83, in literal_eval.<locals>._convert_signed_num(node)
     81     else:
     82         return - operand
---> 83 return _convert_num(node)

File ~/lib/python3.10/ast.py:74, in literal_eval.<locals>._convert_num(node)
     72 def _convert_num(node):
     73     if not isinstance(node, Constant) or type(node.value) not in (int, float, complex):
---> 74         _raise_malformed_node(node)
     75     return node.value

File ~/lib/python3.10/ast.py:71, in literal_eval.<locals>._raise_malformed_node(node)
     69 if lno := getattr(node, 'lineno', None):
     70     msg += f' on line {lno}'
---> 71 raise ValueError(msg + f': {node!r}')

ValueError: malformed node or string on line 1: <ast.Attribute object at 0x1772e8a90>
```

Another option would be to use a plain `eval()`, which works but is insecure:
```py
from ast import literal_eval

def literal_eval_wo_table(expression):
    parsed_expression = literal_eval(expression)
    return (parsed_expression).name("literal_eval_wo_table")

def eval_wo_table(expression):
    parsed_expression = eval(expression)  # insecure
    return (parsed_expression).name("eval_wo_table")

penguins.select(
    "species",
    # literal_eval_wo_table("_.bill_length_mm + _.bill_depth_mm"),  # ValueError: malformed node or string on line 1: <ast.BinOp object at 0x...>
    eval_wo_table("_.bill_length_mm + _.bill_depth_mm"),  # insecure!
)
```
```txt
┏━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ species ┃ eval_wo_table ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ string  │ float64       │
├─────────┼───────────────┤
│ Adelie  │          57.8 │
│ Adelie  │          56.9 │
│ Adelie  │          58.3 │
│ Adelie  │          NULL │
│ Adelie  │          56.0 │
│ Adelie  │          59.9 │
│ Adelie  │          56.7 │
│ Adelie  │          58.8 │
│ Adelie  │          52.2 │
│ Adelie  │          62.2 │
│ …       │             … │
└─────────┴───────────────┘
```

**Comment by deepyaman** [comment]
> I played a little with `literal_eval()`/`eval()` when trying to replace `pyspark.sql.functions.expr()` (as you suggested too) and it turns out that after python 3.7, [operations like additions or subtractions in `literal_eval()` are not permitted anymore](https://github.com/python/cpython/pull/4035/files) (discussion [link](https://github.com/python/cpython/issues/75959)) so it's not possible to evaluate common expressions and a `# ValueError: malformed node or string on line 1: <ast.BinOp object at 0x...>` is returned instead:

Ah, makes sense; `literal_eval` wouldn't know enough about other types. At the point you're executing more arbitrary logic like this, I suppose you're already living live on the edge, and may accept some of the dangers of `eval`ing. :joy:

> Your suggested approach above works fine, tks for this. I believe this issue can be closed, as we have some kind of workaround for it 👍

Will do!
