### ISSUE TITLE
Omission of data frame origins of S and R 

### ISSUE THREAD

**Issue by JosiahParry** [ibis-project/ibis#9336]
https://github.com/ibis-project/ibis/blob/aeb4e9d1974e1feae869f8005ac027f22703d167/docs/presentations/overview.qmd#L376-L379

This slide of the data frame history is a bit revisionist and omits the deep history of data frames that first started in S then in R. [Statistical Models in S](https://archive.org/details/statisticalmodel00john/page/n11/mode/2up) by John Chambers has a chapter dedicated to data frames. This was published in 1992 and they were added to S in 1991. R, as (previously) 100% compatible with S, inherited this functionality in 1992 when it was first published.

In a recent interview [Why he created Pandas, the future of data systems, why he left his CTO role to become a chief architect](https://open.spotify.com/episode/0DQCsNZuaB7cyWWp3pksSs?si=e3b4468ac0124838) (that was a mouthful!), Wes McKinney notes the following about the creation of pandas: 

"[Python is] missing some data analysis tools like the kind of things that I had seen—some of my colleagues programmed in R—and so I wanted to have some of the same kinds of tools in Python that I saw in R."

This alludes to the impact of the data frame implementation in S —and thus R—that he saw was so valuable for analysis. 

Perhaps you can prepend the following?

```
- **S** (1991) data.frame object introduced
- **R** (1992) is released with data.frame support
```

**Comment by JosiahParry** [comment]
[As noted on twitter](https://x.com/gshotwell/status/1799785112701374534), it may make sense to actually _remove_ `dplyr` from this list as it does not introduce any data frames itself. Rather, dplyr is a library for manipulating data frames based on the earlier plyr R package.

**Comment by cpcloud** [comment]
If you're up for submitting a PR, this would be a welcome addition!

**Comment by lostmygithubaccount** [comment]
given I wrote this slide for some context:

- there is a mention of S -> R above: https://github.com/ibis-project/ibis/blob/aeb4e9d1974e1feae869f8005ac027f22703d167/docs/presentations/overview.qmd#L202-L210
- this slide IMO should probably be "Python dataframe history" and remove dplyr -- I included it to draw the comparison to Ibis but that can be verbalized when presenting it

the only source for the S/R thing I've seen is https://towardsdatascience.com/preventing-the-death-of-the-dataframe-8bca1c0f83c8?gi=cae534547339, it you're down to add more on the history +1 on a PR! thanks for raising this
