### ISSUE TITLE
feat: support read_parquet for ms sql backend

### ISSUE THREAD

**Issue by ruiyang2015** [ibis-project/ibis#9357]
### Is your feature request related to a problem?

getting this error:
NotImplementedError: mssql does not support direct registration of parquet data.

did not find any documentation for this feature not supported for ms sql,

### What is the motivation behind your request?

i am trying to use ibis as a generic interface for different backend, and need use it to load parquet file to various backend. But encounter this error for ms sql.

### Describe the solution you'd like

ibis implement this feature.

### What version of ibis are you running?

9.0.0

### What backend(s) are you using, if any?

mssql

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@ruiyang2015 This would be interesting! I think we're unlikely to add support for this without an ADBC driver, given how horribly slow it would be otherwise.

**Comment by jcrist** [comment]
Closing this in favor of the broader #9448.
