### ISSUE TITLE
Poor performance when writing deltalake

### ISSUE THREAD

**Issue by djouallah** [ibis-project/ibis#9408]
### What happened?

I am comparing the performance of some Python Engines for an ETL scenario, Ibis performs is very problematic, I attached a reproducible example, the data is stored in Fabric Onelake and run using a single node spark notebook
https://github.com/djouallah/Light_ETL_Challenge/blob/main/Light_ETL_Challenge.ipynb

### What version of ibis are you using?

ibis_framework-9.1.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhenzhongxu** [comment]
@djouallah thanks for reporting this. we are looking into it and will get back to you shortly.

**Comment by cpcloud** [comment]
Changed the title to reflect the actual problem here. The difference in performance between duckdb native and Ibis is reducible to the `to_delta` call.

The `to_delta` method uses record batches which appear to be anywhere from 2-5x slower depending on which `engine` is passed to `write_deltalake`.

I'll open up an issue on the DuckDB tracker about this.

**Comment by djouallah** [comment]
it is not, I  changed the code to use arrow table and it is still 2 x slower than duckdb

**Comment by cpcloud** [comment]
I don't see this locally.

![image](https://github.com/ibis-project/ibis/assets/417981/c800cf31-09e7-4efa-8c51-b2316c2d546a)

Did you run this multiple times and take the minimum duration?

**Comment by cpcloud** [comment]
You should also change that loop over ibis columns to happen in a single call

```python
DUNIT = DUNIT.cast({col_name: "double" for col_name in df_cols})
```

instead of

```python
for col_name in df_cols:
    DUNIT = DUNIT.cast({col_name: "double"})
```

There's some overhead to the latter, but it should be in the range of 10-15%, not 100% 😅

**Comment by djouallah** [comment]
I suspect the spark runtime is doing something here !!

**Comment by cpcloud** [comment]
I don't think Spark is involved at all in the comparison between DuckDB and Ibis, unless I'm missing something.

**Comment by djouallah** [comment]
turn out the issue is with ipython, run it with version 1.3 and the performance is nearly the same as duckdb

<img width="722" alt="image" src="https://github.com/ibis-project/ibis/assets/12554469/c694814e-27a2-469b-8bf8-5ddae8e5e568">


https://learn.microsoft.com/en-us/fabric/data-engineering/runtime-1-3

**Comment by cpcloud** [comment]
Going to close this out, thanks all!
