### ISSUE TITLE
Problem of authentication with JWTAuthentication and Trino

### ISSUE THREAD

**Issue by ThomasDelorme** [ibis-project/ibis#9409]
While trying to execute this code:
```Python
import google.auth
import ibis
from google.auth.transport.requests import Request
from trino.auth import JWTAuthentication
from trino.dbapi import connect

credentials, project_id = google.auth.default()
credentials.refresh(Request())

con = ibis.trino.connect(
    user="me",
    auth=JWTAuthentication(credentials.token),
    http_scheme="https",
    host="https://ur.l",
    port="8000",
    database="my_catalog",
    schema="my_schema",
)
con.list_databases()
```

I am getting the following error:
TypeError: trino.dbapi.connect() got multiple values for keyword argument 'auth'

The same code is working without any issue in order to connect directly to trinodb.

The issue is coming from the following line, duplicating the auth parameters that is coming both from the **kwargs and from the auth=password,:
https://github.com/ibis-project/ibis/blob/bdc1b3fbb8d44f9246c957b58372d3df84247468/ibis/backends/trino/__init__.py#L303

In order to fix this problem, the following code is working:
```Python
con = ibis.trino.connect(
    user="me",
    password=JWTAuthentication(credentials.token),
    http_scheme="https",
    host="https://ur.l",
    port="8000",
    database="my_catalog",
    schema="my_schema",
)
```

I would then suggest to:
- either add logic to not duplicate the auth parameters if already in the **kwargs
- I don't know if the issue is the same with https://ibis-project.org/backends/trino#authenticating-with-sso, but if it is, updating the documentation to an actually working code, or adding a new parts dedicated to JWTAuthentication.

Thanks! :smile:

**Comment by cpcloud** [comment]
Thanks for the report, definitely a problem :)
