### ISSUE TITLE
bug: duplicate column names in filters leads to error

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#9474]
### What happened?

```python
import ibis

t = ibis.examples.penguins.fetch()
t.filter(
    t.species == "Adelie",
    t.species == "Adelie",
)
# IbisInputError: Duplicate column name "Equals(species, 'Adelie')" in result set
```
Since neither of these columns are actually in the result set, I would expect this to work.

OK, I admit this is a bit of a contrived example, but there are instances where different expressions have the same name, which is how I actually ran into this bug:

```python
t.filter(
    t.island.fill_null("") == "Adelie",
    t.species.fill_null("") == "Adelie",
)
# IbisInputError: Duplicate column name "Equals(Coalesce(), 'Adelie')" in result set
```

perhaps that is just a bug with coalesce though? We should make them have different names?

I think the "pure" solution would be to do some renaming of these temporary columns on the fly inside .filter(), but that might be really hairy, so an easier mitigation would be just to stamp out instances where different expressions map to the same name.

### What version of ibis are you using?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
> I think the "pure" solution would be to do some renaming of these temporary columns on the fly inside .filter()

I don't think so. I think we might want to instead relax whatever constraint is enforcing this, but **only** inside `filter`. Best to look into what's happening before we speculate on solutions though :)

**Comment by cpcloud** [comment]
I think the expression naming collision in this case is also an issue, as the same problem shows up in a `select` invocation.
