### ISSUE TITLE
bug: MSSQL create_table with pandas dataframe leaves a lot ibis_panda table around

### ISSUE THREAD

**Issue by ruiyang2015** [ibis-project/ibis#9475]
### What happened?

using following code:
```
c = ibis.mssql.connect(...)
df = pd.DataFrame.from_dict({'val': [1, 2, 3]})
c.create_table('t', df)
c.list_tables()
```
after the table creation, in addition to the table t being created, there is also a table with 
ibis_pandas_memtable_s2xlcq5anjg5tlyy5i5y4zan7q 
and not get cleaned up

### What version of ibis are you using?

9.0.0

### What backend(s) are you using, if any?

MSSQL

### Relevant log output

```sh
no error logs, just check the tables after create_table calls
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hi @ruiyang2015 !  This is fixed in the 9.1 release.  Thanks for flagging!
