### ISSUE TITLE
feat:  Install ibis-framework[postgres] without requiring the 'pg_config' file

### ISSUE THREAD

**Issue by a92340a** [ibis-project/ibis#9479]
### Is your feature request related to a problem?

Hi developers, I tried to install package ibis-framework[postgres]' on my host machine(MacOS, with M1 silicon), but there's an error message shown "pg_config executable not found." 
I guessed this issue caused by no PostgreSQL installed on my host machine, therefore there is no "pg_config" in my host machine. However, I wanted to run PostgreSQL on Docker container, not on my host. 
I tried to fix this problem, but no found any helpful suggestion on the community. I'd like to know if it's possible to install ibis-framework[postgres]' but no required "pg_config" file? For example, replacing psycopg2 with psycopg2-binary or any possible option to deal with this?
Very appreciated! 
<img width="1116" alt="image" src="https://github.com/ibis-project/ibis/assets/30499702/fc8e40df-5970-4f19-b6fe-3bd2a9a952c7">

### Describe the solution you'd like

I'd like to know if it's possible to install ibis-framework[postgres]' but no required "pg_config" file? For example, replacing psycopg2 with psycopg2-binary or any possible option to deal with this?

### What version of ibis are you running?

1.8.3

### What backend(s) are you using, if any?

PostgreSQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @a92340a!

You should be able to manually set up use of Ibis with the postgres backend and `psycopg2-binary` like this:

```
$ pip install ibis-framework psycopg2-binary
```

Note that I am **not** specifying the `[postgres]` extra.

Closing this out, as it's not really an Ibis issue, but an issue with one of our dependencies!
