### ISSUE TITLE
feat: add `how="positional"` to `Table.join()`

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#9486]
This came up in https://github.com/ibis-project/ibis/issues/9324.

Originally the proposal was for a ibis.hconcat() function that does this for us. But I think we can and should keep everything related to "merging two different relations" in a single place. IDK, are there other methods of merging/joining tables together?

duckdb has this built in. Pandas and dask also would be trivial. Other backends we can add a `ibis.row_number()` column to both relations, then joining on that.

IDK how to handle if the tables are different lengths:
- I would say, ideally, we should require them to be the same length.
- IDK where/how we should enforce that. I don't think it's possible during expression construction, I think we would have to do it at execution time. But then would we have to execute the join result and inspect it, before continue executing it? Not great. So maybe we can't enforce the same-length restriction.

**Comment by cpcloud** [comment]
Thanks for the issue!

I think it makes sense to expose positional, but going out of our to implement it for backends that don't explicitly support it is probably out of scope.
