### ISSUE TITLE
bug: KeyError: <Type.BIT: 'BIT'> for bit types in postgres

### ISSUE THREAD

**Issue by p-a-a-a-trick** [ibis-project/ibis#9511]
### What happened?

It looks like there's a key issue with getting bit types for postgres. Ibis v9.1.0. I receive a sqlglot `KeyError: <Type.BIT: 'BIT'>`  when attempting to pull from a table with a bit column (trace `/lib/python3.12/site-packages/ibis/backends/sql/datatypes.py:174 in to_ibis dtype = _from_sqlglot_types[typecode](nullable=cls.default_nullable)`)

### What version of ibis are you using?

9.1.0

### What backend(s) are you using, if any?

Postgres

### Relevant log output

```sh
con.raw_sql("""
DROP TABLE IF EXISTS ibis_bit_test;
CREATE TABLE ibis_bit_test (
    bit_col BIT(4) NOT NULL
);
INSERT INTO ibis_bit_test
VALUES
    (b'1000');
""")
Out[16]: <cursor object at 0x7d30661b3880; closed: 0>

con.raw_sql("select bit_col from ibis_bit_test").fetchall()
Out[17]: [('1000',)]

con.table("ibis_bit_test").to_pandas()
Traceback (most recent call last):

  Cell In[18], line 1
    con.table("ibis_bit_test").to_pandas()

  /lib/python3.12/site-packages/ibis/backends/sql/__init__.py:137 in table
    table_schema = self.get_schema(name, catalog=catalog, database=database)

 /lib/python3.12/site-packages/ibis/backends/postgres/__init__.py:604 in get_schema
    col: type_mapper.from_string(typestr, nullable=nullable)

  /lib/python3.12/site-packages/ibis/backends/sql/datatypes.py:435 in from_string
    return cls.to_ibis(sgtype, nullable=nullable)

  /lib/python3.12/site-packages/ibis/backends/sql/datatypes.py:174 in to_ibis
    dtype = _from_sqlglot_types[typecode](nullable=cls.default_nullable)

KeyError: <Type.BIT: 'BIT'>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Great to see you around these parts!

Yeah, this isn't implemented.

How do you want to use this? As an integer, string, something else?

**Comment by p-a-a-a-trick** [comment]
Ibis is useful!

I don't really use bit operations outside of the DB (I'm just pulling them into my result so I can eyeball them), but it might be handy to have them as int just in case the user wants to use bit operations in python.

String would be helpful to preserve leading zeros/size, but also really long bit strings might be cumbersome and annoying to look at after a while.

Personally I'd lean towards numeric/int, but dev's choice, I think!

**Comment by gforsyth** [comment]
Hey @p-a-a-a-trick !  So I added in a thing so we fall back to `dt.unknown` as the type for any column that isn't in our explicit mappings.  That will let you _load_ the table with the `BIT` columns, but if there is a better way to display that particular dtype, let us know!  Also, maybe the current REPR view with `dt.unknown` "just works"?  Not sure.

**Comment by gforsyth** [comment]
Closing this as completed, but keep us posted if you need some bit ops or a friendlier REPR!
