### ISSUE TITLE
docs: `unnest` on table yields error

### ISSUE THREAD

**Issue by dkapitan** [ibis-project/ibis#9512]
### Please describe the issue

The example for unnesting on a Table shown [here](https://github.com/ibis-project/ibis/blob/efa6fb72bf4c790450d00a926d7bd809dade5902/ibis/expr/types/relations.py#L4736) yields `AttributeError: 'Table' object has no attribute 'unnest'`

`t.mutate(x=_.x.unnest())` does work. Am I missing something here?

Testen on OSX (M2), Python 3.11.7 and Ibis 9.1.0.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This won't be available until Ibis 9.2.0, https://github.com/ibis-project/ibis/pull/9423) was merged two days ago.
