### ISSUE TITLE
bug: timestamp.cast(str) gives backend-dependent results

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#9534]
### What happened?

Spin off from #9483. Feel free to close as not planned, I don't have any imminent need, I just wanted it written down, we can reopen later as needed.

I originally added a test case eg

```python
param(
            marks=[
                pytest.mark.broken(
                    "datafusion", reason="1672531200000000 (micro-seconds)"
                ),
                pytest.mark.broken(["exasol"], reason="2023-01-01 00:00:00.000000"),
                pytest.mark.broken(["flink"], reason="2023-01-01 00:00:00.000000"),
                pytest.mark.broken(["impala"], reason="casts to '2023-01-0100:00:00'"),
                pytest.mark.broken(["mssql"], reason="2023-01-01 00:00:00.000000"),
                pytest.mark.broken("oracle", reason="01-JAN-23 12.00.00.000000000 AM"),
                pytest.mark.broken(
                    "polars", reason="1672531200000000000 (nanoseconds)"
                ),
                pytest.mark.broken(["trino"], reason="2023-01-01 00:00:00.000"),
            ],
        )

e = ibis.literal(datetime.datetime(2023, 1, 1)), type="timestamp").cast("string")
assert con,execute(e) == "2023-01-01 00:00:00"
```

but before we add test cases, we need to decide what the expected behavior is.

Seeing as how some backends support it, I would lean towards as much precision as possible, eg down to nanosecond "2023-01-01 00:00:00.000000000".
- this is ALMOST [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), but not quite. IDK why these backends aren't using that? probably a good reason? If I was inventing the world I would say we should use ISO 8601, but the interop friction/perf hit I don't think is worth it.
- Backends with less precision can add trailing 0s.
- Oracle can just be broken over there by itself until a user fixes it themselves
- impala can get a patch for inserting the needed space. Or "fixed" upstream? 
- polars can be broken until someone wants to fix.

### What version of ibis are you using?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for documenting this @NickCrews ! I think we will go ahead and close this as not planned (for now).
