### ISSUE TITLE
feat(test): improve pytest mark names and/or docs

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#9535]
### Is your feature request related to a problem?

inspired from https://github.com/ibis-project/ibis/pull/9483#discussion_r1661157508

the current test mark names aren't great.

### What is the motivation behind your request?

Not obvious what they mean, and aren't even that strictly defined/used. This makes it difficult
- when writing a test to know which mark to use 
- when I see a mark how to interpret it

### Describe the solution you'd like

I can see several different axes by which we could measure a failing test:
- fixableness: is this easy or hard to fix? how much effort should we put in?
- cause: is this an upstream bug? a bug in ibis?
- commision vs ommission: is this an actual wrong behavior, or have we just not gotten around to implementing it yet?
- severity: sometimes tests fail due to some platform/OS/unrelated bug, or we can't get the right version of some package installed in CI, but for an end user the functionality works just fine.
- another axes you can think of?

In an ideal world we could encode all of these axes. But of course we can't have 2^3=8 (or more) different marks for each possible combo. So my interpretation is we currently use marks that describe 95% of test failures:

- pytest.mark.never: We have given up on this, we "expect" this to be broken, you probably don't want to sink time in here. eg anything to do with arrays or structs in sqlite, they will probably never be added to sqlite. eg not fixable, the cause is upstream. commission/ommision isn't really relevant.
- pytest.mark.notimpl: We label ibis as the cause, and error by ommision. It is fixable, but could be easy or hard
- pytest.mark.notyet: upstream is the cauase. could be commission or ommission. It is fixable, but I at least interpret this as difficult.
- pytest.mark.broken: this is fixable, but IDK how hard. this is ibis's fault, by commission.

Are there other corners of our axes space that we don't have a good name for?

are some axes more important than others and we want to emphasize them more? I think fixableness is one of the most important ones. WHY something is broken is usually an educated guess anyways, if you actually dig into it the cause and commission/ommission you might find something different, but as a reader of a test case I don't actually care too much, I just want to know if I should try to fix this or if I can expect someone else to ever fix it.

I think our current marks actually work pretty well. Maybe just rename "notyet" to "upstream"? Then all the other marks mean it is ibis's fault.

Currently [the docs suggest](https://ibis-project.org/contribute/02_workflow#adding-appropriate-tests) to use mark.broken whenever you make an unrelated change that just happens to break a test. I think this should be adjusted: I think when this happens, the developer can still feel free to add a mark and continue in their PR, but they should choose whichever mark makes the most sense, so they might still choose notimpl or upstream. I don't really care the circumstances under which a test case was added. I don't think that is what mark.broken should be reserved for. Either we should come up with a better meaning and/or name for mark.broken, or it should just get removed. 

This is sorta a brain dump so far, but just wanted to get some thoughts out there.

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepyaman** [comment]
@cpcloud, @gforsyth, et al. are at SciPy this week and will be back next week. This sounds like something they'd need to weigh in on, so will look to get back to you soon after that!

**Comment by gforsyth** [comment]
@NickCrews -- I agree we could call rename `notyet` to `upstream`, although I'm concerned that there will be a follow-up issue from someone requesting that it be named to `upstream_issue` and I'm not interested in mark names that are that long.  So I guess I'm a -0 on that?  I can be convinced.

`broken` should never be used on a test that has been added in the same PR.  but we've had situations where a backend (often a cloud backend where we don't control the version) just starts breaking on something that was previously working.
We don't want to saddle a new contributor with tracking down some regression in Snowflake or BigQuery to determine how to best label a test that is not part of their patch.

I do think that `broken` has been overused.  All lightly imposed conventions will suffer from drift.

**Comment by gforsyth** [comment]
I'm going to close this as unplanned, but we can re-open and continue if folks have strong motivation to change this.

**Comment by NickCrews** [comment]
What about for one change we just replace .broken with .notyet? It seems like the end result is the same, there is something going on upstream that is breaking us. I don't think we need to differentiate between "used to work" (broken) and "never worked" (notyet)? If someone goes to make a fix, I don't think that distinction is relevant?

**Comment by gforsyth** [comment]
Hey @NickCrews, yeah, that makes sense to me!  I'd be happy to merge that PR in.
