### ISSUE TITLE
bug: create_table() to non-default 'database' not working (mssql)

### ISSUE THREAD

**Issue by nikdotcodes** [ibis-project/ibis#9538]
### What happened?

When trying to create_table() to anything other that 'dbo' results in an error
`ibis.common.exceptions.UnsupportedOperationError: Creating tables in other databases is not supported by Postgres`

Have tried using `schema` and `database` parameter, both failing - when using defaults, the table is created happily.

Example script
```python

import ibis

mssql = ibis.mssql.connect(
        host="localhost",
        database="ibisdb",
        driver="ODBC Driver 17 for SQL Server"
    )
load_data = ibis.memtable({"values": [1, 2, 1, 2, 3, 2]})
ibis.set_backend(mssql)
mssql.create_table('nik_test', load_data.to_pyarrow(), database='fldr2', overwrite=True)
```

```bash
Traceback (most recent call last):
  File "c:\sc\AzureDevOps\FileLoader%20v2\fileloaderv2\to_inputfile\from_csv.py", line 44, in <module>
    mssql.create_table('nik_test', load_data.to_pyarrow(), database='fldr2', overwrite=True)
  File "C:\sc\AzureDevOps\FileLoader%20v2\.venv\Lib\site-packages\ibis\backends\mssql\__init__.py", line 455, in create_table
    raise com.UnsupportedOperationError(
ibis.common.exceptions.UnsupportedOperationError: Creating tables in other databases is not supported by Postgres
```

### What version of ibis are you using?

9.1.0

### What backend(s) are you using, if any?

Mssql

### Relevant log output

```sh
Traceback (most recent call last):
  File "c:\sc\AzureDevOps\FileLoader%20v2\fileloaderv2\to_inputfile\from_csv.py", line 44, in <module>
    mssql.create_table('nik_test', load_data.to_pyarrow(), database='fldr2', overwrite=True)
  File "C:\sc\AzureDevOps\FileLoader%20v2\.venv\Lib\site-packages\ibis\backends\mssql\__init__.py", line 455, in create_table
    raise com.UnsupportedOperationError(
ibis.common.exceptions.UnsupportedOperationError: Creating tables in other databases is not supported by Postgres
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepyaman** [comment]
I believe this was fixed in https://github.com/ibis-project/ibis/pull/9434; can you try installing Ibis from `main` to get the latest (unreleased) version. You should be able to do something like `pip install 'ibis-framework[mssql] @ git+https://github.com/ibis-project/ibis'`. Alternatively, you can wait for the next release, if it's not urgent.

**Comment by gforsyth** [comment]
This is fixed on `main`, definitely let us know if you still have problems creating tables outside of `dbo`.
