### ISSUE TITLE
feat: implement read_delta with the native duckdb extension

### ISSUE THREAD

**Issue by asbonatto** [ibis-project/ibis#9547]
### Is your feature request related to a problem?

For some datasets the current implementation of read_delta is significantly slower than the native duckdb delta extension. In a specific dataset I'm using  (which consists in very large number of small files) it lakes ~39 seconds to infer the schema of the table  vs 0.3s using the native extension.

### Describe the solution you'd like

I drafted an implementation using the native extension and the performance improved dramatically. This implementation follows roughly the _read_parquet_duckdb_native method:
 
```python
from ibis.backends.duckdb import Backend
from ibis import util
from typing import TYPE_CHECKING, Any
import sqlglot.expressions as sge
from ibis.backends.sql.compiler import STAR, C
import sqlglot as sg
import ibis.expr.types as ir
import os
import ibis


class NativeDeltaBackend(Backend):

    def read_delta(
        self,
        source_table: str,
        table_name: str | None = None,
        **kwargs: Any,
    ) -> ir.Table:
        """Register a Delta Lake table as a table in the current database using native delta extension

        Parameters
        ----------
        source_table
            The data source. Must be a directory
            containing a Delta Lake table.
        table_name
            An optional name to use for the created table. This defaults to
            a sequentially generated name.
        **kwargs
            Additional keyword arguments passed to deltalake.DeltaTable.

        Returns
        -------
        ir.Table
            The just-registered table.

        """
        
        source_table = util.normalize_filenames(source_table)
        table_name = table_name or util.gen_name("read_delta")

        if any(
            source.startswith(("http://", "https://", "s3://"))
            for source in source_table
        ):
            self._load_extensions(["httpfs"])

        self._load_extensions(["delta"])


        options = [
            sg.to_identifier(key).eq(sge.convert(val)) for key, val in kwargs.items()
        ]
        self._create_temp_view(
            table_name,
            sg.select(STAR).from_(self.compiler.f.delta_scan(source_table, *options)),
        )
        return self.table(table_name)
```

### What version of ibis are you running?

latest

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
@asbonatto thanks for opening! this is definitely something we should do

see https://github.com/ibis-project/ibis/pull/9361 -- there was a concern that Windows isn't supported. personally, I'd also like for them to add write support before we switch though that doesn't need to be blocking

**Comment by asbonatto** [comment]
Nice! Sorry for reopening this issue!

**Comment by lostmygithubaccount** [comment]
no worries! it's good to know people are looking for this -- I don't think we had an issue before so we can keep this open until closed by a PR

**Comment by ncclementi** [comment]
In their docs, as of last week, it looks like there is windows support now. https://github.com/duckdb/duckdb_delta/commit/a392ea517720dfe08276d74e32f7e9e78c7585b9

Unless I'm missing something maybe it is already possible.

**Comment by ncclementi** [comment]
xref: https://github.com/ibis-project/ibis/pull/9566

**Comment by ncclementi** [comment]
@asbonatto this PR https://github.com/ibis-project/ibis/pull/9566 adds the support you needed. You can install from main, or wait until the 9.2 release. But if you give it a try let us know

**Comment by asbonatto** [comment]
It's working. thank you for the fast response!

**Comment by ncclementi** [comment]
Nice!. 
@asbonatto would you be interested in writing a blogpost in the Ibis site showcasing your use case with a small example.?

**Comment by asbonatto** [comment]
I'd be happy to collaborate but I'm not sure this project is interesting enough. So far I've been using ibis to convert ~ 300 Gb of csv files to delta format to speed up analysis.

**Comment by ncclementi** [comment]
Well, the invitation is open.  It would be great to have some content/short blog on a real-world delta lake use case.
