### ISSUE TITLE
chore(deps): possibly make pyarrow optional

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#9548]
Based on some discussion at SciPy this week, we are going to hack on this during the sprints and see if we can make pyarrow an optional dependency.

In practice, pyarrow is a required dependency because of its pervasive use in the codebase, but it's only needed for actions that involve execution or type inference on in-memory data.

Users who want to use fully abstract expressions don't need to incur this overhead with an install like `pip install ibis-framework`.

Instead, the idea is that our backend extras just get a `"pyarrow"` added to their list.

If this goes well, we can try to apply this same approach to numpy and pandas.

cc @gforsyth

**Comment by jcrist** [comment]
See #8430 for more general discussion of making `pyarrow`/`pandas`/`numpy`optional.

**Comment by cpcloud** [comment]
Closing in favor of #8430. I'll comment there.
