### ISSUE TITLE
read_geo table doesn't persist in duckdb

### ISSUE THREAD

**Issue by AaronFarquharQSI** [ibis-project/ibis#9579]
### What happened?

Tables created using `read_geo` cannot be found in my (local) duckdb database if I disconnect from the connection or end my python session. On the other hand,  non-geospatial tables created using `create_table` do persist. 

This is the case for all shapefiles I have tested. For this example, I am using a GADM USA shapefile from: [https://geodata.ucdavis.edu/gadm/gadm4.1/shp/gadm41_USA_shp.zip](url)

```
con = ibis.duckdb.connect('data.duckdb')
con.read_geo('gadm41_USA_0.shp')
con.list_tables()

# output: ['ibis_read_geo_gmeukea6hnbkrewopitnqlky5a']

con.disconnect()
con = ibis.duckdb.connect('data.duckdb') # or con.reconnect()
con.list_tables()

# output: []
```

### What version of ibis are you using?

9.1.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @AaronFarquharQSI !  

All of the `read_*` methods create temporary views or tables (depending on the backend) that don't persist between sessions.

If you want the data to stay in the `duckdb` file, you can do something like:

```python
con = ibis.duckdb.connect('data.duckdb')
shp_file = con.read_geo('gadm41_USA_0.shp')

con.create_table("gadm41_USA", shp_file)
```

`list_tables` is a bit of a misnomer here, as it returns both tables and views

**Comment by cpcloud** [comment]
Yep, this behavior is intentional, to give `read_*` methods transient behavior with respect to storage, like other dataframe APIs.

`create_table` is the way to persist things into the backend.
