### ISSUE TITLE
docs(blog/how to): Ibis + duckdb spatial + geoparquet + lonboard 

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#9598]
### Please describe the issue

After this support added to duckdb to read geoparquet (still on nightly as there is no new release), and this PR on Ibis https://github.com/ibis-project/ibis/pull/9549, we should now be able to plot on lonboard directly from an Ibis table. 

Write a blog/how to about it. Not sure what's the best option, I don't have a strong opinion. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kylebarron** [comment]
With #9549 it _should_ work to pass `lonboard.viz(ibis_table)` or `lonboard.ScatterplotLayer(table=ibis_table)` directly. Let me know if it doesn't

**Comment by ncclementi** [comment]
@kylebarron  Confirmed, I can plot directly from an Ibis table both with `viz` or a map with multiple Layers. 

The only caveat is that if the data is not on WGS84, because duckdb doesn't have info of the CRS then it errors when trying to plot. Transforming to the right projection does the trick.

I'll try to put a doc, blog or something up at some point this week.

**Comment by ncclementi** [comment]
I wonder if we should wait for the next duckdb patch release or give instructions on  how to install from nightly. Happy to give instructions and then update once released.

**Comment by kylebarron** [comment]
Yeah that sounds great! I always struggle to find compelling datasets, so if you have one you like, I'm happy to use that one

**Comment by ncclementi** [comment]
I've been trying to play around with some more interesting data from overture maps, and while at it I landed in a few bugs hence the delay. 
xref: https://github.com/ibis-project/ibis/issues/9662
xref: https://github.com/duckdb/duckdb/issues/13120 (this one is a problem as a nightly version is needed to be able to get the geoparquet support)

**Comment by ncclementi** [comment]
Now blocked on https://github.com/duckdb/duckdb/issues/13285
