### ISSUE TITLE
docs: missing to_parquet() docs

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#9600]
### Please describe the issue

xref zulip: https://ibis-project.zulipchat.com/#narrow/stream/405265-tech-support/topic/specify.20partition.20columns.20in.20to_parquet.28.29.3F/near/451643876 

We have docstrings but I wasn't able to find this rendered, is this intentional because it's experimental or they are somehow missing? 

 https://github.com/ibis-project/ibis/blob/f50cbfc204712a6465684c3597b26473b683b463/ibis/expr/types/core.py#L568-L604

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
so a bunch of these are rendered in the backend docs pages, but aren't showing up in Algolia.  I'm going to try to add them to our additional algolia index scrape script.
