### ISSUE TITLE
feat: remove `IntegerValue.label()`

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#9612]
Putting this up for tracking it, not immediately actionable.

Once #9096 lands then I think we should remove the `IntegerValue.label(labels,  nulls)` method. Users can easily switch to `val.cases(*enumerate(labels), else_=nulls)`, and we can have this pointer in the deprecation notice.

_Originally posted by @NickCrews in https://github.com/ibis-project/ibis/pull/9096#discussion_r1586541965_

**Comment by cpcloud** [comment]
Seems reasonable!
