### ISSUE TITLE
bug(pyspark): unable to remove punctuation using re_replace 

### ISSUE THREAD

**Issue by jstammers** [ibis-project/ibis#9615]
### What happened?

I have a function that uses a regular expression to remove punctuation from a string column.
I am able to execute it without issues on a duckdb-based table, but am not able to execute it on a pyspark backend.
My suspicion is that this is related to some of the characters not being escaped correctly

```python
import pandas as pd
import string
import ibis

def remove_punctutation(x):
    punkt_re = '[{}]'.format(string.punctuation)
    x = x.re_replace(rf"{punkt_re}", " ")
    return x

con_sql = ibis.pyspark.connect(spark)
df = ibis.memtable(pd.DataFrame({"text": ["foo!", "bar?", "(baz)"]}))

remove_punctutation(df.text)

df_spark = con_sql.create_view("df", df, overwrite=True)

remove_punctutation(df_spark.text)
```
The error I get suggests it is related to the ` character, which I suspect is reserved within spark SQL for quoting column names.

For reference, here are the corresponding SQL statements that I observe using `ibis.to_sql`

```python
SELECT
  REGEXP_REPLACE("t0"."text", '[!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~]', ' ', 'g') AS "RegexReplace(text, '[!""#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~]', ' ')"
FROM "ibis_pandas_memtable_skqyndin6bdzrfhsaajcp4hvje" AS "t0"

SELECT
  REGEXP_REPLACE(`t0`.`text`, '[!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~]', ' ') AS `RegexReplace(text, '[!"#$%&\'()*+,-./:;<=>?@[\\]^_"`{|}~]', ' ')`
FROM `df` AS `t0`
```

I am able to achieve what I need using a unicode range, e.g.
```python
punkt_re = '[^\u00BF-\u1FFF\u2C00-\uD7FF\w\s]'
```

but I thought it would be worth highlighting the initial string as an example that could break compatibility between different backends.

### What version of ibis are you using?

9.1.0

### What backend(s) are you using, if any?

DuckDB, PySpark

### Relevant log output

```sh
ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near '{'. SQLSTATE: 42601 (line 1, pos 156)

== SQL ==
SELECT
  REGEXP_REPLACE(`t0`.`text`, '[!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~]', ' ') AS `RegexReplace(text, '[!"#$%&\'()*+,-./:;<=>?@[\\]^_"`{|}~]', ' ')`
FROM `df` AS `t0`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for opening this, @jstammers -- you've found one of the query translation footguns.
PySpark uses Java regular expressions, and DuckDB uses re2 for regular expressions.

We don't have a good way to translate between regex dialects, so this remains one of the frustrating backend-specific pieces.

I'm going to close this out as not-planned, but please feel free to continue the discussion here!
