### ISSUE TITLE
bug: timestamp truncation shifts time with polars backend

### ISSUE THREAD

**Issue by wojciechowski-p** [ibis-project/ibis#9618]
### What happened?

When calling `timestamp.truncate()` method with polars backend, the resulting timestamps are truncated but additionally **shifted 7 days backwards**.

Example:
```python
import polars as pl
from datetime import datetime


timestamps = [
    datetime(2024, 1, 1, 12, 0),
    datetime(2024, 1, 2, 13, 12),
    datetime(2024, 1, 3, 14, 55),
    datetime(2024, 1, 4, 16, 12),
    datetime(2024, 1, 5, 12, 30)
]

df = pl.DataFrame({
    'timestamp': timestamps
})

con = ibis.polars.connect({"df":df})
table = con.table("df")

table.mutate(timestamp_truncated=table.timestamp.truncate('h')).execute()

##result:
            timestamp timestamp_truncated
0 2024-01-01 12:00:00 2023-12-25 12:00:00
1 2024-01-02 13:12:00 2023-12-26 13:00:00
2 2024-01-03 14:55:00 2023-12-27 14:00:00

##expected output (as when using pyspark backend):
            timestamp timestamp_truncated
0 2024-01-01 12:00:00 2024-01-01 12:00:00
1 2024-01-02 13:12:00 2024-01-02 13:00:00
2 2024-01-03 14:55:00 2024-01-03 14:00:00
```

Running the same ibis operation `table.mutate(timestamp_truncated=table.timestamp.truncate('h'))` on pyspark backend results in expected output.

### What version of ibis are you using?

9.1.0

### What backend(s) are you using, if any?

Polars

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@wojciechowski-p Thanks for the report, definitely a bug!
