### ISSUE TITLE
bug: "Dask via Ibis" 30x slower than running Dask directly

### ISSUE THREAD

**Issue by MarcoGorelli** [ibis-project/ibis#9631]
### What happened?

I was curious about running Dask via Ibis, and tried out tpc-H Q1. Fully reproducible results are here: https://www.kaggle.com/code/marcogorelli/tpch-q1-s2-dask?scriptVersionId=188826566

Dask code:
```python
from datetime import datetime

def q1_dask(lineitem_ds):
    VAR1 = datetime(1998, 9, 2)
    lineitem_filtered = lineitem_ds[lineitem_ds.l_shipdate <= VAR1]
    lineitem_filtered["sum_qty"] = lineitem_filtered.l_quantity
    lineitem_filtered["sum_base_price"] = lineitem_filtered.l_extendedprice
    lineitem_filtered["avg_qty"] = lineitem_filtered.l_quantity
    lineitem_filtered["avg_price"] = lineitem_filtered.l_extendedprice
    lineitem_filtered["sum_disc_price"] = lineitem_filtered.l_extendedprice * (
        1 - lineitem_filtered.l_discount
    )
    lineitem_filtered["sum_charge"] = (
        lineitem_filtered.l_extendedprice
        * (1 - lineitem_filtered.l_discount)
        * (1 + lineitem_filtered.l_tax)
    )
    lineitem_filtered["avg_disc"] = lineitem_filtered.l_discount
    lineitem_filtered["count_order"] = lineitem_filtered.l_orderkey
    gb = lineitem_filtered.groupby(["l_returnflag", "l_linestatus"])

    total = gb.agg(
        {
            "sum_qty": "sum",
            "sum_base_price": "sum",
            "sum_disc_price": "sum",
            "sum_charge": "sum",
            "avg_qty": "mean",
            "avg_price": "mean",
            "avg_disc": "mean",
            "count_order": "size",
        }
    )

    return total.reset_index().sort_values(["l_returnflag", "l_linestatus"]).compute()
```

Dask via Ibis code:
```python
def q1_ibis(lineitem):
    var1 = datetime(1998, 9, 2)
    lineitem = lineitem.filter(lineitem["l_shipdate"] <= var1)
    lineitem = lineitem.mutate(
        disc_price=lineitem["l_extendedprice"] * (1 - lineitem["l_discount"]),
        charge=(
            lineitem["l_extendedprice"]
            * (1.0 - lineitem["l_discount"])
            * (1.0 + lineitem["l_tax"])
        ),
    )
    q_final = (
        lineitem
        .group_by(["l_returnflag", "l_linestatus"])
        .aggregate(
            sum_qty=lineitem["l_quantity"].sum(),
            sum_base_price=lineitem["l_extendedprice"].sum(),
            sum_disc_price=(lineitem['disc_price'].sum()),
            sum_charge=(lineitem['charge'].sum()),
            avg_qty=lineitem["l_quantity"].mean(),
            avg_price=lineitem["l_extendedprice"].mean(),
            avg_disc=lineitem["l_discount"].mean(),
            count_order=lambda lineitem: lineitem.count(),
        )
        .order_by(["l_returnflag", "l_linestatus"])
    )
    return q_final.to_pyarrow()
```

IO functions:
```python
import ibis
import pyarrow.parquet as pq
import dask.dataframe as dd

con_dask = ibis.dask.connect()

IO_FUNCS = {
    'dask[ibis]': lambda x: con_dask.read_parquet(x, engine='pyarrow', dtype_backend='pyarrow'),
    'dask': lambda x: dd.read_parquet(x, engine='pyarrow', dtype_backend='pyarrow'),
}
```

Am I using anything incorrectly for this function?

Just wanted to report in case there's a bug here on your end that you might be interested in investigating

### What version of ibis are you using?

dask-2024.7.0 dask-expr-1.1.7 ibis-framework-9.1.0

### Relevant log output

- Dask: 4.18 s
- Dask via Ibis: 2 min 3s

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @MarcoGorelli -- thanks for flagging this.  The `dask` backend is built largely on top of the `pandas` backend and suffers performance-wise because of that.  I think especially given the recent improvements with `dask-expr`, that Ibis is _not_ a good way to make use of `dask.dataframe`.
It's been on our list for a while to look at rewriting the dask backend to directly target `dask-expr`, but we're spread a little thin and implementing non-SQL backends is a lot more of a lift, generally.

**Comment by MarcoGorelli** [comment]
Thanks @gforsyth !

Makes sense, thanks. If you recommend not using Ibis to run dask, may I suggest amending this sentence

> If you need to scale out with [Dask](https://ibis-project.org/backends/dask) or [PySpark](https://ibis-project.org/backends/pyspark) or [Trino](https://ibis-project.org/backends/trino), you can use Ibis

from [this blog post](https://ibis-project.org/posts/1tbc/)?

**Comment by gforsyth** [comment]
Yep!

**Comment by gforsyth** [comment]
Ok, thanks again, @MarcoGorelli -- I'm going to close this out as unplanned.
