### ISSUE TITLE
docs: How to call duckDB SUMMARIZE function using ibis .sql() ? 

### ISSUE THREAD

**Issue by vparpoil** [ibis-project/ibis#9694]
### Please describe the issue

Disclaimer : I'm quite new to ibis and duckdb, please excuse me if its answer is obvious

I'm trying to use ibis to execute a SQL `SUMMARIZE` command on a ibis table with duckDB backend (this is somehow related to #9639 : performance was an issue, we found a workarround using duckdb directly, but we want to refactor to full ibis code), but it doesn't seem to work as expected : 

```python
backend = ibis.duckdb.connect()
dataset_as_ibis_table = backend.read_parquet(dataset_path)
dataset_as_ibis_table.alias("dataset").sql("SUMMARIZE dataset").execute()
```

Leads to the following : 
```
  File "./clients/ibis_client.py", line 72, in _summarize_dataset_columns_from_ibis_table
    dataset_summarize = dataset_as_ibis_table.alias("dataset").sql("SUMMARIZE dataset").execute()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//.venv/lib/python3.12/site-packages/ibis/expr/types/relations.py", line 3533, in sql
    schema = backend._get_sql_string_view_schema(name, expr, query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/ibis/backends/sql/__init__.py", line 225, in _get_sql_string_view_schema
    parsed = parsed.with_(
             ^^^^^^^^^^^^
AttributeError: 'Alias' object has no attribute 'with_'
```

relevant dependencies 
```
python = "^3.12"
ibis-framework = {extras = ["duckdb"], version = "^9.1.0"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
You can't do that right now, because SQLGlot generates incorrect code for this operation:

```
In [1]: import sqlglot.expressions as sge, sqlglot as sg

In [2]: sg.parse_one("summarize my_table", read="duckdb")
Out[2]:
Alias(
  this=Column(
    this=Identifier(this=summarize, quoted=False)),
  alias=Identifier(this=my_table, quoted=False))

In [3]: sg.parse_one("summarize my_table", read="duckdb").sql("duckdb")
Out[3]: 'summarize AS my_table'
```

I'll open an issue on their side.

**Comment by cpcloud** [comment]
https://github.com/tobymao/sqlglot/issues/3823 is the corresponding SQLGlot issue.

**Comment by cpcloud** [comment]
In the meantime, you can try using the `.describe()` (slower, but more statistics) or `.info()` (faster, but fewer statistics) methods.

**Comment by cpcloud** [comment]
Looks like this will be supported in the next sqlglot release, which means it should start to work if you upgrade your sqlglot version.

**Comment by jitingxu1** [comment]
HI @vparpoil could I know the dimension (rows, cols) in your table? Do you have any lazy operations before running the `describe()`.  I would like to learn how large the table could be in real-life. 

Fort my case, It took me  ~100 seconds to describe a table with 1.5m rows and 450 cols. See the https://github.com/ibis-project/ibis/issues/9639#issuecomment-2246906904

**Comment by vparpoil** [comment]
Hi @jitingxu1, 
We are building something generic that would let users upload their data and play with it. Description of each column is then an important feature. No other lazy operation running, it's done directly after reading a parquet file.

I have used smaller dataset : about 30 columns and < 500k records. DuckDB response on summarize for such a dataset seems very quick (I haven't measured it exactly)

**Comment by cpcloud** [comment]
With my changes in #9684,

Ibis's `Table.describe()` and DuckDB's `SUMMARIZE` appear to be on par with each other:

```

------------------------------------------------------------------------------- benchmark 'summarization': 2 tests -------------------------------------------------------------------------------
Name (time in s)                           Min               Max              Mean            StdDev            Median               IQR            Outliers     OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_summarize_duckdb                   2.5834 (1.06)     2.6984 (1.0)      2.6345 (1.0)      0.0413 (1.0)      2.6330 (1.0)      0.0372 (1.0)           2;0  0.3796 (1.0)           5           1
test_summarize_end_to_end[describe]     2.4275 (1.0)      3.5094 (1.30)     3.1210 (1.18)     0.4134 (10.00)    3.2654 (1.24)     0.4122 (11.08)         1;0  0.3204 (0.84)          5           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by cpcloud** [comment]
The next release of Ibis (9.3, slated for this week) will support a version of sqlglot for which calling `SUMMARIZE` will work.
