### ISSUE TITLE
bug: to_arrow on ClickHouse backend not returning all rows

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#9709]
### What happened?

calling `.to_arrow()` on a table from a ClickHouse Cloud public playground is giving a (different) subset of rows:

```python
import ibis

ibis.options.interactive = True

# define external source
host = "clickpy-clickhouse.clickhouse.com"
port = 443
user = "play"
database = "pypi"

pypi_package = "ibis-framework"

ch_con = ibis.clickhouse.connect(
    host=host,
    port=port,
    user=user,
    database=database,
)

# read in data from external source
t = ch_con.table(
    "pypi_downloads_per_day_by_version_by_installer_by_type_by_country"
).filter(ibis._["project"] == pypi_package)
t
```

now output the count:

```python
t.count()
```

```html
┌────────┐
│ 218601 │
└────────┘
```

then do this:

```python
ibis.memtable(t.to_pyarrow()).count()
```

```html
┌──────┐
│ 1732 │
└──────┘
```

I get a different number of rows each time I run it, ranging from 1000s to 9000s. it almost seems like ClickHouse is limiting the amount of data you can transfer out, which would seem reasonable for a public playground, but I'm not sure. opening for discussion/see if this would be something known

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb, clickhouse

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
> it almost seems like ClickHouse is limiting the amount of data you can transfer out, which would seem reasonable for a public playground, but I'm not sure.

Clickhouse playground does do this, this is what you're seeing. Closing as expected for clickhouse playground (but not clickhouse itself).
