### ISSUE TITLE
Quarterly truncation no longer allowed in backends.sql.compilers.base.visit_TimestampTruncate

### ISSUE THREAD

**Issue by ph-eip** [ibis-project/ibis#9714]
### What happened?

When truncating my timestamps to quarterly, the error: *Unsupported truncate unit None* was reported.

However, in the documentation quarterly is listed as supported: https://ibis-project.org/reference/expression-temporal.html#parameters-4.  (Also, database backends support quarterly truncation).

The error appears to be the definition of 'unit_mapping' in the function **visit_TimestampTruncate** found at:

https://github.com/ibis-project/ibis/blob/038a95a19d979fde23fee95df5df8c1838eaa9b3/ibis/backends/sql/compilers/base.py#L837

```python
    def visit_TimestampTruncate(self, op, *, arg, unit):
        unit_mapping = {
            "Y": "year",
            "M": "month",
            "W": "week",
            "D": "day",
            "h": "hour",
            "m": "minute",
            "s": "second",
            "ms": "ms",
            "us": "us",
        }

        if (unit := unit_mapping.get(unit.short)) is None:
            raise com.UnsupportedOperationError(f"Unsupported truncate unit {unit}")
```

There you can see that 'Q' is missing from the unit_mapping keys.

### What version of ibis are you using?

9.2.0

### What backend(s) are you using, if any?

Postgres

### Relevant log output

```sh
https://github.com/ibis-project/ibis/blob/038a95a19d979fde23fee95df5df8c1838eaa9b3/ibis/backends/sql/compilers/base.py#L837
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
I hit this recently too (DuckDB backend) but hadn't investigated, appreciate the thorough report!

**Comment by cpcloud** [comment]
Thanks! This looks like might have been a casualty of the port to 9.0, and that we may not have enough test coverage. Great bug report!

**Comment by cpcloud** [comment]
We'll try to cut 9.3 this week!
