### ISSUE TITLE
BUG: Unable to set "value" in set_options() where "." (period) exists in value

### ISSUE THREAD

**Issue by pyite1** [ibis-project/ibis#974]
Hello, 

I am trying to set request_pool via set_options... and receive an error if the value has a "." in the field.

```
client.set_options({'REQUEST_POOL':'root.xxx'})
````

**Comment by cpcloud** [comment]
There's something very strange going on here. I can perform the following operation on the Impala command line, Hive command line, and PyHive, but not in ibis:

```sql
SET REQUEST_POOL = foo.bar
```
I suspect that there's a bug in impyla, which is the client communicating with thrift.

**Comment by wesm** [comment]
are you using the beeswax or hs2 protocol?

**Comment by pyite1** [comment]
I'm using HS2.

**Comment by pyite1** [comment]
I was able to get around this one by escaping the second argument:
```
client.set_options({'REQUEST_POOL':"'root.xxx'"})
```

**Comment by cpcloud** [comment]
Keeping this open until I have an understanding of why this happens.

**Comment by cpcloud** [comment]
I haven't had time to track this down since the last release. Pushing to 0.13.
