### ISSUE TITLE
feat: ArrayCollect aggregation for Flink backend

### ISSUE THREAD

**Issue by ArtnerC** [ibis-project/ibis#9801]
### What happened?

Attempting to aggregate rows to an array using collect() is resulting in an operation not supported error for ArrayCollect.

Flink supports this functionality through the [ARRAY_AGG function](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/functions/systemfunctions/) while the Flink dialect inherits from Hive which uses COLLECT_LIST.

I was attempting to implement this myself until the recent changes supporting order_by in some aggregates dropped and it derailed my changes. Would appreciate some help here as it seems like some additional plumbing is needed for this to work in flink.

### What version of ibis are you using?

9.3.0

### What backend(s) are you using, if any?

flink, duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks @ArtnerC!

Please make a pull request with what you've already done, and we can go from there

**Comment by ArtnerC** [comment]
Done. Before [a recent #71271dd ](https://github.com/ibis-project/ibis/commit/71271dd262f28dd34e58475d9b2e1e2c70cb4cb8) I had also removed `ArrayCollect` from UNSUPPORTED_OPS and it was correctly generating SQL with ARRAY_AGG. Now it is looking for `visit_ArrayCollect` but I'm having trouble implementing that because it is getting an `include_null` arg instead of `ignore_null`.
