### ISSUE TITLE
feat: add Excel backend is necessary

### ISSUE THREAD

**Issue by 332123342** [ibis-project/ibis#9807]
### Which new backend would you like to see in Ibis?

Excel is common use in work

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
hi @332123342, can you describe your use case better here? you can already use data from Excel in Ibis via memtables with the DuckDB backend or several others, with various methods for ingestion (through pandas, Polars, DuckDB, DataFusion, or PyArrow)

**Comment by cpcloud** [comment]
Excel **files** are already supported through DuckDB and Polars. Please use one of those backends.

**Comment by 332123342** [comment]
> Excel **files** are already supported through DuckDB and Polars. Please use one of those backends.

how to add .xlsx files?
only found read_csv ...
<img width="1216" alt="image" src="https://github.com/user-attachments/assets/7fd4079b-bab0-406e-a669-436a9b9b9da5">
