### ISSUE TITLE
bug: repr for count now includes np.int64 or whatever type

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#9820]
### What happened?

on a fresh install:

`pip install 'ibis-framework[duckdb,examples]'`

repr now seems to include numpy types in the output. for instance:

```python
[ins] In [1]: import ibis

[ins] In [2]: ibis.options.interactive = True

[nav] In [3]: t = ibis.examples.penguins.fetch()

[ins] In [4]: t.count()
Out[4]:
┌───────────────┐
│ np.int64(344) │
└───────────────┘
```

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
also to be clear this happens for other methods than `.count()` too

**Comment by cpcloud** [comment]
This is related to using numpy 2. Numpy 2 includes changes to their repr, and IMO is not something we should spend any time addressing.

In fact, the new repr hides less information: it was still coming back as a `np.whatever` value, but not showing it.

**Comment by jcrist** [comment]
I disagree Phillip - we're doing a pretty repr here, and numpy types (especially numerics) can generally be subbed in to methods anywhere a native python type is accepted. Taking the care to render these nicely as their expected `int`/`float` variety seems worth it to me. Happy to take on this work myself if you don't disagree.

**Comment by cpcloud** [comment]
Definitely didn't mean to come off super strongly opinionated here 😅, just seems like it might be a rabbit hole not worth exploring. I have no issue with anyone addressing this.

By "coming back" I was being too imprecise, what I meant was "when executed"

**Comment by cpcloud** [comment]
Reopening!
