### ISSUE TITLE
feat: MonetDB as backend

### ISSUE THREAD

**Issue by simonaubertbd** [ibis-project/ibis#9845]
### Which new backend would you like to see in Ibis?

Hello all,

MonetDB is a very light, fast, open-source database available here :
https://www.monetdb.org/

Really enjoy it, works pretty well with Tableau and it's a good introduction to column-store concepts and analytics with SQL.

It has also gained a lot of popularity these last years :
https://db-engines.com/en/ranking_trend/system/MonetDB

Best regards,

Simon

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

Supporting MonetDB might be hard for us to justify given it lacks some critical features of other modern analytics backends that we support:

1. Array, map, and struct types
2. Reading parquet files

Additionally, there are two other systems that we have great support for that use columnar storage: DuckDB and ClickHouse.

Both DuckDB and ClickHouse work with Tableau as well.

**Comment by simonaubertbd** [comment]
@cpcloud actually DuckDB does not work that well for Tableau... there is custom connector since a few months ago but I wrote an idea for Tableau to support it natively and it's in development. https://community.tableau.com/s/idea/0874T000000HEXbQAO/detail ;)

For reading parquet file, I mentioned your point on the enhancement I wrote a month ago for MonetDB to support Parquet
https://github.com/MonetDB/MonetDB/issues/7427

For complex type support, I opened another issue https://github.com/MonetDB/MonetDB/issues/7568

Best regards,

Simon

**Comment by jcrist** [comment]
Hi @simonaubertbd. Given the size of MonetDB's userbase and the market that it targets, it's not clear to us that MonetDB is a backend that is meaningful to prioritize at this time. We're already struggling to maintain the 20-some backends we already have :). As @cpcloud said above, in 2024 there are DB options for analytics that are both more performant (`duckdb`, `clickhouse`), more popular, and still supported by tableau. While we thank you for your interest, this is not a backend we're willing to support at this time.
