### ISSUE TITLE
refactor(api): remove casting from timestamp to integer and integer to timestamp

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#9854]
These two operations differ in our backends and IMO are confusing foot guns that make it hard to write portable Ibis code due to differing support for different units across backends. It also doesn't round trip, even within the same backend.

For the `timestamp -> integer` case, we can make an `epoch(unit)` API on `TimestampValue`.

For the `integer -> timestamp` case, we have the `IntegerValue.to_timestamp` method which allows specifying units. For that case I think we should also make the units required and not default to seconds.

**Comment by ncclementi** [comment]
> For the timestamp -> integer case, we can make an epoch(unit) API on TimestampValue.
@jcrist you had some comments/opions about this part while we were on triage. 


> For the integer -> timestamp case, we have the IntegerValue.to_timestamp method which allows specifying units. For that case I think we should also make the units required and not default to seconds.

We can do easily in the new `IntervalValue.as_timestamp()` API that we just changed. (PR coming up).

**Comment by cpcloud** [comment]
I think you mean Integer value in the last bit. IntervalValue.as_timestamp() isn't a meaningful operation in general.

**Comment by ncclementi** [comment]
Yup, you are right!
