### ISSUE TITLE
feat: Datafusion add support for using a list of paths when reading csv parquet etc

### ISSUE THREAD

**Issue by djouallah** [ibis-project/ibis#9866]
### Is your feature request related to a problem?

currently when reading csv/parquet, I can't pass a list of paths
read_csv(self, path, table_name=None, **kwargs)

### Describe the solution you'd like

support a list of paths,  the same way as currently supported in duckdb

### What version of ibis are you running?

0.9.3

### What backend(s) are you using, if any?

Datafusion

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@mesejo Any interest in creating a PR for this?

**Comment by mesejo** [comment]
I can take a swing at it

**Comment by mesejo** [comment]
The feature was not readily available in DataFusion, but it will be once this [PR](https://github.com/apache/datafusion-python/pull/824) is merged and released.
