### ISSUE TITLE
bug: AttributeError: 'StringColumn' object has no attribute 'as_date'

### ISSUE THREAD

**Issue by brooklynbagel** [ibis-project/ibis#9874]
### What happened?

Running the following examples

```python
import ibis
ibis.options.interactive = True
t = ibis.memtable({"ts": ["20240819"]})
t.ts.as_date("%Y%m%d")
```

or 

```python
con = ibis.duckdb.connect()
t = con.create_table("t", {"ts": ["20240819"]})
t.ts.as_date("%Y%m%d")
```

both result in the following `AttributeError: 'StringColumn' object has no attribute 'as_date'`. If this is not a bug then possibly the documentation at <https://ibis-project.org/reference/expression-strings#ibis.expr.types.strings.StringValue.as_date> needs to be updated. It is even stated in the docs:

> All string operations are valid for both scalars and columns.

### What version of ibis are you using?

9.3.0

### What backend(s) are you using, if any?

DuckDB and whatever `ibis.memtable` uses

### Relevant log output

```sh
>>> import ibis
... ibis.options.interactive = True
... t = ibis.memtable({"ts": ["20240819"]})
... t.ts.as_date("%Y%m%d")
AttributeError: 'StringColumn' object has no attribute 'as_date'
Cell In[1], line 4
      2 ibis.options.interactive = True
      3 t = ibis.memtable({"ts": ["20240819"]})
----> 4 t.ts.as_date("%Y%m%d")

>>> con = ibis.duckdb.connect()
... t = con.create_table("t", {"ts": ["20240819"]})
... t.ts.as_date("%Y%m%d")
AttributeError: 'StringColumn' object has no attribute 'as_date'
Cell In[2], line 3
      1 con = ibis.duckdb.connect()
      2 t = con.create_table("t", {"ts": ["20240819"]})
----> 3 t.ts.as_date("%Y%m%d")
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I think we haven't yet released this change yet!

In the mean time you should be able to use `to_date`.

**Comment by cpcloud** [comment]
The docs match `main` because in practice having versioned docs was more trouble than it was worth.

**Comment by brooklynbagel** [comment]
Okay, got it. Seems like a decent issue to setup versioned docs in the future if there's bandwidth for that.
