### ISSUE TITLE
bug: methods like `get_name()` and `type()` do not work with underscore API

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#9900]
### What happened?

When I call various methods of Ibis column expressions using the underscore API, it raises various errors. For example:

```py
import ibis
from ibis import _
import ibis.selectors as s
import pandas as pd

df = pd.DataFrame(data={'col1': [1, 2],
                        'col2': [3, 4],
                        'col3_secret': [5, 6],
                        'col4': [7, 8]})
t = ibis.memtable(df)

t.mutate(
  s.across(
    s.all(),
    ibis.null(type=_.type()) if _.get_name().endswith('_secret') else _
  )
)
```

The errors seem to vary depending on which specific method is called.

I can use a lambda to work around this:

```py
t.mutate(
  s.across(
    s.all(),
    lambda x: ibis.null(type=x.type()) if x.get_name().endswith('_secret') else x
  )
)
```

It'd be great if this worked with the underscore API. Thanks!

### What version of ibis are you using?

9.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ianmcook** [comment]
P.S. I recognize that it would be more efficient to do it this way:

```py
t.mutate(
  s.across(
    s.endswith('_secret'),
    lambda x: ibis.null(type=x.type())
  )
)
```

But that doesn't demonstrate use of `get_name()`.

**Comment by cpcloud** [comment]
An expression like

```
ibis.null(type=_.type()) if _.get_name().endswith('_secret') else _
```

cannot be equivalent to the `lambda` version.

The syntax `y if x else z` will invoke `x.__bool__` which is meaningless for deferred objects (things derived from the `_`).

**Comment by ianmcook** [comment]
Ah, ok, thanks. How about just a simpler case like this then:

```
t.mutate(
  s.across(
    s.all(),
    ibis.null(type=_.type())
  )
)
```

I'm not sure why anyone would want to do that, but it seems like it _should_ work.

**Comment by cpcloud** [comment]
Can you construct an example that uses **only** deferred expressions?

**Comment by cpcloud** [comment]
Ah, I think we also need to make `null` deferrable...

**Comment by cpcloud** [comment]
so, nevermind, your example is fine!

**Comment by ianmcook** [comment]
Here's another silly-ish example that (I think?) avoids non-deferred expressions:
 
```py
t.mutate(
  s.across(
    s.all(),
    ibis.literal(_.get_name())
  )
)
```

**Comment by cpcloud** [comment]
Nah, `ibis.literal` isn't deferrable either, and I'm not sure we'll make it so, just yet. Need to poke around a bit.

**Comment by ianmcook** [comment]
Gotcha. Ultimately it's pretty easy to just use lambdas here, so I don't think it's worth a big effort to make this work.

Especially since you can just stick `lambda _: ` before it and change nothing else to make it work.
