### ISSUE TITLE
ENH: Support dialect specific types for sqlalchemy based clients

### ISSUE THREAD

**Issue by mariusvniekerk** [ibis-project/ibis#992]
Most sqlalchemy dialects support an additional set of types that can be used.

For example

```python
sqlalchemy.dialects.postgres.UUID
```

We should probably move some of the pieces around converting sqlalchemy metadata into a dialect specific subclass instead of having it all in `ibis.sql.alchemy`

**Comment by cpcloud** [comment]
Interesting. I'm curious how you might expect to use such a thing. Are you envisioning something like a bridge between ibis types and sqlalchemy types that allows you to easily wrap dialect specific types?

I've been eyeing this library for inspiration: http://sqlalchemy-utils.readthedocs.io

**Comment by mariusvniekerk** [comment]
yeah that looks like a good candidate.

**Comment by cpcloud** [comment]
If the type is missing, we'll add it to the next release (and any after that). Let us know if there's still something missing.
