### ISSUE TITLE
bug: incorrect parenthesization when mixing binary operators named expressions

### ISSUE THREAD

**Issue by chelsea-lin** [ibis-project/ibis#9975]
### What happened?

The `parenthesize_inputs` function is designed to improve SQL generation by adding parentheses for certain operators. It functions correctly in scenarios like this:
```
t = bq.table("bigframes-dev.ibis_gbq_testing.functional_alltypes")
f1 = t.int_col + t.int_col
ibis.to_sql(f1 * t.int_col, dialect="bigquery")
``` 
This produces the expected SQL output:
```
SELECT
  (
    `t0`.`int_col` + `t0`.`int_col`
  ) * `t0`.`int_col` AS `Multiply_Add_int_col_int_col_int_col`
FROM `bigframes-dev`.`ibis_gbq_testing`.`functional_alltypes` AS `t0`
```

However, the functionality breaks down when column aliases are introduced:
```
bq = ibis.bigquery.connect(project_id="bigframes-dev")
t = bq.table("bigframes-dev.ibis_gbq_testing.functional_alltypes")
f1 = t.int_col + t.int_col
ibis.to_sql(f1.name("col1") * t.int_col.name("col2"), dialect="bigquery")
```
This generates the following incorrect SQL:
```
SELECT
  `t0`.`int_col` + `t0`.`int_col` * `t0`.`int_col` AS `Multiply_col1_col2`
FROM `bigframes-dev`.`ibis_gbq_testing`.`functional_alltypes` AS `t0`
```

### What version of ibis are you using?

9.2.0

### What backend(s) are you using, if any?

BigQuery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Thanks for opening this, this is indeed a bug. This only shows up for named columns (so if you drop the `.name("col1")` the bug goes away). Named columns don't really make sense out of a projection (e.g. an arg to a `.select(...)`), so if possible I'd suggest avoiding calling it in other contexts. That said, we shouldn't accidentally be generating semantically different SQL, looking into a fix now.

**Comment by chelsea-lin** [comment]
One way to fix this might be to treat `Alias` operations as a special case. Here's an example code snippet for how we could implement that. What are your thoughts on this approach?

```
    @classmethod
    def _add_parens(cls, op, sg_expr):
        if isinstance(op, cls.NEEDS_PARENS) or (
            isinstance(op, ops.Alias) and isinstance(op.arg, cls.NEEDS_PARENS)
        ):
            return sge.paren(sg_expr, copy=False)
        return sg_expr
```

**Comment by cpcloud** [comment]
That code was removed in #10007, so the approach will have to do something else.
