### ISSUE TITLE
feat: un-deprecate Struct.destructure()

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#9977]
### Is your feature request related to a problem?

It was mentioned as the goal in [this comment](https://github.com/ibis-project/ibis/pull/8917#issuecomment-2077786221), and implemented in https://github.com/ibis-project/ibis/pull/9824.

However, the suggested workarounds of Struct.lift() and Struct.unpack() do not work for my use case of

```python
people = ibis.table({"phones": "array<struct<number: string, kind: str>>"})
people_longer = people.mutate(people.phones.unnest().destructure())
```

Is there a way to accomplish the above using other ibis APIs (without too much boilerplate?)

If we want to reduce duplication, could we instead remove Table.unpack? That is pretty easily spelled with `table.mutate(*table.struct_col.destructure())`. unpack also doesn't support on-the-fly modifications such as `table.mutate(*table.struct_col.fill_null({"default": "val"}).destructure())`.

Was there another motivation for removing .destructure() that I'm missing?

### Describe the solution you'd like

keep Struct.destructure, possibly deprecate Table.unpack()

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
What's wrong with this?

```python
people = ibis.table({"phones": "array<struct<number: string, kind: str>>"})
people_longer = people.mutate(splatted=_.phones.unnest()).unpack("splatted")
```

We might be able to make `unpack` more flexible in its input so you could write:

```python
people.unpack(_.phones.unnest())
```

`destructure` doesn't fit in with anything else in Ibis's API, it doesn't return an expression, so you can't really combine it anything except `select` or `mutate`; `unpack` and `lift` on the other hand return `Table` expressions.

**Comment by NickCrews** [comment]
> destructure doesn't fit in with anything else in Ibis's API

There is also Table.bind(), which I also use a decent amount, which also returns tuple[Value]. I'm dealing with unknown table schemas ("this table has columns street1, but it may not have street2", or "all the columns may or may not be prefixed with address_, eg address_street1") so I rely on these "metaprogramming" utils of ibis a decent bit. I bet this is fairly rare among ibis users though.

> What's wrong with this?

That would work! It is a bit annoying, since I would need to be a bit more careful with that intermediate assignment (but still quite workable):

```python
people.mutate(__column_i_hope_doesnt_collide=_.phones.unnest()).unpack("__column_i_hope_doesnt_collide").drop("__column_i_hope_doesnt_collide"
```

I guess  `struct.destructure()`  is simply `def destructure(struct) : return [struct[field] for field in struct.names]`,
so I can get back to `people.mutate(*destructure(people.phones.unnest()))` if I really want. Just the extra layer of parens is harder to read, I prefer the chaining API.

I grepped through my codebase and there is this slightly more complex use I have:

```python
people.mutate(
            *[
                c.name("job__" + c.get_name())
                for c in people.jobs.unnest().destructure()
            ]
        ).drop("jobs")
```

I think this would best be replicated as

```python
people.mutate(
        *[
                field.name("job__" + c.get_name())
                for field in destructure(people.jobs.unnest())
            ]
        ).drop("jobs")
```
which isn't that bad.

re unpack, I have never really liked that because it is a Struct-specific function that lives on a Table. There aren't methods for any other specific dtype on Table except for .unnest(), but that seems much more necessary since it is a cardinality-changing operation.

My ideal dream world would be:
- Struct.destructure() remains, which allows for...
- Struct.lift() is removed, it is spelled as `ibis.table(*struct.destructure())`, but this isn't possible unless we add support for passing ibis Values into ibis.table().
- Table.unpack() is removed, it is spelled as `t.mutate(*struct.destructure())`

I think this API is more composable, simple (1 method instead of 3!), and easier to understand (fewer atomic building blocks to work with)

**Comment by cpcloud** [comment]
I think we'll keep this deprecated, thanks for the feedback!
