### ISSUE TITLE
bug: interactive repr of URLs is weird on vscode

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#9980]
### What happened?

This isn't a huge deal, but a little annoying. This might be an upstream issue with rich, since it only is present on vscode's jupyter notebooks, not in vanilla ipython. Feel free to close this out if so, but maybe we are using rich incorrectly.

```python
import ibis
ibis.options.interactive = True

ibis.memtable(
    {
        "url": ["https://ibis-project.org/reference/expression-strings#ibis.expr.types.strings.StringValue.as_timestamp"]
    }
)
```

<img width="1076" alt="image" src="https://github.com/user-attachments/assets/bdf7d6f2-0a07-40cb-9e26-a641f5cd88d9">

### What version of ibis are you using?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for the report @NickCrews -- this works fine on IPython and Python, so I think this can be reported upstream to VSCode, since they seem to not be handling escape codes correctly.

**Comment by ncclementi** [comment]
@NickCrews just for the record, I run this also on VScode and I don't see this issue, screenshot for reference: 



![Image](https://github.com/user-attachments/assets/1e953aa7-ddd4-487c-9792-6a7b8002d9da)

**Comment by NickCrews** [comment]
Thank you both! Sounds good, sounds like a vscode issue.
