### ISSUE TITLE
GPU-Accelerated Backend

### ISSUE THREAD

**Issue by adamamer20** [ibis-project/ibis#9986]
### Which new backend would you like to see in Ibis?

I think it would be useful to have a GPU-Accelerated backend for operations on big DFs. [In this paper](https://arxiv.org/html/2406.13831v1) they tested duckdb againts other GPU-Accelerated databases and the performance difference is significant. Since ibis used to support pandas, [RAPIDS cuDF](https://github.com/rapidsai/cudf) would be an obvious choice as it probably wouldn't need too much refactoring.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
hi @adamamer20, thanks for opening this issue! apologies for the slow reply

you are right that with the pandas backend, you could use cuDF (and in theory other pandas-API compatible tools) -- this was shown here: https://voltrondata.com/blog/ibis-cudf-pandas

while supporting GPU-based execution engines is important to us, the pandas backend with Ibis (and pandas API in general) leaves a ton of performance on the table, largely negating the purpose of using hardware acceleration. the pandas API assumes all data can fit in memory and single-threaded execution

Ibis is an independently governed open source project, with its main sponsor being [Voltron Data](https://voltrondata.com/about) -- BlazingSQL (mentioned in the paper you link) was effectively merged (idk the exact corporate language here) into Voltron Data: https://voltrondata.com/news/fundinglaunch. a lot of the founders and engineers at Voltron Data that many of the Ibis contributors work with were largely responsible for RAPIDS and cuDF

separately, Polars is working with the RAPIDS team at NVIDIA to bring a new version of GPU execution that presumably improves on the pandas API version: https://pola.rs/posts/polars-on-gpu/. our tentative plan is to leverage this via the Polars backend for Ibis once it becomes available for single-node NVIDIA GPU execution

so our general thinking on this is:

- a pandas-API GPU backend isn't performant and not worth keeping our pandas backend around for
- Polars is adding GPU support Ibis gets "for free", covering single-node GPU query engine
- Ibis already supports a distributed GPU query engine with Voltron Data's Theseus engine

**Comment by adamamer20** [comment]
ehi @lostmygithubaccount, thanks for the detailed response! In my tests, pandas-cudf was also slower than eager polars, glad to hear it wasn't due to my implementation. I hadn't heard about Theseus, that looks promising. From what I understand it is not publicly available yet, right? I would keep the issue open until RAPIDS polars comes out or Theseus is a supported backend, but you can close it if you'd like (since it's not dependent on ibis itself).

**Comment by lostmygithubaccount** [comment]
yep, Theseus is not public (and probably won't be anytime soon) -- the general thinking is these modern single-node OLAP engines like DuckDB, DataFusion, and eventually Polars (once it implements its new "streaming" engine that works like the other two) are sufficient for 90-99% of data use cases, as they allow you to scale up to ~10TB size queries

it's unclear if single-node GPU w/ current tooling would be of much use in real world scenarios. we'll keep an eye on developments with Polars and look to add via the Polars backend if it's compelling 

I'll close this out because there's nothing to do immediately, just waiting and watching. Ibis already does support Theseus (the repo for that backend is private, though could be made public eventually)

**Comment by adamamer20** [comment]
Wanted to leave a note that Polars GPU engine has just been released in open beta

https://pola.rs/posts/gpu-engine-release/

**Comment by lostmygithubaccount** [comment]
yep! in theory this should "just work" through the Ibis backend already (we might need to bump the supported version of Polars or something), though I don't have a NVIDIA GPU readily available to try it out

**Comment by lostmygithubaccount** [comment]
I believe this will allow you to use it: https://github.com/ibis-project/ibis/pull/10151
