### ISSUE TITLE
docs: Exception stack traces on the "Datatypes and Datashapes" page

### ISSUE THREAD

**Issue by chrispy-snps** [ibis-project/ibis#9990]
### Please describe the issue

On the "Datatypes and Datashapes" page, there are some exception stack traces in the example results:

https://ibis-project.org/concepts/datatypes

I did not check other documentation pages for similar exceptions; that might be worth a look, if there's a programmatic way to do it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @chrispy-snps -- thanks for raising this!

That exception is included there by design, to show that you cannot arbitrarily combine columns from two separate relations without first joining them.

The exception is _so_ long, that I think we might benefit from not actually executing the failing cell, but sort of "faking" it and only showing the relevant portion of the traceback to improve readability.

**Comment by chrispy-snps** [comment]
Thanks @gforsyth!

Oops, I did not realize it was included by design - I was quickly scrolling through to look for something else, and the length threw me off. In our product's documentation, I do typically abstract away non-relevant parts of documented traced with `...` to focus on the relevant bits of the trace. I wonder if there's a way in your doc framework to automatically post-process traces to the last *N* levels?

**Comment by lostmygithubaccount** [comment]
automatically post-processing is probably possible, but for now we can at least just fake this one's output

**Comment by cpcloud** [comment]
It seems like we should understand why we're showing the exception three times:

We're showing:

1. The `rich` styled one
2. The IPython short styled one
3. The IPython full traceback

Not all of our docstrings that show exceptions have this problem, so we should understand what's happening before hacking around it.

**Comment by cpcloud** [comment]
For example, the [`Table.pivot_longer` docstring](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.pivot_longer) shows some intentional exceptions, and the traceback is shown only once (in the IPython style).

**Comment by cpcloud** [comment]
It's probably because we're calling `console.print_exception()` and we almost certainly shouldn't be.

**Comment by cpcloud** [comment]
The second repr is from `_repr_mimebundle_`.

**Comment by chrispy-snps** [comment]
Thank you everyone!
